### ISSUE TITLE
Bug: Unable to view Page 2 of Jobs

### ISSUE THREAD

**Issue by Parasdeepkohli** [MISP/MISP#10004]
### Actual behavior

Opening page of the jobs page returns a 500 error. 

### Expected behavior

The page opens and shows page 2 of all default jobs

### Steps to reproduce

Just try to open page 2 of the default jobs index

### Version

2.4.198

### Operating System

Ubuntu LTS

### Operating System version

18.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
2024-10-24 13:56:09 Error: [TypeError] Argument 1 passed to BackgroundJob::__construct() must be of the type array, string given, called in /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php on line 345
Request URL: /jobs/index/default/page:2
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
#1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
#2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
#3 [internal function]: JobsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trizzosk** [comment]
I am adding this issue on Ubuntu 20.04 as well. Definitely not related to OS version. Previously I was on 2.4.195 and had no issues.

**Comment by Q-Feeds** [comment]
Same problem here

**Comment by righel** [comment]
Check https://github.com/MISP/MISP/issues/10017#issuecomment-2487943103

**Comment by simillo01** [comment]
Hi, for me [jhuntwork comment](https://github.com/MISP/MISP/issues/10017#issuecomment-2459680001) in this discussion worked.
Using Ubuntu 24.04.1 LTS and MISP v2.5.2

**Comment by Parasdeepkohli** [comment]
Issue resolved with  @righel's sugested fix
