### ISSUE TITLE
Support: Freetext Import - Not Allowed

### ISSUE THREAD

**Issue by pesquisa1234** [MISP/MISP#10012]
### Support Questions

I can't use the freetext import in events, I can't populate from a lot of attributes in freeext, here an example:
It happend after I updated to versions 2.5 

![image](https://github.com/user-attachments/assets/f24957d2-b71c-4e04-ba56-f9ecca7e11dd)

### MISP version

v2.5.1 (5c4e205f2a224227123833ccbd46d040a05cd66c)

### Operating System

Ubuntu Server

### Operating System version

22.04

### PHP version

latest

### Browser

Edge and Chrome

### Relevant log output

```shell
2024-10-28 17:19:10 Warning: Warning (2): Undefined array key "MispAttribute" in [/var/www/MISP/app/Controller/EventsController.php, line 4224]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 232
EventsController::saveFreeText() - APP/Controller/EventsController.php, line 4224
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 500
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 107

2024-10-28 17:19:10 Warning: Warning (2): Trying to access array offset on value of type null in [/var/www/MISP/app/Controller/EventsController.php, line 4226]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 232
EventsController::saveFreeText() - APP/Controller/EventsController.php, line 4226
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 500
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 107

2024-10-28 17:19:10 Error: [HttpException] Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.
Request URL: /events/saveFreeText/1362
Stack Trace:
#0 /var/www/MISP/app/Controller/EventsController.php(4226): AppController->_jsonDecode()
#1 [internal function]: EventsController->saveFreeText()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#5 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#6 {main}
2024-10-28 17:19:15 Error: Blackhole exception when accessing /events/saveFreeText/1362 (isRest: 0, action: saveFreeText, unlockedActions: ["viewEventAttributes"]): CSRF token mismatch
2024-10-28 17:19:15 Error: [BadRequestException] The request has been black-holed
Request URL: /events/saveFreeText/1362
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(688): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#10 {main}
2024-10-28 17:27:54 Error: Blackhole exception when accessing /events/saveFreeText/1362 (isRest: 0, action: saveFreeText, unlockedActions: ["viewEventAttributes"]): CSRF token mismatch
2024-10-28 17:27:54 Error: [BadRequestException] The request has been black-holed
Request URL: /events/saveFreeText/1362
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(688): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
This has already been fixed, please pull in the latest update for the 2.5 branch.

**Comment by iglocska** [comment]
![image](https://github.com/user-attachments/assets/7b813046-2b16-4464-ab2b-590f6952c36d)

**Comment by pesquisa1234** [comment]
@iglocska I am with the latest, take a look:

![image](https://github.com/user-attachments/assets/da56aef6-9ba3-44c1-a445-7f9dd0006c3f)
![image](https://github.com/user-attachments/assets/3dfc2c1f-43ee-46da-950b-5d3fc577efa3)


I did yesterday:

docker compose pull
docker compose up -d

Am I missing something?

**Comment by tomking2** [comment]
Given you are using docker, you'll be pulling the latest tagged release, `v2.5.1` instead of the lastest code version. I'm pretty sure @iglocska's fixes came after this release, so you will likely need to wait until `v2.5.2` is available (which should be in a week or so I expect)

**Comment by iglocska** [comment]
This should be fixed in the latest release but please open a new issue if it isn't!
