### ISSUE TITLE
Support: misp-modules.service Issue after upgrading to 2.5.1 

### ISSUE THREAD

**Issue by xali20** [MISP/MISP#10016]
### Support Questions

Upgraded to MISP 2.5.1 from 2.4.199
upgrade went smoothly. No errors 
Web GUI Accessible as normal.
Server settings and maintenance showed no major issues apart from the following in Module System:

Enrichment module system…curl error 7 'Couldn't connect to server': Failed to connect to 127.0.0.1 port 6666 after 0 ms: Couldn't connect to server
Import module system…curl error 7 'Couldn't connect to server': Failed to connect to 127.0.0.1 port 6666 after 0 ms: Couldn't connect to server
Export module system…curl error 7 'Couldn't connect to server': Failed to connect to 127.0.0.1 port 6666 after 0 ms: Couldn't connect to server

from the workflow modules tab the following error is given 
`Make sure the [setting](/servers/serverSettings/Plugin) Plugin.Action_services_enable is enabled and the action service is reachable.`

The following is set: 
Plugin.Action_services_enable | true

service is not reachable.

Issue was noticed after workflow Job failed. with the following error from prio worker (healthy): 

```
2024-10-30 09:18:53 Error: Failed to query module Enrichment
[SocketException] curl error 7 'Couldn't connect to server': Failed to connect to 127.0.0.1 port 6666 after 0 ms: Couldn't connect to server
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(100): CurlClient->internalRequest()
#1 /var/www/MISP/app/Model/Module.php(329): CurlClient->post()
#2 /var/www/MISP/app/Model/Module.php(287): Module->sendRequest()
#3 /var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php(131): Module->queryModuleServer()
#4 /var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php(61): WorkflowBaseModule->render_jinja_template()
#5 /var/www/MISP/app/Model/WorkflowModules/action/Module_send_mail.php(66): WorkflowBaseModule->getParamsWithValues()
#6 /var/www/MISP/app/Model/Workflow.php(703): Module_send_mail->exec()
#7 /var/www/MISP/app/Model/Workflow.php(624): Workflow->executeNode()
#8 /var/www/MISP/app/Console/Command/WorkflowShell.php(56): Workflow->walkGraph()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): WorkflowShell->walkGraph()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#12 /var/www/MISP/app/Console/cake.php(47): ShellDispatcher::run()
#13 {main}
Warning Error: Trying to access array offset on false in [/var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php, line 135]

2024-10-30 09:18:53 Warning: Trying to access array offset on false in [/var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php, line 135]
Warning Error: Trying to access array offset on null in [/var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php, line 135]

2024-10-30 09:18:53 Warning: Trying to access array offset on null in [/var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php, line 135]
Warning Error: Trying to access array offset on null in [/var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php, line 135]

2024-10-30 09:18:53 Warning: Trying to access array offset on null in [/var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php, line 135]
Warning Error: Trying to access array offset on null in [/var/www/MISP/app/Model/WorkflowModules/WorkflowBaseModule.php, line 135]

```
Checked to see if  misp-modules is running correctly. Active shows as Failed with the following output. 

```
× misp-modules.service - System-wide instance of the MISP Modules
     Loaded: loaded (/etc/systemd/system/misp-modules.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-10-29 12:28:10 CET; 23h ago
   Duration: 396ms
    Process: 1361 ExecStart=/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 (code=exited, status=1/FAILURE)
   Main PID: 1361 (code=exited, status=1/FAILURE)
        CPU: 51ms

Oct 29 12:28:10 TEST-Misp systemd[1]: Started misp-modules.service - System-wide instance of the MISP Modules.
Oct 29 12:28:10 TEST-Misp misp-modules[1361]: Traceback (most recent call last):
Oct 29 12:28:10 TEST-Misp misp-modules[1361]:   File "/var/www/MISP/venv/bin/misp-modules", line 5, in <module>
Oct 29 12:28:10 TEST-Misp misp-modules[1361]:     from misp_modules import main
Oct 29 12:28:10 TEST-Misp misp-modules[1361]: ModuleNotFoundError: No module named 'misp_modules'
Oct 29 12:28:10 TEST-Misp systemd[1]: misp-modules.service: Main process exited, code=exited, status=1/FAILURE
Oct 29 12:28:10 TEST-Misp systemd[1]: misp-modules.service: Failed with result 'exit-code'.
```

Any assistance would be appreciated. 

### MISP version

2.5.1

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8.3

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thetechhouse** [comment]
same issue here.

**Comment by diaa-abushaqra** [comment]
same issue here.

**Comment by xali20** [comment]
> same issue here.
> same issue here.

I managed to solve the issue by re installing misp modules in the virtual environment. 

**Activating the virtual environment:** 
`source /var/www/MISP/venv/bin/activate`

**Check if misp-modules are installed**
`pip show misp-modules`

**Installing misp-modules if not found**
`/var/www/MISP/venv/bin/pip install misp-modules`

**Restarting the service**
`sudo systemctl restart misp-modules`

**Checking status**
`sudo systemctl status misp-modules`

After performing this through the Diagnostics tab from Server Settings & Maintenance, The Module System showed 'OK' and modules were working. no errors.
