### ISSUE TITLE
Bug: Viewing Job in Administration throwing 500 ERROR

### ISSUE THREAD

**Issue by trizzosk** [MISP/MISP#10017]
### Actual behavior

Showing Jobs overview throwing HTTP 500 error:
```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.
```

In `/var/www/MISP/app/tmp/logs/error.log` I see following error:

```
2024-10-30 13:10:23 Error: [TypeError] Argument 1 passed to BackgroundJob::__construct() must be of the type array, string given, called in /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php on line 345
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
#1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
#2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
#3 [internal function]: JobsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(105): Dispatcher->dispatch()
#8 {main}
```

### Expected behavior

Showing Jobs overview as previously (2.4.198).

### Steps to reproduce

Just opening Jobs overview.

### Version

2.9.199

### Operating System

Ubuntu

### Operating System version

20.04.6 LTS (Focal Fossa)

### PHP version

PHP 7.4.3-4ubuntu2.24 (cli) (built: Sep 30 2024 18:16:20) ( NTS )

### Browser

Chromium

### Browser version

130.0.6723.69 (Official Build) built on Debian

### Relevant log output

```shell
2024-10-30 13:10:23 Error: [TypeError] Argument 1 passed to BackgroundJob::__construct() must be of the type array, string given, called in /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php on line 345
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
#1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
#2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
#3 [internal function]: JobsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(105): Dispatcher->dispatch()
#8 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robert1993** [comment]
Same issue

**Comment by Q-Feeds** [comment]
After upgrade to 2.5.1. same still issue. Tried flushing caches and redis already, unfortunately no change:

<details><summary>Details</summary>
<p>
2024-11-04 15:21:55 Error: [TypeError] BackgroundJob::__construct(): Argument #1 ($properties) must be of type array, string given, called in /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php on line 345
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
#1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
#2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
#3 [internal function]: JobsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#8 {main}
</p>
</details>

**Comment by Lexati** [comment]
Same issue yet.

**Comment by jhuntwork** [comment]
Made this change locally and it seems to have helped

```diff
diff --git a/app/Lib/Tools/BackgroundJobsTool.php b/app/Lib/Tools/BackgroundJobsTool.php
index f73c4239f..36be36206 100644
--- a/app/Lib/Tools/BackgroundJobsTool.php
+++ b/app/Lib/Tools/BackgroundJobsTool.php
@@ -342,6 +342,7 @@ class BackgroundJobsTool
         if ($rawJob instanceof BackgroundJob) {
             return $rawJob;
         } else if ($rawJob) {
+            $rawJob = is_array($rawJob) ? $rawJob : array($rawJob);
             return new BackgroundJob($rawJob);
         }

```

**Comment by trizzosk** [comment]
Since I do not have a spare instance to test it - can anybody to confirm this works? @jhuntwork Any idea to incorporate this PR and push to 2.4.199 version (or .200 :) )?

Thx.

**Comment by jhuntwork** [comment]
It works from the standpoint of addressing the cause of the crash, it ensures that the data passed to the BackgroundJob constructor is always an array. I can confirm that on my instance I no longer see the 500 errors.

I didn't make a PR up to now because I think there's probably a deeper issue that needs fixed somewhere. It's not clear to me why $rawJob wouldn't be an array before getting to that point. This just forces the right data structure.

**Comment by trizzosk** [comment]
Since I was really struggling with this I decided that I applied this fix today. It really helped to solve the issue, for now. Anyway I think that @jhuntwork adjustment is just a temporary workaround.... that's well appreciated

**Comment by righel** [comment]
Hello,
Please go to `Administration` -> `Server Settings & Maintenance` -> `SimpleBackgroundJobs` and check the setting `SimpleBackgroundJobs.redis_serializer` is set to `JSON` and not `igbinary`.
See below:
![image](https://github.com/user-attachments/assets/90ee7e46-c24b-4c28-8ebe-b8e5aae96e80)

If it was set to `igbinary`, after changing it to `JSON` to to `/jobs/index` and purge all job entries:
![image](https://github.com/user-attachments/assets/c3573695-5878-4467-a928-baff1c22859e)

**Comment by iglocska** [comment]
Woah, nice catch @righel. I wonder how that got switched to igbinary, will change the upgrade/install scripts to make sure it's forced to JSON.

**Comment by Q-Feeds** [comment]
I've had the serializer on JSON all the time but still getting the error when switching pages. running release v2.5.2 (39a7a54f7c93b51fdb28f7c2bda499d8f5b1667c)

**Comment by righel** [comment]
> I've had the serializer on JSON all the time but still getting the error when switching pages. running release v2.5.2 ([39a7a54](https://github.com/MISP/MISP/commit/39a7a54f7c93b51fdb28f7c2bda499d8f5b1667c))

Can you purge all your job history and try to reproduce the issue with a minimal scenario of maybe 1 job that causes this issue? and if so share the value of the redis key.

Should be something like this:
```
# redis-cli
127.0.0.1:6379> select 1
OK
127.0.0.1:6379[1]> keys *
1) "background_jobs:job_status:e951c44e-9c3b-4a1f-bbbb-b58d1ca0f7b4"
127.0.0.1:6379[1]> get "background_jobs:job_status:e951c44e-9c3b-4a1f-bbbb-b58d1ca0f7b4"
"\x00\x00\x00\x02\x17\rBackgroundJob\x14\t\x11\x11\x00BackgroundJob\x00id\x11$e951c44e-9c3b-4a1f-bbbb-b58d1ca0f7b4\x11\x16\x00BackgroundJob\x00command\x11\x05event\x11\x13\x00BackgroundJob\x00args\x14\x05\x06\x00\x11\apublish\x06\x01\x11\x011\x06\x02\x00\x06\x03\x06\x02\x06\x04\x0e\a\x11\x18\x00BackgroundJob\x00createdAt\ng=\xed\\\x11\x18\x00BackgroundJob\x00updatedAt\ng=\xed\\\x11\x15\x00BackgroundJob\x00status\x06\x04\x11\x15\x00BackgroundJob\x00output\r\x11\x14\x00BackgroundJob\x00error\r\x11\x17\x00BackgroundJob\x00metadata\x14\x00"
127.0.0.1:6379[1]> 
```

**Comment by Q-Feeds** [comment]
I've purged all jobs first via GUI. Then via Redis-cli i've noticed that it printed 200000+ jobs. Did a FLUSHALL within redis-cli. Triggered some jobs and now this is my output: 

`127.0.0.1:6379[1]> keys *
 1) "background_jobs:job_status:3468ea2a-a34f-413d-9756-ffac8ac91f45"
 2) "background_jobs:job_status:bffdb941-3d5b-4bda-8e05-ebc17c3c5ae4"
 3) "background_jobs:job_status:cee80379-a207-4c92-b1c1-2b70b6e7f197"
 4) "background_jobs:job_status:6ef9e25b-f308-4089-874e-3cfb6de7bd52"
 5) "background_jobs:job_status:c874288e-0cd0-4748-9efd-9a2103a3cfb2"
 6) "background_jobs:job_status:d0631631-6711-42bd-b81d-d1704050d21f"
 7) "background_jobs:job_status:250ce68a-46db-419d-94d1-12d617231431"
 8) "background_jobs:job_status:fccf032a-681a-4649-977a-73832bc67d40"
 9) "background_jobs:job_status:2016b18d-83d0-4ada-a8a4-66da22eec7c2"
10) "background_jobs:job_status:ad184df9-a3d8-404b-a8c9-195543030deb"
11) "background_jobs:job_status:a9d99900-38e6-41d9-ae9c-0908aeecf907"
12) "background_jobs:job_status:fa270574-fd72-4146-a326-54520b756c07"
13) "background_jobs:job_status:69a7cb47-2c8c-4fc5-83f1-657d57e97b58"
14) "background_jobs:job_status:d8739af0-2418-4f4c-bf90-681a7403f8bc"
15) "background_jobs:job_status:8d9ec235-e596-44f2-a1ed-8d75cea3d3f4"
16) "background_jobs:job_status:a6e83306-f072-4b0a-aef0-41ceeeca25b6"
17) "background_jobs:job_status:3d74dbff-4de8-4e42-a440-82ff8d3d8c02"
18) "background_jobs:job_status:edf99331-105d-4319-8d70-e919fb208863"
19) "background_jobs:job_status:11b425fe-5532-4f35-9327-0c649c8b8aa5"
20) "background_jobs:job_status:20685994-5b87-418e-b160-8834e065bee4"
21) "background_jobs:job_status:ccc93bdf-d217-4f12-8a63-6dae057e6aed"
22) "background_jobs:job_status:3dc345bb-e87b-4cef-a2d8-d955b39c7b37"
23) "background_jobs:job_status:acae5d9c-4450-4b1a-98a4-68996f3d4f89"
24) "background_jobs:job_status:cad8ed10-4779-42a3-90ea-8815c91b60d5"
25) "background_jobs:job_status:16d1c14b-265a-47a6-906d-a46e04ef6fed"
26) "background_jobs:job_status:72945bcb-5ac6-4ed8-b740-0348cc061723"
27) "background_jobs:job_status:00709861-6760-4b59-86a5-31bbaf5b7dc5"
28) "background_jobs:job_status:f42cd075-73f0-47ba-960f-1b3b497ec7cd"
29) "background_jobs:job_status:5ba8fb9a-a362-4387-a2b7-d442848ba3df"
30) "background_jobs:job_status:29a8cab8-4c02-4dea-830c-763c797db3a3"
31) "background_jobs:job_status:23319637-ff58-468c-aa36-625acc1da1cc"
32) "background_jobs:job_status:73c5312a-7315-41bb-b2cf-f84e01d2a85a"
33) "background_jobs:job_status:9a78d49a-3e15-470c-9e34-6536f63f94d8"
34) "background_jobs:job_status:362e13c9-0a30-49a5-bf7c-387044ffe2a8"
35) "background_jobs:job_status:7fbc5fee-cc73-49bc-af55-1a8eaa7f95a8"
36) "background_jobs:job_status:fcbe90ab-1c03-41bb-88fc-fb1c89f06c12"
37) "background_jobs:job_status:0e349fc9-75d0-4e64-a541-9f93080315ce"
38) "background_jobs:job_status:d1942c23-1281-4ec8-8a8f-90a7adb557bc"
39) "background_jobs:job_status:6c331c7e-0a52-41df-ad31-ceed453b3429"
40) "background_jobs:job_status:c1f9a412-259a-4da7-85a1-22d405b40022"
41) "background_jobs:job_status:be3b8742-fe29-43ff-b152-e165c189a87e"
42) "background_jobs:job_status:42b2308b-9978-4e30-8feb-72107f2b624b"
43) "background_jobs:job_status:83b23a05-d2ba-4b47-bbc2-c0b2636f7866"
44) "background_jobs:job_status:78fe14e9-4f30-4cd9-89d1-bb8e92f2c507"
45) "background_jobs:job_status:f296c260-8d60-471d-a7fa-ba9ad5d0ec31"
46) "background_jobs:job_status:2d4195e9-5403-4555-a0d0-c24b13c74d26"
47) "background_jobs:job_status:9e34fc3c-e22d-45cb-a1dc-a3ad067450d1"`

Unfortunately the 500 error is still persistant.

**Comment by righel** [comment]
@Q-Feeds 
Try to trigger the least amount of jobs you need to reproduce the issue and please show me the contents of the keys stored in redis.

**Comment by Kaloszer** [comment]
> Hello, Please go to `Administration` -> `Server Settings & Maintenance` -> `SimpleBackgroundJobs` and check the setting `SimpleBackgroundJobs.redis_serializer` is set to `JSON` and not `igbinary`. See below: ![image](https://private-user-images.githubusercontent.com/1659902/388018759-90ee7e46-c24b-4c28-8ebe-b8e5aae96e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjI0NzcsIm5iZiI6MTczMzIyMjE3NywicGF0aCI6Ii8xNjU5OTAyLzM4ODAxODc1OS05MGVlN2U0Ni1jMjRiLTRjMjgtOGViZS1iOGU1YWFlOTZlODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMTAzNjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRlMDFlYzRiZTA2MzIzODUzMjg4YTliZWJiYmYxNzY0MGYwNmI4ZGI3MzEyODdjMjBjYWFiNTljZjVlNjNmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7QPoiE0vqCeT3T_qjwIHiBA9VuU3q1vgSH-8C6Vkgxs)
> 
> If it was set to `igbinary`, after changing it to `JSON` to to `/jobs/index` and purge all job entries: ![image](https://private-user-images.githubusercontent.com/1659902/388020883-c3573695-5878-4467-a928-baff1c22859e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjI0NzcsIm5iZiI6MTczMzIyMjE3NywicGF0aCI6Ii8xNjU5OTAyLzM4ODAyMDg4My1jMzU3MzY5NS01ODc4LTQ0NjctYTkyOC1iYWZmMWMyMjg1OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMTAzNjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI4NzY0MjI5YjNiNTJlOGFlMmE2Mzc4MzI3OWVjYjU2MTdiYTZlYzYyNTBhMWY4ZTk0ZGZlN2RlMTlmN2Q1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pVcUfOGSreQYMKli4ufNg4oUHJYtMJJBirk3cA7msLA)

Right, but you can't actually get into the jobs page in the first place to purge those jobs :D

**Comment by Q-Feeds** [comment]
> @Q-Feeds Try to trigger the least amount of jobs you need to reproduce the issue and please show me the contents of the keys stored in redis.

Could we come up with another debug proces? It's on a production environment so I can't stop these automations. In order to do so on a test environment it's very time intensive. If there's no other way I can do it but it takes time.

**Comment by simillo01** [comment]
Hi, Using Ubuntu 24.04.1 LTS and MISP v2.5.2, PHP 8.3 and this comment from @jhuntwork 

> Made this change locally and it seems to have helped
> 
> ```diff
> diff --git a/app/Lib/Tools/BackgroundJobsTool.php b/app/Lib/Tools/BackgroundJobsTool.php
> index f73c4239f..36be36206 100644
> --- a/app/Lib/Tools/BackgroundJobsTool.php
> +++ b/app/Lib/Tools/BackgroundJobsTool.php
> @@ -342,6 +342,7 @@ class BackgroundJobsTool
>          if ($rawJob instanceof BackgroundJob) {
>              return $rawJob;
>          } else if ($rawJob) {
> +            $rawJob = is_array($rawJob) ? $rawJob : array($rawJob);
>              return new BackgroundJob($rawJob);
>          }
> ```

worked perfectly

**Comment by sebdooris** [comment]
Same issue with MISP 2.5.11 on fresh install Ubuntu 24.04.2 LTS.  The "/var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php" workaround worked. 

`root@SERVER:/home/user# tail -f  /var/www/MISP/app/tmp/logs/error.log
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
#1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
#2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
#3 [internal function]: JobsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#8 {main}
`

**Comment by jeremiah-RENISAC** [comment]
Chiming in with still the same error here on MISP 2.5.21 when trying to view the jobs page. This is on a recently recent fresh install of 2.5.21.

```
[misp-logger] 2025-09-23 13:15:14 Error: [TypeError] BackgroundJob::__construct(): Argument #1 ($properties) must be of type array, string given, called in /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php on line 345
[misp-logger] Request URL: /jobs/index
[misp-logger] User <user> (User #2) @ <ip>
[misp-logger] Error in: /var/www/MISP/app/Lib/Tools/BackgroundJobs/BackgroundJob.php, Line: 54
[misp-logger] Stack Trace:
[misp-logger] #0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
[misp-logger] #1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
[misp-logger] #2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
[misp-logger] #3 [internal function]: JobsController->index()
[misp-logger] #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
[misp-logger] #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
[misp-logger] #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
[misp-logger] #7 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
[misp-logger] #8 {main}
```

The workaround above is functional in getting me back to the jobs page, though it does write a new warning:
```
[misp-logger] 2025-09-23 13:24:22 Warning: Warning (2): Undefined array key "id" in [/var/www/MISP/app/Lib/Tools/BackgroundJobs/BackgroundJob.php, line 56]
[misp-logger] Trace:
[misp-logger] ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261
[misp-logger] BackgroundJob::__construct() - APP/Lib/Tools/BackgroundJobs/BackgroundJob.php, line 56
[misp-logger] BackgroundJobsTool::getJob() - APP/Lib/Tools/BackgroundJobsTool.php, line 346
[misp-logger] JobsController::__getJobStatus() - APP/Controller/JobsController.php, line 197
[misp-logger] JobsController::index() - APP/Controller/JobsController.php, line 43
[misp-logger] ReflectionMethod::invokeArgs() - [internal], line ??
[misp-logger] Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 500
[misp-logger] Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
[misp-logger] Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[misp-logger] [main] - APP/webroot/index.php, line 107
```

Was hoping I could reproduce the error, but after purging all jobs and repeating my last job, the jobs page loads fine, suggesting it's something that had been in there longer / from an automated task and I just hadn't noticed.

**Comment by ghost** [comment]
Hello,

Still issue...

Warning: Warning (2): Undefined variable $rawJobs in [/var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php, line 347]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261
Configure::{closure}() - APP/Config/core.php, line 61
BackgroundJobsTool::getJob() - APP/Lib/Tools/BackgroundJobsTool.php, line 347
JobsController::__getJobStatus() - APP/Controller/JobsController.php, line 197
JobsController::index() - APP/Controller/JobsController.php, line 43
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 500
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 107

Error: [TypeError] BackgroundJob::__construct(): Argument #1 ($properties) must be of type array, null given, called in /var/www/MISP/app/Lib/Tools/Backg
roundJobsTool.php on line 347
Request URL: /jobs/index
User X.X (User #52) @ 172.30.50.200
Error in: /var/www/MISP/app/Lib/Tools/BackgroundJobs/BackgroundJob.php, Line: 54
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(347): BackgroundJob->__construct()
#1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
#2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
#3 [internal function]: JobsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#8 {main}

**Comment by righel** [comment]
Which version of MISP are you running @AMI-NXV ?

**Comment by ghost** [comment]
@righel  v2.5.31

**Comment by righel** [comment]
Strange,
Warning: Warning (2): Undefined variable $rawJobs in [/var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php, line 347]

https://github.com/MISP/MISP/blob/2.5/app/Lib/Tools/BackgroundJobsTool.php#L347

There is no reference of $rawJobs on that line, have you made changes to that file? If not, could you share how your `getJob` function in the /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php file?

**Comment by ghost** [comment]
I adapted the PHP file as mentionned above from an other user:

`diff --git a/app/Lib/Tools/BackgroundJobsTool.php b/app/Lib/Tools/BackgroundJobsTool.php
index f73c4239f..36be36206 100644
--- a/app/Lib/Tools/BackgroundJobsTool.php
+++ b/app/Lib/Tools/BackgroundJobsTool.php
@@ -342,6 +342,7 @@ class BackgroundJobsTool
         if ($rawJob instanceof BackgroundJob) {
             return $rawJob;
         } else if ($rawJob) {
+            $rawJob = is_array($rawJob) ? $rawJob : array($rawJob);
             return new BackgroundJob($rawJob);
         }`

But the issue still persists

**Comment by righel** [comment]
I believe you made a typo because the error message says `$rawJob*s*` not `$rawJob`

**Comment by ghost** [comment]
Hello,

I reinstalled the whole MISP, on a Ubuntu, with official script (before it was docker image), everything went well but same, out of nowhere, after adding a simple feed:

2026-01-27 07:51:06 Error: [TypeError] BackgroundJob::__construct(): Argument #1 ($properties) must be of type array, string given, called in /var/www/MISP/app/Lib/Tools/Bac
kgroundJobsTool.php on line 345
Request URL: /jobs/index
User ami-nxv (User #4) @ 172.10.27.2
Error in: /var/www/MISP/app/Lib/Tools/BackgroundJobs/BackgroundJob.php, Line: 54
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
#1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
#2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
#3 [internal function]: JobsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#8 {main}

It was that feed: The Botvrij.eu Data

I even fine tuned the instance with the worker number, switched to the No ACL Engine.... but still
