### ISSUE TITLE
Support: Support for STIX and maec libraries

### ISSUE THREAD

**Issue by caiquebarqueta** [MISP/MISP#10026]
### Support Questions

I'm having trouble exporting in STIX format using integrated tools. Unfortunately, the libraries are installed and MISP doesn't recognize the installed libraries. I ran the STIX test script and no error was returned, and even so, it is still not recognized by the application.

### MISP version

2.5.1

### Operating System

Ubuntu 

### Operating System version

24.04.01

### PHP version

PHP 8.3.6

### Relevant log output

```shell
2024-11-06 06:12:58 Error: [JsonException] Syntax error
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/JsonTool.php(35): json_decode()
#1 /var/www/MISP/app/Lib/Export/StixExport.php(102): JsonTool::decode()
#2 /var/www/MISP/app/Model/Event.php(7561): StixExport->footer()
#3 /var/www/MISP/app/Controller/AppController.php(1434): Event->restSearch()
#4 [internal function]: AppController->restSearch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#9 {main}


/var/www/MISP/app/tmp/logs# pip list | grep stix
stix                   1.2.0.11
stix2                  3.0.1
stix2-patterns         2.0.0

/var/www/MISP/app/tmp/logs# pip list | grep maec
maec                   4.1.0.17
```

### Extra attachments

![image](https://github.com/user-attachments/assets/7f18aefa-4446-4606-89f6-cea6221587d3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
The python libraries should be installed in the python virtual environment that is specifically created for MISP during the install. 

Try this:
```bash
sudo -u www-data /var/www/MISP/venv/bin/pip install /var/www/MISP/app/files/scripts/misp-stix
```

**Comment by ViolatorDM** [comment]
@righel same issue for us. Libraries seem to be installed but not recognized or something is missing, but installed in the venv...
![image](https://github.com/user-attachments/assets/da394767-e4fe-4d47-8625-f66c81363b5c)

, but:
![image](https://github.com/user-attachments/assets/f4ecfd3a-a76e-4141-884f-a66bb2c2d316)

**Comment by makc14ek** [comment]
https://github.com/MISP/MISP/issues/10039#issuecomment-2485532629

**Comment by ViolatorDM** [comment]
@makc14ek you rock!

What you provided, seems to have fixed it...

I did everything as www-data using sudo -H -u www-data though.

![image](https://github.com/user-attachments/assets/f14b89f0-1c7b-4d9c-bd54-04c37cf8e9aa)

![image](https://github.com/user-attachments/assets/6b083014-d4b5-4195-95d3-c763bac65b0c)

After what I did, STIX 1 is working.

STIX 2 is still not working with an error:
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.
