### ISSUE TITLE
Bug: MISP 2.5 using remote database gives CakePHP error

### ISSUE THREAD

**Issue by jyrcija** [MISP/MISP#10037]
### Actual behavior

When attaching MISP to a remote database server CakePHP related error message is shown on the MISP login site:

![misperror](https://github.com/user-attachments/assets/733b75a9-c685-42ce-a815-584ed6541b5a)

With a local database the same installation works fine.
I have been using remote database servers with previous version of MIPS without errors with similar configs.

### Expected behavior

MISP login page without CakePHP error

### Steps to reproduce

MISP is installed on an EC2 instance and remote database is AWS RDS instance.

1. After a fresh MISP 2.5 installation migrate the local database to a remote MariaDB
mysqldump -h localhost -u misp -p misp > misp_db_new.sql
mysql -h <remove_host> -u misp -p misp < misp_db_new.sql (remember to create the misp user and misp database first)

2. Edit the host attribute in database.php file (and password attribute if not the same)
3. Try to access the MISP web page

### Version

2.5.1

### Operating System

Ubuntu

### Operating System version

24.04 (AWS AMI: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20240927)

### PHP version

8.3.6

### Browser

Edge

### Browser version

130.0.2849.68

### Relevant log output

```shell
error.log

2024-11-11 15:04:09 Error: [ParseError] syntax error, unexpected single-quoted string "database", expecting "]"
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(83): ConnectionManager::_init()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3660): ConnectionManager::getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1163): Model->setDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3687): Model->setSource()
#4 /var/www/MISP/app/Model/User.php(258): Model->getDataSource()
#5 [internal function]: User->__construct()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#7 /var/www/MISP/app/Controller/AppController.php(124): ClassRegistry::init()
#8 /var/www/MISP/app/Controller/UsersController.php(29): AppController->beforeFilter()
#9 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(687): BetterCakeEventManager->dispatch()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#14 {main}
2024-11-11 15:04:09 Warning: Warning (2): Undefined variable $debugMode in [/var/www/MISP/app/View/Elements/footer.ctp, line 1]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 232
include - APP/View/Elements/footer.ctp, line 1
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 80
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 973
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2024-11-11 15:04:09 Warning: Warning (2): Undefined variable $debugMode in [/var/www/MISP/app/View/Elements/footer.ctp, line 2]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 232
include - APP/View/Elements/footer.ctp, line 2
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 80
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 973
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2024-11-11 15:04:17 Error: [ParseError] syntax error, unexpected single-quoted string "database", expecting "]"
Request URL: /events/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(83): ConnectionManager::_init()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3660): ConnectionManager::getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1163): Model->setDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3687): Model->setSource()
#4 /var/www/MISP/app/Model/User.php(258): Model->getDataSource()
#5 [internal function]: User->__construct()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#7 /var/www/MISP/app/Controller/AppController.php(124): ClassRegistry::init()
#8 /var/www/MISP/app/Controller/EventsController.php(66): AppController->beforeFilter()
#9 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): EventsController->beforeFilter()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(687): BetterCakeEventManager->dispatch()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#14 {main}
```

### Extra attachments

database.php file

class DATABASE_CONFIG {

    public $default = [
#       'datasource' => 'Database/Mysql',
        'datasource' => 'Database/MysqlObserverExtended',
        'persistent' => false,
       'host' => '<remote host>',
#        'host' => 'localhost',
        'login' => 'misp',
        'port' => 3306,
       'password' => '<password>'
        'database' => 'misp',
        'prefix' => '',
        'encoding' => 'utf8',
        'flags' => [
            PDO::ATTR_STRINGIFY_FETCHES => true
        ]
        ];
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
You have a typo in your config:

```
class DATABASE_CONFIG {

    public $default = [
#       'datasource' => 'Database/Mysql',
        'datasource' => 'Database/MysqlObserverExtended',
        'persistent' => false,
       'host' => '<remote host>',
#        'host' => 'localhost',
        'login' => 'misp',
        'port' => 3306,
       // The following line needs to be ended with a comma:
       'password' => '<password>'
        'database' => 'misp',
        'prefix' => '',
        'encoding' => 'utf8',
        'flags' => [
            PDO::ATTR_STRINGIFY_FETCHES => true
        ]
        ];
}
```

**Comment by jyrcija** [comment]
Thanks! That was it. Damn, one really get blind to his own typos. And I triple-checked the configs before creating this support ticket.

**Comment by iglocska** [comment]
Don't worry about it, it happens more frequently than you'd thing. It's super easy to make a mistake and very hard to notice. Glad it's sorted :)
