### ISSUE TITLE
Bug: Unable to access MISP's web UI

### ISSUE THREAD

**Issue by Parasdeepkohli** [MISP/MISP#10046]
### Actual behavior

Receive an error message: An internal error has occured

### Expected behavior

Pass MISP's host name or IP to a browser and the web portal login should appear

### Steps to reproduce

Do a fresh install of MISP 2.5.1 on Ubuntu 24.04 server and try to access the Web portal using the hostname/IP

### Version

2.5.1

### Operating System

Ubuntu Server

### Operating System version

24.04

### PHP version

8.3

### Browser

Chrome

### Relevant log output

```shell
MISP error log:

2024-11-14 07:30:05 Warning: Warning (2): Undefined variable $debugMode in [/var/www/MISP/app/View/Elements/footer.ctp, line 2]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 232
include - APP/View/Elements/footer.ctp, line 2
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 80
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 973
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Oppenheim3r** [comment]
same issue

**Comment by mathurin68** [comment]
same here!

**Comment by righel** [comment]
Can you share the full error log? that warning would not cause an Internal Server Error.

**Comment by MrKenie** [comment]
same here !

**Comment by Parasdeepkohli** [comment]
Hi @righel 

You were right. Above this exception, the log file has the following error:

2024-11-29 11:26:29 Error: [MissingConnectionException] Database connection "MysqlObserverExtended" is missing, or could not be created.

Exception Attributes: array (

  'class' => 'MysqlObserverExtended',

  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',

  'enabled' => true,

)

Request URL: /

Stack Trace:

#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()

#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()

#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3660): ConnectionManager::getDataSource()

#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1163): Model->setDataSource()

#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3687): Model->setSource()

#5 /var/www/MISP/app/Model/User.php(258): Model->getDataSource()

#6 [internal function]: User->__construct()

#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()

#8 /var/www/MISP/app/Controller/AppController.php(124): ClassRegistry::init()

#9 /var/www/MISP/app/Controller/EventsController.php(66): AppController->beforeFilter()

#10 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): EventsController->beforeFilter()

#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(687): BetterCakeEventManager->dispatch()

#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()

#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()

#14 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()

#15 {main}

**Comment by alens** [comment]
same here, [MISP 2.5.8] still has the same error.

**Comment by chappi6** [comment]
> Hi [@righel](https://github.com/righel)
> 
> You were right. Above this exception, the log file has the following error:
> 
> 2024-11-29 11:26:29 Error: [MissingConnectionException] Database connection "MysqlObserverExtended" is missing, or could not be created.
> 
> Exception Attributes: array (
> 
>   'class' => 'MysqlObserverExtended',
> 
>   'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
> 
>   'enabled' => true,
> 
> )
> 
> Request URL: /
> 
> Stack Trace:
> 
> #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
> 
> [#1](https://github.com/MISP/MISP/issues/1) /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
> 
> [#2](https://github.com/MISP/MISP/issues/2) /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3660): ConnectionManager::getDataSource()
> 
> [#3](https://github.com/MISP/MISP/issues/3) /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1163): Model->setDataSource()
> 
> [#4](https://github.com/MISP/MISP/issues/4) /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3687): Model->setSource()
> 
> [#5](https://github.com/MISP/MISP/issues/5) /var/www/MISP/app/Model/User.php(258): Model->getDataSource()
> 
> [#6](https://github.com/MISP/MISP/issues/6) [internal function]: User->__construct()
> 
> [#7](https://github.com/MISP/MISP/issues/7) /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
> 
> [#8](https://github.com/MISP/MISP/issues/8) /var/www/MISP/app/Controller/AppController.php(124): ClassRegistry::init()
> 
> [#9](https://github.com/MISP/MISP/issues/9) /var/www/MISP/app/Controller/EventsController.php(66): AppController->beforeFilter()
> 
> [#10](https://github.com/MISP/MISP/issues/10) /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): EventsController->beforeFilter()
> 
> [#11](https://github.com/MISP/MISP/issues/11) /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(687): BetterCakeEventManager->dispatch()
> 
> [#12](https://github.com/MISP/MISP/issues/12) /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
> 
> [#13](https://github.com/MISP/MISP/issues/13) /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
> 
> [#14](https://github.com/MISP/MISP/issues/14) /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
> 
> [#15](https://github.com/MISP/MISP/issues/15) {main}

For me this error was fix by editing /var/www/MISP/app/Config/database.php 
replacing 
host => 'localhost'
with 
host => '127.0.01'

How that helps.
