### ISSUE TITLE
Bug: During upgrade misp to 2.5 get maria db error (Invalid datetime format)

### ISSUE THREAD

**Issue by RR19MR** [MISP/MISP#10054]
### Actual behavior

After upgrading from Ubuntu 20.04 to 22.04 and MISP from 2.4.198 to 2.5.2 and php from 7.4 to 8.1, get error related maria db ( invalid datetime format).  After upgrade server version was: 10.6.18-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04

Database update  from 10.6.18  to 11.4.4-MariaDB did not resolve the issue.

Logs below.

### Expected behavior

-

### Steps to reproduce

-

### Version

2.4.198

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.33

### Relevant log output

```shell
2024-11-20 09:38:53 Error: [PDOException] SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1732095533' for column `misp`.`logs`.`created` at row 1
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Log.php(277): Model->save()
#6 /var/www/MISP/app/Model/User.php(1340): Log->createLogEntry()
#7 /var/www/MISP/app/Plugin/ShibbAuth/Controller/Component/Auth/ApacheShibbAuthenticate.php(137): User->extralog()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(698): ApacheShibbAuthenticate->getUser()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
#10 /var/www/MISP/app/Controller/AppController.php(1317): AuthComponent->startup()
#11 /var/www/MISP/app/Controller/AppController.php(270): AppController->_loadAuthenticationPlugins()
#12 /var/www/MISP/app/Controller/UsersController.php(29): AppController->beforeFilter()
#13 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#17 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#18 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
How did you run the update, you were on 22.04 and it should only work on 24.04?... Or did you do it manually?

**Comment by RR19MR** [comment]
> How did you run the update, you were on 22.04 and it should only work on 24.04?... Or did you do it manually?
first upgrade ubuntu to 22.04, later upgrade MISP to 2.5.2 by git comands

**Comment by iglocska** [comment]
There's an upgrade process to be followed, just switching to the 2.5 branch will definitely not work. 

https://github.com/MISP/MISP/blob/2.5/INSTALL/UPGRADE.ubuntu2404.sh

**Comment by RR19MR** [comment]
Everything worked after the updates, but one day I got same error:
```
2025-01-03 08:17:41 Error: [PDOException] SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1735892261' for column `misp`.`logs`.`created` at row 1
Request URL: /events/edit/dc608d28-a388-49c2-b5f3-60fb53799043/metadata:1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1943): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1761): Model->_doSave()
#5 /var/www/MISP/app/Model/Log.php(322): Model->save()
#6 /var/www/MISP/app/Model/Event.php(4349): Log->createLogEntry()
#7 /var/www/MISP/app/Controller/EventsController.php(2854): Event->_edit()
#8 [internal function]: EventsController->edit()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
```

Do you know what solutions could be available? The solutions provided at https://github.com/MISP/MISP/issues/9019 does not helping.

MISP version: 2.5.4

Describe logs
--------------

```
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| title       | text         | YES  |     | NULL    |                |
| created     | datetime     | YES  |     | NULL    |                |
| model       | varchar(80)  | NO   |     | NULL    |                |
| model_id    | int(11)      | NO   |     | NULL    |                |
| action      | varchar(20)  | NO   |     | NULL    |                |
| user_id     | int(11)      | NO   |     | NULL    |                |
| change      | text         | YES  |     | NULL    |                |
| email       | varchar(255) | NO   |     |         |                |
| org         | varchar(255) | NO   |     |         |                |
| description | text         | YES  |     | NULL    |                |
| ip          | varchar(45)  | NO   |     |         |                |
+-------------+--------------+------+-----+---------+----------------+
```
