### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by Elevation5000** [MISP/MISP#10052]
### Support Questions

I inherited a non working MISP server. I am trying to troubleshoot issues in the logs. When going to the IP of the server i get.

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Download: [Server PGP public key](http://xx.xx.xx.xx/gpg.asc)
Powered by [MISP ](https://github.com/MISP/MISP)- 2024-11-19 20:21:21
Loading

### MISP version

Unsure because it doesn't load.

### Operating System

Oracle Linux Server

### Operating System version

8.10

### PHP version

7.4.33

### Browser

All

### Browser version

Latest

### Relevant log output

```shell
2024-11-19 20:21:21 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'root\'@\'localhost\'',
  'enabled' => true,                                                                                                    )                                                                                                                       Request URL: /servers/cspReport
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()                              #10 /var/www/MISP/app/Model/AppModel.php(114): Model->__construct()                                                     #11 /var/www/MISP/app/Model/User.php(255): AppModel->__construct()
#12 [internal function]: User->__construct()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
It sounds like your MISP is not configured correctly, edit `/var/www/MISP/app/Config/database.php` with the correct db credentials. Also, please don't use the root mysql user for MISP if possible.

**Comment by Elevation5000** [comment]
Is there a way to reset those if the previous Sys Admin doesn't know?

**Comment by iglocska** [comment]
I mean it's a matter of changing the permissions in your mysql/mariadb. As long as you can log in via the admin user into your mysql you should be able to just create a new user / change the password of the existing one.

https://docs.rackspace.com/docs/create-a-new-user-and-grant-permissions-in-mysql
