### ISSUE TITLE
Bug: The /galaxy_clusters/index/{galaxyId} API call does not work

### ISSUE THREAD

**Issue by adpaccent** [MISP/MISP#10062]
### Actual behavior

Instead, when executing a call successfully, it returns "500 An Internal Error Has Occured" and the JSON response is:

{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/galaxy_clusters\/index\/3"}

### Expected behavior

When executing a call successfully, it should return "200 Get galaxy clusters response" and the JSON response should be:

{ "GalaxyCluster": { ... } }

### Steps to reproduce

Tried executing a GET to /galaxy_clusters/index/3 using the PyMISP - Python library using the MISP Rest API client.

Please note, we do not have this issue with MISP 2.5.1, but only with MISP 2.5.2.

Reference:
https://www.misp-project.org/openapi/#tag/Galaxy-Clusters/operation/getGalaxyClusters

### Version

2.5.2

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8.2

### Relevant log output

```shell
error.log:

2024-11-26 10:41:10 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Galaxy.default' in 'where clause'
Request URL: /galaxy_clusters/index/3
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3054): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3026): Model->_readDataSource()
#6 /var/www/MISP/app/Model/AppModel.php(4346): Model->find()
#7 /var/www/MISP/app/Controller/GalaxyClustersController.php(101): AppModel->find()
#8 [internal function]: GalaxyClustersController->index()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#13 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonbjorzen-ts** [comment]
Can confirm this behaviour on version 2.4.200 with PyMISP 2.5.2.
This breaks some integrations for us that rely on the search_galaxy_clusters function in PyMISP.

**Comment by adpaccent** [comment]
Please consider this issue urgent because it is blocking our integration between MISP and Crowdstrike (MISP Tools Manual Import):

https://github.com/CrowdStrike/MISP-tools/

Please let us know.

**Comment by simonbjorzen-ts** [comment]
Any progress on this? Thanks

**Comment by iglocska** [comment]
Just to rule out some issues that may have gone wrong:

1. Could you go to your diagnostics page as an admin and click the "clean cache" button?
2. Could you log into your mysql and run the following query?

`describe galaxies`;
`describe galaxy_clusters`;

**Comment by simonbjorzen-ts** [comment]
Hi @iglocska, 
1. Tried, still the same error when using PyMISP `misp.search_galaxy_clusters(galaxy="c4e851fa-775f-11e7-8163-b774922098cd", searchall="T1453")`
2. 
```
MariaDB [misp]> describe galaxies;
+------------------+------------------+------+-----+---------+----------------+
| Field            | Type             | Null | Key | Default | Extra          |
+------------------+------------------+------+-----+---------+----------------+
| id               | int(11)          | NO   | PRI | NULL    | auto_increment |
| uuid             | varchar(255)     | NO   | UNI | NULL    |                |
| name             | varchar(255)     | NO   | MUL |         |                |
| type             | varchar(255)     | NO   | MUL | NULL    |                |
| description      | text             | NO   |     | NULL    |                |
| version          | varchar(255)     | NO   |     | NULL    |                |
| icon             | varchar(255)     | NO   |     |         |                |
| namespace        | varchar(255)     | NO   | MUL | misp    |                |
| enabled          | tinyint(1)       | NO   |     | 1       |                |
| local_only       | tinyint(1)       | NO   |     | 0       |                |
| kill_chain_order | text             | YES  |     | NULL    |                |
| default          | tinyint(1)       | NO   |     | 0       |                |
| org_id           | int(10) unsigned | NO   |     | NULL    |                |
| orgc_id          | int(10) unsigned | NO   |     | NULL    |                |
| created          | datetime         | NO   |     | NULL    |                |
| modified         | datetime         | NO   |     | NULL    |                |
| distribution     | tinyint(4)       | NO   |     | NULL    |                |
+------------------+------------------+------+-----+---------+----------------+
17 rows in set (0.001 sec)
```

```
MariaDB [misp]> describe galaxy_clusters;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| id               | int(11)      | NO   | PRI | NULL    | auto_increment |
| uuid             | varchar(255) | NO   | MUL |         |                |
| collection_uuid  | varchar(255) | NO   | MUL | NULL    |                |
| type             | varchar(255) | NO   | MUL | NULL    |                |
| value            | text         | NO   | MUL | NULL    |                |
| tag_name         | varchar(255) | NO   | MUL |         |                |
| description      | text         | NO   |     | NULL    |                |
| galaxy_id        | int(11)      | NO   | MUL | NULL    |                |
| source           | varchar(255) | NO   |     |         |                |
| authors          | text         | NO   |     | NULL    |                |
| version          | int(11)      | YES  | MUL | 0       |                |
| distribution     | tinyint(4)   | NO   |     | 0       |                |
| sharing_group_id | int(11)      | YES  | MUL | NULL    |                |
| org_id           | int(11)      | NO   | MUL | NULL    |                |
| orgc_id          | int(11)      | NO   | MUL | NULL    |                |
| default          | tinyint(1)   | NO   | MUL | 0       |                |
| locked           | tinyint(1)   | NO   |     | 0       |                |
| extends_uuid     | varchar(40)  | YES  | MUL |         |                |
| extends_version  | int(11)      | YES  | MUL | 0       |                |
| published        | tinyint(1)   | NO   |     | 0       |                |
| deleted          | tinyint(1)   | NO   |     | 0       |                |
+------------------+--------------+------+-----+---------+----------------+
21 rows in set (0.001 sec)
```

Thanks!

**Comment by simonbjorzen-ts** [comment]
Just to clarify, this was not an issue on v2.4.199, but happened after upgrading to v2.4.200.

**Comment by iglocska** [comment]
Interesting, sadly my theory was wrong.

**Comment by adpaccent** [comment]
From our side, this was not an issue on v2.5.1, but happened after upgrading to v2.5.2.

**Comment by iglocska** [comment]
hmm, I am testing it on v2.4.200 and I can't seem to be able to reproduce it so far. 

Just wondering, do you also have the issue if you navigate to `/galaxy_clusters/index/c4e851fa-775f-11e7-8163-b774922098cd.json` via your browser?

**Comment by simonbjorzen-ts** [comment]
> hmm, I am testing it on v2.4.200 and I can't seem to be able to reproduce it so far.
> 
> Just wondering, do you also have the issue if you navigate to `/galaxy_clusters/index/c4e851fa-775f-11e7-8163-b774922098cd.json` via your browser?

That works fine and returns the expected clusters.

**Comment by simonbjorzen-ts** [comment]
Looking into this further, turned on debug mode and this is the executed SQL query:
```
SELECT `GalaxyCluster`.`id`, `GalaxyCluster`.`uuid`, `GalaxyCluster`.`collection_uuid`, `GalaxyCluster`.`type`, `GalaxyCluster`.`value`, `GalaxyCluster`.`tag_name`, `GalaxyCluster`.`description`, `GalaxyCluster`.`galaxy_id`, `GalaxyCluster`.`source`, `GalaxyCluster`.`authors`, `GalaxyCluster`.`version`, `GalaxyCluster`.`distribution`, `GalaxyCluster`.`sharing_group_id`, `GalaxyCluster`.`org_id`, `GalaxyCluster`.`orgc_id`, `GalaxyCluster`.`default`, `GalaxyCluster`.`locked`, `GalaxyCluster`.`extends_uuid`, `GalaxyCluster`.`extends_version`, `GalaxyCluster`.`published`, `GalaxyCluster`.`deleted` 
FROM `misp`.`galaxy_clusters` AS `GalaxyCluster`   
WHERE ((`GalaxyCluster`.`deleted` = '0') 
AND (((((LOWER(`GalaxyCluster`.`value`) LIKE '%t1453%') OR (LOWER(`GalaxyCluster`.`description`) LIKE '%t1453%') OR (`GalaxyCluster`.`uuid` = 'T1453') OR (`GalaxyCluster`.`id` IS NULL)))  AND  (`GalaxyCluster`.`galaxy_id` = 22))) AND (((((`Galaxy`.`default` = '1') OR (`Galaxy`.`org_id` = 1) OR (((`Galaxy`.`distribution` > 0) AND (`Galaxy`.`distribution` < 4))))) AND (((`GalaxyCluster`.`org_id` = 1) OR (((`GalaxyCluster`.`distribution` > 0) AND (`GalaxyCluster`.`distribution` < 4))) OR (((`GalaxyCluster`.`sharing_group_id` IN (7, 1, 2, 3, 4, 5, 6, 8)) AND (`GalaxyCluster`.`distribution` = 4))))))))
```

Executing this query in the database also returns the error `ERROR 1054 (42S22): Unknown column 'Galaxy.default' in 'where clause'`

To me as an amateur in SQL, it appears that the table Galaxy is missing in the query, changing the query FROM line to this makes the query execute correctly. 

```
FROM `misp`.`galaxy_clusters` AS `GalaxyCluster`, `misp`.`galaxies` AS `Galaxy`  
```

**Comment by rubentroncon** [comment]
Same issue in MISP 2.5.6.

**Comment by DeZuko** [comment]
> Looking into this further, turned on debug mode and this is the executed SQL query:
> 
> ```
> SELECT `GalaxyCluster`.`id`, `GalaxyCluster`.`uuid`, `GalaxyCluster`.`collection_uuid`, `GalaxyCluster`.`type`, `GalaxyCluster`.`value`, `GalaxyCluster`.`tag_name`, `GalaxyCluster`.`description`, `GalaxyCluster`.`galaxy_id`, `GalaxyCluster`.`source`, `GalaxyCluster`.`authors`, `GalaxyCluster`.`version`, `GalaxyCluster`.`distribution`, `GalaxyCluster`.`sharing_group_id`, `GalaxyCluster`.`org_id`, `GalaxyCluster`.`orgc_id`, `GalaxyCluster`.`default`, `GalaxyCluster`.`locked`, `GalaxyCluster`.`extends_uuid`, `GalaxyCluster`.`extends_version`, `GalaxyCluster`.`published`, `GalaxyCluster`.`deleted` 
> FROM `misp`.`galaxy_clusters` AS `GalaxyCluster`   
> WHERE ((`GalaxyCluster`.`deleted` = '0') 
> AND (((((LOWER(`GalaxyCluster`.`value`) LIKE '%t1453%') OR (LOWER(`GalaxyCluster`.`description`) LIKE '%t1453%') OR (`GalaxyCluster`.`uuid` = 'T1453') OR (`GalaxyCluster`.`id` IS NULL)))  AND  (`GalaxyCluster`.`galaxy_id` = 22))) AND (((((`Galaxy`.`default` = '1') OR (`Galaxy`.`org_id` = 1) OR (((`Galaxy`.`distribution` > 0) AND (`Galaxy`.`distribution` < 4))))) AND (((`GalaxyCluster`.`org_id` = 1) OR (((`GalaxyCluster`.`distribution` > 0) AND (`GalaxyCluster`.`distribution` < 4))) OR (((`GalaxyCluster`.`sharing_group_id` IN (7, 1, 2, 3, 4, 5, 6, 8)) AND (`GalaxyCluster`.`distribution` = 4))))))))
> ```
> 
> Executing this query in the database also returns the error `ERROR 1054 (42S22): Unknown column 'Galaxy.default' in 'where clause'`
> 
> To me as an amateur in SQL, it appears that the table Galaxy is missing in the query, changing the query FROM line to this makes the query execute correctly.
> 
> ```
> FROM `misp`.`galaxy_clusters` AS `GalaxyCluster`, `misp`.`galaxies` AS `Galaxy`  
> ```

I have the same issue with my misp 2.4.200.

Can this improvised query in any way helps fixing the search_galaxy_clusters function in PyMISP?. In my case I used this function for the integration between MISP and Crowdstrike...
