### ISSUE TITLE
Bug: Cannot login to MISP due to tripping CSRF protection

### ISSUE THREAD

**Issue by www-jedi** [MISP/MISP#10083]
### Actual behavior

Login via GUI than error message about CSRF 

### Expected behavior

Get an error when logging in 

### Steps to reproduce

Login via GUI than error message about CSRF 

### Version

2.5.2

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8.3

### Browser

Chrome

### Relevant log output

```shell
You have tripped the cross-site request forgery protection of MISP
CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed.

Alternatively, click here to continue to the start page.


2024-12-06 00:17:39 Error: Blackhole exception when accessing /users/login (isRest: 0, action: login, unlockedActions: []): '_Token' was not found in request data.
2024-12-06 00:17:39 Error: [BadRequestException] The request has been black-holed
Request URL: /users/login?_=1733444257241
Stack Trace:
#0 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /datadisk/MISP/var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /datadisk/MISP/var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(688): BetterCakeEventManager->dispatch()
#7 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /datadisk/MISP/var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by www-jedi** [comment]
I tried to disable CSP via cli and no luck
sudo -u www-data /var/www/MISP/app/Console/cake admin setSetting Security.csp_enforce false
/var/www/MISP/app/tmp/logs/[28144]: serverSettingsEdit -- Server setting changed -- Security.csp_enforce () => ()
Setting "Security.csp_enforce" changed to false

**Comment by www-jedi** [comment]
I fixed the issue due to setting the value of upload_max_filesize = 50MB to  'upload_max_filesize = 50M'

https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize
