### ISSUE TITLE
Support: Log in error with MISP 2.5.5 and PHP 8.1

### ISSUE THREAD

**Issue by enzok00** [MISP/MISP#10138]
### Support Questions

Hello,

I've just download the new MISP version 2.5.5 on my Ubuntu server 22.0.4, and I get an internal error when I try to connect to MISP via the url **<misp-url>/users/login**.

git describe result:
_v2.5.5-1-g40e50041f_

php -v result:
_PHP 8.1.31 (cli) (built: Nov 21 2024 13:10:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.31, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.31, Copyright (c), by Zend Technologies_

### MISP version

2.5.5

### Operating System

Ubuntu

### Operating System version

22.0.4

### PHP version

8.1.31

### Browser

Microsoft Edge

### Browser version

131.0.2903.112

### Relevant log output

```shell
2024-12-31 17:40:55 Error: [TypeError] implode(): Argument #2 ($array) must be of type ?array, string given
Request URL: /users/login
Stack Trace:
#0 /var/www/html/MISP/app/Vendor/iglocska/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/html/MISP/app/Vendor/iglocska/php-resque-ex/lib/Resque/Redis.php(158): Redisent->__call()
#2 /var/www/html/MISP/app/Vendor/iglocska/resque-status/src/ResqueStatus/ResqueStatus.php(160): RedisApi->__call()
#3 /var/www/html/MISP/app/Model/Server.php(8310): ResqueStatus\ResqueStatus->getWorkers()
#4 /var/www/html/MISP/app/Model/Server.php(3796): Server->getWorkers()
#5 /var/www/html/MISP/app/Model/AppModel.php(2771): Server->workerDiagnostics()
#6 /var/www/html/MISP/app/Model/User.php(2233): AppModel->runUpdates()
#7 /var/www/html/MISP/app/Controller/UsersController.php(1281): User->init()
#8 [internal function]: UsersController->login()
#9 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(504): ReflectionMethod->invokeArgs()
#10 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/html/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#13 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
That sounds like something went wrong with the installation / update. You are still on CakeResque as your background worker engine and using the fallback redis library (Redisent). Which installation / upgrade script were you using?

**Comment by enzok00** [comment]
Thanks for the answer.
The installation script is an homemade script, and the problem was with composer . I updated my composer dependencies and it fixed the issue.
