### ISSUE TITLE
Attachment upload of existing file

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1024]
The UI interface message when uploading an existing attachment is "please contact your administrator" but we can see in the error log the reason: 

```
2016-03-16 14:57:21 Error: [NotFoundException] Event already exists, if you would like to edit it, use the url in the location header.
Request URL: /events
Stack Trace:
#0 [internal function]: EventsController->add()
#1 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP-priv/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

We would be nice to have the message available to the user.

**Comment by iglocska** [comment]
Even though we could label it as part of the "get to know you administrator
initiative", it's probably a good idea to change that indeed.

**Comment by adulau** [comment]
"Get to know you administrator initiative" Looks like a new series of sticker for MISP ;-)
