### ISSUE TITLE
 Error: [MissingTableException] after upgrade to 2.4.41

### ISSUE THREAD

**Issue by keram79** [MISP/MISP#1112]
I've just updated my MISP install from 2.4.x to 2.4.41 by following the steps in INSTALL/UPDATE.txt
When trying to access the Website, it shows `Error: An Internal Error Has Occurred.`  

The logfile `/var/www/MISP/app/tmp/logs/error.log` contains the following:

```
2016-04-29 11:29:28 Error: [MissingTableException] Table favourite_tags for model FavouriteTag was not found in datasource default.
Exception Attributes: array (
  'table' => 'favourite_tags',
  'class' => 'FavouriteTag',
  'ds' => 'default',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3653): Model->setSource('favourite_tags')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1387): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(2529): Model->schema()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1769): DboSource->fields(Object(FavouriteTag), 'FavouriteTag', '')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1264): DboSource->generateAssociationQuery(Object(User), Object(FavouriteTag), 'hasMany', 'FavouriteTag', Array, Array, true)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1144): DboSource->queryAssociation(Object(User), Object(FavouriteTag), 'hasMany', 'FavouriteTag', Array, Array, true, Array, 0, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(User), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('count', Array)
#8 /var/www/MISP/app/Controller/UsersController.php(676): Model->find('count')
#9 [internal function]: UsersController->login()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

My mysql database `misp`doesn't contain a table `favourite_tags`:

```
mysql> show tables;
+-------------------------------+
| Tables_in_misp                |
+-------------------------------+
| admin_settings                |
| attributes                    |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
| event_delegations             |
| event_tags                    |
| events                        |
| feeds                         |
| jobs                          |
| logs                          |
| organisations                 |
| posts                         |
| regexp                        |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| tags                          |
| tasks                         |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| users                         |
| whitelist                     |
+-------------------------------+
36 rows in set (0.00 sec)
```

**Did I miss something during Update?**  

There's the file `upgrade_2.4.sql`, but the UPDATE.TXT didn't say to import this.

**Comment by iglocska** [comment]
There shouldn't be a need to import it, the table should be created automatically the moment you load the a page after running git pull, this is weird.

**Comment by iglocska** [comment]
I've just pushed a small change that should help. Could you post the contents of your admin_settings table and do a git pull?

**Comment by keram79** [comment]
I've re-run the command in UPGRADE.TXT that executes the .sql file against my MISP database, this created the missing table.  
After clearing the caches, the login works fine again.
