### ISSUE TITLE
StackTraces for JsContoller

### ISSUE THREAD

**Issue by geudrik** [MISP/MISP#1161]
Happens on every page. I started seeing issues ~5 hotfixes ago, but never saw any major issues with functionality.

```
Request URL: /js/misp2.4.45.js
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 07:32:21 Error: [MissingControllerException] Controller class JsController could not be found.
Exception Attributes: array (
  'class' => 'JsController',
  'plugin' => NULL,
)
Request URL: /js/misp2.4.45.js
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 07:32:23 Error: [MissingControllerException] Controller class JsController could not be found.
Exception Attributes: array (
  'class' => 'JsController',
  'plugin' => NULL,
)
Request URL: /js/misp2.4.45.js
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 07:32:25 Error: [MissingControllerException] Controller class JsController could not be found.
Exception Attributes: array (
  'class' => 'JsController',
  'plugin' => NULL,
)
Request URL: /js/misp2.4.45.js
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 07:32:58 Error: [MissingControllerException] Controller class JsController could not be found.
Exception Attributes: array (
  'class' => 'JsController',
  'plugin' => NULL,
)
Request URL: /js/misp2.4.45.js
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
```

**Comment by geudrik** [comment]
I should note that I'm actually running `.46`

<img width="331" alt="screen shot 2016-05-23 at 10 46 48 am" src="https://cloud.githubusercontent.com/assets/2020115/15474640/b1e41208-20d3-11e6-8214-960436860188.png">

**Comment by iglocska** [comment]
Could you git pull again and see if the issue persists?

**Comment by geudrik** [comment]
My routine for upgrading (keeping up with latest releases) is to `fetch --all` then `checkout tags/xxxx`

Is there a different route I should be taking? I'm not super keep on tracking master...

**Comment by iglocska** [comment]
Ah yeah, I made a mistake and linked to the wrong JS file and pushed the
fix within minutes of the tag. Just checkout 2.4 and pull the latest
version and it should fix it. I'll push the version number later tonight to
resolve it, sorry about the inconvenience!

**Comment by geudrik** [comment]
No worries, thanks Andras! :) I'll pull tomorrow/later tonight.

**Comment by geudrik** [comment]
Confirming that latest hotfix resolves this issue. 👍
