### ISSUE TITLE
Log message in MISP Logs for MethodNotAllowedException

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1402]
Log a meaningful error message, preferably with username and/or source ip inside MISP logs just before MethodNotAllowedException exceptions are thrown.

What I have now is lots of errors logged into error.log but not means of knowing what is creating them. 

For example:

```
2016-08-03 11:15:11 Error: [MethodNotAllowedException] You do not have permission to use this functionality.
Request URL: /shadow_attributes/getProposalsByUuid/5703b3c1-e6a4-421a-a394-440f950d210f
Stack Trace:
#0 /var/www/MISP/app/Controller/Component/ACLComponent.php(376): ACLComponent->__error(403, 'You do not have...')
#1 /var/www/MISP/app/Controller/AppController.php(334): ACLComponent->checkAccess(Array, 'shadowAttribute...', 'getProposalsByU...')
#2 /var/www/MISP/app/Controller/ShadowAttributesController.php(25): AppController->beforeFilter()
#3 [internal function]: ShadowAttributesController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ShadowAttributesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

**Comment by rotanid** [comment]
this message comes from here:
https://github.com/MISP/MISP/blob/2.4/app/Controller/AppController.php#L334
which calls this:
https://github.com/MISP/MISP/blob/2.4/app/Controller/Component/ACLComponent.php#L356
it might also be related to your issue with perm_delegate because the permissions are checked there - but that's just a wild guess

**Comment by github-germ** [comment]
i also see this `[MethodNotAllowedException]` in the `error.log`. how do we determine the cuase and remedy based on the associated trace:
```
2018-05-22 16:02:33 Error: [MethodNotAllowedException] You do not have permission to use this functionality.
Request URL: /tags/add
Stack Trace:
#0 /var/www/MISP/app/Controller/Component/ACLComponent.php(506): ACLComponent->__error(403, 'You do not have...')
#1 /var/www/MISP/app/Controller/AppController.php(395): ACLComponent->checkAccess(Array, 'tags', 'add')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
```

**Comment by github-germ** [comment]
seeing LOTS of these errors. HELP...

**Comment by iglocska** [comment]
That's cool. Event got an edit, MISP tried to attach a tag that was already
attached, MISP said no thanks.

**Comment by github-germ** [comment]
Cool. I assume it's "cheaper" to add a tag, vs. checking first if it exists, e.g. with search.

**Comment by iglocska** [comment]
yep!

**Comment by iglocska** [comment]
but looking at the error it looks like I should have spent more time with it, looks like an ACL issue. Hmph. You sure you're on the latest version?

**Comment by github-germ** [comment]
FYI, with the `deadlockfix` branch I do not see these SQL errors anymore.
