### ISSUE TITLE
HTTP 500 error response when updating using PyMISP

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#1433]
Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug/support... |
| OS version (server) | CentOS |
| OS version (client) | 14.04 |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.50 |
| Browser | N/A |
### Expected behavior

Update an event using the PyMISP API, should receive 200 response to indicate success.
### Actual behavior

Attempting to update an event using the PyMISP API, receiving a 500 Server Error response. However, the event is actually updated, but I get the error anyways!

Having looked at the logs, the error that is being thrown is:
**PHP Fatal error:  Class 'CakeResque' not found in /var/www/MISP/app/Model/Event.php on line 1486**
### Steps to reproduce the behavior

Python code:

```
from pymisp import PyMISP
pm = PyMISP(_URL_, _key_, True, 'json')
event = pm.get(_event_id_)
event['Event']['timestamp'] = int(event['Event']['timestamp']) + 1 # So that the event is theoretically newer
for place, attr in enumerate(event['Event']['Attribute']):
    attr['distribution'] = 5 #Inherits the Event
    attr['timestamp'] = int(attr['timestamp']) + 1 # Updating attribute timestamp too
    event['Event']['Attribute'][place] = attr
```

**Comment by tomking2** [comment]
Fixed it!

Don't even ask... somehow our instance did not have CakeResque installed, who knows how it's been running up until now! I was never involved in the setup, so somehow it must've been missed.

**Comment by Rafiot** [comment]
Thanks for the feedback, closing! :)

**Comment by tomking2** [comment]
Any chance of opening this up again? Looks like CakeResque still isn't installing :(. When trying to start the workers, I'm getting an error saying the plugin cannot be found

**Comment by Rafiot** [comment]
Hmmm did you follow the install guide? What is the error message?

**Comment by tomking2** [comment]
Yep, our MISP has been running no issued for many months. Tried to reinstall, but it informs me it's already installed. Error is as follows:

```
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(252): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('CakeResque.Cake...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(252): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('CakeResque.Cake...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(252): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('CakeResque.Cake...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(252): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('CakeResque.Cake...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(252): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('CakeResque.Cake...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(252): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('CakeResque.Cake...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}



```

**Comment by Rafiot** [comment]
@iglocska any clue?

**Comment by iglocska** [comment]
Not yet, this is new. Never had any issues with CakeResque missing.

**Comment by tomking2** [comment]
Was able to roll back, and managed to update to the latest version. CakeResque is now working - yay!

However, still getting this 500 server error, but no error logs are appearing for PHP. Error logs I've seen are as follows:

```
2016-08-11 20:42:22 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Server.lastfetchedid' in 'field list'
Request URL: /events/5076
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Server`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('SELECT `Server`...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1359): DboSource->fetchAll('SELECT `Server`...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1298): DboSource->queryAssociation(Object(SharingGroupServer), Object(Server), 'belongsTo', 'Server', Array, Array, true, Array, 0, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1144): DboSource->queryAssociation(Object(SharingGroup), Object(SharingGroupServer), 'hasMany', 'SharingGroupSer...', Array, Array, true, Array, 1, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(SharingGroup), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('first', Array)
#8 /var/www/MISP/app/Model/SharingGroup.php(335): Model->find('first', Array)
#9 /var/www/MISP/app/Model/Event.php(1940): SharingGroup->captureSG(Array, Array)
#10 /var/www/MISP/app/Controller/EventsController.php(1212): Event->_edit(Array, Array, '5076')
#11 [internal function]: EventsController->edit('5076')
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#15 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
```

**Comment by tomking2** [comment]
And at the same time, with debug logs on...

```
2016-08-11 20:42:22 Notice: Notice (8): Undefined index: perm_delegate in [/var/www/MISP/app/Controller/AppController.php, line 311]
Trace:
AppController::beforeFilter() - APP/Controller/AppController.php, line 311
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 155
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 92
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??

```

**Comment by iglocska** [comment]
Hmm that means that the upgrade procedure failed for you. Any chance you could check the audit logs for failed SQL queries via the UI?

**Comment by tomking2** [comment]
Is this the upgrade from 2.3 -> 2.4? if so, we've been on 2.4 for a long time! 

Where can I find the audit logs by any chance?

**Comment by iglocska** [comment]
No no, basically with each point release there is an upgrade procedure that makes changes to the database (You can find them in /var/www/MISP/app/Model/AppModel.php) - these are executed on the first page load after upgrading with a git pull.

The audit logs: When you log in as a site admin it's in the right upper corner. If you cannot log in I'll post an alternate way of getting it via mysql directly.

**Comment by tomking2** [comment]
Ah okay, that makes sense, thanks for clearing it up.

Audit logs - here we go!:

```
The executed SQL query was: ALTER TABLE `servers` DROP `lastfetchedid`;
The returned error is: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'lastfetchedid'; check that column/key exists 
```

```
The executed SQL query was: ALTER TABLE `tasks` CHANGE `job_id` `process_id` varchar(32) DEFAULT NULL;
The returned error is: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'job_id' in 'tasks' 
```

```
The executed SQL query was: ALTER TABLE `roles` ADD `perm_delegate` tinyint(1) NOT NULL DEFAULT 0 AFTER `perm_publish`;
The returned error is: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'perm_delegate' 
```

**Comment by tomking2** [comment]
```
The executed SQL query was: ALTER TABLE `users` ALTER COLUMN `server_id` SET DEFAULT 0;
The returned error is: Table cake_errors for model CakeError was not found in datasource default. 
```

**Comment by iglocska** [comment]
Hmm that is weird. It sounds like the upgrade happened twice. Could you try to clean out the model cache by navigating to the diagnostics page (administration -> server settings -> clean model cache) ?

Does it work for you after this? Hopefully the 500 error codes should be gone, but the cakeresque issue is separate that we need to tackle.

**Comment by tomking2** [comment]
You're amazing, I really do owe you one! That's now all working, cleaning the model cache did it, thank you!

Ah, well I've managed to resolve that myself - Fortunately had a backup of my MISP, and used that to update it, may have been the reason the model cache went a bit funny, who knows. Cakeresque was working without issue on this copy, thank god. No idea what the issue with this was though, tried to re-run the cakeresque install but nothing seemed to work. At least I've got a working copy now though!

Once again, thank you!

**Comment by iglocska** [comment]
Thank you, this reveals an issue with the process we have for clearing caches. I need to look into why it didn't correctly at the end of the upgrade procedure as it should. Nudge me if you run into any other issues! Will close the issue for now, but if the issue pops up again, or anyone else has the same issue and the cache-cleaning method doesn't solve it just let us know here and we'll reopen it!

**Comment by tomking2** [comment]
Ooh - One more thing I should point out - Looks like the version ID is one behind itself - Currently on 2.4.50, but it's coming up as 2.4.49, just one to look out for :)
[https://github.com/MISP/MISP/blob/v2.4.50/VERSION.json](https://github.com/MISP/MISP/blob/v2.4.50/VERSION.json)

**Comment by iglocska** [comment]
Hmm that is weird, are you running the latest tagged version or the latest commit from HEAD? It should say 2.4.50 but I might have forgotten to bump the version number until after I tagged it...

**Comment by tomking2** [comment]
I'm currently running the tagged version, not the latest commit from head. Looks to be that way, seems fine on HEAD, but not on tagged
