### ISSUE TITLE
Passivetotal and Virustotal enrichment plugins failing

### ISSUE THREAD

**Issue by infde6** [MISP/MISP#1466]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, Question, Feature Request, support... |
| OS version (server) | Ubuntu |
| OS version (client) | Server 16.04 |
| PHP version | 7.0.8 |
| MISP version / git hash | 2.4.50 |
| Browser | N/A |
### Expected behavior

When using either the Passivetotal or VirusTotal enrichment, receive results from those sources for inclusion in events.
### Actual behavior

After selecting enrichment, MISP loads page stating, "Error: An Internal Error Has Occurred."

Additionally, app/tmp/log/error.log contains the following error:
Request URL: /events/queryEnrichment/146948/virustotal
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Events/query_en...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render(NULL, NULL)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

2016-08-23 09:40:49 Error: [MissingViewException] View file "Events/query_enrichment.ctp" is missing.
Exception Attributes: array (
  'file' => 'Events/query_enrichment.ctp',
)
Request URL: /events/queryEnrichment/2902/passivetotal
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Events/query_en...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render(NULL, NULL)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

2016-08-23 09:41:00 Error: [MissingViewException] View file "Events/query_enrichment.ctp" is missing.
Exception Attributes: array (
  'file' => 'Events/query_enrichment.ctp',

When troubleshooting further, the file MISP/app/Views/Events/query_enrichment.ctp does not exist.
### Steps to reproduce the behavior

1) Install MISP-modules
2) Set settings for Passivetotal and Virustotal modules
3) Attempt to enrich an event from Passivetotal / Virustotal
### Logs, screenshots, configuration dump, ...

See actual behaviour

**Comment by adulau** [comment]
Could you start the module with the -d option (debug)? and paste the output here (don't forget to remove your API keys if they appear in the logs ;-)? Thank you very much.

**Comment by infde6** [comment]
Set the misp-modules to start in debugging:
sudo -u www-data misp-modules -s -d

Entries in MISP/app/tmp/logs/error.log still the same:
Request URL: /events/queryEnrichment/147970/passivetotal
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Events/query_en...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render(NULL, NULL)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-08-24 09:25:31 Error: [MissingViewException] View file "Events/query_enrichment.ctp" is missing.
Exception Attributes: array (
  'file' => 'Events/query_enrichment.ctp',
)
Request URL: /events/queryEnrichment/2902/virustotal
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Events/query_en...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render(NULL, NULL)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-08-24 09:25:41 Error: [MissingViewException] View file "Events/query_enrichment.ctp" is missing.
Exception Attributes: array (
  'file' => 'Events/query_enrichment.ctp',
)

Again, the requested file does not exist, and is not part of the misp-modules branch on github. Any way to re-create it?

Thank you!

**Comment by iglocska** [comment]
query_enrichment.ctp not existing is correct, the function should return a json response and not go through a view. Could you git pull and get the latest commit for MISP from head? The issue was most likely caused by a low timeout compounded with some other issues that should now be resolved.

**Comment by infde6** [comment]
Could you please post the exact git command you would like me to run so that I don't make any mistakes?

Thank you!

**Comment by iglocska** [comment]
cd /var/www/MISP
git pull origin 2.4

this should do the trick

**Comment by infde6** [comment]
Performed git pull origin 2.4 on .../MISP and restarted Apache.

When attempting to use Virustotal enrichment, received the error:
Enrichment service not reachable.
Error: The requested address '/events/queryEnrichment/2902/virustotal' was not found on this server.

No additional information is provided in the .../app/tmp/logs/debug or error logs.

**Comment by iglocska** [comment]
Looking into it, weird.

**Comment by giedriusramas** [comment]
I get following error when trying to test virustotal module.

2016-09-08 14:01:50,272 - misp-modules - ERROR - Something went wrong:
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/misp_modules/init.py", line 195, in post
response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
value = future.result()
File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
raise_exc_info(self.exc_info)
File "", line 3, in raise_exc_info
File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
result = self.fn(self.args, *self.kwargs)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init_.py", line 183, in run_request
response = mhandlers[x['module']].handler(q=jsonpayload)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 39, in handler
r["results"] += getDomain(q["domain"], key)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 85, in getDomain
toReturn += getIP(res["ip_address"], key, True)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 67, in getIP
toReturn += getMoreInfo(req, key)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 141, in getMoreInfo
"values":data["submission_names"],
KeyError: 'submission_names'
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/misp_modules/init.py", line 195, in post
response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
value = future.result()
File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
raise_exc_info(self.exc_info)
File "", line 3, in raise_exc_info
File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
result = self.fn(self.args, *self.kwargs)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init_.py", line 183, in run_request
response = mhandlers[x['module']].handler(q=jsonpayload)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 39, in handler
r["results"] += getDomain(q["domain"], key)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 85, in getDomain
toReturn += getIP(res["ip_address"], key, True)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 67, in getIP
toReturn += getMoreInfo(req, key)
File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 141, in getMoreInfo
"values":data["submission_names"],
KeyError: 'submission_names'
{"error": "Something went wrong, look in the server logs for details"}[14:01:50]

To test module I run following command. curl -s http://127.0.0.1:6666/query -H "Content-Type: application/json" --data @body_virustotal.json -X POST

body_virustotal.json

{
"domain": "aijazeera.org",
"module": "virustotal",
"config":
{
"apikey": "myAPIkey", 
"event_limit": "5"
}
}
