### ISSUE TITLE
Unable to get MISP-Modules Installed

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#1494]
I've been trying to get the MISP-Modules installed on my CENTOS 7 system. I see the install commands are for Ubuntu, but I tried running running the commands to install the packages and etc under CENTOS 7. Is there specific instructions on how to install the MISP-Modules for CENTOS 7?

**Comment by gra55h0pp3r** [comment]
So I've ran the following commands for misp-module import:

cd /tmp
wget https://bootstrap.pypa.io/get-pip.py
python3.4 get-pip.py
cd /usr/local/src/
git clone https://github.com/MISP/misp-modules.git
cd misp-modules
pip3 install --upgrade -r REQUIREMENTS
pip3 install --upgrade .

So editing the rc.local is where I'm lost. I think for CENTOS the command ran would be sudo -u apache misp-modules -s, but I'm not sure if it's correct.

I'm not sure if any of the above what I did will may it work correctly or not.

**Comment by cristianbell** [comment]
this works for me on RHEL: `su -s /bin/bash apache -c 'python3 /usr/local/src/misp-modules/bin/misp-modules'` 

I created a PR with the install commands for RHEL/CentOS in parallel to the Ubuntu one a while ago, but got rejected: https://github.com/MISP/misp-modules/pull/38/commits/ee3c6bd2a35c5ab9593dc2d6df3ab796871a3d06

**Comment by gra55h0pp3r** [comment]
I tried following your install instruction and everything ran pretty smoothly. When I try running the command: su -s /bin/bash apache -c 'python3 /usr/local/src/misp-modules/bin/misp-modules' 
I get the following error message.
python3: can't open file '/usr/local/src/misp-modules/bin/misp-modules': [Errno 13] Permission denied
I changed the own of the folder to apache, but still permissions denied.

Thanks for providing what you did.

**Comment by cristianbell** [comment]
That is odd. But please make sure that the apache user can get to the whole path, not only the bin/misp-modules. let me look a little at the server/folder and will tell u if I find anything else..

**Comment by cristianbell** [comment]
ah, just out of curiosity, how did you install python3? from SCL?

**Comment by gra55h0pp3r** [comment]
I installed it from yum. I don't see a bin directory, so that would explain the permissions issues.

So I was able to see the modules in MISP, but when I try running OCR import for example I get all kinds of error message from python:

ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/**init**.py", line 195, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/__init__.py", line 183, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/modules/import_mod/ocr.py", line 28, in handler
    ocrized = image_to_string(Image.open(image_file))
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/pytesseract/pytesseract.py", line 161, in image_to_string
    config=config)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/pytesseract/pytesseract.py", line 94, in run_tesseract
    stderr=subprocess.PIPE)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/subprocess.py", line 950, in **init**
    restore_signals, start_new_session)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract'

**Comment by iglocska** [comment]
It sounds like you are missing some dependencies, make sure you run:

sudo pip3 install --upgrade -r REQUIREMENTS

**Comment by gra55h0pp3r** [comment]
I tried running the command and all the requirements showed already updated.

I tried running OCR again and still the same output.

**Comment by adulau** [comment]
Everything looks good. It's just that you are missing the OCR software installation. 

The OCR installation is a bit more complex if you want to use the OCR. You can follow this procedure install tesseract OCR on your machine:

http://miphol.com/muse/2013/05/install-tesseract-ocr-on-ubunt.html

I hope this helps.

**Comment by adulau** [comment]
@cristianbell We are still waiting for your documentation and PR in misp-book to install the modules on the different GNU/Linux distribution.

**Comment by gra55h0pp3r** [comment]
I finally got OCR working, but the STIX import will not work.

Error Message:
Failed to load package
2016-09-02 23:44:08,183 - misp-modules - ERROR - Something went wrong:
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/modules/import_mod/stiximport.py", line 234, in loadPackage
    package = STIXPackage().from_json(temp)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/mixbox/entities.py", line 468, in from_json
    d = json.load(json_doc)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/**init**.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/**init**.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/**init**.py", line 195, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/__init__.py", line 183, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/modules/import_mod/stiximport.py", line 51, in handler
    package = loadPackage(package, memsize)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/modules/import_mod/stiximport.py", line 237, in loadPackage
    raise ValueError("COULD NOT LOAD STIX PACKAGE!")
ValueError: COULD NOT LOAD STIX PACKAGE!
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/modules/import_mod/stiximport.py", line 234, in loadPackage
    package = STIXPackage().from_json(temp)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/mixbox/entities.py", line 468, in from_json
    d = json.load(json_doc)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/**init**.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/**init**.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/**init**.py", line 195, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/__init__.py", line 183, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/modules/import_mod/stiximport.py", line 51, in handler
    package = loadPackage(package, memsize)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/misp_modules-1.0-py3.5.egg/misp_modules/modules/import_mod/stiximport.py", line 237, in loadPackage
    raise ValueError("COULD NOT LOAD STIX PACKAGE!")
ValueError: COULD NOT LOAD STIX PACKAGE!

**Comment by adulau** [comment]
I'll close the issue. Feel free to reopen if the issue persists.
