### ISSUE TITLE
PDOException after git pull

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1737]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu  16.04.1 LTS 
| OS version (client)       | macOS Sierra 10.12.1
| PHP version               | 7.0
| MISP version / git hash   | 2.4.56 b653a2aab122c2cce15e3b23813f08705efc2c41
| Browser                   | Not applicable

### Expected behavior
MISP should stay functional after a git pull

### Actual behavior
Viewing an event throws:
```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
```
Clearing the cached myapp models does not help. 

### Steps to reproduce the behavior
Click on any event from the index

### Logs, screenshots, configuration dump, ...
```
2016-12-08 22:34:24 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.GalaxyCluster.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /events/view/11
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('SELECT `GalaxyC...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(671): DboSource->execute('SELECT `GalaxyC...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1120): DboSource->fetchAll('SELECT `GalaxyC...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(GalaxyCluster), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('list', Array)
#6 /var/www/MISP/app/Controller/EventsController.php(819): Model->find('list', Array)
#7 /var/www/MISP/app/Controller/EventsController.php(901): EventsController->__viewUI(Array, false, NULL)
#8 [internal function]: EventsController->view('11')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
```

**Comment by FloatingGhost** [comment]
Duplicate of #1732

**Comment by RichieB2B** [comment]
Thanks, also for the fix! I just know I couldn't have been the first to see this.

**Comment by iglocska** [comment]
Just a heads-up if you're not following the other thread - it's fixed now, just git pull please!
