### ISSUE TITLE
shadow_attributes comment not set on delete proposal

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1741]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04.1 LTS
| OS version (client)       | macOS Sierra 10.12.1
| PHP version               | 7.0
| MISP version / git hash   | 2.4.56 01f078344c67e1779eec6682c0c4d887cde57a7c
| Browser                   | Not applicable

### Expected behavior
Proposals to delete an attributes should be saved

### Actual behavior
MISP throws a PDOException

### Steps to reproduce the behavior
Propose the deletion of an attribute

### Logs, screenshots, configuration dump, ...
```
2016-12-09 09:03:15 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'comment' doesn't have a default value
Request URL: /shadow_attributes/delete/77722
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1026): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(ShadowAttribute), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/ShadowAttributesController.php(761): Model->save(Array)
#6 [internal function]: ShadowAttributesController->delete('77722')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ShadowAttributesController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ShadowAttributesController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by iglocska** [comment]
Woah, how did this go undetected this long? Great that you caught it!
