### ISSUE TITLE
 Column not found: 1054 Unknown column 'Task.job_id' in 'field list'

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#1750]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 5.6
| MISP version / git hash   | 2.4.56, aaaaaa0523b691b30b4431ffff5d2dd97d57d7df
| Browser                   | FF

### Expected behavior
See the list of scheduled tasks

### Actual behavior
An Internal Error Has Occurred

### Steps to reproduce the behavior
Administration -> Scheduled Tasks

### Logs, screenshots, configuration dump, ...

==> error.log <==
2016-12-12 14:08:14 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list'
Request URL: /tasks
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Task`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('SELECT `Task`.`...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1113): DboSource->fetchAll('SELECT `Task`.`...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Task), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Controller/TasksController.php(35): Model->find('first', Array)
#7 /var/www/MISP/app/Controller/TasksController.php(18): TasksController->__checkTasks()
#8 [internal function]: TasksController->index()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

==> resque-scheduler-2016-12-12.log <==
[2016-12-12 15:00:02] main.INFO: Moving scheduled job SERVERSHELL to DEFAULT {"type":"movescheduled","args":{"timestamp":1481551200,"class":"ServerShell","queue":"default","job_id":"352cab971a1a2d757eae49847d39e1cf","wait":1481551202.423,"s_wait":1481551200},"worker":"misp.ip-plus.net:30163"} []
[2016-12-12 15:00:02] main.INFO: Moving scheduled job SERVERSHELL to DEFAULT {"type":"movescheduled","args":{"timestamp":1481551200,"class":"ServerShell","queue":"default","job_id":"528e5e34a37afe8be16aae9555037943","wait":1481551202.425,"s_wait":1481551200},"worker":"misp.ip-plus.net:30163"} []
[2016-12-12 15:00:02] main.INFO: Moving scheduled job SERVERSHELL to DEFAULT {"type":"movescheduled","args":{"timestamp":1481551200,"class":"ServerShell","queue":"default","job_id":"36b473bcf8c52717bc6ee02cff8723e8","wait":1481551202.426,"s_wait":1481551200},"worker":"misp.ip-plus.net:30163"} []
[2016-12-12 15:00:02] main.INFO: Moving scheduled job SERVERSHELL to DEFAULT {"type":"movescheduled","args":{"timestamp":1481551200,"class":"ServerShell","queue":"default","job_id":"c0776712810a5e8cc7a59c2d9b49cbea","wait":1481551202.429,"s_wait":1481551200},"worker":"misp.ip-plus.net:30163"} []

==> resque-2016-12-12.log <==
[2016-12-12 15:00:06] main.INFO: got {"queue":"default","id":"352cab971a1a2d757eae49847d39e1cf","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481536805}]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"352cab971a1a2d757eae49847d39e1cf\",\"class\":\"ServerShell\",\"args\":[{\"0\":\"enqueuePull\",\"1\":1481551200,\"2\":\"1\",\"3\":\"2\",\"s_time\":1481536805}]})","worker":"misp.ip-plus.net:30082"} []
[2016-12-12 15:00:06] main.INFO: Processing ID:352cab971a1a2d757eae49847d39e1cf in default {"type":"process","worker":"misp.ip-plus.net:30082","job_id":"352cab971a1a2d757eae49847d39e1cf"} []
[2016-12-12 15:00:06] main.ERROR: {"queue":"default","id":"352cab971a1a2d757eae49847d39e1cf","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481536805}]} failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list' {"type":"fail","log":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list'","job_id":"352cab971a1a2d757eae49847d39e1cf","time":58,"worker":"misp.ip-plus.net:30082"} []
[2016-12-12 15:00:06] main.INFO: got {"queue":"default","id":"528e5e34a37afe8be16aae9555037943","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481537583}]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"528e5e34a37afe8be16aae9555037943\",\"class\":\"ServerShell\",\"args\":[{\"0\":\"enqueuePull\",\"1\":1481551200,\"2\":\"1\",\"3\":\"2\",\"s_time\":1481537583}]})","worker":"misp.ip-plus.net:30082"} []
[2016-12-12 15:00:06] main.INFO: Processing ID:528e5e34a37afe8be16aae9555037943 in default {"type":"process","worker":"misp.ip-plus.net:30082","job_id":"528e5e34a37afe8be16aae9555037943"} []
[2016-12-12 15:00:06] main.ERROR: {"queue":"default","id":"528e5e34a37afe8be16aae9555037943","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481537583}]} failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list' {"type":"fail","log":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list'","job_id":"528e5e34a37afe8be16aae9555037943","time":81,"worker":"misp.ip-plus.net:30082"} []
[2016-12-12 15:00:06] main.INFO: got {"queue":"default","id":"36b473bcf8c52717bc6ee02cff8723e8","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481541176}]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"36b473bcf8c52717bc6ee02cff8723e8\",\"class\":\"ServerShell\",\"args\":[{\"0\":\"enqueuePull\",\"1\":1481551200,\"2\":\"1\",\"3\":\"2\",\"s_time\":1481541176}]})","worker":"misp.ip-plus.net:30082"} []
[2016-12-12 15:00:06] main.INFO: Processing ID:36b473bcf8c52717bc6ee02cff8723e8 in default {"type":"process","worker":"misp.ip-plus.net:30082","job_id":"36b473bcf8c52717bc6ee02cff8723e8"} []
[2016-12-12 15:00:06] main.ERROR: {"queue":"default","id":"36b473bcf8c52717bc6ee02cff8723e8","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481541176}]} failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list' {"type":"fail","log":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list'","job_id":"36b473bcf8c52717bc6ee02cff8723e8","time":51,"worker":"misp.ip-plus.net:30082"} []
[2016-12-12 15:00:06] main.INFO: got {"queue":"default","id":"c0776712810a5e8cc7a59c2d9b49cbea","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481541299}]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"c0776712810a5e8cc7a59c2d9b49cbea\",\"class\":\"ServerShell\",\"args\":[{\"0\":\"enqueuePull\",\"1\":1481551200,\"2\":\"1\",\"3\":\"2\",\"s_time\":1481541299}]})","worker":"misp.ip-plus.net:30082"} []
[2016-12-12 15:00:06] main.INFO: Processing ID:c0776712810a5e8cc7a59c2d9b49cbea in default {"type":"process","worker":"misp.ip-plus.net:30082","job_id":"c0776712810a5e8cc7a59c2d9b49cbea"} []
[2016-12-12 15:00:06] main.ERROR: {"queue":"default","id":"c0776712810a5e8cc7a59c2d9b49cbea","class":"ServerShell","args":[{"0":"enqueuePull","1":1481551200,"2":"1","3":"2","s_time":1481541299}]} failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list' {"type":"fail","log":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list'","job_id":"c0776712810a5e8cc7a59c2d9b49cbea","time":53,"worker":"misp.ip-plus.net:30082"} []

**Comment by h122015** [comment]
I've just updated the issue to include the logs of the scheduler. It should have performed a pull/push from all connected instances, instead of that I see these error messages in the logs
