### ISSUE TITLE
Jobs hang at pulling proposals

### ISSUE THREAD

**Issue by stevengoossensB** [MISP/MISP#1788]
Hi,

Since some time, my pull jobs never seem to complete. While they do download new events and even new proposals, the job stalls at around 6% with status 'pulling proposals'. After 1h, when the new job starts, it stays forever at 6% with status 'pulling'.

None of the logs show that there is an issue of some kind.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support...
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04.1
| PHP version               | 7.0.8
| MISP version / git hash   | 2.4.58

### Expected behavior
Job reaches status done

### Actual behavior
Job stalls at 6%

### Steps to reproduce the behavior
?

### Logs, screenshots, configuration dump, ...
![image](https://cloud.githubusercontent.com/assets/10197869/21517951/4017ccfc-cce3-11e6-92d7-76371cfbb52c.png)

**Comment by cristianbell** [comment]
Which Ubuntu is it? you put 16.04.1 for the client, is that for the server as well? 

Can you look in the logs? Also in `/var/www/MISP/app/tmp/logs/resque-2016-12-dd.log` 

And what happens when you do a manual pull? The same behavior? 
If that is the case, for the manual pull you will also have the Process id. You can look in the `resque-yyyy-mm-dd.log` log for infos about the pull. Or you can query the redis (`redis-cli` and then `KEYS processid`) to see the status of the job.

**Comment by stevengoossensB** [comment]
Hi,

Apparently it is failing because of the 'org' field not being filled out. Although my org name is visible for the job and is filled out in the 'jobs' table.

[2016-12-29 15:19:05] main.ERROR: {"queue":"default","id":"dd77a125379715b050100ad5b91c1142","class":"ServerShell","args":[{"0":"enqueuePull","1":1483021140,"2":"1","3":"2","s_time":1483021091}]} failed: SQLSTATE[HY000]: General error: 1364 Field 'org' doesn't have a default value {"type":"fail","log":"SQLSTATE[HY000]: General error: 1364 Field 'org' doesn't have a default value","job_id":"dd77a125379715b050100ad5b91c1142","time":5202,"worker":"inrpmisp001:15109"} []

**Comment by stevengoossensB** [comment]
And apparently in the redis-cli my job is marked as failed:

 "resque:failed:a68b49a7915f6a499f17fcb3bed67fa1"

**Comment by iglocska** [comment]
Interesting, so one of the log entry inserts fails for you. Let me have a
look!

**Comment by iglocska** [comment]
Just pushed a small (and somewhat dirty) fix, let's see if that solves it
for you for now. Could you git pull and give it another shot?

**Comment by stevengoossensB** [comment]
Doesn't change anything for me :(

I restarted the workers to be 'clean'. And still got the 'org' problem.

[2016-12-29 16:19:53] main.INFO: Exiting... {"type":"shutdown","worker":"inrpmisp001:32443"} []
[2016-12-29 16:19:53] main.INFO: Exiting... {"type":"shutdown","worker":"inrpmisp001:32389"} []
[2016-12-29 16:19:53] main.INFO: Exiting... {"type":"shutdown","worker":"inrpmisp001:32407"} []
[2016-12-29 16:19:53] main.INFO: Exiting... {"type":"shutdown","worker":"inrpmisp001:32425"} []
[2016-12-29 16:19:53] main.INFO: Starting worker inrpmisp001:32532:default {"type":"start","worker":"inrpmisp001:32532:default"} []
[2016-12-29 16:19:53] main.INFO: Starting worker inrpmisp001:32550:prio {"type":"start","worker":"inrpmisp001:32550:prio"} []
[2016-12-29 16:19:53] main.INFO: Starting worker inrpmisp001:32568:cache {"type":"start","worker":"inrpmisp001:32568:cache"} []
[2016-12-29 16:19:54] main.INFO: Starting worker inrpmisp001:32586:email {"type":"start","worker":"inrpmisp001:32586:email"} []
[2016-12-29 16:20:10] main.INFO: got {"queue":"default","id":"4852a507989473d053a725eeffbc0a35","class":"ServerShell","args":[["pull","1","5","full","23228"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"worker\":null,\"payload\":{\"class\":\"ServerShell\",\"args\":[[\"pull\",\"1\",\"5\",\"full\",\"23228\"]],\"id\":\"4852a507989473d053a725eeffbc0a35\"}})","worker":"inrpmisp001:11024"} []
[2016-12-29 16:20:10] main.INFO: Processing ID:4852a507989473d053a725eeffbc0a35 in default {"type":"process","worker":"inrpmisp001:11024","job_id":"4852a507989473d053a725eeffbc0a35"} []
[2016-12-29 16:20:14] main.ERROR: {"queue":"default","id":"4852a507989473d053a725eeffbc0a35","class":"ServerShell","args":[["pull","1","5","full","23228"]]} failed: SQLSTATE[HY000]: General error: 1364 Field 'org' doesn't have a default value {"type":"fail","log":"SQLSTATE[HY000]: General error: 1364 Field 'org' doesn't have a default value","job_id":"4852a507989473d053a725eeffbc0a35","time":3982,"worker":"inrpmisp001:11024"} 

Next to that, I seem to be hitting hte same bug/error as xme (https://github.com/MISP/MISP/issues/1587)

2016-12-29 16:25:14 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /jobs/getGenerateCorrelationProgress/23226
Stack Trace:
#0 [internal function]: AppController->beforeFilter(Object(CakeEvent))
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

**Comment by stevengoossensB** [comment]
...And related to that, this might be of interest to you:

mysql> describe logs
    -> ;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| title       | text         | YES  |     | NULL    |                |
| created     | datetime     | YES  |     | NULL    |                |
| model       | varchar(20)  | YES  |     | NULL    |                |
| model_id    | int(11)      | YES  |     | NULL    |                |
| action      | varchar(20)  | YES  |     | NULL    |                |
| user_id     | int(11)      | YES  |     | NULL    |                |
| change      | text         | YES  |     | NULL    |                |
| email       | varchar(255) | YES  |     | NULL    |                |
| org         | varchar(255) | YES  |     | NULL    |                |
| description | text         | YES  |     | NULL    |                |
| ip          | varchar(45)  | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
12 rows in set (0.00 sec)

mysql> describe organisations;
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| id            | int(11)      | NO   | PRI | NULL    | auto_increment |
| name          | varchar(255) | NO   | MUL | NULL    |                |
| date_created  | datetime     | NO   |     | NULL    |                |
| date_modified | datetime     | NO   |     | NULL    |                |
| description   | text         | NO   |     | NULL    |                |
| type          | varchar(255) | NO   |     | NULL    |                |
| nationality   | varchar(255) | NO   |     | NULL    |                |
| sector        | varchar(255) | NO   |     | NULL    |                |
| created_by    | int(11)      | NO   |     | 0       |                |
| uuid          | varchar(40)  | YES  | MUL | NULL    |                |
| contacts      | text         | NO   |     | NULL    |                |
| local         | tinyint(1)   | NO   |     | 0       |                |
| landingpage   | text         | NO   |     | NULL    |                |
+---------------+--------------+------+-----+---------+----------------+
13 rows in set (0.00 sec)

**Comment by stevengoossensB** [comment]
Hi,

I managed to resolve my issue with a (temporary) workaround.

Apparently, the update to MySQL 5.7 introduced the 'STRICT_TRANS_TABLES' in my config, which caused a problem somewhere in the database. Disabling it fixed my problem for now, but indicates that one of the queries probably doesn't have a 100% correct syntax?

Best regards

Steven,
