### ISSUE TITLE
An Internal Error Has Occurred / Error: [MissingTableException] Table logs for model Log was not found in datasource default.

### ISSUE THREAD

**Issue by rubenrodr-versia** [MISP/MISP#1796]
Hi,

I have made a fresh install on Centos 7 and get the error
An Internal Error Has Occurred 
when accessing the web page.
The error log shows this:
2016-12-30 13:05:32 Error: [MissingTableException] Table logs for model Log was not found in datasource default.
Exception Attributes: array (
  'table' => 'logs',
  'class' => 'Log',
  'ds' => 'default',
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3660): Model->setSource('logs')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(275): Model->schema()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('User', Array)
#6 /var/www/MISP/app/Model/AppModel.php(31): Model->__construct(Array, NULL, NULL)
#7 [internal function]: AppModel->__construct(Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(742): ClassRegistry::init(Array)
#10 /var/www/MISP/app/Controller/AppController.php(90): Controller->loadModel('User')
#11 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#12 [internal function]: EventsController->beforeFilter(Object(CakeEvent))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#17 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}

I can log into the db with the misp user:
 mysql -u misp -p misp
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 13
Server version: 10.1.20-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [misp]> 

Also tried to recreate the table log without success.

Thanks.
Best regards.

**Comment by FloatingGhost** [comment]
I have a feeling that you didn't run the SQL for creating the tables

`sudo -u www-data sh -c "mysql -u misp -p misp < /var/www/MISP/INSTALL/MYSQL.sql"`

**Comment by rubenrodr-versia** [comment]
Hi,

Yes, i have run the database creation sql:

$ mysql -u misp -p misp
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 12
Server version: 10.1.20-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [misp]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| misp               |
| test               |
+--------------------+
3 rows in set (0.00 sec)

MariaDB [misp]> show tables;
+-------------------------------+
| Tables_in_misp                |
+-------------------------------+
| admin_settings                |
| attributes                    |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
| event_delegations             |
| event_tags                    |
| events                        |
| favourite_tags                |
| feeds                         |
| galaxies                      |
| galaxy_clusters               |
| galaxy_elements               |
| galaxy_reference              |
| jobs                          |
| logs                          |
| news                          |
| organisations                 |
| posts                         |
| regexp                        |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| sightings                     |
| tags                          |
| tasks                         |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| users                         |
| warninglist_entries           |
| warninglist_types             |
| warninglists                  |
| whitelist                     |
+-------------------------------+
46 rows in set (0.00 sec)

and checked tha logs table is being created:

MariaDB [misp]> describe logs;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| title       | text         | YES  |     | NULL    |                |
| created     | datetime     | NO   |     | NULL    |                |
| model       | varchar(20)  | NO   |     | NULL    |                |
| model_id    | int(11)      | NO   |     | NULL    |                |
| action      | varchar(20)  | NO   |     | NULL    |                |
| user_id     | int(11)      | NO   |     | NULL    |                |
| change      | text         | YES  |     | NULL    |                |
| email       | varchar(255) | NO   |     | NULL    |                |
| org         | varchar(255) | NO   |     | NULL    |                |
| description | text         | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
11 rows in set (0.01 sec)

Thanks.
Best regards.

**Comment by FloatingGhost** [comment]
what about /var/www/MISP/app/Config/database.php? 

Is that all set up to point at the right database?

**Comment by rubenrodr-versia** [comment]
Hi,

Yes is pointing to the correct db (the only one on this host):

class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		//'datasource' => 'Database/Postgres',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'misp',
		'port' => 3306, // MySQL & MariaDB
		//'port' => 5432, // PostgreSQL
		'password' => '*******',
		'database' => 'misp',
		'prefix' => '',
		//'encoding' => 'utf8',
	);
}

Thanks.
Best regards.

**Comment by iglocska** [comment]
Could you clean your model cache just in case?

rm /var/www/MISP/app/tmp/cache/models/myapp*
rm /var/www/MISP/app/tmp/cache/persistent/myapp*

Does this solve it?

**Comment by rubenrodr-versia** [comment]
Hi,

The cache diretory is empty:
$ ls -rltah /var/www/MISP/app/tmp/cache/
total 8,0K
drwxr-x--- 7 apache apache 4,0K dic 30 09:29 ..
drwxr-x--- 2 apache apache 4,0K dic 30 13:56 .

Thanks.
Best regards.

**Comment by iglocska** [comment]
This shouldn't be an issue with mysql/mariadb only with redis, but could you run:

```
setsebool -P httpd_can_network_connect=1
```

**Comment by rubenrodr-versia** [comment]
Hi,

Selinux is disabled:

$ setsebool -P httpd_can_network_connect=1
setsebool:  SELinux is disabled.

Thanks.
Best regards.
