### ISSUE TITLE
Can't add user when SMIME is disabled

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1821]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04.1 LTS
| OS version (client)       | n/a
| PHP version               | 7.0
| MISP version / git hash   | 2.4.59 0e37fc7c75163ff42e7b6e570a85a70cb490c560
| Browser                   | n/a

### Expected behavior
User should be added

### Actual behavior
MISP throws an internal error

### Steps to reproduce the behavior
Add a user on a MISP instance with SMIME.enabled set to false (or blank)

### Logs, screenshots, configuration dump, ...
```
2017-01-10 13:06:26 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'certif_public' doesn't have a default value
Request URL: /admin/users/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1026): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(User), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/UsersController.php(384): Model->save(Array, true, Array)
#6 [internal function]: UsersController->admin_add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by iglocska** [comment]
Hacky quick fix for the issue. We should at one point review all default values in the database and have an upgrade script that fixes these.
