### ISSUE TITLE
getGenerateCorrelationProgress auth problem?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1890]
I started to see this error in my logs:

2017-02-06 10:32:47 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /jobs/getGenerateCorrelationProgress/11976
Stack Trace:
#0 [internal function]: AppController->beforeFilter(Object(CakeEvent))
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

The reason is clear :)
But I don't find to which action is related this error...
Any idea?

**Comment by xme** [comment]
Again, I'm seeing this error in my logs... Any idea?
I checked in the code, the line that generates this error is just after the block: 
if (!empty($_SERVER['HTTP_AUTHORIZATION']))
=> It means that the header is not present in the request. How? Why?

**Comment by iglocska** [comment]
I'll have a look, nothing to worry about, it shouldn't require it. Basically getGenerateCorrelationProgress is not an API query, it's just looking at job progress in the jobs index.

**Comment by xme** [comment]
Ok, good to know!

**Comment by lctrcl** [comment]
Can confirm, MISP v2.4.76 (982924779ede42e3dbe0b1e464979319348b035f), after update from 75->75 started to see these errors:

```
2017-06-21 08:09:35 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /jobs/getGenerateCorrelationProgress/31
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by StefanKelm** [comment]
Also seeing many of these errors. Seems to happen when I manually fetch all the events from one of our enabled feeds (in this case: https://feeds.inthreat.com/osint/misp/) and that feed had not been updated for quite a while. Sometimes fetching all events stops and I have to re-start fetching:

> 2017-11-21 14:42:43 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
> Request URL: /jobs/getGenerateCorrelationProgress/3560
> Stack Trace:
> #0 [internal function]: AppController->beforeFilter(Object(CakeEvent))
> #1 /services/inst/misp/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
> #2 /services/inst/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
> #3 /services/inst/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
> #4 /services/inst/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
> #5 /services/inst/misp/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #6 {main}
