### ISSUE TITLE
User exports take an insane amount of time

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#1963]
When the admin account on barncat MISP tries to do an export, it takes 5-10 minutes to generate.  When a user tries to generate an export, it can take a week.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 16.04 LTS
| PHP version               | 7.0
| MISP version / git hash   | 2.4.66
| Browser                   | If applicable

**Comment by iglocska** [comment]
Very curious what causes that will try to look into it using your instance this week if that's ok.

**Comment by bambenek** [comment]
No rush, thanks!

**Comment by bambenek** [comment]
Here's a thought, is it possible to have MISP incrementally add to the exports (say by configuration setting) so instead of generating the export anew each time, it simply just keeps adding new events as it goes to existing export files? Perhaps with some validation that all the data is still there?

**Comment by bambenek** [comment]
MISP exports when done by users and not admins still take way too long.


1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
-- | -- | -- | -- | -- | -- | -- | -- | --
75353 | 2017-06-13 18:49:15 | 2017-06-17 19:47:06 | 27be8564216e6ae2861c0b95cc7d3cc5 | cache | cache_csv_all | Events visible to: Barncat Users | Job done. (in 349068s) | Barncat Users

**Comment by adulau** [comment]
Just for the follow-up, does this issue still exist for 2.4.82?

**Comment by bambenek** [comment]
I logged in with a user account and it errors out, max_allowed_packet.

--

2017-11-13 02:08:23 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /events/export
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('SELECT `Event`....', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(671): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1120): DboSource->fetchAll('SELECT `Event`....', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Controller/EventsController.php(1863): Model->find('first', Array)
#7 [internal function]: EventsController->export()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-11-13 02:08:23 Warning: Warning (2): Error while sending QUERY packet. PID=30781 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468]
Trace:
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 434
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 671
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1120
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3038
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3010
AppModel::__runCleanDB() - APP/Model/AppModel.php, line 1055
AppModel::runUpdates() - APP/Model/AppModel.php, line 1014
AppController::beforeFilter() - APP/Controller/AppController.php, line 253
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??

**Comment by iglocska** [comment]
Will have a look today what's going on that's weird
