### ISSUE TITLE
Undefined index: type [APP/Model/Server.php, line xxxx]

### ISSUE THREAD

**Issue by yohonet** [MISP/MISP#1987]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 7.3
| OS version (client)       | Win7
| PHP version               | 7.0.10 (via scl)
| MISP version / git hash   | 2.4.66
| Browser                   | Firefox

### Expected behavior

"Server Settings" page shows up

### Actual behavior

Notice (8): Undefined index: type [APP/Model/Server.php, line 2897]

Notice (8): Undefined index: type [APP/Model/Server.php, line 2897]

### Steps to reproduce the behavior

Click on the "Server Settings" tab.

-------

This happened after I updated to the latest commit (after weeks without any update). I've turned on debugging and the server settings page does not show up. The "workers" array doesn't contain an index called "type" but the code is checking for it. When I look at the context of the error, this is what I see:

Notice (8): Undefined index: type [APP/Model/Server.php, line 2897]
Code Context

        $procAccessible = file_exists('/proc');
        foreach ($workers as $pid => $worker) {
            $entry = ($worker['type'] == 'regular') ? $worker['queue'] : $worker['type'];

$workerIssueCount = (int) 0
$workers = array(
	'cache' => array(
		'ok' => true
	),
	'default' => array(
		'ok' => true
	),
	'email' => array(
		'ok' => true
	),
	'prio' => array(
		'ok' => true
	),
	'scheduler' => array(
		'ok' => true
	)
)
$currentUser = 'apache'
$worker_array = array(
	'cache' => array(
		'ok' => true
	),
	'default' => array(
		'ok' => true
	),
	'email' => array(
		'ok' => true
	),
	'prio' => array(
		'ok' => true
	),
	'scheduler' => array(
		'ok' => true
	)
)
$procAccessible = true
$worker = array(
	'ok' => true
)
$pid = 'cache'

Server::workerDiagnostics() - APP/Model/Server.php, line 2897
ServersController::serverSettings() - APP/Controller/ServersController.php, line 753
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
[...]

**Comment by yohonet** [comment]
I think the problem is due to the job table which doesn't have any field "type". Probably an update problem but how can I fix this ?

**Comment by yohonet** [comment]
I have the same issue by trying to view the "jobs"

**Comment by yohonet** [comment]
I found that I upgraded from version 2.4.54 to the latest one (2.4.67)

**Comment by adulau** [comment]
@yohonet Do you mean that is now fixed with 2.4.67 or do you still have the issue? Thank you for the report.

**Comment by yohonet** [comment]
No I still have the issue, but it happened after I upgraded from 2.4.54 to 2.4.67

**Comment by yohonet** [comment]
2.4.73 - still the same issue . All the other pages are working fine but can't see jobs nor change the server settings :(

**Comment by yohonet** [comment]
Still having this issue with the very latest MISP version. Everything appears to work except the administration and the jobs pages.

I found another similar thread (open a while ago) which suggested to switch back to php 5.6. Indeed, the issue is gone when doing so... 

The error.log is displayning the following error, don't know if it helps that much :

2017-05-18 10:11:14 Error: [MethodNotAllowedException] Non numeric PID found.
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(843): Server->workerDiagnostics(0)
#1 [internal function]: ServersController->serverSettings()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

**Comment by iglocska** [comment]
Is PHP redis installed? Non numeric PID errors are usually a sign of
falling back to redisent.

**Comment by yohonet** [comment]
Yes it is:
`$ scl enable rh-php70 bash`
`$ pecl list`
`Installed packages, channel pecl.php.net:`
`=========================================`
`Package Version State`
`redis   3.1.1   stable`
`$`

How can I troubleshoot ?

**Comment by yohonet** [comment]
I tend to believe this is a bug either in php or RequeStatus or both: If you have a look at my original post, you will see the array "$workers" has the same content as "$worker_array" and I don't think that's intended: for instance, the keys should be numerical pids and not 'cache, default, etc...".

$workers = array(
'cache' => array(
'ok' => true
),
'default' => array(
'ok' => true
),
'email' => array(
'ok' => true
),
'prio' => array(
'ok' => true
),
'scheduler' => array(
'ok' => true
)

**Comment by iglocska** [comment]
$workers for me looks like this:

```
array(
	(int) 32434 => array(
		'type' => 'scheduler',
		'log' => '/var/www/MISP/app/tmp/logs/resque-scheduler-error.log',
		'interval' => (int) 3,
		'workers' => (int) 1,
		'queue' => 'default',
		'user' => 'www-data',
		'verbose' => false,
		'Log' => array(
			'handler' => 'RotatingFile',
			'target' => '/var/www/MISP/app/tmp/logs/resque-scheduler.log'
		)
	),
	(int) 32414 => array(
		'interval' => (int) 5,
		'queue' => 'email',
		'help' => false,
		'verbose' => false,
		'quiet' => false,
		'type' => 'regular',
		'log' => '/var/www/MISP/app/tmp/logs/resque-worker-error.log',
		'workers' => (int) 1,
		'user' => 'www-data',
		'Log' => array(
			'handler' => 'RotatingFile',
			'target' => '/var/www/MISP/app/tmp/logs/resque.log'
		)
	),
	(int) 32378 => array(
		'interval' => (int) 5,
		'queue' => 'prio',
		'help' => false,
		'verbose' => false,
		'quiet' => false,
		'type' => 'regular',
		'log' => '/var/www/MISP/app/tmp/logs/resque-worker-error.log',
		'workers' => (int) 1,
		'user' => 'www-data',
		'Log' => array(
			'handler' => 'RotatingFile',
			'target' => '/var/www/MISP/app/tmp/logs/resque.log'
		)
	),
	(int) 32396 => array(
		'interval' => (int) 5,
		'queue' => 'cache',
		'help' => false,
		'verbose' => false,
		'quiet' => false,
		'type' => 'regular',
		'log' => '/var/www/MISP/app/tmp/logs/resque-worker-error.log',
		'workers' => (int) 1,
		'user' => 'www-data',
		'Log' => array(
			'handler' => 'RotatingFile',
			'target' => '/var/www/MISP/app/tmp/logs/resque.log'
		)
	),
	(int) 32360 => array(
		'interval' => (int) 5,
		'queue' => 'default',
		'help' => false,
		'verbose' => false,
		'quiet' => false,
		'type' => 'regular',
		'log' => '/var/www/MISP/app/tmp/logs/resque-worker-error.log',
		'workers' => (int) 1,
		'user' => 'www-data',
		'Log' => array(
			'handler' => 'RotatingFile',
			'target' => '/var/www/MISP/app/tmp/logs/resque.log'
		)
	)
)
```

The issues you're having normally come from using Redisent over PHP-redis (a fall-ack in cakePHP).

Make sure you've followed the following (of course in your case you need to adapt it as you're not using 5.6):

```
# CakeResque normally uses phpredis to connect to redis, but it has a (buggy) fallback connector through Redisent. It is highly advised to install phpredis using "yum install php-redis"
pecl install redis-2.2.8
echo "extension=redis.so" > /etc/opt/rh/rh-php56/php-fpm.d/redis.ini
ln -s ../php-fpm.d/redis.ini /etc/opt/rh/rh-php56/php.d/99-redis.ini
systemctl restart rh-php56-php-fpm.service

Note: if using rh-php56 redis needs to be installed through its terminal: /usr/bin/scl enable rh-php56  "pecl install redis-2.2.8"
```

**Comment by yohonet** [comment]
I followed these instructions already and think phpredis is correctly
installed and configured. However I think there's a problem with PHP
itself. Where is the recommendation for PHP 7.0.16 coming from? Software
collection only provides 7.0.10.

**Comment by iglocska** [comment]
7.0.16 was the current version for Ubuntu when I tagged the recommended version, basically anything should work past 5.6.

**Comment by yohonet** [comment]
By just moving the following line, the diagnostic page works (although the worker tab doesn't)... it makes no sense, so I really think there's a php bug somewhere. I asked if it was possible to update the software collection php 7 to a more recent version.

`$git diff Model/Server.php`

```Diff
diff --git a/app/Model/Server.php b/app/Model/Server.php
index cc92789..97ffa00 100644
--- a/app/Model/Server.php
+++ b/app/Model/Server.php
@@ -3096,7 +3096,6 @@ class Server extends AppModel {
                                        'scheduler' => array('ok' => false)
                        );
                }
-               $workers = $this->ResqueStatus->getWorkers();
                if (function_exists('posix_getpwuid')) {
                        $currentUser = posix_getpwuid(posix_geteuid());
                        $currentUser = $currentUser['name'];
@@ -3111,6 +3110,7 @@ class Server extends AppModel {
                                'scheduler' => array('ok' => true)
                );
                $procAccessible = file_exists('/proc');
+               $workers = $this->ResqueStatus->getWorkers();
                foreach ($workers as $pid => $worker) {
                        $entry = ($worker['type'] == 'regular') ? $worker['queue'] : $worker['type'];
                        $correct_user = ($currentUser === $worker['user']);
```
