### ISSUE TITLE
An Internal Error Has Occurred for Server Settings, Jobs and Publish Event

### ISSUE THREAD

**Issue by CQRuu** [MISP/MISP#2030]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | ubuntu
| PHP version               | 5.5.9
| MISP version / git hash   | 2.4.58 (and I tried 2.4.67 too)
| Browser                   | NA

### Expected behavior
Able to view the pages when I clicked to go the following pages:
- Administration >> Server Settings
- Administration >> Jobs
- Main page >> publish an event (redirects to https://[[domain:port]]/events/alert/[[eventid]])

### Actual behavior
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

### Steps to reproduce the behavior
- click on Server Settings / Jobs under "Administration" in header menu.
- click to publish any unpublished events on home page

### Logs, screenshots, configuration dump, ...
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2824): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(750): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

and

#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Event.php(2337): Resque::redis()
#5 /var/www/MISP/app/Controller/EventsController.php(1525): Event->publishRouter('46941', NULL, Array)
#6 [internal function]: EventsController->alert('46941')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by iglocska** [comment]
The stack traces are missing the actual error - could you post the full thing? Also, is Redis set up?

**Comment by CQRuu** [comment]
Hi,

How can i check whether my Redis server is up? There are error messages saying it went away..
Here are my stack traces:




Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(753): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings('misp')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 03:59:54 Error: [RedisException] Redis server went away
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(753): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 04:03:07 Error: [RedisException] Redis server went away
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(753): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 04:03:18 Error: [RedisException] Redis server went away
Request URL: /servers/serverSettings/misp
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(753): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings('misp')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 04:03:39 Error: [RedisException] Redis server went away
Request URL: /servers/serverSettings/misp
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(753): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings('misp')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 04:23:02 Error: [MissingControllerException] Controller class ModulesController could not be found.
Exception Attributes: array (
'class' => 'ModulesController',
'plugin' => NULL,
)
Request URL: /modules
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-03-06 04:23:10 Error: [MissingControllerException] Controller class ModulesController could not be found.
Exception Attributes: array (
'class' => 'ModulesController',
'plugin' => NULL,
)
Request URL: /modules
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-03-06 04:33:46 Error: [MissingControllerException] Controller class ModulesController could not be found.
Exception Attributes: array (
'class' => 'ModulesController',
'plugin' => NULL,
)
Request URL: /modules
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-03-06 05:36:31 Error: [RedisException] Redis server went away
Request URL: /events/alert/46883
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Event.php(2628): Resque::redis()
#5 /var/www/MISP/app/Controller/EventsController.php(1543): Event->publishRouter('46883', NULL, Array)
#6 [internal function]: EventsController->alert('46883')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 05:36:34 Error: [RedisException] Redis server went away
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/JobsController.php(20): Server->workerDiagnostics(0)
#6 [internal function]: JobsController->index()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(JobsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 05:43:04 Error: [RedisException] Redis server went away
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/JobsController.php(20): Server->workerDiagnostics(0)
#6 [internal function]: JobsController->index()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(JobsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 05:43:54 Error: [RedisException] Redis server went away
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/JobsController.php(20): Server->workerDiagnostics(0)
#6 [internal function]: JobsController->index()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(JobsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-06 05:46:07 Error: [RedisException] Redis server went away
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/PubSubTool.php(69): Redis->select('1')
#1 /var/www/MISP/app/Model/Event.php(2684): PubSubTool->publishEvent(Array)
#2 /var/www/MISP/app/Model/Event.php(2238): Event->publish('46898', NULL)
#3 /var/www/MISP/app/Controller/EventsController.php(1075): Event->_add(Array, true, Array, '', NULL, false, NULL, '46898', Array)
#4 [internal function]: EventsController->add()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2017-03-06 05:46:37 Error: [RedisException] Redis server went away
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/PubSubTool.php(69): Redis->select('1')
#1 /var/www/MISP/app/Model/Event.php(2684): PubSubTool->publishEvent(Array)
#2 /var/www/MISP/app/Model/Event.php(2238): Event->publish('46899', NULL)
#3 /var/www/MISP/app/Controller/EventsController.php(1075): Event->_add(Array, true, Array, '', NULL, false, NULL, '46899', Array)
#4 [internal function]: EventsController->add()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2017-03-06 06:42:00 Error: [RedisException] Redis server went away
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2936): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(753): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by iglocska** [comment]
If you type redis-cli on the command line, what happens?

**Comment by CQRuu** [comment]
it gives

127.0.0.1:6379>

**Comment by iglocska** [comment]
Was it working fine before? Or did it never work in the first place?

**Comment by CQRuu** [comment]
Hi iglocksa,

I'm not too sure as I've not worked with Redis-cli before .. Am I missing any dependencies / packages?

**Comment by iglocska** [comment]
Sorry, I mean I was wondering whether MISP worked without the above errors before or if it's a fresh install that didn't work from the get go.

**Comment by CQRuu** [comment]
MISP used to be working before (at least, for the older versions before i upgraded to newer versions)

**Comment by iglocska** [comment]
Which version did you upgrade from?

**Comment by CQRuu** [comment]
Hi! 

I've actually upgraded from version 2.4.58. It was still working in late Jan 2017, then some time later it didn't, so I thought I'd try upgrading to the latest MISP version to see how it goes (unfortunately that didn't work for me). 

My fix was simply just restarting MISP** and typing "redis-server" in the command line. (However I believe this fix is just temporary because when I reboot MISP, the internal error message returns and I'd need to type "redis-server" on the command line to start it up again.)

** note: during the start-up, the line "redis-server" shows it started [ OK ]
![image](https://cloud.githubusercontent.com/assets/9025937/23849864/1bf8be38-0818-11e7-8992-191f1e44aec9.png)
