### ISSUE TITLE
NotFoundException when no events found by restSearch

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2096]
Running 2.4.70 0163ab649a99a7b4f9d5a1f81b5451ac80119e03 when users poll for new events using the API but no new event are found, a NotFoundException is [thrown](https://github.com/MISP/MISP/blob/2.4/app/Controller/EventsController.php#L2686). This seems a bit harsh, especially because it produces a stack trace in error.log:

```
2017-03-30 13:23:47 Error: [NotFoundException] No matches.
Request URL: /events/restSearch/download
Stack Trace:
#0 [internal function]: EventsController->restSearch('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```
Perhaps a nice clean "Sorry, nothing found" message should be sent instead?

**Comment by iglocska** [comment]
Yep, changing it to []

**Comment by iglocska** [comment]
Yay for fewer exceptions!
