### ISSUE TITLE
fail to log with postgrey database

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#2150]
I can not login with pastres sql database

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (client)       | debian
| PHP version               | 7.0
| MISP version / git hash   | 2.4.72
| DB                   | psql (PostgreSQL) 9.6.2

### Expected behavior
login

### Actual behavior

**An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.**

### Steps to reproduce the behavior
Check this issue to add missing table :  * https://github.com/MISP/MISP/issues/2149 *
Configure db with postgres
Restart server
Try to log

### traceback
```bash
Error: [PDOException] SQLSTATE[42P01]: Undefined table: 7 ERREUR:  la relation « bruteforces_id_seq » n'existe pas
Request URL: /users/login
Stack Trace:
#0 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Postgres.php(299): PDO->lastInsertId('bruteforces_id_...')
#1 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): Postgres->lastInsertId('bruteforces', 'id')
#2 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(Bruteforce), Array, Array)
#3 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#4 /var/www/html/MISP/app/Model/Bruteforce.php(18): Model->save(Array)
#5 /var/www/html/MISP/app/Controller/UsersController.php(719): Bruteforce->insert('127.0.0.1', 'admin@admin.tes...')
#6 [internal function]: UsersController->login()
#7 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#8 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#10 /var/www/html/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by truckydev** [comment]
Don't forget to select in the good database ^_^
```bash
sudo -u postgres psql -U postgres -d misp
```

With debug mod i see that sighting table not exist
because bad syntaxe here : https://github.com/MISP/MISP/blob/2.4/INSTALL/POSTGRESQL-structure.sql#L517

```sql
CREATE TABLE IF NOT EXISTS sightings (
  id bigint NOT NULL ,
  attribute_id bigint NOT NULL,
  event_id bigint NOT NULL,
  org_id bigint NOT NULL,
  date_sighting bigint NOT NULL,
  uuid varchar(255) DEFAULT '',
  source varchar(255) DEFAULT '',
  type int DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE INDEX attribute_id_id ON sightings(attribute_id);
CREATE INDEX event_id ON sightings(event_id);
CREATE INDEX org_id ON sightings(org_id);
CREATE INDEX uuid ON sightings(uuid);
CREATE INDEX source ON sightings(source);
CREATE INDEX type ON sightings(type);
```

**Comment by truckydev** [comment]
I have create this database but I have again the same message : 
```php
Missing Database Table
Error: Table sightings for model Sighting was not found in datasource default.

Notice: If you want to customize this error message, create app/View/Errors/missing_table.ctp

Stack Trace

APP/Lib/cakephp/lib/Cake/Model/Model.php line 3667 → Model->setSource(string)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3038 → Model->getDataSource()
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3010 → Model->_readDataSource(string, array)
APP/Model/Sighting.php line 181 → Model->find(string, array)
APP/Model/AppModel.php line 86 → Sighting->addUuids()
APP/Model/AppModel.php line 887 → AppModel->updateMISP(string)
APP/Controller/AppController.php line 237 → AppModel->runUpdates()
APP/Controller/EventsController.php line 33 → AppController->beforeFilter()
APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php line 243 → EventsController->beforeFilter(CakeEvent)
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 677 → CakeEventManager->dispatch(CakeEvent)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(EventsController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

I think it's because sighting table is empty.
It will be good to cache this no ?
```
APP/Model/Sighting.php line 181 → Model->find(string, array)
```

**Comment by truckydev** [comment]
so ...
I will not go any further. swith to Postgres is currently not available :(

**Comment by adulau** [comment]
I'll close the issue as Postgresql is not supported. Feel free to reopen if there are any progresses.

**Comment by bluejade-lin** [comment]
Create the table bruteforces with a serial id column (id bigserial)
