### ISSUE TITLE
List Tags -> Internal Error (max_allowed_packet)

### ISSUE THREAD

**Issue by zeroq** [MISP/MISP#2156]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04 LTS
| OS version (client)       | MacOS
| PHP version               | 7.0.15
| MISP version / git hash   | 2.4.72
| Browser                   | Safari

### Expected behavior

Clicking "Event Actions" -> "List Tags" should show a list of all tags. There are currently five different tags in the DB Table "tags" and about 550.000 Events in the DB that have one of tags attached. 

### Actual behavior

Webserver reports: "Internal Server Error". Error.log shows the following:

```
Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Event`....', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Event`....', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Controller/TagsController.php(75): Model->find('all', Array)
#7 [internal function]: TagsController->index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-05-02 10:51:26 Warning: Warning (2): Error while sending QUERY packet. PID=1161 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 470]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 470
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 436
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 673
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1184
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3038
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3010
AppModel::__runCleanDB() - APP/Model/AppModel.php, line 914
AppModel::runUpdates() - APP/Model/AppModel.php, line 873
AppController::beforeFilter() - APP/Controller/AppController.php, line 237
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??
```

In "my.cnf" the "max_allowed_packet" setting is set to: 10485760M

**Comment by iglocska** [comment]
Didn't mean to close it, I've pushed a change that might help resolve this, could you give it a shot?

**Comment by adulau** [comment]
This should be resolved in recent version of MISP. Feel free to reopen the issue if this is not solved. Thank you very much!
