### ISSUE TITLE
Unknown column 'Attribute.disable_correlation' in 'where clause'

### ISSUE THREAD

**Issue by Danko90** [MISP/MISP#2224]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 14.04
| OS version (client)       | Ubuntu 14.04
| PHP version               | 5.6
| MISP version / git hash   | 2.4.73

Hi all,
I ran into an error while trying to push events with MISP-TAXII-Server. Below the stacktrace
```
2017-05-26 18:27:36 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Attribute.disable_correlation' in 'where clause'
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Attribute), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Attribute.php(1439): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Attribute.php(552): Attribute->__afterSaveCorrelation(Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1968): CakeEventManager->dispatch(Object(CakeEvent))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#11 /var/www/MISP/app/Model/Event.php(2169): Model->save(Array, Array)
#12 /var/www/MISP/app/Controller/EventsController.php(1107): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#13 [internal function]: EventsController->add()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#17 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}
```
I tried to update, but it didn't work.
Can anyone help me?

Thank you!

**Comment by Danko90** [comment]
Solved, After update the database schema wasn't updated. Closing.
