### ISSUE TITLE
Capture stderr of shell_exec() calls for troubleshooting

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2266]
Whenever misp2stix breaks it is always a pain to troubleshoot because the stderr is not captured. The MISP error.log just shows a generic error. It would be nice if the stderr of all exec() calls could be captured somewhere.

```
2017-06-16 13:10:13 Error: [Exception] There was an issue generating the STIX export.
Request URL: /events/stix/download/8517.xml
Stack Trace:
#0 [internal function]: EventsController->stix('download', '8517')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by iglocska** [comment]
Good point. For now I've only done it with the stix export, more to come later.
