### ISSUE TITLE
RHEL7: No GPG key set in your profile. To receive emails, submit your public key in your profile.

### ISSUE THREAD

**Issue by enkidunolinux** [MISP/MISP#2471]
Hi,

I have two instances of MISP stood up now and installted on AWS RHEL7. I'm getting the warring on the top of the webpage  **"No GPG key set in your profile. To receive emails, submit your public key in your profile."** "The profile could not be updated. Please, try again."

- I tried to submit the public key in my profile and got this error "The profile could not be updated. Please, try again.**" and under GPG Key "GPG key not valid, please enter a valid key."** and in the bottom of the page **"Could not fetch the given PGP key."**

the error logs are:

```
2017-09-14 05:24:29 Error: [InternalErrorException] Internal Server Error
Request URL: /users/fetchPGPKey/me@mymail?_=1505366612367
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught except...', '/var/www/MISP/a...', 261)
#1 [internal function]: ErrorHandler::handleError(1, 'Uncaught except...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Uncaught except...', '/var/www/MISP/a...', 261, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-09-14 05:24:39 Error: [SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://pgp.mit.edu:443 (Unknown error)
Request URL: /users/fetchPGPKey/me@mymail?_=1505366612368
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(386): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('GET /pks/lookup...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(466): HttpSocket->request(Array)
#3 /var/www/MISP/app/Model/User.php(869): HttpSocket->get('https://pgp.mit...')
#4 /var/www/MISP/app/Controller/UsersController.php(1513): User->fetchPGPKey('me@...')
#5 [internal function]: UsersController->fetchPGPKey('me@...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2017-09-14 05:24:39 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(2)
#1 [internal function]: ExceptionRenderer->error400(Object(SocketException))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): call_user_func_array(Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#4 [internal function]: ErrorHandler::handleException(Object(SocketException))
#5 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
2017-09-14 05:24:39 Error: Fatal Error (1): Uncaught exception 'InternalErrorException' with message 'Internal Server Error' in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2017-09-14 05:24:39 Error: [InternalErrorException] Internal Server Error
Request URL: /users/fetchPGPKey/me@mymail?_=1505366612368
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught except...', '/var/www/MISP/a...', 261)
#1 [internal function]: ErrorHandler::handleError(1, 'Uncaught except...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Uncaught except...', '/var/www/MISP/a...', 261, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```
 

worth mentioning that MISP session handler enforced to use database sessions as PHP didn't work for me which i'm still trying to find a fix for (in another open issue)

**Comment by iglocska** [comment]
I see two separate issues here:

1. Your key could not be validated: If you have manually entered it and it fails, then something weird is happening with your key itself. If you try to import it via the command line via gpg, does it work as expected? Is it able to both sign and an encrypt?

2. You seem to be unable to fetch the PGP keys via the built in feature that fetches keys, from the MIT PGP keyserver using the entered e-mail address:

```
2017-09-14 05:24:39 Error: [SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://pgp.mit.edu:443 (Unknown error)
```

This is weird though. SSL errors with the MIT pgp keyserver are a bit scary, are you doing anything funky in your network? Terminating the ssl connection? Using something like Bluecoat?

As for the database sessions: The only impact it has is a ~50ms overhead on your queries as opposed to using redis based sessions, there are no other downsides.

**Comment by enkidunolinux** [comment]
Hi @iglocska 

1-  as far as I understand the key is created, I have recreated and validated as following (let me know if I have done something stupid :) ) and something very "interesting" happen

```
[root@myservername MISP]# rm -rf /var/www/MISP/.gnupg
[root@myservername MISP]# gpg --gen-key
gpg (GnuPG) 2.0.22; Copyright (C) 2013 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
Your selection?
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (2048)
Requested keysize is 2048 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0)
Key does not expire at all
Is this correct? (y/N) y

GnuPG needs to construct a user ID to identify your key.

Real name: me
Email address: me@myemail
Comment:
You selected this USER-ID:
    "me <me@myemail>"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? o
You need a Passphrase to protect your secret key.

We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: key 287F86F5 marked as ultimately trusted
public and secret key created and signed.

gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
pub   2048R/287F86F5 2017-09-14
      Key fingerprint = E826 DAB6 3869 EE02 0B81  4A5E 5ECE DA43 287F 86F5
uid                  me <me@myemail>
sub   2048R/29E4B752 2017-09-14

[root@myservername MISP]# mv ~/.gnupg /var/www/MISP/
[root@myservername MISP]# chown -R apache:apache /var/www/MISP/.gnupg
[root@myservername MISP]# gpg --list-key
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
[root@myservername MISP]# gpg-agent --homedir=/var/www/MISP/.gnupg --daemon &
[1] 13107
[root@myservername MISP]# GPG_AGENT_INFO=/var/www/MISP/.gnupg/S.gpg-agent:13108:1; export GPG_AGENT_INFO;

[1]+  Done                    gpg-agent --homedir=/var/www/MISP/.gnupg --daemon
[root@myservername MISP]# gpg --list-key
[root@myservername MISP]# cd /var/www/MISP/.gnupg
[root@myservername .gnupg]# export HOME=/var/www/MISP/
[root@myservername .gnupg]#  gpg --list-key
gpg: WARNING: unsafe ownership on configuration file `/var/www/MISP//.gnupg/gpg.conf'
/var/www/MISP//.gnupg/pubring.gpg
---------------------------------
pub   2048R/287F86F5 2017-09-14
uid                  me <me@myemail>
sub   2048R/29E4B752 2017-09-14

[root@myservername .gnupg]# gpg --list-secret-keys
gpg: WARNING: unsafe ownership on configuration file `/var/www/MISP//.gnupg/gpg.conf'
/var/www/MISP//.gnupg/secring.gpg
---------------------------------
sec   2048R/287F86F5 2017-09-14
uid                  me <me@myemail>
ssb   2048R/29E4B752 2017-09-14

[root@myservername .gnupg]# echo hello world | gpg --clearsign
gpg: WARNING: unsafe ownership on configuration file `/var/www/MISP//.gnupg/gpg.conf'

You need a passphrase to unlock the secret key for
user: "me <me@myemail>"
2048-bit RSA key, ID 287F86F5, created 2017-09-14

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

hello world
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQEcBAEBAgAGBQJZui/uAAoJEF7O2kMof4b1EVIH/200voLjEpHyDxFVvlYEAJD8
2oWTRMGL34zM1leE0nQnJP1nA7e1hgKDO2mpRxqIpiwK5uyo8Xffe53SI/VZrx6T
3uDC10MdN+lC7QTvhEXSK/XaJ9MA+GToNjWWm74PbQRBfJ2hkzGtR4iRMhdHL0As
PjFRquW+uQbrM0LcYEMdyvdzNceY3XWKsgeBkT/ekvDlHjdwsZYMV8HbTSL1r+g5
D4eMvNaalXDhiK2tpA9BMxKkh8+cs6l5YWpPGJBc30d0FbCSgWAfvwRmI3Oi2PiT
74ZE/AzOlx5TnSTzFsrmpZ8+HyemKmNac8tubf8VcgbMbwIbHpIusLTqv58TBPU=
=pTsK
-----END PGP SIGNATURE-----
[root@myservername .gnupg]#
```
I tried one more time (tired like 10 times before) to add the public key and it seems like it did accept it but then I got the error below

![image](https://user-images.githubusercontent.com/31463354/30417860-7c290cb6-9974-11e7-97a4-410d9c86e1ab.png)


however, if I navigate anywhere else is fine, I keep getting this page only when I select my profile!
"**No GPG key set in your profile. To receive emails, submit your public key in your profile.**" doesnt show in the home page anymore but, but still in the diagnostics !!

![image](https://user-images.githubusercontent.com/31463354/30418076-1e56ff84-9975-11e7-95e3-dc73f118f43f.png)
 

nothing related in the error logs (there's error related to another issue but will open different issue for that, to keep it tidy here)


```
2017-09-14 07:48:10 Error: [MissingControllerException] Controller class Api:9000Controller could not be found.
Exception Attributes: array (
  'class' => 'Api:9000Controller',
  'plugin' => NULL,
)
Request URL: /api:9000/modules
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2017-09-14 07:48:12 Error: [MissingControllerException] Controller class Api:9000Controller could not be found.
Exception Attributes: array (
  'class' => 'Api:9000Controller',
  'plugin' => NULL,
)
Request URL: /api:9000/modules
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-09-14 07:48:14 Error: [MissingControllerException] Controller class Api:9000Controller could not be found.
Exception Attributes: array (
  'class' => 'Api:9000Controller',
  'plugin' => NULL,
)
Request URL: /api:9000/modules
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
```

**Comment by adulau** [comment]
Do you have SELinux installed and enabled? Is there any enforcement of permissions on the directory or access to the socket of the agent?

**Comment by enkidunolinux** [comment]
@adulau 
```
cat /etc/sysconfig/selinux

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=enforcing
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted

 sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

```

**Comment by adulau** [comment]
Can you try without enforcing the security policies? To check if this is related.

**Comment by enkidunolinux** [comment]
you mean change the SELinux status to disabled?

**Comment by adulau** [comment]
Indeed ;-)

**Comment by enkidunolinux** [comment]
Ok things are changing now :)
not getting the previous error in my profile page
![image](https://user-images.githubusercontent.com/31463354/30419435-a58b5208-9979-11e7-84ff-9520dae9753e.png)


![image](https://user-images.githubusercontent.com/31463354/30419473-cde7a99a-9979-11e7-8b12-6d180828e4d0.png)

**Comment by iglocska** [comment]
That is new and interesting - is your PGP set up correctly? Could be a permission issue or invalid key/passphrase as suggested. Best way to test it is by trying it vial the commandline with the same homedir (--homedir directive).

**Comment by enkidunolinux** [comment]
as in what I did above? 
```
gpg: key 287F86F5 marked as ultimately trusted
public and secret key created and signed.

gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
pub   2048R/287F86F5 2017-09-14
      Key fingerprint = E826 DAB6 3869 EE02 0B81  4A5E 5ECE DA43 287F 86F5
uid                  me <me@myemail>
sub   2048R/29E4B752 2017-09-14

[root@myservername MISP]# mv ~/.gnupg /var/www/MISP/
[root@myservername MISP]# chown -R apache:apache /var/www/MISP/.gnupg
[root@myservername MISP]# gpg --list-key
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
[root@myservername MISP]# gpg-agent --homedir=/var/www/MISP/.gnupg --daemon &
[1] 13107
[root@myservername MISP]# GPG_AGENT_INFO=/var/www/MISP/.gnupg/S.gpg-agent:13108:1; export GPG_AGENT_INFO;

[1]+  Done                    gpg-agent --homedir=/var/www/MISP/.gnupg --daemon
[root@myservername MISP]# gpg --list-key
[root@myservername MISP]# cd /var/www/MISP/.gnupg
[root@myservername .gnupg]# export HOME=/var/www/MISP/
[root@myservername .gnupg]#  gpg --list-key
gpg: WARNING: unsafe ownership on configuration file `/var/www/MISP//.gnupg/gpg.conf'
/var/www/MISP//.gnupg/pubring.gpg
---------------------------------
pub   2048R/287F86F5 2017-09-14
uid                  me <me@myemail>
sub   2048R/29E4B752 2017-09-14

[root@myservername .gnupg]# gpg --list-secret-keys
gpg: WARNING: unsafe ownership on configuration file `/var/www/MISP//.gnupg/gpg.conf'
/var/www/MISP//.gnupg/secring.gpg
---------------------------------
sec   2048R/287F86F5 2017-09-14
uid                  me <me@myemail>
ssb   2048R/29E4B752 2017-09-14

[root@myservername .gnupg]# echo hello world | gpg --clearsign
gpg: WARNING: unsafe ownership on configuration file `/var/www/MISP//.gnupg/gpg.conf'

You need a passphrase to unlock the secret key for
user: "me <me@myemail>"
2048-bit RSA key, ID 287F86F5, created 2017-09-14

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

hello world
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQEcBAEBAgAGBQJZui/uAAoJEF7O2kMof4b1EVIH/200voLjEpHyDxFVvlYEAJD8
2oWTRMGL34zM1leE0nQnJP1nA7e1hgKDO2mpRxqIpiwK5uyo8Xffe53SI/VZrx6T
3uDC10MdN+lC7QTvhEXSK/XaJ9MA+GToNjWWm74PbQRBfJ2hkzGtR4iRMhdHL0As
PjFRquW+uQbrM0LcYEMdyvdzNceY3XWKsgeBkT/ekvDlHjdwsZYMV8HbTSL1r+g5
D4eMvNaalXDhiK2tpA9BMxKkh8+cs6l5YWpPGJBc30d0FbCSgWAfvwRmI3Oi2PiT
74ZE/AzOlx5TnSTzFsrmpZ8+HyemKmNac8tubf8VcgbMbwIbHpIusLTqv58TBPU=
=pTsK
-----END PGP SIGNATURE-----
[root@myservername .gnupg]
```#

**Comment by lostInSpaceSomewhere** [comment]
I have the same issue.  RHEL 7 - not on AWS, on premises.
![image](https://user-images.githubusercontent.com/7539605/38324924-94182e62-380f-11e8-9b3d-59a96707c473.png)

I also have the same issue when adding a key to a user, it fails then when looking at the user it throws the same error above.

I can go in with the admin account and remove the key and the user will them be able to view their profile again.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
