### ISSUE TITLE
MISP 2.4.80 breaks RESTful searches

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#2496]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue            | Bug
| OS version (server)   | Ubuntu 14.04 server
| OS version (client)     | Ubuntu 16.04 workstation
| PHP version               | 5.5.9-1ubuntu4.22
| Browser/client            | curl, pymisp==2.4.79, pymisp==2.4.80

### Expected behavior
Searches via the REST interface should return matching events.

### Actual behavior
MISP returns the error "The request has been black-holed."

### Steps to reproduce the behavior
I've tested using curl, and versions 2.4.79 and 2.4.80 of pymisp, each resulting in the same error. This appears to be a server (MISP) issue.

```
$ python
Python 2.7.12 (default, Jul 18 2016, 15:02:52) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymisp
... warnings about python 2 deleted ...
>>> print pymisp.__version__
2.4.79
>>> misp = pymisp.PyMISP(url='http://misp.my_domain', key='my_api_key')
>>> print misp.test_connection()  # success
True
>>> print misp.get_version()  # success
{u'version': u'2.4.80', u'perm_sync': False}
>>> print misp.get(1)  # success
{u'Event': { ... big blob of event data deleted ... }
print misp.search_all('10.1.1.1')
{u'url': u'/events/restSearch/download', u'message': u'The request has been black-holed', 'errors': [u'The request has been black-holed'], u'name': u'The request has been black-holed'}
>>> print misp.search(values='10.1.1.1')
{u'url': u'/events/restSearch/download', u'message': u'The request has been black-holed', 'errors': [u'The request has been black-holed'], u'name': u'The request has been black-holed'}
```
### Logs, screenshots, configuration dump, ...
From /var/www/MISP/app/tmp/logs/error.log

```
2017-09-20 08:32:21 Error: [BadRequestException] The request has been black-holed
Request URL: /events/restSearch/download
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(EventsController), 'auth', Object(AuthSecurityException))
#4 [internal function]: SecurityComponent->startup(Object(EventsController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by adulau** [comment]
This is an issue with the recent upgrade of CakePHP. We did roll-back to a previous version. Just do a `git pull && git submodule update` that should solve the issue.

https://github.com/MISP/MISP/commit/09dfb7aa147a4398141885e7f2fa7576ff89b08f

**Comment by ghost** [comment]
Thank you @adulau. I confirm that doing the following has fixed the issue for us.
```
$ git pull origin 2.4
$ git submodule update --init --force
```

**Comment by adulau** [comment]
@certau-user Thank you very much for the feedback. I'll close the issue.
