### ISSUE TITLE
SQL error when publishing new events

### ISSUE THREAD

**Issue by larsjsol** [MISP/MISP#2540]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

I have an issue where publishing new events fails. This started happening after several upgrades from version 2.4.65 to version 2.4.79.

I have a suspicion that this is caused by the last UPDATE query in shown in the log below. 

I would be grateful for any advice on how to fix this :)

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug(?)
| OS version (server)       | ubuntu xenial
| OS version (client)       | n/a
| PHP version               | 7.0.22
| MISP version / git hash   | 2.4.79
| Browser                   | If applicable

### Expected behavior
Publishing event completes without printing errors in the logs and jobs failing.

### Actual behavior
The 'prio' job fails. SQL errors are printed in the logs.

### Steps to reproduce the behavior
1. Log in to the web ui
2. Follow the 'Add event' link, fill in test values and press 'Add'
3. Open the new event and press 'Publish event'

### Logs, screenshots, configuration dump, ...
mysql general log:
```
2017-10-05T09:59:18.189206Z	451024 Query	START TRANSACTION
2017-10-05T09:59:18.189818Z	451024 Query	SELECT COUNT(*) AS `count` FROM `misp`.`events` AS `Event`   WHERE `Event`.`id` = 5601
2017-10-05T09:59:18.193281Z	451024 Query	SELECT COUNT(*) AS `count` FROM `misp`.`events` AS `Event`   WHERE `Event`.`id` = 5601
2017-10-05T09:59:18.196348Z	451024 Query	SELECT COUNT(*) AS `count` FROM `misp`.`events` AS `Event`   WHERE `Event`.`id` = 5601
2017-10-05T09:59:18.197098Z	451024 Query	UPDATE `misp`.`events` SET `id` = 5601, `info` = 'test please disregard', `published` = '1', `publish_timestamp` = 1507197558  WHERE `misp`.`events`.`id` = '5601'
2017-10-05T09:59:18.198422Z	451024 Query	UPDATE `misp`.`correlations` AS `Correlation`  SET `Correlation`.`info` = 'test please disregard'  WHERE `Correlation`.`event_id` = '\'5601\''
2017-10-05T09:59:18.198931Z	451024 Query	ROLLBACK
```
Notice the quoted and escaped event_id in the last update query.

MISP/app/tmp/error.log:
```
2017-10-05 11:42:51 Error: [PDOException] SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: ''5600''
Request URL: /events/5600
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('UPDATE `misp`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(415): DboSource->execute('UPDATE `misp`.`...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2670): Mysql->update(Object(AppModel), '`Correlation`.`...', NULL, ' WHERE `Correla...')
#4 /var/www/MISP/app/Model/Event.php(410): Model->updateAll(Array, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Event->afterSave(false, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1968): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#8 /var/www/MISP/app/Model/Event.php(2309): Model->save(Array, Array)
#9 /var/www/MISP/app/Controller/EventsController.php(1358): Event->_edit(Array, Array, '5600')
#10 [internal function]: EventsController->edit('5600')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
```

https://misp.example.com/jobs/index shows the 'prio' worker with failed 'publish_event' jobs

**Comment by iglocska** [comment]
Interesting, could you run and paste the outputs of the following commands?

```
describe events;
describe correlations;
describe logs;
```

**Comment by iglocska** [comment]
From mysql that is*

**Comment by flexd** [comment]
```
mysql> describe events;
+---------------------+------------------+------+-----+---------+----------------+
| Field               | Type             | Null | Key | Default | Extra          |
+---------------------+------------------+------+-----+---------+----------------+
| id                  | int(11)          | NO   | PRI | NULL    | auto_increment |
| date                | date             | NO   |     | NULL    |                |
| info                | text             | NO   | MUL | NULL    |                |
| user_id             | int(11)          | NO   |     | NULL    |                |
| published           | tinyint(1)       | NO   |     | 0       |                |
| uuid                | varchar(40)      | NO   | MUL | NULL    |                |
| attribute_count     | int(11) unsigned | YES  |     | 0       |                |
| analysis            | tinyint(4)       | NO   |     | NULL    |                |
| timestamp           | int(11)          | NO   |     | 0       |                |
| distribution        | tinyint(4)       | NO   |     | 0       |                |
| proposal_email_lock | tinyint(1)       | NO   |     | 0       |                |
| locked              | tinyint(1)       | NO   |     | 0       |                |
| threat_level_id     | int(11)          | NO   |     | NULL    |                |
| publish_timestamp   | int(11)          | NO   |     | 0       |                |
| sharing_group_id    | int(11)          | NO   |     | 0       |                |
| org_id              | int(11)          | NO   |     | 0       |                |
| orgc_id             | int(11)          | NO   |     | 0       |                |
| disable_correlation | tinyint(1)       | NO   |     | 0       |                |
+---------------------+------------------+------+-----+---------+----------------+
18 rows in set (0.01 sec)

mysql> describe correlations;
+--------------------+------------+------+-----+---------+----------------+
| Field              | Type       | Null | Key | Default | Extra          |
+--------------------+------------+------+-----+---------+----------------+
| id                 | int(11)    | NO   | PRI | NULL    | auto_increment |
| value              | text       | NO   |     | NULL    |                |
| 1_event_id         | int(11)    | NO   | MUL | NULL    |                |
| 1_attribute_id     | int(11)    | NO   | MUL | NULL    |                |
| 1_private          | tinyint(1) | NO   |     | 0       |                |
| event_id           | int(11)    | NO   |     | NULL    |                |
| attribute_id       | int(11)    | NO   | MUL | NULL    |                |
| private            | tinyint(1) | NO   |     | NULL    |                |
| date               | date       | NO   |     | NULL    |                |
| info               | text       | NO   |     | NULL    |                |
| org_id             | int(11)    | NO   |     | 0       |                |
| distribution       | tinyint(4) | NO   |     | 0       |                |
| a_distribution     | tinyint(4) | NO   |     | 0       |                |
| sharing_group_id   | int(11)    | NO   |     | 0       |                |
| a_sharing_group_id | int(11)    | NO   |     | 0       |                |
+--------------------+------------+------+-----+---------+----------------+
15 rows in set (0.00 sec)

mysql> describe logs;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| title       | text         | YES  |     | NULL    |                |
| created     | datetime     | YES  |     | NULL    |                |
| model       | varchar(20)  | YES  |     | NULL    |                |
| model_id    | int(11)      | YES  |     | NULL    |                |
| action      | varchar(20)  | YES  |     | NULL    |                |
| user_id     | int(11)      | YES  |     | NULL    |                |
| change      | text         | NO   |     | NULL    |                |
| email       | varchar(255) | NO   |     |         |                |
| org         | varchar(255) | NO   |     |         |                |
| description | text         | YES  |     | NULL    |                |
| ip          | varchar(45)  | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
12 rows in set (0.01 sec)
```

**Comment by iglocska** [comment]
That looks fine (you're running a pretty old instance that has been upgraded over the years I guess, seeing the private fields - pre 2.4 ;)).

Something to try: Go to administration server settings -> diagnostics -> clean model cache

See if that fixes it.

Could you also run and paste the following?

```
describe jobs;
```

As publishing should create a background job - maybe that's where we have an incorrect datetime field (if that is indeed the issue and not simply model caching).

**Comment by flexd** [comment]
Cleaning the model cache did not resolve the problem. The job fails with the same error message as before.
```
mysql> describe jobs;
+---------------+-------------+------+-----+---------+----------------+
| Field         | Type        | Null | Key | Default | Extra          |
+---------------+-------------+------+-----+---------+----------------+
| id            | int(11)     | NO   | PRI | NULL    | auto_increment |
| worker        | varchar(32) | NO   |     | NULL    |                |
| job_type      | varchar(32) | NO   |     | NULL    |                |
| job_input     | text        | NO   |     | NULL    |                |
| status        | tinyint(4)  | NO   |     | 0       |                |
| retries       | int(11)     | NO   |     | 0       |                |
| message       | text        | NO   |     | NULL    |                |
| progress      | int(11)     | NO   |     | 0       |                |
| process_id    | varchar(32) | YES  |     | NULL    |                |
| org_id        | int(11)     | NO   |     | 0       |                |
| date_created  | datetime    | NO   |     | NULL    |                |
| date_modified | datetime    | NO   |     | NULL    |                |
+---------------+-------------+------+-----+---------+----------------+
12 rows in set (0.00 sec)

```

**Comment by larsjsol** [comment]
@iglocska do you have any other suggestions? We are still experiencing this problem and would really appreciate any help we could get in fixing it.

**Comment by iglocska** [comment]
Sorry been a little bit swamped. Is your instance in production? If not we can try some more drastic measures:

1. Disable the background processing (administration -> server settings -> background_jobs)
2. Enable debugging (Administration -> server settings -> security -> debug on

If it's in production: 

1.  first put your MISP into disabled mode: Administration -> Server settings -> live to false (this will only allow site admins to log in)
2. enable site admin debug (Administration -> server settings -> security -> site_admin_debug)

Now try to publish an event and you should get a stack trace. Could you paste that here?

**Comment by flexd** [comment]
@iglocska Thanks for getting back to us! The instance is in production, and I have tried the steps you suggested in scenario 2.

Adding a event gives no stack trace. Only the publishing background job fails, as it did before. 

I'm looking through logs now, but so far I have not seen anything useful.

**Comment by flexd** [comment]
```
2017-10-10 12:40:05 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 87]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 87
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error400() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 236
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2017-10-10 12:40:05 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Layouts/default.ctp, line 102]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 102
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error400() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 236
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??
```

I just found these in debug.log

**Comment by flexd** [comment]
```
2017-10-13 11:44:12 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'private' doesn't have a default value
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(898): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Attribute.php(1571): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /var/www/MISP/app/Model/Attribute.php(555): Attribute->__afterSaveCorrelation(Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1968): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#6 /var/www/MISP/app/Model/Event.php(2208): Model->save(Array, Array)
#7 /var/www/MISP/app/Controller/EventsController.php(1111): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#8 [internal function]: EventsController->add()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
```
And this earlier.

**Comment by iglocska** [comment]
Ahhh perfect, so it was indeed the leftover stuff from the upgrade long long time ago. So basically what happens is that a field that has been removed from MISP ages ago still exists in your database and updates fail when they stay unset. Let's resolve this:

```
ALTER TABLE correlations DROP COLUMN private;
ALTER TABLE correlations DROP COLUMN 1_private;
```

Once done go to administration -> server settings -> diagnostics -> clean model cache. Don't forget to re-enable background jobs, to disable debug mode and to put misp back into "live" state. 

Let me know if the issue persists and sorry it took this long ;)

**Comment by flexd** [comment]
Excellent! We are making progress. Unfortunately, the publishing jobs still fail.

```
[2017-10-13 14:51:54] main.ERROR: {"queue":"prio","id":"04a7b1af68985fed758b8e8b8c09f28c","class":"EventShell","args":[["publish","5657",null,"7111","1"]]} failed: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: ''5657'' {"type":"fail","log":"SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: ''5657''","job_id":"04a7b1af68985fed758b8e8b8c09f28c","time":114,"worker":"misp:20243"} []
`

**Comment by iglocska** [comment]
Could you check the exact commit ID you are on? The problem is that the datetime issue comes from line 410 in event.php in your logs and for me that line is an empty line, so Event.php has changed since your version already ;)

**Comment by flexd** [comment]
* (HEAD detached at v2.4.79)
commit 4ba21c5770c64998712187c2b48aa502bfd84a6c is the latest entry in git log.

**Comment by iglocska** [comment]
If you look at the event itself, what is the "date" of the event? Does it show up correctly as a date in the yyyy-mm-dd format?

**Comment by flexd** [comment]
The date of the event itself is correct. The SQL error looks to me that it is trying to put the id "5657" into a datetime format field. 5657 is the event ID.

It fails on the query ```UPDATE `misp`.`correlations` AS `Correlation`  SET `Correlation`.`info` = 'test please disregard'  WHERE `Correlation`.`event_id` = '\'5601\''``` 
If we correct the query to
```
UPDATE `misp`.`correlations` AS `Correlation`  SET `Correlation`.`info` = 'test please disregard'  WHERE `Correlation`.`event_id` = 5601''
``` 
It seems to execute fine.

So my theory is that something is wrong with the correlations table, or that the code does not match what  the table looks like.

**Comment by iglocska** [comment]
```
UPDATE `misp`.`correlations` AS `Correlation` SET `Correlation`.`info` = 'test please disregard' WHERE `Correlation`.`event_id` = '\'5601\''
```

hmph this works fine for me...

**Comment by iglocska** [comment]
Which version of MYSQL are you using?

**Comment by flexd** [comment]
That fails with
 ```
mysql> UPDATE `misp`.`correlations` AS `Correlation` SET `Correlation`.`info` = 'test please disregard' WHERE `Correlation`.`event_id` = '\'5601\'';
ERROR 1292 (22007): Truncated incorrect DOUBLE value: ''5601''
```
for me. 

Running mysql-server-5.7

**Comment by iglocska** [comment]
ok, finally I reproduced it. Could you git pull and give it a shot?

**Comment by flexd** [comment]
Unfortunately I left work for the weekend :) I'll try it out first thing on Monday.

**Comment by iglocska** [comment]
Sure just let me know how it goes, and have a nice weekend!

**Comment by flexd** [comment]
Hey there! I just tried pulling the latest in the 2.4 branch (I can see the commit you made).
Unfortunately this still fails with the same error message.

**Comment by iglocska** [comment]
Back to the drawing board. You're not at Hack.lu by any chance this week?

**Comment by flexd** [comment]
@iglocska Unfortunately no, I wish. But we should be on some of the same IRC servers, that would make trying out things a bit quicker. First IRC, for example? Some of your colleagues are there.

**Comment by flexd** [comment]
@iglocska We are still experiencing this. Any new ideas?

**Comment by larsjsol** [comment]
> UPDATE `misp`.`correlations` AS `Correlation` SET `Correlation`.`info` = 'test please disregard' WHERE >`Correlation`.`event_id` = '\'5601\''
> hmph this works fine for me...

Hi there @iglocska, which version of MySQL is it you are testing on? Would you mind telling us what sql_mode is set to? (you can check by running `select @@global.sql_mode;` and `select @@session.sql_mode` )

We are running version 5.7.20 with `sql_mode` set to `ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`.

**Comment by iglocska** [comment]
both are:

`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

Version is MariaDB 10.1.25

**Comment by larsjsol** [comment]
Thanks

The reason I asked was that  I was hoping that the query working for you and not for us could be explained by different `sql_mode`. I was able to publish events by setting `sql_mode` to just `NO_ENGINE_SUBSTITUTION`. This is a dirty workaround as this just causes the query to fail silently.

Is still think the failing query looks a bit odd. Is it really expected behavior for MISP to compare a string with escaped quotes (`'\'5601\''`) to an integer?

**Comment by iglocska** [comment]
Will try to reproduce it this afternoon, currently in a training but can play around trying to break stuff. Will get back to you soon ;)

**Comment by larsjsol** [comment]
> Will try to reproduce it this afternoon,

Great! Thanks alot :)

**Comment by iglocska** [comment]
Slight delays but the above commit should resolve it! Let me know if it doesn't.

**Comment by larsjsol** [comment]
Pulling that commit fixed the issue. Thank you!

**Comment by iglocska** [comment]
Excellent news B-) Sorry for the massive delays.
