### ISSUE TITLE
Upload ZIP not possible

### ISSUE THREAD

**Issue by c-goes** [MISP/MISP#2610]
Possible bug in MISP

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | Not applicable

### Expected behavior

ZIP file can be uploaded with add_file_object.py

### Actual behavior

ZIP file cannot be uploaded using  add_file_object.py

### Steps to reproduce the behavior

1. Upload zip file with add_file_object.py

### Logs, screenshots, configuration dump, ...

```javascript
2017-10-30 15:53:51 Error: [InternalErrorException] Composite type, but value not explodable
Request URL: /objects/add/20/9
Stack Trace:
\#0 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->beforeSave(Array)
\#1 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Model/Model.php(1871): CakeEventManager->dispatch(Object(CakeEvent))
\#2 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
\#3 /opt/misp-server/misp/app/Model/Attribute.php(2495): Model->save(Array)
\#4 /opt/misp-server/misp/app/Model/MispObject.php(108): Attribute->saveAttributes(Array)
\#5 /opt/misp-server/misp/app/Controller/ObjectsController.php(170): MispObject->saveObject(Array, '20', Array, Array, 'halt')\
\#6 [internal function]: ObjectsController->add('20', '9')
\#7 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ObjectsController), Array)
\#8 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
\#9 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ObjectsController), Object(CakeRequest))
\#10 /opt/misp-server/misp/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
\#11 {main}
```

**Comment by Rafiot** [comment]
Most probably fixed by https://github.com/MISP/PyMISP/commit/75d96b2d7a89406997035a1715de7c3cbce2303b
