### ISSUE TITLE
Internal error when doing OpenIOC import through the web interface

### ISSUE THREAD

**Issue by spacepatcher** [MISP/MISP#2699]
# Possible bug in OpenIOC importing thru MISP web-interface

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04.2 LTS
| OS version (client)       | Ubuntu 16.04.2 LTS
| PHP version               | 7.1
| MISP version / git hash   | 2.4.82, b7b09b7cdb92bf15e2bc9853f10f121fccf26d32
| Browser                   | Chrome

### Expected behavior
Link to MISP event vith imported data from `.ioc` file

### Actual behavior
Internal Error (message from /var/www/MISP/app/tmp/logs/error.log):
```
2017-12-01 13:40:10 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'sharing_group_id' doesn't have a default value
Request URL: /events/addIOC/22238
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1090): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(Attribute), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1752): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2350): Model->save(Array, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2570): Model->saveMany(Array, Array)
#7 /var/www/MISP/app/Controller/EventsController.php(2436): Model->saveAssociated(Array, Array)
#8 /var/www/MISP/app/Controller/EventsController.php(1326): EventsController->_addIOCFile('22238')
#9 [internal function]: EventsController->addIOC('22238')
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

### Steps to reproduce the behavior
View Event: "Populate From" -> "OpenIOC Import" -> "Upload" = "Error: An Internal Error Has Occurred."

### OpenIOC file for tests
Link: https://github.com/STIXProject/openioc-to-stix/blob/master/examples/duqu.ioc.xml

**Comment by spacepatcher** [comment]
| Questions                 | Answers
|---------------------------|--------------------
| MISP version / git hash   | 2.4.84, ced7db17e9418e9033053f18bc91323a840d08ef

For a newer version, the problem is also relevant.

Please pay attention.
