### ISSUE TITLE
STIX 2 export issue with event without tags

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#2741]
STIX 2 export issue with event without tags

~~~~
Traceback (most recent call last):
  File "/var/www/MISP-priv/app/files/scripts/stix2/misp2stix2.py", line 766, in <module>
    main(sys.argv)
  File "/var/www/MISP-priv/app/files/scripts/stix2/misp2stix2.py", line 757, in main
    report = eventReport(misp, identity, object_refs, external_refs)
  File "/var/www/MISP-priv/app/files/scripts/stix2/misp2stix2.py", line 719, in eventReport
    if 'Tag' in event:
  File "/usr/lib/python3.4/_collections_abc.py", line 428, in __contains__
    self[key]
  File "/usr/local/lib/python3.4/dist-packages/pymisp/abstract.py", line 68, in __getitem__
    return getattr(self, key)
AttributeError: 'MISPEvent' object has no attribute 'Tag'
~~~~

**Comment by adulau** [comment]
@chrisr3d fixed the issue in recent version.
