### ISSUE TITLE
Whois expansion module throws error

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2769]
When querying the whois module on our 2.4.85 instance the GUI tells us _Error: An Internal Error Has Occurred_ while error.log contains:

```
2017-12-28 13:34:46 Error: Fatal Error (1): Call to undefined function ctype_alnum() in [/services/inst/misp/app/Lib/Tools/ComplexTypeTool.php, line 297]
2017-12-28 13:34:46 Error: [InternalErrorException] Internal Server Error
Request URL: /events/queryEnrichment/984642/whois/Enrichment
Stack Trace:
#0 /services/inst/misp/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/services/inst/...', 297)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/services/inst/...', 297, Array)
#2 /services/inst/misp/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/services/inst/...', 297, Array)
#3 /services/inst/misp/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

Maybe this is due to the PHP version being used on our server (5.5.14)?

**Comment by adulau** [comment]
Just to be sure do you have the `php-ctype` package loaded?

**Comment by StefanKelm** [comment]
`php-ctype` wasn't installed on the system (since it was not documented as a dependency within https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.debian8.txt).

We've installed that package but the error remains.

**Comment by StefanKelm** [comment]
Apparently resolved.
