### ISSUE TITLE
Unknown column Object.distribution when doing attribute search

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#2855]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu, ...
| PHP version               | 7.1
| MISP version / git hash   | 2.4.86 (04c89499a234da5d6596a711fb65522b5c793a23) detached head

### Expected behavior
Search should return with results (or no results)

### Actual behavior
It appears that when searching as a role below an administrator, attempting to use the attribute search at:
/attributes/search, an Internal Server Error is returned, with the following error:
```
2018-01-18 15:40:23 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Object.distribution' in 'where clause'
Request URL: /attributes/search
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Attribute), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Attribute), Array, Array)
#8 /var/www/MISP/app/Controller/AttributesController.php(1671): Controller->paginate()
#9 [internal function]: AttributesController->search()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

Do you think this has got something possibly to do with the blocking of viewing Sharing Groups or other organisations on the site? Could be restricting access if not authorised to view.

### Steps to reproduce the behavior
Create a low-permission account (broken with Publisher, User, but not admin), and attempt to use the search.

**Comment by tomking2** [comment]
Just realised it's already been resolved!
