### ISSUE TITLE
Updating Taxonomies on new installation throws " An Internal Error Has Occurred.  Error: An Internal Error Has Occurred."

### ISSUE THREAD

**Issue by HachimanSec** [MISP/MISP#2964]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Debian
| PHP version               | 7.0.27-0+deb9u1 (Up to date)
| MISP version / git hash   | v2.4.87 (f6b9e07986e829b2a9204f272f35675dee8f41a4) 
| Browser                   | If applicable

### Expected behavior
List taxonomies and tags

### Actual behavior
I have a new installation of MISP and just updated the taxonomies. 
After the update I always receive an error clicking on Events -> List Taxonomies:

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

The same is true when I click on List Tags, same error as above. 

### Logs, screenshots, configuration dump, ...
<img width="636" alt="screen shot 2018-02-25 at 19 49 06" src="https://user-images.githubusercontent.com/20123996/36645155-f96406ba-1a64-11e8-8147-02f15622a429.png">

**Comment by adulau** [comment]
Could you check the permission of the  <YOUR-MISP>/app/files/taxonomies? and ensure `git submodule update` works. You can also have a look at the error logs <YOUR-MISP>app/tmp/logs/error.log? and copy the error output?

**Comment by HachimanSec** [comment]
Thank you for the very quick reply. 

Please finde the permission output for taxonomies below:
```
sudo ls -lat ./var/www/MISP/app/files/taxonomies
total 268
drwxrws--- 120 www-data www-data  4096 Feb 25 18:49 ..
drwxrws---  54 www-data www-data  4096 Feb 19 20:37 .
drwxrws---   4 www-data www-data  4096 Feb 19 20:37 tools
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 tor
-rwxrws---   1 www-data www-data   571 Feb 19 20:37 validate_all.sh
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 veris
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 vocabulaire-des-probabilites-estimatives
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 workflow
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 domain-abuse
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 ecsirt
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 enisa
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 estimative-language
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 eu-marketop-and-publicadmin
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 euci
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 europol-event
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 europol-incident
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 event-assessment
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 fr-classif
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 honeypot-basic
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 iep
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 information-security-indicators
-rwxrws---   1 www-data www-data   290 Feb 19 20:37 jq_all_the_things.sh
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 kill-chain
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 malware_classification
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 mapping
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 misp
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 ms-caro-malware
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 ms-caro-malware-full
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 nato
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 open_threat
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 osint
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 passivetotal
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 rt_event_status
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 runtime-packer
-rwxrws---   1 www-data www-data  2682 Feb 19 20:37 schema.json
-rwxrws---   1 www-data www-data   467 Feb 19 20:37 schema_mapping.json
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 stealth_malware
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 stix-ttp
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 targeted-threat-index
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 tlp
-rwxrws---   1 www-data www-data   349 Feb 19 20:37 .travis.yml
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 DML
-rwxrws---   1 www-data www-data 10752 Feb 19 20:37 MANIFEST.json
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 PAP
-rwxrws---   1 www-data www-data 14202 Feb 19 20:37 README.md
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 accessnow
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 action-taken
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 admiralty-scale
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 adversary
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 ais-marking
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 analyst-assessment
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 binary-class
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 circl
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 collaborative-intelligence
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 csirt_case_classification
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 cssa
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 ddos
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 de-vs
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 dhs-ciip-sectors
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 diamond-model
drwxrws---   2 www-data www-data  4096 Feb 19 20:37 dni-ism
-rwxrws---   1 www-data www-data    51 Feb 19 20:37 .git
```

**Comment by HachimanSec** [comment]
The last ouptut from the error.log : 
```
2018-02-25 18:36:41 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /taxonomies/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT COUNT(*)...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT COUNT(*)...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT COUNT(*)...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('count', Array)
#6 /var/www/MISP/app/Controller/TaxonomiesController.php(31): Model->find('count', Array)
#7 [internal function]: TaxonomiesController->index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TaxonomiesController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TaxonomiesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2018-02-25 18:36:44 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Tag), Array, Array)
#8 /var/www/MISP/app/Controller/TagsController.php(70): Controller->paginate()
#9 [internal function]: TagsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-02-25 18:39:01 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /tags
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Tag), Array, Array)
#8 /var/www/MISP/app/Controller/TagsController.php(70): Controller->paginate()
#9 [internal function]: TagsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-02-25 18:39:04 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Tag), Array, Array)
#8 /var/www/MISP/app/Controller/TagsController.php(70): Controller->paginate()
#9 [internal function]: TagsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-02-25 18:39:08 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /tags/index/1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Tag), Array, Array)
#8 /var/www/MISP/app/Controller/TagsController.php(70): Controller->paginate()
#9 [internal function]: TagsController->index('1')
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-02-25 18:43:00 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /taxonomies/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT COUNT(*)...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT COUNT(*)...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT COUNT(*)...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('count', Array)
#6 /var/www/MISP/app/Controller/TaxonomiesController.php(31): Model->find('count', Array)
#7 [internal function]: TaxonomiesController->index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TaxonomiesController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TaxonomiesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2018-02-25 18:47:45 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /taxonomies/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT COUNT(*)...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT COUNT(*)...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT COUNT(*)...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('count', Array)
#6 /var/www/MISP/app/Controller/TaxonomiesController.php(31): Model->find('count', Array)
#7 [internal function]: TaxonomiesController->index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TaxonomiesController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TaxonomiesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2018-02-25 18:48:22 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Tag), Array, Array)
#8 /var/www/MISP/app/Controller/TagsController.php(70): Controller->paginate()
#9 [internal function]: TagsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-02-25 18:51:40 Error: Fatal Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 724]
2018-02-25 18:51:40 Error: [InternalErrorException] Internal Server Error
Request URL: /events/view/4086
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 724)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 724, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-02-25 18:53:06 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Controller/EventsController.php, line 885]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
EventsController::viewEventAttributes() - APP/Controller/EventsController.php, line 885
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2018-02-25 18:56:23 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Tag), Array, Array)
#8 /var/www/MISP/app/Controller/TagsController.php(70): Controller->paginate()
#9 [internal function]: TagsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}

```

**Comment by adulau** [comment]
Interesting. Could you update to 2.4.88? a simple `git pull origin 2.4` and then logout-login via the web interface. And let us know.

**Comment by HachimanSec** [comment]
I tried an update via web interface, this is the result: 
```
git pull origin  2>&1

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>


=================================

git submodule init && git submodule update 2>&1

```

I am quite new to git, would I have to execute this command in /var/www/MISP? Which is no accessible except for www-data and I would have to change the nologin option to get there.

**Comment by HachimanSec** [comment]
Just added my user to www-data group and executed the command in /var/www/MISP:
```
git pull origin 2.4
error: cannot open .git/FETCH_HEAD: Permission denied
```

**Comment by HachimanSec** [comment]
```
sudo -u www-data git pull origin 2.4
From https://github.com/MISP/MISP
 * branch              2.4        -> FETCH_HEAD
Updating f6b9e079..22b1d787
Fast-forward
 .gitignore                                             |   2 +
 INSTALL/INSTALL.ubuntu1604.txt                         |  18 +++
 INSTALL/MYSQL.sql                                      |   5 +-
 PyMISP                                                 |   2 +-
 README.md                                              |   2 +-
 VERSION.json                                           |   2 +-
 app/Console/worker/start.sh                            |   2 +-
 app/Controller/AppController.php                       |   4 +-
 app/Controller/AttributesController.php                |  28 ++---
 app/Controller/Component/ACLComponent.php              |  10 ++
 app/Controller/Component/RestResponseComponent.php     |  15 ++-
 app/Controller/EventsController.php                    | 476 ++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------
 app/Controller/GalaxiesController.php                  |   3 +
 app/Controller/GalaxyClustersController.php            |  21 ++++
 app/Controller/ModulesController.php                   |  66 +++++++++++
 app/Controller/OrganisationsController.php             |  35 +++++-
 app/Controller/ServersController.php                   |   7 --
 app/Controller/ShadowAttributesController.php          |   4 +-
 app/Controller/SharingGroupsController.php             | 153 +++++++++++++++++++++++++
 app/Controller/SightingsController.php                 |   3 +
 app/Controller/TagsController.php                      |  26 ++++-
 app/Controller/UsersController.php                     |  44 ++++----
 app/Lib/Tools/JSONConverterTool.php                    |   3 +-
 app/Model/AppModel.php                                 |  21 +++-
 app/Model/Attribute.php                                |  77 +++++++++++--
 app/Model/Event.php                                    |  35 ++++++
 app/Model/FuzzyCorrelateSsdeep.php                     |  94 ++++++++++++++++
 app/Model/ObjectReference.php                          |   2 +-
 app/Model/ObjectTemplateElement.php                    |   6 +-
 app/Model/Organisation.php                             |  42 ++++++-
 app/Model/Server.php                                   |  42 ++++---
 app/Model/SharingGroup.php                             |  29 +++++
 app/Model/User.php                                     |  17 ++-
 app/View/Attributes/ajax/attributeConfirmationForm.ctp |   6 +-
 app/View/Attributes/search.ctp                         |   5 +-
 app/View/Elements/Events/View/row_attribute.ctp        |   4 +-
 app/View/Elements/Events/View/row_object.ctp           |   4 +-
 app/View/Elements/eventattribute.ctp                   |  10 +-
 app/View/Elements/footer.ctp                           |   9 +-
 app/View/Elements/global_menu.ctp                      |   1 +
 app/View/Elements/side_menu.ctp                        |   2 +-
 app/View/Events/ajax/exportChoice.ctp                  |  40 ++++++-
 app/View/Events/index.ctp                              |   1 +
 app/View/Events/upload_stix.ctp                        |  29 +++++
 app/View/Events/view.ctp                               |   1 +
 app/View/Galaxies/view.ctp                             |   6 +-
 app/View/GalaxyClusters/ajax/index.ctp                 |  32 ++++++
 app/View/Organisations/admin_edit.ctp                  |  12 ++
 app/View/Organisations/ajax/merge.ctp                  |  14 ++-
 app/View/Sightings/ajax/list_sightings.ctp             |   2 +-
 app/View/Tags/ajax/select_tag.ctp                      |  16 ++-
 app/View/Tags/ajax/taxonomy_choice.ctp                 |  12 +-
 app/files/feed-metadata/defaults.json                  | 448 ++++++++++++++++++++++++++++++++++++++++++++----------------------------
 app/files/misp-galaxy                                  |   2 +-
 app/files/misp-objects                                 |   2 +-
 app/files/scripts/misp2stix_framing.py                 |   2 +
 app/files/scripts/stix2misp.py                         |  48 ++++++--
 app/files/taxonomies                                   |   2 +-
 app/files/warninglists                                 |   2 +-
 app/webroot/css/main.css                               |  33 ++++++
 app/webroot/js/misp.js                                 | 149 +++++++++++++++++++++---
 app/webroot/shortcuts/event_index.json                 |   9 ++
 app/webroot/shortcuts/event_view.json                  |  24 ++++
 app/webroot/shortcuts/global_menu.json                 |  14 +++
 tools/misp-wipe/misp-wipe.sh                           |  14 +++
 tools/misp-wipe/misp-wipe.sql                          |  10 ++
 66 files changed, 1752 insertions(+), 509 deletions(-)
 mode change 100644 => 100755 .gitignore
 create mode 100755 app/Controller/ModulesController.php
 create mode 100644 app/Model/FuzzyCorrelateSsdeep.php
 create mode 100644 app/View/Events/upload_stix.ctp
 create mode 100644 app/webroot/shortcuts/event_index.json
 create mode 100644 app/webroot/shortcuts/event_view.json
 create mode 100644 app/webroot/shortcuts/global_menu.json
```

**Comment by HachimanSec** [comment]
Update seemd to work:
```
Currently installed version… v2.4.88 (22b1d787222c7d6ce57cc9c9264164c2b82c0f42)
Latest available version… v2.4.88 (22b1d787222c7d6ce57cc9c9264164c2b82c0f42)
Status… OK
Current branch… 
```

List taxonomies now work too! Don't know why but thank you 👍

**Comment by adulau** [comment]
@TomHubGit You're welcome. Have fun with MISP ;-)

**Comment by HachimanSec** [comment]
Thank you @adulau , I am sure I will ;)
