### ISSUE TITLE
extra comma in JSON : PyMISP example complains about server side being broken

### ISSUE THREAD

**Issue by philpraxis** [MISP/MISP#3084]
In some queries, there seem to be an extra comma "," just before the last line of the JSON.
Maybe this is me, but looks like differing output depending on search string.
As the PyMISP scripts says: 
> pymisp.exceptions.PyMISPError: Unknown error (something is very broken server-side: {"response": ...
So I'm submitting here in MISP issues.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Probable Bug 
| OS version (server)       | mispXXXX.circl.TLD
| OS version (client)       | 10.12.6
| PHP version               | unknow, current online
| MISP version / git hash   | unknown, current online
| Browser                   | Python 3.6.4

### Expected behavior
no error message in PyMISP requests, just as in search like: 
> ./searchall.py -s phone-number

### Actual behavior
error message from the examples/searchall.py complaining about 
There seem to be an extra comma "," just before the last line of the JSON

```
[...]
                "exportable": true,
                "hide_tag": false,
                "user_id": "0"
            }
        ]
    }
}, <--------- This is the comma that example script (and jq) is complaining about
]}
```

### Steps to reproduce the behavior
> ./searchall.py -s eternal

### Logs, screenshots, configuration dump, ...

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 217, in _check_response
>     to_return = response.json()
>   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 506640 column 1 (char 20803485)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./searchall.py", line 41, in <module>
>     searchall(misp, args.search, args.quiet, misp_url, args.output)
>   File "./searchall.py", line 16, in searchall
>     result = m.search_all(search)
>   File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 1015, in search_all
>     return self.__query('restSearch/download', query)
>   File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 952, in __query
>     return self._check_response(response)
>   File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 220, in _check_response
>     raise PyMISPError('Unknown error (something is very broken server-side: {})'.format(response.text))
> pymisp.exceptions.PyMISPError: Unknown error (something is very broken server-side: {"response":[{
>     "Event": {
>         "id": "387",
>         "orgc_id": "2",
>         "org_id": "2",
[...]
>                 "exportable": true,
>                 "hide_tag": false,
>                 "user_id": "0"
>             }
>         ]
>     }
> }, <--------- This is the comma that example script (and jq) is complaining about
> ]}
>

**Comment by philpraxis** [comment]
Ok, this is fixed now.
Thanks.
