### ISSUE TITLE
CSVImport.py - "Something went wrong, look in the server logs for details"

### ISSUE THREAD

**Issue by woosha** [MISP/MISP#3189]
Hi,

I receive in MISP "Something went wrong, look in the server logs for details" when attempting to import a csv file. I have also tested the testimport.py and works fine. 

When trying to use the CSVimport.py to import a CSV file i get this error above by MISP. I have checked delimiters etc details that the python script is checking for as well as csv UTF-8 etc to ensure are correct with no luck so far.

Looking at the server side i see the following: 

2018-04-24 16:02:36,599 - misp-modules - ERROR - Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/import_mod/csvimport.py", line 114, in handler
    config = request['config'].get('header').split(',')
AttributeError: 'NoneType' object has no attribute 'split'
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/import_mod/csvimport.py", line 114, in handler
    config = request['config'].get('header').split(',')
AttributeError: 'NoneType' object has no attribute 'split'

I have also enabled STIXimport python script to see if I will receive the same error and when tried importing STIXsample.xml I received the same error. any help would be much appreciated. thanks

**Comment by adulau** [comment]
Do you have an extract or sample of the CSV file?

**Comment by woosha** [comment]
Hi,

Please be aware that I have test several scenarios:

1) extract directly from a MISP event in CSV format and import on the new created event
2) Add only one value in excel (i.e. md5) - with the expected event titles (i.e. Value, etc) and without 
3) add hostnames/IP etc only

Screenshot below: (all tested files were saved both in CSV UTF-8 (Comma delimited) and Comma Separated Values when testing). Also, all files were opened in a notepad to ensure no unexpected characters were inserted etc.

![example](https://user-images.githubusercontent.com/37815445/39230079-1f4aa35e-485d-11e8-8a11-1d7383e9a119.jpg)

thanks

**Comment by woosha** [comment]
Update: I have also tested importing a STIXsample.xml file and get the same errors. Could there be a dependency causing this

**Comment by cathy927** [comment]
Hi, I met this problem as well. T-T
Furthermore, the csv file downloaded in Search Attributes result is empty.
Looking forward to the solution!
Thank you!

**Comment by adulau** [comment]
@chrisr3d could you update the CSV import to support single column CSV? ;-) Thanks

**Comment by woosha** [comment]
@adulau Hey - as mentioned above, i have tested this scenario as well which didnt work for me either. thanks

**Comment by woosha** [comment]
![screen shot 2018-04-25 at 10 14 59](https://user-images.githubusercontent.com/37815445/39236783-91f684d6-4871-11e8-891b-b16e2169a84a.png)
![screen shot 2018-04-25 at 10 14 52](https://user-images.githubusercontent.com/37815445/39236789-986e36d8-4871-11e8-94b2-a15e62fd2d52.png)

**Comment by mrjoshua** [comment]
I too am having problems with importing CSV files both domain and ip addr as well. I cannot find any syntax references or guidance in the documentation on the settings or the specific setting "Plugin.Import_csvimport_header"

 failed [value]: IP address has an invalid format.

Anyone have any guidance on what that setting should be, are there specific header types that are required etc...

--Thanks in advance

**Comment by chrisr3d** [comment]
I just updated the module to have the header in user configuration side.

You can find some instructions about this update in: https://github.com/MISP/misp-modules/pull/190
Hope it can help you

Don't hesitate to ping me if you have any further question

**Comment by mrjoshua** [comment]
Thank you very much I will do a new pull and test this out.

**Comment by woosha** [comment]
thanks @chrisr3d. Even when i parse one header in excel for the time being, I receive "_0 attributes created. 4 attributes could not be saved. This may be due to attributes with similar values already existing_" on several scenarios that i tried when importing data from a csv. the Testimport script works though. Any ideas? Thanks

**Comment by woosha** [comment]
also if you try to import only one value (i.e. a hostname), i receive the following: " _0 attributes created. 1 attributes could not be saved. Reason for the failure: {"type":["Options depend on the selected category."],"category":["Options : Payload delivery, Antivirus detection, Payload installation, Files dropped ..."],"value":["Value not in the right type\/format. Please double check the value or select type \"other\"."]}"_ . I tested to use a MISP header to  see if it will be able to parse the data but the same error is returned.

**Comment by djha983** [comment]
Hi,

I am trying to use csvimport module for populating the data from csv and is not working for me.Here is what i am doing.In view event page,I click on populate from and when new page appears i selected option csvimport.It brought me to csvimport page asking for selecting the file and provide the header information.As my csv file has header info in first row i simply selected the tick box Has_Header and selected import file by browsing it from my local drive.Once i click in import it shows me error message "Something went wrong, look in the server logs for details". When i check /var/log/syslog file for log entry i see below message.

Dec 31 15:46:58 misptip misp-modules[1366]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 189, in run_request
Dec 31 15:46:58 misptip misp-modules[1366]:     response = mhandlers[x['module']].handler(q=jsonpayload)
Dec 31 15:46:58 misptip misp-modules[1366]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/import_mod/csvimport.py", line 222, in handler
Dec 31 15:46:58 misptip misp-modules[1366]:     csv_parser = CsvParser(header, has_header, data)
Dec 31 15:46:58 misptip misp-modules[1366]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/import_mod/csvimport.py", line 49, in __init__
Dec 31 15:46:58 misptip misp-modules[1366]:     self.parse_data(data)
Dec 31 15:46:58 misptip misp-modules[1366]:   File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/modules/import_mod/csvimport.py", line 81, in parse_data
Dec 31 15:46:58 misptip misp-modules[1366]:     line = line.split('#')[0].strip()
Dec 31 15:46:58 misptip misp-modules[1366]: AttributeError: 'list' object has no attribute 'split'

Please let me know what is the issue? Am i doing some mistake in creating csv file? my csv file has below entry.
![image](https://user-images.githubusercontent.com/17782428/71615674-61164080-2bd8-11ea-9fd4-a090dde7a1a2.png)

Please advice if i am doing some mistake in creating csv file and header.

**Comment by chrisr3d** [comment]
Hi @deepak-eventtracker,

I strongly advise you to update your misp modules using the following commands:
```
cd /usr/local/src/misp-modules
sudo rm -fr build/*
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U .
sudo killall -9 misp-modules
```
To be sure you also have the latest dependencies, I would recommend to use `sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U -r REQUIREMENTS` as well

Then you can restart your modules with:
`/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s &`

Tell me if anything goes wrong

**Comment by djha983** [comment]
Hello 

> 
> 
> Hi @deepak-eventtracker,
> 
> I strongly advise you to update your misp modules using the following commands:
> 
> ```
> cd /usr/local/src/misp-modules
> sudo rm -fr build/*
> sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U .
> sudo killall -9 misp-modules
> ```
> 
> To be sure you also have the latest dependencies, I would recommend to use `sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U -r REQUIREMENTS` as well
> 
> Then you can restart your modules with:
> `/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s &`
> 
> Tell me if anything goes wrong

Hello @chrisr3d 

Thank you for the response.I tried the suggestions given by you above.Now i don't see any error while importing it says job is queued.In jobs queue it says it is complete.However i don't see those attributes from csv part of the event.

Please suggest/help.Why i am not seeing whether it is successfully imported? or any logs where i can look for errors?

Thank You.

**Comment by LHQ8884** [comment]
@deepak-eventtracker 

I also don't see any error while importing it says job is queued.In jobs queue it says it is complete. How do you resolved this issue?

**Comment by djha983** [comment]
Hi,

It is because of the encoding format of the file.File from which you are importing shd be strictly saved in utf-8 format.

Regards,
Deepak Jha

Sent from Mobile
________________________________

**Comment by LHQ8884** [comment]
![image](https://user-images.githubusercontent.com/65844505/82755367-92044580-9e05-11ea-9d46-98cfb38cecd2.png)

![image](https://user-images.githubusercontent.com/65844505/82755382-ad6f5080-9e05-11ea-90da-f7ffeb83859c.png)

@deepak-eventtracker
I still can't get even my file is in utf-8 format
