### ISSUE TITLE
avoid MISP error.log when adding existing tag to object

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3245]
when calling PyMISP.tag() and it already exists the client does get an error in the response which can processed accordingly. additionally, the MISP server error.log has an entry as below.

is there a better method to check if a tag first exists before adding (that is not too "expensive) to avoid the error.log entry?

```
Request URL: /tags/attachTagToObject
Stack Trace:
#0 [internal function]: TagsController->attachTagToObject()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2018-05-10 19:30:18 Error: [MethodNotAllowedException] Cannot attach tag, Event already has the tag attached.
```

**Comment by iglocska** [comment]
Hmm an exception is overkill for that indeed.
