### ISSUE TITLE
lower error for tag already existing to debug level?

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3309]
when doing bulk ingestion there are times that a tag already exists. should it's prior existence be tested before adding? if not possible, then should this be an error output to `error.log` (e.g. perhaps better in `debug.log`)?
```
2018-06-04 21:07:25 Error: [MethodNotAllowedException] Could not add the Tag. [name]: A similar name already exists.
Request URL: /tags/add
Stack Trace:
#0 [internal function]: TagsController->add()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by iglocska** [comment]
This is now fixed, it will return a 200 if the tag already exists and return the actual tag so you can reuse the local ID.
