### ISSUE TITLE
remove error.log entries every 3 secs when jobs page open in WebUI

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3339]
2.4.92

Please remove these entries in the `error.log` which are triggered when someone has the jobs page open in the WebUI. I thought it was actually a job continually looping and instead that job is actually dead.
```
2018-06-14 14:21:12 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /jobs/getGenerateCorrelationProgress/12232
Stack Trace:
#0 /var/www/MISP_2.4.92/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#1 /var/www/MISP_2.4.92/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#2 /var/www/MISP_2.4.92/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#3 /var/www/MISP_2.4.92/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#4 /var/www/MISP_2.4.92/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by iglocska** [comment]
Thanks for the heads-up!
