### ISSUE TITLE
Stix import broken for MISP v2.4.92

### ISSUE THREAD

**Issue by HachimanSec** [MISP/MISP#3365]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| MISP version / git hash   | v2.4.92 (6eb4e49f2c62d05e671e3482ac1b21004ce58ee3) 
| Browser                   | Firefox

### Expected behavior
Manually importing stix file (https://www.us-cert.gov/ncas/analysis-reports/AR18-165A)

### Actual behavior
Error message:
` Could not import STIX document: Issues executing the ingestion script or invalid input. Check whether the dependencies for STIX are met via the diagnostic tool.`

### Steps to reproduce the behavior
Actually this is a completely fresh installation according to the install guide https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.debian9.txt

### Logs, screenshots, configuration dump, ...

```
STIX: 1.2.0.6
CyBox: 2.1.0.18.dev0
mixbox: 1.0.3
PyMISP: >2.4.92
Other versions might work but are not tested / recommended.
STIX and Cybox libraries…OK
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
PYMISP library version…OK
```

**Comment by jezkerwin** [comment]
Have a look at https://github.com/MISP/MISP/issues/3353 to see if it addresses your issues.

I had the same problem and executing > pip3 install maec fix my issue.

**Comment by HachimanSec** [comment]
Thank you, I have seen this one as well. 
Executing pip3 install maec didnt help unfortunately

`Successfully installed cybox-2.1.0.17 lxml-4.2.1 maec-4.1.0.13 mixbox-1.0.3 ordered-set-3.0.0 python-dateutil-2.7.3 six-1.11.0
`

**Comment by RichieB2B** [comment]
STIX import uses https://github.com/MISP/misp-modules Are you running the latest version of misp-modules? Detailed errors will be in the stderr of the misp-modules process.

**Comment by iglocska** [comment]
The import shouldn't use misp-modules. It uses a built in script like the STIX export. (Unless I am wrong, which has a 50% chance of happening these days)

**Comment by adulau** [comment]
Could you have a look in <your-misp>/app/tmp/logs/exec-errors.log?

**Comment by RichieB2B** [comment]
@iglocska I did a simple test:

1. Verify _Populate from.. --> Stiximport_ is there
2. kill misp-moduiles
3. Observe _Populate from.. --> Stiximport_ is  no longer there
4. start misp-modules
5.  Observe _Populate from.. --> Stiximport_ is back

Wait... there are now 2 STIX import options: also a new `Import from ...` submenu on the main Event List page. @TomHubGit which one are you using?

**Comment by adulau** [comment]
@RichieB2B Yep, maybe we should kill the old STIX misp-module import to avoid the confusion as there is the default STIX and STIX 2 import.

**Comment by HachimanSec** [comment]
I am using the UI version of the STIX import.

@adulau interestingly it says that maec is missing (just like in the referenced issue)

```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1077, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1071, in main
    stix_parser.load(args, pathname)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 58, in load
    event = STIXPackage.from_xml(filename)
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/core/stix_package.py", line 249, in from_xml
  File "/usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/parser.py", line 183, in parse_xml
    check_root=check_root
  File "/usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/parser.py", line 152, in parse_xml_to_obj
    entity_obj.build(root)
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/stix_core.py", line 171, in build
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/stix_core.py", line 207, in buildChildren
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/stix_core.py", line 646, in build
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/stix_core.py", line 653, in buildChildren
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/ttp.py", line 1425, in build
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/ttp.py", line 1451, in buildChildren
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/ttp.py", line 1062, in build
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/ttp.py", line 1072, in buildChildren
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/ttp.py", line 773, in build
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/ttp.py", line 780, in buildChildren
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/extensions/malware/maec_4_1.py", line 94, in build
  File "/usr/local/lib/python3.5/dist-packages/stix-1.2.0.6-py3.5.egg/stix/bindings/extensions/malware/maec_4_1.py", line 100, in buildChildren
ImportError: No module named 'maec'
```

However I am 100% sure I installed maec via pip yesterday when I came across the other issue. 

When I re-run the installer, it throws an error now:
```
Collecting maec
  Downloading https://files.pythonhosted.org/packages/bb/3d/b9075416ce1dd17ad866253b7c7987e52b78bb8b8c1c6dc23f4b1a94e51f/maec-4.1.0.13.tar.gz (152kB)
    100% |################################| 153kB 2.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p9vem58u/maec/setup.py", line 24, in <module>
        readme = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 141: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-p9vem58u/maec/
root@ecs-6c50:/var/www/MISP/app/tmp/logs# cat /tmp/pip-build-p9vem58u/maec/
cat: /tmp/pip-build-p9vem58u/maec/: No such file or directory
```

This leaves me seriously puzzled...

<img width="758" alt="screen shot 2018-06-22 at 11 51 12" src="https://user-images.githubusercontent.com/20123996/41770482-a20458ac-7612-11e8-8310-5bc66a2acd6d.png">

**Comment by HachimanSec** [comment]
Quick update, pip didnt like that I forgot the sudo in front. 

However I still can't upload STIX files.
```
pip3 install maec
Collecting maec
Collecting mixbox>=0.0.13 (from maec)
  Using cached https://files.pythonhosted.org/packages/0c/1e/32062f67cb0250d86179b9d31acd0a694b313bc282e15131738c4b1f6c28/mixbox-1.0.3-py2.py3-none-any.whl
Collecting lxml>=2.2.3 (from maec)
  Using cached https://files.pythonhosted.org/packages/30/65/6dcc7a1a0ec3bbc10a1316b3610f9997ca132183a5f5345c5b88fc1eaf79/lxml-4.2.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting cybox<2.1.1.0,>=2.1.0.13.dev1 (from maec)
  Using cached https://files.pythonhosted.org/packages/8f/7e/14db0a8ae5f47d9b066a1f3cb0b6830727f68ecaeed10b9d1548903c4836/cybox-2.1.0.17-py2.py3-none-any.whl
Collecting ordered-set (from mixbox>=0.0.13->maec)
Collecting python-dateutil (from mixbox>=0.0.13->maec)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->mixbox>=0.0.13->maec)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: ordered-set, lxml, six, python-dateutil, mixbox, cybox, maec
Successfully installed cybox-2.1.0.17 lxml-4.2.1 maec-4.1.0.13 mixbox-1.0.3 ordered-set-3.0.0 python-dateutil-2.7.3 six-1.11.0
```

**Comment by HachimanSec** [comment]
I rebooted the server and it gives me a permission denied error in: /usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/__init__.py


```
cat exec-errors.log 
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 19, in <module>
    import mixbox.namespaces as mixbox_ns
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 774, in get_code
  File "<frozen importlib._bootstrap_external>", line 826, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/__init__.py'
```


```
ls -lat /usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/__init__.py
-rwxrws--- 1 root staff 138 Jun 21 19:46 /usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/__init__.py
```

Is there any special access permission I missed during the install? I cant find anything in the manual in regards to this

**Comment by adulau** [comment]
@TomHubGit Indeed, the permission is clearly incorrect (not sure how you managed to reach that permission with pip ;-). Your HTTP server won't be able to read the python library file. I was more expecting to see `-rw-r--r--`. If you fix it, it should be fine. Thank you.

**Comment by HachimanSec** [comment]
@adulau glad I achieved something special :D So I did change the permissions to 644.
However I still receive an error, on the UI as well as in the exec-error.log

```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 19, in <module>
    import mixbox.namespaces as mixbox_ns
  File "/usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/__init__.py", line 4, in <module>
    from .version import __version__
ImportError: No module named 'mixbox.version'

```
