### ISSUE TITLE
mispzmq.py throws uncatched exception

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3401]
In mispzmq.py if zmq is already running it "bombs" out.

Implement try/catch
for: zmq.error.ZMQError: Address already in use

==> mispzmq.error.log <==
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 103, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 71, in main
    socket.bind("tcp://*:%s" % settings["port"])
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
tail: mispzmq.error.log: file truncated
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 103, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 71, in main
    socket.bind("tcp://*:%s" % settings["port"])
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
tail: mispzmq.error.log: file truncated
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 103, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 71, in main
    socket.bind("tcp://*:%s" % settings["port"])
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

**Comment by Rafiot** [comment]
This should be fixed in this PR: https://github.com/MISP/MISP/pull/3405
