### ISSUE TITLE
Better error handling in UI when Import services are not reacheable

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3402]
For some reason in my dev environment my misp-modules are "slow" and some time fail to respond.

The UI will simply throw an internal exception, but it could be catched with the below from error.log

UI:
An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

==> error.log <==
2018-06-29 01:23:22 Error: [Exception] Import service not reachable.
Request URL: /events/importModule/ocr/1
Stack Trace:
#0 [internal function]: EventsController->importModule(Array, '1')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by coolacid** [comment]
Search, just hit this issue.

**Comment by coolacid** [comment]
Oh, this is a UI ticket, not the fact that OCR comes back not reachable even though it did finish.
