### ISSUE TITLE
Tornado in misp-modules timing out when submit large PDF

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3403]
When submitting a large-ish file and script execution takes some time.
Tornado times out.

Investigate: how to make tornado wait :)

Todo: Update VM and INSTALL materials to take change into account.

ERROR:tornado.application:Exception in Future <Future at 0x7fb7580d81d0 state=finished raised WandError> after timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 936, in error_callback
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/local/lib/python3.6/dist-packages/misp_modules/modules/import_mod/ocr.py", line 54, in handler
    image = img.composite(pdf.sequence[p], top=pdf.height * p, left=0)
  File "/usr/local/lib/python3.6/dist-packages/wand/image.py", line 543, in wrapped
    result = function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wand/image.py", line 2196, in composite
    self.raise_exception()
  File "/usr/local/lib/python3.6/dist-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.WandError: wand contains no images `MagickWand-28' @ error/magick-image.c/MagickCompositeImageChannel/2043

**Comment by SteveClement** [comment]
Fixed in upcoming misp-modules PR
