### ISSUE TITLE
Internal Server Error using events/index API

### ISSUE THREAD

**Issue by jonbelanger** [MISP/MISP#3444]
max_execution_time (3600)…	OK (recommended: 300)
memory_limit (16384M)…	OK (recommended: 512M)  (this was doubled to attempt to solve)
upload_max_filesize (50M)…	OK (recommended: 50M)
post_max_size (50M)…	OK (recommended: 50M)

my.cnf has:
max_allowed_packet      = 2048M  (this was doubled to attempt to solve)

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 16.04.3 TLS
| PHP version               | 7.0
| MISP version / git hash   | 2.4.87
| Browser                   | curl

### Expected behavior
list of events

### Actual behavior
$ curl --header "Authorization: <api key>" --header "Accept: application/json" --header "Content-Type: application/json"  https://domain.tld/events/index 

{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/index"}

on server side:
```
2018-07-05 15:30:37 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /events/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('SELECT `EventTa...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(671): DboSource->execute('SELECT `EventTa...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1458): DboSource->fetchAll('SELECT `EventTa...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1292): DboSource->_fetchHasMany(Object(Event), 'SELECT `EventTa...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1151): DboSource->queryAssociation(Object(Event), Object(EventTag), 'hasMany', 'EventTag', Array, Array, true, Array, 1, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Event), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#8 /var/www/MISP/app/Controller/EventsController.php(589): Model->find('all', Array)
#9 [internal function]: EventsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-07-05 15:30:37 Warning: Warning (2): Error while sending QUERY packet. PID=15230 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468]
Trace:
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 434
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 671
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1120
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3038
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3010
User::getAuthUserByUuid() - APP/Model/User.php, line 623
AppController::checkAuthUser() - APP/Controller/AppController.php, line 471
AppController::beforeFilter() - APP/Controller/AppController.php, line 177
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??
```

### Steps to reproduce the behavior

same as above

**Comment by jonbelanger** [comment]
I can't help but think this has something to do with numbers of events, but it can't be that high can it?

Events239936 (+293)  Attributes2360316 (+2639)  Attributes / event10 Correlations found50201852 Proposals active0 Users1522 Organisations151 Discussion threads3 (0)  Discussion posts6 (0)

**Comment by iglocska** [comment]
240k events? :O Indeed, that could be the cause that is unusually high. Sounds like you have a lot of tiny events. It is simply much data returned from SQL in one shot and it ends up croaking.

**Comment by iglocska** [comment]
Will look into some refactoring to solve it.

**Comment by jonbelanger** [comment]
ok, thanks.  How long of a turnaround do you think?

**Comment by jonbelanger** [comment]
Also, should I use a pipe instead of the local socket for mysql connection?

**Comment by iglocska** [comment]
Give it a shot now!

**Comment by jonbelanger** [comment]
events/indexes returns now as does /usr/bin/python3.4 misp_searchall.py -s keyword

What kind of scale can we expect wrt number of events.  Millions?  Billions?

Thanks for the quick turnaround.
