### ISSUE TITLE
The request has been blackholed" when publishing to ZeroMQ

### ISSUE THREAD

**Issue by keram79** [MISP/MISP#3454]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 16.04.4 LTS
| OS version (client)       | Win10
| MISP version / git hash   | 2.4.93,    f490e44..0a58848 
| Browser                   | Firefox 61.0.1

### Expected behavior
When pressing "Publish event zo ZMQ", I'd expect no error message, but a site refresh. The event details should be published to the zeroMQ.

### Actual behavior
With the current 2.4.93 release, freshly updated via *git pull* today, we're getting the error **The request has been blackholed** when pressing *Publish to ZeroMQ" in any event. 
```
The request has been black-holed
Error: The requested address '/events/pushEventToZMQ/10319' was not found on this server.
```

```tail -f /var/www/MISP/app/tmp/*.log``` shows:
```
2018-07-09 12:52:30 Error: [BadRequestException] The request has been black-holed
Request URL: /events/pushEventToZMQ/10319
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(EventsController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(EventsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

**Comment by iglocska** [comment]
if you refresh the event view page, do you still get this afterwards?

**Comment by keram79** [comment]
I tried to reload the event page, and still got the "Blackholed" message. Trying again, then it went through.
It appears in almost all requests when multiple "things" are done in a short timeframe, such as "adding a new attribute, then Publish the event" - seems it is a duplicate to issue #3505

**Comment by adulau** [comment]
@keram79 Can we close the issue? Have you tested with a recent version? Thank you very much for your feedback

**Comment by keram79** [comment]
I'm on 2.4.98, git-pull'ed yesterday, and the issue is still there:

```
==> /var/www/MISP/app/tmp/logs/error.log <==
2018-11-29 14:41:00 Error: [BadRequestException] The request has been black-holed
Request URL: /events/pushEventToZMQ/10840
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(EventsController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(EventsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```
