### ISSUE TITLE
mispzmq crashing

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3475]
The ZMQ part of MISP seems broken (tested on 2 separate installs/distro)

To reproduce:

Start mispzmq.py in shell and click on status in MISP diagnostics

> $ sudo -u www-data /var/www/MISP/app/files/scripts/mispzmq/mispzmq.py
> Status command received, responding with latest stats.
> Traceback (most recent call last):
>   File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 126, in <module>
>     mzq.main()
>   File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 98, in main
>     self.handleCommand(command)
>   File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 65, in handleCommand
>     self.r.delete("{self.namespace}:status".format(self.namespace))
> KeyError: 'self'
>

**Comment by SteveClement** [comment]
Problem occurs here, smells like redis issue:

```python
        if command == "status":
            print("Status command received, responding with latest stats.")
            self.r.delete("{self.namespace}:status".format(self.namespace))
            self.r.lpush("{self.namespace}:status".format(self.namespace),
                         json.dumps({"timestamp": time.time(),
                                     "timestampSettings": self.timestampSettings,
                                     "publishCount": self.publishCount}))
```

**Comment by SteveClement** [comment]
redis-cli MONITOR output

1531341833.714960 [1 [::1]:59668] "LPOP" "mispq:command"
1531341833.717024 [1 [::1]:59668] "LPOP" "mispq:data:misp_json"
1531341833.717454 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_event"
1531341833.717764 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_attribute"
1531341833.868057 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_sighting"
1531341833.916900 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_organisation"
1531341833.917333 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_user"
1531341833.917767 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_conversation"
1531341834.013436 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_object"
1531341834.015681 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_object_reference"
1531341834.017604 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_audit"
1531341834.063873 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_tag"
1531341834.166168 [1 [::1]:59668] "LPOP" "mispq:command"
1531341834.166826 [1 [::1]:59668] "LPOP" "mispq:data:misp_json"
1531341834.167438 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_event"
1531341834.168606 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_attribute"
1531341834.170437 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_sighting"
1531341834.265116 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_organisation"
1531341834.267403 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_user"
1531341834.267829 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_conversation"
1531341834.308090 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_object"
1531341834.309784 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_object_reference"
1531341834.310401 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_audit"
1531341834.311357 [1 [::1]:59668] "LPOP" "mispq:data:misp_json_tag"
1531341834.408980 [0 [::1]:59694] "SELECT" "1"
1531341834.410538 [0 [::1]:59696] "SELECT" "1"
1531341834.411059 [1 [::1]:59696] "RPUSH" "mispq:command" "status"
1531341834.413101 [1 [::1]:59668] "LPOP" "mispq:command"
1531341835.411750 [1 [::1]:59696] "LPOP" "mispq:status"

**Comment by SteveClement** [comment]
Now:

```python
Status command received, responding with latest stats.
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 126, in <module>
    mzq.main()
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 98, in main
    self.handleCommand(command)
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 65, in handleCommand
    self.r.delete("{}:status".format(self.namespace))
KeyError: 'self'
```
