### ISSUE TITLE
Reopening and enhancing #3426

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#3540]
Just did a fresh upgrade to 2.4.94 but #3426 is still there.

Furthermore, I can now no longer view the ATT&CK matrix from within an event:

![attck](https://user-images.githubusercontent.com/25325656/43836086-7a72f268-9b14-11e8-9407-0ff0dc933856.png)

Error.log shows in both cases:

```
2018-08-08 12:00:35 Error: Fatal Error (1): Call to undefined function _() in [/services/inst/misp/app/View/Elements/view_mitre_attack_matrix.ctp, line 14]
2018-08-08 12:00:35 Error: [InternalErrorException] Internal Server Error
Request URL: /events/viewMitreAttackMatrix/1/event/1?_=1533729630772
Stack Trace:
#0 /services/inst/misp/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/services/inst/...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/services/inst/...', 14, Array)
#2 /services/inst/misp/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/services/inst/...', 14, Array)
#3 /services/inst/misp/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

```

**Comment by iglocska** [comment]
Just a quick naive fix for the error that you've pasted there, could you give it a shot with the latest commit?

**Comment by StefanKelm** [comment]
Thanks! Will do so tomorow and get back to you.

**Comment by iglocska** [comment]
thanks :)

**Comment by StefanKelm** [comment]
@iglocska the "quick naive fix" you provided solved both problems. :-) Thanks a lot!

**Comment by iglocska** [comment]
Perfect, thanks for testing it! :)
