### ISSUE TITLE
STIX Export fails

### ISSUE THREAD

**Issue by alecisec** [MISP/MISP#3592]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | bug
| OS version (server)       |  ubuntu:16.04
| OS version (client)       | any
| PHP version               |  7.0.30-0ubuntu0.16.04.1 
| MISP version / git hash   | 2.4.94
| Browser                   | na

### Expected behavior

https://<misp URL>/events/stix/download displays export of events in STIX format

### Actual behavior

Page displays:

There was an issue generating the STIX export.
Error: An Internal Error Has Occurred.

Stack Trace
[internal function] → EventsController->stix(string)
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(EventsController, array)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(EventsController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

### Steps to reproduce the behavior

navigate to https://<misp URL>/events/stix/download OR use the 'generate' button in the export screen

### Logs, screenshots, configuration dump, ...

When accessing the URL - (from app/tmp/logs/error.log)

2018-08-28 03:27:04 Error: [Exception] There was an issue generating the STIX export.
Request URL: /events/stix/download
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

or when using the generate button - (from resque-2018-08-28.log)

[2018-08-28 03:28:21] main.INFO: got {"queue":"cache","id":"f4f1338ce9894df5ffa4a42e52328d60","class":"EventShell","args":[["cachestix","1","6079",null,null]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"cache\",\"id\":\"f4f1338ce9894df5ffa4a42e52328d60\",\"class\":\"EventShell\",\"args\":[[\"cachestix\",\"1\",\"6079\",null,null]]})","worker":"9610c0006798:224"} []
[2018-08-28 03:28:21] main.INFO: Processing ID:f4f1338ce9894df5ffa4a42e52328d60 in cache {"type":"process","worker":"9610c0006798:224","job_id":"f4f1338ce9894df5ffa4a42e52328d60"} []
[2018-08-28 03:28:22] main.ERROR: {"queue":"cache","id":"f4f1338ce9894df5ffa4a42e52328d60","class":"EventShell","args":[["cachestix","1","6079",null,null]]} failed: Internal Server Error {"type":"fail","log":"Internal Server Error","job_id":"f4f1338ce9894df5ffa4a42e52328d60","time":260,"worker":"9610c0006798:224"} []

**Comment by chrisr3d** [comment]
Have you checked if the correct python libraries are installed, running the diagnostic tool ? (Administration -> Server Settings & Maintenance -> Diagnostics, then scroll down to "STIX and Cybox libraries")

It should look like this:
![image](https://user-images.githubusercontent.com/16307976/44707719-9622f800-aaa5-11e8-984b-4be162aadafc.png)

If you have anything different please let me know so I can see if the issue is coming from there or somewhere else

**Comment by SteveClement** [comment]
Dear @alecisec if this didn't solve your issue feel free to re-open.
