### ISSUE TITLE
SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine

### ISSUE THREAD

**Issue by scrublullz** [MISP/MISP#3719]
Synopsis: When inserting new events into MISP via PyMISP, some events do not populate with all attributes associated with them. The following error was identified in logs during these times.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug(?) / Support
| OS version (server)       | Ubuntu 16.04.5 Server
| OS version (client)       | Ubuntu 18.04 Desktop
| PHP version               | PHP 7.0.32-0ubuntu0.16.04.1 
| MISP version / git hash   | 2.4.95 / 50a0a6c16db38a30458147efa886403df3cc5cb5
| Browser                   | Chrome 

### Expected behavior
MISP to read the auto_increment value from SQL

### Actual behavior
`SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine`

### Steps to reproduce the behavior
Unknown steps to take to reproduce

### Logs, screenshots, configuration dump, ...

```
2018-09-27 16:30:18 Error: [PDOException] SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine
Request URL: //events/?%2Fevents%2F=
Stack Trace:
#0 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(913): PDOStatement->execute()
#1 /data/misp/www/app/Model/Attribute.php(1887): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /data/misp/www/app/Model/Attribute.php(614): Attribute->__afterSaveCorrelation(Array)
#3 /data/misp/www/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#5 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#6 /data/misp/www/app/Model/Attribute.php(3417): Model->save(Array, Array)
#7 /data/misp/www/app/Model/Event.php(3008): Attribute->captureAttribute(Array, '276516', Array, 0, Object(Log))
#8 /data/misp/www/app/Controller/EventsController.php(1597): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#9 [internal function]: EventsController->add()
#10 /data/misp/www/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /data/misp/www/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-09-27 16:30:19 Error: [PDOException] SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine
Request URL: //events/?%2Fevents%2F=
Stack Trace:
#0 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(913): PDOStatement->execute()
#1 /data/misp/www/app/Model/Attribute.php(1887): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /data/misp/www/app/Model/Attribute.php(614): Attribute->__afterSaveCorrelation(Array)
#3 /data/misp/www/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#5 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#6 /data/misp/www/app/Model/Attribute.php(3417): Model->save(Array, Array)
#7 /data/misp/www/app/Model/Event.php(3008): Attribute->captureAttribute(Array, '276517', Array, 0, Object(Log))
#8 /data/misp/www/app/Controller/EventsController.php(1597): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#9 [internal function]: EventsController->add()
#10 /data/misp/www/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /data/misp/www/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-09-27 16:30:19 Error: [PDOException] SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine
Request URL: //events/?%2Fevents%2F=
Stack Trace:
#0 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(913): PDOStatement->execute()
#1 /data/misp/www/app/Model/Attribute.php(1887): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /data/misp/www/app/Model/Attribute.php(614): Attribute->__afterSaveCorrelation(Array)
#3 /data/misp/www/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#5 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#6 /data/misp/www/app/Model/Attribute.php(3417): Model->save(Array, Array)
#7 /data/misp/www/app/Model/Event.php(3008): Attribute->captureAttribute(Array, '276518', Array, 0, Object(Log))
#8 /data/misp/www/app/Controller/EventsController.php(1597): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#9 [internal function]: EventsController->add()
#10 /data/misp/www/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /data/misp/www/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-09-27 16:30:20 Error: [PDOException] SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine
Request URL: //events/?%2Fevents%2F=
Stack Trace:
#0 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(913): PDOStatement->execute()
#1 /data/misp/www/app/Model/Attribute.php(1887): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /data/misp/www/app/Model/Attribute.php(614): Attribute->__afterSaveCorrelation(Array)
#3 /data/misp/www/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#5 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#6 /data/misp/www/app/Model/Attribute.php(3417): Model->save(Array, Array)
#7 /data/misp/www/app/Model/Event.php(3008): Attribute->captureAttribute(Array, '276519', Array, 0, Object(Log))
#8 /data/misp/www/app/Controller/EventsController.php(1597): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#9 [internal function]: EventsController->add()
#10 /data/misp/www/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /data/misp/www/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-09-27 16:30:21 Error: [PDOException] SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine
Request URL: //events/?%2Fevents%2F=
Stack Trace:
#0 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(913): PDOStatement->execute()
#1 /data/misp/www/app/Model/Attribute.php(1887): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /data/misp/www/app/Model/Attribute.php(614): Attribute->__afterSaveCorrelation(Array)
#3 /data/misp/www/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#5 /data/misp/www/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#6 /data/misp/www/app/Model/Attribute.php(3417): Model->save(Array, Array)
#7 /data/misp/www/app/Model/Event.php(3008): Attribute->captureAttribute(Array, '276520', Array, 0, Object(Log))
#8 /data/misp/www/app/Controller/EventsController.php(1597): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#9 [internal function]: EventsController->add()
#10 /data/misp/www/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /data/misp/www/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /data/misp/www/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2018-09-27 17:00:38 Warning: Invalid argument supplied for foreach() in [/data/misp/www/app/Model/Feed.php, line 1100]
2018-09-27 17:01:21 Warning: Invalid argument supplied for foreach() in [/data/misp/www/app/Model/Feed.php, line 1100]
2018-09-27 17:01:21 Warning: Invalid argument supplied for foreach() in [/data/misp/www/app/Model/Feed.php, line 1100]
2018-09-27 17:01:21 Warning: Invalid argument supplied for foreach() in [/data/misp/www/app/Model/Feed.php, line 1100]
2018-09-27 17:01:21 Warning: Invalid argument supplied for foreach() in [/data/misp/www/app/Model/Feed.php, line 1100]
```

**Comment by scrublullz** [comment]
Here is the table status for Correlations: 
```
+-------------------------------+--------+---------+------------+------------+----------------+--------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-------------------+----------+----------------+---------+
| Name                          | Engine | Version | Row_format | Rows       | Avg_row_length | Data_length  | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time | Collation         | Checksum | Create_options | Comment |
+-------------------------------+--------+---------+------------+------------+----------------+--------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-------------------+----------+----------------+---------+
| correlations                  | InnoDB |      10 | Dynamic    | 2092764167 |            117 | 245743222784 |               0 | 306110742528 |  13631488 |     2147483647 | 2018-04-09 16:58:37 | 2018-09-27 19:00:05 | NULL       | utf8_bin          |     NULL |                |         |
```

**Comment by scrublullz** [comment]
It looks like this may be related to the Correlation table size:
https://github.com/MISP/MISP/issues/3142

**Comment by scrublullz** [comment]
The issue was confirmed to be the Correlations table.  In order to continue adding events, I had to drop and recreate the table.

```
DROP TABLE `correlations`;
CREATE TABLE IF NOT EXISTS `correlations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `value` text COLLATE utf8_bin NOT NULL,
  `1_event_id` int(11) NOT NULL,
  `1_attribute_id` int(11) NOT NULL,
  `event_id` int(11) NOT NULL,
  `attribute_id` int(11) NOT NULL,
  `org_id` int(11) NOT NULL,
  `distribution` tinyint(4) NOT NULL,
  `a_distribution` tinyint(4) NOT NULL,
  `sharing_group_id` int(11) NOT NULL,
  `a_sharing_group_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `info` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `value` (`value`(255)),
  INDEX `event_id` (`event_id`),
  INDEX `1_event_id` (`1_event_id`),
  INDEX `attribute_id` (`attribute_id`),
  INDEX `1_attribute_id` (`1_attribute_id`),
  INDEX `org_id` (`org_id`),
  INDEX `sharing_group_id` (`sharing_group_id`),
  INDEX `a_sharing_group_id` (`a_sharing_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

Events can be recorrelated:

`/pages/display/administration`

and clicking on `Recorrelate` attributes.

**Comment by SteveClement** [comment]
@scrublullz did you figure out what the issue was?

**Comment by scrublullz** [comment]
> @scrublullz did you figure out what the issue was?

Correlations DB grew out of control. I dropped the table and rebuilt it. It exceeded a maximum size.
