### ISSUE TITLE
PyMISP crafted objects with references failed to add via API

### ISSUE THREAD

**Issue by andurin** [MISP/MISP#3834]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.0
| MISP version / git hash   | 2.4.XX, 1bf6e57118528e6de7a602196f1d06abc56b6635
| Browser                   | Firefox

### Expected behavior
Result should be a new created event with File-Objects and references.

### Actual behavior
Event is created but references are missing.

### Steps to reproduce the behavior
Tried to `add_event()` with the following json data.

references were created like this:
```
parent_uuid = 'real_life_uuid'
misp_object.add_reference(parent_uuid, 'extracted-from','')
```

JSON:
```
{
  "Event": {
    "Attribute": [],
    "Object": [
      {
        "Attribute": [
          {
            "category": "Payload delivery",
            "disable_correlation": true,
            "object_relation": "filename",
            "to_ids": false,
            "type": "filename",
            "uuid": "a5aaf110-9dfd-4d05-bcf2-0616beea1210",
            "value": "testfile.txt"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "md5",
            "to_ids": true,
            "type": "md5",
            "uuid": "c2b8136d-ced4-44c1-8181-e65c6db1646c",
            "value": "2205e48de5f93c784733ffcca841d2b5"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha1",
            "to_ids": true,
            "type": "sha1",
            "uuid": "ef12e254-21bc-4794-8147-213abac471ea",
            "value": "1c68ea370b40c06fcaf7f26c8b1dba9d9caf5dea"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha256",
            "to_ids": true,
            "type": "sha256",
            "uuid": "3e80690b-419e-4d52-8a27-971b9635d57c",
            "value": "c9d04c9565fc665c80681fb1d829938026871f66e14f501e08531df66938a789"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha512",
            "to_ids": true,
            "type": "sha512",
            "uuid": "4d538e8e-d9db-4069-9a2d-94f4fd6d584f",
            "value": "ffb360b65e823271ec9dc554a984bcb41793cbb91cba641c52a56b29d1d5dc5f219ad18fe03fd1eb6005da7d88af158369891115f1d6dbcfa0a23b8096b64a47"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "ssdeep",
            "to_ids": true,
            "type": "ssdeep",
            "uuid": "aaee9815-e1f3-45d4-927f-bfd61f4cea14",
            "value": "3:BJn:vn"
          },
          {
            "category": "Other",
            "disable_correlation": true,
            "object_relation": "size-in-bytes",
            "to_ids": false,
            "type": "size-in-bytes",
            "uuid": "13bc6607-b45e-4902-a875-b1601af624d5",
            "value": "5"
          },
          {
            "category": "Artifacts dropped",
            "disable_correlation": true,
            "object_relation": "mimetype",
            "to_ids": false,
            "type": "mime-type",
            "uuid": "679d49ea-2b6d-4993-8907-ef3777612420",
            "value": "text/plain"
          }
        ],
        "ObjectReference": [
          {
            "comment": "",
            "object_uuid": "8ea3f788-13de-4c33-b840-bdd54a1ec708",
            "referenced_uuid": "cb74d31d-34b2-4149-8f3e-7649ba28227e",
            "relationship_type": "extracted-from"
          }
        ],
        "description": "File object describing a file with meta-information",
        "distribution": "5",
        "meta-category": "file",
        "name": "file",
        "sharing_group_id": "0",
        "template_uuid": "688c46fb-5edb-40a3-8273-1af7923e2215",
        "template_version": "15",
        "uuid": "8ea3f788-13de-4c33-b840-bdd54a1ec708"
      },
      {
        "Attribute": [
          {
            "category": "Payload delivery",
            "disable_correlation": true,
            "object_relation": "filename",
            "to_ids": false,
            "type": "filename",
            "uuid": "beb7a357-b654-436a-a9a4-23714a7cbc19",
            "value": "test"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "md5",
            "to_ids": true,
            "type": "md5",
            "uuid": "b013cd59-9406-447e-96c8-05a7b45cd9a9",
            "value": "727ea70fd6114695db8f43de25e44c5c"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha1",
            "to_ids": true,
            "type": "sha1",
            "uuid": "39e1007d-365d-455b-ae54-c7c33a2d10cf",
            "value": "731cc0df493eb33e1b0b3ebd77667453526862ad"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha256",
            "to_ids": true,
            "type": "sha256",
            "uuid": "37c96004-b73c-42a3-988f-de1016604e4e",
            "value": "5be0454265160c949a993adc2621bd2828cc5674d0decb0f9fc3863104f45600"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha512",
            "to_ids": true,
            "type": "sha512",
            "uuid": "4826d9cb-30f8-45aa-9a36-7f78fd5b64cd",
            "value": "c521e8c40f8758b925a6b6a00f5cd7053745154746132bc7ac72847bdcdde7b50024dc981db52d26292d6fcb0bd085ba64d2e77a5381eed4e1266d7e45f95cc1"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "ssdeep",
            "to_ids": true,
            "type": "ssdeep",
            "uuid": "fd6ad03e-6d9d-4a59-b014-8b9267956fb0",
            "value": "3:HxxXKjwbRfETl0H78FluXvKlX5Jll/:HVZEVWX2Hll"
          },
          {
            "category": "Other",
            "disable_correlation": true,
            "object_relation": "size-in-bytes",
            "to_ids": false,
            "type": "size-in-bytes",
            "uuid": "68fb9c3f-915f-4fd0-8d95-0cfc6f1ac10a",
            "value": "10240"
          },
          {
            "category": "Artifacts dropped",
            "disable_correlation": true,
            "object_relation": "mimetype",
            "to_ids": false,
            "type": "mime-type",
            "uuid": "ce2505b2-0ad8-406e-b053-866e81ba8409",
            "value": "application/x-tar"
          }
        ],
        "ObjectReference": [
          {
            "comment": "",
            "object_uuid": "cb74d31d-34b2-4149-8f3e-7649ba28227e",
            "referenced_uuid": "f2cc2169-4d3b-4ed4-b916-8c811473fcef",
            "relationship_type": "extracted-from"
          }
        ],
        "description": "File object describing a file with meta-information",
        "distribution": "5",
        "meta-category": "file",
        "name": "file",
        "sharing_group_id": "0",
        "template_uuid": "688c46fb-5edb-40a3-8273-1af7923e2215",
        "template_version": "15",
        "uuid": "cb74d31d-34b2-4149-8f3e-7649ba28227e"
      },
      {
        "Attribute": [
          {
            "category": "Payload delivery",
            "disable_correlation": true,
            "object_relation": "filename",
            "to_ids": false,
            "type": "filename",
            "uuid": "90a4657a-8d23-406e-bfee-3f6c9ab7298a",
            "value": "test.gz"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "md5",
            "to_ids": true,
            "type": "md5",
            "uuid": "f294517a-948c-46e8-81b9-c36a0e5b75cb",
            "value": "b99bda7dd3a9817fa3244c3498d65ecb"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha1",
            "to_ids": true,
            "type": "sha1",
            "uuid": "0a2d65e2-6529-48d3-984f-effe86cf4b2b",
            "value": "dfdf7eae4e01969dba615ac0f297e88fc6e562f6"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha256",
            "to_ids": true,
            "type": "sha256",
            "uuid": "5dee981d-fa94-4059-9544-b67ce6dd17da",
            "value": "38257ea7d9748f91c44fddb1682aad6c03446e6ded86da247e27421e4fdcda50"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "sha512",
            "to_ids": true,
            "type": "sha512",
            "uuid": "54619329-6113-4be4-8a4a-0ff9d147e786",
            "value": "18f84cd54e7cd2a53f8330bc08105ed03f56b29aba5fb5b062a9a31451f9a7340fb5a776836cbba06a65331a37cde1c5b32b46648c00c77ddb2e96d89411e9de"
          },
          {
            "category": "Payload delivery",
            "disable_correlation": false,
            "object_relation": "ssdeep",
            "to_ids": true,
            "type": "ssdeep",
            "uuid": "dd5e4889-7453-495c-aad9-7cf31deea6e0",
            "value": "3:FtCa8Ut1zgBpBNnBoNsc9IhoZkOShW6dAMeMeXC/v:XCfQzgpNBoL6EkOQpdA9JSX"
          },
          {
            "category": "Other",
            "disable_correlation": true,
            "object_relation": "size-in-bytes",
            "to_ids": false,
            "type": "size-in-bytes",
            "uuid": "21d1567a-f4af-4f61-9c11-88f58ed0bb79",
            "value": "133"
          },
          {
            "category": "Artifacts dropped",
            "disable_correlation": true,
            "object_relation": "mimetype",
            "to_ids": false,
            "type": "mime-type",
            "uuid": "6cec7f75-2477-4fb0-a918-48904603938d",
            "value": "application/gzip"
          }
        ],
        "description": "File object describing a file with meta-information",
        "distribution": "5",
        "meta-category": "file",
        "name": "file",
        "sharing_group_id": "0",
        "template_uuid": "688c46fb-5edb-40a3-8273-1af7923e2215",
        "template_version": "15",
        "uuid": "f2cc2169-4d3b-4ed4-b916-8c811473fcef"
      }
    ],
    "analysis": "0",
    "distribution": "2",
    "info": "MISP-API-Debug",
    "org_id": "2",
    "orgc_id": "2",
    "published": false,
    "threat_level_id": "4"
  }
}
```

### Logs, screenshots, configuration dump, ...

File: error.log
```
2018-11-01 00:48:03 Error: [PDOException] SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Object' for column 'referenced_type' at row 1
Request URL: /events
Stack Trace:
#0 /opt/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /opt/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /opt/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /opt/misp/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(ObjectReference), Array, Array)
#4 /opt/misp/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /opt/misp/app/Model/ObjectReference.php(251): Model->save(Array)
#6 /opt/misp/app/Model/Event.php(3224): ObjectReference->captureReference(Array, '43483', Array, Object(Log))
#7 /opt/misp/app/Controller/EventsController.php(1619): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#8 [internal function]: EventsController->add()
#9 /opt/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /opt/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /opt/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /opt/misp/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}


```

**Comment by ghost** [comment]
Got some time for debugging...

Even with the latest code creating misp events which includes (object-)references via API is broken.

```
{
    "code": 500,
    "name": "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: &#039;Object&#039; for column &#039;referenced_type&#039; at row 1",
    "message": "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: &#039;Object&#039; for column &#039;referenced_type&#039; at row 1",
    "url": "\/events\/",
    "error": {
        "errorInfo": [
            "HY000",
            1366,
            "Incorrect integer value: 'Object' for column 'referenced_type' at row 1"
        ],
        "queryString": "INSERT INTO `misp`.`object_references` (`timestamp`, `referenced_type`, `deleted`, `source_uuid`, `object_id`, `event_id`, `referenced_uuid`, `referenced_id`, `relationship_type`, `uuid`, `comment`) VALUES (1541683369, 'Object', '0', '8ea3f788-13de-4c33-b840-bdd54a1ec708', 3108, 43785, 'cb74d31d-34b2-4149-8f3e-7649ba28227e', 3109, 'related-to', '5be4274c-5a28-4d77-8c01-1b670a201f98', '')"
    }
```

https://github.com/MISP/MISP/blob/671ff699699b7bdc05c1141bab9366e3c0ea8e84/app/Model/ObjectReference.php#L232-L234

I guess it should be "0" for attributes and "1" for Objects?

Unfortunately testing with the integer values I am able to create events, containing all expected objects but without the references.
