### ISSUE TITLE
query builder submit to /rest - should it be /restSearch?

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3998]
with new query builder in 2.4.100... when i try Template: `attributes > restSearch`, why does submit go to `https://localhost/servers/rest` and not `.../restSearch` which then yields
```
The request has been black-holed
Error: The requested address '/servers/rest' was not found on this server.
```

**Comment by github-germ** [comment]
How can we get query builder submissions working on our instance? Thanks!!

**Comment by github-germ** [comment]
Does Query Builder work for anybody?

**Comment by github-germ** [comment]
@mokaddem -- can you help to get this working? Thanks!!

**Comment by iglocska** [comment]
`https://localhost/servers/rest` is correct. You are not querying the API directly, you are querying the REST client which internally queries the API endpoint.

**Comment by github-germ** [comment]
Thanks for the reply!! OK, that helps. However, that `https://localhost/servers/rest` for these settings:

<img width="562" alt="screen shot 2019-01-16 at 10 53 17 am" src="https://user-images.githubusercontent.com/8812009/51260782-05c65080-197d-11e9-8c4e-bdce6b903f6f.png">

yields:
```
The request has been black-holed
Error: The requested address '/servers/rest' was not found on this server.
```

**Comment by iglocska** [comment]
If you're doing some weird Port forwarding on a vm for example, probably better to check "use full path" and correct the relative URL to an absolute URL

**Comment by github-germ** [comment]
@iglocska -- Thx for the great hint -- indeed, we do access the WebUI via an ssh tunnel we setup. So, we are now one step closer, i.e. same query this time with what you suggested as below:

<img width="561" alt="screen shot 2019-01-16 at 3 42 52 pm" src="https://user-images.githubusercontent.com/8812009/51277365-68334700-19a5-11e9-971d-1c63b9d98a33.png">

This generates an error (perhaps still related to our tunnel access method?). Here's the tail from `error.log`:

The css file `chosen-sprite@2x.png` earmarked below is not on our MISP instance. And I don't see it here: https://github.com/MISP/MISP/tree/2.4/app/webroot/css

```
==> error.log <==
2019-01-16 20:40:37 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /css/chosen-sprite@2x.png
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-01-16 20:40:38 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /css/chosen-sprite@2x.png
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-01-16 20:40:59 Error: [SocketException] stream_socket_client(): Peer certificate CN=`135.91.54.39' did not match expected CN=`localhost'
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://localhost:443 (Unknown error)
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(386): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('POST /attribute...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(514): HttpSocket->request(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1716): HttpSocket->post('https://localho...', '{\r\n    "returnF...', Array)
#4 /var/www/MISP/app/Controller/ServersController.php(1635): ServersController->__doRestQuery(Array, 'curl \\\n -d '{"r...', 'misp_url = 'htt...')
#5 [internal function]: ServersController->rest()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2019-01-16 20:40:59 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(2)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(SocketException))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
2019-01-16 20:40:59 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2019-01-16 20:40:59 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by github-germ** [comment]
I downloaded a file of the same name `chosen-sprite@2x.png` and put it in `/var/www/MISP/app/webroot/css` and that error is gone. This is a temporary fix.

  1. Was this file left out of the code base?
  2. How do I get this resolved the correct way?

And, the other issue is indeed related our arrangement using an ssh tunnel to access the server WebUI. Also looks like we have a certificate issue. So, at this point that issue is on us. Thx for your help with that.

**Comment by github-germ** [comment]
the original issue was resolved with the hint to prepend `http://localhost` to the `Relative path to query` textbox.

i will close this issue, and create a new issue for the secondary finding re' the seemingly missing `chosen-sprite@2x.png` file needed for Query Builder.

thanks!!

Query Builder is **AWESOME** !!
