### ISSUE TITLE
Adding org to sharing group via REST API fails

### ISSUE THREAD

**Issue by maynardflies** [MISP/MISP#4040]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04 LTS
| PHP version               | ?
| MISP version / git hash   | 2.4.101 (pulled from default branch)

### Expected behavior
Calling misp /sharingGroups/addOrg with a valid sharing group and org id should add the org to the sharing group.  This does work in misp 2.4.95 build

### Actual behavior

The API returns an "Internal Error" response.  In app/tmp/logs/error.log, the following is recorded

2019-01-23 05:21:21 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null
Request URL: /sharingGroups/addOrg
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(SharingGroupOrg), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/SharingGroupsController.php(425): Model->save(Array)
#6 [internal function]: SharingGroupsController->addOrg()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SharingGroupsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SharingGroupsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
### Steps to reproduce the behavior

add a sharing group, add an org, and use the REST api to add the org to the sharing group.  org id tested with string and int id, uuid, and name

### Logs, screenshots, configuration dump, ...

exception pasted above

**Comment by maynardflies** [comment]
Please note that I reinstalled from the 2.4.95 tag and it worked like it used to, so something seems to have borked between 2.4.95 and 2.4.101

**Comment by adulau** [comment]
@iglocska Does this ring a bell to you?

**Comment by maynardflies** [comment]
Folks, any word on this?  I have tried with the newest versions of both MISP and PyMISP (108 and 106 respectively) and the problem still exists.  We are forced to stay back on .95 right now and we'd like to upgrade  Has anyone looked at this yet?

**Comment by tomking2** [comment]
I've stumbled across the issue here, but not sure as to what _should_ happen in this case.

Taking a look at this:
https://github.com/MISP/MISP/blob/ba6fe46d6ed26bedcc096c9d9bd1df92ccdd5a32/app/Controller/SharingGroupsController.php#L399

This is where the Org is identified and returned as an object. This is expected to have the structure:
```json
{
    "Organisation": {
        "id": "...", ...
    }
}
```

However, the object doesn't have the base 'Organisation' key, instead being directly:

```json
{
    "id": "...", ...
}
```

This then causes problems when adding the sharing group, as the ID is _null_

https://github.com/MISP/MISP/blob/2.4/app/Controller/SharingGroupsController.php#L418-L424

From what I understand, there _should_ be a 'Organisation' key present. @iglocska - Is that right?

If not, it's a quick fix.

**Comment by tomking2** [comment]
Took a further look and placed in a PR for the fix.

If we need to drop the 'Organisation' key, I can alter the fix within the 'addOrg' function instead of re-introducing the key in 'fetchOrg'

**Comment by Rafiot** [comment]
Have you tried to use ` add_org_to_sharing_group`: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L1129

That's the recommended approach for adding an org to a sharing group.

If it doesn't work for you, please let let us know why.

**Comment by maynardflies** [comment]
The add_org_to_sharing_group is the function that internally calls the REST endpoint we’re talking about.  I was trying to boil it down to the actual thing that is failing but for clarity, yes I am trying to call that and that is how I got to this failure in the first place

**Comment by Rafiot** [comment]
So I have a test case (https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L1738) and it works (I checked, the org is properly added in the sharing group).

Can you send me the actual data you're POSTing? You can do that easily by enabling debug in PyMISP.
