### ISSUE TITLE
Errors after restore and move

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#4077]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18
| OS version (client)       | Ubuntu 18
| PHP version               | 7.2
| MISP version / git hash   | 4d684be5eb8477be2b10673f138d6935e0104059 (HEAD -> 2.4, origin/HEAD, origin/2.4)
| Browser                   | If applicable

### Expected behavior
login page

### Actual behavior
Internal error, could not locate the GnuPG public key
![screenshot from 2019-02-02 13-40-12](https://user-images.githubusercontent.com/947191/52169126-aee8a700-26f0-11e9-8b06-d778d62d14c1.png)

### Steps to reproduce the behavior
Go to the page.  I followed [Ubuntu Install](https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.ubuntu1804.md) up to step 6, copied over my apache conf files, then did an misp-restore. I had to manually copy over /var/www/MISP/.gnupg files.  Not sure where to go next..thank you.

### Logs, screenshots, configuration dump, ...
error.log:
~~~
2019-02-02 13:39:58 Error: [MissingTableException] Table logs for model Log was not found in datasource default.
Exception Attributes: array (
  'table' => 'logs',
  'class' => 'Log',
  'ds' => 'default',
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3673): Model->setSource('logs')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(268): Model->schema()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('User', Array)
#6 /var/www/MISP/app/Model/AppModel.php(46): Model->__construct(NULL, NULL, 'default')
#7 [internal function]: AppModel->__construct(Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(741): ClassRegistry::init('User')
#10 /var/www/MISP/app/Controller/AppController.php(123): Controller->loadModel('User')
#11 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}
~~~

debug.log:
~~~
2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 18]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 18
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Elements/global_menu.ctp, line 1]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/global_menu.ctp, line 1
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 45
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Elements/global_menu.ctp, line 10]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/global_menu.ctp, line 10
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 45
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Elements/footer.ctp, line 1]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/footer.ctp, line 1
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 66
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Elements/footer.ctp, line 2]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/footer.ctp, line 2
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 66
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 72]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 72
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: baseurl in [/var/www/MISP/app/View/Layouts/default.ctp, line 99]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 99
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-02 13:39:58 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 108]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 108
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??
~~~

**Comment by DigiAngel** [comment]
So...a few things that didn't get copied over/performed with misp-restore.sh:
~~~
database wasn't imported
gpg.asc 
~~~
after restoring gpg.asc from a backup, importing MYSQL.sql, and importing MISPbackupfile.sql I'm now at a username and password prompt, but current creds to not function.

**Comment by DigiAngel** [comment]
Errors are fixed, so closing this issue.
