### ISSUE TITLE
MySQL host problem with "Initialize user and fetch Auth Key"

### ISSUE THREAD

**Issue by znb** [MISP/MISP#4129]
Running through the install documentation for Ubuntu 18.04 and having issues with the "Initialize user and fetch Auth Key" section. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.1
| MISP version / git hash   | 2.4.XX,
| Browser                   | NA

### Expected behavior

Run

`sudo -H -u www-data -E $CAKE userInit -q`

to get the auth keys.

### Actual behavior

MySQL connection attempts to connect to "localhost" but our database runs on a different host.
Thus the script fails to connect to the database.

### Steps to reproduce the behavior

I need to be able to get the connection made to the host configured in database.php
Or be able to pass the database host as a parameter to the above script

### Logs, screenshots, configuration dump, ...

`
misp@misp:/var/www/MISP/app/Config$ sudo -H -u www-data -E $CAKE userInit -q
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3646): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3673): Model->setSource('logs')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#5 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(268): Model->schema()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('User', Array)
#9 /var/www/MISP/app/Model/AppModel.php(46): Model->__construct(NULL, NULL, 'default')
#10 [internal function]: AppModel->__construct(Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init('User')
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel('User')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(218): Shell->initialize()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#17 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#18 {main}
`

**Comment by znb** [comment]
I must have missed something somewhere during my setup process.

I reran the install script and everything appears to be working.
