### ISSUE TITLE
app/Console/cake Server fetchFeed Undefined variable MispObject.php

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4130]
2.4.102

Enabled `CIRCL OSINT Feed` and cron execution throws the error below on the first execution, no events created. Ran a second time, now events are being created, and then after a few minutes while still ingesting saw the same error below, and then later, finally saw the stack trace below.

1. The error:
```
# /var/www/MISP/app/Console/cake Server fetchFeed 14 1
...

2019-02-08 16:41:57 Notice: Undefined variable: attribute in [/var/www/MISP/app/
Model/MispObject.php, line 590]
...
```

2. The stack trace:
```
Error: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x9B\xA1\xEF\xB8...' for column 'value1' at row 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Attribute), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/Attribute.php(3540): Model->save(Array, Array)
#6 /var/www/MISP/app/Model/MispObject.php(577): Attribute->captureAttribute(Array, '46379', Array, '51876', Object(Log))
#7 /var/www/MISP/app/Model/Event.php(3289): MispObject->captureObject(Array, '46379', Array, Object(Log))
#8 /var/www/MISP/app/Model/Feed.php(784): Event->_add(Array, true, Array)
#9 /var/www/MISP/app/Model/Feed.php(474): Feed->__addEventFromFeed(Object(HttpSocket), Array, '5c500809-453c-4...', Array, Array)
#10 /var/www/MISP/app/Model/Feed.php(868): Feed->downloadFromFeed(Array, Array, Object(HttpSocket), Array, '408089')
#11 /var/www/MISP/app/Console/Command/ServerShell.php(169): Feed->downloadFromFeedInitiator('1', Array, '408089')
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('fetchFeed', Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#15 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#16 {main}
```

**Comment by cvandeplas** [comment]
There seems to be something wrong with your installation. Please ensure you install MISP using the [instructions](https://github.com/MISP/MISP/tree/2.4/INSTALL) .
