### ISSUE TITLE
/feeds/add/ 

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4142]
2.4.102

Why does `/feeds/add` yield `black-holed`?

Thanks...

My test case:
```
curl \
--insecure \
--header 'Authorization: REDACTED' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '
{
    "source_format": "misp",
    "url": "https://thisisjustatest.org",
    "name": "add test feed",
    "input_source": "network",
    "provider": "test"
}' \
--request POST \
https://localhost/feeds/add
{"name":"The request has been black-holed","message":"The request has been black-holed","url":"\/feeds\/add"}
```

Excerpt from `error.log`:
```
2019-02-11 21:08:16 Error: [BadRequestException] The request has been black-holed
Request URL: /feeds/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(FeedsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(FeedsController), 'auth', Object(AuthSecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(FeedsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(FeedsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

**Comment by github-germ** [comment]
Same result when I attempt using `PyMISP.add_feed(...)`

**Comment by iglocska** [comment]
Should be fixed now!

**Comment by github-germ** [comment]
i brought in your change: https://github.com/MISP/MISP/blob/358a8f2eac5a4ea071efec86a113c91eabc9c41c/app/Controller/FeedsController.php

and now...
```
2019-02-11 22:24:54 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
Request URL: /feeds/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Feed), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/FeedsController.php(203): Model->save(Array)
#6 [internal function]: FeedsController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(FeedsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(FeedsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by iglocska** [comment]
Sounds like you didn't fill out the name field.

**Comment by github-germ** [comment]
it does sound like that; however, i did exactly as the curl test case above: 
https://github.com/MISP/MISP/issues/4142#issue-408981006

**Comment by iglocska** [comment]
Can you try the same query via the rest client to eliminate potential curl typos?

**Comment by FloatingGhost** [comment]
Your curl won't validate since the endpoint expects the type to be wrapped in a `Feed` key

i.e
```json
{
  "source_format": "misp",
  "tag_id": "0",
  "name": "my feed",
  "url": "http://example.com"
}
```

will fail whereas
```json
{
  "Feed": {
    "source_format": "misp",
    "tag_id": "0",
    "name": "my feed",
    "url": "http://example.com"
  }
}
```
will succeed 

It's rather inconsistent where type-wrapping is required and where it isn't, but in this case it is

**Comment by github-germ** [comment]
Indeed encapsulating in a `Feed{}` worked with `curl`. Thanks!!

```
curl --insecure --header 'Authorization: REDACTED \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '
{
  "Feed":
  {
    "source_format": "misp",
    "url":           "https://thisisjustatest.org",
    "name":          "add test feed",
    "input_source":  "network",
    "provider":      "test"
  }
}
' --request POST https://localhost/feeds/add
{
    "Feed": {
        "id": "67",
        "name": "add test feed",
        "provider": "test",
        "url": "https:\/\/thisisjustatest.org",
        "rules": null,
        "enabled": false,
        "distribution": "0",
        "sharing_group_id": "0",
        "tag_id": "0",
        "default": false,
        "source_format": "misp",
        "fixed_event": true,
        "delta_merge": false,
        "event_id": "0",
        "publish": false,
        "override_ids": false,
        "settings": "[]",
        "input_source": "network",
        "delete_local_file": false,
        "lookup_visible": false,
        "headers": null,
        "caching_enabled": false
    }
}
```


PyMISP still fails. What do you suggest for that?
```
$ more ./mispAddFeed.py
...
respDict = misp.add_feed(
    source_format = 'misp',
    url           = 'https://thisisjustatest.org',
    name          = 'add test feed',
    input_source  = 'network',
    provider      = 'test')

print(respDict)
```

```
$ python3 ./mispAddFeed.py
CRITICAL [api.py:243 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.102 - Python 3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '147', 'Authorization': 'CtmJMWppkG7l481Lwd1sO48XoO1PhGufhOJntWFW', 'content-type': 'application/json'}
Request body:
{
  "input_source": "network",
  "name": "add test feed",
  "provider": "test",
  "source_format": "misp",
  "url": "https://thisisjustatest.org"
}
Response (if any):
{'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/feeds/add'}
{'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/feeds/add', 'errors': ["500 exception: {'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/feeds/add'}"]}
$ 
```

```
# tail -f error.log
2019-02-12 15:08:18 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
Request URL: /feeds/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Feed), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/FeedsController.php(203): Model->save(Array)
#6 [internal function]: FeedsController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(FeedsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(FeedsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by github-germ** [comment]
> Your curl won't validate since the endpoint expects the type to be wrapped in a `Feed` key

Does this mean that on the `REST client` page (`servers/rest`), that the `feeds > add` template should also wrap the the body in a `Feed` key?
