### ISSUE TITLE
Fresh CentOS 7 install: Navigating through application redirects me to localhost

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#4182]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 7
| OS version (client)       | Ubuntu
| PHP version               | 7.1
| MISP version / git hash   | 2.4.102
| Browser                   | Firefox

### Expected behavior
Navigate through application 

### Actual behavior
Being redirected to https://127.0.0. Example: https://127.0.0.1servers/serverSettings

### Steps to reproduce the behavior
Followed CentOS 7 install guide. Access interface, login with default credentials, visualize main Events page. While trying to access any other menu, it redirects me to localhost.

### Additional info
Already tried.
1) Cake BaseURL
[root@misp logs]#  /var/www/MISP/app/Console/cake Baseurl http://10.64.1.6
PHP Fatal error:  Can't use function return value in write context in /var/www/MISP/app/Model/Server.php on line 1876
Fatal Error Error: Can't use function return value in write context in [/var/www/MISP/app/Model/Server.php, line 1876]

2019-02-14 15:41:35 Error: Can't use function return value in write context in [/var/www/MISP/app/Model/Server.php, line 1876

### Logs, screenshots, configuration dump, ...
/var/www/MISP/app/tmp/logs/error.log

2019-02-14 13:40:59 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2019-02-14 13:44:36 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2019-02-14 13:47:31 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2019-02-14 13:49:16 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2019-02-14 14:06:30 Error: Can't use function return value in write context in [/var/www/MISP/app/Model/Server.php, line 1876]

debug.log

2019-02-14 13:49:16 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Elements/footer.ctp, line 2]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/footer.ctp, line 2
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 66
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-14 13:49:16 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 72]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 72
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-14 13:49:16 Notice: Notice (8): Undefined variable: baseurl in [/var/www/MISP/app/View/Layouts/default.ctp, line 99]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 99
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-14 13:49:16 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 108]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 108
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-02-14 13:52:14 Notice: Notice (8): Undefined index: email in [/var/www/MISP/app/Controller/UsersController.php, line 1259]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
UsersController::__extralog() - APP/Controller/UsersController.php, line 1259
UsersController::change_pw() - APP/Controller/UsersController.php, line 200
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by ghost** [comment]
Looking into other similar issues, it seems to be PHP version used by Cake. But I'm trying to figure out why it's happening with a fresh install.

**Comment by ghost** [comment]
Reviewing all steps and doing some tests I figure it out.
I was pointing baseurl as IP. Example: http://10.1.1.2. Also found some communication issues on my lab.
After all solved, I pointed baseurl as recommended and it's working fine now.

# config.php   : baseurl (example: 'baseurl' => 'http://misp',) - don't use "localhost" it causes issues when browsing externally

Obs: Still don't know the reason why /var/www/MISP/app/Console/cake Baseurl http://misp, didn't worked.
