### ISSUE TITLE
Can't add object to event

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4195]
On MISP 2.4.102 when I try to add an object to an event number 1006, the Add Object menu item gives:
```
2019-02-21 15:56:37 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.ObjectTemplate.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /objectTemplates/objectMetaChoice/1006?_=1550760996299
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('SELECT `ObjectT...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(675): DboSource->execute('SELECT `ObjectT...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1186): DboSource->fetchAll('SELECT `ObjectT...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(ObjectTemplate), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('list', Array)
#6 /var/www/MISP/app/Controller/ObjectTemplatesController.php(22): Model->find('list', Array)
#7 [internal function]: ObjectTemplatesController->objectMetaChoice('1006')
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ObjectTemplatesController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ObjectTemplatesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by RichieB2B** [comment]
The offending MySQL query is:
```
SELECT `ObjectTemplate`.`id`, `ObjectTemplate`.`meta-category` FROM `misp`.`object_templates` AS `ObjectTemplate`   WHERE `ObjectTemplate`.`active` = '1'  GROUP BY `ObjectTemplate`.`meta-category`  ORDER BY `ObjectTemplate`.`meta-category` asc;
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.ObjectTemplate.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by RichieB2B** [comment]
This is duplicate of #1894 and I can confirm that disabling only_full_group_by in MySQL works around this issue. But from @iglocska comment in #1894 I gather that it should not be happening in the first place.

**Comment by iglocska** [comment]
Indeed, should be fixed now, thanks!

**Comment by RichieB2B** [comment]
Oh wow, that's an easy fix. Thanks! Indeed it works now. Can you explain why selecting `meta-category` twice in the fields parameter works around this?

**Comment by iglocska** [comment]
find('list',... actually always fetches value pairs, ID is always silently added as the first value if only one value is requested. By adding it twice we just fetch category,category instead of id,category. full group by requires us to group on every requested field, so not adding ID to the list of grouped keys would fail otherwise.

#FrameworkWoes
