### ISSUE TITLE
fix REST client add feed body

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4400]
2.4.104

Originally discovered in https://github.com/MISP/MISP/issues/4142#issuecomment-462789300

It appears that on the WebUI `servers/rest` the `body` template for `feeds > add` needs to be revised to wrap the existing key:values in a `Feed` key.

**Comment by iglocska** [comment]
Works fine for me without wrapping it.

**Comment by github-germ** [comment]
Does NOT work for me. Here's some details. Let me know where I am missing the point. Thanks...

**Failed Test Case:**
* Submit with this `body`, which is **from the default template for `feed>add`**:
```
  {
    "source_format": "misp",
    "url":           "https://thisisjustatest.org",
    "name":          "add test feed",
    "input_source":  "network",
    "provider":      "test"
  }
```
* Yields this in the WebUI results section:
```
Response

Response code: 500
Request duration: 335.41ms
Headers
  Date: Tue, 02 Apr 2019 16:53:49 GMT
  Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 mod_wsgi/4.6.2 Python/3.6
  X-Powered-By: PHP/7.1.8
  Set-Cookie: CAKEPHP=rahit81j0lsifenccmj1u49hjc; expires=Wed, 03-Apr-2019 16:53:50 GMT; Max-Age=86400; path=/; secure; HttpOnly
  Content-Length: 107
  Connection: close
  Content-Type: application/json; charset=UTF-8
RawJSONHTML
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/feeds\/add"}
```
* and this in `error.log`:
```
2019-04-02 16:46:49 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
Request URL: /feeds/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Feed), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/FeedsController.php(203): Model->save(Array)
#6 [internal function]: FeedsController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(FeedsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(FeedsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Successful Test Case:**
* Submit with this `body`, which is from the default template for `feed>add` and **manually encapsulating in the `"Feed"` key**:
```
{
  "Feed":
  {
    "source_format": "misp",
    "url":           "https://thisisjustatest.org",
    "name":          "add test feed",
    "input_source":  "network",
    "provider":      "test"
  }
}
```

* Yields the newly added feed with HTTP 200 in the WebUI results section.

* and nothing in the `error.log`:

**Comment by bschoenmaeckers** [comment]
I have this issue too. The template is wrong.
