### ISSUE TITLE
attribute not added to event when parallel attributes are sent

### ISSUE THREAD

**Issue by jochman** [MISP/MISP#4402]
When sending multiple attributes (in threads) to misp, it's not adding them all (and returns an error).

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS
| OS version (client)       | Mac, Linux
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.102
| Browser                   | Not relevant

### Expected behavior
add all mentioned attributes to event

### Actual behavior
error is returning from the server

### Steps to reproduce the behavior
you can run the following script:
[PasteBin](https://pastebin.com/BqVqmUwM)

in this case, 27 attributes are in file. only 14-16 attributes are added to MISP in runtime.
![image](https://user-images.githubusercontent.com/11165655/55286324-ded7c200-53a2-11e9-9a48-be850b17dbc2.png)

### Logs, screenshots, configuration dump, ...
https://pastebin.com/eCEubwPN

**Comment by iglocska** [comment]
Could you check the server logs via /var/www/MISP/app/tmp/logs/error.log?

**Comment by jochman** [comment]
[error.log](https://github.com/MISP/MISP/files/3038678/error.log)
here it is

**Comment by iglocska** [comment]
Hmph, seems to be full of authentication failures. Which session handler are you using?

**Comment by ariansvirsky** [comment]
it runs in docker , probably using php session handler

**Comment by iglocska** [comment]
what session handler is PHP using? Could you switch it to redis instead of files?

**Comment by jochman** [comment]
I think that the default (which we are using) is files. I'll check if we can change to Redis on Sunday.
It's clear why on files there's a problem.

**Comment by iglocska** [comment]
Yeah indeed, switching to redis should go a long way. Let us know if it doesn't help!

**Comment by jochman** [comment]
[error (1).log](https://github.com/MISP/MISP/files/3053875/error.1.log)

It didn't work, here's the log. But it did add up to 20-21 attributes instead of 10-14.

**Comment by jochman** [comment]
ping. something new?

**Comment by jochman** [comment]
hey, is something new?

**Comment by adulau** [comment]
Did you update your MISP to the latest version and update your session handler?

**Comment by SteveClement** [comment]
@jochman any update on this?

**Comment by jochman** [comment]
Tried it, still not working.
```
CRITICAL [aping.py:67 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.103 - Python 3.7.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '1012', 'Authorization': 'API_KEY', 'content-type': 'application/json'}
Request body:
{
  "Event": {
    "Attribute": [
      {
        "category": "Network activity",
        "disable_correlation": false,
        "to_ids": true,
        "type": "ip-src",
        "uuid": "bd1344f5-f218-423d-a95a-ceda68fe3d10",
        "value": "x.x.x.x"
      }
    ],
    "Org": {
      "id": "1",
      "name": "ORGNAME",
      "uuid": "5c77af86-8274-4106-862e-0045ac110002"
    },
    "Orgc": {
      "id": "1",
      "name": "ORGNAME",
      "uuid": "5c77af86-8274-4106-862e-0045ac110002"
    },
    "analysis": "0",
    "attribute_count": "0",
    "date": "2019-06-12",
    "disable_correlation": false,
    "distribution": "1",
    "event_creator_email": "admin@admin.test",
    "extends_uuid": "",
    "id": "1186",
    "info": "bug test",
    "locked": false,
    "org_id": "1",
    "orgc_id": "1",
    "proposal_email_lock": false,
    "publish_timestamp": "0",
    "published": false,
    "sharing_group_id": "0",
    "threat_level_id": "4",
    "uuid": "5d0106a1-547c-4556-bebd-2750ac110002"
  }
}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/5d0106a1-547c-4556-bebd-2750ac110002"}
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "misp.py", line 61, in create_att
    misp.update_event(event)
  File "/usr/local/lib/python3.7/site-packages/pymisp/aping.py", line 111, in update_event
    updated_event = super().update_event(event.uuid, event)
  File "/usr/local/lib/python3.7/site-packages/pymisp/api.py", line 407, in update_event
    return self._check_response(response)
  File "/usr/local/lib/python3.7/site-packages/pymisp/aping.py", line 68, in _check_response
    raise MISPServerError('Error code 500:\n{}'.format(response.text))
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/5d0106a1-547c-4556-bebd-2750ac110002"}
```

**Comment by jochman** [comment]
Related to [this](https://github.com/MISP/PyMISP/issues/345) issue.
