### ISSUE TITLE
event_lock.ctp is missing

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4409]
Running 2.4.105 084b79e3992be527f87e308fa50258aed05e7faa the error.log is filled with:

```
2019-04-02 10:52:24 Error: [MissingViewException] View file "Events/ajax/event_lock.ctp" is missing.
Exception Attributes: array (
  'file' => 'Events/ajax/event_lock.ctp',
)
Request URL: /events/checkLocks/14538
Stack Trace:
#0 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Events/ajax/eve...')
#1 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(968): View->render('/Events/ajax/ev...', NULL)
#2 /var/www/html/MISP/app/Controller/EventsController.php(5643): Controller->render('/Events/ajax/ev...')
#3 [internal function]: EventsController->checkLocks('14538')
#4 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#5 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/html/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/html/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

**Comment by SteveClement** [comment]
fixed.
