### ISSUE TITLE
Sorting template elements returns error 400

### ISSUE THREAD

**Issue by iwitz** [MISP/MISP#4417]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RHEL 
| OS version (client)       | 7.6
| PHP version               | 7.2
| MISP version / git hash   | 2.4.105 
| Browser                   | Firefox, Chrome

### Expected behavior
In the view https://misp/templates/view/templateID, it should be possible to order template elements by dragging and dropping them.

### Actual behavior
When sorting a template's elements in the view, the changes are not saved in the model, which means that as soon as the page is reloaded / the template is used the elements order isn't like it should be.

### Steps to reproduce the behavior
* Create a template
* Add elements to it
* Try to sort them

### Logs, screenshots, configuration dump, ...
The AJAX request returns a 400 error regardless of the template that I'm editing or of the number of elements of the template.
I do not believe that the request headers are the issue because I have compared the headers sent when POSTing /templates/saveElementSorting/ and they are basically the same as those sent when POSTing /templates/add (which works).

In app/tmp/logs/error.log : 
```
2019-04-04 07:13:42 Error: [BadRequestException] The request has been black-holed
Request URL: /templates/saveElementSorting/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(TemplatesController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(TemplatesController), 'auth', Object(AuthSecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(TemplatesController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TemplatesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
```

I am using Kerberos authentication, could that be the reason why I'm getting Auth exceptions ?

edit: removed my (wrong) hypothesis about the cause of the bug

**Comment by SteveClement** [comment]
It has nothing to do with you Auth mechanism.

This is a bug.
