### ISSUE TITLE
STIX2 export creates empty file. Invalid value for Malware 'id': not a valid STIX identifier.

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#4482]
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.2.15-0ubuntu0.18.04.2
| MISP version / git hash   | v2.4.105 (a94f1deea61964308c2dbeedc13dd3425b06aa2f)

Expected behavior - Complete export of all events in STIX2 format.
Actual behavior - Empty/no STIX2 file created.
The STIX2 export works successfully if I limit the search to the last 1 day. 

For example, this configuration works from the Rest Client:

{
    "returnFormat": "stix2",
    "last": "1d"
} 

This export does not work:

{
    "returnFormat": "stix2"
} 

I can export all events in XML, STIX1, and JSON format using either the Rest Client or from the command line but the STIX2 export creates no file from the Rest Client or an empty file using the curl command. There are about 100 events with 16,000 attributes in MISP at this time.

The exec-errors.log reports:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/stix2/base.py", line 90, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/usr/local/lib/python3.6/dist-packages/stix2/properties.py", line 217, in clean
    raise ValueError(ERROR_INVALID_ID)
ValueError: not a valid STIX identifier, must match <object-type>--<UUIDv4>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1264, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1261, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if                                     self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if                                     self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 171, in handler
    self.parse_galaxy(galaxy, self.report_id)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 354, in parse_galaxy
    to_call(galaxy)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 488, in add_malware
    malware = Malware(**malware_args)
  File "/usr/local/lib/python3.6/dist-packages/stix2/core.py", line 27, in __init__
    super(STIXDomainObject, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stix2/base.py", line 162, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stix2/base.py", line 94, in _check_property
    raise InvalidValueError(self.__class__, prop_name, reason=str(exc))
stix2.exceptions.InvalidValueError: Invalid value for Malware 'id': not a valid STIX identifier, must match <o                                    bject-type>--<UUIDv4>

![image](https://user-images.githubusercontent.com/8250365/56222039-ee0c7000-6030-11e9-8c1f-7c14b122056d.png)

**Comment by chrisr3d** [comment]
Do you have by any chance a sample of data failing for you at this point ? 
I tried to reproduce your issue without success

**Comment by timhux123** [comment]
Thanks for reaching out.
I'm closing this one for now. I've moved in a different direction to only exporting stix2 for the last 1 day using this rest search:

{
"returnFormat": "stix2",
"last": "1d"
}
