### ISSUE TITLE
ZMQ wont start due to port being used

### ISSUE THREAD

**Issue by dharshanduck** [MISP/MISP#4497]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | ![image](https://user-images.githubusercontent.com/9196526/56297758-87d43a00-6163-11e9-899f-1b8cd51263d0.png)
| Browser                   | Chrome

### Expected behavior
For ZeroMQ script to start

### Actual behavior
ZeroMQ fails to start

### Steps to reproduce the behavior
Environment was running normally, system reboot took place, ZeroMQ failed to run after restart

### Logs, screenshots, configuration dump, ...
Server status
![image](https://files.gitter.im/MISP/Support/EFSB/image.png)
 Ran 
`/var/www/MISP/venv/bin/python/var/www/MISP/app/files/scripts/mispzmq/mispzmqtest.py`
As suggested by @SteveClement 
![image](https://files.gitter.im/MISP/Support/V25d/image.png)
pyzmq already installed
![image](https://files.gitter.im/MISP/Support/IwAH/image.png)
Setting of Misp.python_bin
`/var/www/MISP/app/Console/cake Admin getSetting MISP.python_bin`
```
Welcome to CakePHP v2.10.16 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
{
    "level": 1,
    "description": "It is highly recommended to install all the python dependencies in a virtualenv. The recommended location is: \/var\/www\/MISP\/venv",
    "value": "\/var\/www\/MISP\/venv\/bin\/python",
    "errorMessage": "",
    "null": false,
    "test": "testForBinExec",
    "beforeHook": "beforeHookBinExec",
    "type": "string",
    "tab": "MISP",
    "setting": "MISP.python_bin"
}
```

**Comment by dharshanduck** [comment]
I have found the issue to this problem. It could be helpful to others who might experience this if using [dynatrace monitoring](https://www.dynatrace.com/) software.

Additionally, I overlooked the /var/www/MISP/app/tmp/logs/mispzmq.error.log which has error;
```
 Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 126, in <module>
    mzq.main()
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 92, in main
    socket.bind("tcp://*:{}".format(self.settings["port"]))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
```

The dynatrace agent uses port range 50000-50100 which is why the above error is received, your options can be either change the ports for dynatrace agent, or mispzmq.

A little tip to find out what process is using which port run `sudo netstat -a -lp`

Changing mispzmq ports:
head to `/var/www/MISP/app/files/scripts/mispzmq/settings.json` change the port `{"port":{other port of choice}}` and try to run the script again, be sure to update the zmq port number within the plugin settings page.

As for my case, I will be changing the dynatrace agent ports.

Result
![image](https://user-images.githubusercontent.com/9196526/56338506-e12c7f80-61dc-11e9-8a3e-b04d479658ad.png)
