### ISSUE TITLE
Installer errors (viper)

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#4504]
pyMISP tests fail
```
No module named 'keys'
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8e4018ac8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/www/MISP/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8e4018ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 101, in __init__
    response = self.get_recommended_api_version()
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 1414, in get_recommended_api_version
    response = self._prepare_request('GET', url)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 187, in _prepare_request
    return s.send(prepped, **settings)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8e4018ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 50, in setUpClass
    cls.admin_misp_connector = ExpandedPyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 115, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://localhost:8443). Please make sure the API key and the URL are correct (http/https is required): HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8e4018ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))

----------------------------------------------------------------------
Ran 0 tests in 0.016s

FAILED (errors=1)
#################################################################################################  (96%)
```

**Comment by Rafiot** [comment]
`pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://localhost:8443).` <= shouldn't it be `8080`? And/Or verifycert should be False? Can you point me to the place int he install script that happen?

**Comment by SteveClement** [comment]
Yeah, didn't spot it.

Basically my logic was:

If on a VM BaseURL is https://localhost:8443 because of port forwarding.
This is obviously wrong...

So I guess I just forward that port on OS level if on a VM.

**Comment by SteveClement** [comment]
This https://github.com/MISP/MISP/pull/4511 should fix it.
