### ISSUE TITLE
Server/rest returns an exception

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#4506]
Using /server/rest returns an exception

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win 10
| PHP version               | 7.2.15-0ubuntu0.18.04.2
| MISP version / git hash   | 2.4.103 (e6e927b0da34753a4c139b8e96f806e896ee1562)
| Browser                   | n.a.

### Expected behavior

A single JSON result

### Actual behavior

An exception

### Steps to reproduce the behavior

1. Go to /server/rest
2. Select POST
3. Query: /events/restSearch
4. Type: `{ "returnFormat": json, "page": 1, "limit": 1 }`
9. Hit 'Run query'

### Logs, screenshots, configuration dump, ...

Error on the server:

```
2019-04-18 09:16:47 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by rommelfs** [comment]
Check 4. `{ "returnFormat": json, "page": 1, "limit": 1 }`.

returnFormat expects a string like "json".

**Comment by ancailliau** [comment]
It is just a silly mistake in the reporting. I confirm the issue on my instance, with the quotes. 

Please reopen, it is NOT fixed (nor it is malformed input)

**Comment by iglocska** [comment]
I cannot reproduce this. Could you update to the latest version?

**Comment by ancailliau** [comment]
I updated to the last version. Bug is still present. It looks like the rest client on my instance is not working. I always get an error, but the returned exception is not very helpful in identifying the cause.

**Comment by iglocska** [comment]
That is weird. Is it on a VM with a forwarded port by any chance?

**Comment by ancailliau** [comment]
MISP is in a VM indeed, but the hypervisor is not NAT'ing to forward to a specific port on the VM.

**Comment by iglocska** [comment]
Generally what can go wrong: Your MISP cannot connect to itself via the baseurl.

First of all: Could you switch to using the full path instead of relative paths? There's a checkbox under the URL field. Please prepend the url with the baseurl that you use (so instead of /events/restSearch use http://myvm/events/restSearch). Does it work that way?

**Comment by rommelfs** [comment]
Can you try with the following checkbox enabled: 'Use full path - disclose my apikey' in the REST client interface?

**Comment by ancailliau** [comment]
I was able to find the time to dive a little bit more in the issue. Here is the error from the logs.

```
Error: [SocketException] php_network_getaddresses: getaddrinfo failed: Name or service not known
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(386): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('POST /attribute...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1681): HttpSocket->post('https://misp.si...', '{"returnFormat"...', Array)
#4 /var/www/MISP/app/Controller/ServersController.php(1581): ServersController->__doRestQuery(Array, 'curl \\\n -d '{"r...', 'misp_url = 'htt...')
#5 [internal function]: ServersController->rest()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}

[CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(0)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(SocketException))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]

Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]

Error: [InternalErrorException] Internal Server Error
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

And with the box checked, 
```
Error: [SocketException] Connection refused
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(386): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('POST /attribute...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1681): HttpSocket->post('/attributes/res...', '{"returnFormat"...', Array)
#4 /var/www/MISP/app/Controller/ServersController.php(1581): ServersController->__doRestQuery(Array, 'curl \\\n -d '{"r...', 'misp_url = '/at...')
#5 [internal function]: ServersController->rest()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}

Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(111)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(SocketException))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]

Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]

Error: [InternalErrorException] Internal Server Error
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```
