### ISSUE TITLE
Revise object bug

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4563]
~~~~
2019-05-02 13:28:17 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'value' in 'where clause'
Request URL: /objects/revise_object/add/14670/217
Stack Trace:
#0 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Attribu...', false)
#4 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Attribute), Array)
#5 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#6 /var/www/MISP-priv/app/Controller/ObjectsController.php(109): Model->find('all', Array)
#7 [internal function]: ObjectsController->revise_object('add', '14670', '217')
#8 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ObjectsController), Array)
#9 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ObjectsController), Object(CakeRequest))
#11 /var/www/MISP-priv/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}


~~~~

**Comment by adulau** [comment]
Fixed in 9b1b5a689650b9a00683ae7ba744c724eedbe6a2
