### ISSUE TITLE
MISP no longer working after upgrade to 2.4.106 - Error: [PDOException] SQLSTATE[HY000]: General error: 1366 Incorrect integer value

### ISSUE THREAD

**Issue by keram79** [MISP/MISP#4574]
After upgrading to the current release, MISP no longer works. Might also be related to an upgrade to ubuntu 18.0.4, can't say due to multiple people administering the MISP box :/

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 18.04
| OS version (client)       | Win10
| PHP version               | 7.2.17
| MISP version / git hash   | 2.4.106
| Browser                   | FF 66.0.4

### Expected behavior
MISP showing login page

### Actual behavior
MISP website is displaying header and footer, and in between

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

### Logs, screenshots, configuration dump, ...

Stack trace:
```
root@misp:/var/www/MISP# su - www-data -s /bin/bash -c '/var/www/MISP/app/Console/cake Admin updateDatabase'

Welcome to CakePHP v2.10.16 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Executing all updates to bring the database up to date with the current version.
Executing 29..................Error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'org_id' at row 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Job), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/AppModel.php(248): Model->save(Array)
#6 /var/www/MISP/app/Model/AppModel.php(193): AppModel->updateDatabase(29)
#7 /var/www/MISP/app/Model/AppModel.php(1501): AppModel->updateMISP(29)
#8 /var/www/MISP/app/Console/Command/AdminShell.php(314): AppModel->runUpdates(true)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateDatabase()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateDatabase', Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#12 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#13 {main}
```

**Comment by SteveClement** [comment]
Thanks, will look at it straight away.

**Comment by rommelfs** [comment]
From which version did you upgrade?

**Comment by keram79** [comment]
2.4.102, if I‘m not mistaken.

**Comment by SteveClement** [comment]
@keram79 can you check if the date and time of your server is correct and synced?

**Comment by keram79** [comment]
I can confirm it is correct (UTC), NTP is configured.
We're running all components on a single box, thus different systems with different time settings should not be an issue.

**Comment by keram79** [comment]
Hmmm..... isn't this supposed to work?
```
root@misp:~# su - www-data -s /bin/bash -c '/var/www/MISP/app/Console/cake admin'
Notice Error: Undefined index: SERVER_PORT in [/var/www/MISP/app/Config/bootstrap.php, line 89]

Notice Error: Undefined index: SERVER_ADDR in [/var/www/MISP/app/Config/bootstrap.php, line 92]

Notice Error: Undefined index: SERVER_PORT in [/var/www/MISP/app/Config/bootstrap.php, line 92]

Usage:
cake admin [subcommand] [-h] [-v] [-q]
[...]
```

**Comment by keram79** [comment]
Ah, the "baseurl" was missing from config.php for whatever reason, after adding it back in the ```cake admin``` doesn't throw any error any more. The above stacktrace still occurs when trying to access MISP, however.

**Comment by keram79** [comment]
Not sure if relevant:
```
root@misp:/var/www/MISP# git status
On branch 2.4
Your branch is up to date with 'origin/2.4'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/composer.json
        modified:   app/composer.phar
        deleted:    app/tmp/cache/feeds/empty
        deleted:    app/tmp/cache/ingest/empty
        deleted:    app/tmp/cache/models/empty
        deleted:    app/tmp/cache/persistent/empty
        deleted:    app/tmp/cache/views/empty
        deleted:    app/tmp/cached_exports/rpz/empty
```

**Comment by iglocska** [comment]
Hmph. That is weird as hell. Could you try the following?

```
rm -f /var/www/MISP/app/tmp/cache/models/myapp*
rm -f /var/www/MISP/app/tmp/cache/persistent/myapp*
```

**Comment by iglocska** [comment]
Could you git pull and try again? Think I found it but it was a bit of a blind fix as I couldn't reproduce it ;)

**Comment by keram79** [comment]
Pray to the god of cakephp!  
Whatever you did, it fixed our issue. Git pull, and nothing else required.

**Comment by iglocska** [comment]
Awesome, cheers for the feedback B-)

**Comment by SteveClement** [comment]
Fixed it for me too, thanks.
