### ISSUE TITLE
Internal Error fetching events with large amount of attributes

### ISSUE THREAD

**Issue by stricaud** [MISP/MISP#4640]
I have an event, with ID 1697 which contains 314852 attributes, when I get this event, it returns an internal error.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04.6 LTS
| OS version (client)       | Debian buster/sid
| PHP version               | 7.0+49
| MISP version / git hash   |  v2.4.103 (aa2218846cab471cf5a0ae22afd79e231a74f3ca) 
| Browser                   | not applicable, it fails on both Firefox to view the event and curl REST API call

### Expected behavior
Getting my events.

### Actual behavior
The client returns an internal error, and the logs server side show a lack of allowed memory. I increase the value in php.ini, but I have to increase it everytime I am getting more attributes.
```
May 15 22:09:24 e362c7e5625a misp.error 2019-05-15 22:09:24 Error: Fatal Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 284]
May 15 22:09:24 e362c7e5625a misp.error 2019-05-15 22:09:24 Error: [InternalErrorException] Internal Server Error
May 15 22:09:24 e362c7e5625a misp.error Request URL: /events/1697
May 15 22:09:24 e362c7e5625a misp.error Stack Trace:
May 15 22:09:24 e362c7e5625a misp.error #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 284)
May 15 22:09:24 e362c7e5625a misp.error #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 284, Array)
May 15 22:09:24 e362c7e5625a misp.error #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
May 15 22:09:24 e362c7e5625a misp.error #3 [internal function]: App::shutdown()
May 15 22:09:24 e362c7e5625a misp.error #4 {main}
```

### Steps to reproduce the behavior
```
$ curl -k --header "Authorization: s3cr3t " --header "Accept: application/json" --header "Content-Type: application/json" https://misp-instance/events/1697
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/1697"}
```

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/956069/57812736-cb9a6f00-7722-11e9-966c-af4d0a239d10.png)

**Comment by iglocska** [comment]
That is indeed massive. I'll keep this in mind, we need to refactor a few things to avoid having stupidly high memory requirements for massive events.

**Comment by iglocska** [comment]
As a temporary fix, raise your memory limit in php.ini from 512MB to something higher (we use 1536 IIRC internally)

**Comment by stricaud** [comment]
thanks, I did this to 2048MB, but for some large events it still brings the issue.

**Comment by github-germ** [comment]
We also experience this error with events with large attribute counts. Will include `error.log` excerpt below. In our case we have `memory_limit=24G` in `php.ini`, and the user role is also set to `24G`. however, the error seems to indicate that the request exceeded `10G`.

1. Why would the error show `10G` as the limit, when we set it to `24G`?
   `Allowed memory size of 10737418240 bytes exhausted...`
1. Are we missing configuring the limit somewhere else?

Thanks!!

```
2019-06-18 09:40:14 Error: Fatal Error (1): Allowed memory size of 10737418240 bytes exhausted (tried to allocate 803213312 bytes) in [/var/www/MISP/app/Lib/Tools/JSONConverterTool.php, line 92]
2019-06-18 09:40:14 Error: [InternalErrorException] Internal Server Error
Request URL: /events/41121
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 92)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 92, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-06-18 09:50:02 Warning: array_merge(): Argument #2 is not an array in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 457]
2019-06-18 10:00:01 Warning: array_merge(): Argument #2 is not an array in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 457]
2019-06-18 11:36:48 Error: Fatal Error (1): Allowed memory size of 10737418240 bytes exhausted (tried to allocate 803213312 bytes) in [/var/www/MISP/app/Lib/Tools/JSONConverterTool.php, line 92]
2019-06-18 11:36:48 Error: [InternalErrorException] Internal Server Error
Request URL: /events/41121
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 92)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 92, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-06-18 11:37:53 Error: Fatal Error (1): Allowed memory size of 10737418240 bytes exhausted (tried to allocate 803213312 bytes) in [/var/www/MISP/app/Lib/Tools/JSONConverterTool.php, line 92]
2019-06-18 11:37:53 Error: [InternalErrorException] Internal Server Error
Request URL: /events/41121
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 92)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 92, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```
