### ISSUE TITLE
Problem synching MISP and TheHive

### ISSUE THREAD

**Issue by masoudqashqai** [MISP/MISP#4651]
when i'm trying to sync misp with TheHive i get GENERAL SSLENGINE PROBLEM, i followed @To-om comment on issue #544 and relized my server does not have a domain or Common name and im getting below error

```
Caused by: java.security.cert.CertificateException: No subject alternative names present
        at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:145)
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
```

My Question is Do i need a domain name for my server to get rid of this problem ?

**Comment by SteveClement** [comment]
If it expects a SAN then you need to issue your certificate with the same SAN name as the CN.

Perhaps this helps:

https://medium.com/@sajithekanayaka/solved-java-security-cert-certificateexception-no-subject-alternative-names-present-eec1669faf0d

But this looks more like a Hive support ticket then MISP.

We do not use Java.
