### ISSUE TITLE
Caching feeds- redis not reachable error

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4759]
Questions | Answers
-- | --
Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()
Browser

I am getting the error 'Redis not reachable' when I am trying to cache feeds?

Can anyone explain what caching feeds does?

![image](https://user-images.githubusercontent.com/42444130/59604689-7c08e380-90d2-11e9-8dbe-8ac333bf3e55.png)

**Comment by SteveClement** [comment]
Caching feeds puts the entire feed into redis to make fast lookups, for the matrix or correlations for example.

It seems your redis server is down.

**Comment by dmolina213** [comment]
Redis is running
systemctl status rh-redis32-redis
ΓùÅ rh-redis32-redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/rh-redis32-redis.service; enabled; ve
ndor preset: disabled)
  Drop-In: /etc/systemd/system/rh-redis32-redis.service.d
           ΓööΓöÇlimit.conf
   Active: active (running) since Mon 2019-06-17 13:23:04 UTC; 46min ago
  Process: 19640 ExecStop=/opt/rh/rh-redis32/root/usr/libexec/redis-shutdown (co
de=exited, status=0/SUCCESS)
 Main PID: 19652 (redis-server)
   CGroup: /system.slice/rh-redis32-redis.service
           ΓööΓöÇ19652 /opt/rh/rh-redis32/root/usr/bin/redis-server 127.0.0.1:63
7...

ps -aux | grep redis
redis    19652  0.0  0.0 143140 14092 ?        Ssl  13:23   0:02 /opt/rh/rh-redi
s32/root/usr/bin/redis-server 127.0.0.1:6379
root     25527  0.0  0.0 112712   976 pts/5    S+   14:10   0:00 grep --color=au
to redis

**Comment by dmolina213** [comment]
looks like the same issue but for RHEL7  https://github.com/MISP/MISP/issues/2652

**Comment by adastra22** [comment]
I'm having the same issue right now on CentOS 7. 

[root@server~]# systemctl status redis
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: active (running) since Mon 2019-06-24 11:31:10 EDT; 25min ago
  Process: 129825 ExecStop=/usr/libexec/redis-shutdown (code=exited, status=0/SUCCESS)
 Main PID: 129840 (redis-server)
   CGroup: /system.slice/redis.service
           └─129840 /usr/bin/redis-server 127.0.0.1:6379

Jun 24 11:31:10 dtlcp001sec015 systemd[1]: Starting Redis persistent key-value database...
Jun 24 11:31:10 dtlcp001sec015 systemd[1]: Started Redis persistent key-value database.

![image](https://user-images.githubusercontent.com/16085663/60033800-425a4e80-9677-11e9-9dd0-84f36513c624.png)

![image](https://user-images.githubusercontent.com/16085663/60033906-7a619180-9677-11e9-8dd6-7203eb9e251f.png)

![image](https://user-images.githubusercontent.com/16085663/60033931-88afad80-9677-11e9-97c5-4156c6722265.png)

**Comment by holidayz1** [comment]
Runnung into the same  error

2019-09-10 10:33:24 Warning: Warning (2): Redis::connect(): connect() failed: Connection refused in [/var/www/MISP/app/Model/AppModel.php, line 1793]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Redis::connect() - [internal], line ??
AppModel::setupRedis() - APP/Model/AppModel.php, line 1793
Feed::attachFeedCacheTimestamps() - APP/Model/Feed.php, line 1015
FeedsController::index() - APP/Controller/FeedsController.php, line 76
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-09-10 10:33:27 Warning: Redis::connect(): connect() failed: Connection refused in [/var/www/MISP/app/Model/AppModel.php, line 1793]
2019-09-10 10:33:27 Error: Could not get freetext feed 5
[Exception] Could not reach Redis.
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(801): Feed->getFreetextFeed(Array, Object(HttpSocket), 'csv', 'all')
#1 /var/www/MISP/app/Console/Command/ServerShell.php(170): Feed->downloadFromFeedInitiator('5', Array, '130')
#2 /var/www/MISP/app/Console/Command/AppShell.php(32): ServerShell->fetchFeed()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#8 {main}

**Comment by dpatanker** [comment]
Hi Team,

recently started having this issue as well.
checked redis server setting and zenmq.redis and nothing was changed.
All was working fine till updated from v2.4.115 to v 2.4.117
running it on redhat 7 and can not see where else to look


2019-10-24 13:30:02 Error: Could not get freetext feed 9
[Exception] Could not reach Redis.
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(799): Feed->getFreetextFeed(Array, Object(HttpSocket), 'freetext', 'all')
#1 /var/www/MISP/app/Console/Command/ServerShell.php(170): Feed->downloadFromFeedInitiator('9', Array, '2957')
#2 /var/www/MISP/app/Console/Command/AppShell.php(32): ServerShell->fetchFeed()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
