### ISSUE TITLE
Creating new user and having a defunct mail system crashes ungracefully

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#4760]
When your MISP instance has not properly configured the mail system the following happens and a generic exception is thrown, which will confuse the user.

```
2019-06-17 13:41:35 Error: [SocketException] Could not send email: unknown
Request URL: /admin/users/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/MailTransport.php(52): MailTransport->_mail('steve@localhost...', '[MyORGA MISP] N...', 'Dear MISP user,...', 'From: notify@ad...', NULL)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/CakeEmail.php(1183): MailTransport->send(Object(CakeEmail))
#2 /var/www/MISP/app/Model/User.php(854): CakeEmail->send('Dear MISP user,...')
#3 /var/www/MISP/app/Model/User.php(804): User->__finaliseAndSendEmail(false, Object(CakeEmail), '', Array, '[MyORGA MISP] N...', 'Dear MISP user,...')
#4 /var/www/MISP/app/Model/User.php(1135): User->sendEmail(Array, 'Dear MISP user,...', false, '[MyORGA MISP] N...')
#5 /var/www/MISP/app/Controller/UsersController.php(633): User->initiatePasswordReset(Array, true, true, '')
#6 [internal function]: UsersController->admin_add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by Nelsonwgc** [comment]
Were you able to solve this?
