### ISSUE TITLE
API Requests Internal Server Error

### ISSUE THREAD

**Issue by b00lpy** [MISP/MISP#4930]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Support
| OS version (server)       | Ubuntu
| OS version (client)       | 10, Ubuntu, ...
| PHP version               |7.2
| MISP version / git hash   | latest
| Browser                   | chrome/firefox

### Expected behavior
When i perform any kind of API call I always get an Internal Server Error. Tested with:
1. ManualREST call  
2. REST Client MISP feature  
3. PyMISP module   
4. TheHive connector

### Actual behavior
Nothing work, always a 501 HTTP Error followed by a weird 200 OK which sends me ALL misp events.

### Steps to reproduce the behavior
Hard to explain...
1. Install MISP with default script adding all modules
2. Basic server configuration 
3. Try to perform a MISP api call

I don't have inserted a certificate yet, is this the cause?

### Logs, screenshots, configuration dump, ...
```

2019-07-23 13:30:08 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(ServersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(ServersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(ServersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2019-07-23 13:30:45 Error: [SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://localhost:443 (Unknown error)
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(386): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('POST /events/ad...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1772): HttpSocket->post('https://localho...', '{\r\n    "info": ...', Array)
#4 /var/www/MISP/app/Controller/ServersController.php(1672): ServersController->__doRestQuery(Array, 'curl \\\n -d '{"i...', 'misp_url = 'htt...')
#5 [internal function]: ServersController->rest()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2019-07-23 13:30:45 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(2)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(SocketException))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
2019-07-23 13:30:45 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2019-07-23 13:30:45 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

```
____
###  With this request

![immagine](https://user-images.githubusercontent.com/50588190/61716819-35a54500-ad60-11e9-94c4-cb11b1094ef8.png)

### I got this

![immagine](https://user-images.githubusercontent.com/50588190/61716763-18707680-ad60-11e9-8291-7b1d061d9513.png)

**Comment by b00lpy** [comment]
## UPDATE

With the REST client  if I skip the SSL validation i have another error: 
```
The request has been black-holed

Error: The requested address '/servers/rest' was not found on this server.
```

**Comment by b00lpy** [comment]
### Update part 2

Fresh install done today (2.4.111) , no errors in installation.
MISP is running on a remote server.
When i try this:
![image](https://user-images.githubusercontent.com/50588190/62205234-4ae92780-b38f-11e9-8331-785dc7890993.png)

I got this:
![image](https://user-images.githubusercontent.com/50588190/62205261-5f2d2480-b38f-11e9-8532-942831f1cca9.png)

Editing relative path to full:
![image](https://user-images.githubusercontent.com/50588190/62205314-79ff9900-b38f-11e9-8a80-c0e4a5f986e6.png)

Another error again:
![image](https://user-images.githubusercontent.com/50588190/62205394-a1566600-b38f-11e9-8139-1936ca70ce2d.png)

What am i missing guys?

**Comment by b00lpy** [comment]
Found out that the user was trying to perform API calls hadn't inserted his PGP Key. Is this related, and if it is, where's quoted inside the documentation?

BTW I'll close
