### ISSUE TITLE
Importing iocs from openioc file format failure

### ISSUE THREAD

**Issue by torsolaso** [MISP/MISP#4956]
Hi,

When we try to upload iocs from openioc file format we get an internal error. We debugged the logs and it seems that the variable "sharing_group_id" is null. Below all the logs attached.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.2.6-1
| MISP version / git hash   | 2.4.112

### Expected behavior
Upload Iocs

### Actual behavior

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

### Steps to reproduce the behavior
1. Create an event
2. Click on "Populate from" 
3. Click on OpenIOC Import
4. Upload the file on  "Open IOC file" section below attached.

### Logs, screenshots, configuration dump, ...

```
2019-08-05 18:31:44 Warning: Warning (2): array_keys() expects parameter 1 to be array, null given in [/var/www/MISP/app/Controller/Component/IOCImportComponent.php, line 341]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
array_keys - [internal], line ??
IOCImportComponent::__isAssoc() - APP/Controller/Component/IOCImportComponent.php, line 341
IOCImportComponent::__createRootNode() - APP/Controller/Component/IOCImportComponent.php, line 296
IOCImportComponent::readXML() - APP/Controller/Component/IOCImportComponent.php, line 171
EventsController::_addIOCFile() - APP/Controller/EventsController.php, line 3170
EventsController::addIOC() - APP/Controller/EventsController.php, line 2008
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-08-05 18:31:44 Warning: Warning (2): array_filter() expects parameter 1 to be array, null given in [/var/www/MISP/app/Controller/Component/IOCImportComponent.php, line 341]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
array_filter - [internal], line ??
IOCImportComponent::__isAssoc() - APP/Controller/Component/IOCImportComponent.php, line 341
IOCImportComponent::__createRootNode() - APP/Controller/Component/IOCImportComponent.php, line 296
IOCImportComponent::readXML() - APP/Controller/Component/IOCImportComponent.php, line 171
EventsController::_addIOCFile() - APP/Controller/EventsController.php, line 3170
EventsController::addIOC() - APP/Controller/EventsController.php, line 2008
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-08-05 18:31:44 Warning: Warning (2): count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Controller/Component/IOCImportComponent.php, line 341]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
IOCImportComponent::__isAssoc() - APP/Controller/Component/IOCImportComponent.php, line 341
IOCImportComponent::__createRootNode() - APP/Controller/Component/IOCImportComponent.php, line 296
IOCImportComponent::readXML() - APP/Controller/Component/IOCImportComponent.php, line 171
EventsController::_addIOCFile() - APP/Controller/EventsController.php, line 3170
EventsController::addIOC() - APP/Controller/EventsController.php, line 2008
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-08-05 18:31:44 Warning: Warning (2): count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Controller/Component/IOCImportComponent.php, line 193]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
IOCImportComponent::readXML() - APP/Controller/Component/IOCImportComponent.php, line 193
EventsController::_addIOCFile() - APP/Controller/EventsController.php, line 3170
EventsController::addIOC() - APP/Controller/EventsController.php, line 2008
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-08-05 18:31:44 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'sharing_group_id' doesn't have a default value
Request URL: /events/addIOC/10772
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Attribute), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2352): Model->save(Array, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2572): Model->saveMany(Array, Array)
#7 /var/www/MISP/app/Controller/EventsController.php(3201): Model->saveAssociated(Array, Array)
#8 /var/www/MISP/app/Controller/EventsController.php(2008): EventsController->_addIOCFile('10772')
#9 [internal function]: EventsController->addIOC('10772')
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

### Open IOC file

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenIOC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="c6f55a03-2967-4f91-a20c-3666341db64f" last-modified="2019-08-01T05:51:44" published-date="0001-01-01T00:00:00" xmlns="http://openioc.org/schemas/OpenIOC_1.1">
  <metadata>
    <short_description></short_description>
    <description><![CDATA[Falcon Sandbox v8.30 auto-generated IOC for c4056fea5a2496ccbd1c0621a7dd5dc02058dde154c0236e3a7c0bd6739d8679 (SHA256: c4056fea5a2496ccbd1c0621a7dd5dc02058dde154c0236e3a7c0bd6739d8679)]]></description>
    <keywords></keywords>
    <authored_by>Hybrid Analysis</authored_by>
    <authored_date>2019-08-01T05:51:44</authored_date>
    <links></links>
  </metadata>
  <criteria>
    <Indicator operator="OR" id="69954d1d-5821-48d0-9426-0a98171ce19c">
      <Indicator operator="AND" id="f496c290-4eb4-4829-9f2a-979dfc8ba44e">
        <IndicatorItem id="6d2cbdd8-0214-4330-bc7d-c64d13e97542" condition="contains">
          <Context document="ProcessItem" search="ProcessItem/StringList/string" type="vxs"></Context>
          <Content type="string"><![CDATA['#j4@T.M]]></Content>
        </IndicatorItem>
        <IndicatorItem id="478221c6-d743-4524-b93f-587d7f2fe0f5" condition="contains">
          <Context document="ProcessItem" search="ProcessItem/StringList/string" type="vxs"></Context>
          <Content type="string"><![CDATA[GetActiveWindow]]></Content>
        </IndicatorItem>
        <IndicatorItem id="2ac61178-cc6a-4d0f-b4ac-f7803243f5d9" condition="contains">
          <Context document="ProcessItem" search="ProcessItem/StringList/string" type="vxs"></Context>
          <Content type="string"><![CDATA[GetLastActivePopup]]></Content>
        </IndicatorItem>
        <IndicatorItem id="aaa3b1f4-66e8-4c2f-887d-698e26d0e977" condition="contains">
          <Context document="ProcessItem" search="ProcessItem/StringList/string" type="vxs"></Context>
          <Content type="string"><![CDATA[LoadRegTypeLib]]></Content>
        </IndicatorItem>
        <IndicatorItem id="7ef9fba0-1ddb-453a-8c32-b45d80a6f175" condition="contains">
          <Context document="ProcessItem" search="ProcessItem/StringList/string" type="vxs"></Context>
          <Content type="string"><![CDATA[LoadTypeLib]]></Content>
        </IndicatorItem>
      </Indicator>
    </Indicator>
  </criteria>
</OpenIOC>
```

**Comment by jloehel** [comment]
@torsolaso There are two different things happening. You tried to upload a file in the OpenIOC 1.1 format. The old OpenIOC import can only handle the OpenIOC 1.0 format:

https://github.com/MISP/MISP/blob/eebe0310916a6c54f7387cb9499b72e21c4d8688/app/Controller/Component/IOCImportComponent.php#L296

It will fail in line 296 because the key `definitions` does not exist in 1.1. The array functions get null instead of an array.

Furthermore the sharing_group_id is missing:

https://github.com/MISP/MISP/blob/eebe0310916a6c54f7387cb9499b72e21c4d8688/app/Controller/EventsController.php#L3079-L3098

I patched it quick and dirty with:
```
diff --git a/../../Controller/EventsController.php b/tmp/EventsController.php
index a3d1ea1..9882a9e 100644
--- a/../../Controller/EventsController.php
+++ b/tmp/EventsController.php
@@ -3083,7 +3083,6 @@ class EventsController extends AppController
                 'to_ids' => false,
                 'distribution' => $dist,
                'data' => base64_encode($xmlFileData),
-               'sharing_group_id' => 0,
                 'comment' => 'OpenIOC import source file'
             );
 
@@ -3094,7 +3093,7 @@ class EventsController extends AppController
 
             $fieldList = array(
                     'Event' => array('published', 'timestamp'),
-                    'Attribute' => array('event_id', 'category', 'type', 'value', 'value1', 'value2', 'to_ids', 'uuid', 'distribution', 'timestamp', 'sharing_group_id', 'comment')
+                    'Attribute' => array('event_id', 'category', 'type', 'value', 'value1', 'value2', 'to_ids', 'uuid', 'distribution', 'timestamp', 'comment')
             );
             // Save it all
             $saveResult = $this->Event->saveAssociated($saveEvent, array('validate' => true, 'fieldList' => $fieldList));
``` 

Anyway, the code seems deprecated. @PROTechThor When will you remove it or is it possible to deactivate it?

**Comment by enjeck** [comment]
> Anyway, the code seems deprecated. @PROTechThor When will you remove it or is it possible to deactivate it?

@jloehel 
I think @iglocska or @SteveClement can answer this question, not me.
