### ISSUE TITLE
1213 Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by Scudmeister** [MISP/MISP#5004]
MISP has been returning a number of "500 An Internal Error Has Occurred" responces.
We are using a MySQL datebase.
Example details from server error.log:

2019-08-12 11:11:13 Error: [PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
Request URL: /events/edit/40
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Correla...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Correla...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2872): Mysql->delete(Object(AppModel), ' WHERE `Correla...')
#4 /var/www/MISP/app/Model/Attribute.php(1762): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Attribute.php(617): Attribute->__beforeSaveCorrelation(Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->beforeSave(Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#9 /var/www/MISP/app/Model/Attribute.php(3943): Model->save(Array, Array)
#10 /var/www/MISP/app/Model/MispObject.php(695): Attribute->editAttribute(Array, '40', Array, '114', Object(Log))
#11 /var/www/MISP/app/Model/Event.php(3749): MispObject->editObject(Array, '40', Array, Object(Log))
#12 /var/www/MISP/app/Controller/EventsController.php(2236): Event->_edit(Array, Array, '40')
#13 [internal function]: EventsController->edit('40')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#17 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior
200 responce 

### Actual behavior
500

### Logs, screenshots, configuration dump, ...
2019-08-12 11:11:13 Error: [PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
Request URL: /events/edit/40
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Correla...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Correla...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2872): Mysql->delete(Object(AppModel), ' WHERE `Correla...')
#4 /var/www/MISP/app/Model/Attribute.php(1762): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Attribute.php(617): Attribute->__beforeSaveCorrelation(Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->beforeSave(Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#9 /var/www/MISP/app/Model/Attribute.php(3943): Model->save(Array, Array)
#10 /var/www/MISP/app/Model/MispObject.php(695): Attribute->editAttribute(Array, '40', Array, '114', Object(Log))
#11 /var/www/MISP/app/Model/Event.php(3749): MispObject->editObject(Array, '40', Array, Object(Log))
#12 /var/www/MISP/app/Controller/EventsController.php(2236): Event->_edit(Array, Array, '40')
#13 [internal function]: EventsController->edit('40')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#17 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}

**Comment by Scudmeister** [comment]
This MISP instance is running on an Azure ubuntu 18.04 VM.

**Comment by Scudmeister** [comment]
More investigation of our logs etc. show that in each case our system was making multiple calls (maximum of 3, each with a new and different event) into misp_api.uploadStix, followed by a call into misp_api.updateEvent.

We are now wondering if MISP in itself is not thread safe.

Can you advise if this indeed the case that MISP is not thread safe?

**Comment by VVX7** [comment]
I'm seeing the same thing when sending asynch requests to MISP.  ~1k attributes added to an event using a worker pool.  It also messes up the number of reported attributes. Event 3 has 175 attributes according to the event list and 834 in the event.

![event_list](https://user-images.githubusercontent.com/46228229/78502264-4c44ce00-772e-11ea-9c7b-5284dd29705a.png)

![event_3](https://user-images.githubusercontent.com/46228229/78502267-4fd85500-772e-11ea-972d-84154dc5f269.png)

```
Error: [PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
Request URL: /attributes/add/3
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('UPDATE `misp`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute('UPDATE `misp`.`...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update(Object(Event), '`id` = 3, `org_...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/Attribute.php(672): Model->save(Array, Array)
#6 /var/www/MISP/app/Model/Attribute.php(764): Attribute->__alterAttributeCount('3')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave(true, Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#10 /var/www/MISP/app/Model/Attribute.php(4084): Model->save(Array, Array)
#11 /var/www/MISP/app/Controller/AttributesController.php(181): Attribute->captureAttribute(Array, '3', Array, false, Object(Log), false, Array, Array)
#12 [internal function]: AttributesController->add('3')
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}
```

**Comment by Rafiot** [comment]
The exception you get is because you MySQL cannot keep up with the amount of requests. You need to give more resources to the database, or reduce the speed at which you're hammering MISP.

The attribute count is unrelated to that.

**Comment by github-germ** [comment]
Any tips on what MySQL resource cnf settings to tune would be appreciated as we just started seeing these in our MISP also. Thanks!!

**Comment by Scudmeister** [comment]
Hi.
We never found the real cause, we always thought it was a MISP problem and not a db config issue, but got around it by implementing a retry process within our code, which worked really well – never ‘saw’ the problem again.

**Comment by github-germ** [comment]
Thanks... We've also wrapped all our PyMISP custom app code interfacing the API calls with  retries with exponential back-off and paginating large requests. These measures certainly helped. At times we are seeing these deadlocks in Default Feed fetching processing which is not in our control.

**Comment by iglocska** [comment]
Interesting, the feed fetcher might use some longer lasting bulk entries as
a performance tweak - those are the ones that bite us in the arse when
we're in a high parallel processing mode due to some other scripts.
Definitely one to look into.

**Comment by chrisinmtown** [comment]
I'd like to report we see many occurrences of this error when adding objects to a version 2.4.133 MISP server. The server is relatively lightly loaded, there are few jobs running. The theory about a database that is starved for resources is not likely for us, that box is bare metal (not virtual) and has main memory size of at least 10x the database size, and Mysql has been configured to use most of that memory.

Any other suggestions or ideas? Simply retrying is a poor solution 👎 
```
2021-01-13 20:56:11 Error: [PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
Request URL: /objects/add/889daee3-cefc-4599-b521-0cf765b59799
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('UPDATE `misp`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute('UPDATE `misp`.`...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2672): Mysql->update(Object(Event), '`Event`.`attrib...', NULL, ' WHERE `Event`....')
#4 /var/www/MISP/app/Model/Attribute.php(699): Model->updateAll(Array, Array)
#5 /var/www/MISP/app/Model/Attribute.php(792): Attribute->__alterAttributeCount('202219')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave(true, Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#9 /var/www/MISP/app/Model/Attribute.php(3770): Model->save(Array)
#10 /var/www/MISP/app/Model/MispObject.php(393): Attribute->saveAttributes(Array, Array)
#11 /var/www/MISP/app/Controller/ObjectsController.php(270): MispObject->saveObject(Array, '202219', Array, Array, 'halt', false)
#12 [internal function]: ObjectsController->add('202219')
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ObjectsController), Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ObjectsController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}
```

**Comment by chrisinmtown** [comment]
> Can you advise if this indeed the case that MISP is not thread safe?

It would be REALLY helpful if the CIRCL team would please answer this question.

**Comment by chrisinmtown** [comment]
I most recently hit this problem while trying to ingest modest amounts of data. I was adding a single object with 20 or so attributes to an existing event. Nobody else was doing much of anything.  But I was ingesting data that had already been ingested so the correlations were enormous, about 4 million from my 10 or so events. I speculate - truly a SWAG - that the load on the sql server due to updating the correlations table causes this problem.

**Comment by iglocska** [comment]
Yeah that sounds like it. 4M entries from 10 events is pretty wild.

**Comment by chrisinmtown** [comment]
Here's the latest deadlock problem that's bedeviling us.  Happens in the context of adding 10 MISPObjectAttribute collections to an Event, when MISP tries to update correlations:
```
2021-06-18 19:00:31 Error: [PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
Request URL: /events/edit/246548/metadata:1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Correlation), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2352): Model->save(Array, Array)
#6 /var/www/MISP/app/Model/Correlation.php(239): Model->saveMany(Array, Array)
#7 /var/www/MISP/app/Model/Correlation.php(349): Correlation->__saveCorrelations(Array)
#8 /var/www/MISP/app/Model/Attribute.php(432): Correlation->afterSaveCorrelation(Array, false, Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave(true, Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#12 /var/www/MISP/app/Model/Attribute.php(3631): Model->save(Array, Array)
#13 /var/www/MISP/app/Model/MispObject.php(994): Attribute->captureAttribute(Array, '246548', Array, '3544371', Object(Log))
#14 /var/www/MISP/app/Model/MispObject.php(1048): MispObject->captureObject(Array, '246548', Array, Object(Log))
#15 /var/www/MISP/app/Model/Event.php(4123): MispObject->editObject(Array, '246548', Array, Object(Log), false, false)
#16 /var/www/MISP/app/Controller/EventsController.php(2456): Event->_edit(Array, Array, '246548')
#17 [internal function]: EventsController->edit('246548')
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#21 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#22 {main}
```

**Comment by juju4** [comment]
I also observe this from time to time in github workflow from my ansible role
example:
https://github.com/juju4/ansible-MISP/runs/5079564814?check_suite_focus=true#step:14:68

I don't expect any load issue as build on commit/schedule with just few pymisp calls to ensure functional.
In above example, list user, add user1 worked but adding user2 failed.

**Comment by mamoedo** [comment]
I'm also facing this issue when using the The Hive integration https://github.com/TheHive-Project/TheHive/issues/2222
