### ISSUE TITLE
How to troubleshoot push-SYNC problems?

### ISSUE THREAD

**Issue by ITServ-DE** [MISP/MISP#5007]
Ladies and Gentleman,

I'm playing with MISP sync and two servers, and I have a working setup for **pulling** events from one host to the other. But I'd like to reverse the process: I want to **push**. For some reason, I don't get it work. The connection has been setup by creating a sync config on the target host and import of the settings on the source host.

The connectivity test succeeds, I can also explore the events on the remote server, but when I add and publish an event on the source start the push to the target, it does not show up on the target system. Still, pulling works.

During push, I see network traffic on the target host, so the communication is established. But I also see some HTTP 403 (forbidden) on the target host:
```
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 3943 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "POST /events/filterEventIdsForPush HTTP/1.1" 200 4531 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "POST /events HTTP/1.1" 403 4317 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "POST /events HTTP/1.1" 403 4317 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "POST /events/index HTTP/1.1" 403 3873 "-" "CakePHP"
```
I double-checked that the source host uses the API key for a SYNC account on the target, but still I get an Authentication error logged in the error.log:

```
2019-08-15 09:33:51 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /events/index
Stack Trace:
#0 /var/www/MISP/app/Controller/EventsController.php(55): AppController->beforeFilter()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
``` 

Just for fun an curiosity, I've changed the API key for the sync operation to an admin's key - no change. I also disabled `MISP.enableEventBlacklisting` to make sure I did not miss some blacklisting setting I'm not aware of.

Which more options do I have for troubleshooting? Is there a setting required to allow the target system to accept push delivery of events?

Thank you for your support.

**Comment by ITServ-DE** [comment]
I'd like to add the following:
* I enabled `MISP.log_paranoid = True`
* I enabled `MISP.log_paranoid_include_post_body = True`

This makes me find HTTP POST requests without a request body:
![Snag_29af024c](https://user-images.githubusercontent.com/50981940/63082390-6aaf4c80-bf46-11e9-866b-2a881b1212d4.png)

Is this normal? I thought POST requests have the data in it?

**Comment by ITServ-DE** [comment]
must be a bug, opening bug report.

**Comment by iglocska** [comment]
Just tested it, it works fine for me (latest HEAD). Your POST request is not empty, it's "[]", so an empty list which is valid. Also, it clearly says that it's an authentication issue.

**Comment by ITServ-DE** [comment]
Now I'm on the latest HEAD (2.4.113), and it still does not work. I see the following:

From my "pushing" server, I can browse the remote server. This basically means that the key I use works for reading events.

The authentication key stored on the "pushing" server is the auth key of a SYNC user on the target system, and the sync role has granted the sync role.

Strange enogh, my "pushing" server's error log has these entries:
```
2019-08-19 09:08:20 Warning: array_merge(): Argument #2 is not an array in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 457]
2019-08-19 09:08:32 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 883]
2019-08-19 09:08:33 Warning: array_merge(): Argument #2 is not an array in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 457]
2019-08-19 09:08:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 883]
2019-08-19 09:15:37 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 883]
2019-08-19 09:15:38 Warning: array_merge(): Argument #2 is not an array in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 457]
2019-08-19 09:15:38 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 883]
```

I don't know if this has something to do with my problem, but I'll follow that trail ...

**Comment by ITServ-DE** [comment]
OK, I'm quite sure I now know the problem: MISP simply forgets to send the authorization header.

I have reconfigured my target MISP to use unencrypted HTTP and got a packet dump. Then, I ran a `strings` command over it (I do not have WireShark at hand, but that's close enough). And now I clearly see the Authorization header is missing.

Here the HTTP dialog of the last two HTTP requests.

### Request with key:
```
GET /servers/getVersion HTTP/1.1
Host: misp2.itserv.de
Connection: close
User-Agent: CakePHP
Authorization: 8*********SYNC-API-KEY***********p
Accept: application/json
Content-Type: application/json
MISP-version: 2.4.113
commit: e296288f59a33dc603fb282f191af4b36e7a61ad
Cookie: MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=6p84vp7476murb2iuo68d9i5g0
```

### Server Response
```
HTTP/1.1 200 OK
Date: Mon, 19 Aug 2019 08:12:33 GMT
Server: Apache/2.4.25 (Debian)
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Set-Cookie: MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Set-Cookie: MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=6p84vp7476murb2iuo68d9i5g0; expires=Mon, 19-Aug-2019 18:12:33 GMT; Max-Age=36000; path=/; HttpOnly
Set-Cookie: MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=4rmu0hob399p9pdj4gddo8ol93; expires=Mon, 19-Aug-2019 18:12:33 GMT; Max-Age=36000; path=/; HttpOnly
Set-Cookie: MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=4rmu0hob399p9pdj4gddo8ol93; expires=Mon, 19-Aug-2019 18:12:33 GMT; Max-Age=36000; path=/; HttpOnly
Content-Length: 38
Connection: close
Content-Type: application/json; charset=UTF-8
{"version":"2.4.113","perm_sync":true}
```

### Next Request, which is failing
Now the HTTP request **without the API key**:

```
POST /events/index HTTP/1.1
Host: misp2.hidden.domain
Connection: close
User-Agent: CakePHP
Accept: application/json
Content-Type: application/json
MISP-version: 2.4.113
commit: e296288f59a33dc603fb282f191af4b36e7a61ad
Content-Length: 13
Cookie: MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=4rmu0hob399p9pdj4gddo8ol93
{"minimal":1}
```

### Server Response: **forbidden**

```
#HTTP/1.1 403 Forbidden
Date: Mon, 19 Aug 2019 08:12:33 GMT
Server: Apache/2.4.25 (Debian)
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 284
Connection: close
Content-Type: application/json; charset=UTF-8
{"name":"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.","message":"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.","url":"\/events\/index"}

```

This is the definition of the remote Server:

![Snag_3e54c0c6](https://user-images.githubusercontent.com/50981940/63250892-f558ba00-c26c-11e9-9ada-1bb6959f378f.png)

So the question is: why is the authorization header missing?

**Comment by iglocska** [comment]
Interesting. I'll try to reproduce this, but your previous error log together with this is quite telling, so that should be a good starting point:

```
2019-08-19 09:08:20 Warning: array_merge(): Argument #2 is not an array in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 457]
```

This sounds like the headers were passed in an incorrect format internally which meant that it was never added to the request. I'll try to debug it!

**Comment by ITServ-DE** [comment]
If you need me to run any test, tell me, I'll gladly do. And I could also grant you access to the two servers, if required. They are my personal playground.

For now, I will try to switch directions and see if I could make it work with switched sender/receiver role.

**Comment by ITServ-DE** [comment]
No, doesn't work in the other direction either.

**Comment by iglocska** [comment]
I am a bit confused, /events/index should not be part of the equation, really weird.

**Comment by iglocska** [comment]
Are you sure it's a push and not a pull that's failing?

**Comment by ITServ-DE** [comment]
Yes, I am. 
Push fails, pull works.

**Comment by ITServ-DE** [comment]
But let me add, the log message 

```
2019-08-19 09:08:20 Warning: array_merge(): Argument #2 is not an array in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 457]
```

must not be associated with the problem. I have this in my logs, but I'm not able to reproduce it. I have no idea what I've done to get this message. However, it' surely a bug - related or unrelated with my sync problem.

I have read through the relevant part of the source code, and even though I have very limited experience with PHP and object-oriented programming, I was not able to identify the code that **should** take the authkey for the POST message from the database. The methods `runPOSTtest` and `runConnectionTest` use very different methods to define `$server` which is used for `setupSyncRequest`.

I would guess (but it's not more) the AuthKey is not read from the DB during Server object creation.

**Comment by ITServ-DE** [comment]
If I hard-code the sync AuthKey in setupSyncRequest, the HTTP-403 error message is gone. The sync did not succeed though, but that might well be a different problem.

Original code (app/Model/AppModel.php)
```
 public function setupSyncRequest($server)
    {
        $request = array(
                'header' => array(
                        'Authorization' => $server['Server']['authkey'],
                        'Accept' => 'application/json',
                        'Content-Type' => 'application/json'
                )
        );
        $request = $this->addHeaders($request);
        return $request;
    }
```

My hacked version:

``` 
public function setupSyncRequest($server)
    {
        $request = array(
                'header' => array(
                        'Authorization' => '8*********SYNC-API-KEY***********p',
                        'Accept' => 'application/json',
                        'Content-Type' => 'application/json'
                )
        );
        $request = $this->addHeaders($request);
        return $request;
    }
```

**Comment by iglocska** [comment]
I don't see how that can happen unless your server object doesn't have the API key set up.

Go to: 
`https://path.to.your.misp/servers/index.json`

and look for the server config of the instance you're pushing to - in the authkey field, do you see the correct API key?

**Comment by ITServ-DE** [comment]
It's defined and matches that authkey of a user with the sync role on the target system.

Here is the output (is the undefined type of the remote org nomal?)
```
[
    {
        "Server": {
            "id": "3",
            "name": "MISP2",
            "url": "http:\/\/misp2.my.domain",
            "authkey": "8*********SYNC-API-KEY*****************p",
            "org_id": "1",
            "push": true,
            "pull": false,
            "lastpulledid": null,
            "lastpushedid": "293",
            "organization": null,
            "remote_org_id": "20",
            "publish_without_email": true,
            "unpublish_event": true,
            "self_signed": false,
            "pull_rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]}}",
            "push_rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]}}",
            "cert_file": null,
            "client_cert_file": null,
            "internal": false,
            "skip_proxy": false,
            "caching_enabled": false,
            "cache_timestamp": false
        },
        "Organisation": {
            "id": "1",
            "name": "ORGNAME",
            "uuid": "5cdd8e19-31a8-4f52-8d82-3dc25c69efb1",
            "nationality": "Not specified",
            "sector": null,
            "type": "ADMIN"
        },
        "RemoteOrg": {
            "id": "20",
            "name": "EMIP",
            "uuid": "5d42d607-d850-4a6c-a331-104f2578bf2d",
            "nationality": "Not specified",
            "sector": "",
            "type": ""
        },
        "User": []
    }
]
```

**Comment by ITServ-DE** [comment]
And directly out of the DB:

```
m?1034hMariaDB [misp]> select * from servers:;KK;
+----+-------+------------------------+------------------------------------------+--------+------+------+--------------+--------------+--------------+---------------+-----------------------+-----------------+-------------+-------------------------------------------------------+-------------------------------------------------------+-----------+------------------+----------+------------+-----------------+
| id | name  | url                    | authkey                                  | org_id | push | pull | lastpulledid | lastpushedid | organization | remote_org_id | publish_without_email | unpublish_event | self_signed | pull_rules                                            | push_rules                                            | cert_file | client_cert_file | internal | skip_proxy | caching_enabled |
+----+-------+------------------------+------------------------------------------+--------+------+------+--------------+--------------+--------------+---------------+-----------------------+-----------------+-------------+-------------------------------------------------------+-------------------------------------------------------+-----------+------------------+----------+------------+-----------------+
|  3 | MISP2 | http://misp2.my.domain | 8*********SYNC-API-KEY*****************p |      1 |    1 |    0 |         NULL |          293 | NULL         |            20 |                     1 |               1 |           0 | {"tags":{"OR":[],"NOT":[]},"orgs":{"OR":[],"NOT":[]}} | {"tags":{"OR":[],"NOT":[]},"orgs":{"OR":[],"NOT":[]}} | NULL      | NULL             |        0 |          0 |               0 |
+----+-------+------------------------+------------------------------------------+--------+------+------+--------------+--------------+--------------+---------------+-----------------------+-----------------+-------------+-------------------------------------------------------+-------------------------------------------------------+-----------+------------------+----------+------------+-----------------+
0;1m1 row in set (0.00 sec)
m0;1m
mMariaDB [misp]> 0;1mBye
m0;root@hive: ~root@hive:~# exit
```

**Comment by iglocska** [comment]
Hmph, that looks good...

**Comment by ITServ-DE** [comment]
Sorry. I would like to be able to provide a neon arrow pointing at the problem.

Is there a simple way for me to inject logging commands into the source code, so I could help searching? Again, I'm not too familiar with PHP.

**Comment by iglocska** [comment]
Finally found where the /events/index call comes from - it's the proposal sync part. So whilst I cannot reproduce your issue with the auth key being stripped (it definitely does get set correctly for me) on that call - it is also a call that is not necessary to synchronise events.

The process of syncing works like this:

1. MISP A determines that a server is suitable for pushing
2. MISP A asks MISP B about its version number
3. If all is fine with [2], MISP A asks MISP B for a list of available event UUIDs along with their timestamps
4. MISP A fetches a list of all events locally that meet the criteria to be pushed and removes any events that exist on the remote side and are at least the same age as on the local side
5. MISP A starts looping through the events and either uploads them (if the UUID isn't known by the remote) or updates it on the remote side (if the UUID exists but the timestamp is outdated on the remote)
6. Once this is done, MISP queries the remote side for all visible event UUIDs (via /events/index <- the call that fails for you)
7. MISP will then use these UUIDs to fetch all of the proposals on the local side that belong to events already known to the remote and pushes them (if [6] fails, this is what won't work for you).



Just to ensure that there isn't something absolutely silly happening here, could you do the following?

POST to you pushing server's event add endpoint `/events/add`
with headers set as follows:
```
Authorization: MY_API_KEY
Accept: application/json
Authorization: application/json
```
The body of the request should be as follows:
```
{
    "info": "test",
    "distribution": 2,
    "published": 1,
    "Attribute": [{
          "value": "foobar",
          "type": "comment"
     }]
}
```

This should:
1. Create an event on your pushing server
2. publish said event
3. automatically push the event to the remote site (distribution is set to 2)

Keep in mind, pushing data requires the following:
1. Events have to be published
2. Events have to have a distribution setting >= connected community
3. The sync link has to have the push flag set
4. The sync link cannot have any filters set that would prevent the push
5. The remote user has to have read, write, publish permissions along with the sync permission

**Comment by ITServ-DE** [comment]
I will double-check your requirements this evening.


OK, I ran the following code (fixed your missing Content-Type):
```
curl -XPOST -H "Authorization: 8*********SYNC-API-KEY********p" \
		 -H "Accept: application/json" \
		 -H "Content-Type: application/json" \
		 -d '{"info":"test","distribution":2,"published":1,"Attribute":[{"value":"foobar","type:":"comment"}]}'		 \
		 http://misp2.my.domain/events/add

```
and got this response:

```
{
    "Event": {
        "id": "460",
        "orgc_id": "3",
        "org_id": "3",
        "date": "2019-08-20",
        "threat_level_id": "4",
        "info": "test",
        "published": true,
        "uuid": "5d5bedf3-10dc-4d61-8efe-127f2578bf2d",
        "attribute_count": "0",
        "analysis": "0",
        "timestamp": "1566305779",
        "distribution": "2",
        "proposal_email_lock": false,
        "locked": false,
        "publish_timestamp": "1566305779",
        "sharing_group_id": "0",
        "disable_correlation": false,
        "extends_uuid": "",
        "Org": {
            "id": "3",
            "name": "EMIP",
            "uuid": "5d42d607-d850-4a6c-a331-104f2578bf2d"
        },
        "Orgc": {
            "id": "3",
            "name": "EMIP",
            "uuid": "5d42d607-d850-4a6c-a331-104f2578bf2d"
        },
        "Attribute": [],
        "ShadowAttribute": [],
        "RelatedEvent": [],
        "Galaxy": [],
        "Object": []
    }
}

```

The event is shown on the target system:

![Snag_446d770a](https://user-images.githubusercontent.com/50981940/63349145-1ac3f180-c35b-11e9-9dac-b4de788027d9.png)

Sorry, I have to leave now, but I'll be back tomorrow.

As mentioned before, I was able to bypass the 403-Error by hardcoding my Sync Key into `function setupSyncRequest` (in `app/Model/AppModel.php`). Running a sync than gives me part of your protocol description, but drives wild after step 4 or so and continues to ask for Version numbers.

(Output from libapache_forensics_log)
```
+4574:5d5ba301:1|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad
-4574:5d5ba301:1
+4575:5d5ba301:1|POST /events/filterEventIdsForPush HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Content-Length:8056
-4575:5d5ba301:1
+4571:5d5ba301:2|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=p0iqq0mrldlgocod1h1uj3p9l0
-4571:5d5ba301:2
+4573:5d5ba301:1|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=24c0o6pfk8f5pi9hl6ok33aqs3
-4573:5d5ba301:1
+4589:5d5ba301:0|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=ev4871odcabjd0n3ouukcgnuc1
-4589:5d5ba301:0
+4588:5d5ba301:1|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=67073e1dajqjbbra8rb1jhbu55
-4588:5d5ba301:1
+4572:5d5ba302:2|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=cro4ulskohcb1k5loq7g987hk4
-4572:5d5ba302:2
+4587:5d5ba302:1|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=kb9082drjl81ghcdmh93tjrjt3
-4587:5d5ba302:1
+4574:5d5ba302:2|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=gt7klj6vpdgckqn3o5nb7m48u5
-4574:5d5ba302:2
+4575:5d5ba302:2|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=aedvi2saq2d8ebrth7p8obhq67
-4575:5d5ba302:2
+4571:5d5ba302:3|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=bk2o6tv65hn0hp8t7o9m1msqe7
-4571:5d5ba302:3
+4573:5d5ba302:2|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=qe2j0vfahm0mmmki47i34rro23
-4573:5d5ba302:2
+4589:5d5ba302:1|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=fp8dtp2utrmm33bcsn2i0qhg90
-4589:5d5ba302:1
+4588:5d5ba302:2|GET /servers/getVersion HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=unfh2fssdbtkcua10dca764da5
-4588:5d5ba302:2
+4572:5d5ba302:3|POST /events/index HTTP/1.1|Host:misp2.my.domain|Connection:close|User-Agent:CakePHP|Authorization:8*****KEY*******p|Accept:application/json|Content-Type:application/json|MISP-version:2.4.113|commit:e296288f59a33dc603fb282f191af4b36e7a61ad|Content-Length:13|Cookie:MISP-5d42ad40-988c-47c9-8e35-02282578bf2d=62gv1v9abfr29rfodoqfvf56p5
-4572:5d5ba302:3

```

**Comment by ITServ-DE** [comment]
Just a last quick question: I do not have to configure the sync link on **both** sides of the link, do I? For pulling, it was enough to configure the link on the pulling server, so I assume when I push the target server does not have to be aware of the other host.

Right?

**Comment by iglocska** [comment]
Definitely not. Having a one way connection is fine, that's how I test it too. The version checks are indeed a bit annoying but they're also fine, we do a version check on each push atm I think, so at least it's trying to push something.

**Comment by ITServ-DE** [comment]
I think it works now. Needs more testing, I'll return with news when they are triple-checked.

Probable error source: User->ID10T

**Comment by iglocska** [comment]
Oh wow, what was it?

**Comment by ITServ-DE** [comment]
OK, it works now. And I don't have an idea what it was. I don't get it.

But one last point: when I push from source to destination, the event needs to be published to "connected community". When I pull, it's enough to have an event shared with "this community only".

Does that make sense for you?

I have to admit, I didn't understand sharing and sharing groups yet, so I'm not really sure whats going on. But I'm learning ...
