### ISSUE TITLE
Worker type: scheduler randomly/constantly crashing after a few minutes 

### ISSUE THREAD

**Issue by leveepointe** [MISP/MISP#5016]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version                 | Ubuntu 18.04.2
| PHP version               | 7.2.19
| MISP version / git hash   | 2.4.112
| Browser                   | n/a

### Expected behavior
Start Server and All workers are healthy and working not crashing after few minutes.

### Actual behavior
All workers can be restarted but only scheduler will crash after random time

### Steps to reproduce the behavior
New Install/Build on VM not docker

### Logs, screenshots, configuration dump, ...
==> /var/www/MISP/app/tmp/logs/resque-scheduler-error.log <==
Warning Error: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]

Warning Error: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]

Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php(248): Redis->zRangeByScore('_schdlr_', '-inf', '1565979443', Array)
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(61): ResqueScheduler\ResqueScheduler::nextDelayedTimestamp(1565979443)
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(44): ResqueScheduler\Worker->handleDelayedItems()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work('3')
#4 {main}

Pulled from error log all logs point to redis.resque error but not able to resolve.  Redis listening on 6379. Please Advise Thanks

**Comment by leveepointe** [comment]
resolved by rtfm Section:Troubleshooting MISP not connecting to redis but redis-cli working. Closing
