### ISSUE TITLE
workers problem after clean install (ubuntu 18.04)

### ISSUE THREAD

**Issue by GelosSnake** [MISP/MISP#5107]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| OS version (server)       | , ubuntu, 
| OS version (client)       | 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.114 

### Expected behavior
Workers should be up to 5

### Actual behavior
![image](https://user-images.githubusercontent.com/5004714/64285413-74840880-cf64-11e9-9b1e-e84a238fc538.png)

### Steps to reproduce the behavior
clean install using the main script:
https://misp.github.io/MISP/INSTALL.ubuntu1804/

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/5004714/64285633-8e255000-cf64-11e9-81e3-1af1b88e6865.png)

**Comment by GelosSnake** [comment]
Some error might be related? 

$cat /var/www/MISP/app/tmp/logs/resque-worker-error.log

Error: Call to undefined method Monolog\Logger::addInfo()
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(360): Resque_Worker->log('Starting worker...', 200)
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(194): Resque_Worker->startup()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('cache', 1, Object(MonologInit\MonologInit), '5')
#4 {main}

**Comment by GelosSnake** [comment]
This issue is duplicated of #5085 
Fixed by downgrading monlog:
$ su -s /bin/bash www-data -c 'php ./composer.phar require monolog/monolog=1.24.0'
