### ISSUE TITLE
Feed download error: 406 not acceptable

### ISSUE THREAD

**Issue by 1earch** [MISP/MISP#5131]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Not applicable
| PHP version               | 7.2
| MISP version / git hash   | 2.4.115, 91e43787e04ca9618a97650170027337cbd8b317

### Expected behavior
Fetch all feeds.

### Actual behavior
Feeds from `hosts-file.net` aren't downloaded.

### Steps to reproduce the behavior
Fresh install of MISP, try to sync a feed hosted on `hosts-file.net`.

### Logs, screenshots, configuration dump, ...
```
2019-09-10 08:57:50 Error: Could not get freetext feed 20
[Exception] Fetching the 'https://hosts-file.net/psh.txt' failed with HTTP error 406: Not Acceptable
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(199): Feed->feedGetUri(Array, 'https://hosts-f...', Object(HttpSocket), true)
#1 /var/www/MISP/app/Model/Feed.php(1040): Feed->getFreetextFeed(Array, Object(HttpSocket), 'csv', 'all')
#2 /var/www/MISP/app/Model/Feed.php(1031): Feed->__cacheFreetextFeed(Array, Object(Redis), Object(HttpSocket), '6')
#3 /var/www/MISP/app/Model/Feed.php(1001): Feed->__cacheFeed(Array, Object(Redis), '6')
#4 /var/www/MISP/app/Console/Command/ServerShell.php(257): Feed->cacheFeedInitiator(Array, '6', '20')
#5 /var/www/MISP/app/Console/Command/AppShell.php(32): ServerShell->cacheFeed()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#11 {main}
```

**Comment by 1earch** [comment]
After debugging, the server `hosts-file.net` is responding the following:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>406 - Client browser does not accept the MIME type of the requested page.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>406 - Client browser does not accept the MIME type of the requested page.</h2>
  <h3>The page you are looking for cannot be opened by your browser because it has a file name extension that your browser does not accept.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

Modifying [line 464 of the feed model](https://github.com/MISP/MISP/blob/2.4/app/Model/Feed.php#L464) as bellow fixes the problem:
```
        $result = array(
            'header' => array(
                    'Accept' => array('application/json', 'text/plain'),
                    'Content-Type' => 'application/json',
                    'MISP-version' => $version,
                    'MISP-uuid' => Configure::read('MISP.uuid')
            )
        );
```
