### ISSUE TITLE
Can not export feed in STIX2 format using REST API or WebGUI

### ISSUE THREAD

**Issue by camAtGitHub** [MISP/MISP#5164]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Unknown
| OS version (client)       | Unknown
| PHP version               | Unknown
| MISP version / git hash   | MISP 2.4.115 - Commit unknown
| Browser                   | PyMISP

Sorry can't return the above details as it's not my server :-(

***I guess I'm wondering "Is this a bug that is known and has a solution?"***

### Expected behavior
Retrieve a STIX2 formatted feed from the REST API

### Actual behavior
ERROR Message.

    DEBUG [aping.py:2047 - _check_response() ] 0
    Traceback (most recent call last):
      File "debug.py", line 26, in <module>
        result = misp.search(publish_timestamp=args.last, limit=args.limit, pythonify=False, return_format='stix2')
      File "/usr/local/lib/python3.6/site-packages/pymisp/aping.py", line 1488, in search
        if 'errors' in normalized_response:
    TypeError: argument of type 'int' is not iterable

Also going the WebGUI @ https://SUBSCRIBED-MISP/events/export > Clicking 'Generate' for STIX2 and then clicking 'Download' returns a file with the contents of '0'.

### Steps to reproduce the behavior
    cam@cam:[/tmp]: cat debug.py
	
    #!/usr/bin/env python3
    # -*- coding: utf-8 -*-

    from pymisp import ExpandedPyMISP
    from keys import misp_url, misp_key, misp_verifycert, misp_client_cert
    import pymisp
    import argparse
    import os

    if __name__ == '__main__':
        parser = argparse.ArgumentParser(description='Download latest events from a MISP instance.')
        parser.add_argument("-m", "--limit", required=False, default="10")
        parser.add_argument("-l", "--last", required=True, default="24h")
        args = parser.parse_args()

        if misp_client_cert == '':
            misp_client_cert = None
        else:
            misp_client_cert = (misp_client_cert)

        misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=misp_client_cert, debug=True)
        result = misp.search(publish_timestamp=args.last, limit=args.limit, pythonify=False, return_format='stix2')

        print(result)

    cam@qld-gdpt-campbell:[/tmp]: python3 debug.py -l 24h -m 1

### Logs, screenshots, configuration dump, ...
    cam@qld-gdpt-campbell:[/tmp]: python3 debug.py -l 24h -m 1
    INFO [aping.py:68 - __init__() ] To configure logging in your script, leave it to None and use the following: import logging; logging.getLogger('pymisp').setLevel(logging.DEBUG)
    DEBUG [aping.py:2073 - _prepare_request() ] GET - https://SUBSCRIBED-MISP/servers/getPyMISPVersion.json
    DEBUG [aping.py:2075 - _prepare_request() ] {}
    DEBUG [aping.py:2100 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.114 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'MY-API-KEY', 'content-type': 'application/json'}
    DEBUG [aping.py:2047 - _check_response() ] {'version': '2.4.114'}
    DEBUG [aping.py:2073 - _prepare_request() ] GET - https://SUBSCRIBED-MISP/servers/getVersion.json
    DEBUG [aping.py:2075 - _prepare_request() ] {}
    DEBUG [aping.py:2100 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.114 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'MY-API-KEY', 'content-type': 'application/json'}
    DEBUG [aping.py:2047 - _check_response() ] {'version': '2.4.115', 'perm_sync': False}
    DEBUG [aping.py:2073 - _prepare_request() ] GET - https://SUBSCRIBED-MISP/attributes/describeTypes.json
    DEBUG [aping.py:2075 - _prepare_request() ] {}
    DEBUG [aping.py:2100 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.114 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'MY-API-KEY', 'content-type': 'application/json'}
    DEBUG [aping.py:2047 - _check_response() ] {'result': {'sane_defaults': {'md5': {'default_category': 'Payload delivery', 'to_ids': 1}, 'sha1': {'default_category': 'Payload delivery', 'to_ids': 1}, 'sha256': {'default_category': 'Payload delivery', 'to_ids': 1}, 'filename': {'default_category': 'Payload delivery', 'to_ids': 1}, 'pdb': {'default_category': 'Artifacts dropped', 'to_ids': 0}, 'filename|md5': {'default_category': 'Payload delivery', 'to_ids': 1}, 'filename|sha1': {'default_category': 'Payload delivery', 'to_ids': 1}, 'filename|sha256': 

     << TRUNCATED BY CAM >>

     'boolean', 'anonymised']}}}
    DEBUG [aping.py:2073 - _prepare_request() ] POST - https://SUBSCRIBED-MISP/events/restSearch
    DEBUG [aping.py:2075 - _prepare_request() ] {'returnFormat': 'stix2', 'page': None, 'limit': '1', 'value': None, 'type': None, 'category': None, 'org': None, 'tags': None, 'quickFilter': None, 'from': None, 'to': None, 'eventid': None, 'withAttachments': 0, 'metadata': 0, 'uuid': None, 'publish_timestamp': '24h', 'published': None, 'enforceWarninglist': 0, 'deleted': None, 'includeEventUuid': 0, 'sgReferenceOnly': 0, 'eventinfo': None, 'searchall': None, 'requested_attributes': None, 'includeContext': 0, 'headerless': 0, 'includeSightings': 0, 'includeCorrelations': 0}
    DEBUG [aping.py:2100 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.114 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '261', 'Authorization': 'MY-API-KEY', 'content-type': 'application/json'}
    DEBUG [aping.py:2047 - _check_response() ] 0
    Traceback (most recent call last):
      File "debug.py", line 26, in <module>
        result = misp.search(publish_timestamp=args.last, limit=args.limit, pythonify=False, return_format='stix2')
      File "/usr/local/lib/python3.6/site-packages/pymisp/aping.py", line 1488, in search
        if 'errors' in normalized_response:
    TypeError: argument of type 'int' is not iterable

**Comment by chrisr3d** [comment]
I would first recommend to ask the administrator of the server to update PyMISP.
Once it is up-to-date, test again and if it is still broken, raise the error by creating a new issue in PyMISP's repository, or transfer this one there

**Comment by camAtGitHub** [comment]
Do you mean the connecting clients PyMISP (which is PyMISP 2.4.114 - Python 3.6) 
Or actual on the Server running MISP ?

Thanks

**Comment by chrisr3d** [comment]
I guess the one where you got the error message from, when you described the actual behavior

**Comment by chrisr3d** [comment]
If error message is still the same, and PyMISP is up-to-date, then there is any issue with PyMISP that needs to be fixed before trying again
