### ISSUE TITLE
CakeResque bootstrap.php not found

### ISSUE THREAD

**Issue by redbaron4** [MISP/MISP#5176]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | ScientificLinux
| OS version (client)       | 7
| PHP version               | 7.2
| MISP version / git hash   | 2.4.115
| Browser                   | NA

I followed the CentOS install guide to install MISP on a fresh VM running ScientificLinux. The install proceeded smoothly but now I am seeing the following warning in my logs

```
2019-09-17 17:35:24 Warning: Warning (2): include(/var/www/MISP/app/Plugin/CakeResque/Config/bootstrap.php): failed to open stream: No such file or directory in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 286]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 286
CakePlugin::_includeFile() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 286
CakePlugin::bootstrap() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 205
CakePlugin::load() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 124
CakePlugin::loadAll() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 167
include - APP/Config/bootstrap.php, line 169
Configure::bootstrap() - APP/Lib/cakephp/lib/Cake/Core/Configure.php, line 98
include - APP/Lib/cakephp/lib/Cake/bootstrap.php, line 432
[main] - APP/webroot/index.php, line 81

2019-09-17 17:35:24 Warning: Warning (2): include() [<a href='http://php.net/function.include'>function.include</a>]: Failed opening '/var/www/MISP/app/Plugin/CakeResque/Config/bootstrap.php' for inclusion (include_path='/var/www/MISP/app/Vendor/pear/pear_exception:/var/www/MISP/app/Vendor/pear/console_commandline:/var/www/MISP/app/Vendor/pear/crypt_gpg:.:/opt/rh/rh-php72/root/usr/share/pear:/opt/rh/rh-php72/root/usr/share/php') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 286]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 286
CakePlugin::_includeFile() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 286
CakePlugin::bootstrap() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 205
CakePlugin::load() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 124
CakePlugin::loadAll() - APP/Lib/cakephp/lib/Cake/Core/CakePlugin.php, line 167
include - APP/Config/bootstrap.php, line 169
Configure::bootstrap() - APP/Lib/cakephp/lib/Cake/Core/Configure.php, line 98
include - APP/Lib/cakephp/lib/Cake/bootstrap.php, line 432
[main] - APP/webroot/index.php, line 81

```
My Plugin directiry looks like

```
# ll /var/www/MISP/app/Plugin/CakeResque/
total 48
-rwxr-x---. 1 apache apache 9042 Jul 12  2015 CHANGELOG.md
-rwxr-x---. 1 apache apache 1029 Jul 12  2015 composer.json
drwxr-x---. 2 apache apache 4096 Sep 17 17:03 config
-rwxr-x---. 1 apache apache 1737 Jul 12  2015 CONTRIBUTING.md
-rwxr-x---. 1 apache apache 1076 Jul 12  2015 Gruntfile.js
-rwxr-x---. 1 apache apache 1091 Jul 12  2015 LICENSE.txt
-rwxr-x---. 1 apache apache  777 Jul 12  2015 package.json
-rwxr-x---. 1 apache apache 1006 Jul 12  2015 README.md
drwxr-x---. 5 apache apache 4096 Sep 17 16:54 src
drwxr-x---. 4 apache apache 4096 Jul 12  2015 tests

```

For some reason I don't have a `Config` directory but a `config` directory. Any pointers?

**Comment by redbaron4** [comment]
To update, I created the `Config` directory myself and copied the `config` contents into it. Now I get the error

```
2019-09-18 15:10:49 Error: [Error] Class 'Cake\Core\Configure' not found
Stack Trace:
#0 /var/www/MISP/app/Plugin/CakeResque/src/CakeResque.php(78): CakeResque\CakeResque::loadConfig(NULL)
#1 /var/www/MISP/app/Plugin/CakeResque/Config/bootstrap.php(23): CakeResque\CakeResque::init()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php(286): include('/var/www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php(205): CakePlugin::_includeFile('/var/www/MISP/a...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php(124): CakePlugin::bootstrap('CakeResque')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php(167): CakePlugin::load('CakeResque', Array)
#6 /var/www/MISP/app/Config/bootstrap.php(169): CakePlugin::loadAll(Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap(true)
#9 /var/www/MISP/app/webroot/index.php(81): include('/var/www/MISP/a...')
#10 {main}

```

It looks like a namespace error but I can't figure out what is wrong.

I tried to fiddle around with `autoload.php` (wrong I know but still...) and added manually the path to `Cake\Core` in the autoload script. Now I get the error

```
2019-09-18 15:27:34 Error: Fatal Error (1): Cannot declare class Configure, because the name is already in use in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php, line 35]
2019-09-18 15:27:34 Error: [InternalErrorException] Internal Server Error
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Cannot declare ...', '/var/www/MISP/a...', 35)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Cannot declare ...', '/var/www/MISP/a...', 35, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

```

Apparently CakeResque can't find the namespace `Cake\Core\Configure` and If I explicilty add the namespace, I get an error about namespace being in use. Any pointers will be much appreciated.

**Comment by redbaron4** [comment]
I was installing MISP in an offline environment and bundled the wrong Cake-Resque version. Bundling the correct version fixed my problem.
