### ISSUE TITLE
Statistics -> Galaxy Matrix fails when choosing other Organisation than all (DB error)

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#5179]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 9
| OS version (client)       | Windows 10
| PHP version               | 7.3
| MISP version / git hash   | v2.4.116 (e8900b425d71eca25845a6f7de8a13b1cf8ee589)
| Browser                   | Chrome

### Expected behavior
Being able to choose specific organisations to get Galaxy Matrix

### Actual behavior
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

```
2019-09-17 17:46:33 Error: [PDOException] SQLSTATE[HY000]: General error: 1712 Index attribute_tags is corrupted
Request URL: /users/statistics/galaxyMatrix/galaxy_id:32/organisation:2
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany(Object(Attribute), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1411): DboSource->queryAssociation(Object(Attribute), Object(AttributeTag), 'hasMany', 'AttributeTag', Array, Array, true, Array, 1, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(Event), Object(Attribute), 'hasMany', 'Attribute', Array, Array, true, Array, 2, Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Event), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#9 /var/www/MISP/app/Model/Event.php(2092): Model->find('all', Array)
#10 /var/www/MISP/app/Model/Event.php(6764): Event->fetchEvent(Array, Array, true)
#11 /var/www/MISP/app/Controller/UsersController.php(1923): Event->restSearch(Array, 'attack', Array, false, false, 493, 'attack_view')
#12 /var/www/MISP/app/Controller/UsersController.php(1568): UsersController->__statisticsGalaxyMatrix(Array)
#13 [internal function]: UsersController->statistics('galaxyMatrix')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#17 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}
```

### Steps to reproduce the behavior
Click "Global Actions" -> "Statistics" -> "Galaxy Matrix"

If any other organisation than "all" the error occours.

**Comment by iglocska** [comment]
General error: 1712 Index attribute_tags is corrupted


This doesn't sound good at all......

**Comment by eCrimeLabs** [comment]
It seems to have started after doing mass attribute addition on an event and deleting them. At some point the event was giving errors :)

I can share the script privatly if interested

**Comment by eCrimeLabs** [comment]
This seems to be a single instance issue

**Comment by iglocska** [comment]
very curious, it sounds like a corruption of your DB though :( Reindexing the field should solve it.
