### ISSUE TITLE
Unknown column 'Taxonomy.required' in 'where clause'

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#5350]
Similar to: #4560 
Cause: Partial DB Update
Cause of Cause: www-dir had wrong permissions, possibly breaking the GUI update

ToDo: Properly docuemnt how to re-roll a DB update.

```2019-10-22 05:00:29 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Taxonomy.required' in 'where clause'
Request URL: /events/view/1355
Stack Trace:
#0 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Taxonom...', Array)
#2 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Taxonom...', Array, Array)
#3 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Taxonom...', Array)
#4 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Taxonomy), Array)
#5 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('list', Array)
#6 /var/www/MISPkappa/app/Model/Event.php(6909): Model->find('list', Array)
#7 /var/www/MISPkappa/app/Controller/EventsController.php(1521): Event->getRequiredTaxonomies()
#8 /var/www/MISPkappa/app/Controller/EventsController.php(1651): EventsController->__viewUI(Array, false, NULL)
#9 [internal function]: EventsController->view('1355')
#10 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISPkappa/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISPkappa/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

**Comment by iglocska** [comment]
Could you try cleaning the cache to see if it's not that causing the issue? That would be explained by fine permission issues

**Comment by SteveClement** [comment]
@iglocska nah, that did nothing.

I will now pull to the latest version and see how that goes.

Worst case I will roll-back to a previous db version and re-run the upgrade scripts and hope for the best.

**Comment by iglocska** [comment]
Yeah that should solve it, but very curious how you ended up in this
situation in the first place. They only times i run into issues like this
is with dev instances when checking out other branches / prs with
mismatched update script revisions.
