### ISSUE TITLE
Random blackholing when adding attributes

### ISSUE THREAD

**Issue by marcnil815** [MISP/MISP#5398]
Adding an attributes on .118 throws an Error concerning blackholing.
*If you would like to report a bug, please fill the template bellow

Relates to #4406 
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.1 LTS
| OS version (client)       | macOS Catalina (10.15.1)
| PHP version               | 7.2.24-0ubuntu0.18.04.1 
| MISP version / git hash   | 2.4.118
| Browser                   | Safari 13.0.3 (15608.3.10.1.4).
| Other | MISP instance is behind a AWS ALB, leveraging the MISP CustomAuth module

### Expected behavior
Adding an attributes add attribute to event.

### Actual behavior
MISP throws a blackhole error.
Following has been tried:
Restarting MISP app: negative
Cleaning cache: negative

Everyting else seems to work. Adding events, tagging, galaxies, etc.. Only attributes ( attribute tyoe doesn't matter).

On FireFox (70.0.1 (64-bit)) it also happens, but less frequent.

The instance is behind an AWS ALB using the CustomAuth module, however, this error cropped up _just_ after the upgrade to 118.

### Steps to reproduce the behavior
Create event. Add attribute.
Random between several instances of the exact same build and versions above.

### Logs, screenshots, configuration dump, ...
2019-11-14 14:02:50 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/add/125
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(AttributesController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(AttributesController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

**Comment by marcnil815** [comment]
Hmm...it seems using the side menu "Add Attribute" does not exhibit this behaviour.

**Comment by neok0** [comment]
Had a similar issue with using the CustomAuth header. The issue was that the custom auth method refreshes the session under some circumstances which invalids all existing form tokens. This leads to a CSRF exception. 
Using the "Add Attribute" menu generates new forms using new and valid form tokens, and therefore probably works.

**Comment by iglocska** [comment]
Oooh. Will look into that!

**Comment by marcnil815** [comment]
Ah. Nice find.

Thanks for looking into it. @iglocska 
The workaround would be to disable CSRF and take the risk. Only viable in an isolated environment with trusted users and only limited read-only API access.

Oh and yes. The CustomAuth reauthenticates constantly according to the logs.

**Comment by marcnil815** [comment]
Hi
Any updates on this?
The workaround would be to disable CSRF in SecurityComponent.php which is not optimal :)

Br
Marc

**Comment by shirley815** [comment]
> Ah. Nice find.
> 
> Thanks for looking into it. @iglocska The workaround would be to disable CSRF and take the risk. Only viable in an isolated environment with trusted users and only limited read-only API access.
> 
> Oh and yes. The CustomAuth reauthenticates constantly according to the logs.

Could I ask how to disable CSRF, please?

**Comment by marcnil815** [comment]
It's in the settings (cannot remember where), top row.

**Comment by marcnil815** [comment]
@iglocska is there any traction on this particular CSRF issues with CustomAuth?
