### ISSUE TITLE
ForbiddenException on deletion of attribute(s)

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#5431]
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4 master

### Expected behavior
Deletion of attributes should succeed as user that is allowed to manage organizations attributes.

### Actual behavior
It does not work, no UI error message displayed.

### Steps to reproduce the behavior
Try to delete an attribute using either the icon on the right or the selection mechanism.

### Logs, screenshots, configuration dump, ...
```
2019-11-27 14:37:34 Error: [ForbiddenException] You do not have permission to do that.
Request URL: /attributes/deleteSelected/33058
Stack Trace:
#0 /var/www/MISP/app/Controller/AttributesController.php(1388): Attribute->deleteAttribute('4530516', Array, false)
#1 [internal function]: AttributesController->deleteSelected('33058')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
```

**Comment by 3c7** [comment]
Works as admin, but not as the user which created the attribute.

**Comment by 3c7** [comment]
Can not reproduce the issue after pulling from 2.4 again, so it's probably solved already. :)
