### ISSUE TITLE
Sync servers failed : Event cannot be created as you are not a member of the creator organisation

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#5509]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.0.4
| OS version (client)       | Ubuntu 18.0.4
| PHP version               | 7.2
| MISP version / git hash   | 2.4.119
| Browser                   | 

### Expected behavior
Sync (pull events) from command line as schedule job

### Actual behavior
When I execute  `sudo -u www-data  app/Console/cake Server pull 2 1 full` the console returns error messages and the new events are **not** pulled.

```
Error: Event cannot be created as you are not a member of the creator organisation.
#0 /var/www/MISP/app/Model/Server.php(2343): Event->_add(Array, true, Array, '1', '1', true, '42')
#1 /var/www/MISP/app/Model/Server.php(2380): Server->__checkIfPulledEventExistsAndAddOrUpdate(Array, '5e1e1bef-0df8-4...', Array, Array, Object(Event), Array, Array, '42')
#2 /var/www/MISP/app/Model/Server.php(2488): Server->__pullEvent('5e1e1bef-0df8-4...', Array, Array, Object(Event), Array, Array, '42')
#3 /var/www/MISP/app/Console/Command/ServerShell.php(66): Server->pull(Array, '1', 'full', Array, '42')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('pull', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
```

These errors are preceded with a number of warnings

```

Welcome to CakePHP v2.10.19 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Notice Error: Undefined index: Organisation in [/var/www/MISP/app/Console/Command/ServerShell.php, line 58]

2020-01-14 19:59:43 Notice: Undefined index: Organisation in [/var/www/MISP/app/Console/Command/ServerShell.php, line 58]
Notice Error: Undefined index: id in [/var/www/MISP/app/Model/Server.php, line 2307]

2020-01-14 19:59:43 Notice: Undefined index: id in [/var/www/MISP/app/Model/Server.php, line 2307]
Notice Error: Undefined index: org_id in [/var/www/MISP/app/Model/Event.php, line 3655]

2020-01-14 19:59:43 Notice: Undefined index: org_id in [/var/www/MISP/app/Model/Event.php, line 3655]
Notice Error: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3656]

2020-01-14 19:59:43 Notice: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3656]
Notice Error: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3656]

2020-01-14 19:59:43 Notice: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3656]
Notice Error: Undefined index: id in [/var/www/MISP/app/Model/Server.php, line 2307]

2020-01-14 19:59:44 Notice: Undefined index: id in [/var/www/MISP/app/Model/Server.php, line 2307]
Notice Error: Undefined index: id in [/var/www/MISP/app/Model/Event.php, line 3334]

2020-01-14 19:59:44 Notice: Undefined index: id in [/var/www/MISP/app/Model/Event.php, line 3334]
Notice Error: Undefined index: Organisation in [/var/www/MISP/app/Model/Event.php, line 3351]

2020-01-14 19:59:44 Notice: Undefined index: Organisation in [/var/www/MISP/app/Model/Event.php, line 3351]
Notice Error: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3351]

2020-01-14 19:59:44 Notice: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3351]
Notice Error: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3351]

2020-01-14 19:59:44 Notice: Undefined index: Role in [/var/www/MISP/app/Model/Event.php, line 3351]

```

Only debug.log contains error messages afterwards

```
==> debug.log <==
2020-01-14 20:04:33 Notice: Undefined index: Organisation in [/var/www/MISP/app/Console/Command/ServerShell.php, line 58]
2020-01-14 20:04:34 Notice: Undefined index: Organisation in [/var/www/MISP/app/Model/Server.php, line 2530]
2020-01-14 20:04:34 Notice: Undefined index: email in [/var/www/MISP/app/Model/Server.php, line 2533]
2020-01-14 20:04:34 Notice: Undefined index: id in [/var/www/MISP/app/Model/Server.php, line 2535]

```

### Steps to reproduce the behavior
As per behavior

**Comment by mokaddem** [comment]
Looking at the first error, it seems that the user cannot be fetched.
I added a test (4100af2a301d832ec6964d3cbafadd91a308367e) in the console script to prevent execution whenever the user corresponding to the provided user_id does not exists.
Hopefully, it will narrow down your issue.

**Comment by racco42** [comment]
In my case, this error was caused by removal of "admin" rights from the user account who created the sync configuration. Once the privileges were returned, is started to work. So I assume that the sync config has "owner" user (and it is not visible in GUI) and that user have to have sync privileges.
