### ISSUE TITLE
Problem installing MISP

### ISSUE THREAD

**Issue by shoron-dutta** [MISP/MISP#5516]
I'm installing MISP core on Ubuntu 18.04 using the commands:

wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c

during installation I came across the following:

_pymisp.exceptions.NoKey: Please provide your authorization key_

Nevertheless, it was installed but there is no access URL. The message is:

_MISP Installed, access here: ""_

**Comment by mokaddem** [comment]
Thanks for opening an issue.
I'm not sure to understand correctly. Is you installation successful or not?

**Comment by SteveClement** [comment]
@shoron-dutta the pymisp exception might be ok.

If you browse to "localhost" does it have a MISP login?

**Comment by shoron-dutta** [comment]
Hi,
My host system is Windows 10. Previously I tried installing in Windows Sub-system for Linux. Then I found these [instructions.](https://indico.cern.ch/event/595396/contributions/2566371/attachments/1448720/2233045/2017-04-25__MISP_Training_Instructions.pdf)


According to this, I have completed up to step 4. 
But in step 5, after inserting the command "ssh -p 2222 root@localhost", I get an error: "Connect to host localhost port 2222: connection refused"

**Comment by SteveClement** [comment]
@shoron-dutta those instructions are fairly old and not by the MISP-Project, I cannot help you with that.

What you can try, is in your WSL:

```
ifconfig
```

And try to figure out what IP address setup you have there.
You will see that there are all your Network Cards you have under windows too.

Meaning that for example if something is already running on TCP port 443 or 80 the WSL will not be able to use that. AFAIK.

Also, this is not a MISP issue as such.

**Comment by SteveClement** [comment]
closing due to inactivity.

**Comment by utkonos** [comment]
I have run into this same error during install. Here it is:

```
Successfully installed pymisp validators-0.14.2
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 60, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 106, in __init__
    raise NoKey('Please provide your authorization key.')
pymisp.exceptions.NoKey: Please provide your authorization key.

----------------------------------------------------------------------
Ran 0 tests in 0.004s

FAILED (errors=1)
#########################################################################################  (88%)
```

**Comment by utkonos** [comment]
This is using the main installer:

```
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sh
```

Using the method for MISP Core and misp-modules

**Comment by Pilly170** [comment]
I also have this
Ubuntu server 20.04

**Comment by oencarnacion** [comment]
The problem is that the MISP instance and the MYSQL are not establishing a connection. The steps I took to do this were the following:

With the file hosted on the misp user called mysql.txt I used the generated root password I went to my mysql instance and reset the root user by putting the password I saw in the file

How to reset the user:

/etc/init.d/mysql stop
mysqld_safe --skip-grant-tables &
mysql -u root
use mysql;
select PASSWORD("password from mysql.txt");
update user set authentication_string=PASSWORD("password from mysql.txt") where user'root';
update user set plugin = "mysql_native_password" where user='root';
quit;
/etc/init.d/mysql start
