### ISSUE TITLE
Replying or editing post always black-holed

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#555]
When replying to a post or editing an existing post, the black-holed error message is always shown. Adding new posts is not affected. Looks like the CSRF protection is tripped unneeded. Running v2.3.81
```
2015-06-22 10:27:22 Error: [BadRequestException] The request has been black-holed
Request URL: /posts/add/post/72
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(PostsController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(239): SecurityComponent->blackHole(Object(PostsController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(PostsController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by iglocska** [comment]
Thanks for the heads-up, looking into it!

**Comment by iglocska** [comment]
Interesting issue!

I just looked into it, the issue was with certain cakephp versions having a bug in the formhelper - it basically used disabled fields (in the reply / edit view) while creating the hashed token for the form, which it shouldn't have. https://github.com/cakephp/cakephp/issues/5603

Updating cakephp should fix it, but I'll push a patch that will resolve it anyway in a moment (by not creating the disabled fields using the formhelper).

Thanks for reporting the issue!

**Comment by RichieB2B** [comment]
Thanks for looking into this. I just checked and we are running CakePHP 2.6.7 (from May 2015) which should be recent enough.
