### ISSUE TITLE
ERROR: test_first_last_seen on Ubuntu 18.04 Install

### ISSUE THREAD

**Issue by mlab12** [MISP/MISP#5575]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (client)       | Ubuntu 18.04
| MISP version / git hash   | 2.4.120

### Expected behavior
Installer completes with no errors

### Actual behavior
test_first_last_seen fails

### Steps to reproduce the behavior
Followed the installation instructions for MISP core on Ubuntu 18.04:
```
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c
```
I can still access the web GUI after the installation completes.

### Logs, screenshots, configuration dump, ...
```
................E...........{
  "type": "bundle",
  "spec_version": "2.0",
  "id": "bundle--5e3357d4-9380-4bae-93a6-1d89c0a8010f",
  "objects": [
    {
      "type": "identity",
      "id": "identity--5e335787-b8d0-4697-8a94-1771c0a8010f",
      "name": "blah",
      "identity_class": "organization",
      "created": "2020-01-30T22:25:25.023Z",
      "modified": "2020-01-30T22:25:25.023Z"
    },
    {
      "type": "report",
      "id": "report--5e3357d3-9798-47fa-8002-1771c0a8010f",
      "name": "This is a super simple test",
      "created_by_ref": "identity--5e335787-b8d0-4697-8a94-1771c0a8010f",
      "created": "2020-01-30T00:00:00.000Z",
      "published": "1970-01-01T00:00:00Z",
      "labels": [
        "Threat-Report",
        "misp:tool=\"misp2stix2\""
      ],
      "object_refs": [
        "x-misp-object-text--e91bcf51-e4bf-413b-8690-5293f93536f8",
        "indicator--4d2b37ea-eb4a-4588-8867-6deeeec3d74f"
      ],
      "modified": "2020-01-30T22:25:25.041Z"
    },
    {
      "id": "x-misp-object-text--e91bcf51-e4bf-413b-8690-5293f93536f8",
      "x_misp_category": "Other",
      "labels": [
        "misp:type=\"text\"",
        "misp:category=\"Other\"",
        "misp:to_ids=\"False\""
      ],
      "x_misp_timestamp": "2020-01-30 22:25:23",
      "x_misp_value": "e1d664f4-8fc5-4454-988e-5a73e86e5bc9",
      "created_by_ref": "identity--5e335787-b8d0-4697-8a94-1771c0a8010f",
      "type": "x-misp-object-text",
      "created": "2020-01-30T22:25:25.023Z",
      "modified": "2020-01-30T22:25:25.023Z"
    },
    {
      "id": "indicator--4d2b37ea-eb4a-4588-8867-6deeeec3d74f",
      "type": "indicator",
      "labels": [
        "misp:type=\"ip-src\"",
        "misp:category=\"Network activity\"",
        "misp:to_ids=\"True\""
      ],
      "kill_chain_phases": [
        {
          "kill_chain_name": "misp-category",
          "phase_name": "Network activity"
        }
      ],
      "valid_from": "2020-01-30T00:00:00Z",
      "created_by_ref": "identity--5e335787-b8d0-4697-8a94-1771c0a8010f",
      "pattern": "[network-traffic:src_ref.type = 'ipv4-addr' AND network-traffic:src_ref.value = '8.8.8.8']",
      "created": "2020-01-30T22:25:25.024Z",
      "modified": "2020-01-30T22:25:25.024Z"
    }
  ]
}
..............................
======================================================================
ERROR: test_first_last_seen (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 430, in from_dict
    self.last_seen = datetime.strptime(ls, "%Y-%m-%dT%H:%M:%S.%f%z")
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-01-04T12:30:34.323242+8:00' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 2085, in test_first_last_seen
    event.add_attribute('ip-dst', '8.8.8.8', first_seen='2020-01-04', last_seen='2020-01-04T12:30:34.323242+8:00')
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1332, in add_attribute
    attribute.from_dict(type=type, value=value, **kwargs)
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 433, in from_dict
    self.last_seen = ls
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 223, in __setattr__
    raise PyMISPError('last_seen ({value}) has to be after first_seen ({self.first_seen})')
pymisp.exceptions.PyMISPError: last_seen ({value}) has to be after first_seen ({self.first_seen})

----------------------------------------------------------------------
Ran 58 tests in 116.307s

FAILED (errors=1)
#################################################################################################  (96%)

```

**Comment by mokaddem** [comment]
Thanks for the report.
PR https://github.com/MISP/PyMISP/pull/534 should fix the error
