### ISSUE TITLE
Send credentials from /admin/user/view/ is always blackholed

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#565]
Using the Administration -> Contact Users page does work.
```
2015-07-09 16:17:18 Error: [BadRequestException] The request has been black-holed
Request URL: /users/initiatePasswordReset/55/true
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(239): SecurityComponent->blackHole(Object(UsersController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(UsersController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by iglocska** [comment]
Looking into it!

**Comment by iglocska** [comment]
Hmm weird, I am not able to reproduce the issue... Which version are you on?

**Comment by RichieB2B** [comment]
This was on version 2.3.92 and 2.3.95. I just tried to reproduce it on 2.3.96, and now the reset works just fine. Very strange. I'll reopen this if I see it again.

**Comment by iglocska** [comment]
Great, let me know if it resurfaces!

**Comment by RichieB2B** [comment]
This morning the issue was back. Upgrading to 2.3.107 did not help.
```
2015-08-18 09:11:29 Error: [BadRequestException] The request has been black-holed
Request URL: /users/initiatePasswordReset/56/true
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(239): SecurityComponent->blackHole(Object(UsersController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(UsersController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by iglocska** [comment]
Hmm that is odd, will have a look!
