### ISSUE TITLE
STIX2 file import -- failed

### ISSUE THREAD

**Issue by Sp-TT** [MISP/MISP#5656]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat7
| OS version (client)       | Win10
| PHP version               | 7.2.10
| MISP version / git hash   |  v2.4.121 (413399611ed41665edab24422bdb1fdead5286be) 
| Browser                   | Firefox

### Support Questions
Try to import a STIX2 format feed to MISP via "import from ..." function. 
Get the following error in exec-errors.log

Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 99, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/properties.py", line 192, in clean
    valid = self.contained.clean(item)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/properties.py", line 696, in clean
    parsed_obj = parse(dictified, allow_custom=self.allow_custom, interoperability=self.interoperability)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/core.py", line 73, in parse
    obj = dict_to_stix2(obj, allow_custom, interoperability, version)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/core.py", line 140, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, interoperability=interoperability, **stix_dict)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/core.py", line 27, in __init__
    super(STIXDomainObject, self).__init__(*args, **kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 198, in __init__
    self._check_object_constraints()
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/v20/sdo.py", line 142, in _check_object_constraints
    errors = run_validator(self.get('pattern'), '2.0')
TypeError: run_validator() takes 1 positional argument but 2 were given

stix2 python lib was updated. Please give a hand for this issue. 
Thanks for support.

**Comment by Sp-TT** [comment]
problem solved. stix2patterns is not updated. 

I am following this https://misp.github.io/MISP/UPDATE/ for my update. 
Not sure where did i miss stix2patterns update?

Thank you for any advise for this, it will help for my next update.
