### ISSUE TITLE
The "MISP.unpublishedprivate" setting does not always makes an exception for site admin

### ISSUE THREAD

**Issue by obert01** [MISP/MISP#5666]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | v2.4.122 (5bef9d03a95517f90b11e6a488a7fee1f9335f3c) 

### Expected behavior
The site administrator should be able to fetch/edit/delete attributes, even if an event is unpublished, wheither it belongs to him or not. 

### Actual behavior
I have found this bug with the following precise case. Let's suppose the following simple request:
```
curl -X POST -o - --header "Authorization: XXX" --header "Accept: application/json" --header "Content-Type: application/json"  \
-d '{"Attribute": {"category": "External analysis", "type": "comment", "value": "test"}}' \
https://misp.cert-ist.com/attributes/edit/2583141
```
The first /attributes/edit works, when the event is published I suppose. If I try another similar edit attribute request, I obtain the following error:
```
{
    "name": "Invalid attribute",
    "message": "Invalid attribute",
    "url": "\/attributes\/edit\/2583141"
}
```
And the log shows:
```
2020-02-26 22:32:20 Error: [MethodNotAllowedException] Invalid attribute
Request URL: /attributes/edit/2583141
Stack Trace:
#0 [internal function]: AttributesController->edit('2583141')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

I must precise that I'm performing requests with the "site admin" role, since the goal is eventually to enrich or correct existing attributes (I know, it's not exactly the philosophy of MISP). 
Note that adding a new attributes works perfectly Only fetching, editing and deleting fails, as far as I am concerned. I have the impression that this is the Attribute::fetchAttributes(...) function which causes the issue. 

### Steps to reproduce the behavior
1. Set "MISP.unpublishedprivate" to "true" and be sure to make request with the "site admin" role". 
2. Create and publish an event with a few attributes
3. Using the API, edit an attribute. 
4. Using the API, edit another attribute. This should fail.

**Comment by iglocska** [comment]
Nice catch, indeed site admins should not follow any such restrictions.
