### ISSUE TITLE
Why get black-holed REST Client WebUI when external auth is enabled

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5681]
2.4.121

When we enable external authentication for users, which now is working well with our SSO system, the WebUI `REST client` page yields the `black-holed` error when submitted. This is true when setting the HTTP `Authorization` header to the user's `authkey` or `external_auth_key`.

Any idea on how to troubleshoot why this is occuring is appreciated.

Thanks.

p.s. @Rafiot and @iglocska I did email you more details that we cannot here for security reasons.

**Comment by github-germ** [comment]
All I do is select the `Events > index` template. No change to HTTP headers (I've tried it with both my user `authkey` and `external_auth_key`); and set the `Body` to `{}` --> **black-holed**.

Please let me know what else to try or look for to diagnose and fix.

@Rafiot + @iglocska -- more details in email. THANKS!

**Comment by github-germ** [comment]
Did you need anything else for me on this issue? We are still on 2.4.121 -- if it was fixed in 2.4.124, let me know. THANKS!!

**Comment by chrisinmtown** [comment]
I suggest treating this as a request to improve the robustness of the in-webapp REST client feature and/or the clarity of the error message it reports.

I tested the REST feature on MISP version 2.4.131, which in our lab uses an external SSO feature.  The result is internal error, not "blackhole" anymore:
```
    An Internal Error Has Occurred.
    Error: An Internal Error Has Occurred.
```
Here's the full detail from error.log
```
2020-10-05 14:42:30 Error: [SocketException] Connection refused
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('POST /events/in...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(2031): HttpSocket->post('https://misp-de...', '{\r\n    "all": "...', Array)
#4 /var/www/MISP/app/Controller/ServersController.php(1930): ServersController->__doRestQuery(Array, 'curl \\\n -d '{"a...', 'misp_url = 'htt...')
#5 [internal function]: ServersController->rest()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2020-10-05 14:42:30 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(111)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(SocketException))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
2020-10-05 14:42:30 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2020-10-05 14:42:30 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```
We seem to have some network configuration issues that prevent the server from talking to itself.  Those issues are our problem (not the MISP team).  Still, it would be enormously helpful if the error sent to the log were more explicit about what connection was tried, what failed, etc.

**Comment by github-germ** [comment]
In prior releases (e.g. just tried it again on 2.4.125), the error did state:
```
The request has been black-holed
Error: The requested address '/servers/rest' was not found on this server.
```
However, now on 2.4.131, the current error seen is likely a local network config condition as per the `error.log` excerpt shown. Hence `internal error` is OK, but it would be nice if it was possible to state more details.

**Comment by github-germ** [comment]
Now on 2.4.143 WebUI submitting `rest/search` hits CSRF error:
```
You have tripped the cross-site request forgery protection of MISP
CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed.

Alternatively, click here to continue to the start page.
```
Related? https://github.com/MISP/MISP/issues/6940
