### ISSUE TITLE
Enrichment error: Cannot save log because of validation errors

### ISSUE THREAD

**Issue by smclinden** [MISP/MISP#5710]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | All
| PHP version               | 7.2
| MISP version / git hash   | v2.4.123 (55bcc4fa470af0bd24db0128e3b2cf3919af1c7e) 
| Browser                   | All

### Support Questions
I have enabled the Crowdstrike enrichment and obtained credentials from CS Customer Support and verified that they work using CURL from the MISP server platform. But when I queue the Enrichment I get an error (below).

I've checked the configuration and it appears to be correct so I am at a loss as to how to debug this issue.

### Logs, screenshots, configuration dump, ...

main.ERROR: {"queue":"prio","id":"58bbb09ffd0c766baaac321b8a6f98bb","class":"EventShell","args":[["enrichment","2","1392","[\"crowdstrike_falcon\"]","1481"]]} fai\
led: Cannot save log because of validation errors: {"action":["Options : ..."]} {"type":"fail","log":"Cannot save log because of validation errors: {\"action\":[\"Options : ...\"]}","j\

**Comment by smclinden** [comment]
Some additional info. In debug mode, I get the errors, below, using CURL.

My question is, does the authentication information need to be passed in the CURL string or will this information be read from the MISP database? None of the examples in the MISP Modules documentation that I have found deals with authentication information so do I need to pass the ['config'] info in the JSON?

ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
 File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 201, in post
  response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
 File "/var/www/MISP/venv/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
  value = future.result()
 File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 189, in run_request
  response = mhandlers[x['module']].handler(q=jsonpayload)
 File "/var/www/MISP/venv/lib/python3.6/site- 
  packages/misp_modules/modules/expansion/crowdstrike_falcon.py", line 47, in handler
   client = CSIntelAPI(request['config']['api_id'], request['config']['apikey'])
 KeyError: 'config'
