### ISSUE TITLE
Synchronization job doesn't work (Queued) -- SQL error (Incorrect integer value: '' for column 'deleted' at row 1)

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#5714]
Hello MISP dev team,

I'm facing an issue when I launch (via Web interface or via CLI) a synchronisation job (example pull):

* via the web interface: the job is `queued` (forever)
* and via CLI, I obtain the following SQL error:

```
/var/www/MISP/app/Console/Command$ ../cake server pull 2 3 full

Welcome to CakePHP v2.10.19 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'deleted' at row 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('UPDATE `misp`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute('UPDATE `misp`.`...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update(Object(ObjectReference), '`id` = 187, `uu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/ObjectReference.php(195): Model->save(Array)
#6 /var/www/MISP/app/Model/Event.php(3763): ObjectReference->captureReference(Array, '9708', Array, Object(Log))
#7 /var/www/MISP/app/Model/Server.php(2392): Event->_edit(Array, Array, '9708', '176601', '3')
#8 /var/www/MISP/app/Model/Server.php(2419): Server->__checkIfPulledEventExistsAndAddOrUpdate(Array, '5a329d19-03e0-4...', Array, Array, Object(Event), Array, Array, '176601')
#9 /var/www/MISP/app/Model/Server.php(2527): Server->__pullEvent('5a329d19-03e0-4...', Array, Array, Object(Event), Array, Array, '176601')
#10 /var/www/MISP/app/Console/Command/ServerShell.php(74): Server->pull(Array, '3', 'full', Array, '176601')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('pull', Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#15 {main}
```

```
../cake server pull 2 3 full
Welcome to CakePHP v2.10.19 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'deleted' at row 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(ObjectReference), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/ObjectReference.php(262): Model->save(Array)
#6 /var/www/MISP/app/Model/Event.php(3763): ObjectReference->captureReference(Array, '9711', Array, Object(Log))
#7 /var/www/MISP/app/Model/Server.php(2392): Event->_edit(Array, Array, '9711', '176602', '3')
#8 /var/www/MISP/app/Model/Server.php(2419): Server->__checkIfPulledEventExistsAndAddOrUpdate(Array, '5a339ef9-a768-4...', Array, Array, Object(Event), Array, Array, '176602')
#9 /var/www/MISP/app/Model/Server.php(2527): Server->__pullEvent('5a339ef9-a768-4...', Array, Array, Object(Event), Array, Array, '176602')
#10 /var/www/MISP/app/Console/Command/ServerShell.php(74): Server->pull(Array, '3', 'full', Array, '176602')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('pull', Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#15 {main}
```

I started to dig in MISP PHP code and the error appears to be located when an object reference is created (file: https://github.com/MISP/MISP/blob/2.4/app/Model/ObjectReference.php#L254). The field `deleted` of the object reference appears to not be correctly set. 

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.123 (commit: fa0eb43120ebd74518d19450a2068bf895824509)

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | all
| MISP version / git hash   | 2.4.123, fa0eb43120ebd74518d19450a2068bf895824509
| Browser                   | Chrome, Firefox, all

### Expected behavior

Synchronisation job should be launched

### Actual behavior

Synchronisation job doesn't work (Queued) -- SQL error (`Incorrect integer value: '' for column 'deleted' at row 1`)

### Logs, screenshots, configuration dump, ...

![Screenshot-sync-job-queued](https://user-images.githubusercontent.com/9305238/77345676-41a13680-6d35-11ea-8a39-e0b74b1d338b.png)

**Comment by devnull-** [comment]
Hello MISP dev team,

This issue appears to be fixed (tested with commit 1604096a26deec72ddefcd8df29d44b473d463b4). I also updated the `DB_schema` with the SQL command : <pre>ALTER TABLE `object_references` MODIFY COLUMN `deleted` tinyint(1) DEFAULT "0" NOT NULL ;
Query OK, 0 rows affected (0.20 sec)
Records: 0  Duplicates: 0  Warnings: 0</pre>

(command proposed in the section `Schema status` on the diagnostics web-page: https://XXX.com/servers/serverSettings/diagnostics

Don't hesitate to contact me if you need some help and if you have some question.

devnull-
