### ISSUE TITLE
PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Role.enforce_rate_limit' in 'field list'

### ISSUE THREAD

**Issue by adthomson** [MISP/MISP#5810]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu,
| OS version (client)       | MacOS,
| PHP version               | 7.1
| MISP version / git hash   | MISP 2.4.123 
| Browser                   | Chrome

### Support Questions
Hi All, 

After my instance ran out of disk space I can no longer access the system. I can authenticate to the system but can't navigate to any of the pages without getting An Internal Error Has Occurred.

Looking at the error log, I'm seeing the following: Unknown column 'Role.enforce_rate_limit' in 'field list'. Based on cases I've read about I've tried deleting the cache files but that hasn't provided any luck by running the following commands:
#sudo rm -f /var/www/MISP/app/tmp/cache/persistent/myapp*
sudo rm -f /var/www/MISP/app/tmp/cache/models/myapp*

Any ideas? 

### Logs, screenshots, configuration dump, 
`2020-04-23 14:56:32 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Role.enforce_rate_limit' in 'field list'
Request URL: /users/change_pw
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(User), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1636): Model->find('first', Array)
#7 /var/www/MISP/app/Controller/UsersController.php(312): Model->read(NULL, '1')
#8 [internal function]: UsersController->change_pw()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}`

![Screenshot 2020-04-23 at 15 22 02](https://user-images.githubusercontent.com/6068150/80110190-506a4b80-8576-11ea-875b-bff8de9f6038.png)

**Comment by adthomson** [comment]
Ah by pulling down the latest release from Git seemed to resolve the issue. 

cd /var/www/MISP/
sudo -u apache git pull origin 2.4
sudo -u apache git submodule update --init --recursive
