### ISSUE TITLE
test: background workers for php-nightly probably doesn't work

### ISSUE THREAD

**Issue by JakubOnderka** [MISP/MISP#5825]
But it looks like problem in old CakePHP and invalid `implode` call, that is fatal error in new PHP version.

Output from Travis log:
```
$ app/Console/worker/start.sh &
$ sleep 10
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Error:</...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Error:</...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(59): ConsoleOutput->write('<error>Error:</...')
#5 [internal function]: ConsoleErrorHandler->handleException(Object(TypeError))
#6 {main}
  thrown in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Fatal Er...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Fatal Er...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(84): ConsoleOutput->write('<error>Fatal Er...')
#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(1, 'Uncaught TypeEr...', '/home/travis/bu...', 268, Array)
#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/Ap in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
Creating workers
Starting worker ... Done
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Error:</...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Error:</...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(59): ConsoleOutput->write('<error>Error:</...')
#5 [internal function]: ConsoleErrorHandler->handleException(Object(TypeError))
#6 {main}
  thrown in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Fatal Er...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Fatal Er...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(84): ConsoleOutput->write('<error>Fatal Er...')
#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(1, 'Uncaught TypeEr...', '/home/travis/bu...', 268, Array)
#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/Ap in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
Creating workers
Starting worker ... Done
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Error:</...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Error:</...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(59): ConsoleOutput->write('<error>Error:</...')
#5 [internal function]: ConsoleErrorHandler->handleException(Object(TypeError))
#6 {main}
  thrown in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Fatal Er...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Fatal Er...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(84): ConsoleOutput->write('<error>Fatal Er...')
#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(1, 'Uncaught TypeEr...', '/home/travis/bu...', 268, Array)
#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/Ap in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
Creating workers
Starting worker ... Done
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Error:</...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Error:</...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(59): ConsoleOutput->write('<error>Error:</...')
#5 [internal function]: ConsoleErrorHandler->handleException(Object(TypeError))
#6 {main}
  thrown in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Fatal Er...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Fatal Er...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(84): ConsoleOutput->write('<error>Fatal Er...')
#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(1, 'Uncaught TypeEr...', '/home/travis/bu...', 268, Array)
#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/Ap in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
Creating workers
Starting worker ... Done
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Error:</...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Error:</...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(59): ConsoleOutput->write('<error>Error:</...')
#5 [internal function]: ConsoleErrorHandler->handleException(Object(TypeError))
#6 {main}
  thrown in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Fatal Er...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Fatal Er...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(84): ConsoleOutput->write('<error>Fatal Er...')
#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(1, 'Uncaught TypeEr...', '/home/travis/bu...', 268, Array)
#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/Ap in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
Creating workers
Starting worker ... Done
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Error:</...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Error:</...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(59): ConsoleOutput->write('<error>Error:</...')
#5 [internal function]: ConsoleErrorHandler->handleException(Object(TypeError))
#6 {main}
  thrown in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Fatal Er...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Fatal Er...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(84): ConsoleOutput->write('<error>Fatal Er...')
#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(1, 'Uncaught TypeEr...', '/home/travis/bu...', 268, Array)
#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/Ap in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
Creating the scheduler workers
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Error:</...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Error:</...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(59): ConsoleOutput->write('<error>Error:</...')
#5 [internal function]: ConsoleErrorHandler->handleException(Object(TypeError))
#6 {main}
  thrown in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($pieces) must be of type array, string given in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php:268
Stack trace:
#0 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(268): implode(Array, ';')
#1 [internal function]: ConsoleOutput->_replaceTags(Array)
#2 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(239): preg_replace_callback('/<(?P<tag>[a-z0...', Array, '<error>Fatal Er...')
#3 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php(192): ConsoleOutput->styleText('<error>Fatal Er...')
#4 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php(84): ConsoleOutput->write('<error>Fatal Er...')
#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(1, 'Uncaught TypeEr...', '/home/travis/bu...', 268, Array)
#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Core/Ap in /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleOutput.php on line 268
```

**Comment by JakubOnderka** [comment]
PR sent to CakePHP: https://github.com/cakephp/cakephp/pull/14507

**Comment by JakubOnderka** [comment]
So it doesn't work, because of similar problem in `kamisama/php-resque-ex` package:
```
Error: implode(): Argument #2 ($pieces) must be of type array, string given
1997#0 /home/travis/build/MISP/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode(Array, '\r\n')
1998#1 /home/travis/build/MISP/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call('smembers', Array)
1999#2 /home/travis/build/MISP/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(103): RedisApi->__call('smembers', Array)
2000#3 /home/travis/build/MISP/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(292): Resque_Worker::all()
2001#4 /home/travis/build/MISP/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(637): CakeResque::getWorkers()
2002#5 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->stop()
2003#6 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('stop', Array)
2004#7 /home/travis/build/MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
2005#8 /home/travis/build/MISP/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
2006#9 {main}
```
But last commit in this package is from 2016, so I am afraid it will be never fixed and we should find another library, that is supported.
