### ISSUE TITLE
Redis configuration is not followed everywhere

### ISSUE THREAD

**Issue by stricaud** [MISP/MISP#5883]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Debian
| PHP version               | 7.3
| MISP version / git hash   | 2.4.125, b724e302823af2ad16573fc3a28b9211999f9797
| Browser                   | Mosaic 3

### Expected behavior
When Redis is configured, this configuration must be used everywhere

### Actual behavior
The configuration is used in some places, but not all of them, in particular:
* app/Vendor/kamisama/php-resque-ex/lib/Resque.php
* app/Vendor/monolog/monolog/src/Monolog/Handler/RedisHandler.php
* app/Lib/Tools/PubSubTool.php
* app/Plugin/CakeResque/Config/config.php

Which all have "localhost" hardcoded in their configuration, preventing MISP to use a Redis not installed on localhost.

### Steps to reproduce the behavior
Install Redis outside of localhost, Install MISP, configure ZeroMQ with attributes_notification on.

### Logs, screenshots, configuration dump, ...
With Redis configured with the proper hostname in MISP:
```
Error: Cannot assign requested address
#0 /usr/share/misp/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect('localhost', 6379, 5, '125')
#1 /usr/share/misp/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /usr/share/misp/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /usr/share/misp/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /usr/share/misp/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(77): Resque::redis()
#5 /usr/share/misp/app/Lib/cakephp/lib/Cake/Console/Shell.php(451): CakeResqueShell->startup()
#6 /usr/share/misp/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('start', Array)
#7 /usr/share/misp/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /usr/share/misp/app/Console/cake.php(32): ShellDispatcher::run(Array)
#9 {main}
```

**Comment by stricaud** [comment]
While working on a patch, realized PubSubTool.php sets its configuration underneath and should not be impacted. However this comes from Libraries external to the source code.
