### ISSUE TITLE
Cannot import JSON STIX 2.0 events

### ISSUE THREAD

**Issue by dn2020gh** [MISP/MISP#5886]
When Importing Events from JSON Stix 2.0 getting the following error:

_Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool._

...I initially thought that JSON file may have an issue but I have tried with old ones that i did work and getting this error all the time. STIX 1.1.1 xml import works fine but does not recognise URL IOCs

I did update to v2.4.125 and the following are the versions of library modules:

STIX: >1.2.0.6
CyBox: >2.1.0.21
mixbox: 1.0.3
maec: >4.1.0.14
STIX2: >1.2.0
PyMISP: >2.4.120
![Capture](https://user-images.githubusercontent.com/65148145/81523846-796e4700-9392-11ea-8cf7-bf54e48d3c2a.PNG)

Issue still occurs..below is the exec-errors.log output:

_Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 104, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/properties.py", line 225, in clean
    valid = self.contained.clean(item)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/properties.py", line 722, in clean
    parsed_obj = parse(dictified, allow_custom=self.allow_custom, interoperability=self.interoperability)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 47, in parse
    obj = dict_to_stix2(obj, allow_custom, interoperability, version)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 142, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, interoperability=interoperability, **stix_dict)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/v20/sdo.py", line 256, in __init__
    super(Report, self).__init__(*args, **kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 334, in __init__
    super(_DomainObject, self).__init__(*args, **kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 196, in __init__
    raise MissingPropertiesError(cls, missing_kwargs)
stix2.exceptions.MissingPropertiesError: No values for required properties for Report: (labels, name, object_refs, published).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1578, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1569, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 47, in parse
    obj = dict_to_stix2(obj, allow_custom, interoperability, version)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 142, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, interoperability=interoperability, **stix_dict)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/v20/bundle.py", line 42, in __init__
    super(Bundle, self).__init__(**kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 199, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 114, in _check_property
    exc,
  File "<string>", line 3, in raise_from
stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': No values for required properties for Report: (labels, name, object_refs, published)._

**Comment by dn2020gh** [comment]
@chrisr3d will you be addressing the STIX 2.0 JSON issue? Still does not work

STIX 1 fixed

**Comment by chrisr3d** [comment]
I have been testing with the files you provided, and as the error message you sent here already mention it: some required fields are missing within the files themselves.

Before it goes through all the processing to parse the content, there is a function called `parse` that is executed to load the document, and it fails because the `report` object within the document has some required fields that are missing (labels, name, object_refs, published).

Do you know how those documents have been generated? There is a tool called [stix2_validator](https://github.com/oasis-open/cti-stix-validator) that can be used to check the validity of a stix2 document.

**Comment by dn2020gh** [comment]
Yes I have tried to validate them using stix2_validator and indeed validation have failed.

This is interesting as I was uploading them as Events into MISP last week with no issues.

Those JSONs are all exports from IBM X-Force Exchange reports. You can see some samples ones here:

https://exchange.xforce.ibmcloud.com/collection/COVID-19-Infostealer-Spearphishing-Campaign-8cdbf707a0776a9b31466a271ee4ecd0
https://exchange.xforce.ibmcloud.com/collection/COVID-19-Fears-Behind-Brazilian-Phishing-Scam-91bc7df5d5a99807e0d6c9eee7f09b18
https://exchange.xforce.ibmcloud.com/collection/Threat-Actors-Capitalizing-on-COVID-19-f812020e3eddbd09a0294969721643fe

....when you go the above reports, there is an option of exporting them either in STIX 1 XML or STIX 2 JSON.

So STIX 1 was never working for me as URLs were not recognised until today when @RichieB2B applied the fix. STIX 2 were always working until last week. 

Perhaps IBM has done something on their end last week but then their old reports(3 links above) should still work but they don't :(

Can you supply me the examples of valid JSONs so I can test out?

**Comment by RichieB2B** [comment]
@chrisr3d did the STIX 1.1.1 fixes, I just tested them. :-)

**Comment by abhijeetasawant** [comment]
I found this issue while importing STIX2 file 

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2061, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2055, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 80, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 354, in parse_event
    getattr(self, self._stix2misp_mapping[object_type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 373, in _parse_indicator
    self.parse_indicator_object(indicator)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 494, in parse_indicator_object
    pattern = self._handle_pattern(indicator.pattern).replace('\\\\', '\\').split(' AND ')
**AttributeError: 'StixFromMISPParser' object has no attribute '_handle_pattern'**
