### ISSUE TITLE
Complete Pull job from another Instance in "Queued" state without any reasonable cause

### ISSUE THREAD

**Issue by marianpigi2020** [MISP/MISP#5981]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.4 LTS
| OS version (client)       | Win10
| PHP version               | 7.4.4
| MISP version / git hash   | v2.4.121 (0f632236fa62e16f98e4e09e41349e1926998b3e)
| Browser                   | Chrome

### Support Questions
Hi, everybody!
We would like to troubleshoot the "full pull" job from another instance, that seems not working.

Recently, we deployed a new instance of the misp, we will call it MISP_A. 
The new MISP_A instance should reach a remote instance, MISP_B, on the internet.

We wanted to align the two instances, by creating an hourly job on MISP_A that pulls from MISP_B.
The intention was to do a first "pull" of all the events in MISP_B (about 300000) so that we could align the two instances.

The first few days, after establishing a connection between the two instances, the pull loaded a huge amount of events (it reaches up to 18000 pulled events per day).

Although the rate of downloaded events is high, the pull never finished. Day by day, the job still was in progress but was not progressing quickly.
Over time, the rate was inconsistent, reaching less than 100 events per day, then 2 events per day and finally 0 events per day.

Once arrived at this situation, MISP_A no longer downloads events either by manual pull or by automated cron-jobs pull.
All these jobs remains in "queue" state.

Manual jobs rarely starts, and when started they usually stucks at low percentages, like 2%, and remains in this state for days.

CPU/RAM are not busy. There is plenty of disk space.
We do not see any processes that are consuming resources.

We have attempted on restarting workers, also rebooting the entire MISP_A machine, checked connection (tests are working properly), pulling a single event works well without any error.

MISP_A is now at version 2.4.121.
MISP_B version is 2.4.103.

Do you have any idea what might have gone wrong? What you would suggest to verify in order to restore the functionality of MISP_A pulling from MISP_B?

I would like to thank you all the team and anyone that will suggests any kind of check or log we could investigate on.

### Logs, screenshots, configuration dump, ...
From the logs, we do not see any relevant changes.
We also checked all the machine logs.
No errors from:
/var/log/mysql/error.log
/var/log/redis/redis-server.log

SOme little warnings from:
/var/www/MISP/app/tmp/logs/debug.log
`2020-06-04 12:46:29 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Controller/Component/ACLComponent.php, line 697]2020-06-04 12:46:29 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/AppModel.php, line 2180]2020-06-04 12:46:29 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Controller/AppController.php, line 686]
`

/var/www/MISP/app/tmp/logs/error.log
```

2020-06-04 12:50:29 Warning: stream_socket_enable_crypto(): SSL: Handshake timed out in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
2020-06-04 13:23:00 Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
2020-06-02 11:23:46 Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
2020-06-02 12:22:56 Warning: stream_socket_enable_crypto(): SSL: Handshake timed out in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
2020-06-02 13:22:43 Warning: stream_socket_enable_crypto(): SSL: Handshake timed out in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]


```

Most relevant errors are from these logs:
/var/www/MISP/app/tmp/logs/resque-2020xxxxx.log
```

[2020-06-04 11:20:02] main.INFO: got {"queue":"default","id":"6cb2ee0340cb3712104399b754a4ec9a","class":"ServerShell","args":[{"0":"enqueuePull","1":1591262400,"2":"1","3":"2","s_time":1591258806}]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"6cb2ee0340cb3712104399b754a4ec9a\",\"class\":\"ServerShell\",\"args\":[{\"0\":\"enqueuePull\",\"1\":1591262400,\"2\":\"1\",\"3\":\"2\",\"s_time\":1591258806}]})","worker":"misp:839"} []
[2020-06-04 11:20:02] main.INFO: Processing ID:6cb2ee0340cb3712104399b754a4ec9a in default {"type":"process","worker":"misp:839","job_id":"6cb2ee0340cb3712104399b754a4ec9a"} []
[2020-06-04 11:23:06] main.ERROR: {"queue":"default","id":"6cb2ee0340cb3712104399b754a4ec9a","class":"ServerShell","args":[{"0":"enqueuePull","1":1591262400,"2":"1","3":"2","s_time":1591258806}]} failed: Unable to perform enableCrypto operation on CakeSocket {"type":"fail","log":"Unable to perform enableCrypto operation on CakeSocket","job_id":"6cb2ee0340cb3712104399b754a4ec9a","time":183525,"worker":"misp:839"} []
[2020-06-04 12:20:01] main.INFO: got {"queue":"default","id":"f0bd93a2e2369e23ab195e48cc126e31","class":"ServerShell","args":[{"0":"enqueuePull","1":1591266000,"2":"1","3":"2","s_time":1591262402}]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"f0bd93a2e2369e23ab195e48cc126e31\",\"class\":\"ServerShell\",\"args\":[{\"0\":\"enqueuePull\",\"1\":1591266000,\"2\":\"1\",\"3\":\"2\",\"s_time\":1591262402}]})","worker":"misp:839"} []
[2020-06-04 12:20:01] main.INFO: Processing ID:f0bd93a2e2369e23ab195e48cc126e31 in default {"type":"process","worker":"misp:839","job_id":"f0bd93a2e2369e23ab195e48cc126e31"} []
[2020-06-04 12:22:22] main.ERROR: {"queue":"default","id":"f0bd93a2e2369e23ab195e48cc126e31","class":"ServerShell","args":[{"0":"enqueuePull","1":1591266000,"2":"1","3":"2","s_time":1591262402}]} failed: Unable to perform enableCrypto operation on CakeSocket {"type":"fail","log":"Unable to perform enableCrypto operation on CakeSocket","job_id":"f0bd93a2e2369e23ab195e48cc126e31","time":141402,"worker":"misp:839"} []
[2020-06-04 12:47:33] main.INFO: got {"queue":"default","id":"1ad098d9df86637f45c72f5baced7699","class":"ServerShell","args":[["pull","5","2","full","4"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"1ad098d9df86637f45c72f5baced7699\",\"class\":\"ServerShell\",\"args\":[[\"pull\",\"5\",\"2\",\"full\",\"4\"]]})","worker":"misp:839"} []
[2020-06-04 12:47:33] main.INFO: Processing ID:1ad098d9df86637f45c72f5baced7699 in default {"type":"process","worker":"misp:839","job_id":"1ad098d9df86637f45c72f5baced7699"} []
[2020-06-04 12:50:29] main.ERROR: {"queue":"default","id":"1ad098d9df86637f45c72f5baced7699","class":"ServerShell","args":[["pull","5","2","full","4"]]} failed: Unable to perform enableCrypto operation on CakeSocket {"type":"fail","log":"Unable to perform enableCrypto operation on CakeSocket","job_id":"1ad098d9df86637f45c72f5baced7699","time":176448,"worker":"misp:839"} []
[2020-06-04 13:20:04] main.INFO: got {"queue":"default","id":"4a468bb53641a7f8b7cb2c23ca0f1360","class":"ServerShell","args":[{"0":"enqueuePull","1":1591269600,"2":"1","3":"2","s_time":1591266001}]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"4a468bb53641a7f8b7cb2c23ca0f1360\",\"class\":\"ServerShell\",\"args\":[{\"0\":\"enqueuePull\",\"1\":1591269600,\"2\":\"1\",\"3\":\"2\",\"s_time\":1591266001}]})","worker":"misp:839"} []
[2020-06-04 13:20:04] main.INFO: Processing ID:4a468bb53641a7f8b7cb2c23ca0f1360 in default {"type":"process","worker":"misp:839","job_id":"4a468bb53641a7f8b7cb2c23ca0f1360"} []
[2020-06-04 13:23:00] main.ERROR: {"queue":"default","id":"4a468bb53641a7f8b7cb2c23ca0f1360","class":"ServerShell","args":[{"0":"enqueuePull","1":1591269600,"2":"1","3":"2","s_time":1591266001}]} failed: Unable to perform enableCrypto operation on CakeSocket {"type":"fail","log":"Unable to perform enableCrypto operation on CakeSocket","job_id":"4a468bb53641a7f8b7cb2c23ca0f1360","time":176295,"worker":"misp:839"} []

```
/var/www/MISP/app/tmp/logs/resque-scheduler-error.log
```

PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/redis.so.so (/usr/lib/php/20190902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/redis.so.so (/usr/lib/php/20190902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/redis.so.so (/usr/lib/php/20190902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Notice Error: fwrite(): send of 53 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php, line 77]

Error: Failed to write entire command to stream
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(539): RedisApi->__call()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work()
#4 {main}
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/redis.so.so (/usr/lib/php/20190902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work()
#3 {main}
Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work()
#3 {main}
Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work()
#3 {main}
Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work()
#3 {main}
Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work()
#3 {main}


```

![MISP__job_state](https://user-images.githubusercontent.com/66361984/83776293-4a44b000-a688-11ea-85ce-83377ecfea7c.png)
![MISP__server_configuration](https://user-images.githubusercontent.com/66361984/83776916-0e5e1a80-a689-11ea-9966-35e251ba3027.png)

**Comment by icepaule** [comment]
Having exact the same issue. Even after setting up a new and initial instance of MISP.
Giving the pull some time, it fortunatly comes back with some error messages. Maybe that will help pointing into the right direction.

Currently installed version… v2.4.129 (8ddb1305bec62b9ea8cb0cbb7c613a911c248ce1)
Cleared cache bevore attempt.
Checked diagnostics

_ERROR: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
--_

Thaaanks so much for your help.  ;-)

Cheers
Marcus

**Comment by iglocska** [comment]
I think the two issues might be unrelated, we've introduced several fixes that should resolve the issue described by the OP since then (could you confirm this?)

as for the full group by issue - do you have the full stack trace from the error.log / worker-error.log by any chance?

**Comment by icepaule** [comment]
Hi iglocska,

sure, have a look:
 **cat resque-2020-08-05.log**

_[2020-08-05 10:17:03] main.INFO: got {"queue":"default","id":"146090c67df851c587073d5ef13c83a7","class":"ServerShell","args":[["pull","2","2","full","6101"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"146090c67df851c587073d5ef13c83a7\",\"class\":\"ServerShell\",\"args\":[[\"pull\",\"2\",\"2\",\"full\",\"6101\"]]})","worker":"misp:1580"} []
[2020-08-05 10:17:03] main.INFO: Processing ID:146090c67df851c587073d5ef13c83a7 in default {"type":"process","worker":"misp:1580","job_id":"146090c67df851c587073d5ef13c83a7"} []
[2020-08-05 10:17:06] main.INFO: got {"queue":"default","id":"ce2ade3b636d3b269dd82b0d4cc16b3b","class":"ServerShell","args":[["pull","2","3","full","6102"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"ce2ade3b636d3b269dd82b0d4cc16b3b\",\"class\":\"ServerShell\",\"args\":[[\"pull\",\"2\",\"3\",\"full\",\"6102\"]]})","worker":"misp:3103"} []
[2020-08-05 10:17:06] main.INFO: Processing ID:ce2ade3b636d3b269dd82b0d4cc16b3b in default {"type":"process","worker":"misp:3103","job_id":"ce2ade3b636d3b269dd82b0d4cc16b3b"} []
[2020-08-05 10:17:15] main.ERROR: {"queue":"default","id":"146090c67df851c587073d5ef13c83a7","class":"ServerShell","args":[["pull","2","2","full","6101"]]} failed: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by {"type":"fail","log":"SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by","job_id":"146090c67df851c587073d5ef13c83a7","time":12150,"worker":"misp:1580"} []
[2020-08-05 10:19:14] main.ERROR: {"queue":"default","id":"ce2ade3b636d3b269dd82b0d4cc16b3b","class":"ServerShell","args":[["pull","2","3","full","6102"]]} failed: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by {"type":"fail","log":"SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by","job_id":"ce2ade3b636d3b269dd82b0d4cc16b3b","time":127229,"worker":"misp:3103"} []_

**cat debug.log**

_2020-08-05 10:15:33 Notice: Error during adding GPG signing key.
[Crypt_GPG_KeyNotFoundException] Key not found: [removed]
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG.php(1251): Crypt_GPG->_addKey(Array, false, true, 'marcus.pauli@f-...', 'e12937c0ee842b4...')
#1 /var/www/MISP/app/Model/Server.php(5049): Crypt_GPG->addSignKey('marcus.pauli@f-...', 'e12937c0ee842b4...')
#2 /var/www/MISP/app/Controller/ServersController.php(1085): Server->gpgDiagnostics(1)
#3 [internal function]: ServersController->serverSettings('diagnostics')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}_

**cat resque-worker-error.log**

_Error: LOADING Redis is loading the dataset in memory
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(668): Redis->hSet('workerLogger', 'misp:1265:updat...', '["RotatingFile"...')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(107): Resque_Worker->registerLogger(Object(MonologInit\MonologInit))
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('update', 1, Object(MonologInit\MonologInit), '5')
#3 {main}_


And thanks a lot for your kind help.  :-)

Marcus

**Comment by marianpigi2020** [comment]
> I think the two issues might be unrelated, we've introduced several fixes that should resolve the issue described by the OP since then (could you confirm this?)
> 
> as for the full group by issue - do you have the full stack trace from the error.log / worker-error.log by any chance?

Hi Iglocska!
Yes i confirm. Sorry for the late reply but i had some issues in executing the update.
After the update, the misp instance start collect the missing events.

So, the first issue is no more existing and this issue could be set on "resolved".

We had a lot of events to pull from the other MISP instance (about 200k).
After the resolution, it took some days to collect only the 30% of the events from the other MISP instance.
Day after day, the pulling activity was gradually slowing down. It passes from 10k events/days pulled, till 1k events/day pulled.

So, we choose to de-activate the correlation from the Server Settings.
As conseguence of this, The events were pulled instantaneously. Our MISP instance has pulled all the remaining events (around 140ooo events) in 2 days.
Also, our MISP instance has created a "purge correlations" job (that is still in "queue" status after a month).

Now we've pulled all the events from the other MISP instance. We will find a way to fix the correlation problems. Thanks a lot for your help, support and sharing knowledge!
