### ISSUE TITLE
MISP all jobs stuck at Waiting

### ISSUE THREAD

**Issue by the0new0kid** [MISP/MISP#6020]
My VM in VMware workstation is in Bridged mode able to access the internet. 

--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.6
| OS version (client)       | Win10, Ubuntu 18.04.6
| PHP version               | 7.2.24
| MISP version / git hash   | v2.4.126 (eef05690d88b69e7448d9dc9b8611c7bfbfc130e)
| Browser                   | Chrome, Firefox

### Support Questions
I have installed MISP in my Ubuntu virtual machine. I sometimes use my windows 10 host browser to access or firefox on the local VM. I'm following tutorial videos about events and feeds, i've enabled some feeds, fetched data from feeds but the jobs even from may are stuck at Waiting. 

### Logs, screenshots, configuration dump, ...
https://i.ibb.co/xj4qMfK/image.png
https://i.ibb.co/KWJn0hW/image.png
https://i.ibb.co/W6VXR6c/image.png

In debug.log
```
2020-06-17 13:57:09 Notice: Error during initializing GPG.
[Crypt_GPG_FileException] The 'homedir' "/var/www/MISP/.gnupg" is not enterable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPGAbstract.php(288): Crypt_GPG_Engine->__construct(Array)
#1 /var/www/MISP/app/Model/Server.php(5046): Crypt_GPGAbstract->__construct(Array)
#2 /var/www/MISP/app/Controller/ServersController.php(1056): Server->gpgDiagnostics(0)
#3 [internal function]: ServersController->serverSettings('diagnostics')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2020-06-17 13:57:16 Notice: Error during initializing GPG.
[Crypt_GPG_FileException] The 'homedir' "/var/www/MISP/.gnupg" is not enterable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPGAbstract.php(288): Crypt_GPG_Engine->__construct(Array)
#1 /var/www/MISP/app/Model/Server.php(5046): Crypt_GPGAbstract->__construct(Array)
#2 /var/www/MISP/app/Controller/ServersController.php(1056): Server->gpgDiagnostics(0)
#3 [internal function]: ServersController->serverSettings('diagnostics')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2020-06-17 13:58:57 Notice: Error during initializing GPG.
[Crypt_GPG_FileException] The 'homedir' "/var/www/MISP/.gnupg" is not enterable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPGAbstract.php(288): Crypt_GPG_Engine->__construct(Array)
#1 /var/www/MISP/app/Model/Server.php(5046): Crypt_GPGAbstract->__construct(Array)
#2 /var/www/MISP/app/Controller/ServersController.php(1056): Server->gpgDiagnostics(0)
#3 [internal function]: ServersController->serverSettings('diagnostics')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

In error.log 
```
2020-05-27 21:52:31 Warning: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]
2020-06-17 13:38:03 Warning: vsprintf(): Too few arguments in [/var/www/MISP/app/Lib/cakephp/lib/Cake/I18n/I18n.php, line 697]
2020-06-17 13:56:04 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(ServersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(ServersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(ServersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2020-06-17 13:56:04 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(ServersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(ServersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(ServersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2020-06-17 13:56:04 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(ServersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(ServersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(ServersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2020-06-17 13:56:04 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(ServersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(ServersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(ServersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

**Comment by cvandeplas** [comment]
The errors of your debug log should be self-explanatory:
```
2020-06-17 13:58:57 Notice: Error during initializing GPG.
[Crypt_GPG_FileException] The 'homedir' "/var/www/MISP/.gnupg" is not enterable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory.
```
Your webserver user cannot access this folder, or you might not have correctly generated GPG private keys.

In your error.log
```
2020-05-27 21:52:31 Warning: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]
```
MISP Cannot access your redis server. It might not be running, or has a configuration problem preventing MISP to access it.
Background workers need Redis to be functional. This is why your feeds are not downloaded/fetched.

```
2020-06-17 13:56:04 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/update
Stack Trace:
<snip>
```
These are likely caused because your MISP has short session timeouts, you got disconnected from your authenticated session as you left the page open for too long.

**Comment by the0new0kid** [comment]
> The errors of your debug log should be self-explanatory:
> 
> ```
> 2020-06-17 13:58:57 Notice: Error during initializing GPG.
> [Crypt_GPG_FileException] The 'homedir' "/var/www/MISP/.gnupg" is not enterable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory.
> ```
> 
> Your webserver user cannot access this folder, or you might not have correctly generated GPG private keys.
> 
> In your error.log
> 
> ```
> 2020-05-27 21:52:31 Warning: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]
> ```
> 
> MISP Cannot access your redis server. It might not be running, or has a configuration problem preventing MISP to access it.
> Background workers need Redis to be functional. This is why your feeds are not downloaded/fetched.
> 
> ```
> 2020-06-17 13:56:04 Error: [BadRequestException] The request has been black-holed
> Request URL: /servers/update
> Stack Trace:
> <snip>
> ```
> 
> These are likely caused because your MISP has short session timeouts, you got disconnected from your authenticated session as you left the page open for too long.

Thank you,  i gave write access recursively for www-data to the app folder and everything is working fine now. Turns out under diagnostics i had a lot of files with read/write access disabled too that's why it was not working.
