### ISSUE TITLE
 Error: [PDOException]

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#604]
Hi again, 

When I am trying to manually batch import ~3000 indicators I get the following error (after all only 67 indicators are imported..):
 "
 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org' cannot be null
Request URL: /attributes/add/1691
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(460): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(426): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1012): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1928): DboSource->create(Object(AppModel), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1745): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2338): Model->save(Array, Array)
#6 /var/www/MISP/app/Model/Attribute.php(1034): Model->saveMany(Array)
#7 /var/www/MISP/app/Model/Attribute.php(413): Attribute->__afterSaveCorrelation(Array)
#8 [internal function]: Attribute->afterSave(true, Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): call_user_func_array(Array, Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1956): CakeEventManager->dispatch(Object(CakeEvent))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#12 /var/www/MISP/app/Controller/AttributesController.php(152): Model->save(Array)
"

Any ideas about this?

Kind regards,
Andreas

**Comment by iglocska** [comment]
Looking into it!

**Comment by advancedeng** [comment]
Hi iglocska, did you have time to look into this?

Thanks in advance, 
Andreas

**Comment by iglocska** [comment]
Not yet sorry, am a bit knocked out atm with a flu, will have a look at it over the weekend! Sorry for the delay!

**Comment by iglocska** [comment]
I've tried to reproduce it but didn't manage. 

What I did: Add ~1.3k hashes via the UI using add attribute button and ticking batch import.
Result: 1.3k hashes added to the event.

Is this what you also tried to do, or did you use some different method of adding the attributes?

**Comment by advancedeng** [comment]
Seems to be working right now. Still have not identified the root cause though!

**Comment by iglocska** [comment]
Very odd. The typical issue of "it works, but why does it work?" :)

**Comment by advancedeng** [comment]
It happened again when trying to import 700 "payload delivery"->src-ip .
From the logs I can see lots of the following
"
[2015-08-27 16:52:11] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:11356"} []
[2015-08-27 16:52:12] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:1236"} []
[2015-08-27 16:52:12] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:10605"} []
[2015-08-27 16:52:12] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:461"} []
[2015-08-27 16:52:13] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:29718"} []
[2015-08-27 16:52:13] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:5422"} []
"

Any idea?

Cheers,
Andreas

**Comment by elhoim** [comment]
Those logs line are about resque workers trying to reconnect. The value after the semi-colon should be the process id, so you should see those using ps.

**Comment by elhoim** [comment]
Try to kill them and restart all workers from the admin screen or using the command line script. It should stop those reconnection attempts.

Try to do a tail -f on the error log in /var/www/MISP/app/tmp/logs/ and re-start the importing of attributes, so that you can see what errors are generated at that moment.

**Comment by iglocska** [comment]
CakeResque workers should not try to reconnect under normal situations - were those entries generated while you were trying to add the attributes, or is it completely unrelated? 

As for the main issue that returned, I'll look more closely into this early next week!

**Comment by advancedeng** [comment]
@iglocska these entries are apparently unrelated. 
@elhoim Even if I stop all the workers (running the /var/www/MISP/app/Console/worker/stop.sh script) I still got the following logs
"
[2015-08-28 11:20:59] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:1725"} []
[2015-08-28 11:21:00] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp-prod:12871"} []
"

**Comment by elhoim** [comment]
Do you see them using ps? 
With something like 
```
ps faux | grep -E "1725|12871"
```

**Comment by advancedeng** [comment]
==> ./resque-2015-09-01.log <==
[2015-09-01 16:49:10] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:2471"} []
[2015-09-01 16:49:12] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:15606"} []
[2015-09-01 16:49:13] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:10605"} []
[2015-09-01 16:49:17] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:2471"} []
[2015-09-01 16:49:18] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:15606"} []
[2015-09-01 16:49:20] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:10605"} []
[2015-09-01 16:49:24] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:2471"} []
[2015-09-01 16:49:25] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:15606"} []
[2015-09-01 16:49:26] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:10605"} []
[2015-09-01 16:49:30] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:2471"} []
[2015-09-01 16:49:32] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:15606"} []
[2015-09-01 16:49:33] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:10605"} []
[2015-09-01 16:49:37] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:2471"} []
[2015-09-01 16:49:38] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:15606"} []
[2015-09-01 16:49:40] main.INFO: SIGPIPE received; attempting to reconnect {"type":"reconnect","worker":"misp:10605"} []
^C

root@misp:/var/www/MISP/app/tmp/logs# ps faux | grep -E "2471|15606|10605"
root      9354  0.0  0.0  11980   932 pts/1    S+   16:49   0:00          \_ grep --color=auto -E 2471|15606|10605

**Comment by RichieB2B** [comment]
I just did the upgrade to 2.4.7 and pulling from misppriv.circl.lu gives me the same type of error:
```
2016-01-14 15:13:34 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org' cannot be null
Request URL: /servers/pull/2/full
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(Job), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/ServersController.php(468): Model->save(Array)
#6 [internal function]: ServersController->pull('2', 'full')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by VolleyTom** [comment]
Hello,
We also tried to update from 2.3.0 to 2.4 (yesterday 2.4.7, today 2.4.10) and when trying to pull events, we got the following error:

<pre>
2016-01-20 10:37:46 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org' cannot be null
Request URL: /servers/pull/1/full
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(Job), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/ServersController.php(468): Model->save(Array)
#6 [internal function]: ServersController->pull('1', 'full')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}</pre>

Has someone a solution for this issue?

br

**Comment by iglocska** [comment]
Yeah, it's the leftover fields that have are not nullable that aren't used by 2.4 anymore that are giving you these issues. Give me a few minutes and I'll have a fix ready.

**Comment by iglocska** [comment]
I've just pushed a patch, just git pull and you'll find a new script in administration -> administrative scripts.

It's called 2.3->2.4 cleanup and it should resolve your issues. Let me know if it doesn't!

**Comment by elhoim** [comment]
@advancedeng @VolleyTom @RichieB2B Is it working for you? Can I close?

**Comment by RichieB2B** [comment]
I haven't seen these errors since fixing the MySQL tables.
