### ISSUE TITLE
Crashes when uploading malware sample.

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#6080]
Uploading a malware sample might cause MISP to generate an internal error. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | N.A.
| PHP version               | 7.2
| MISP version / git hash   | 2.4.125
| Browser                   | N.A.

### Expected behavior

Sample is uploaded and object is created.

### Actual behavior

Internal error.

### Logs, screenshots, configuration dump, ...

```
2020-07-01 08:29:14 Error: Could not finish advanced extraction
[Exception] Command 'python3 /var/www/MISP/app/files/scripts/generate_file_objects.py -p '/tmp/php1ezxq2'' return error code 1. STDERR: 'Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/generate_file_objects.py", line 67, in <module>
    obj = make_objects(args.path)
  File "/var/www/MISP/app/files/scripts/generate_file_objects.py", line 37, in make_objects
    fo, peo, seos = make_binary_objects(path)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/tools/create_misp_object.py", line 66, in make_binary_objects
    return make_pe_objects(lief_parsed, misp_file, standalone, default_attributes_parameters)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/tools/create_misp_object.py", line 26, in make_pe_objects
    pe_object = PEObject(parsed=lief_parsed, standalone=standalone, default_attributes_parameters=default_attributes_parameters)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/tools/peobject.py", line 51, in __init__
    self.generate_attributes()
  File "/usr/local/lib/python3.6/dist-packages/pymisp/tools/peobject.py", line 107, in generate_attributes
    s = PESectionObject(section, self._standalone, default_attributes_parameters=self._default_attributes_parameters)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/tools/peobject.py", line 123, in __init__
    super(PESectionObject, self).__init__('pe-section', standalone=standalone, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/mispevent.py", line 1299, in __init__
    self._set_template(kwargs.get('misp_objects_path_custom'))
  File "/usr/local/lib/python3.6/dist-packages/pymisp/mispevent.py", line 1362, in _set_template
    self._known_template = self._load_template_path(self.misp_objects_path / self.name / 'definition.json')
  File "/usr/local/lib/python3.6/dist-packages/pymisp/mispevent.py", line 1335, in _load_template_path
    self._definition = self._load_json(template_path)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/abstract.py", line 110, in _load_json
    data = load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2310: ordinal not in range(128)
```

**Comment by Rafiot** [comment]
Unless I'm mistaken, this issue has been fixed in newer versions of MISP, could you please update and try again?

**Comment by ancailliau** [comment]
The issue can be closed, we could not reproduce the issue after the update.
