### ISSUE TITLE
[misp2stix2.py] Invalid created date

### ISSUE THREAD

**Issue by coolacid** [MISP/MISP#6098]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.128, CoolAcid's Docker
| Browser                   | If applicable

### Expected behavior
Export of STIX2 Document

### Actual behavior
Error:
```
Error while processing your query: Invalid value for Report 'created': must be a datetime object, date object, or timestamp string in a recognizable format.
```

### Steps to reproduce the behavior
Attempt to export a STIX2 file

### Logs, screenshots, configuration dump, ...
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/stix2/utils.py", line 245, in parse_into_datetime
    parsed = dt.datetime.strptime(value, fmt)
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2020-06-27' does not match format '%Y-%m-%dT%H:%M:%SZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/stix2/base.py", line 104, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/usr/local/lib/python3.7/dist-packages/stix2/properties.py", line 378, in clean
    value, self.precision, self.precision_constraint,
  File "/usr/local/lib/python3.7/dist-packages/stix2/utils.py", line 249, in parse_into_datetime
    "must be a datetime object, date object, or "
ValueError: must be a datetime object, date object, or timestamp string in a recognizable format.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "misp2stix2.py", line 1802, in <module>
    main(sys.argv)
  File "misp2stix2.py", line 1799, in main
    stix_builder.buildEvent()
  File "misp2stix2.py", line 53, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "misp2stix2.py", line 53, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "misp2stix2.py", line 171, in handler
    report = self.eventReport()
  File "misp2stix2.py", line 84, in eventReport
    return Report(**report_args)
  File "/usr/local/lib/python3.7/dist-packages/stix2/v20/sdo.py", line 256, in __init__
    super(Report, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/stix2/base.py", line 334, in __init__
    super(_DomainObject, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/stix2/base.py", line 199, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/stix2/base.py", line 114, in _check_property
    exc,
  File "<string>", line 3, in raise_from
stix2.exceptions.InvalidValueError: Invalid value for Report 'created': must be a datetime object, date object, or timestamp string in a recognizable format.
```
Turns out, when MISP writes the temporary file for misp2stix2.py, the date is created as ` "date": "2020-07-06",` Which is invalid for STIX2 as it needs to be with time, misp2stix2.py doesn't do any mangling, and passes this string directly.

**Comment by coolacid** [comment]
Fixed in https://github.com/MISP/MISP/commit/364ca9d9d8ca8206cac5daebeadb18c52452f0e1
