### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by alexdjpre** [MISP/MISP#6100]
Hi, i've installed MISP on a kubernetes cluster but when i try to start mis_modules i receive this error:

2020-07-07 07:03:36,298 - misp-modules - INFO - Launch MISP modules server from current directory.
INFO:misp-modules:Launch MISP modules server from current directory.
Traceback (most recent call last):
  File "/usr/local/bin/misp-modules", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/misp_modules/__init__.py", line 261, in main
    mhandlers, loaded_modules = _launch_from_current_dir()
  File "/usr/local/lib/python3.7/site-packages/misp_modules/__init__.py", line 218, in _launch_from_current_dir
    load_helpers(helpersdir=helpersdir)
  File "/usr/local/lib/python3.7/site-packages/misp_modules/__init__.py", line 88, in load_helpers
    hhandlers[helpername] = importlib.import_module(helpername)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "helpers/cache.py", line 27, in <module>
    port = int(os.getenv("REDIS_PORT")) if os.getenv("REDIS_PORT") else 6379
ValueError: invalid literal for int() with base 10: 'tcp://10.100.216.61:6379'

I found a workaround to solve this issue with the missconfiguration of the IP resolution of redis instances. I've forced the redis instances to be on localhost.

The cache.py is:
import os

import redis
import hashlib

port = int(os.getenv("REDIS_PORT")) if os.getenv("REDIS_PORT") else 6379
hostname = os.getenv("REDIS_BACKEND") or '127.0.0.1'
db = int(os.getenv("REDIS_DATABASE")) if os.getenv("REDIS_DATABASE") else 0

Into the REDIS_BACKEND environment i put this entry:
REDIS_BACKEND=redis

Can you help me to solve this issue ?

Bye
Alessandro

**Comment by helinko** [comment]
Which docker images are you using?

**Comment by alexdjpre** [comment]
Hi is not docker, i've delivered the image on kuebrnetes.

**Comment by linehammer** [comment]
The error message invalid literal for int() with base 10 would seem to indicate that you are passing a string that's not an integer to the int() function . In other words it's either empty, or has a character in it other than a digit. You can solve this error by using Python isdigit() method to check whether the value is number or not. The returns True if all the characters are digits, otherwise False . The other way to overcome this issue is to wrap your code inside a Python try...except block to handle this error.
 
Sometimes the difference between Python2.x and Python3.x that leads to this ValueError: [invalid literal](http://net-informations.com/python/err/int.htm) for int() with base 10 . With Python2.x , int(str(3/2)) gives you "1". With Python3.x , the same gives you ("1.5"): ValueError: invalid literal for int() with base 10: "1.5".
