### ISSUE TITLE
Email Test Failed. Reason: The message could not be sent.

### ISSUE THREAD

**Issue by utkonos** [MISP/MISP#6246]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.130

### Expected behavior
Install completes

### Actual behavior
Install stops at 88% with two errors.

### Steps to reproduce the behavior
```
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M
```

### Logs, screenshots, configuration dump, ...

```
======================================================================
FAIL: test_user_settings (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 2155, in test_user_settings
    self.assertTrue(mail_logs[0].title.startswith(f'Email  to {self.admin_misp_connector._current_user.email}'), mail_logs[0].title)
AssertionError: False is not true : Email to admin@admin.test, titled "[ORGNAME MISP] Event 76 - Low - tlp:amber" failed. Reason: The message could not be sent.

======================================================================
FAIL: test_zmq (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 1452, in test_zmq
    self.assertEqual(r['message'], 'Event published to ZMQ')
AssertionError: 'ZMQ event publishing not enabled.' != 'Event published to ZMQ'
- ZMQ event publishing not enabled.
+ Event published to ZMQ


----------------------------------------------------------------------
Ran 66 tests in 127.381s

FAILED (failures=2)
#########################################################################################  (88%)
```

**Comment by utkonos** [comment]
Whole new set of errors on install now. This one is gone.
