### ISSUE TITLE
Import failed of a CISA STIX file

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#6250]
https://us-cert.cisa.gov/sites/default/files/publications/MAR-10301706-2.v1.WHITE.stix.xml

~~~~
/var/www/MISP-priv/venv/lib/python3.8/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/var/www/MISP-priv/venv/lib/python3.8/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/var/www/MISP-priv/venv/lib/python3.8/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
TOUMarking:TermsOfUseMarkingStructureType
Traceback (most recent call last):
  File "/var/www/MISP-priv/app/files/scripts/stix2misp.py", line 1499, in <module>
    main(sys.argv)
  File "/var/www/MISP-priv/app/files/scripts/stix2misp.py", line 1494, in main
    stix_parser.build_misp_event(event)
  File "/var/www/MISP-priv/app/files/scripts/stix2misp.py", line 80, in build_misp_event
    self.build_misp_dict(event)
  File "/var/www/MISP-priv/app/files/scripts/stix2misp.py", line 1176, in build_misp_dict
    self.parse_external_indicators(self.event.indicators)
  File "/var/www/MISP-priv/app/files/scripts/stix2misp.py", line 1226, in parse_external_indicators
    self.parse_external_single_indicator(indicator)
  File "/var/www/MISP-priv/app/files/scripts/stix2misp.py", line 1254, in parse_external_single_indicator
    self.handle_object_case(attribute_type, attribute_value, compl_data, to_ids=True, object_uuid=object_uuid)
NameError: name 'object_uuid' is not defined

~~~~

**Comment by adulau** [comment]
Thank you very much for the quick fix. It works.

Maybe some additional fields could be imported such as:

- cybox:Description
- incident:Description - stix:Incident
-   <FileObj:Hashes>
                        <cyboxCommon:Hash> which contains ssdeep and many other hashes supported by misp
- relationships with Characterized_By
- ArtifactObj:Raw_Artifact
- yaraTM:Rule
