### ISSUE TITLE
Unable to update taxonomies

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#6263]
# Unable to update taxonomies

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.4
| MISP version / git hash   | v2.4.130 (d1ddf7d10234f507f2d3008c07f253c667de4657)
| Browser                   | Chrome

### Expected behavior
Update taxonomies if have new

### Actual behavior
Error message in Taxonomies update page
```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
```

### Steps to reproduce the behavior
Fresh install using imported database from older misp instance. If in `logs` table field `ip` is set as expected by `Schema status` error occurs. If set default value to empty string then error not occurs but `Schema status` at `Reveal benign deltas` show mismatch with what have expected.

### Logs, screenshots, configuration dump, ...
```
2020-09-01 09:33:33 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'ip' doesn't have a default value
Request URL: /taxonomies/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Controller/TaxonomiesController.php(213): Model->save()
#6 [internal function]: TaxonomiesController->update()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#11 {main}
```

**Comment by Turecky** [comment]
When set `ip` field default value to `empty string` looks like working but in response message get:
```
Could not update any of the taxonomy libraries
```
and in debug log have:
```
2020-09-01 11:42:16 Notice: Notice (8): Undefined index: confidence in [/var/www/MISP/app/Model/Taxonomy.php, line 112]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 112
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: confidence in [/var/www/MISP/app/Model/Taxonomy.php, line 113]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 113
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: periodicity in [/var/www/MISP/app/Model/Taxonomy.php, line 112]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 112
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: periodicity in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: periodicity in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: change-likelihood in [/var/www/MISP/app/Model/Taxonomy.php, line 112]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 112
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: change-likelihood in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: change-likelihood in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Undefined index: TaxonomyPredicate in [/var/www/MISP/app/Model/TaxonomyPredicate.php, line 32]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
TaxonomyPredicate::beforeValidate() - APP/Model/TaxonomyPredicate.php, line 32
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 242
ModelValidator::_triggerBeforeValidate() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 454
ModelValidator::errors() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 242
ModelValidator::validates() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 99
Model::validates() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3502
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 134
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
ModelValidator::validateMany() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 211
Model::validateMany() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2413
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 162
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
Model::saveAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2463
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 119
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-01 11:42:16 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/TaxonomyPredicate.php, line 32]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
TaxonomyPredicate::beforeValidate() - APP/Model/TaxonomyPredicate.php, line 32
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 242
ModelValidator::_triggerBeforeValidate() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 454
ModelValidator::errors() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 242
ModelValidator::validates() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 99
Model::validates() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3502
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 134
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
ModelValidator::validateMany() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 211
Model::validateMany() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2413
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 162
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
Model::saveAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2463
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 119
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

```

**Comment by aaronkaplan** [comment]
seeing the same issue. @iglocska any ideas?
For me this results in a very large queue of open jobs which don't get processed.

Output from the log file:
```
aaron@server:~/MISP/app/tmp/logs$ [2020-09-07 15:50:16] main.INFO: got {"queue":"email","id":"35d6cb21d06766b7d7b51ce4590c5212","class":"EventShell","args":[["alertemail","13","126036","78191",null]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"email\",\"id\":\"35d6cb21d06766b7d7b51ce4590c5212\",\"class\":\"EventShell\",\"args\":[[\"alertemail\",\"13\",\"126036\",\"78191\",null]]})","worker":"server:25845"} []
[2020-09-07 15:50:16] main.INFO: Processing ID:35d6cb21d06766b7d7b51ce4590c5212 in email {"type":"process","worker":"server:25845","job_id":"35d6cb21d06766b7d7b51ce4590c5212"} []
[2020-09-07 15:50:17] main.ERROR: {"queue":"email","id":"35d6cb21d06766b7d7b51ce4590c5212","class":"EventShell","args":[["alertemail","13","126036","78191",null]]} failed: SQLSTATE[HY000]: General error: 1364 Field 'ip' doesn't have a default value {"type":"fail","log":"SQLSTATE[HY000]: General error: 1364 Field 'ip' doesn't have a default value","job_id":"35d6cb21d06766b7d7b51ce4590c5212","time":943,"worker":"server:25845"} []
```

**Comment by aaronkaplan** [comment]
so should this be fixed in the latest update?

**Comment by iglocska** [comment]
Yup! We now set an empty value when appropriate for the log entries.

**Comment by iglocska** [comment]
For a more in-depth explanation:

If IP logging is enabled, a new column is added to the log table to log the IPs - this column gets fed the client's IP for each entry.

However, if you generate a log entry via a background job, there is no user executing the query, it's a CLI script, as such the IP field remains empty. No problem normally, but if you are running mysql in strict mode, not having a default value on the table for the IP field will make it barf. We now force an empty string in these cases (that way we avoid having to modify a potentially massive table in the DB).

**Comment by aaronkaplan** [comment]
got it! Thx,
what to do with the existing stalled update worker jobs?

**Comment by iglocska** [comment]
They should trigger again - if they don't, go to administration -> server settings ->diagnostics, you can release the lock there.

**Comment by Turecky** [comment]
Still have errors in `debug.log` on `Taxonomy update`
Currently installed version… v2.4.132 (ae5434fbc66cf61376986424841df976e9c70fef)
```
2020-09-21 09:01:29 Notice: Notice (8): Undefined index: confidence in [/var/www/MISP/app/Model/Taxonomy.php, line 112]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 112
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: confidence in [/var/www/MISP/app/Model/Taxonomy.php, line 113]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 113
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: periodicity in [/var/www/MISP/app/Model/Taxonomy.php, line 112]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 112
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: periodicity in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: periodicity in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: change-likelihood in [/var/www/MISP/app/Model/Taxonomy.php, line 112]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 112
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: change-likelihood in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: change-likelihood in [/var/www/MISP/app/Model/Taxonomy.php, line 115]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 115
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Undefined index: TaxonomyPredicate in [/var/www/MISP/app/Model/TaxonomyPredicate.php, line 32]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
TaxonomyPredicate::beforeValidate() - APP/Model/TaxonomyPredicate.php, line 32
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 242
ModelValidator::_triggerBeforeValidate() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 454
ModelValidator::errors() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 242
ModelValidator::validates() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 99
Model::validates() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3502
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 134
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
ModelValidator::validateMany() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 211
Model::validateMany() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2413
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 162
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
Model::saveAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2463
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 119
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-09-21 09:01:29 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/TaxonomyPredicate.php, line 32]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
TaxonomyPredicate::beforeValidate() - APP/Model/TaxonomyPredicate.php, line 32
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 242
ModelValidator::_triggerBeforeValidate() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 454
ModelValidator::errors() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 242
ModelValidator::validates() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 99
Model::validates() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3502
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 134
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
ModelValidator::validateMany() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 211
Model::validateMany() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2413
ModelValidator::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 162
Model::validateAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2659
Model::saveAssociated() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 2463
Taxonomy::__updateVocab() - APP/Model/Taxonomy.php, line 119
Taxonomy::update() - APP/Model/Taxonomy.php, line 80
TaxonomiesController::update() - APP/Controller/TaxonomiesController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by iglocska** [comment]
Do you run any custom taxonomies?

**Comment by Turecky** [comment]
No

**Comment by Turecky** [comment]
I just try to write in debug log in `foreach` loop at `Model/Taxonomy.php` 112 line. I Skip the previous posted error messages 
```
2020-09-30 08:03:03 Debug: {"predicate":"confidence","entry":[{"value":"High","expanded":"High confidence"},{"value":"Low","expanded":"Low confidence"},{"value":"Medium","expanded":"Medium confidence"}]}
2020-09-30 08:03:03 Debug: XXXXXXXXXXXXXXXXXXXXX
2020-09-30 08:03:03 Notice: Notice (8): Undefined index: confidence in [/var/www/MISP/app/Model/Taxonomy.php, line 114]
...
2020-09-30 08:03:03 Debug: {"predicate":"periodicity","entry":[{"value":"hourly","expanded":"This attribute is likely to happen at an hourly interval"},{"value":"daily","expanded":"This attribute is likely to happen at a daily interval"},{"value":"weekly","expanded":"This attribute is likely to happen at a weekly interval"},{"value":"monthly","expanded":"This attribute is likely to happen at a monthly interval"},{"value":"yearly","expanded":"This attribute is likely to happen at a yearly interval"}]}
2020-09-30 08:03:03 Debug: XXXXXXXXXXXXXXXXXXXXX
2020-09-30 08:03:03 Notice: Notice (8): Undefined index: periodicity in [/var/www/MISP/app/Model/Taxonomy.php, line 114]
...
2020-09-30 08:03:03 Debug: {"predicate":"change-likelihood","entry":[{"value":"low","expanded":"Low change probability"},{"value":"medium","expanded":"Medium change probability"},{"value":"high","expanded":"High change probability"},{"value":"unknown","expanded":"Unknown change probability"}]}
2020-09-30 08:03:03 Debug: XXXXXXXXXXXXXXXXXXXXX
2020-09-30 08:03:03 Notice: Notice (8): Undefined index: change-likelihood in [/var/www/MISP/app/Model/Taxonomy.php, line 114]

```
Lines with `XXXXXXXXXXXXXXXXXXXXX` is next line after writing to debug log. I convert `$value` to JSON

**Comment by Turecky** [comment]
And data at line for `TaxonomyPredicate` error
```
2020-09-30 11:07:53 Debug: {"TaxonomyEntry":[
{"value":"High","expanded":"High confidence"},
{"value":"Low","expanded":"Low confidence"},
{"value":"Medium","expanded":"Medium confidence"},
{"value":"hourly","expanded":"This attribute is likely to happen at an hourly interval"},
{"value":"daily","expanded":"This attribute is likely to happen at a daily interval"},
{"value":"weekly","expanded":"This attribute is likely to happen at a weekly interval"},
{"value":"monthly","expanded":"This attribute is likely to happen at a monthly interval"},
{"value":"yearly","expanded":"This attribute is likely to happen at a yearly interval"},
{"value":"low","expanded":"Low change probability"},
{"value":"medium","expanded":"Medium change probability"},
{"value":"high","expanded":"High change probability"},
{"value":"unknown","expanded":"Unknown change probability"}]}
2020-09-30 11:07:53 Debug: YYYYYYYYYYYYYYYYYYYYYYY
2020-09-30 11:07:53 Notice: Notice (8): Undefined index: TaxonomyPredicate in [/var/www/MISP/app/Model/TaxonomyPredicate.php, line 32]
```

**Comment by mokaddem** [comment]
Hey @Turecky I can't reproduce the error you are experiencing. Would you mind:
- Making sure your taxonomy repository is pointing to the correct HEAD
- Making sure no modification has been done on the taxonomies' JSON by running a `git status`

Thanks!

**Comment by Turecky** [comment]
Hey @mokaddem Looks like taxonomy HEAD was the problem. As new install with old db i do not have to go to update from CLI. Now i update from web admin. But some stuff are ignored. Thanks for pointing ;)

In admin panel Diagnostic section all submodels was with status OK

**Comment by mokaddem** [comment]
So everything is resolved?
