### ISSUE TITLE
Warning list update error

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#6365]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04.1
| OS version (client)       | Ubuntu 20.04.1
| PHP version               | 7.4.3
| MISP version / git hash   | v2.4.132 (92fab26172b27e514f07130179db7a8ea6dabfd4)
| Browser                   | Chrome

### Expected behavior
Update warning list
### Actual behavior
```
2020-09-30 12:35:35 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'warninglist_entry_count' doesn't have a default value
Request URL: /warninglists/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Warninglist.php(117): Model->save()
#6 /var/www/MISP/app/Model/Warninglist.php(71): Warninglist->__updateList()
#7 /var/www/MISP/app/Controller/WarninglistsController.php(44): Warninglist->update()
#8 [internal function]: WarninglistsController->update()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#13 {main}
```
### Steps to reproduce the behavior
Besof manual update database field default value:
```
MariaDB [misp]> describe warninglists;
+-------------------------+------------------+------+-----+---------+----------------+
| Field                   | Type             | Null | Key | Default | Extra          |
+-------------------------+------------------+------+-----+---------+----------------+
| id                      | int(11)          | NO   | PRI | NULL    | auto_increment |
| name                    | varchar(255)     | NO   |     | NULL    |                |
| type                    | varchar(255)     | NO   |     | string  |                |
| description             | text             | NO   |     | NULL    |                |
| version                 | int(11)          | NO   |     | 1       |                |
| enabled                 | tinyint(1)       | NO   |     | 0       |                |
| warninglist_entry_count | int(11) unsigned | YES  |     | NULL    |                |
+-------------------------+------------------+------+-----+---------+----------------+
```
Run alter table:
```
ALTER TABLE warninglists ALTER warninglist_entry_count SET DEFAULT 0;
```
After `SET DEFAULT` value warninglist update works. No errors in `error.log` or `debug.log`
But have error in `Administration -> Server Settings & Maintenace -> Diagnostics` section `Schema status` about `warninglist_entry_count` to must be `NULL` but have `0` as I set manualy to able update warning list

**Comment by mokaddem** [comment]
Thanks for the report. It's fixed with 28a05576a4bec0c82dbef07af8caf7af02fcde0c
