### ISSUE TITLE
Error during upgrade 2.4.132 -> 2.4.133

### ISSUE THREAD

**Issue by Airborne1974** [MISP/MISP#6476]
Hello,
this is my first issue with 3 MISP instance. I'm sorry if this looks trivial to somebody. I'd appreciate any help to proceed to successful upgrade to 2.4.133.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | CentOS
| PHP version               | 7.1
| MISP version / git hash   | 2.4.133
| Browser                   | Mozzila

### Support Questions
Hi,

I'd like to know how to fix this issue? No similar problem so far.

I started upgrade 2.4.132-> 2.4.133. 
During execution:
[xxxxxxx misp-modules]# sudo -u apache /var/www/MISP/venv/bin/pip install -I -U -r REQUIREMENTS

I got error at the end even setuptools (50.3.2) is installed:

Running setup.py develop for pymisp
    ERROR: Command errored out with exit status 1:
     command: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"'; __file__='"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /var/www/MISP/venv/src/pymisp/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
  Rolling back uninstall of pymisp
  Moving to /var/www/MISP/venv/lib/python3.6/site-packages/pymisp.egg-link
   from /tmp/pip-uninstall-3ylp4zoh/pymisp.egg-link
ERROR: Command errored out with exit status 1: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"'; __file__='"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

### Logs, screenshots, configuration dump, ...
[xxxx@XXXX misp-modules]# sudo -u apache /var/www/MISP/venv/bin/pip install -I -U -r REQUIREMENTS
Obtaining file:///usr/local/src/misp-modules (from -r REQUIREMENTS (line 2))
Obtaining pybgpranking from git+https://github.com/D4-project/BGP-Ranking.git/@fd9c0e03af9b61d4bf0b67ac73c7208a55178a54#egg=pybgpranking&subdirectory=client (from -r REQUIREMENTS (line 3))
  Skipping because already up-to-date.
Obtaining pyipasnhistory from git+https://github.com/D4-project/IPASN-History.git/@fc5e48608afc113e101ca6421bf693b7b9753f9e#egg=pyipasnhistory&subdirectory=client (from -r REQUIREMENTS (line 4))
  Skipping because already up-to-date.
Obtaining pyintel471 from git+https://github.com/MISP/PyIntel471.git@0df8d51f1c1425de66714b3a5a45edb69b8cc2fc#egg=pyintel471 (from -r REQUIREMENTS (line 5))
  Skipping because already up-to-date.
Obtaining pymisp[fileobjects,openioc,pdfexport,virustotal] from git+https://github.com/MISP/PyMISP.git@b5b40ae2c5225a4b349c26294cfc012309a61352#egg=pymisp[fileobjects,openioc,virustotal,pdfexport] (from -r REQUIREMENTS (line 6))
  Skipping because already up-to-date.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Obtaining uwhois from git+https://github.com/Rafiot/uwhoisd.git@411572840eba4c72dc321c549b36a54ed5cea9de#egg=uwhois&subdirectory=client (from -r REQUIREMENTS (line 7))
  Skipping because already up-to-date.
Obtaining odtreader from git+https://github.com/cartertemm/ODTReader.git/@49d6938693f6faa3ff09998f86dba551ae3a996b#egg=odtreader (from -r REQUIREMENTS (line 8))
  Skipping because already up-to-date.
Obtaining pydnstrails from git+https://github.com/sebdraven/pydnstrails@48c1f740025c51289f43a24863d1845ff12fd21a#egg=pydnstrails (from -r REQUIREMENTS (line 9))
  Skipping because already up-to-date.
Obtaining pyonyphe from git+https://github.com/sebdraven/pyonyphe@1ce15581beebb13e841193a08a2eb6f967855fcb#egg=pyonyphe (from -r REQUIREMENTS (line 10))
  Skipping because already up-to-date.
Obtaining pyfaup from git+https://github.com/stricaud/faup.git#egg=pyfaup&subdirectory=src/lib/bindings/python (from -r REQUIREMENTS (line 11))
  Updating /var/www/MISP/venv/src/pyfaup clone
Collecting aiohttp==3.4.4
  Using cached aiohttp-3.4.4-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
Processing /usr/share/httpd/.cache/pip/wheels/a8/04/35/9449686f1c26ff16f6224dc942e108329f3782185802ec6b93/antlr4_python3_runtime-4.8-py3-none-any.whl
Collecting apiosintds==1.8.3
  Using cached apiosintDS-1.8.3-py3-none-any.whl (13 kB)
Collecting argparse==1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting assemblyline-client==3.7.3
  Using cached assemblyline_client-3.7.3-py2.py3-none-any.whl (16 kB)
Collecting async-timeout==3.0.1
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs==19.3.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting backscatter==0.2.4
  Using cached backscatter-0.2.4-py3-none-any.whl (11 kB)
Collecting beautifulsoup4==4.8.2
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Processing /usr/share/httpd/.cache/pip/wheels/6e/d9/4f/65e76bdafa4f3a950c679c9d999664c604b33077b0a9d014e8/blockchain-1.4.4-cp36-none-any.whl
Processing /usr/share/httpd/.cache/pip/wheels/b0/da/c6/3b1faa8e1e45a9b1e1563de70013f39cc119f79a44e9c57e7e/censys-0.0.8-py3-none-any.whl
Collecting certifi==2019.11.28
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting cffi==1.14.0
  Using cached cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (399 kB)
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting click-plugins==1.1.1
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting click==7.1.1
  Using cached click-7.1.1-py2.py3-none-any.whl (82 kB)
Collecting colorama==0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting cryptography==2.8
  Using cached cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl (2.3 MB)
Collecting decorator==4.4.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting deprecated==1.2.7
  Using cached Deprecated-1.2.7-py2.py3-none-any.whl (8.3 kB)
Collecting dnspython==1.16.0
  Using cached dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
Processing /usr/share/httpd/.cache/pip/wheels/75/43/7e/c9a6f13b1140cfa5ffdddc1c436ddf5b4560da0a212e74a8f3/domaintools_api-0.3.3-py2.py3-none-any.whl
Collecting enum-compat==0.0.3
  Using cached enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Processing /usr/share/httpd/.cache/pip/wheels/dc/e8/6b/3d5ff5a3efd7b5338d1e173ac981771e2628ceb2f7866d49ad/ez_setup-0.9-cp36-none-any.whl
Processing /usr/share/httpd/.cache/pip/wheels/c9/6c/f9/107d39d45441980bf273757eba003ef057c6193c9d7650fac7/ezodf-0.3.2-py2.py3-none-any.whl
Processing /usr/share/httpd/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94/future-0.18.2-py3-none-any.whl
Collecting futures==3.1.1
  Using cached futures-3.1.1-py3-none-any.whl (2.8 kB)
Collecting geoip2==3.0.0
  Using cached geoip2-3.0.0-py2.py3-none-any.whl (23 kB)
Collecting httplib2==0.17.0
  Using cached httplib2-0.17.0-py3-none-any.whl (95 kB)
Processing /usr/share/httpd/.cache/pip/wheels/d3/00/b3/32d613e19e08a739751dd6bf998cfed277728f8b2127ad4eb7/idna_ssl-1.1.0-cp36-none-any.whl
Collecting idna==2.9
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting importlib-metadata==1.6.0
  Using cached importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting isodate==0.6.0
  Using cached isodate-0.6.0-py2.py3-none-any.whl (45 kB)
Collecting jbxapi==3.4.0
  Using cached jbxapi-3.4.0-py2.py3-none-any.whl (13 kB)
Collecting jsonschema==3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting lief==0.10.1
  Using cached lief-0.10.1-cp36-cp36m-manylinux1_x86_64.whl (3.5 MB)
Collecting lxml==4.5.0
  Using cached lxml-4.5.0-cp36-cp36m-manylinux1_x86_64.whl (5.8 MB)
Collecting maclookup==1.0.3
  Using cached maclookup-1.0.3-py2.py3-none-any.whl (10 kB)
Processing /usr/share/httpd/.cache/pip/wheels/e8/74/a5/1f91545399ab5055993722d7b368372c36137b67a4418e3d53/maxminddb-1.5.2-py3-none-any.whl
Collecting multidict==4.7.5
  Using cached multidict-4.7.5-cp36-cp36m-manylinux1_x86_64.whl (148 kB)
Processing /usr/share/httpd/.cache/pip/wheels/2b/df/57/f40bef951382112d9c644b3ec6d713ceb200ea7c15c074de42/np-1.0.2-cp36-none-any.whl
Collecting numpy==1.18.2
  Using cached numpy-1.18.2-cp36-cp36m-manylinux1_x86_64.whl (20.2 MB)
Collecting oauth2==1.9.0.post1
  Using cached oauth2-1.9.0.post1-py2.py3-none-any.whl (25 kB)
Collecting opencv-python==4.2.0.32
  Using cached opencv_python-4.2.0.32-cp36-cp36m-manylinux1_x86_64.whl (28.2 MB)
Collecting pandas-ods-reader==0.0.7
  Using cached pandas_ods_reader-0.0.7-py3-none-any.whl (7.1 kB)
Collecting pandas==1.0.3
  Using cached pandas-1.0.3-cp36-cp36m-manylinux1_x86_64.whl (10.0 MB)
Collecting passivetotal==1.0.31
  Using cached passivetotal-1.0.31-py3-none-any.whl (23 kB)
Processing /usr/share/httpd/.cache/pip/wheels/b1/21/20/9935d41bc95fa05546c8a78162b408250bd4cb8653e11225b7/pdftotext-2.1.4-cp36-cp36m-linux_x86_64.whl
Collecting pillow==7.0.0
  Using cached Pillow-7.0.0-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
Collecting progressbar2==3.50.1
  Using cached progressbar2-3.50.1-py2.py3-none-any.whl (51 kB)
Processing /usr/share/httpd/.cache/pip/wheels/a1/d9/f2/b5620c01e9b3e858c6877b1045fda5b115cf7df6490f883382/psutil-5.7.0-cp36-cp36m-linux_x86_64.whl
Collecting pycparser==2.20
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pycryptodome==3.9.7
  Using cached pycryptodome-3.9.7-cp36-cp36m-manylinux1_x86_64.whl (13.7 MB)
Collecting pycryptodomex==3.9.7
  Using cached pycryptodomex-3.9.7-cp36-cp36m-manylinux1_x86_64.whl (13.7 MB)
Processing /usr/share/httpd/.cache/pip/wheels/16/66/c0/681236e825d657b57fe1322a44b382521f823f9be845bc12ee/pydeep-0.4-cp36-cp36m-linux_x86_64.whl
Processing /usr/share/httpd/.cache/pip/wheels/73/69/0e/04c9e08e43c2fbd38de1487e28fb3413faa5f15a20a0d0df5a/pyeupi-1.0-cp36-none-any.whl
Collecting pygeoip==0.3.2
  Using cached pygeoip-0.3.2-py2.py3-none-any.whl (20 kB)
Collecting pyopenssl==19.1.0
  Using cached pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
Collecting pyparsing==2.4.6
  Using cached pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
Collecting pypdns==1.5.1
  Using cached pypdns-1.5.1-py3-none-any.whl (4.4 kB)
Processing /usr/share/httpd/.cache/pip/wheels/92/ec/db/e094621b64a22f8a447d5f3c0a8e2cf0da5bb58bb58cf78247/pypssl-2.1-cp36-none-any.whl
Processing /usr/share/httpd/.cache/pip/wheels/d1/8a/1c/32ab9017418a2c64e4fbaf503c08648bed2f8eb311b869a464/pyrsistent-0.16.0-cp36-cp36m-linux_x86_64.whl
Processing /usr/share/httpd/.cache/pip/wheels/a0/7b/57/8529cc5be44564843b37775e5a0c8347ea5a5acfded4e2ca05/pytesseract-0.3.3-py2.py3-none-any.whl
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Processing /usr/share/httpd/.cache/pip/wheels/18/0b/a0/1dd62ff812c857c9e487f27d80d53d2b40531bec1acecfa47b/python_docx-0.8.10-cp36-none-any.whl
Collecting python-magic==0.4.15
  Using cached python_magic-0.4.15-py2.py3-none-any.whl (5.5 kB)
Processing /usr/share/httpd/.cache/pip/wheels/1f/1f/2c/29acca422b420a0b5210bd2cd7e9669804520d602d2462f20b/python_pptx-0.6.18-cp36-none-any.whl
Collecting python-utils==2.4.0
  Using cached python_utils-2.4.0-py2.py3-none-any.whl (12 kB)
Collecting pytz==2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Processing /usr/share/httpd/.cache/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc/PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl
Collecting pyzbar==0.1.8
  Using cached pyzbar-0.1.8-py2.py3-none-any.whl (28 kB)
Collecting pyzipper==0.3.1
  Using cached pyzipper-0.3.1-py2.py3-none-any.whl (160 kB)
Collecting rdflib==4.2.2
  Using cached rdflib-4.2.2-py3-none-any.whl (344 kB)
Collecting redis==3.4.1
  Using cached redis-3.4.1-py2.py3-none-any.whl (71 kB)
Collecting reportlab==3.5.42
  Using cached reportlab-3.5.42-cp36-cp36m-manylinux2010_x86_64.whl (2.6 MB)
Collecting requests-cache==0.5.2
  Using cached requests_cache-0.5.2-py2.py3-none-any.whl (22 kB)
Collecting requests[security]==2.23.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Processing /usr/share/httpd/.cache/pip/wheels/3c/d4/51/6b45a41c55c40752da01605c72818b66823f4f6963141c292d/shodan-1.22.0-py3-none-any.whl
Collecting sigmatools==0.16.0
  Using cached sigmatools-0.16.0-py3-none-any.whl (134 kB)
Collecting six==1.14.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Processing /usr/share/httpd/.cache/pip/wheels/6c/eb/4f/ff045b4365ae5801a0a9de14cc0d00075a1ae33348e75ec1ef/socketIO_client-0.5.6-py3-none-any.whl
Collecting soupsieve==2.0
  Using cached soupsieve-2.0-py2.py3-none-any.whl (32 kB)
Collecting sparqlwrapper==1.8.5
  Using cached SPARQLWrapper-1.8.5-py3-none-any.whl (26 kB)
Collecting stix2-patterns==1.3.0
  Using cached stix2_patterns-1.3.0-py2.py3-none-any.whl (68 kB)
Collecting tabulate==0.8.7
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Processing /usr/share/httpd/.cache/pip/wheels/37/a7/db/2d592e44029ef817f3ef63ea991db34191cebaef087a96f505/tornado-6.0.4-cp36-cp36m-linux_x86_64.whl
Processing /usr/share/httpd/.cache/pip/wheels/44/32/9c/2a9da8b3ca3bf2c19fc1996f8ccd96a28b4d91e6feb3517aac/trustar-0.3.28-py3-none-any.whl
Collecting url-normalize==1.4.1
  Using cached url_normalize-1.4.1-py2.py3-none-any.whl (12 kB)
Processing /usr/share/httpd/.cache/pip/wheels/95/3a/cf/a050fe42891cc87e8c0385bca41da8148a4cc8962fe5d5ff6f/urlarchiver-0.2-cp36-none-any.whl
Collecting urllib3==1.25.8
  Using cached urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
Processing /usr/share/httpd/.cache/pip/wheels/db/a8/6b/1d734a9707418ee486ef4834d017f7a275de70f18d6f8c8120/validators-0.14.0-py3-none-any.whl
Collecting vt-graph-api==1.0.1
  Using cached vt_graph_api-1.0.1-py3-none-any.whl (36 kB)
Collecting vulners==1.5.5
  Using cached vulners-1.5.5-py3-none-any.whl (27 kB)
Collecting wand==0.5.9
  Using cached Wand-0.5.9-py2.py3-none-any.whl (129 kB)
Collecting websocket-client==0.57.0
  Using cached websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Processing /usr/share/httpd/.cache/pip/wheels/32/42/7f/23cae9ff6ef66798d00dc5d659088e57dbba01566f6c60db63/wrapt-1.12.1-cp36-cp36m-linux_x86_64.whl
Collecting xlrd==1.2.0
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting xlsxwriter==1.2.8
  Using cached XlsxWriter-1.2.8-py2.py3-none-any.whl (141 kB)
Processing /usr/share/httpd/.cache/pip/wheels/3d/46/3f/f55d12978f06c6633eb3420d4cceea75f9757d6c2cb3e52251/yara_python-3.8.1-cp36-cp36m-linux_x86_64.whl
Collecting yarl==1.4.2
  Using cached yarl-1.4.2-cp36-cp36m-manylinux1_x86_64.whl (252 kB)
Collecting zipp==3.1.0
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Collecting netaddr
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting setuptools
  Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
Collecting configparser
  Using cached configparser-5.0.1-py3-none-any.whl (22 kB)
Collecting tzlocal
  Using cached tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Processing /usr/share/httpd/.cache/pip/wheels/8d/0b/ff/bbba4ab3cf81844c3f8d130f8c53d392e1224b9750a71f0485/unicodecsv-0.14.1-py3-none-any.whl
Collecting importlib-resources; python_version < "3.7"
  Using cached importlib_resources-3.0.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: certifi, idna, urllib3, chardet, six, pycparser, cffi, cryptography, pyopenssl, requests, pybgpranking, pyipasnhistory, pyintel471, python-dateutil, wrapt, deprecated, setuptools, pyrsistent, attrs, zipp, importlib-metadata, jsonschema, lief, pydeep, python-magic, soupsieve, beautifulsoup4, pillow, reportlab, decorator, validators, pymisp, uwhois, odtreader, pydnstrails, pyonyphe, pyfaup, multidict, idna-ssl, yarl, async-timeout, aiohttp, antlr4-python3-runtime, pytz, argparse, apiosintds, websocket-client, socketio-client, pycryptodome, assemblyline-client, tabulate, backscatter, future, enum-compat, blockchain, importlib-resources, netaddr, censys, click, click-plugins, colorama, dnspython, domaintools-api, ez-setup, ezodf, futures, maxminddb, geoip2, httplib2, isodate, pycryptodomex, pyzipper, jbxapi, lxml, maclookup, np, numpy, oauth2, opencv-python, pandas, pandas-ods-reader, passivetotal, pdftotext, python-utils, progressbar2, psutil, pyeupi, pygeoip, pyparsing, requests-cache, pypdns, pypssl, pytesseract, python-docx, xlsxwriter, python-pptx, pyyaml, pyzbar, rdflib, redis, shodan, sigmatools, sparqlwrapper, stix2-patterns, tornado, configparser, tzlocal, unicodecsv, trustar, url-normalize, urlarchiver, vt-graph-api, vulners, wand, xlrd, yara-python, misp-modules
  Attempting uninstall: pybgpranking
    Found existing installation: pybgpranking 0.1
    Uninstalling pybgpranking-0.1:
      Successfully uninstalled pybgpranking-0.1
  Running setup.py develop for pybgpranking
  Attempting uninstall: pyipasnhistory
    Found existing installation: pyipasnhistory 0.1
    Uninstalling pyipasnhistory-0.1:
      Successfully uninstalled pyipasnhistory-0.1
  Running setup.py develop for pyipasnhistory
  Attempting uninstall: pyintel471
    Found existing installation: pyintel471 0.1
    Uninstalling pyintel471-0.1:
      Successfully uninstalled pyintel471-0.1
  Running setup.py develop for pyintel471
  Attempting uninstall: pymisp
    Found existing installation: pymisp 2.4.123
    Uninstalling pymisp-2.4.123:
      Successfully uninstalled pymisp-2.4.123
  Running setup.py develop for pymisp
    ERROR: Command errored out with exit status 1:
     command: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"'; __file__='"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /var/www/MISP/venv/src/pymisp/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
  Rolling back uninstall of pymisp
  Moving to /var/www/MISP/venv/lib/python3.6/site-packages/pymisp.egg-link
   from /tmp/pip-uninstall-3ylp4zoh/pymisp.egg-link
ERROR: Command errored out with exit status 1: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"'; __file__='"'"'/var/www/MISP/venv/src/pymisp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
[xxxx@xxxx misp-modules]# 

[xxxxxx@xxxxxx misp-modules]# pip list
Package                Version
---------------------- ----------
antlr4-python3-runtime 4.8
certifi                2019.11.28
chardet                3.0.4
Click                  7.0
Flask                  1.1.2
geoip2                 3.0.0
idna                   2.9
itsdangerous           1.1.0
Jinja2                 2.11.1
MarkupSafe             1.1.1
maxminddb              1.5.2
phonenumbers           8.12.2
pip                    20.2.4
ply                    3.11
plyara                 2.0.3
pycountry              19.8.18
python-dateutil        2.8.1
pytz                   2019.3
pyzmq                  19.0.0
redis                  2.10.6
requests               2.23.0
setuptools             50.3.2
simplejson             3.17.0
six                    1.14.0
stix2                  1.4.0
stix2-patterns         1.3.0
urllib3                1.25.8
Werkzeug               1.0.0
zmq                    0.0.0

Thank you,
AB1974

**Comment by Rafiot** [comment]
Can you try to do a git pull in the `misp-modules` directory? This error is related to a new feature in the most recent version of pip and it should be fixed.
