### ISSUE TITLE
Not able to add PGP keys because every key is invalid

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#6575]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.133

### Expected behavior
MISP accepts PGP keys for users, if they're not expired.

### Actual behavior
Valid keys cannot be added to user objects, because MISP detects them as invalid. The underlying error is "No key found":

```
[Exception] No key found
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(325): GpgTool->validateGpgKey()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationRule.php(275): User->validateGpgkey()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationSet.php(135): CakeValidationRule->process()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(268): CakeValidationSet->validate()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(99): ModelValidator->errors()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3502): ModelValidator->validates()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1838): Model->validates()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#8 /var/www/MISP/app/Controller/UsersController.php(956): Model->save()
#9 [internal function]: UsersController->admin_edit()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#14 {main}
```

### Steps to reproduce the behavior
Add a valid pgp key.

### Logs, screenshots, configuration dump, ...
![Screenshot from 2020-11-11 08-46-46](https://user-images.githubusercontent.com/2846609/98783883-8ed43480-23fa-11eb-943a-f0998c9d8089.png)

**Comment by JakubOnderka** [comment]
Hello, can you provide PGP key that is not possible to import and GPG application version?

**Comment by 3c7** [comment]
After testing with various MISP instances, I get different results with the same GPG version (2.1.11) and I can't find out why. The servers have the same encryption related settings.

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFpxwC0BEAC0y1+w5/eEkDnCdk8qwIVu+qxceF+LEZkDDdG9WH1xrHUurN5H
S6ZHbrRz58CZnBEXMleEqag/ViEa1nriF1cNhpCpv2f8Q6jL5KYr328e2iXtQ3J5
JX7WfteejBtpbgzsPZVzcIEHn19KWUdDwWwEJ1cpBwWi+FmyXzMhHf/vjnuVTrlr
GPl9CXziHD0hPRh+EXok2SqfFGd8skmhsfQKn8EnoaDC6NBcpNRjLsF0FOa6XqLt
ILKZWZqNBc4dwrX7SlKGXRWR3Ayb64YPGnvrH1BJS2AgowGgsw9u4swJk9fDz9wp
WCsNB6oAfwU844IVHLUonODMNzfk59Xj9q1xZriiAZ0i221pRV29PrWRvE1ZuteV
oirhZ65YJE4bdAxhmTSYVzCgdexP7Du3uC4Pklqr+oj5krMrEwULTMaIvLb/LIaR
lMwTSVGJbxyc1B6QUQgV28/1KbC2RPxz6unM/Gkcrf9HUvLx5o8ATjp+LUI70ZHF
J/E7xJosoCehxphS8mo2qIVMmN6gUSt/cwWUGOG/TpgFALpSMLBbYCZHus+FBbrn
XyZ2Cvi9/Qq4RLf0xORKCDx/dHx/MBWxd4cTvW4xRvy1rfQ8gNMcxnnzmR/w+uG1
dhuZTZCgQKjz0d8cH3M4LMO7hYTMQW2VuiYuItJGojm8tBy8TUSyjryGIwARAQAB
tChOaWxzIEt1aG5lcnQgPE5pbHMuS3VobmVydEBjZXJ0LWJ1bmQuZGU+iQJUBBMB
CAA+AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAFiEEB/UOKhja3Pe7d4wA774R
MbWK/1EFAl430n0FCQeIeVAACgkQ774RMbWK/1H4vQ//eBaf6B3kQJPjdtvzNZkp
k7m/x3gVRCudW6d0qUDrw6KpRMmXODJppa+1jYuZM2FDyzysbrp9Hmx9XNAsYLT5
Rsn123E4fab0FEWTQB4G3MYlsCKfKFdU2V0joLGsjoxCggS0bw2DCRESOvH4amkK
BMb3r9Sb1hx2m8er7sEHk9jQqoKDg50ry+7r8aGvdS9n2qLLfHn9tOhZzaCK37eS
4mUPDG7+RUcn0otR05Ss6Hsj4jG216ccZWG8F4xpKYd5+h96IJhG1L7lbwtX5ag0
vGv6/mydDvNbU+5hbXL8IXxLsAPEPn0X5OEwHOAsK58lKKrWZFIKSV6ZQhAOphqF
Hd74QNXGy3rBF8H1g9ktpTabno0iY4UBDmHEYxTmrzcecM10+MqA1owzVVLP94ew
PAKAKtvwIOmolNRqzHodv30hXn+vzTkzGvss1SteG4xhQ3Bo4yha2PbE5iZjEq4o
/bZ0bn6UmlrPr4nGhqfkehdoUu0rG7YXaVklkWkik17UNSmmCOFMHfhGcEKEEUBb
ozQ7IFBmaC8HNFnDJO4dSi4ZffkExTd2zgqNHDiLMYNmL4mQAfju8YXF266VzWfB
TdwQVmzLQ02i5085lgAhzbppWjEZsKr85UwUfeou+4FTDNPfI5RZdi9zqZgQ+s07
bueirs2fbtQIhC2N3k0xZyKJAjMEEAEIAB0WIQTw5plk0QZ4eFyAmmE1kd1bMQPt
UAUCWnHAVwAKCRA1kd1bMQPtUCfaD/415enJXSu4LnebQj5VhP+n/sWFaGQD9lA5
Mu1Z+ykb2bbJ/miiCUEv0aUOtBGjSgxZ5o5+Vb+KAIewSZ0CAQCmFka/jPb4Sy8y
XWncXp7j7FvF4RqBvdBkJ+WmfDSMSXOdt8/JOhoFERjNt+QjE/esw2j4OVtkbP8a
AKwh4pYsdx04dkY43gxX+1/cGnFYLv0PiIkPBsEip3VmJq1PlXVxZAotJbh9VZRy
h0rHc4oV5iPnK6dklZlREq6/g9/FxGCZ3jAd406LBPy9VnvuTZwXvcPxh1DWiTch
lBOygCXmVBruJajd0EGPfMzOMXBeHTbRC/LfVN3Uww0D6QNvQlzhsnwdIfwJDisC
0MRa8O5APYEu40rVcXV+SfurlWARlmmOjCMj4ZRf/96bcZJVy7OGf76VMSf3Els4
eY3yYXZzAN57jq4SzQ1MDOqDGFJiouo85koFePwT2wcQMtDrjxq8im3cGL/gR6Mo
S/w0RMc2vtsr/s8iLNiMxH0B6V8AlbnIgIUZfhBCpgvUzuEevQ+NWrjShIBdqBPs
vlfU7dezti09YcwDE6rFumtKCEw4t8k20mbKSJKGDzDaP8BXEulc3NwlZbUjAFiB
AT1LeAT6lQRL9ZmAb1EVy8tWDDQCzllj6NEBT40dR5qQN9YVqP3NfEkHQRkYpHX9
umlTgJIlCokCHAQQAQgABgUCWnHAyQAKCRDjBDSJqwtKA2KdD/sHNmFwddg+9OAh
Owu1PhYSrQOvwL+7tdXzGDNDK80BBh57CzxtxF2NYtibwsavKkYQBQXvALIcYz97
Sbc1qZNvTpje1YPlq3rMmLmYFn89R7MQGRhcnAAH9P+0oYnjcfujLdUeMYmGFt3T
ptVso17TmFAHPxBvI9NtXqy8r1k0eAvts/3ktbP3RwWZGVkKxB1iMX5t6Hcwu7/o
OPadfJGmlWPP22moL+2lVM1Ksxs8zhCSf8vqHLSP/JXVHT5XH730TtMBCMdXrQeD
9g8tfaHUgOsNslSwe13+leZ7j0xnRMcal4ZqQd1KBuLNspxheNrPY1ukiEadPPws
oW77O9ITpM+BBESB800WSNR/qXVnbwAwJgVLlqUPe6iVwXTgz+CSOqto8zq+plkl
UTHdhBqMRuF+afDVSSpTARgYVf42tbAPMXXm8a80TArjsB6vYVARa440V3zNLjrX
HMGNqQAVzYmdKxfb9bGcSXd+xk9nUR4xQ9qxoW+TNBOc16QlfUfoM4rmte91sIio
ISvZLDmXY7DYlHfFq4Jq5Dgne6T/vEAHCcLXJE8YExyj/fAl7AtixSfrnHruB369
41thRrloeXSadrlqp02jxYUclEyMOXbfCSa/Mzuvp1G5OwyXwJ0GlcMarO5UBCNn
H/45SkfzdXTGz+G9UKIGrhsz9RaaA4kCVAQTAQgAPhYhBAf1DioY2tz3u3eMAO++
ETG1iv9RBQJaccAtAhsDBQkDwkiDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJ
EO++ETG1iv9RVO8P+wWu1GzydCdk5rhL6NMQKpoVMaiyDtv8v275DA7wT+ttBtLA
n2Qr3TxKSxdPyy+IvPAiRvWg40P9dejsUjx2CJqtsWJ+fAtl/Y+gaECwpVFH+Tdn
M7grE7zWiqXcwd4WPwodSpGDeSEOlILCmwispsQIbpXCWh6S9YEtp6TObN3RbAw5
ot5kqRr7riLYX8YBrPGzzrxaf5v1ILBDaW/5ZfPSR0hjVA4Um9M4h/kqqleaBSls
m3fksS9lwCzblj/RjKHXTcGdWrxbSv5Ylfo+kCM623U7YHnmz4xA15e7e2yO8CzB
3z/cL0XnVeA6J74hajaEUemz/NqP4n6r2LMG3HHknzN8sWwlGDRDSTkwk0vOyteK
lyUzXw6RHJR/doZUE9fFEi7yBabmfUYSFr9TD3ALG2wQd0ETD3YftGZTIggHq7DT
Ump06pfS4auj9htuyrByWzB6CPJhNJMsK0EQ3rKRD2Zdi3S9Y78YYBaorS4JCpLY
EQvMlaX7X+u7NKF74kAJn+BceQluUxDx/FY1VgK6y5PPD7gLuKqZeZPs/UzwkPvG
FF1p2ZGMPqdslfpIrfru0v3KwwA1Y2BTFXNHZqvD3TDF1afPMSjVCQVJ+xZpAej0
ek4hlIfa0oJqzOE6sFxoAb85g8o+GtNs1B8hweyTOhXopa9o7UHiJr5nmBviuQIN
BFpxwC0BEADENbor9pRkqxexxRdrEBgZJYKBwGtBvweHCvwdHcSgoaNEhf0NiIJy
Ksd6aDGkI1i1StvcNVhWk1dBnU1G5Y2nO8J+tR3Aq/B0gCoHEtPEouO1bzlAGP0R
nSv1ML5ma42UsU+UuHB1iz/S9zvpeO2ui69Zcq9Bc10l+Z4/SXVMb1lR/FVjDZD7
r4U6EBEhPnx+q40gS3nxup8yvZrb4q2sc5HtwY82Jwjjt6LAy3j4CfDDcan+OF2/
tbjQE1im4OzO3qUqCTutOJRiuR6SIOpjkBS/ELZs3CpMRKd8sIuIQlM8AsGyOBn2
YNo9L1OIqGZd2u2EnEATTwEEx9Jw/LL9IiPUOYwrFkU//ngVXb7CIWhppSAUp2jt
XaXBcqqF0+2HFy1gRi/v7AUwiJvkFM+UrFiGHjljZG316sMlUIqMM5mc4gib1lVt
mXbgQaQTxTrBEh+izZRC6N8176AulKEPYGidaqPmUcZszcH5hFMmFrFgcpdxuVot
nWgiPFpeU+ZatFReKYW7AgN+/C7mgbVF2Cz2hGTc4nmg0ikdWVMADLUDnKHihbtp
umyiKMnj+n+LnBAxFVIZarsDz7+vc6O1XcRxtU0olxmBajQg5p3InYqzGDinh/nA
14xH/C5QcxKlZwJTd4GvxqOKKreab8lrPXaRqTNBOwaA2So56fxkuQARAQABiQI8
BBgBCAAmAhsMFiEEB/UOKhja3Pe7d4wA774RMbWK/1EFAl430qwFCQeIeX8ACgkQ
774RMbWK/1EDzA/7BnRc9cwiLott8U40n+LOhlQXRfyVUSXIjaEQJiI9f6xgDFdW
QlxVraSIcnX31qVj3O6LQN4TkuOYVhXTyMmxRxHvdVxouXoOYlWwPpahAH8KhrI6
CZcfQ8V+zxT0dSKWDZJysSwLKMyrKvHh52e4Mp+Tg3igbIbz0Zej6SgtWutKAqt+
dUyO6hv2YykiCuii0qG2qmocwRsYwJV42Un26tHN+k2fNEqTSg4ROaxeuoc0PyYh
LHfoyPmP7WrjuUKU4Uv0uMKDAXvio0mVotdBQlvS9xHySDlGkoBvb+DQaOorYLeO
sUG2PGL3G+YkHGPEIRpZv/NbOkLT/aLUrirI9d49IirLEpZ2LZCuCSCpZzMLYk2G
XYAXpBYlsf/Xoyg4ctYypE2rPRWgkBfuD604StFe6stGxdoUaK57oW4emuoaqyb1
QNzEQy+/nJbPf28vH93OWssbEn0dR7XdZtvqaYTZN5wo95okqayea9d1ABxf2P3q
2lTTUJSHWwMrkhwjxZRbpXvwXHO1gZ8khfoQm7z3NeYQ9jWJCtQ22LkvN8DQ3p1+
AK63i/67oiQXgCuG3QSuDd054L8jh/R51bsAs6kM7+yYsGjRrpPNx5HIs7W3OyVc
gmIaJUXDRSkeCpoZU/N8rqFpVVtGWMJ4bgVaLVWLW7pRL5iGZi2lo2A4OR4=
=GylB
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by chrisinmtown** [comment]
For what it's worth, I used gpg (GnuPG) version 2.2.23 to export the public key (`gpg --armor  --export my-key-id`), uploaded the result to MISP version 2.4.133, and it was accepted just fine. Maybe when I generated mine I used too few bits, not sure, but my public key block is much shorter than the one you posted above.

**Comment by 3c7** [comment]
Because the above key is signed by other keys, it's bigger than the public key alone (edit: but that was just an example, it happens with other keys, too). Should definitely not be the problem. Still could not narrow down the issue...

**Comment by JakubOnderka** [comment]
Should be fixed by https://github.com/MISP/MISP/pull/6697. Can you please test it with that patch applied and reopen if it didn't help?

**Comment by 3c7** [comment]
Hey @JakubOnderka,

the commits indeed fix some of the issues. My key provided above can be used now. Unfortunately, there are still issues with another key, the output of the gpg binary seems empty:

```
2020-12-07 12:00:55 Notice: Exception during validating GPG key
[Crypt_GPG_Exception] Key data provided, but gpg process output could not be parsed: 
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/GpgTool.php(97): CryptGpgExtended->keyInfo()
#1 /var/www/MISP/app/Model/User.php(341): GpgTool->validateGpgKey()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationRule.php(275): User->validateGpgkey()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationSet.php(135): CakeValidationRule->process()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(268): CakeValidationSet->validate()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(99): ModelValidator->errors()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3502): ModelValidator->validates()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1838): Model->validates()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#9 /var/www/MISP/app/Controller/UsersController.php(982): Model->save()
#10 [internal function]: UsersController->admin_edit()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#15 {main}
```

Importing the key to my keyring e.g. does not throw any errors, so I assume the key is valid. Any idea how to debug this?

**Comment by JakubOnderka** [comment]
@3c7 What is your GPG version? 2.1.11 as you mention before?

**Comment by 3c7** [comment]
Yes, the environment hasn't changed (beside pulling the MISP repo).

**Comment by Nebojsa92** [comment]
Same issue here with MISP 2.4.173.
```
2023-07-11 14:27:41 Notice: Exception during validating GPG key
[Exception] Multiple keys found
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(380): GpgTool->validateGpgKey()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationRule.php(275): User->validateGpgkey()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationSet.php(135): CakeValidationRule->process()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(268): CakeValidationSet->validate()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(99): ModelValidator->errors()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3502): ModelValidator->validates()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1838): Model->validates()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#8 /var/www/MISP/app/Controller/UsersController.php(223): Model->save()
#9 [internal function]: UsersController->edit()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#14 {main}

```
