### ISSUE TITLE
An Internal Error Has Occurred. / Error: Failed to query module Export

### ISSUE THREAD

**Issue by steveise3** [MISP/MISP#6635]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu,
| OS version (client)       | Ubuntu 18.04.2 LTSphp
| PHP version               | PHP 7.4.9 (cli) (built: Aug  7 2020 14:29:36) ( NTS )
| MISP version / git hash   | On branch 2.4 Your branch is up-to-date with 'origin/2.4'

### Support Questions
I performed the latest update for MISP and after that i am receiving "An Internal Error Has Occurred."
My workers were dead before i perform the update. From an investigation i performed there must be an issue with MySQL Database and PHP

### Logs, screenshots, configuration dump, ...

misp@ubuntu:/var/www/MISP$ sudo -H -u www-data git status
On branch 2.4
Your branch is up-to-date with 'origin/2.4'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   PyMISP (modified content)
        modified:   app/Lib/cakephp (modified content)
        modified:   app/files/misp-objects (untracked content)
        modified:   app/files/noticelists (untracked content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        INSTALL/dependencies/
        app/Config/config.php.bk
        app/tmp/cached_exports/stix2/
        app/tmp/cached_exports/yara/
        app/webroot/.well-known/
        app/webroot/IP.json
        app/webroot/IPevents.txt
        app/webroot/domains.txt
        app/webroot/ev3nt5.json
        app/webroot/output.txt
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5_0
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5_1
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5_2
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5_3
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5_4
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5_5
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8def5_6
        docs/xINSTALL.debian9-postgresql.md~HEAD
        docs/xINSTALL.debian9-postgresql.md~HEAD_0
        docs/xINSTALL.debian9-postgresql.md~HEAD_1
        docs/xINSTALL.debian9-postgresql.md~HEAD_2
        docs/xINSTALL.debian9-postgresql.md~HEAD_3
        docs/xINSTALL.debian9-postgresql.md~HEAD_4
        docs/xINSTALL.debian9-postgresql.md~HEAD_5
        docs/xINSTALL.debian9-postgresql.md~HEAD_6
-----------------------------------------------------------------------------------------------------------------------------
misp@ubuntu:/var/www/MISP/app/Console$ sudo -u www-data ./cake Admin runUpdates
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#5 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(273): Model->schema()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#9 /var/www/MISP/app/Model/AppModel.php(55): Model->__construct()
#10 [internal function]: AppModel->__construct()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#12 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(269): ClassRegistry::init()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#16 /var/www/MISP/app/Model/AppModel.php(55): Model->__construct()
#17 /var/www/MISP/app/Model/Event.php(389): AppModel->__construct()
#18 [internal function]: Event->__construct()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): Shell->initialize()
#24 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#25 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run()
#26 {main}

-----------------------------------------------------------------------------------------------------------------------------

Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('auth_keys')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(2663): Model->schema()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1886): DboSource->fields(Object(AuthKey), 'AuthKey', '')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1377): DboSource->generateAssociationQuery(Object(User), Object(AuthKey), 'hasMany', 'AuthKey', Array, Array, true)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(User), Object(AuthKey), 'hasMany', 'AuthKey', Array, Array, true, Array, 0, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(User), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('count', Array)
#8 /var/www/MISP/app/Controller/UsersController.php(1245): Model->find('count')
#9 [internal function]: UsersController->login()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2020-11-23 11:08:51 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /

**Comment by steveise3** [comment]
Hi,

The Internal Error has been fixed!
There was an issue with Workers directory permissions.
However, from GUI the workers look dead and there is an issue preventing them to start.

Please have a look on this:

PHP Settings

PHP ini path:… /etc/php/7.2/apache2/php.ini
PHP Version (>7.4 recommended): 7.2.17-0ubuntu0.18.04.1 (Update highly recommended)
PHP CLI Version (>7.4 recommended): 7.4.9 (Up to date)

How can i change the PHP ini path in order for PHP Version to be the correct one?
