### ISSUE TITLE
Azure AD integration, stuck with [CakeException] Authentication adapter "AADAuthenticate" error

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#6641]
Hi,

Based on the code snippet from https://www.sipponen.com/archives/4024 I'd like to setup Azure Active Directory integration for authentication. The code seems to work properly, and you can query the AD-groups. This allows to have MISP access defined by AD groups.

Now, the hurdle is how to integrate this into MISP. As far as I can check, the customauth module isn't possible because I can't instruct AAD to include a custom header. LDAP auth is also not possible because that doesn't work with AAD.

1) In config.php in the array Security I added 
`'auth'=>array('AADAuth.AADAuthenticate')`
and included a dummy section to set configuration variables.

```
	'AADAuthenticate'  =>                      
  array(
    'test'         => 'REMOTE_USER',       
  ),
```

2) In bootstrap I added 
`CakePlugin::load('AADAuth');`

3) In MISP/app/Plugin/AADAuth/Controller/Component/Auth/AADAuthenticate.php I created a class
`	class AADAuthenticate extends BaseAuthenticate {`

Unfortunately this keeps throwing the error message "Authentication adapter "AADAuthenticate" was not found.".

```
2020-11-24 11:49:49 Error: [CakeException] Authentication adapter "AADAuthenticate" was not found.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(695): AuthComponent->constructAuthenticate()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
#2 /var/www/MISP/app/Controller/AppController.php(1175): AuthComponent->startup(Object(UsersController))
#3 /var/www/MISP/app/Controller/AppController.php(294): AppController->_loadAuthenticationPlugins()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

Do you have any suggestions where to look first? Feels like "close" ;-)

**Comment by cudeso** [comment]
Tried with adding a die() statement in the MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticate.php but no luck, seems as if the file isn't even loaded.

**Comment by cudeso** [comment]
Minor progress. 
Naming the file "AadAuthenticateAuthenticate.php" and class AadAuthenticateAuthenticate removes the error. Still have to work on the 'real' authentication part.

Adding: 
`echo $className;`
in constructAuthenticate() of app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php to find out how the call to the adapter call is done exactly.

**Comment by cudeso** [comment]
Further progress. Having passwordless login to MISP.

```
<?php

App::uses('BaseAuthenticate', 'Controller/Component/Auth');
App::uses('RandomTool', 'Tools');

if (session_status() == PHP_SESSION_NONE) {
	session_start();
}
session_regenerate_id();

class AadAuthenticateAuthenticate extends BaseAuthenticate {	

	public function __construct()
	{
		
	}

	public function authenticate(CakeRequest $request, CakeResponse $response)
	{
                // Insert AAD lookup code here
		$mispUsername = "admin@admin.test";
		$this->settings['fields'] = array('username' => 'email');
		$user = $this->_findUser($mispUsername);
		return $user;
	}

}

```
