### ISSUE TITLE
Unable to analyse file hashes via Cortex

### ISSUE THREAD

**Issue by BannersSecret** [MISP/MISP#6729]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2
| MISP version / git hash   | v2.4.134 (557c4f59e3df7b108cf6f4dabbe5ac7a0ee7efa2)
| Browser                   | Chrome

### Expected behavior

Submit a file hash for analysis via thehive/Cortex, which correlates with events in MISP.

### Actual behavior

When submitting the hash, I receive the following error:

Request headers:{'User-Agent': 'PyMISP 2.4.134 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'MISP-ba7f1640-8e16-48b3-8761-e21906a9d5a5=7mjnurnjj6nv6frhe2nvkh1q6b', 'Content-Length': '661', 'Authorization': '[REDACTED]', 'content-type': 'application/json'}Request body:{"returnFormat": "json", "value": "fd77b5dd0ca45d110a897d650e9fb146d4b4aae5", "type": ["md5", "sha1", "sha256", "ssdeep", "sha224", "sha384", "sha512", "sha512/224", "sha512/256", "tlsh", "authentihash", "filename|md5", "filename|sha1", "filename|sha256", "filename|ssdeep", "filename|sha224", "filename|sha384", "filename|sha512", "filename|sha512/224", "filename|sha512/256", "filename|tlsh", "filename|authentihash"], "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0}Response (if any):{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}Traceback (most recent call last):  File "/opt/Cortex-Analyzers/analyzers/MISP/misp.py", line 80, in <module>    MISPAnalyzer().run()  File "/opt/Cortex-Analyzers/analyzers/MISP/misp.py", line 60, in run    response = self.misp.search_hash(self.get_data())  File "/opt/Cortex-Analyzers/analyzers/MISP/mispclient.py", line 252, in search_hash    return self.__search(type_attribute=self.__misphashtypes(), value=searchterm)  File "/opt/Cortex-Analyzers/analyzers/MISP/mispclient.py", line 225, in __search    misp_response = connection.search(type_attribute=type_attribute, value=value)  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 2050, in search    normalized_response = self._check_json_response(response)  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 2943, in _check_json_response    r = self._check_response(response, expect_json=True)  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 2952, in _check_response    raise MISPServerError(f'Error code 500:\n{response.text}')pymisp.exceptions.MISPServerError: Error code 500:{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}

I am, however, able to successfully submit IPs and domains for analysis against MISP.

### Steps to reproduce the behavior

Add hash as an observable in thehive, then submit for analysis to MISP via Cortex.

**Comment by JakubOnderka** [comment]
Hello, can you check MISP error log? It should contain more information about the exception.

**Comment by BannersSecret** [comment]
Hi, this is what is appended to the error.log at /var/www/MISP/app/tmp/logs/ when I run the analyzer:

2020-12-10 13:14:57 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1616]
2020-12-10 13:14:57 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1616)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1616, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}


Thanks for your help.

**Comment by JakubOnderka** [comment]
For me it looks like bug in Cortext script, because it queries `/events/restSearch` endpoint, but the query looks like it should go to `/attributes/restSearch`. So I would recommend to you to open issue in https://github.com/TheHive-Project/Cortex-Analyzers repo.
