### ISSUE TITLE
Error messages using Postgres db instead of MariaDB

### ISSUE THREAD

**Issue by walkergregt** [MISP/MISP#6770]
I am required to use Postgres db Version 12.5 instead of MariaDB.  When trying to connect by doing the following:
(1) Enter username
(2) Enter password
(3) MISP accepts and then attempts to load the first page after login,
I get the following error messages:
"ERROR: invalid input syntax for type integer:""
LINE 1: ...("Job"."org_id" = "Org"."id") WHERE "Job"."id" = "  LIMI...

Request URL:/users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Dbosource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Dbosource.php(468): DboSource->_execute('SELECT "Job"."i...',Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Dbosource.php(715): DboSource->execute('SELECT "Job"."i...',Array,Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Dbosource.php(1226): DboSource->fetchAll('SELECT "Job"."i...'.Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Job),Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first',Array)
#6 /var/www/MISP/app/Model/AppModel.php(1867): Model->find('first',Array)
#7 /var/www/MISP/app/Controller/AppController.php(326): AppModel->runUpdates()
#8 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter(Object(CakeEvent))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}

Work environment: (1) OS: RHEL 7, (2) PHP: 7.2, (3) MISP 2.4.133, (4) Browser: Chrome.

**Comment by JakubOnderka** [comment]
Hello, what MISP version do you use? Because in latest version this should be already fixed.

**Comment by walkergregt** [comment]
MISP 2.4.133

**Comment by JakubOnderka** [comment]
So please try it again with v2.4.136.
