### ISSUE TITLE
Internal Server Error after MISP reboot

### ISSUE THREAD

**Issue by pietrogu** [MISP/MISP#6777]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.134

### Support Questions

After rebooting my working MISP server, an Internal Server Error appeared. 
In the logs the only information is about some problem related to Redis (redis-cli works).
 Seems similar to #5246
### Logs, screenshots, configuration dump, ...
In **error.log** there is this line repeated a large number of times:
`2020-12-18 16:40:33 Warning: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]`

In **resque-2020-12-18.log**
`[2020-12-18 16:40:28] main.INFO: CONT received; resuming job processing {"type":"resume","worker":"MISP-AzNe-01:2257"} []`
`[2020-12-18 16:40:28] main.INFO: Exiting... {"type":"shutdown","worker":"MISP-AzNe-01:2257"} []`
`[2020-12-18 16:40:28] main.INFO: CONT received; resuming job processing {"type":"resume","worker":"MISP-AzNe-01:2293"} []`
`[2020-12-18 16:40:28] main.INFO: Exiting... {"type":"shutdown","worker":"MISP-AzNe-01:2293"} []`
`[2020-12-18 16:40:28] main.INFO: CONT received; resuming job processing {"type":"resume","worker":"MISP-AzNe-01:2239"} []`
`[2020-12-18 16:40:28] main.INFO: Exiting... {"type":"shutdown","worker":"MISP-AzNe-01:2239"} []`
`[2020-12-18 16:40:28] main.INFO: CONT received; resuming job processing {"type":"resume","worker":"MISP-AzNe-01:2219"} []`
`[2020-12-18 16:40:28] main.INFO: Exiting... {"type":"shutdown","worker":"MISP-AzNe-01:2219"} []`
`[2020-12-18 16:40:28] main.INFO: CONT received; resuming job processing {"type":"resume","worker":"MISP-AzNe-01:2275"} []`
`[2020-12-18 16:40:28] main.INFO: Exiting... {"type":"shutdown","worker":"MISP-AzNe-01:2275"} []`
`[2020-12-18 16:41:05] main.INFO: Starting worker MISP-AzNe-01:2036:update {"type":"start","worker":"MISP-AzNe-01:2036:update"} []`

In **resque-scheduler-2020-12-18.log**:
`[2020-12-18 16:40:28] main.INFO: CONT received; resuming job processing {"type":"resume","worker":"MISP-AzNe-01:2311"} []`
`[2020-12-18 16:40:28] main.INFO: Exiting... {"type":"shutdown","worker":"MISP-AzNe-01:2311"} []`

In **resque-scheduler-error.log**:
`Error: read error on connection`
`#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem('workers', 'MISP-AzNe-01...')`
`#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()`
`#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work('3')`
`#3 {main}`

In **resque-worker-error.log**:
`Warning Error: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]`
`Error: Connection lost`
`#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem('workers', 'MISP-AzNe-01...')`
`#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(265): Resque_Worker->unregisterWorker()`
`#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')`
`#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('prio', 1, Object(MonologInit\MonologInit), '5')`
`#4 {main}`
`Error: LOADING Redis is loading the dataset in memory`
`#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(668): Redis->hSet('workerLogger', 'MISP-AzNe-01...', '["RotatingFile"...')`
`#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(107): Resque_Worker->registerLogger(Object(MonologInit\MonologInit))`
`#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')`
`#3 {main}`

**Comment by mokaddem** [comment]
It seems that your MISP instance is configured to use redis but the server is unreachable (connection refused).
Could you make sure that it is up and running?
Thanks
