### ISSUE TITLE
Uploading a file attachment with CJK characters fails

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#6801]
When uploading a file to a MISP event with Chinese, Japanese, Korean characters, strips the file name, thus losing the name of the file.

Rename any file to this for example, and upload to reproduce.

```
ヴァル井.txt
```

**Comment by chrisinmtown** [comment]
I see that a file attached via the GUI goes in as an attribute on the event, and the original file name is put into the attributes table, value1 column. That column seems to be defined in a way that *should* accept any properly encoded character:
```
  `value1` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
```
I tested against version 2.4.133, we use Python 3.6.  I created a file with an emoji in the name ("👍.jpg") and attempted to upload the file. The result was "The request has been blackholed". The error log shows this:
```
2021-01-05 20:16:05 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/add_attachment/204673
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(837): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(357): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(261): SecurityComponent->blackHole(Object(AttributesController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(AttributesController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

On a subsequent attempt, for what it's worth, I foolishly pasted the emoji character in the comment field also, that resulted in Internal Server Error, and the error log showed this:
```
2021-01-05 20:10:53 Error: [PDOException] SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x91\x8D' for column 'comment' at row 1
Request URL: /attributes/add_attachment/204673
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Attribute), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/AttributesController.php(441): Model->save(Array)
#6 [internal function]: AttributesController->add_attachment('204673')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```
This is a separate problem actually - the comment column is defined without a declaration of a charset:
```
  `comment` text COLLATE utf8_unicode_ci,
```
