### ISSUE TITLE
[stix2] Import failure

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#6807]
Currently: MISPv2.4.136 (fe00072164cde8728b72180d241085a37b70f1c7) 
Install Date: Jun 23  2020
Updated semi-frequently.
No DB Schema issues.

The following 2 test files:

https://gist.github.com/SteveClement/03d584be817739640ea0ea5cffe62f99

poisonivy.json -> Imports ok
apt1.json -> Internal server error:

```
2020-12-30 14:08:44 Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1
Request URL: /events/upload_stix/2
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Tag.php(348): Model->save()
#6 /var/www/MISP/app/Model/Event.php(3569): Tag->captureTag()
#7 /var/www/MISP/app/Model/Event.php(3848): Event->__captureObjects()
#8 /var/www/MISP/app/Model/Event.php(5921): Event->_add()
#9 /var/www/MISP/app/Controller/EventsController.php(2134): Event->upload_stix()
#10 [internal function]: EventsController->upload_stix()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#15 {main}
```

**Comment by SteveClement** [comment]
"fixed" with: https://github.com/MISP/MISP/commit/f7d5bc272bd457e5f216b9c5aea19ccb30b492b3

From Support:
```
Doubt anything is wrong with it, sounds like it includes a stix 2 label / marking that is too long for the constraints of the tag name field
pushed a brain-dead fix for it for now:
MISP/MISP@f7d5bc2
should hopefully fix it
in the future we should fix this properly by changing the tag name field's length
```

@iglocska @chrisr3d
