### ISSUE TITLE
[PHP8] Error: Unknown named parameter $subject

### ISSUE THREAD

**Issue by juju4** [MISP/MISP#6904]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu (github action)
| OS version (client)       | N/A
| PHP version               | 8
| MISP version / git hash   | 2.4 latest (and older)

### Expected behavior

Since Dec 14, my ansible MISP role CI was failing with above error when creating key with `cake userinit` in command-line.

I tried to revert MISP code to commit around this period but github CI is still failing
https://github.com/juju4/ansible-MISP/actions?query=branch%3Adevel-test

After troubleshooting, I identified this to a change of github image and php8 addition with its use as default.
https://github.com/actions/virtual-environments/commit/be672cb22cdc52323c0d46dc03903f8c3b8654ef#diff-8d528b68ca937dfe5a0194829f0eb2633bc3d7a3105a637ccb534a4da765f7a3R116

Forcing php7.4 resolves issues
Likely to add to https://github.com/MISP/MISP/pull/6666

### Actual behavior

https://github.com/juju4/ansible-MISP/runs/1754881981?check_suite_focus=true#step:7:15716
```
TASK [juju4.misp : generate key file - cake userInit] **************************
[...]
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "/var/www/_MISP/MISP/app/Console/cake userInit -q | tee /var/www/_MISP/MISP/.ht_key",
    "delta": "0:00:00.130790",
    "end": "2021-01-23 20:04:14.593162",
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "_raw_params": "/var/www/_MISP/MISP/app/Console/cake userInit -q | tee /var/www/_MISP/MISP/.ht_key",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2021-01-23 20:04:14.462372",
[...]
    "stderr_lines": [
        "Error: Unknown named parameter $subject",
        "#0 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger()",
        "#1 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3110): CakeEventManager->dispatch()",
        "#2 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3020): Model->buildQuery()",
        "#3 /var/www/_MISP/MISP/app/Model/User.php(230): Model->find()",
        "#4 [internal function]: User->__construct()",
        "#5 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()",
        "#6 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()",
        "#7 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()",
        "#8 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()",
        "#9 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): Shell->initialize()",
        "#10 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()",
        "#11 /var/www/_MISP/MISP/app/Console/cake.php(32): ShellDispatcher::run()",
        "#12 {main}"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

### Steps to reproduce the behavior

use php8

### Logs, screenshots, configuration dump, ...

Normal execution
https://github.com/juju4/ansible-MISP/runs/1548274184?check_suite_focus=true#step:7:15429

**Comment by JakubOnderka** [comment]
Thanks for report, but PHP8 is not supported yet.

**Comment by juju4** [comment]
I saw the PR, just highlighting an issue point.
If already identified, that's fine and issue can be closed

**Comment by chrisinmtown** [comment]
Hi CIRCL, the PHP8 issue is frequently mentioned at https://gitter.im/MISP/Support.  Seems to affect people who update their Ubuntu 20.04.  Perhaps Ubuntu 20.04 just upgraded to PHP version 8 recently?  I'm just asking, maybe this deserves some priority -- to show an error and/or simply don't start?

**Comment by iglocska** [comment]
Yeah looks like they have indeed. I'll add a banner so people are aware.

**Comment by iglocska** [comment]
I've pushed a warning, if you log in and the instance is running PHP8 you'll have an error banner telling the user. 

![image](https://user-images.githubusercontent.com/3668672/106137644-46135880-616b-11eb-9ded-93ebd73ee3f6.png)

**Comment by Rafiot** [comment]
Just making sure: if PHP8.0 is used, it will never fail before the user is logged in and reach the index?

**Comment by juju4** [comment]
sorry, missed above comment.

For me, on Ubuntu 22.04, install fails at composer components install
https://github.com/juju4/ansible-MISP/actions/runs/3165325387/jobs/5154264566#step:9:4554.
