### ISSUE TITLE
"Internal Server Error" when you propose an attachment

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#693]
Hello all, 

An error ("An Internal Error Has Occurred.") occures when I try to propose a attachment in a event :

1. Open a event
2. Click on Propose Attachment on the left
3. Select file and category 
4. Click Propose

My MISP version is 2.3.139. The Strack trace is the following:

```
2015-10-21 19:50:41 Error: Fatal Error (1): Call to a member function generateUuid() on a non-object in [/var/www/MISP/app/Controller/ShadowAttributesController.php, line 504]
2015-10-21 19:50:41 Error: [InternalErrorException] Internal Server Error
Request URL: /shadow_attributes/add_attachment/2541
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/MISP/a...', 504)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/MISP/a...', 504, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/MISP/a...', 504, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

**Comment by iglocska** [comment]
Thanks for the heads-up, just pushed a fix. Let me know if it still persists!

**Comment by devnull-** [comment]
I quickly tested and it's works.
Thank you for your reply and the patch :)

**Comment by iglocska** [comment]
My pleasure!
