### ISSUE TITLE
REST endpoint /feeds/add returns 500 if name property is missing

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6947]
Please make the endpoint /feeds/add more robust.  I am using MISP version 2.4.137 and ditto for PyMISP. While trying to add a feed using a dict I botched it, I omitted the name property.  The response was 500, internal server error.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137
| Browser                   | n/a

### Expected behavior

The /feeds/add endpoint recognizes that the request is incomplete and kicks back 400, bad request.

### Actual behavior

The database layer throws an error that name column is required, and the PHP app treats this as a fatal error, result to client is 500, internal server error.

### Steps to reproduce the behavior

Create a feed using a JSON object lacking the 'name' property.

### Logs, screenshots, configuration dump, ...

Here's the client response:
```
CRITICAL [api.py:3180 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.137.2 - Python 3.6', 'Accept-Encoding': 'br, gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'choclate-chip-cookie', 'Content-Length': '412', 'Authorization': 'authorization', 'content-type': 'application/json'}
Request body:
{"Feed": {"provider": "provider name", "url": "https://nowhere.mycompany.com", "rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]},\"url_params\":\"\"}", "source_format": "misp", "fixed_event": true, "delta_merge": false, "override_ids": false, "publish": false, "settings": {"csv": {"value": "", "delimiter": ","}, "common": {"excluderegex": ""}}, "default": false, "lookup_visible": false}}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/feeds\/add"}
```

Here's the server's error.log entry:
```
2021-02-02 15:37:53 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
Request URL: /feeds/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Feed), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/FeedsController.php(273): Model->save(Array)
#6 [internal function]: FeedsController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(FeedsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(FeedsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by JakubOnderka** [comment]
Fixed, thanks for report.
