### ISSUE TITLE
SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.GalaxyCluster.value'

### ISSUE THREAD

**Issue by jloehel** [MISP/MISP#7013]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| PHP version               | 7.4
| MISP version / git hash   | 2.4.138
| DB | mysqld 8.0.23

### Expected behavior
Successful import of a STIX 2.0 document

### Actual behavior
500 error

### Steps to reproduce the behavior
`https://misp.XXX/events` -> `Import from ...` -> `STIX format 2.0 (lossy)` -> `Select file` -> `click on upload`

### Logs, screenshots, configuration dump, ...
```
2021-02-16 02:05:19 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.GalaxyCluster.value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /events/upload_stix/2
Stack Trace:
#0 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `GalaxyC...', Array)
#2 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `GalaxyC...', Array, Array)
#3 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `GalaxyC...', Array)
#4 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(GalaxyCluster), Array)
#5 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP-2.4.138/app/Model/Event.php(5847): Model->find('all', Array)
#7 /var/www/MISP-2.4.138/app/Model/Event.php(5791): Event->__getTagNamesFromSynonyms('/var/www/MISP-2...')
#8 /var/www/MISP-2.4.138/app/Controller/EventsController.php(2101): Event->upload_stix(Array, '/var/www/MISP-2...', '3xAFqr4J1smR', 'STIX 2.0', 'fireeye-redteam...', '0')
#9 [internal function]: EventsController->upload_stix('2')
#10 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP-2.4.138/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

https://github.com/MISP/MISP/blob/54bd6e0951e6985342cacc5770628f762e602f99/app/Model/Event.php#L5846-L5855

**Comment by abhijeetasawant** [comment]
My observations:
Importing STIX2 file works perfectly fine on OVA setup (MARIA DB), but fails on docker setup (mysql).

**Comment by jloehel** [comment]
> My observations:
> Importing STIX2 file works perfectly fine on OVA setup (MARIA DB), but fails on docker setup (mysql).

Yes, these group by thingies are usually MySQL related, because it works with `only_full_group_by` which means that only strict ANSI SQL rules will be applied. This means that I can not use:
* 'GalaxyCluster.value', 
* 'GalaxyCluster.id'

in this query. One solution is to add these columns also to the group by.

**Comment by Ari-R** [comment]
I am having the same issue when using the "import from" button with a docker version of misp. What is the best way to fix this ?

**Comment by jloehel** [comment]
> I am having the same issue when using the "import from" button with a docker version of misp. What is the best way to fix this ?

In my opinion the query should work also if mysql is running in strict mode but you can fix it if you turn off the strict mode: https://github.com/docker-library/mysql/issues/149#issuecomment-353646309

**Comment by fukusuket** [comment]
###  Similar issue

I'm having the same issue. (on [misp-docker](https://github.com/MISP/misp-docker/tree/master) .. misp ver. 2.4.152)
Also, 'Event actions -> **Events with proposal**' has similar problem.  The error.log is as follows.

```
2022-01-30 10:41:55 Error: [PDOException] SQLSTATE[HY000]: General error: 3065 Expression #2 of ORDER BY clause is not in SELECT list, references column 'misp.ShadowAttribute.type' which is not in SELECT list; this is incompatible with DISTINCT
Request URL: /events/proposalEventIndex
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Controller/EventsController.php(3351): Model->find()
#7 [internal function]: EventsController->proposalEventIndex()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#12 {main}
```

###  Workaround
In my environment, these problems(STIX import, Events with proposal) were solved by executing the following mysql query.
```
bash-4.2# mysql -u root -p

.... (login mysql cli)

mysql > SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
```
Reference about sql_mode,'**ONLY_FULL_GROUP_BY**'

- [SQL Mode Changes in MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes)

**Comment by el-fabri** [comment]
> ### Workaround
> 
> In my environment, these problems(STIX import, Events with proposal) were solved by executing the following mysql query.
> 
> ```
> bash-4.2# mysql -u root -p
> 
> .... (login mysql cli)
> 
> mysql > SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
> ```

How can I make that change permanent? It seems that it needs to be done everytime you start MISP or restart the computer.

**Comment by fukusuket** [comment]
> How can I make that change permanent? It seems that it needs to be done everytime you start MISP or restart the computer.

If you want to change the sql_mode permanently, add the following text to the mysql config file(usually it’s in **/etc/my.cnf** or **/etc/mysql/my.cnf**) and restart mysqld.

```
[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
```
Then, you can permanently set the sql_mode(disable ONLY_FULL_GROUP_BY) even after restarting the OS (or mysqld).

See also:
- https://tableplus.com/blog/2018/08/mysql-how-to-turn-off-only-full-group-by.html
- https://stackoverflow.com/questions/23921117/disable-only-full-group-by
