### ISSUE TITLE
ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.event_id'

### ISSUE THREAD

**Issue by jloehel** [MISP/MISP#7014]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| PHP version               | 7.4
| MISP version / git hash   | 2.4.138
| DB | mysqld 8.0.23

### Expected behavior
Get attribute stats

### Actual behavior
500 error

### Steps to reproduce the behavior
~~~Python
stats = pymisp.attributes_statistics()
~~~

### Logs, screenshots, configuration dump, ...
```
2021-02-16 06:41:40 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.event_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /attributes/attributeStatistics/type
Stack Trace:
#0 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Attribute), Array)
#5 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP-2.4.138/app/Controller/AttributesController.php(2587): Model->find('all', Array)
#7 [internal function]: AttributesController->attributeStatistics('type')
#8 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#9 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP-2.4.138/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP-2.4.138/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

https://github.com/MISP/MISP/blob/54bd6e0951e6985342cacc5770628f762e602f99/app/Controller/AttributesController.php#L2584-L2588

**Comment by mokaddem** [comment]
Hello,
I couldn't reproduce the issue even when enforcing the `full_group_by` on mysql.
https://github.com/MISP/MISP/commit/2779077cbdbae33c913ee4fd8f6a52a20a898585 should fix the issue, but do not hesitate to come back if you spot something else.
Thanks for the report!

**Comment by jloehel** [comment]
@mokaddem Thanks for the fast response, the patch fixed it. :+1:
