### ISSUE TITLE
CIDR Warning lists produce error on APT1 report

### ISSUE THREAD

**Issue by cocaman** [MISP/MISP#7058]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04.2 LTS
| OS version (client)       | MacOS
| PHP version               | 7.4.15
| MISP version / git hash   | v2.4.139 (3228588921e032c1a7161af4a0906bee09ff6e51) 
| Browser                   | Chrome and Safari

### Expected behavior
Event is displayed, warning lists are used and for hits, displayed in the event view.

### Actual behavior
Error message thrown, event not displayed.

Disabling all warning lists for type "cidr" resolves the error and displays the event correctly.
Enabling *any* cidr list results in the same error message.

### Steps to reproduce the behavior
1) import APT1 STIX report from https://oasis-open.github.io/cti-documentation/stix/examples
2) browse the newly imported event
3) error displayed in browser: _Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator._
4) error displayed in logs: _[Error] Class 'CidrTool' not found_

### Logs, screenshots, configuration dump, ...
Error log details
```
2021-02-22 11:04:21 Error: [Error] Class 'CidrTool' not found
Request URL: /events/view/965
Stack Trace:
#0 /var/www/MISP/app/Model/Warninglist.php(454): Warninglist->getFilteredEntries()
#1 /var/www/MISP/app/Model/Warninglist.php(120): Warninglist->checkForWarning()
#2 /var/www/MISP/app/Model/Event.php(2206): Warninglist->attachWarninglistToAttributes()
#3 /var/www/MISP/app/Controller/EventsController.php(1577): Event->fetchEvent()
#4 [internal function]: EventsController->view()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(104): Dispatcher->dispatch()
#9 {main}
```

**Comment by cocaman** [comment]
adding `CidrTool.php` from https://github.com/MISP/MISP/blob/2.4/app/Lib/Tools/CidrTool.php fixed the warning.

**Comment by iglocska** [comment]
That is weird, I'm curious why you don't have that file there.

**Comment by cocaman** [comment]
Just checked my other MISP instance, it is also missing on that one.
v2.4.136 (f7d5bc272bd457e5f216b9c5aea19ccb30b492b3)

**Comment by StefanKelm** [comment]
https://github.com/MISP/MISP/pull/6114/files#diff-ca04d727d224f384993b7548b75b00e6a14c399a7d0eb25e759596127090aa3a

**Comment by iglocska** [comment]
This must have been reverted though, 

https://github.com/MISP/MISP/blob/2.4/app/Lib/Tools/CidrTool.php
