### ISSUE TITLE
ImportCSV module not found

### ISSUE THREAD

**Issue by maro584** [MISP/MISP#7124]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat, 7
| OS version (client)       | Win10
| PHP version               | 7.4
| MISP version / git hash   | 2.4.133, hash of the commit / 752a31d8ccd7d120010b3ac0b724da8a84f027f7

### Support Questions
When I am trying to use importCSV module in this way:
https://<fqdn>/events/importModule/csvimport/1272

I have got following error:
The modules system reports that it found no suitable modules

The misp-modules is installed:
[root@xxxx tmp]# find / -name misp-modules
/var/www/MISP/venv/bin/misp-modules
/usr/local/src/misp-modules

Also I have curl a misp-modules and got this:
curl -s http://127.0.0.1:6666/modules

{"name": "csvimport", "type": "import_mod", "mispattributes": {"userConfig": {"header": {"type": "String", "message": "Define the header of the csv file, with types (included in MISP attribute types or attribute fields) separated by commas.\nFor fields that do not match these types or that you want to skip, please use space or simply nothing between commas.\nFor instance: ip-src,domain, ,timestamp"}, "has_header": {"type": "Boolean", "message": "Tick this box ONLY if there is a header line, NOT COMMENTED, and all the fields of this header are respecting the recommendations above."}, "special_delimiter": {"type": "String", "message": "IF THE DELIMITERS ARE NOT COMMAS, please specify which ones are used (for instance: \";\", \"|\", \"/\", \"\t\" for tabs, etc)."}}, "inputSource": ["file"], "format": "misp_standard"}, "meta": {"version": "0.2", "author": "Christian Studer", "description": "Import Attributes from a csv file.", "module-type": ["import"], "config": []}}
### Logs, screenshots, configuration dump, ...

[root@xxxx tmp]# tail -f /var/www/MISP/app/tmp/logs/error.log

2021-03-02 13:22:57 Error: [MethodNotAllowedException] The modules system reports that it found no suitable modules.
Request URL: /events/importModule/csvimport/1272
Stack Trace:
#0 [internal function]: EventsController->importModule('The modules sys...', '1272')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by mokaddem** [comment]
Could you check that the csv module is detected by MISP and that it's enabled (`/servers/serverSettings/Plugin`)?

**Comment by maro584** [comment]
![csv_import_error](https://user-images.githubusercontent.com/34789307/112154045-300e9b00-8be4-11eb-9db0-6c920928f48c.PNG)

**Comment by maro584** [comment]
Yes it is enabled

**Comment by mokaddem** [comment]
I didn't manage to reproduce your issue, maybe it has been patched in the meantime.
Could you please make sure that your misp-module and your misp instance are updated to the latest version?
At least, we would look at the same code base.
Thanks!
