### ISSUE TITLE
Stix2 Import: Works only once

### ISSUE THREAD

**Issue by jloehel** [MISP/MISP#7185]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| PHP version               | 7.4
| MISP version / git hash   | 2.4.138
| Database | mysqld 8.0.23

### Expected behavior
Stix 2.x import works always

### Actual behavior
Stix 2.x import works only once

### Steps to reproduce the behavior
UI: Import file -> Delete event -> Import file again

### Logs, screenshots, configuration dump, ...
```
2021-03-10 06:26:48 Error: [PDOException] SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'event_id' at row 1
Request URL: /events/upload_stix/2
Stack Trace:
#0 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(MispObject), Array, Array)
#4 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP-2.4.139/app/Model/Event.php(7026): Model->save(Array)
#6 /var/www/MISP-2.4.139/app/Model/Event.php(5845): Event->add_original_file('{\n    "type": "...', '60471131be95ba6...', false, 'STIX 2.0')
#7 /var/www/MISP-2.4.139/app/Controller/EventsController.php(2104): Event->upload_stix(Array, '/var/www/MISP-2...', '34oLoaQp4TBu', 'STIX 2.0', '60471131be95ba6...', '0')
#8 [internal function]: EventsController->upload_stix('2')
#9 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP-2.4.139/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /var/www/MISP-2.4.139/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
```

**Comment by abhijeetasawant** [comment]
My observation is.
Once you delete the event - it gets added in blocklisted events. Then import fails. 
If you delete blocklisted event from blocklist then  it will get imported.

**Comment by iglocska** [comment]
Indeed, the uuid of the stix document is reused for the event uuid to be created. Deletions block-list the uuid as @abhijeetasawant correctly observed.

With that said the error needs to be cleaned up to indicate this.
