### ISSUE TITLE
Web UI's REST client page yields CSRF error on run query in 2.4.137

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7223]
Please tell me how to debug a CSRF failure seen when I try to use the web user interface REST client in version 2.4.137.  I open the page at a URL like https://misp.my-company.com:48752/servers/rest ; pick the templates drop-down, pick events then index; leave the HTTP headers and HTTP body textboxes unchanged from the suggestion; then click the Run query button. I always land at a page "You have tripped the cross-site request forgery protection of MISP."  The server's error log is below.
```
2021-03-18 19:52:11 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(ServersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(ServersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(ServersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug (maybe)
| OS version (server)       | RHEL
| OS version (client)       | MacOS (but probably not relevant)
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137
| Browser                   | Firefox (but probably not relevant)

### Expected behavior

the web UI's REST client interface yields results.

### Actual behavior

the web UI's REST client interface yields error.

 We've cleaned up our act with server certificates and I get the same result if I check (or uncheck) the box "Skip SSL validation". I don't sit on the REST client page for hours and hours, not even a few seconds, so the form/page token should be fresh.  I've tried both Firefox and Safari browsers with the same bad result.

When we last had this problem I had to modify SecurityComponent.php to log its inner secrets, that was awful. Is there a better way?

**Comment by chrisinmtown** [comment]
One particularly annoying nuance about our situation: we have a reverse proxy server listening on an odd port, that's the 48752 shown above.  The form with the REST client controls like the template list, the HTTP headers textbox and so on is served out to me and accepted back via that proxy server on that port.  Then to the best of my knowledge, upon receipt of that form, the server PHP code opens a new connection to itself directly on port 443 to run the query. I'm not 100% certain where/when the error happens -- I don't know if the server is accepting the REST client form contents or not, or whether I get to the next step, where the server contacts itself to run the query.

**Comment by chrisinmtown** [comment]
This is arguably a dupe of #6940 which I opened back in February.  I currently have no value set for server setting Security.rest_client_baseurl. Sorry about this.
