### ISSUE TITLE
SSL_CA configure on database.php 

### ISSUE THREAD

**Issue by torsolaso** [MISP/MISP#7232]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | latest

### Support Questions

Hi, I am testing the connection against a remote MYSQL in Azure and i'm having trouble specifying MISP to use the "ssl_ca" variable in the database.php configuration.

1. I can connect using SSL manually by using next command setting the cert in the argument:

` mysql -u <user> -p<pass> -h <ip> --ssl-ca=/etc/nginx/certs/myca.pem`

2. I create the certificate in the folder /var/www/MISP with www-data ownership and read permission.

`-rw-r--r-- 1 www-data www-data 1294 Dec  6  2017 /var/www/MISP/myca.pem`

3. Configure on app/Config/database.php 

```
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                //'datasource' => 'Database/Postgres',
                'persistent' => false,
                'host' => '<host>',
                'login' => '<user>',
                'port' => 3306, // MySQL & MariaDB
                //'port' => 5432, // PostgreSQL
                'password' => '<pass>',
                'database' => 'misp',
                'prefix' => '',
                'encoding' => 'utf8',
                'ssl_ca' => '/var/www/MISP/myca.pem',
        );
}
```

Am I doing something wrong? Is the use of SSL against MYSQL not supported?

### Error

But this configuration is not working. I think MISP is not using properly ssl_cert variable.

```
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource('default')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('logs')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(273): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('User', Array)
#10 /var/www/MISP/app/Model/AppModel.php(55): Model->__construct(NULL, NULL, NULL)
#11 /var/www/MISP/app/Model/User.php(227): AppModel->__construct()
#12 [internal function]: User->__construct(Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#14 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(269): ClassRegistry::init('User')
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(Event), Array)
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('Event', Array)
#18 /var/www/MISP/app/Model/AppModel.php(55): Model->__construct(NULL, NULL, 'default')
#19 /var/www/MISP/app/Model/Event.php(278): AppModel->__construct(Array, NULL, NULL)
#20 [internal function]: Event->__construct(Array)
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init('Event')
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel('Event')
#24 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#25 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): Shell->initialize()
#26 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#27 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#28 {main}


```

**Comment by torsolaso** [comment]
I am using as ssl_ca this cert

https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem

extracted from:
https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl

**Comment by torsolaso** [comment]
I got it changing a FLAG L178 on https://github.com/MISP/MISP/blob/8d9100b4a41c658d14956c7dd94ba3dd9c18ecbf/app/Model/Datasource/Database/MysqlExtendedLogging.php

```
                    if (!empty($config['ssl_ca'])) {​​​​​​​
                        $flags[PDO::MYSQL_ATTR_SSL_CA] = $config['ssl_ca'];
                        $flags[PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT ] = false;
                }​​​​​​​
 
```

Would it be possible to parameterize from the config to be able to use the flag?

**Comment by mokaddem** [comment]
Hello @torsolaso ,
Are you sure you are not turning off certificate verification by providing the following line?

` $flags[PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT ] = false;`

Because if it does, what's the point of using a certificate in the end?
Thanks

**Comment by torsolaso** [comment]
hi mokaddem,

this line disables the verification, but transmits the encrypted traffic over SSL. this is the sense. If not, the communication forces me to go in plain text. At this point, MISP is a client communicating against DB server. It happens same thing with flag `misp_verifycert = False` in PyMISP against MISP.

Thanks for answering

**Comment by mokaddem** [comment]
Hey, have you tried updating your `MISP/app/Config/database.php` and pass your `MYSQL_ATTR_SSL_VERIFY_SERVER_CERT` flag that way?
It would probably be easier than creating a new datasource
```php
<?php
  class DATABASE_CONFIG {
          public $default = array(
                  'datasource' => 'Database/Mysql',
                  'persistent' => false,
                  'host' => 'localhost',
                  'login' => 'misp',
                  'port' => 3306, // MySQL & MariaDB
                  'password' => '~pass~',
                  'database' => 'misp',
                  'prefix' => '',
                  'encoding' => 'utf8',
                  'flags' => array(
                      PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false
                  )
          );
  }
```

**Comment by torsolaso** [comment]
Thanks mokaddem with this config is working properly. Is the same result wihtout change the if clause. I close the issue
