### ISSUE TITLE
Configure whether repeated uses of the same invalid auth key yield repeated log entries

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7239]
**Describe the problem**

MISP 2.4.137 suppresses repeated API authkey auth_fail events - repeated uses of the same invalid auth key don't yield more log entries. See appcontroller 1556.

**Describe the solution you'd like**

We would like to use count of api auth_fail events in the log to detect a misconfigured system, a bad config file that needs to be updated. Hundreds (thousands) of attempts will get our attention. A single event will not.

To allow that, support configuration of whether log entries are suppressed for failed authkey events.

This issue arose from a discussion with @iglocska on gitter:

    https://gitter.im/MISP/Support?at=605b6cc9ac0fd631ca8bf16b

**Comment by iglocska** [comment]
Two issues here, one the described feature request, but also investigate why even individual entries might be omitted currently.

**Comment by chrisinmtown** [comment]
Re individual entries being omitted - I was trying to force an auth_fail into the system log by sending the wrong authkey in a PyMISP script.  Checking the time interval when I run the test, I see the logs table growing with various entries but never a single action=auth_fail.  I'll paste my test code below; it generates a date-time string for the authkey so that's guaranteed unique at each invocation.
```
#!/usr/bin/env python3
from datetime import datetime
import json
import urllib3
from pymisp import PyMISP

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
pymisp = PyMISP(
    url='https://misp.my-company.com:48752',
    key=f'{datetime.now()}',
    ssl=False)
print('Get orgs')
resp = pymisp.organisations(scope='all', pythonify=False)
if 'errors' in resp:
    raise Exception('failed: {}'.format(resp['errors']))
if len(resp) == 0:
    raise Exception('failed to get orgs')
for org in resp:
    pretty = json.dumps(org, indent=2)
    print(f'Org: {pretty}')
```
The output is pretty messy:
```
ERROR [api.py:3072 - _check_response() ] Something went wrong (403): {'name': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'message': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'url': '/servers/getPyMISPVersion.json'}
WARNING [api.py:132 - __init__() ] 403
ERROR [api.py:3072 - _check_response() ] Something went wrong (403): {'name': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'message': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'url': '/servers/getVersion'}
ERROR [api.py:3072 - _check_response() ] Something went wrong (403): {'name': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'message': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'url': '/users/view/me'}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.137-py3.6.egg/pymisp/api.py", line 149, in __init__
    self._current_user, self._current_role, self._current_user_settings = self.get_user(pythonify=True, expanded=True)
ValueError: not enough values to unpack (expected 3, got 1)
```
The server complains bitterly to its error.log file, maybe that explains why it does not log anything?
```
2021-03-24 17:44:52 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /servers/getPyMISPVersion.json
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(37): AppController->beforeFilter()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ServersController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2021-03-24 17:44:52 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /servers/getVersion
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(37): AppController->beforeFilter()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ServersController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2021-03-24 17:44:52 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /users/view/me
Stack Trace:
#0 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
```

**Comment by chrisinmtown** [comment]
@iglocska  maybe this is actually two separate issues - pls advise if you would like me to split into two.

**Comment by iglocska** [comment]
Yeah that is funky. Will have a look.

For the collapsing of multiple repeated entries there's a new setting that's going into the next release:

https://github.com/MISP/MISP/commit/5661adcf8fd4ca32ca559368c897bcc68ef2af70

**Comment by iglocska** [comment]
For the other issue, I've added an additional logging case, if no API key is provided and an API functionality is requested, it will no longer silently throw an exception, it will also log it to the audit logs:

https://github.com/MISP/MISP/commit/c7643515d6c8502371cf58caf419c2cd803ab1bc

**Comment by chrisinmtown** [comment]
I see the new code for the no-api-key case, thanks. What about the wrong-api-key case?  Is that handled by the same code?

**Comment by chrisinmtown** [comment]
We upgraded to 2.4.141 and I tested by running cURL to perform an API access with an invalid auth key. No entry appears in our audit log. Did this make it into that version?
