### ISSUE TITLE
Python 3.8 and PLyara modules error

### ISSUE THREAD

**Issue by silverem** [MISP/MISP#7312]
I tried to install plyara with python 3.8. I got the error:

 sudo /var/www/MISP/venv/bin/pip install plyara
Traceback (most recent call last):
  File "/var/www/MISP/venv/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 28, in <module>
    from pip._internal.models.target_python import TargetPython
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/models/target_python.py", line 3, in <module>
    from pip._internal.pep425tags import get_supported, version_info_to_nodot
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/pep425tags.py", line 7, in <module>
    from pip._vendor.packaging.tags import (
ModuleNotFoundError: No module named 'pip._vendor.packaging.tags'

Please help.
thanx

**Comment by Rafiot** [comment]
You probably need to upgrade pip in the virtualenv: `pip install -U pip` or `python -m pip install -U pip`. 

Also, you're not supposed to install things in the virtualenv as root (`sudo`...), it breaks the variables. You may want to reinstall the virtualenv completely because the perms are probably all over the place.

**Comment by silverem** [comment]
Ok i have deleted the venv and recreate it using www-data . All is ok . thank you
