### ISSUE TITLE
Redis connection refused

### ISSUE THREAD

**Issue by silverem** [MISP/MISP#7316]
hi all,
I got an issue with redis, i cannot connect to the redis database and when i visit /job, i got error: connection refused

 PHP extension version: 5.1.1
Redis is not available. Connection refused 

sudo -H -u www-data /var/www/MISP/app/Console/worker/start.sh
Error: Connection refused
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct()
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(77): Resque::redis()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(451): CakeResqueShell->startup()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run()

OS: ubuntu 20.0.4

**Comment by silverem** [comment]
How to uninstall redis and reinstall manually. i tried without success to follow the manual update of cakeResque, but no success

**Comment by chrisinmtown** [comment]
You did not mention what Linux version you are using.  We use RHEL, we install redis using an RPM named rh-redis5-redis, here's how to see what's installed:
```
(venv) [root@myhost ~]# rpm -qa | grep redis
python36u-redis-2.10.6-1.ius.centos7.noarch
rh-redis5-redis-5.0.5-1.el7.x86_64
rh-redis5-runtime-3.3-1.el7.x86_64
rh-redis5-3.3-1.el7.x86_64
```
Here's how I check the status of the redis server.:
```
(venv) [root@myhost ~]# systemctl status rh-redis5-redis
● rh-redis5-redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/rh-redis5-redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/rh-redis5-redis.service.d
           └─limit.conf
   Active: active (running) since Fri 2021-04-02 20:32:32 UTC; 5 days ago
  Process: 15602 ExecStop=/opt/rh/rh-redis5/root/usr/libexec/redis-shutdown (code=exited, status=0/SUCCESS)
 Main PID: 15652 (redis-server)
   CGroup: /system.slice/rh-redis5-redis.service
           └─15652 /opt/rh/rh-redis5/root/usr/bin/redis-server 127.0.0.1:6379

Apr 02 20:32:32 myhost systemd[1]: Starting Redis persistent key-value database...
Apr 02 20:32:32 myhost systemd[1]: Started Redis persistent key-value database.

**Comment by silverem** [comment]
5.4.0-70-generic x86_64
ubuntu 20.04

Normally redis-server is automatically installed and configured with cakeresque under MISP ?

```
more /var/www/MISP/app/tmp/logs/resque-scheduler-error.log
Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem('workers', 'sxbdvlmsp01:717...')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work('3')
#3 {main}
Warning Error: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]
Warning Error: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]
Warning Error: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]
```

and 

```
more /var/www/MISP/app/tmp/logs/resque-worker-error.log
Error: NOAUTH Authentication required.
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(108): Redis->select()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(668): Resque::redis()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(107): Resque_Worker->registerLogger()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
```

i have specified:

```
more /var/www/MISP/app/Plugin/CakeResque/Config/config.php

 'Redis' => array(
                'host' => '127.0.0.1',          // Redis server hostname
                'port' => 6379,                         // Redis server port
                'database' => 0,                        // Redis database number
                'namespace' => 'resque',        // Redis keys namespace
                'password' => 'xxxxxxxxxx'  
```

and 

`sudo -H -u www-data /var/www/MISP/app/Console/cake Admin setSetting "MISP.redis_password" "xxxxxxxxxxx"`

i restart:
```
su - www-data -s /bin/bash -c 'bash /var/www/MISP/app/Console/worker/start.sh'
Error: Connection refused
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct()
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(77): Resque::redis()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(451): CakeResqueShell->startup()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run()
#9 {main}

```

**Comment by silverem** [comment]
redis-server was not installed !
so i have start the server in background and it is working without password.
