### ISSUE TITLE
[RedisException] Connection refused (even though redis is working and is connected to MISP)

### ISSUE THREAD

**Issue by DISREL** [MISP/MISP#7325]
The error.log file from MISP/app/tmp/logs
```
2021-04-12 04:36:55 Error: [RedisException] Connection refused
Request URL: /feeds/fetchFromFeed/1
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(123): Resque::redis()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(76): Resque::push()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(169): Resque_Job::create()
#7 /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(140): Resque::enqueue()
#8 /var/www/MISP/app/Controller/FeedsController.php(472): CakeResque::enqueue()
#9 [internal function]: FeedsController->fetchFromFeed()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#14 {main}
```

Even though my Diagnostics page on MISP says that it's connected to redis, for no known reason.
![image](https://user-images.githubusercontent.com/69538721/114342961-81260500-9b7a-11eb-9537-353deeb72311.png)

My environment is basically https://github.com/coolacid/docker-misp

**Comment by DISREL** [comment]
The issue was not modifying the Redis host in /var/www/MISP/app/Plugin/CakeResque/Config/config.php

The workers were not starting because they couldn't contact the redis server, which caused the Internal Server Error in Feeds and Jobs UI of MISP.
