### ISSUE TITLE
Unable to generate co-relations | v2.4.142 | PHP 7.4 | Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by rishdang** [MISP/MISP#7370]
Have been unable to generate co-relations post upgrading to v2.4.142, the request is black-holed and Job is failed.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  Ubuntu 18.04.5 LTS
| OS version (client)       | Windows 10, Linux, All clients actually
| PHP version               | 7.4
| MISP version / git hash   | 2.4.142
| Browser                   | If applicable

### Expected behavior
co-relations should be generated.

### Actual behavior
Request is blackholed and Job is failed

### Steps to reproduce the behavior

- Login into MISP.
- MISP.completely_disable_correlation set to false
- Go to https://mispurl.com/pages/display/administration
- Click on "Recorrelate attributes"

`" Job queued. You can view the progress if you navigate to the active jobs view (administration -> jobs)."`

- Job Created, status failed.
- Also, somehow, now diagnostics page is not opening

### Logs, screenshots, configuration dump

What has been done - 
Followed steps mentioned here to no avail - 
https://www.circl.lu/doc/misp/faq/#how-can-i-deal-with-a-misp-instance-that-has-pulled-in-feeds-over-and-over-into-new-events-generating-hundreds-of-gbs-of-junk-correlations-rendering-the-instance-unusable

```
root@mispbed:/home/testuser# hostnamectl
   Static hostname: mispbed
         Icon name: computer-vm
           Chassis: vm
        Machine ID: XXX
           Boot ID: YYY
    Virtualization: kvm
  Operating System: Ubuntu 18.04.5 LTS
            Kernel: Linux 4.15.0-106-generic
      Architecture: x86-64
```
Details of redis 
```
root@mispbed:/home/testuser# cat /var/www/MISP/app/Config/config.php | grep 'Session\|redis'
    'redis_host' => 'localhost',
    'redis_port' => 6379,
    'redis_database' => 13,
    'redis_password' => '',
  'Session.defaults' => 'php',
  'Session.timeout' => '600',
  'Session.cookieTimeout' => 3600,
  'Session.autoRegenerate' => false,
  'Session.checkAgent' => false,
```
Details of PHP
```
root@mispbed:/home/testuser# cat /etc/php/7.4/apache2/php.ini | grep -v '\;' | grep session | head -n2
session.save_handler = redis
session.save_path = "tcp://localhost:6379"
```

Contents of error.log

```
2021-04-26 18:56:33 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/generateCorrelation
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#9 {main} 
```

contents of resque logs

```
[2021-04-26 18:58:03] main.INFO: got {"queue":"default","id":"a99cab576a971aff272fbc77424345e9","class":"AdminShell","args":[["jobGenerateCorrelation","98670"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"a99cab576a971aff272fbc77424345e9\",\"class\":\"AdminShell\",\"args\":[[\"jobGenerateCorrelation\",\"98670\"]]})","worker":"mispbed:1013"} []
[2021-04-26 18:58:03] main.INFO: Processing ID:a99cab576a971aff272fbc77424345e9 in default {"type":"process","worker":"mispbed:1013","job_id":"a99cab576a971aff272fbc77424345e9"} []
[2021-04-26 19:13:33] main.INFO: got {"queue":"default","id":"86f1ca1721ac6cb07a3f39713a597d39","class":"AdminShell","args":[["jobGenerateCorrelation","98671"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"86f1ca1721ac6cb07a3f39713a597d39\",\"class\":\"AdminShell\",\"args\":[[\"jobGenerateCorrelation\",\"98671\"]]})","worker":"mispbed:1013"} []
[2021-04-26 19:13:33] main.INFO: Processing ID:86f1ca1721ac6cb07a3f39713a597d39 in default {"type":"process","worker":"mispbed:1013","job_id":"86f1ca1721ac6cb07a3f39713a597d39"} []
[2021-04-26 19:24:03] main.INFO: got {"queue":"default","id":"a5a15fad977a59651fe293804cf8fa5b","class":"AdminShell","args":[["jobGenerateCorrelation","98672"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"a5a15fad977a59651fe293804cf8fa5b\",\"class\":\"AdminShell\",\"args\":[[\"jobGenerateCorrelation\",\"98672\"]]})","worker":"mispbed:1013"} []
[2021-04-26 19:24:03] main.INFO: Processing ID:a5a15fad977a59651fe293804cf8fa5b in default {"type":"process","worker":"mispbed:1013","job_id":"a5a15fad977a59651fe293804cf8fa5b"} []
[2021-04-26 19:31:33] main.INFO: got {"queue":"default","id":"af648563dffb0ef125b737aed88e792e","class":"AdminShell","args":[["jobGenerateCorrelation","98673"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"af648563dffb0ef125b737aed88e792e\",\"class\":\"AdminShell\",\"args\":[[\"jobGenerateCorrelation\",\"98673\"]]})","worker":"mispbed:1013"} []
[2021-04-26 19:31:33] main.INFO: Processing ID:af648563dffb0ef125b737aed88e792e in default {"type":"process","worker":"mispbed:1013","job_id":"af648563dffb0ef125b737aed88e792e"} []
```

**Comment by rishdang** [comment]
Hi Team,

Anything that I can provide to solve this.

Thanks, 
rish

**Comment by mokaddem** [comment]
Hi @rishdang ,
The issue with the diagnostic page has been fixed.
To re-enable (and re-create) the correlations, you can simply turn the setting `MISP.completely_disable_correlation` back to enabled. As stated in the description, it will trigger a full correlation.
Let us know if you have other issues.
Cheers!
