### ISSUE TITLE
MISP fails to import STIX files 

### ISSUE THREAD

**Issue by Kamforka** [MISP/MISP#7383]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.2
| MISP version  | 2.4.140

### Expected behavior

Expected error-free STIX imports.

### Actual behavior

Both v1.2 and v2.0 formatted files are failing import.

The v1.2 import failed with the below error:

```python
Traceback (most recent call last):
  File "/var/www/misp/app/files/scripts/stix2misp.py", line 1536, in <module>
    main(sys.argv)
  File "/var/www/misp/app/files/scripts/stix2misp.py", line 1527, in main
    title = event.stix_header.title
AttributeError: 'NoneType' object has no attribute 'title'
```

While the v2.0 failed with this:

```python
Traceback (most recent call last):
  File "/var/www/misp/app/files/scripts/stix2/stix2misp.py", line 2061, in <module>
    main(sys.argv)
  File "/var/www/misp/app/files/scripts/stix2/stix2misp.py", line 2053, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
TypeError: parse() got an unexpected keyword argument 'interoperability'
```

### Steps to reproduce the behavior

You can use these files to reproduce the issues:
[stix-exports.zip](https://github.com/MISP/MISP/files/6397353/stix-exports.zip)

**Comment by adulau** [comment]
@chrisr3d could you have a look?

**Comment by chrisr3d** [comment]
I just ran the import scripts with both of the STIX files and I did also found some issues.

First, thank you for reporting the issue about the STIX 1 file import, it should be fixed with 0ced4cb.

Concerning the STIX 2 file I noticed you got an issue because your MISP does not use the correct python library. In order to fix this I would recommend to execute the following instructions:
```
cd /var/www/MISP
sudo -H -u www-data git submodule update --init --recursive
cd /var/www/MISP/cti-python-stix2
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U .
```
You will not have the `TypeError: parse() got an unexpected keyword argument 'interoperability'` issue anymore, nonetheless there is another problem related to the file itself.

The datetime values (like `created`, `modified`, `valid_from` and `valid_until`) are raising an issue with the STIX2 python library when it tries to load the file.  
Those values should look like `2021-03-30T17:40:53.000Z` but they actually are like `2021-03-30T17:40:53+02:00`.  
The timezone indicator at the end of the date is not supported by the python library, and it should be expressed in utc format with a milliseconds precision, otherwise it will not be possible to load the file with any STIX 2 python library
