### ISSUE TITLE
My STIX 2 import is not working while any opensource is working.

### ISSUE THREAD

**Issue by TanveerAhmad2017** [MISP/MISP#7418]
## Please consider the following notes

--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (client)        Ubuntu20.4.2.
| PHP version               |7.4.3 
| MISP version / git hash   |  MISP 2.4.140 , 282a9c4
| Browser                   |firefox

### Support Questions
STIX2.1 Import is not working.I have searched similar threads of MISP but i am unable to fix this issue.
i know STIX 2 code is buggy but the Validator is verifying with success.
When I import the STIX from any opensource It is successfully imported but when I import any of my created sample STIX content(Indicator or Bundle) it throws error the error.
`Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool.`
Following is the log of exec-errors.log
`Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2061, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2055, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 80, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1180, in parse_event
    getattr(self, self._stix2misp_mapping[object_type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1209, in _parse_observable
    types = self._parse_observable_types(observable.objects)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/stix2/base.py", line 198, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" %
AttributeError: 'ObservedData' object has no attribute 'objects'
`
I have also updated my STIX2 using 
```
cd /var/www/MISP
git pull origin 2.4
git submodule update
cd cti-python-stix2/
/var/www/MISP/venv/bin/pip install .
```

Note: I have created STIX content using stix2 2.1.0 which I have download from https://pypi.org/project/stix2/ . The STIX2 validator also validate my content and no erroras shown below.
![image](https://user-images.githubusercontent.com/67195832/118797147-b7f7e500-b8b5-11eb-8eb1-c4a4a40e3074.png)
. I will also attach my STIX code here.
WHOLE BUNDLE STIX2 code.

`{
    "type": "bundle",
    "id": "bundle--9393d186-9eaa-4e0e-849c-e4a5ae08ac64",
    "objects": [
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--d6962c8c-7b0f-444b-bad2-2e23a2116d1c",
            "created": "2021-05-07T10:42:16.728169Z",
            "modified": "2021-05-07T10:42:16.728169Z",
            "name": "malicious ip address ",
            "description": "This iis malicious ip oberved on port 22",
            "indicator_types": [
                "malicious-activity"
            ],
            "pattern": "[ipv4-addr:value = '192.168.18.168']",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2021-05-07T10:42:16.728169Z"
        },
        {
            "type": "observed-data",
            "spec_version": "2.1",
            "id": "observed-data--01207cc1-48dc-498f-980b-95b55f45fa9c",
            "created": "2021-05-07T10:42:16.734212Z",
            "modified": "2021-05-07T10:42:16.734212Z",
            "first_observed": "2021-01-06T10:28:57.537257Z",
            "last_observed": "2021-02-06T10:28:57.537257Z",
            "number_observed": 18,
            "object_refs": [
                "ipv4-addr--a6128218-2062-5666-877e-8e1d713c3cc8"
            ]
        },
        {
            "type": "attack-pattern",
            "spec_version": "2.1",
            "id": "attack-pattern--57960456-4621-47e8-a865-357140c9aabd",
            "created": "2021-05-07T10:42:16.734067Z",
            "modified": "2021-05-07T10:42:16.734067Z",
            "name": "Credential Access Brute-force attack on SSH",
            "description": "Brute-force login attempts on port 22 to gain access",
            "kill_chain_phases": [
                {
                    "kill_chain_name": "mitre-att&ck-framework",
                    "phase_name": "credential-access-bruteforce"
                }
            ]
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--864e3803-e588-4a5f-a5aa-6aec78c43797",
            "created": "2021-05-07T10:42:16.734927Z",
            "modified": "2021-05-07T10:42:16.734927Z",
            "relationship_type": "based-on",
            "source_ref": "indicator--d6962c8c-7b0f-444b-bad2-2e23a2116d1c",
            "target_ref": "observed-data--01207cc1-48dc-498f-980b-95b55f45fa9c"
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--a690b7d4-f7e0-45cf-9b40-d6bfd8b0a538",
            "created": "2021-05-07T10:42:16.735037Z",
            "modified": "2021-05-07T10:42:16.735037Z",
            "relationship_type": "indicates",
            "source_ref": "indicator--d6962c8c-7b0f-444b-bad2-2e23a2116d1c",
            "target_ref": "attack-pattern--57960456-4621-47e8-a865-357140c9aabd"
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--bef0b207-286c-4e78-9712-84d237dd1772",
            "created": "2021-05-07T10:42:16.735129Z",
            "modified": "2021-05-07T10:42:16.735129Z",
            "relationship_type": "related-to",
            "source_ref": "observed-data--01207cc1-48dc-498f-980b-95b55f45fa9c",
            "target_ref": "ipv4-addr--a6128218-2062-5666-877e-8e1d713c3cc8"
        }
    ]
}
`
Single Indicator STIX2.
`{
    "type": "indicator",
    "spec_version": "2.1",
    "id": "indicator--e918a9ee-0b59-4de0-a817-e1322326acaa",
    "created": "2021-05-06T10:28:57.537257Z",
    "modified": "2021-05-06T10:28:57.537257Z",
    "name": "malicious ip address ",
    "description": "This iis malicious ip oberved on port 22",
    "indicator_types": ["malicious-activity"],
    "pattern": "[ipv4-addr:value = '192.168.18.168']",
    "pattern_type": "stix",
    "pattern_version": "2.1",
    "valid_from": "2021-05-06T10:28:57.537257Z"
}
`

Remarks: I have no idea what is wrong with my STIX and I will share the sample if required.

**Comment by iglocska** [comment]
The stix libraries are undergoing some heavy changes at the moment, could you update to the latest MISP version and test it again? If the issue persists on 2.4.143, let us know and we'll look into it asap.

**Comment by TanveerAhmad2017** [comment]
I have updated to the latest version  v2.4.143 (). and same issue persists.
attached image which shows MISP is updated.

![image](https://user-images.githubusercontent.com/67195832/118935140-a1f52d80-b964-11eb-94b1-800df5de7fc1.png)

**Comment by TanveerAhmad2017** [comment]
@iglocska soft reminder! no harsh :)

**Comment by TanveerAhmad2017** [comment]
@iglocska  I have figure out the problem by removing each objects one by one and checking where the problem initiates. The problem is in the Observed-data object. Some thing is not Allowing MISP to import the object_refs property. I tried to follow the documentation of STIX2.1 but the same error occurs so I tried go for STIX2.0(depreciated property) and it works.

Before causing problem.
```
"object_refs": [
                "ipv4-addr--a6128218-2062-5666-877e-8e1d713c3cc8"
            ]
```

After sucessful import 
`objects={
						  "0": {
                    "type": "ipv4-addr",
                    "value": "192.168.18.168",
                    "id": "ipv4-addr--a6128218-2062-5666-877e-8e1d713c3cc8",
                    
                },
						  }`
						  
						  
						 
![image](https://user-images.githubusercontent.com/67195832/119326975-ed2c7a80-bc9b-11eb-976c-f2cc3d2be41a.png)
![image](https://user-images.githubusercontent.com/67195832/119327053-00d7e100-bc9c-11eb-94f2-d06cd5abec2d.png)

**Comment by TanveerAhmad2017** [comment]
The problem is solved but it says the warning. I think some there need some improvements in MISP STIX libraries to incorporate the objects_ref property because the old method of objects will be deprecated.
 [!] Warning: observed-data--97b8cec8-92a6-4346-a6e4-889bba765056: {304} Included property 'objects' is deprecated within the indicated spec version.
 
 This thread will be opened till your response then it should be closed. Thanks

**Comment by chrisr3d** [comment]
Well, I don't know how the STIX 2.0 import script behaves with some STIX 2.1 content.
For sure it may barf with the observable objects like `ipv4-addr` since they are embedded within the observed-data `objects` field in STIX 2.0 as you mentioned in your comment.
But I am currently working on import & export scripts to support STIX 2.1, so you will know soon about it once it is released.

**Comment by eCrimeLabs** [comment]
I'm trying to upload a Stix2 file (https://www.cisa.gov/sites/default/files/STIX/MAR-10443863.r1.v1.CLEAR_stix2.json) but I'm getting an error:

```
Could not import STIX document: 'Malware' object has no attribute 'name' Please check whether the dependencies for STIX are met via the diagnostic tool.
``` 

I've also tried validating and it does give some warnings, but do not think that is the issue:

``` [!] Warning: indicator--d0200e3b-ff69-4aee-9bef-778824eddb18: {303} Both the name and description properties SHOULD be present.
    [!] Warning: indicator--b890bef3-aeab-4b01-b881-5869f280e8af: {303} Both the name and description properties SHOULD be present.
    [!] Warning: indicator--d13dc289-3617-4106-a1f6-155de28bdb28: {303} Both the name and description properties SHOULD be present.
```

When I call the stix2misp script from command line I get the following
```{"error": "'Malware' object has no attribute 'name'"}
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 52, in _process_stix_file
    parser.parse_stix_bundle()
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/stix2misp/stix2_to_misp.py", line 203, in parse_stix_bundle
    getattr(self, feature)()
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/stix2misp/stix2_to_misp.py", line 570, in _parse_bundle_with_single_report
    self._handle_object_refs(report.object_refs)
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/stix2misp/stix2_to_misp.py", line 457, in _handle_object_refs
    self._handle_object(object_type, object_ref)
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/stix2misp/stix2_to_misp.py", line 472, in _handle_object
    parser(object_ref)
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/stix2misp/external_stix2_to_misp.py", line 461, in _parse_malware
    self._clusters[malware_ref] = self._parse_galaxy(malware_ref)
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/stix2misp/external_stix2_to_misp.py", line 311, in _parse_galaxy
    return getattr(self, feature)(stix_object, object_type)
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/stix2misp/external_stix2_to_misp.py", line 330, in _parse_galaxy_as_tag_names
    name = stix_object.name
```

I'm running latest version [MISP 2.4.172]
