### ISSUE TITLE
Pull Jobs stuck completely

### ISSUE THREAD

**Issue by qbolbk59** [MISP/MISP#7426]
I recently connected to an external MISP and started pulling the events. However, the pull job is completely stuck since two days now after pulling just 3 events. I already tried the following:
1. Check PHP memory which is set to 2048M. So that looks ok (unless this must be increased even more)
2. Check the redis database but it shows "(empty list or set)"
3. Killed the worker responsible for the pull job, but still the job is stuck.

Not sure what else can be done to kill these stuck jobs and do a fresh pull. Any idea ?

**Comment by righel** [comment]
You can manage the workers via Admin console or API, via console:
```
/var/www/MISP/app/Console/cake Admin getWorkers
/var/www/MISP/app/Console/cake Admin restartWorkers
```

API endpoints that can be use to diagnose/handle the workers/background jobs:
```
GET MISP_HOST/servers/getWorkers
POST MISP_HOST/servers/stopWorker/[worker_pid]
POST MISP_HOST/servers/startWorker/[default|email|scheduler|cache|prio|update]
POST MISP_HOST/servers/restartDeadWorkers
POST MISP_HOST/servers/restartWorkers
POST MISP_HOST/servers/killAllWorkers
```
Sample call:
```
curl --location --request POST 'https://localhost/servers/restartWorkers' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: YOUR_API_KEY'

```

**Comment by qbolbk59** [comment]
> You can manage the workers via Admin console or API, via console:
> 
> ```
> /var/www/MISP/app/Console/cake Admin getWorkers
> /var/www/MISP/app/Console/cake Admin restartWorkers
> ```
> 
> API endpoints that can be use to diagnose/handle the workers/background jobs:
> 
> ```
> GET MISP_HOST/servers/getWorkers
> POST MISP_HOST/servers/stopWorker/[worker_pid]
> POST MISP_HOST/servers/startWorker/[default|email|scheduler|cache|prio|update]
> POST MISP_HOST/servers/restartDeadWorkers
> POST MISP_HOST/servers/restartWorkers
> POST MISP_HOST/servers/killAllWorkers
> ```
> 
> Sample call:
> 
> ```
> curl --location --request POST 'https://localhost/servers/restartWorkers' \
> --header 'Accept: application/json' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: YOUR_API_KEY'
> ```

Hi @righel : I did all these tasks. Killed all workers and restarted them. But the jobs are still stuck. I have to launch pull request multiple times and every time i do it, some events are pulled (but not all) and then it gets stuck again.

**Comment by qbolbk59** [comment]
![image](https://user-images.githubusercontent.com/43533246/119117814-e8609000-ba29-11eb-9478-6d7a0f78cfd0.png)

As you can see above, every time i pull, it pulls some event (but not all) and then just gets stuck. Not sure if it's because of some memory issue. Php has been allocated 2048M as recommended.

**Comment by righel** [comment]
Are you sure they are completely stuck? Do you see errors in the logs? Check:
/var/www/MISP/app/tmp/logs/error.log
/var/www/MISP/app/tmp/logs/resque-worker-error.log

The first pull from a server might take a lot of time depending on the amount of events and attributes, you can check if attributes are being added here refreshing this page https://MISP_HOST/attributes/index/sort:timestamp/direction:desc

**Comment by qbolbk59** [comment]
@righel : I don't see any error in the error.log related to the pull ops. There's some error related to CSP though but i know why's that.
In the resque-worker-error.log, i can see the below error. 

`2021-05-21 09:08:00 Notice: Undefined index: Organisation in [/app/MISP/app/Model/SharingGroup.php, line 148]
Notice Error: Trying to access array offset on value of type null in [/app/MISP/app/Model/SharingGroup.php, line 148]

2021-05-21 09:08:00 Notice: Trying to access array offset on value of type null in [/app/MISP/app/Model/SharingGroup.php, line 148]
Error: Argument 1 passed to Hash::combine() must be of the type array, string given, called in /app/MISP/app/Model/Server.php on line 721
#0 /app/MISP/app/Model/Server.php(721): Hash::combine()
#1 /app/MISP/app/Model/Server.php(1153): Server->getElligibleClusterIdsFromServerForPush()
#2 /app/MISP/app/Model/Event.php(4451): Server->syncGalaxyClusters()
#3 /app/MISP/app/Model/Event.php(4611): Event->uploadEventToServersRouter()
#4 /app/MISP/app/Model/Event.php(3916): Event->publish()
#5 /app/MISP/app/Model/Server.php(412): Event->_add()
#6 /app/MISP/app/Model/Server.php(460): Server->__checkIfPulledEventExistsAndAddOrUpdate()
#7 /app/MISP/app/Model/Server.php(530): Server->__pullEvent()
#8 /app/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#9 /app/MISP/app/Console/Command/AppShell.php(35): ServerShell->pull()
#10 /app/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#11 /app/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#12 /app/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#13 /app/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#14 /app/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#15 {main}`

I believe the jobs are indeed stuck as the first pull job that i did was yesterday and it's still stuck at 10% (same as yesterday). Also the status is always unknown.

**Comment by abhijeetasawant** [comment]
I have observed following error while pushing events (using Scheduled Tasks
) to another misp instance:

Error: Argument 1 passed to Hash::combine() must be of the type array, string given, called in /var/www/MISP/app/Model/Server.php on line 727
#0 /var/www/MISP/app/Model/Server.php(727): Hash::combine('Connection refu...', '{n}.GalaxyClust...', '{n}.GalaxyClust...')
#1 /var/www/MISP/app/Model/Server.php(1159): Server->getElligibleClusterIdsFromServerForPush(Array, NULL, Array, Array)
#2 /var/www/MISP/app/Model/Event.php(4473): Server->syncGalaxyClusters(Object(HttpSocketExtended), Array, Array, '26', Array)
#3 /var/www/MISP/app/Model/Event.php(4633): Event->uploadEventToServersRouter('26', NULL)
#4 /var/www/MISP/app/Console/Command/EventShell.php(330): Event->publish('26', NULL)
#5 /var/www/MISP/app/Console/Command/AppShell.php(35): EventShell->publish()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('prio', 1, Object(MonologInit\MonologInit), '5')
#11 {main}
Error: Argument 2 passed to Server::syncGalaxyClusters() must be of the type array, bool given, called in /var/www/MISP/app/Model/Server.php on line 960
#0 /var/www/MISP/app/Model/Server.php(960): Server->syncGalaxyClusters(Object(HttpSocketExtended), false, Array, 'full')
#1 /var/www/MISP/app/Console/Command/ServerShell.php(622): Server->push('2', 'full', '92', Object(HttpSocketExtended), Array)
#2 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->enqueuePush()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#8 {main}
