### ISSUE TITLE
[Support Request] STIX Lib Issues

### ISSUE THREAD

**Issue by geudrik** [MISP/MISP#744]
I know this isn't an issue of MISP directly, but I'm hoping that someone can point me in the right direction to resolving my STIX dependency issue.

In short, 1.1.1.4 refuses to install correctly, and 1.1.1.5 has a different failure. The latest versions of STIX and Cybox install correctly, but MISP appears to be incompatible (which was an assumed going down that path).

I'm running Ubuntu 14.04.3, `libxml2` is at 2.9.1

via `pip install 'stix==1.1.1.4'`, I get the following output.
```
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-aa2SQq-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
Storing debug log for failure in /root/.pip/pip.log
```

The pip.log is never created, so I can't review it.

When I attempt to upgrade/install stix as laid out in the MISP install procedures, I get the following error 
```
# python setup.py install
...
copying stix.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stix.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stix.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/stix-1.1.1.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing stix-1.1.1.4-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/stix-1.1.1.4-py2.7.egg
Copying stix-1.1.1.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing stix 1.1.1.5 from easy-install.pth file
Adding stix 1.1.1.4 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/stix-1.1.1.4-py2.7.egg
Processing dependencies for stix==1.1.1.4
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    "Operating System :: OS Independent",
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2277, in _dep_map
    for extra,reqs in split_sections(self._get_metadata(name)):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2715, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2305, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1369, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1361, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1425, in _get
    return self.loader.get_data(path)
```

More interestingly, I can install 1.1.1.4 in this manner if I use `python2.7`instead of just `python`. Someone tell me how this makes sense
```
root@neutron:/var/www/MISP/app/files/scripts/python-stix# python --version
Python 2.7.6
root@neutron:/var/www/MISP/app/files/scripts/python-stix# python2.7 --version
Python 2.7.6
root@neutron:/var/www/MISP/app/files/scripts/python-stix# ```

​[18:49] 
 ```root@neutron:/var/www/MISP/app/files/scripts/python-stix# python setup.py install
[FAIL]
root@neutron:/var/www/MISP/app/files/scripts/python-stix# python2.7 setup.py install
[Success]
```

Assuming a successful install via `python2.7 setup.py install`, when I attempt to import stix, I get the following
```
root@neutron:/var/www# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import stix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/stix/__init__.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/stix/base.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/stix/utils/__init__.py", line 342, in <module>
  File "build/bdist.linux-x86_64/egg/stix/utils/nsparser.py", line 309, in <module>
AttributeError: 'module' object has no attribute 'NS_LIST'
>>> 
```

Again, I know this isn't a bug with MISP directly, but I would love another/a few other sets of eyes looking at what I'm doing and for someone to tell me to stop :facepunch: myself

**Comment by Rafiot** [comment]
Which version of pip do you have? 
```
$  pip -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
```
`pip install stix==1.1.1.5 ` and `pip install stix==1.1.1.4 ` both work.

**Comment by geudrik** [comment]
Yep, `pip -V` gives me identical output. Neither of those install commands work for me, however, giving the above errors :cry:

**Comment by cvandeplas** [comment]
Don't you have a pip2.7 command available?( pip tab tab).
If yes, is installation of the correct STIX lib working with that binary?

If it is, then you might want to update-alternatives to change the default
Python and pip version.

**Comment by geudrik** [comment]
```
root@neutron:/var/www/MISP/app# pip
pip   pip2  pip3 
```

I'll try using `pip2` specifically and see if that resolves anything...

**Comment by geudrik** [comment]
Closing this issue. I scrubbed the box and started over. I deviated from the install procedure (which should really be updated and streamlined) to use pip and everything is working again.

**Comment by elhoim** [comment]
Could you document what you did differently by using pip so that we can use that to update the install procedure?

**Comment by geudrik** [comment]
I'll work on updating the install docs for ubuntu 14.04 and submit a PR. The most notable thing I did was tried to condense the use of various plugin/dependency managers to as few as possible
