### ISSUE TITLE
MISP Modules Not Working 

### ISSUE THREAD

**Issue by krishnamohan152** [MISP/MISP#7441]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu Server
| OS version (client)       | 18.04
| PHP version               |  7.1
| MISP version / git hash   | 2.4.142, hash of the commit
| Browser                   | Firefox, Chrome

## MISP Modules are not working in systemd, and working in command line
- I recently upgrade MISP from 2.4.136 to 2.4.142, After i am facing misp modules issue. 
- I tried to check and troubleshoot as per instruction in MISP github as such no luck was there
- Ironically the misp-modules is working in the commandline and when i am trying to run with systemd and i am getting following message like below

MISP Module System Status
-----------------------------

● misp-modules.service - MISP Modules service
   Loaded: loaded (/etc/systemd/system/misp-modules.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-05-25 15:58:27 IST; 2min 0s ago
 Main PID: 123033 (bash)
    Tasks: 17 (limit: 19660)
   CGroup: /system.slice/misp-modules.service
           ├─123033 /bin/bash /root/API/MISP/misp.sh
           └─123034 /usr/bin/python3 /usr/local/bin/misp-modules

May 25 15:58:29 HOST bash[123033]: 2021-05-25 15:58:29,219 - misp-modules - INFO - MISP modules threat_connect_export imported
May 25 15:58:29 HOST bash[123033]: INFO:misp-modules:MISP modules threat_connect_export imported
May 25 15:58:29 HOST bash[123033]: 2021-05-25 15:58:29,219 - misp-modules - INFO - MISP modules threatStream_misp_export imported
May 25 15:58:29 HOST bash[123033]: INFO:misp-modules:MISP modules threatStream_misp_export imported
May 25 15:58:29 HOST bash[123033]: 2021-05-25 15:58:29,220 - misp-modules - INFO - MISP modules cisco_firesight_manager_ACL_rule_export imported
May 25 15:58:29 HOST bash[123033]: INFO:misp-modules:MISP modules cisco_firesight_manager_ACL_rule_export imported
May 25 15:58:29 HOST bash[123033]: 2021-05-25 15:58:29,222 - misp-modules - INFO - MISP modules server started on localhost port 6666
May 25 15:58:29 HOST bash[123033]: INFO:misp-modules:MISP modules server started on localhost port 6666
May 25 15:58:52 HOST bash[123033]: WARNING:tornado.access:404 GET / (::1) 0.52ms
May 25 16:00:22 HOST bash[123033]: WARNING:tornado.access:404 GET / (::1) 0.51ms

# Logs of MISP Modules While performing the enrichment

May 25 16:03:58 HOST bash[123033]: During handling of the above exception, another exception occurred:
May 25 16:03:58 HOST bash[123033]: Traceback (most recent call last):
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
May 25 16:03:58 HOST bash[123033]:     timeout=timeout
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
May 25 16:03:58 HOST bash[123033]:     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 573, in increment
May 25 16:03:58 HOST bash[123033]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
May 25 16:03:58 HOST bash[123033]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report?resource=99a8e4a6cf99530640f0217c05b19967f139db3180ffe1bd5390e80eb7d8911a&apikey=key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2d011fe128>: Failed to establish a new connection: [Errno 111] Connection refused',))
May 25 16:03:58 HOST bash[123033]: During handling of the above exception, another exception occurred:
May 25 16:03:58 HOST bash[123033]: Traceback (most recent call last):
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/misp_modules/__init__.py", line 201, in post
May 25 16:03:58 HOST bash[123033]:     response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 762, in run
May 25 16:03:58 HOST bash[123033]:     value = future.result()
May 25 16:03:58 HOST bash[123033]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
May 25 16:03:58 HOST bash[123033]:     result = self.fn(*self.args, **self.kwargs)
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/misp_modules/__init__.py", line 189, in run_request
May 25 16:03:58 HOST bash[123033]:     response = mhandlers[x['module']].handler(q=jsonpayload)
May 25 16:03:58 HOST bash[123033]:   File "modules/expansion/virustotal_public.py", line 185, in handler
May 25 16:03:58 HOST bash[123033]:     query_result = parser.get_query_result(query_type)
May 25 16:03:58 HOST bash[123033]:   File "modules/expansion/virustotal_public.py", line 69, in get_query_result
May 25 16:03:58 HOST bash[123033]:     return requests.get(self.base_url, params=params)
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 76, in get
May 25 16:03:58 HOST bash[123033]:     return request('get', url, params=params, **kwargs)
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
May 25 16:03:58 HOST bash[123033]:     return session.request(method=method, url=url, **kwargs)
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 542, in request
May 25 16:03:58 HOST bash[123033]:     resp = self.send(prep, **send_kwargs)
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 655, in send
May 25 16:03:58 HOST bash[123033]:     r = adapter.send(request, **kwargs)
May 25 16:03:58 HOST bash[123033]:   File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
May 25 16:03:58 HOST bash[123033]:     raise ConnectionError(e, request=request)
May 25 16:03:58 HOST bash[123033]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report?resource=99a8e4a6cf99530640f0217c05b19967f139db3180ffe1bd5390e80eb7d8911a&apikey=key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2d011fe128>: Failed to establish a new connection: [Errno 111] Connection refused',))

# Troubshooting
[1]. After setting up the proxy and proxy is working fine
[2]. Check The Manual execution and enrichment is succesfully working and systemd level is not working
[3]. Base checks are also done and stilll systemd it is giving me connection refused
### Support Questions
Kindly suggest me the alternative to resolve the isssue

**Comment by mokaddem** [comment]
@krishnamohan152 Have you been able to resolve the your issue?
Based on the error log, it seems your misp-module (and probably the server) cannot reach the virustotal.com API.
