### ISSUE TITLE
Error: [MethodNotAllowedException] Could not remove tag as it is not attached to the target Event Request URL: /tags/removeTagFromObject

### ISSUE THREAD

**Issue by toteb** [MISP/MISP#7473]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |  CentOS
| OS version (client)       |  CentOS Linux 7 (Core) / Linux misp-core 3.10.0-1160.25.1.el7.x86_64
| PHP version               | PHP 7.4.19 (cli)
| MISP version / git hash   |  v2.4.143 (19aa7e23bf1014856e89c6bbdc98255dd75217ea)
| Browser                   | n/a

### Support Questions
Hi guys, probably this is a bit stupid but I have encountered following issue. I have added an autotag for events from few feeds. See screnshots below:
![Screenshot from 2021-06-05 10-32-44](https://user-images.githubusercontent.com/22633321/120884139-c8b09680-c5e9-11eb-8ea6-8922a0f4c0d4.png)
![Screenshot from 2021-06-05 10-33-23](https://user-images.githubusercontent.com/22633321/120884141-c9492d00-c5e9-11eb-9ece-2e4a3e0a49f2.png)

Till couple of days ago everything was working fine and when you go to Events, I was able to see all those events Tagged with Tag I've indicated. I am using PyMISP and python script which looks for specific tag in order to extract events in STIX format and then feed them into ESM. 

Here comes the strange part. I don't see events being tagged from "Events" tab in MISP, but all of thoose are still exported by the script I have which means there should be a tag. I wonder why does this happen? 
![events](https://user-images.githubusercontent.com/22633321/120884631-ce5bab80-c5ec-11eb-9450-dbe228923e8d.png)

From /var/www/MISP/app/tmp/logs/error.log I can see following lines : 

2021-06-05 16:03:49 Error: [MethodNotAllowedException] Could not remove tag as it is not attached to the target Event
Request URL: /tags/removeTagFromObject
Stack Trace:
#0 [internal function]: TagsController->removeTagFromObject()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#5 {main}
2021-06-05 16:16:32 Warning: vsprintf(): Too few arguments in [/var/www/MISP/app/Lib/cakephp/lib/Cake/I18n/I18n.php, line 697]
2021-06-05 16:19:44 Error: [MethodNotAllowedException] Could not remove tag as it is not attached to the target Event
Request URL: /tags/removeTagFromObject
Stack Trace:
#0 [internal function]: TagsController->removeTagFromObject()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#5 {main}
2021-06-05 16:20:49 Error: [MethodNotAllowedException] Could not remove tag as it is not attached to the target Event
Request URL: /tags/removeTagFromObject
Stack Trace:
#0 [internal function]: TagsController->removeTagFromObject()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#5 {main}

The only change I have made to this MISP instance recentry (understand these days) is to enable enrichment modules which I have installed in venv as recommended in https://github.com/MISP/misp-modules

Can someone suggest where to look and what could cause this ? 
Thank you in advance.

**Comment by mokaddem** [comment]
Hi @toteb !
Sorry for the late reply.
Were you able to solve your issue in the end?
If not, could you please update your MISP instance and try again? We improved the `removeTagFromObject` recently.
Thanks!
