### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#752]
~~~~
2015-12-14 10:02:49 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column '1_attribute_id' cannot be null
Request URL: /events/2674
Stack Trace:
#0 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(460): PDOStatement->execute(Array)
#1 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(426): DboSource->_execute('INSERT INTO `mi...', Array)
#2 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1012): DboSource->execute('INSERT INTO `mi...')
#3 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1928): DboSource->create(Object(AppModel), Array, Array)
#4 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1745): Model->_doSave(Array, Array)
#5 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(2338): Model->save(Array, Array)
#6 ./MISP-priv/app/Model/Attribute.php(1046): Model->saveMany(Array)
#7 ./MISP-priv/app/Model/Attribute.php(415): Attribute->__afterSaveCorrelation(Array)
#8 [internal function]: Attribute->afterSave(false, Array)
#9 ./MISP-priv/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): call_user_func_array(Array, Array)
#10 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1956): CakeEventManager->dispatch(Object(CakeEvent))
#11 ./MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#12 ./MISP-priv/app/Controller/EventsController.php(1253): Model->save(Array, Array)
#13 [internal function]: EventsController->edit('2674')
#14 /home/misp/web-2.2/MISP-priv/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#15 /home/misp/web-2.2/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /home/misp/web-2.2/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#17 /home/misp/web-2.2/MISP-priv/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}

~~~~

**Comment by iglocska** [comment]
That is very odd. It means it couldn't find the ID of an attribute in a
correlation pair while creating a correlation.

**Comment by adulau** [comment]
It's based on the expansion for hashes on MISP priv event 2674.

**Comment by iglocska** [comment]
Weird, do you know which attribute exactly caused it? Are you going to be
on chat later on?

**Comment by iglocska** [comment]
Same as #756

**Comment by Rafiot** [comment]
Fixed too.
