### ISSUE TITLE
Error when another organization Push synchronisation

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#7559]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Win10
| PHP version               | 7.4.3
| MISP version / git hash   | 2.4.146, hash of the commit

### Behavior

A member of my community successfully pushed events, and so I was able to view them in my instance when my MISP was at version 2.4.145, as shown in the log below.

For example:

```text
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [03/Jul/2021:08:03:45 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.145 - #01521267352653612v1235612394b4f0426f6036ba7"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [03/Jul/2021:08:03:46 -0300] "POST /events/filterEventIdsForPush HTTP/1.1" 200 3550 "-" "MISP 2.4.145 - #01521267352653612v1235612394b4f0426f6036ba7"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [03/Jul/2021:08:03:46 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.145 - #01521267352653612v1235612394b4f0426f6036ba7"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [03/Jul/2021:08:03:47 -0300] "POST /events HTTP/1.1" 200 40367 "-" "MISP 2.4.145 - #01521267352653612v1235612394b4f0426f6036ba7"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [03/Jul/2021:08:03:47 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.145 - #01521267352653612v1235612394b4f0426f6036ba7"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [03/Jul/2021:08:03:47 -0300] "POST /events HTTP/1.1" 200 40817 "-" "MISP 2.4.145 - #01521267352653612v1235612394b4f0426f6036ba7"
```

After upgrading to version 2.4.146, when my community member tries to push events it gets timeout.

When he makes the request "POST /events" the status code is 500. Information from /var/log/apache2/misp.local_access.log

```text
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [08/Jul/2021:15:38:51 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #015212672327v1235612394b4f0426f6036be1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [08/Jul/2021:15:38:51 -0300] "POST /servers/postTest HTTP/1.1" 200 6426 "-" "MISP 2.4.146 - #015212672327v1235612394b4f0426f6036be1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [08/Jul/2021:15:39:00 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #015212672327v1235612394b4f0426f6036be1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [08/Jul/2021:15:39:00 -0300] "POST /events/filterEventIdsForPush HTTP/1.1" 200 2887 "-" "MISP 2.4.146 - #015212672327v1235612394b4f0426f6036be1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [08/Jul/2021:15:39:01 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #015212672327v1235612394b4f0426f6036be1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [08/Jul/2021:15:39:01 -0300] "POST /events HTTP/1.1" 500 103 "-" "MISP 2.4.146 - #015212672327v1235612394b4f0426f6036be1"
```
Information from /var/www/MISP/app/tmp/logs/error.log

```text
2021-07-08 15:39:32 Error: [TypeError] Argument 1 passed to Hash::combine() must be of the type array, string given, called in /var/www/MISP/app/Model/Server.php on line 727
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(727): Hash::combine()
#1 /var/www/MISP/app/Model/Server.php(1159): Server->getElligibleClusterIdsFromServerForPush()
#2 /var/www/MISP/app/Model/Event.php(4499): Server->syncGalaxyClusters()
#3 /var/www/MISP/app/Model/Event.php(4659): Event->uploadEventToServersRouter()
#4 /var/www/MISP/app/Model/Event.php(3964): Event->publish()
#5 /var/www/MISP/app/Controller/EventsController.php(2069): Event->_add()
#6 [internal function]: EventsController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#11 {main}
```

Line 727 of  /var/www/MISP/app/Model/Server.php:

```text
root@ip:/# sed -n '727p' /var/www/MISP/app/Model/Server.php
        $keyedClusterArray = Hash::combine($clusterArray, '{n}.GalaxyCluster.uuid', '{n}.GalaxyCluster.version');
```

Log of my community member who tried to push events:

```
[2021-07-08 15:38:59] main.INFO: got {"queue":"default","id":"3ef20eebd834f6c5bc05dfe86bd31e55","class":"ServerShell","args":[["push","1","39","272763"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"3ef20eebd834f6c5bc05dfe86bd31e55\",\"class\":\"ServerShell\",\"args\":[[\"push\",\"1\",\"39\",\"272763\"]]})","worker":"misp.xpto.com.br:13121"} []
[2021-07-08 15:38:59] main.INFO: Processing ID:3ef20eebd834f6c5bc05dfe86bd31e55 in default {"type":"process","worker":"misp.xpto.com.br:13121","job_id":"3ef20eebd834f6c5bc05dfe86bd31e55"} []
[2021-07-08 15:39:31] main.ERROR: {"queue":"default","id":"3ef20eebd834f6c5bc05dfe86bd31e55","class":"ServerShell","args":[["push","1","39","272763"]]} failed: Connection timed out {"type":"fail","log":"Connection timed out","job_id":"3ef20eebd834f6c5bc05dfe86bd31e55","time":31867,"worker":"misp.xpto.com.br:13121"} []
```

### Actions I took to try to fix
I restarted the workers and apache.
I performed updates to Galaxies and ObjectsTemplates.
Clean cache in: Server Settings & Maintenance > Clean model cache.
Update Warning List in: /var/www/MISP/app/Console/cake Admin updateWarningLists

### Support Questions

Would anyone know direct me to correction? Is it something related to a misconfiguration in my application or database?

**Comment by mokaddem** [comment]
Hello,
Could you try running the command below on your server (the server that receives the pushed event)?
```js
// POST /galaxy_clusters/restSearch
{
    "published": 1,
    "minimal": 1,
    "custom": 1
}
```
You can easily run API queries against your MISP instance by using the built-in REST client (`servers/rest`).

**Comment by ghost** [comment]
Hello @mokaddem,

I executed, here's the **Response**:

```text
Queried URL: https://misp.xpto.com.br/galaxy_clusters/restSearch
Response code: 200
Request duration: 234.19 ms
Headers
  Date: Tue, 13 Jul 2021 15:04:15 GMT
  Content-Type: application/json; charset=UTF-8
  Content-Length: 17
  Connection: close
  Server: Apache
  Strict-Transport-Security: max-age=63072000; includeSubdomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-XSS-Protection: 1; mode=block
  Upgrade: h2
  Set-Cookie: MISP-06dd4155-6466-4c95-8e31-fd262d188ac7=fg6puk13jmtmon2nral84qo367ek1aqn; expires=Fri, 16-Jul-2021 03:04:15 GMT; Max-Age=216000; path=/; secure; HttpOnly; SameSite=Lax,MISP-06dd4155-6466-4c95-8e31-fd262d188ac7=fg6puk13jmtmon2nral84qo367ek1aqn; expires=Fri, 16-Jul-2021 03:04:15 GMT; Max-Age=216000; path=/; secure; HttpOnly; SameSite=Lax
  Expires: Mon, 26 Jul 1997 05:00:00 GMT
  Last-Modified: Tue, 13 Jul 2021 15:04:15 GMT
  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  X-Username: sync-user@xpto.com.br/API/4
  X-Result-Count: 0
  X-Export-Module-Used: json
  X-Response-Format: json
```
`{"response": []}`

----

I used the AuthKey of the sync user that my community member uses for pushes. The call was executed successfully.

**Comment by mokaddem** [comment]
I thought the query above was failing for some reason but it seems not to be the case.
By any chance, could it be that the other party cannot reach the server anymore (due to network, firewall, .. issues)?
Is the `connection test` from `/servers/index` successful?
Thanks.

**Comment by JakubOnderka** [comment]
Hello, this looks like #7426. I just merged #7433 into `develop` branch that should at least provide you more information, what is wrong.

**Comment by ghost** [comment]
@mokaddem I appreciate the help,

I had already checked this and we don't have any locks, even because it manages to perform other requests successfully and only in "POST / events" that the status code is 500. Below are examples of logs from the last 3 days.

```text
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [12/Jul/2021:07:39:58 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [12/Jul/2021:08:01:15 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [12/Jul/2021:08:01:15 -0300] "POST /events/filterEventIdsForPush HTTP/1.1" 200 3589 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [12/Jul/2021:08:01:16 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [12/Jul/2021:08:01:16 -0300] "POST /events HTTP/1.1" 500 103 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"

XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [13/Jul/2021:08:01:36 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [13/Jul/2021:08:01:37 -0300] "POST /events/filterEventIdsForPush HTTP/1.1" 200 4681 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [13/Jul/2021:08:01:37 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [13/Jul/2021:08:01:37 -0300] "POST /events HTTP/1.1" 500 103 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [13/Jul/2021:13:34:43 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [13/Jul/2021:13:34:43 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"

XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [14/Jul/2021:08:04:35 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [14/Jul/2021:08:04:36 -0300] "POST /events/filterEventIdsForPush HTTP/1.1" 200 6943 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [14/Jul/2021:08:04:36 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [14/Jul/2021:08:04:37 -0300] "POST /events HTTP/1.1" 500 103 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [14/Jul/2021:09:38:38 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [14/Jul/2021:09:38:38 -0300] "GET /servers/getVersion HTTP/1.1" 200 113 "-" "MISP 2.4.146 - #0c25b721724c0fc9dbc064b0cdfcf6e4d77b2ae1"
```

@JakubOnderka, Thanks for the help, I'll check all the information.

**Comment by ghost** [comment]
Gentlemen, I performed troubleshooting, but without success. So I went back to the snapshot from the previous version and we got all the events from our community member, which suggests it might have been something update related.
I will update again and check the behavior of our instance.

Thanks for all the help.
