### ISSUE TITLE
Error when populating hashes from API

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#756]
This happen when I do: `misp check_hashes -p` in viper, and there are attributes to update (and at least one of them actually worked because if I do it multiple times, it works at the end).

Also, I guess it is because we are in debug mode, but the server returns an HTML stream, which makes the python client module unhappy.

```
2015-12-15 15:02:46 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column '1_attribute_id' cannot be null
Request URL: /events/2685
Stack Trace:
#0 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(AppModel), Array, Array)
#4 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1745): Model->_doSave(Array, Array)
#5 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(2343): Model->save(Array, Array)
#6 /var/www/MISP-priv/app/Model/Attribute.php(1151): Model->saveMany(Array)
#7 /var/www/MISP-priv/app/Model/Attribute.php(439): Attribute->__afterSaveCorrelation(Array)
#8 [internal function]: Attribute->afterSave(false, Array)
#9 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): call_user_func_array(Array, Array)
#10 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1961): CakeEventManager->dispatch(Object(CakeEvent))
#11 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#12 /var/www/MISP-priv/app/Controller/EventsController.php(1151): Model->save(Array, Array)
#13 [internal function]: EventsController->edit('2685')
#14 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#15 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /var/www/MISP-priv/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#17 /var/www/MISP-priv/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}
```

**Comment by iglocska** [comment]
I don't have viper installed atm on my laptop, could you check what calls are being made to the API? I cannot seem to be able to reproduce it, for some reason it is trying to save a correlation with only "one side", not sure how that happens (I will keep testing for now, maybe it's an in-event correlation that is blocked incorrectly?) but an example would help loads!

**Comment by iglocska** [comment]
Just tried that, no luck. From what I can tell from the stack trace:
1. it happens during an event pushed for edit
2. it happens during the after save correlation, which happens after an attribute is already saved and it tries to build the correlations between similar attributes
3. saving a correlation fails because the opposite attribute in the correlation pair doesn't have its ID assigned correctly to the correlation object

Could also be due to an older invalid entry in the DB

**Comment by Rafiot** [comment]
From the debug output: 
```
[main] - [internal], line ??</pre></div></pre>{
    "code": 500,
    "name": "SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;1_attribute_id&#039; cannot be null",
    "message": "SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;1_attribute_id&#039; cannot be null",
    "url": "\/events\/2685",
    "error": {
        "errorInfo": [
            "23000",
            1048,
            "Column '1_attribute_id' cannot be null"
        ],
        "queryString": "INSERT INTO `misppriv`.`correlations` (`value`, `1_event_id`, `1_attribute_id`, `event_id`, `attribute_id`, `org_id`, `distribution`, `a_distribution`, `sharing_group_id`, `a_sharing_group_id`, `date`, `info`) VALUES ('4537257cb69a467a63c5a561825571f9', 2685, NULL, 2550, 303156, 2, 3, 3, 0, 0, '2015-11-25', 'OSINT - Attack Campaign on the Government of Thailand Delivers Bookworm Trojan')"
    }
}
```
Does it help?

**Comment by Rafiot** [comment]
Fixed.
