### ISSUE TITLE
Setting emoji on MISP.footermidright fails but works

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#7563]
Setting an 絵文字 (emoji), like: 🌍 on any configurable text field will fail with: "Request failed for an unknown reason."

```
2021-07-14 03:08:08 Error: [PDOException] SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x8D) ...' for column `misp`.`logs`.`change` at row 1
Request URL: /servers/serverSettingsEdit/MISP.footermidright/84/1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Log.php(241): Model->save()
#6 /var/www/MISP/app/Model/Server.php(2195): Log->createLogEntry()
#7 /var/www/MISP/app/Controller/ServersController.php(1489): Server->serverSettingsEditValue()
#8 [internal function]: ServersController->serverSettingsEdit()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#13 {main}```

**Comment by mokaddem** [comment]
Unfortunately, the log table do not support utf8 characters of more than 3 bytes (table is set to `utf8_bin`). When we'll migrate the framework, we'll also update all tables to be ` utf8mb4` or similar.
Sorry for the inconvenience.
