### ISSUE TITLE
Email error while sending the request to join a community - SendEmail->sendExternal()

### ISSUE THREAD

**Issue by AndyCyberSec** [MISP/MISP#7573]
Hello, I was trying to request access for a community but when I send the request through MISP I get the following error:

**An Internal Error Has Occurred.**
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Looking at the logs I can see the following:

```
Request URL: /communities/requestAccess/6201a65a-38fa-4b4a-bea7-cf1fb7bc1563
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(789): SendEmail->sendExternal()
#1 /var/www/MISP/app/Controller/CommunitiesController.php(149): User->sendEmailExternal()
#2 [internal function]: CommunitiesController->requestAccess()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#6 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#7 {main}
```

any suggestion?
Thank you

Attachments:
![misp1](https://user-images.githubusercontent.com/20374411/126146837-94e71beb-c8da-49af-87d3-a7eaa5b742d9.jpg)

![misp2](https://user-images.githubusercontent.com/20374411/126146926-7f692573-4977-43c3-86e9-70811fa3a694.jpg)

**Comment by Xorkan** [comment]
Hi, did you find the solution to this issue ?
