### ISSUE TITLE
Column 'org_id' not found

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#760]
Here as well, I don't know where I clicked (sorry about that) but I see the following in the error.log:

2015-12-16 10:04:34 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'org_id' in 'where clause'
Request URL: /logs/returnDates/Organisation.json
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('SELECT DISTINCT...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(666): DboSource->execute('SELECT DISTINCT...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1106): DboSource->fetchAll('SELECT DISTINCT...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2947): DboSource->read(Object(Log), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2919): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Log.php(83): Model->find('all', Array)
#7 /var/www/MISP/app/Controller/LogsController.php(246): Log->returnDates('Organisation')
#8 [internal function]: LogsController->returnDates('Organisation')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(LogsController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(LogsController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by h122015** [comment]
This happens when I want to see the Activity Heatmap for a specific organisation in the Statistics page (Global actions -> Statistics)
