### ISSUE TITLE
Attribute with invalid subnetmask breaks Correlation

### ISSUE THREAD

**Issue by PatrickHemberger** [MISP/MISP#7700]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat 7
| OS version (client)       | MacOS
| PHP version               | 7.2.24
| MISP version / git hash   | v2.4.148
| Browser                   | all

### Expected behavior

Attributes with an invalid subnetmask cannot be created or the correlation is not breaking

### Actual behavior

Fetching feeds not possible, job fails with Exception: Resque_Job_DirtyExitException; 
The resque-worker-error.log shows following error "Error: Bit shift by negative number"

Searching for the IP shown in the stack trace #0 returns an attribute with an invalid subnetmask 2.1.1.100/**80** and type "ip-src"

The error occurs also after the mentioned attribute was deleted;
As workaround the app/Model/Correlation.php on our MISP was modified as shown below

```
diff --git a/app/Model/Correlation.php b/app/Model/Correlation.php
index f7499ef..e29bf0a 100644
--- a/app/Model/Correlation.php
+++ b/app/Model/Correlation.php
@@ -526,6 +526,9 @@ class Correlation extends AppModel
     private function __ipv4InCidr($ip, $cidr)
     {
         list($subnet, $bits) = explode('/', $cidr);
+        if ($bits > 32){
+            $bits = 32;
+        }
         $ip = ip2long($ip);
         $subnet = ip2long($subnet);
         $mask = -1 << (32 - $bits);
```

With the workaround implemented fetching feeds is running successfully

### Logs, screenshots, configuration dump, ...

```
Error: Bit shift by negative number
#0 /var/www/MISP/app/Model/Correlation.php(492): Correlation->__ipv4InCidr(787745441, '2.1.1.100/...')
#1 /var/www/MISP/app/Model/Correlation.php(65): Correlation->cidrCorrelation(Array)
#2 /var/www/MISP/app/Model/Correlation.php(291): Correlation->__buildAdvancedCorrelationConditions(Array)
#3 /var/www/MISP/app/Model/Attribute.php(441): Correlation->afterSaveCorrelation(Array, false, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave(true, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#7 /var/www/MISP/app/Model/Attribute.php(3664): Model->save(Array, Array)
#8 /var/www/MISP/app/Model/Event.php(3882): Attribute->captureAttribute(Array, '142886', Array, 0, Object(Log), Array)
#9 /var/www/MISP/app/Model/Feed.php(911): Event->_add(Array, true, Array)
#10 /var/www/MISP/app/Model/Feed.php(585): Feed->__addEventFromFeed(Object(HttpSocketExtended), Array, '5534af90-2ce8-4...', Array, Array)
#11 /var/www/MISP/app/Model/Feed.php(984): Feed->downloadFromFeed(Array, Array, Object(HttpSocketExtended), Array, '1033498')
#12 /var/www/MISP/app/Console/Command/ServerShell.php(297): Feed->downloadFromFeedInitiator('1', Array, '1033498')
#13 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#15 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#16 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#17 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#18 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#19 {main}
```

**Comment by JakubOnderka** [comment]
Hello. This is weird, because `ip-src` attribute with invalid subnet mask should be dropped. I will check it.
