### ISSUE TITLE
Error: [ArithmeticError] Bit shift by negative number

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#7718]
2.4.148

In a new MISP instance, we are seeing the error below when adding an IP attribute to an event in the WebUI. We've never seen this one before and would appreciate some help in finding/fixing root cause. Thanks!!

One suspicion is that in `Correlation->__ipv4InCidr` that either the `$cidr` passed into the function has no `/subnet` or the redis `'misp:cidr_cache_list'` is corrupted or perhaps not accessible.

Can someone explain where redis gets the cidr values that are populated into `'misp:cidr_cache_list'` or some other method to determine if this might be related to root cause?

Here's the `error.log` stack trace when adding that IP attribute:
* Note: #7700 sees the same error, but not sure that we have similar root causes.

```
2021-09-01 19:37:48 Error: [ArithmeticError] Bit shift by negative number
Request URL: /attributes/add/973847
Stack Trace:
#0 /var/www/MISP/app/Model/Correlation.php(492): Correlation->__ipv4InCidr()
#1 /var/www/MISP/app/Model/Correlation.php(65): Correlation->cidrCorrelation()
#2 /var/www/MISP/app/Model/Correlation.php(291): Correlation->__buildAdvancedCorrelationConditions()
#3 /var/www/MISP/app/Model/Attribute.php(441): Correlation->afterSaveCorrelation()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#7 /var/www/MISP/app/Model/Attribute.php(3664): Model->save()
#8 /var/www/MISP/app/Controller/AttributesController.php(172): Attribute->captureAttribute()
#9 [internal function]: AttributesController->add()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#14 {​main}​
```

**Comment by github-germ** [comment]
What is the source of the data in `redis 'misp:cidr_cache_list'`? Perhaps for some reason there 's data in our source data for that that has invalid CIDR's with subnet bits > 32???

Any assistance is greatly appreciated as this is in a new Production MISP stood up yesterday which is now non-functional.

Thx.

**Comment by github-germ** [comment]
Update: found the source of the `cidr_cache_list`, grabbed that list with
```
select distinct(value1) from attributes where type in ('ip-src','ip-dst') and value1 like '%/%' into outfile '/tmp/cidr_list';
```
and then found an IP with `/54` !!!

So...
1. How did that premium feed provider (unnamed) allow that invalid data?
2. How did MISP allow that to be ingested?
3. Need this code in `Models/Correlations.php` repaired to ensure that the `/bits <= 32`, e.g.
```
   // using Alnitak's solution from http://stackoverflow.com/questions/594112/$
    private function __ipv4InCidr($ip, $cidr)
    {
        list($subnet, $bits) = explode('/', $cidr);
        // START: insert these 3 lines
        if ($bits > 32) {
            $bits = 32;
        }
        // STOP
        $ip = ip2long($ip);
        ...
```

**Comment by github-germ** [comment]
@JakubOnderka -- Thx a lot for looking at the ingestion validation. Will you also consider the fix to check the bits as above?
