### ISSUE TITLE
Enabling feeds after deletion of all the events failed

### ISSUE THREAD

**Issue by cac0ns3c** [MISP/MISP#7790]
# This template is meant for bug reports, if you have a feature request user the other template.

After deleting all the events from MISP using PyMISP, due to performance issues, tried to reenable all the feeds and got the error:

`2021-09-29 22:07:21 Error: Could not save freetext feed data for feed 7.
[Exception] The target event is no longer valid. Make sure that the target event 225 exists.
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(1013): Feed->saveFreetextFeedData()
#1 /var/www/MISP/app/Console/Command/ServerShell.php(297): Feed->downloadFromFeedInitiator()
#2 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#8 {main}`

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | v2.4.148
| Browser                   | Chrome

### Expected behavior
The fixed id will be reset to a different value

### Actual behavior
The fixed id says the same

### Steps to reproduce the behavior
Don't know how

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/11958671/135355983-7c66e7de-dec2-4827-8bbf-d3b708179813.png)
![image](https://user-images.githubusercontent.com/11958671/135356014-309e3f1d-3464-4abe-9eff-732fb960aabb.png)

**Comment by rodsterD** [comment]
MISP 2.4.152, Ubuntu, PHP 7.4 
Same problem here, cleared all events (by selecting 60 at a time and deleting). Once all cleared, clicked "Fetch and store all feed data". Many feeds gave the error:
1. Error: Could not save freetext feed data for feed abc.
[Exception] The target event is no longer valid. Make sure that the target event xyza exists.

Some other errors (different feeds / events):
a. Error: Could not get freetext feed xyz
Fetching the 'xxx' failed with exception: Connection timed out
b. [HttpSocketHttpException] Remote server returns HTTP error code 404 for URL

Note 1: These are all default feeds using a clean up-to-date installation [so the timeouts and 404s should probably be checked for all the current default urls]; I selected most default feeds [I know - correlation flood :( ]
Note 2: I have 13 feeds of all three types - misp, freetext and csv - that seem to be working fine

Thanks!

**Comment by SergeyDrachuk** [comment]
The same problem. Also after a reinstall (docker-compose) from a scratch feeds working only automatically (by internal scheduler) at night. The manual attempt to pull data from feeds failed with the error
[HttpSocketHttpException] Remote server returns HTTP error code 404 for URL https://misp.cert.gov.my/events/restSearch/manifest.json
It looks like an incorrect request.

**Comment by RyanInsolencee** [comment]
Is there any fix for this currently am getting the same issue

**Comment by Karonxv** [comment]
I have a same problem 

2025-01-30 10:19:31 Error: Could not save freetext feed data for feed 84.
[Exception] The target event is no longer valid. Make sure that the target event 8 exists.
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(1311): Feed->saveFreetextFeedData()
#1 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#2 /var/www/MISP/app/Console/Command/AppShell.php(63): ServerShell->fetchFeed()
#3 /var/www/MISP/app/Vendor/iglocska/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#4 /var/www/MISP/app/Vendor/iglocska/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#5 /var/www/MISP/app/Vendor/iglocska/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#6 /var/www/MISP/app/Vendor/iglocska/php-resque-ex/bin/resque(109): Resque_Worker->work()
#7 /var/www/MISP/app/Vendor/iglocska/php-resque-ex/bin/resque(100): startWorker()
#8 {main}
Job failed.
