### ISSUE TITLE
Redis Broken Pipe Bytes Failed Errors

### ISSUE THREAD

**Issue by bm11100** [MISP/MISP#7794]
## Issue 
I've got a cron just set up to cache feeds and it has been working fine. I saw the feeds havent been cached lately and when I run `/var/www/MISP/app/Console/cake Server cacheFeed 2 all 2>&1` manually I am getting loys of bytes failed errors like below -

```
2021-09-29 14:46:41 Notice: Redis::exec(): send of 8192 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1334]
Notice Error: Redis::exec(): send of 8192 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1334]
```

### Disk space
```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G   33M  7.7G   1% /run
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/nvme0n1p1  500G  9.6G  491G   2% /
tmpfs           1.6G     0  1.6G   0% /run/user/1003
```
### CPU isnt pegged and all workers are healthy 
I've rebooted the server multiple times

### Diagnostics look good
![image](https://user-images.githubusercontent.com/56412096/135485712-223fc2d0-e805-4c79-bf11-43286eb6d231.png)

### Increased some of the default settings
```
max_execution_time (300 seconds)… OK (recommended: 300 seconds)
memory_limit (8192 MB)… OK (recommended: 2048 MB)
upload_max_filesize (150 MB)… OK (recommended: 50 MB)
post_max_size (150 MB)… OK (recommended: 50 MB)
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 7
| OS version (client)       | Win10
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.148, (337ab7d9be55f2c35c579f5166dd96690f2818e7)

### Expected behavior
Cache job runs without errors

### Actual behavior
Lots of errors

### Steps to reproduce the behavior
Manually run the job

**Comment by samitainio** [comment]
@bm11100 

You are not alone with this issue. I also randomly noticed this happening this evening. I don't have a cronjob setup but I do have the scheduled task from the UI side. This error message appears in my logs right after the cache_feeds runs. I grepped the logs and the first time this has appeared on my instance was 2021-08-15. The latest occurance was today with the latest version.

| Questions                 | Answers
|---------------------------|--------------------
| OS version (server)       | Ubuntu 20.04.3 LTS
| PHP version               | 7.4.24
| MISP version / git hash   | v2.4.148 (3822521d2ceeb7dcccaf53ea3052a8a2209f0433)

| Redis info | Version
| --- | --- |
| PHP extension | 5.3.4
| Redis | 5.0.7

I then went to the feeds that I have setup to be cached and saw that the UI showed they hadn't been cached in 61 days. Feeds that I thought I were caching are:

Name | Format | Provider | Source | URL
-- | -- | -- | -- | -- 
ThreatFox | misp | abuse.ch | network | https://threatfox.abuse.ch/downloads/misp/
MalwareBazaar | misp | abuse.ch | network | https://bazaar.abuse.ch/downloads/misp/
URLhaus | misp | abuse.ch | network | https://urlhaus.abuse.ch/downloads/misp/

I rechecked the logs with:

`grep -A 30 -i "exception" /var/www/MISP/app/tmp/logs/debug.log >> exception.log`

Here are the relevant logs per feed:

ThreatFox:
```
[Exception] Fetching the 'https://threatfox.abuse.ch/downloads/misp//hashes.csv' failed with HTTP error 404: Not Found
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(189): Feed->feedGetUri()
#1 /var/www/MISP/app/Model/Feed.php(1350): Feed->getCache()
#2 /var/www/MISP/app/Model/Feed.php(1372): Feed->__cacheMISPFeedCache()
#3 /var/www/MISP/app/Model/Feed.php(1242): Feed->__cacheMISPFeed()
#4 /var/www/MISP/app/Model/Feed.php(1202): Feed->__cacheFeed()
#5 /var/www/MISP/app/Console/Command/ServerShell.php(562): Feed->cacheFeedInitiator()
#6 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->enqueueFeedCache()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#12 {main}
2021-08-15 06:30:31 Notice: Redis::del(): send of 38 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1301]
2021-08-15 06:30:31 Notice: Redis::exec(): send of 8192 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1334]

Last line then repets N-hundred times...
```

MalwareBazaar:

```
[Exception] Fetching the 'https://bazaar.abuse.ch/downloads/misp//hashes.csv' failed with HTTP error 404: Not Found
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(189): Feed->feedGetUri()
#1 /var/www/MISP/app/Model/Feed.php(1350): Feed->getCache()
#2 /var/www/MISP/app/Model/Feed.php(1372): Feed->__cacheMISPFeedCache()
#3 /var/www/MISP/app/Model/Feed.php(1242): Feed->__cacheMISPFeed()
#4 /var/www/MISP/app/Model/Feed.php(1202): Feed->__cacheFeed()
#5 /var/www/MISP/app/Console/Command/ServerShell.php(562): Feed->cacheFeedInitiator()
#6 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->enqueueFeedCache()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#12 {main}
2021-08-15 06:30:59 Notice: Redis::del(): send of 38 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1301]
2021-08-15 06:31:42 Notice: Redis::set(): send of 65 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1376]
```
URLhaus:

```
[Exception] Fetching the 'https://urlhaus.abuse.ch/downloads/misp//hashes.csv' failed with HTTP error 404: Not Found
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(189): Feed->feedGetUri()
#1 /var/www/MISP/app/Model/Feed.php(1350): Feed->getCache()
#2 /var/www/MISP/app/Model/Feed.php(1372): Feed->__cacheMISPFeedCache()
#3 /var/www/MISP/app/Model/Feed.php(1242): Feed->__cacheMISPFeed()
#4 /var/www/MISP/app/Model/Feed.php(1202): Feed->__cacheFeed()
#5 /var/www/MISP/app/Console/Command/ServerShell.php(562): Feed->cacheFeedInitiator()
#6 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->enqueueFeedCache()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#12 {main}
2021-08-15 06:31:43 Notice: Redis::del(): send of 38 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1301]
2021-08-15 06:31:43 Notice: Redis::exec(): send of 8192 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1334]
```

The error message part `<url>//hashes.csv' failed with HTTP error 404: Not Found` is correct in the sense that those feeds do not have the hashes.csv available.

I then tried manually caching the feeds from the UI. UI age counter for the caching resets but those same error logs appear just with different timestamps.

**Comment by internet-goods** [comment]
I also get these errors on the harvard docker container, "Redis::exec(): send of 8192 bytes failed with errno=32 Broken pipe in"
My versions:
PHP Version (>7.4 recommended): 7.4.3 (Up to date)
PHP CLI Version (>7.4 recommended): 7.4.3 (Up to date)
Currently installed version… v2.4.151 (708bb6e3f772cd8a6324837d946f4edf8d3fee91)
Redis info
PHP extension version: 5.1.1
Redis version: 5.0.7
Memory allocator: jemalloc-5.2.1
Memory usage: 705.14MB
Peak memory usage: 793.52MB
Fragmentation ratio: 1.04
Total system memory: 15.12GB

**Comment by 01dr1ch** [comment]
Same here. I'd like to know where the information about .csv file comes from. Reading https://bazaar.abuse.ch/downloads/misp/manifest.json , seems there's no CSV information. 

Feed config also doesn't mention it:
``` json
{
    "Feed": {
        "id": "67",
        "name": "MalwareBazaar",
        "provider": "Abuse.ch",
        "url": "https://bazaar.abuse.ch/downloads/misp/",
        "rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]},\"url_params\":\"{\\n    \\\"timestamp\\\": \\\"1d\\\",\\n    \\\"date\\\": \\\"1d\\\"\\n}\"}",
        "enabled": false,
        "distribution": "4",
        "sharing_group_id": "1",
        "tag_id": "16",
        "default": true,
        "source_format": "misp",
        "fixed_event": false,
        "delta_merge": false,
        "event_id": "0",
        "publish": false,
        "override_ids": false,
        "settings": "{\"csv\":{\"value\":\"\",\"delimiter\":\"\"},\"common\":{\"excluderegex\":\"\"}}",
        "input_source": "network",
        "delete_local_file": false,
        "lookup_visible": true,
        "headers": "",
        "caching_enabled": true,
        "force_to_ids": false,
        "orgc_id": "0",
        "cached_elements": 0,
        "coverage_by_other_feeds": "0%"
    },
    "Tag": {
        "id": "16",
        "name": "<redacted>",
        "colour": "#003d57",
        "exportable": true,
        "org_id": "0",
        "user_id": "0",
        "hide_tag": false,
        "numerical_value": null,
        "is_galaxy": false,
        "is_custom_galaxy": false,
        "local_only": false
    }
}
```

``` log
2021-12-08 12:00:49 Notice: Could not get cache file for 67.
[HttpSocketHttpException] Remote server returns HTTP error code 404 for URL https://bazaar.abuse.ch/downloads/misp//hashes.csv
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(1914): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(199): Feed->feedGetUri()
#2 /var/www/MISP/app/Model/Feed.php(1473): Feed->getCache()
#3 /var/www/MISP/app/Model/Feed.php(1345): Feed->__cacheMISPFeedCache()
#4 /var/www/MISP/app/Model/Feed.php(1298): Feed->__cacheFeed()
#5 /var/www/MISP/app/Console/Command/ServerShell.php(510): Feed->cacheFeedInitiator()
#6 /var/www/MISP/app/Console/Command/AppShell.php(43): ServerShell->enqueueFeedCache()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#12 {main}
Notice Error: Redis::del(): send of 38 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php, line 1417]

2021-12-08 12:00:49 Notice: Redis::del(): send of 38 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Model/Feed.php,
line 1417]
```

**Comment by carlokohan** [comment]
Would like to know if anyone was able to fix this issue? I am also encountering this error

**Comment by scottpendlebury** [comment]
We're (@cybgit) also experiencing the same problem. The workaround I'm using is to cache the feeds manually, one by one. 

![image](https://user-images.githubusercontent.com/2189228/205619525-8e2496dc-9ea6-44e3-a900-7bfa9505a270.png)

The "cache all feeds" button has the same effect as the scheduled job seems to - it appears to complete the job but the age of the cache doesn't change.

**Comment by cybgit** [comment]
> We're (@cybgit) also experiencing the same problem. The workaround I'm using is to cache the feeds manually, one by one.
> 
> ![image](https://user-images.githubusercontent.com/2189228/205619525-8e2496dc-9ea6-44e3-a900-7bfa9505a270.png)
> 
> The "cache all feeds" button has the same effect as the scheduled job seems to - it appears to complete the job but the age of the cache doesn't change.

Yes, bump please. As OP suggested, we've aso increased memory in /etc/php7.2/apache2/php.ini to 8192M
