### ISSUE TITLE
Fetching PGP fails with SSL error.

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#7802]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Potential Bug or Misconfig
| OS version (server)       | Ubuntu 20.04
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | v2.4.148 (164435c475d5a85f7e43b489bf41d0c6eaab57dc)

Fetching a key from opengpg.circl.lu fails with the error below.

```
2021-10-04 02:13:14 Error: [SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://openpgp.circl.lu:443 (Unknown error)
Request URL: /users/searchGpgKey/steve.clement@circl.lu?_=1633313476368
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#2 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(131): HttpSocket->request()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#4 /var/www/MISP/app/Lib/Tools/GpgTool.php(242): HttpSocket->get()
#5 /var/www/MISP/app/Lib/Tools/GpgTool.php(50): GpgTool->keyServerLookup()
#6 /var/www/MISP/app/Model/User.php(871): GpgTool->searchGpgKey()
#7 /var/www/MISP/app/Controller/UsersController.php(2336): User->searchGpgKey()
#8 [internal function]: UsersController->searchGpgKey()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#13 {main}
2021-10-04 02:13:14 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException()
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
2021-10-04 02:13:14 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 [internal function]: ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error()
#3 [internal function]: ErrorHandler::handleException()
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2021-10-04 02:13:14 Error: [InternalErrorException] Internal Server Error
Request URL: /users/searchGpgKey/steve.clement@circl.lu?_=1633313476368
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by SteveClement** [comment]
Updating: /var/www/MISP/app/Lib/cakephp/lib/Cake/Config/cacert.pem results in a quiet failure. In the gui you get a "ressource not found" hint.
Using this source:https://curl.se/docs/caextract.html

**Comment by JakubOnderka** [comment]
Thats probably because Lets Encrypt Root CA expired (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) and CakePHP uses old CA list.

**Comment by zpevma** [comment]
Unfortunately it's not just issue of PGP. Synchronization with MISPs using Let's encrypt certificates does not work either - I get `Server unreachable` error. 

One example is BSI: misp.bsi.bund.de.

**Comment by RonV666** [comment]
I have a similar issue with a cert from https://osint.digitalside.it/ in the feeds, since the LetsEncrypt cross signed cert expired on sept 30 I am no longer able to fetch the feed without getting a SSL verify error as well

2021-10-10 14:02:21 Error: Could not get new event uuids for feed 62.
[Exception] Fetching the 'https://osint.digitalside.it/Threat-Intel/digitalside-misp-feed//manifest.json' failed with exception: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://osint.digitalside.it:443 (Unknown error)

I used a hack from https://github.com/MISP/MISP/issues/3249


set 'ssl_verify_peer' => false 

in /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php

Its ugly, but I am able to download my feed now.

**Comment by adulau** [comment]
The CA bundle store has been updated in https://github.com/MISP/cakephp/tree/2.x -  https://github.com/MISP/MISP/commit/da6d5aaa127bbde63f2d18bd4f6b5ba2bf3b97e5 - You just need to update MISP and the submodule. 

~~~
git submodule sync
git submodule update
~~~

**Comment by RonV666** [comment]
I may have broken my MISP :(

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

fatal: remote error: upload-pack: not our ref c31bb4b4be00d2a0db22c9a038f9fad8a5950efe
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'app/Lib/cakephp', but it did not contain c31bb4b4be00d2a0db22c9a038f9fad8a5950efe. Direct fetching of that commit failed.

is there a way to reinstall a submodule cleanly?

**Comment by adulau** [comment]
git submodule sync
git submodule update

should be fine
