### ISSUE TITLE
MISP modules expansion not possible due to issue with /tmp

### ISSUE THREAD

**Issue by obert01** [MISP/MISP#7868]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Win10
| PHP version               | 7.4
| MISP version / git hash   | v2.4.150 (dc7103ca0ed020b2a06016d4717b3aba387f331f) 

### Expected behavior
On an attribute, I normally click the "add enrichment" button, choose e.g. VirusTotal, get a summary of new attributes to be added, click "Submit", refresh the event view page, and see the new attributes. 

### Actual behavior
The summary of the attribute expansion appears correctly, but the new attributes actually never get added after clicking "submit". 

### Logs, screenshots, configuration dump, ...
The following error appears in resque-worker-error.log:
```
Error: An error has occurred while attempt to read file `/tmp/MISPwbA6Ow`: file doesn't exists.
#0 /var/www/MISP/app/Console/Command/EventShell.php(555): FileAccessTool::readFromFile()
#1 /var/www/MISP/app/Console/Command/AppShell.php(36): EventShell->processmoduleresult()
#2 /var/www/MISP/app/vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#3 /var/www/MISP/app/vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#4 /var/www/MISP/app/vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#5 /var/www/MISP/app/vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#6 /var/www/MISP/app/vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#7 {main}
```

### Possible explanation
I think the issue is due because "/tmp" is a private directory for Apache in Ubuntu (i.e. the "PrivateTmp" directive of systemd). PHP Workers, which run under PHP CLI, are not aware of this private tmp directory. 

I have noticed that app/Lib/Tools/FileAccessTool.php has been modified recently, and especially the function that creates temporary files. I understand that this issue appeared since then. 

Before the change, traces were as follows:
```
resque-2021-10-19.log:[2021-10-19 16:07:31] main.INFO: got {"queue":"prio","id":"2eb113dd50fde70941ab7cfe257c8066","class":"EventShell","args":[["processmoduleresult","9BlHXIAWYScj.json"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"prio\",\"id\":\"2eb113dd50fde70941ab7cfe257c8066\",\"class\":\"EventShell\",\"args\":[[\"processmoduleresult\",\"9BlHXIAWYScj.json\"]]})","worker":"misp:1145"} []
```

After the change, they look like this:
```
resque-2021-10-20.log:[2021-10-20 16:26:34] main.INFO: got {"queue":"prio","id":"e867934f8287b189f492260f51d7c2f7","class":"EventShell","args":[["processmoduleresult","\/tmp\/MISPwbA6Ow"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"prio\",\"id\":\"e867934f8287b189f492260f51d7c2f7\",\"class\":\"EventShell\",\"args\":[[\"processmoduleresult\",\"\\/tmp\\/MISPwbA6Ow\"]]})","worker":"misp:1145"} []
resque-2021-10-20.log:[2021-10-20 16:26:34] main.ERROR: {"queue":"prio","id":"e867934f8287b189f492260f51d7c2f7","class":"EventShell","args":[["processmoduleresult","\/tmp\/MISPwbA6Ow"]]} failed: An error has occurred while attempt to read file `/tmp/MISPwbA6Ow`: file doesn't exists. {"type":"fail","log":"An error has occurred while attempt to read file `/tmp/MISPwbA6Ow`: file doesn't exists.","job_id":"e867934f8287b189f492260f51d7c2f7","time":60,"worker":"misp:1145"} []
```

**Comment by JakubOnderka** [comment]
Hello, can you please try to set `MISP.tmpdir` setting to `/var/www/MISP/app/tmp/` and check if it will works again?

**Comment by adulau** [comment]
I have seen this behaviour. Usually restarting the workers after the update will solve the issue.

**Comment by obert01** [comment]
Hello,

Setting MISP.tmpdir setting to /var/www/MISP/app/tmp/  actually solved the issue. 

For your information, MISP.tmpdir was not set in my config.php, and in the web interface the displayed default value was /tmp.

**Comment by gallypette** [comment]
I just had the same issue on the MISP VM (148 updated manually to 150) @JakubOnderka ' s proposed solution solved the issue.

**Comment by bullcube** [comment]
Having the same issue.  Is this a setting I need to add to config.php?

**Comment by bullcube** [comment]
I got this to work using:
 /var/www/MISP/app/Console/cake Admin setSetting -v MISP.tmpdir /var/www/MISP/app/tmp

This command would not work without the -v option.

**Comment by SteveClement** [comment]
This will be fixed in the next INSTALL.sh release. Thanks for bringing it up.

**Comment by djha983** [comment]
I am facing same issue in MISP V 2.4.163.
MISP.tmpdir is set to "/var/www/MISP/app/tmp"

Any idea what can be issue?
