### ISSUE TITLE
Fresh Install AWS

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [MISP/MISP#7917]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 20.04.
| OS version (client)       | Ubuntu
| Browser                   | chrome

### Support Questions

Hi,
Ive created an instance on AWS, with a security group - no restrictions outbound. Updated the OS
ran :
` wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c`

Only things I specified was baseurl, and create misp user  (I tried both same result)

### Logs, screenshots, configuration dump, ...

`
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ffa73e72cd0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/var/www/MISP/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='<IP>', port=80): Max retries exceeded with url: /servers/getVersion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffa73e72cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 169, in __init__
    response = self.recommended_pymisp_version
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 226, in recommended_pymisp_version
    misp_version = self.misp_instance_version
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 255, in misp_instance_version
    response = self._prepare_request('GET', 'servers/getVersion')
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 3571, in _prepare_request
    return self.__session.send(prepped, timeout=self.timeout, **settings)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='<IP>', port=80): Max retries exceeded with url: /servers/getVersion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffa73e72cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 190, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (http://<IP>). Please make sure the API key and the URL are correct (http/https is required): HTTPConnectionPool(host='<IP>', port=80): Max retries exceeded with url: /servers/getVersion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffa73e72cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

----------------------------------------------------------------------
Ran 0 tests in 130.271s

FAILED (errors=1)

**Comment by SteveClement** [comment]
As I have no  access to AWS I cannot test or reproduce it.

It does look like an issue with your connection on your side.

Also, as it is during the test-suite, it seems the install went just fine until then.

**Comment by Phil-ThePower-Pearce** [comment]
I recreatedthe instance and then did just a core install - I wasnt prompted to enter baseURL

```
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 144, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)
#########################################################################################  (88%)
```

**Comment by SteveClement** [comment]
Again, it seems it is the tests failing. Have you tried to connect to it? Does apache listen?
