### ISSUE TITLE
downloading JSON feed metadata throws exception: Call to a member function sCard() on bool

### ISSUE THREAD

**Issue by njthomas** [MISP/MISP#7941]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  CentOS
| OS version (client)       | CentOS Linux release 7.9.2009 (Core)
| PHP version               | 7.4
| MISP version / git hash   | misp-2.4.148-2.el7.x86_64
| Browser                   | Firefox 93.0

### Expected behavior

downloading any feed throws an error: "An Internal Error Has Occurred" The exact error thrown looks like this:

`{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/feeds\/view\/15.json"}`

There doesn't seem to be any network blocks/firewalls causing this. Running curl on box on the command line
(e.g. `curl -O https://www.circl.lu/doc/misp/feed-osint/5a5df567-ad8c-4649-ad06-480f950d210f.json`) seems to work fine.

### Actual behavior

Something that indicates downloading the feed was successfull.

### Steps to reproduce the behavior

In Sync Feeds > List Feeds, click on any feed's download button (download feed metadata as JSON)
_(this bug is happening for all feeds)_

### Logs, screenshots, configuration dump, ...

The error logs give this stack trace:

    2021-11-08 20:45:03 Error: [Error] Call to a member function sCard() on bool
    Request URL: /feeds/view/3.json
    Stack Trace:
    #0 /var/www/MISP/app/Controller/FeedsController.php(140): Feed->getCachedElements()
    #1 /var/www/MISP/app/Controller/Component/CRUDComponent.php(250): FeedsController->{closure}()
    #2 /var/www/MISP/app/Controller/FeedsController.php(150): CRUDComponent->view()
    #3 [internal function]: FeedsController->view()
    #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
    #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
    #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
    #7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
    #8 {main}

![misp-download-feed](https://user-images.githubusercontent.com/44175460/140818150-3db9fa6e-2f00-4be9-88db-0e46c65ac94a.png)

**Comment by njthomas** [comment]
We can probably close this issue out. I don't have access to the environment anymore, and I suspect external systemic issues  played a part in it.
