### ISSUE TITLE
[Centos8] Invalid background job queue , must be one of: [default, email, cache, prio, update]

### ISSUE THREAD

**Issue by juju4** [MISP/MISP#8001]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 8
| OS version (client)       | N/A
| PHP version               | 7.2
| MISP version / git hash   | 2.4
| Browser                   | N/A

### Expected behavior

PyMISP examples should execute without errors on Centos8.
Likely related to recent changes https://github.com/MISP/MISP/commit/4bd337eb42c6aa17bfff5ac933100bae8d38b432#diff-62a15aa944581510889a92fadbe112aac3293bd09aa6103058f8f7f61704de89

No issue observed on Ubuntu.

Problem may have dependency with pymisp as going back in time for misp code only (to b2c62801949f3b2f53a066f9f5528a2272633c89; https://github.com/juju4/ansible-MISP/runs/4342355100?check_suite_focus=true#step:9:5571) does not solve the issue.

### Actual behavior

```
# /var/www/_MISP/venv/bin/python /var/www/_MISP/MISP/PyMISP/examples/users_list.py 
/var/www/_MISP/venv/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
CRITICAL [api.py:3066 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.137.1 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'yq1k5H10CD3zYqxoBHTSyKyCPwftpWRtAeFFHqZu', 'content-type': 'application/json'}
Request body:
None
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/servers\/getPyMISPVersion.json"}
Traceback (most recent call last):
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 130, in __init__
    response = self.recommended_pymisp_version
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 187, in recommended_pymisp_version
    return self._check_json_response(response)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 3050, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 3067, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/servers\/getPyMISPVersion.json"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/_MISP/MISP/PyMISP/examples/users_list.py", line 12, in <module>
    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 151, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://localhost). Please make sure the API key and the URL are correct (http/https is required): Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/servers\/getPyMISPVersion.json"}

# cat /var/www/_MISP/MISP/app/tmp/logs/error.log
2021-11-27 17:40:41 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update]
Request URL: /servers/getPyMISPVersion.json
Stack Trace:
#0 /var/www/_MISP/MISP/app/Lib/Tools/BackgroundJobsTool.php(311): BackgroundJobsTool->validateQueue('')
#1 /var/www/_MISP/MISP/app/Model/Server.php(3443): BackgroundJobsTool->getQueueSize('')
#2 /var/www/_MISP/MISP/app/Model/AppModel.php(2093): Server->workerDiagnostics(8)
#3 /var/www/_MISP/MISP/app/Controller/AppController.php(255): AppModel->runUpdates()
#4 /var/www/_MISP/MISP/app/Controller/ServersController.php(40): AppController->beforeFilter()
#5 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ServersController->beforeFilter(Object(CakeEvent))
#6 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/_MISP/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

See also ansible role test run
https://github.com/juju4/ansible-MISP/runs/4342029432?check_suite_focus=true#step:9:5594
https://github.com/juju4/ansible-MISP/runs/4342029432?check_suite_focus=true#step:14:53

### Steps to reproduce the behavior

* Centos 8 deployment. example ansible play above

**Comment by righel** [comment]
Hello @juju4 
The error indicates that `BackgroundJobsTool::getQueueSize()` is called with an empty string as parameter, this is likely linked to some configuration error.

By any chance are you starting the workers with some custom command instead of the `/var/www/MISP/app/Console/worker/start.sh` script?

**Comment by righel** [comment]
Digging a bit deeper, the error originates here:
https://github.com/juju4/ansible-MISP/runs/4342029432?check_suite_focus=true#step:14:84
```
2021-11-27 18:18:30 Notice: Notice (8): unserialize(): Error at offset 0 of 5 bytes in [/var/www/_MISP/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 127]
```
The error originates in a faulty response from CakeResque when deserializing the workers status, maybe Redis related. Does the error occurs persistently? Could you try re-run the action?

**Comment by juju4** [comment]
Thanks @righel 
Will review next week-end but there were no real changes in my ansible role recently, still occurs if going for older MISP commits and strangely, only happens on centos8.
Selinux is the main difference I would think for centos setup but does not apply here as test is in a lxc container on top of ubuntu host. And no snuffleupagus like on my default ubuntu setup.

Error is persisting in both github actions and manual testing.
Will check redis logs.

**Comment by juju4** [comment]
nothing special in redis.log
ansible test already runs multiple times user_list.py

one anomaly is pymisp is 2.4.137.1 (Jan 2021) while latest is 2.4.151. ah coming from misp-modules not aligned on latest 2.4.142. 
upgrading pymisp does not help
and anyway latest successful play was also with 2.4.137.1 - https://github.com/juju4/ansible-MISP/runs/4208128223?check_suite_focus=true#step:12:300

quick change to /var/www/_MISP/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php
```
    public function getWorkers()
    {
        $workers = $this->redis->hGetAll(self::$workerKey);
        $temp = array();

        foreach ($workers as $name => $value) {
            error_log(print_r("=====\n", 0));
            error_log(print_r($value, 0));
            error_log(print_r("=====\n", 0));
            $temp[$name] = unserialize($value);
            error_log(print_r(">>>\n", 0));
            error_log(print_r($temp[$name], 0));
            error_log(print_r(">>>\n", 0));
        }
        return $temp;
    }

```

and get
```
# python3 ./users_list.py 
/var/www/_MISP/venv/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 3513, in _check_response
    response_json = response.json()
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 169, in __init__
    response = self.recommended_pymisp_version
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 226, in recommended_pymisp_version
    misp_version = self.misp_instance_version
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 256, in misp_instance_version
    return self._check_json_response(response)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 3481, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/var/www/_MISP/venv/lib/python3.6/site-packages/pymisp/api.py", line 3523, in _check_response
    raise PyMISPUnexpectedResponse(error_msg)
pymisp.exceptions.PyMISPUnexpectedResponse: Unexpected response (size: 9390) from server: =====
73200=====
>>>
>>>
=====
a:10:{s:8:"interval";i:5;s:5:"queue";s:5:"cache";s:4:"help";b:0;s:7:"verbose";b:0;s:5:"quiet";b:0;s:4:"type";s:7:"regular";s:3:"log";s:56:"/var/www/_MISP/MISP/app/tmp/logs/resque-worker-error.log";s:7:"workers";i:1;s:4:"user";s:6:"apache";s:3:"Log";a:2:{s:7:"handler";s:12:"RotatingFile";s:6:"target";s:43:"/var/www/_MISP/MISP/app/tmp/logs/resque.log";}}=====
>>>
Array
(
    [interval] => 5
    [queue] => cache
    [help] => 
    [verbose] => 
    [quiet] => 
    [type] => regular
    [log] => /var/www/_MISP/MISP/app/tmp/logs/resque-worker-error.log
    [workers] => 1
    [user] => apache
    [Log] => Array
        (
            [handler] => RotatingFile
            [target] => /var/www/_MISP/MISP/app/tmp/logs/resque.log
        )

)
>>>
=====
73164=====
>>>
>>>
=====
a:10:{s:8:"interval";i:5;s:5:"queue";s:7:"default";s:4:"help";b:0;s:7:"verbose";b:0;s:5:"quiet";b:0;s:4:"type";s:7:"regular";s:3:"log";s:56:"/var/www/_MISP/MISP/app/tmp/logs/resque-worker-error.log";s:7:"workers";i:1;s:4:"user";s:6:"apache";s:3:"Log";a:2:{s:7:"handler";s:12:"RotatingFile";s:6:"target";s:43:"/var/www/_MISP/MISP/app/tmp/logs/resque.log";}}=====
>>>
Array
(
    [interval] => 5
    [queue] => default
    [help] => 
    [verbose] => 
    [quiet] => 
    [type] => regular
    [log] => /var/www/_MISP/MISP/app/tmp/logs/resque-worker-error.log
    [workers] => 1
    [user] => apache
    [Log] => Array
        (
            [handler] => RotatingFile
            [target] => /var/www/_MISP/MISP/app/tmp/logs/resque.log
        )

)
>>>
[...]
=====
73236=====
>>>
>>>
=====
a:10:{s:8:"interval";i:5;s:5:"queue";s:6:"update";s:4:"help";b:0;s:7:"verbose";b:0;s:5:"quiet";b:0;s:4:"type";s:7:"regular";s:3:"log";s:56:"/var/www/_MISP/MISP/app/tmp/logs/resque-worker-error.log";s:7:"workers";i:1;s:4:"user";s:6:"apache";s:3:"Log";a:2:{s:7:"handler";s:12:"RotatingFile";s:6:"target";s:43:"/var/www/_MISP/MISP/app/tmp/logs/resque.log";}}=====
>>>
Array
(
    [interval] => 5
    [queue] => update
    [help] => 
    [verbose] => 
    [quiet] => 
    [type] => regular
    [log] => /var/www/_MISP/MISP/app/tmp/logs/resque-worker-error.log
    [workers] => 1
    [user] => apache
    [Log] => Array
        (
            [handler] => RotatingFile
            [target] => /var/www/_MISP/MISP/app/tmp/logs/resque.log
        )

)
>>>
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/servers\/getVersion"}
```

still unclear what is the issue...

**Comment by righel** [comment]
Hello,
Seems to be some issue related to Redis, check if this solution helps you: https://github.com/MISP/MISP/issues/1204#issuecomment-871360030

**Comment by juju4** [comment]
Good catch.
Sorry, missed remi repository on rhel/centos 8 which affected package dependency

is there a way to call the test page/code in cli so this can be easily added and checked in CI/CD?
