### ISSUE TITLE
Bug: An Internal Error Has Occurred | Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update]

### ISSUE THREAD

**Issue by acfisher44** [MISP/MISP#8013]
### Expected behavior

GUI Access after login. 

### Actual behavior

After updating to latest version,I have been receiving "An Internal Error Has Occured..." upon logon. I am unable to view any contents, but only that error page. 

I can get to the login, but right after logging in the error message appears and redirects me to url path "Request URL: /users/routeafterlogin"

I was also receiving an error while running sudo -u www-data git submodule update --init --recursive
Error logs found below. 

while running the submodule update, the following error occured:
fatal: remote error: upload-pack: not our ref c31bb4b4be00d2a0db22c9a038f9fad8a5950efe
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'app/Lib/cakephp', but it did not contain c31bb4b4be00d2a0db22c9a038f9fad8a5950efe. Direct fetching of that commit failed.

### Steps to reproduce

I ran updates to OS 
Followed by updates for new version using the following
sudo -u www-data git pull origin 2.4
sudo -u www-data git submodule update --init --recursive

restarted apache 

logged into GUI, and was shown error message. 

Please let me me know if you can provide some assistance to getting data to show up again! Any help is appreciated. 

### Version

2.4.151

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.4

### Relevant log output

```shell
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#1 {main}
2021-12-01 01:01:00 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update]
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(311): BackgroundJobsTool->validateQueue()
#1 /var/www/MISP/app/Model/Server.php(3443): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Model/AppModel.php(2093): Server->workerDiagnostics()
#3 /var/www/MISP/app/Controller/AppController.php(255): AppModel->runUpdates()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}


Error on sudo -u www-data git submodule update --init --recursive

fatal: remote error: upload-pack: not our ref c31bb4b4be00d2a0db22c9a038f9fad8a5950efe
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'app/Lib/cakephp', but it did not contain c31bb4b4be00d2a0db22c9a038f9fad8a5950efe. Direct fetching of that commit failed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Could you try this commands before running the update?
```
sudo -u www-data git submodule sync
sudo -u www-data git submodule update --init --recursive
```

Or update via the MISP UI:
`/servers/serverSettings/diagnostics` -> `Update MISP`

Why: 
Due to changes in the remote of certain submodules we had to update the update commands to reflect these changes: https://github.com/MISP/MISP/commit/a4d20632c98ba1de8dbfc95697128b1ef722e3d0

**Comment by acfisher44** [comment]
Hey @righel I appreciate the reply.
After running those commands, while attempting to login to the UI, I am still redirected to a /users/routeafterlogin page with the "An Internal Error Has Occurred" message. 
All I can get to is the login page in the UI, but right after logging in, I cannot navigate anywhere. All I can see in the error. 

Not sure if this helps, but I did see the following after running:

error: Your local changes to the following files would be overwritten by checkout:
        .travis.yml
        CHANGES.txt
        README.rst
        docs/getting_started.rst
        docs/index.rst
        maec/utils/comparator.py
        maec/utils/deduplicator.py
        maec/version.py
        setup.py
        tox.ini
Please commit your changes or stash them before you switch branches.
Aborting

 AND

Unable to checkout '13e66105c9646156060d0896a4d54970ea358f44' in submodule path 'app/files/scripts/python-maec'

![image](https://user-images.githubusercontent.com/69737121/144435814-4fb57159-c610-43bd-b813-f04a242d21b0.png)

**Comment by righel** [comment]
You can check if the changes in those files are relevant executing `git diff`.
If those are permissions changes or things you didn't change by yourself, it's safe to do a `git stash` to discard the changes and then run the above commands.

Or configure `git` to ignore file permissions changes: 
```
git config --global core.fileMode false
git submodule foreach --recursive git config core.fileMode false
```

Alternatively a this commands should solve any inconsistent permissions in your MISP directory:
```
sudo chown -R www-data:www-data /var/www/MISP
sudo chmod -R 750 /var/www/MISP
sudo chmod -R g+ws /var/www/MISP/app/tmp
sudo chmod -R g+ws /var/www/MISP/app/files
sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp
```

**Comment by acfisher44** [comment]
Still receiving an error after login. Are there any other logs that may be able to assist with this issue? any help would be appreciated

**Comment by righel** [comment]
Can you share the logs again? are having the same errors in the logs?

Check this comment, it may help you: https://github.com/MISP/MISP/issues/7834#issuecomment-988710134

**Comment by acfisher44** [comment]
#1 /var/www/MISP/app/Model/Server.php(3443): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Model/AppModel.php(2093): Server->workerDiagnostics()
#3 /var/www/MISP/app/Controller/AppController.php(255): AppModel->runUpdates()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
root@fcu-repo:/var/www/MISP/app/tmp/logs# tail -50 error.log
#3 /var/www/MISP/app/Controller/AppController.php(255): AppModel->runUpdates()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
2021-12-08 15:22:54 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update]
Request URL: /users/view/24
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(311): BackgroundJobsTool->validateQueue()
#1 /var/www/MISP/app/Model/Server.php(3443): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Model/AppModel.php(2093): Server->workerDiagnostics()
#3 /var/www/MISP/app/Controller/AppController.php(255): AppModel->runUpdates()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
2021-12-08 15:23:06 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update]
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(311): BackgroundJobsTool->validateQueue()
#1 /var/www/MISP/app/Model/Server.php(3443): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Model/AppModel.php(2093): Server->workerDiagnostics()
#3 /var/www/MISP/app/Controller/AppController.php(255): AppModel->runUpdates()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
2021-12-08 15:23:08 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update]
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(311): BackgroundJobsTool->validateQueue()
#1 /var/www/MISP/app/Model/Server.php(3443): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Model/AppModel.php(2093): Server->workerDiagnostics()
#3 /var/www/MISP/app/Controller/AppController.php(255): AppModel->runUpdates()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}

**Comment by zHoopS** [comment]
(coworker of OP)

While doing a comparison with a working instance and this newly updated instance I found a few dependencies that had different versions. I switched to use php7.2 on this instance instead of the 7.4 which was not fruitful, but when switching back to 7.4 I'm not receiving the following error, with error.log shown below:

![image](https://user-images.githubusercontent.com/96838876/147688903-9fa8f9fe-ca85-46b7-84a0-19d2a34107e2.png)

2021-12-29 17:23:39 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'Selected driver is not enabled',
  'enabled' => false,
)
Request URL: /events/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#1 /var/www/MISP/app/Controller/AppController.php(812): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/AppController.php(137): AppController->_setupDatabaseConnection()
#3 /var/www/MISP/app/Controller/EventsController.php(63): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
