### ISSUE TITLE
Bug: Trouble upgrading to new Background Jobs

### ISSUE THREAD

**Issue by imidoriya** [MISP/MISP#8015]
### Expected behavior

This is a continuation of #7980 
I've been following the upgrade guide https://gist.github.com/righel/8ebc6c84341f2aea7d0bfa124e535ef8 but having issues.  This is partly for documentation for others that have issues, possible instruction updates, but also for troubleshooting.

@righel suggested it as a MISP Config, but I hadn't gotten that far in the instructions (maybe the instructions are out of order?)

### Actual behavior

Per the suggestion, I tried to turn on the new Background jobs anyway (configure MISP) by setting the password and enable to true, even though they were all giving FATAL errors.  Now I can't get to the admin page any longer `An Internal Error Has Occurred.`.  

The `misp-workers-errors.log` says this, even though the redis fields were option (I left them as is):
```
Notice Error: Undefined index: redis_host in [/var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php, line 580]

Notice Error: Undefined index: redis_port in [/var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php, line 580]

Error: Redis::connect() expects parameter 1 to be string, null given
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(580): Redis->connect(NULL, NULL)
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(118): BackgroundJobsTool->createRedisConnection()
#2 /var/www/MISP/app/Console/Command/StartWorkerShell.php(23): BackgroundJobsTool->__construct(Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): StartWorkerShell->initialize()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#5 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run(Array)
#6 {main}
```

Looking at my config, the redis information was there, but not in the new SimpleBackgroundJobs section.  It just had the supervisor stuff I had set.  I tried to add  the additional entries manually based on righel's post. Now all the worker jobs appear to be running when I do a `$ sudo supervisorctl status`, but the admin page is still offline.  Error log has this:
```
2021-12-02 21:26:31 Error: [GuzzleHttp\Psr7\Exception\MalformedUriException] Unable to parse URI: http://:/RPC2
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/guzzlehttp/psr7/src/Request.php(44): GuzzleHttp\Psr7\Uri->__construct('http://:/RPC2')
#1 /var/www/MISP/app/Vendor/php-http/message/src/MessageFactory/GuzzleMessageFactory.php(29): GuzzleHttp\Psr7\Request->__construct('POST', 'http://:/RPC2', Array, '<?xml version="...', '1.1')
#2 /var/www/MISP/app/Vendor/lstrojny/fxmlrpc/src/fXmlRpc/Transport/HttpAdapterTransport.php(50): Http\Message\MessageFactory\GuzzleMessageFactory->createRequest('POST', 'http://:/RPC2', Array, '<?xml version="...')
#3 /var/www/MISP/app/Vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(154): fXmlRpc\Transport\HttpAdapterTransport->send('http://:/RPC2', '<?xml version="...')
#4 /var/www/MISP/app/Vendor/supervisorphp/supervisor/src/Supervisor.php(94): fXmlRpc\Client->call('supervisor.getA...', Array)
#5 /var/www/MISP/app/Vendor/supervisorphp/supervisor/src/Supervisor.php(112): Supervisor\Supervisor->call('supervisor', 'getAllProcessIn...', Array)
#6 /var/www/MISP/app/Vendor/supervisorphp/supervisor/src/Supervisor.php(146): Supervisor\Supervisor->__call('getAllProcessIn...', Array)
#7 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(282): Supervisor\Supervisor->getAllProcesses()
#8 /var/www/MISP/app/Model/Server.php(7184): BackgroundJobsTool->getWorkers()
#9 /var/www/MISP/app/Model/Server.php(3401): Server->getWorkers()
#10 /var/www/MISP/app/Controller/ServersController.php(1166): Server->workerDiagnostics(0)
#11 [internal function]: ServersController->serverSettings()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#15 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
```

### Steps to reproduce

Trying to follow the guide after upgrading to 2.4.151

### Version

2.4.151 (b869ff91549436ce189be9ff76aa4d1581384f3f)

### Operating System

Lubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imidoriya** [comment]
I had forgotten to add in the `supervisor_host` and `supervisor_port`. Now it's working.  So the `app/Config/config.php` should end up looking like what @righel had posted.
```
  'MISP' => [
    ...,
  ],
  'SimpleBackgroundJobs' => [
    'enabled' => true,
    'redis_host' => 'localhost',
    'redis_port' => 6379,
    'redis_password' => '',
    'redis_database' => 1,
    'redis_namespace' => 'background_jobs',
    'max_job_history_ttl' => 86400,
    'track_status' => false,
    'supervisor_host' => 'localhost',
    'supervisor_port' => '9001',
    'supervisor_user' => 'supervisor',
    'supervisor_password' => 'supervisor',
  ],
```
Might need to tweek some things in the admin page to prevent a similar mistake by other users.
