### ISSUE TITLE
Bug: After last update can't get diagnostic page

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#8018]
### Expected behavior

Diagnostic page opens correctly

### Actual behavior
![изображение](https://user-images.githubusercontent.com/29750691/144958868-b9f95b8a-2853-4a6f-8b8f-10dd3135197f.png)

### Steps to reproduce

Don't know

### Version

2.4.151

### Operating System

CentOS

### Operating System version

7

### PHP version

7.2

### Browser

Firefox

### Relevant log output

```shell
2021-12-06 14:48:42 Error: [ProcessException] Command ''/var/www/MISP/venv/bin/python' '/var/www/MISP/app/files/scripts/stixtest.py'' return error code 126.
STDERR: 'sh: /var/www/MISP/venv/bin/python: Permission denied
'
STDOUT: ''
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(3221): ProcessTool::execute(''/var/www/MISP/...')
#1 /var/www/MISP/app/Controller/ServersController.php(1104): Server->stixDiagnostics(0)
#2 [internal function]: ServersController->serverSettings('diagnostics')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2021-12-06 14:51:47 Warning: Warning (2): rename(/var/www/MISP/app/tmp/logs/debug.log,/var/www/MISP/app/tmp/logs/debug.log.1638787907): Permission denied in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Log/Engine/FileLog.php, line 205]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
rename - [internal], line ??
FileLog::_rotateFile() - APP/Lib/cakephp/lib/Cake/Log/Engine/FileLog.php, line 205
FileLog::write() - APP/Lib/cakephp/lib/Cake/Log/Engine/FileLog.php, line 137
CakeLog::write() - APP/Lib/cakephp/lib/Cake/Log/CakeLog.php, line 445
CakeObject::log() - APP/Lib/cakephp/lib/Cake/Core/CakeObject.php, line 162
ServersController::serverSettings() - APP/Controller/ServersController.php, line 1055
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101

2021-12-06 14:51:48 Error: [ProcessException] Command ''/var/www/MISP/venv/bin/python' '/var/www/MISP/app/files/scripts/stixtest.py'' return error code 126.
STDERR: 'sh: /var/www/MISP/venv/bin/python: Permission denied
'
STDOUT: ''
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(3221): ProcessTool::execute(''/var/www/MISP/...')
#1 /var/www/MISP/app/Controller/ServersController.php(1104): Server->stixDiagnostics(0)
#2 [internal function]: ServersController->serverSettings('diagnostics')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @NailBash 
Looks like there are some filesystem permissions issues in your instance, files inside MISP dir should be owned by the web server user (`www-data` by default).

Running these commands should fix the issue:
```
sudo chown -R www-data:www-data /var/www/MISP
sudo chmod -R 750 /var/www/MISP
sudo chmod -R g+ws /var/www/MISP/app/tmp
sudo chmod -R g+ws /var/www/MISP/app/files
sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp
```

The error handling for this scenario was already fixed by https://github.com/MISP/MISP/pull/7997 which is merged to `develop` branch.

Let me know if that helps.

**Comment by NailBash** [comment]
![изображение](https://user-images.githubusercontent.com/29750691/144958468-72419425-0fdd-4254-936a-84dc75786c60.png)

Doesn't help
![изображение](https://user-images.githubusercontent.com/29750691/144958886-e2bdcc3b-9c4d-404a-8e54-3edca50ad4f8.png)

**Comment by righel** [comment]
Do you get the same errors in the logs?

**Comment by NailBash** [comment]
> Do you get the same errors in the logs?

yes
```
2021-12-07 13:08:25 Error: [ProcessException] Command ''/var/www/MISP/venv/bin/python' '/var/www/MISP/app/files/scripts/stixtest.py'' return error code 126.
STDERR: 'sh: /var/www/MISP/venv/bin/python: Permission denied
'
STDOUT: ''
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(3221): ProcessTool::execute(''/var/www/MISP/...')
#1 /var/www/MISP/app/Controller/ServersController.php(1104): Server->stixDiagnostics(0)
#2 [internal function]: ServersController->serverSettings('diagnostics')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

```

**Comment by righel** [comment]
Seems `apache` user does not have execute permission for  `/var/www/MISP/venv/bin/python` 

Could you try running the following command:
`sudo chmod u+x /var/www/MISP/venv/bin/python`

Try if you can execute it now:
`sudo -u apache /var/www/MISP/venv/bin/python --version`

**Comment by NailBash** [comment]
before sudo chmod u+x /var/www/MISP/venv/bin/python
![изображение](https://user-images.githubusercontent.com/29750691/145006158-a7deca8b-edba-4223-acb6-0ad1ae09a0a0.png)
and after
![изображение](https://user-images.githubusercontent.com/29750691/145006196-abf5f0be-d6f8-4971-a9c3-10559d183166.png)

Error still here

**Comment by righel** [comment]
Are you sure that `apache2` is running as `apache` user and not `www-data` / other ?
Check:
`ps -fC apache2,httpd`

**Comment by righel** [comment]
If user is correct, and SELinux is enabled try with:
`chcon -t httpd_sys_script_exec_t /var/www/MISP/venv/bin/python`

related issue comment: https://github.com/MISP/MISP/issues/5476#issuecomment-602046941

**Comment by NailBash** [comment]
Well, it works, when SElinux disabled, I will try this:
```
chcon -t httpd_sys_script_exec_t /var/www/MISP/venv/bin/python
```
P.S it worked, thank you
