### ISSUE TITLE
Support: Help with using restsearch

### ISSUE THREAD

**Issue by paligram** [MISP/MISP#8048]
### Support Questions

Im getting 500 error everytime I try to list attributes.

samething when I use pymisp to search for attributes it gives 500 erro
I have increased python memory to 16 g

still the same issue

### MISP version

2.4.152

### Operating System

ubuntu

### Operating System version

20.04

### PHP version

7.2

### Browser

chrome

### Browser version

95.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @paligram 
Could you please share your last bits of the error log? It's located in `/var/www/MISP/app/tmp/logs/error.log`

**Comment by paligram** [comment]
hello @righel 
sorry about the delay in responding
these were the logs I found 

Error: [InvalidArgumentException] Restsearch queries using GET and no parameters are not allowed. If you have passed parameters via a JSON body, make sure you use POST requests.

Request URL: /events/restSearch

Stack Trace:

#0 [internal function]: AppController->restSearch()

#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()

#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()

#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()

#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()

**Comment by righel** [comment]
It looks like your request payload is incorrect, look for missing headers or invalid json body.
Here is a sample curl request to that endpoint:
```
curl --location --insecure --request POST 'https://YOUR_MISP_HOST/events/restSearch' \
--header 'Accept: application/json' \
--header 'Authorization: YOUR_AUTH_TOKEN' \
--data-raw '{
    "page": "1",
    "limit": "10",
    "value": "OSINT"
}'
```
For more details on the endpoint such as possible filters check the docs:
https://www.misp-project.org/documentation/openapi.html#operation/restSearchEvents

**Comment by wabass** [comment]
> It looks like your request payload is incorrect, look for missing headers or invalid json body. Here is a sample curl request to that endpoint:
> 
> ```
> curl --location --insecure --request POST 'https://YOUR_MISP_HOST/events/restSearch' \
> --header 'Accept: application/json' \
> --header 'Authorization: YOUR_AUTH_TOKEN' \
> --data-raw '{
>     "page": "1",
>     "limit": "10",
>     "value": "OSINT"
> }'
> ```
> 
> For more details on the endpoint such as possible filters check the docs: https://www.misp-project.org/documentation/openapi.html#operation/restSearchEvents

How or where do we need to edit this permanently?

**Comment by Kagee** [comment]
This is an example, we don't know where or how you are doing your API requests.
