### ISSUE TITLE
Diagnostics page error post MISP upgrade

### ISSUE THREAD

**Issue by qbolbk59** [MISP/MISP#8078]
I recently upgraded MISP to 2.4.152. The upgrade worked fine on the lower env, but on the prd instance, i am not able to access the Diagnostics page and it always throws server error 500.
Checked the error logs as well, but there are no error related to this. 

Tried updating using CLI as well, but i am getting some perl warnings there as shown below:

![image](https://user-images.githubusercontent.com/43533246/148234993-3c3cbce0-c661-44bb-89c5-e2912b966dad.png)

Any idea where to look now ?

**Comment by righel** [comment]
Hello @qbolbk59,
Can you share more information about your issue?
* Operating system and version are you running on prod
* PHP version
* Relevant bits of `/var/www/MISP/app/tmp/logs/error.log`
* Context of that screenshot

**Comment by JoePJisc** [comment]
I've just upgraded a test instance and trying to access the diagnostics page triggers this in error.log

```
2022-01-07 15:58:09 Error: [Exception] DateTime::__construct() [<a href='http://php.net/datetime.construct'>datetime.construct</a>]: Failed to parse time string (1638287492) at position 7 (4): Unexpected character
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(470): DateTime->__construct()
#1 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(387): SecurityAudit->getKernelBuild()
#2 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(272): SecurityAudit->system()
#3 /var/www/MISP/app/Controller/ServersController.php(1187): SecurityAudit->run()
#4 [internal function]: ServersController->serverSettings()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
```

My setup is:

* CentOS 7 with 
* MISP 2.4.152 installed via MISP-RPM 
* MISP Modules 2.4.150
* misp-python-virtualenv 2.4.152

I've run `sudo -H -u apache /var/www/MISP/app/Console/cake Admin runUpdates`

**Comment by righel** [comment]
Hello @JoeP-oss
This issue was already fixed by commit https://github.com/MISP/MISP/commit/40f83a0329e5dde04f45ec8f00c281fd1b2c9c6c, please pull the code again. Check issue https://github.com/MISP/MISP/issues/8057
