### ISSUE TITLE
Field 'nationality' doesn't have a default value

### ISSUE THREAD

**Issue by zachsis** [MISP/MISP#810]
trying to access the initial login page from a clean install on CentOS7.2 and getting the error below: 

error: 
```
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(Organisation), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/UsersController.php(638): Model->save(Array)
#6 [internal function]: UsersController->login()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

```
cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

```
# php composer.phar show -i
composer/installers              v1.0.22 A multi-framework Composer library installer
kamisama/cake-resque             4.1.2   A CakePHP plugin for creating background jobs with Resque
kamisama/monolog-init            0.2.1   Very basic and light Dependency Injector Container for Monolog
kamisama/php-resque-ex           1.3.0   Redis backed library for creating background jobs and processing them later. PHP port based on resque for Ruby.
kamisama/php-resque-ex-scheduler 1.2.3   php-resque-ex-scheduler is a PHP port of resque-scheduler, which adds support for scheduling jobs to PHP-Resque.
kamisama/resque-status           0.0.2   A API for saving a php-resque worker settings and status
monolog/monolog                  1.17.2  Sends your logs to files, sockets, inboxes, databases and various web services
psr/log                          1.0.0   Common interface for logging libraries
```

```
# yum list installed | grep php
php55w.x86_64                    5.5.30-2.w7                     @webtatic      
php55w-cli.x86_64                5.5.30-2.w7                     @webtatic      
php55w-common.x86_64             5.5.30-2.w7                     @webtatic      
php55w-devel.x86_64              5.5.30-2.w7                     @webtatic      
php55w-gd.x86_64                 5.5.30-2.w7                     @webtatic      
php55w-intl.x86_64               5.5.30-2.w7                     @webtatic      
php55w-mbstring.x86_64           5.5.30-2.w7                     @webtatic      
php55w-mcrypt.x86_64             5.5.30-2.w7                     @webtatic      
php55w-mysql.x86_64              5.5.30-2.w7                     @webtatic      
php55w-opcache.x86_64            5.5.30-2.w7                     @webtatic      
php55w-pdo.x86_64                5.5.30-2.w7                     @webtatic      
php55w-pear.noarch               1:1.10.1-1.w7                   @webtatic      
php55w-pecl-geoip.x86_64         1.0.8-1.w7                      @webtatic      
php55w-pecl-igbinary.x86_64      1.2.1-2.w7                      @webtatic      
php55w-pecl-redis.x86_64         2.2.7-1.w7                      @webtatic      
php55w-process.x86_64            5.5.30-2.w7                     @webtatic      
php55w-xml.x86_64                5.5.30-2.w7                     @webtatic      
```

```
# php -v
PHP 5.5.30 (cli) (built: Oct 16 2015 07:35:20) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by cvandeplas** [comment]
https://github.com/MISP/MISP/blob/2.4/app/Controller/UsersController.php#L630 indeed doesn't have a nationality defined, while the SQL schema requires that field to be NOT NULL.
Marking this as a bug.

**Comment by iglocska** [comment]
It is indeed a bug, it looks like a mistake I made when exporting my db structure for the MYSQL.sql, the contextual fields should definitely be nullable. I'm working on a better way to maintain the DB via updates that I'm hoping to finish today, this will make for a great test case for it.

**Comment by Rafiot** [comment]
nationality field can be NULL, closing. 

https://github.com/MISP/MISP/blob/2.4/INSTALL/MYSQL.sql#L238
