### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by s3cr3search** [MISP/MISP#8102]
### Support Questions

I am attempting to install MISP on Ubuntu 20.04 server. 

It keeps failing with the following error -

 
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 144, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

The install does not prompt me for a Base URL so I am not sure how to resolve this. 

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
This is the test for continuous integration. Not sure why those tests were run during your installation process. This should have no impact on the MISP installation by itself.

**Comment by s3cr3search** [comment]
It seems to be affecting it as the install script will finish at 88% complete. There is the issue that I am not prompted for a base URL. Do you know of a way I can ensure that is prompted or already defined ?

**Comment by HamzaMhirsi** [comment]
Same issue here
Still didn't know why, I can login to the page but the misp platform not fully functional

**Comment by crypt0jan** [comment]
Same issue here:

```
The test files are missing, pulling it.
Cloning into 'tests/viper-test-files'...
remote: Enumerating objects: 110, done.
remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
Receiving objects: 100% (110/110), 15.18 MiB | 10.81 MiB/s, done.
Resolving deltas: 100% (24/24), done.
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 164, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)
#########################################################################################  (88%)
--------------------------------------------------------------------------------------------------------------------------
```

**Comment by denizilhan** [comment]
Same issue here too:

`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The test files are missing, pulling it.
Cloning into 'tests/viper-test-files'...
remote: Enumerating objects: 110, done.
remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
Receiving objects: 100% (110/110), 15.18 MiB | 4.84 MiB/s, done.
Resolving deltas: 100% (24/24), done.
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pymisp/api.py", line 164, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
#########################################################################################  (88%)`

**Comment by pariarajaee** [comment]
any solution? I have the same problem here!

**Comment by oferprtz-atbay** [comment]
Same here! someone figured it out?
