### ISSUE TITLE
Script.py throwing access_token error

### ISSUE THREAD

**Issue by abhinavkumar10** [MISP/MISP#8139]
### Support Questions

Script.py throwing access_token error

access_token error encountered when running script.py after following the steps and making required changes in the config.py file like adding access token and client secret. The script.py encounters error in RequestManager.py

Traceback (most recent call last):
File "script.py", line 100, in
main()
File "script.py", line 93, in main
with RequestManager(total_indicators) as request_manager:
File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 42, in enter
access_token = self._get_access_token(
File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 71, in _get_access_token
access_token = requests.post(
KeyError: 'access_token'

Regenerated app registration as-well in order to validate if error was related to client id and secret. Gives same result.

![image](https://user-images.githubusercontent.com/55996511/153273482-d7f33bf7-f408-4430-a761-196aefb2583f.png)

### MISP version

2.4.152

### Operating System

Ubuntu 

### Operating System version

20.04.3 LTS

### PHP version

PHP 7.4.3 

### Relevant log output

```shell
Traceback (most recent call last):
File "script.py", line 100, in
main()
File "script.py", line 93, in main
with RequestManager(total_indicators) as request_manager:
File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 42, in enter
access_token = self._get_access_token(
File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 71, in _get_access_token
access_token = requests.post(
KeyError: 'access_token'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imvignesh27** [comment]
I'm also receiving the same error. Let me know if you have resolved the issue.
