### ISSUE TITLE
Bug: /admin/users/login was not found

### ISSUE THREAD

**Issue by EvaYiYang** [MISP/MISP#8145]
### Expected behavior

After user login, MISP should direct users to Event Actions page. 

### Actual behavior

This is an intermittent issue. 
Sometime when admin users login, it shows the error "The requested address '/admin/users/login' was not found on this server. Refresh the page will bring users back to Event Actions page. 

### Steps to reproduce

Since the error is intermittent, we did not find a way to reproduce it. 

### Version

2.4.147

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome, Edge

### Relevant log output

```shell
Request URL: /admin/users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}

Error: [MissingActionException] Action UsersController::admin_login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'admin_login',
)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @EvaYiYang 
The `/admin/users/login` url does not exist. How did you end up there?
the login page is `/users/login`

**Comment by EvaYiYang** [comment]
Hi @righel, we are using AzureAD module to authenticate users. The issue happens whenever an administrator logs in, right after they click Login button.

**Comment by trafferty20** [comment]
Hello @EvaYiYang, 
Did you ever find a resolution to this issue? 
Thanks!
