### ISSUE TITLE
Support: [Error] Class 'Redis' not found / Login page not available

### ISSUE THREAD

**Issue by SivaPrem** [MISP/MISP#8151]
### Support Questions

Hello Team ,

Request some help with the Class 'Redis' not found 

lrwxrwxrwx 1 root root 9 févr. 16:32 php7.2.conf -> ../mods-available/php7.2.conf
lrwxrwxrwx 1 root root 9 févr.  16:32 php7.2.load -> ../mods-available/php7.2.load

Any help pls !!!!

### MISP version

2.4.153

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.2

### Browser

Chrome

### Relevant log output

```shell
[Error] Class 'Redis' not found
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/PubSubTool.php(21): PubSubTool->createRedisConnection(Array)
#1 /var/www/MISP/app/Model/AppModel.php(2548): PubSubTool->initTool()
#2 /var/www/MISP/app/Model/User.php(308): AppModel->getPubSubTool()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): User->afterSave(false, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#6 /var/www/MISP/app/Model/User.php(1384): Model->save(Array, true, Array)
#7 /var/www/MISP/app/Controller/UsersController.php(1290): User->updateLoginTimes(Array)
#8 /var/www/MISP/app/Controller/UsersController.php(1195): UsersController->_postlogin()
#9 [internal function]: UsersController->login()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello, seems you are missing the php-redis php extension. Try with:
`sudo apt-get install php-redis`

Let me know if that helps.

**Comment by SivaPrem** [comment]
Thanks Sir , I did have installed PHP-redis already on this machine - [php-redis is already the newest version (5.3.6+4.3.0-1]

Not sure Why I have this error , a bit stuck

**Comment by Kagee** [comment]
Please show the output of `apt show php-redis` (possible debug info) and then run run `phpenmod redis` (may solve your problem)
