### ISSUE TITLE
Bug: Auth key's allowed IPs overflow

### ISSUE THREAD

**Issue by 0xThiebaut** [MISP/MISP#8156]
### Expected behavior

When creating a new auth key, I expect the allowed IPs to be validated before being stored.

### Actual behavior

When creating a new auth key with a long list of allowed IPs, MISP inserts the JSON list as-is, resulting in a truncated record. This then results in MISP throwing an `UnexpectedValueException` error when trying to JSON decode the record such as in the logs and auth key list.

### Steps to reproduce

Create a new auth key with the Azure Cloud IP ranges as listed in [this gist](https://gist.githubusercontent.com/0xThiebaut/456ed7fba2b865e3b396847a1f6582af/raw/Azure%2520Cloud.csv) (as the list is too long for a GitHub comment).

### Version

2.4.152

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.2

### Browser

Firefox

### Browser version

97.0.1 (64-bit)

### Relevant log output

```shell
2022-02-22 13:14:36 Error: [UnexpectedValueException] Could not parse JSON: Control character error, possibly incorrectly encoded
Request URL: /admin/audit_logs/index
Stack Trace:
#0 /data/www/MISP/app/Model/AuditLog.php(167): AppModel->jsonDecode('{"user_id":33,"...')
#1 /data/www/MISP/app/Model/AuditLog.php(96): AuditLog->decodeChange('{"user_id":33,"...')
#2 /data/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): AuditLog->afterFind(Array, true)
#3 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3371): CakeEventManager->dispatch(Object(CakeEvent))
#4 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3057): Model->_filterResults(Array)
#5 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): Model->find('all', Array)
#7 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate(Object(AuditLog), Array, Array)
#8 /data/www/MISP/app/Controller/AuditLogsController.php(104): Controller->paginate()
#9 [internal function]: AuditLogsController->admin_index()
#10 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AuditLogsController), Array)
#11 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuditLogsController), Object(CakeRequest))
#13 /data/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}

2022-02-22 13:16:59 Error: [UnexpectedValueException] Could not parse JSON: Control character error, possibly incorrectly encoded
Request URL: /auth_keys/index/page:2
Stack Trace:
#0 /data/www/MISP/app/Model/AuthKey.php(94): AppModel->jsonDecode('["13.64.0.0\\/16...')
#1 /data/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): AuthKey->afterFind(Array, true)
#2 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3371): CakeEventManager->dispatch(Object(CakeEvent))
#3 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3057): Model->_filterResults(Array)
#4 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#5 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): Model->find('all', Array)
#6 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate(Object(AuthKey), Array, Array)
#7 /data/www/MISP/app/Controller/Component/CRUDComponent.php(53): Controller->paginate()
#8 /data/www/MISP/app/Controller/AuthKeysController.php(48): CRUDComponent->index(Array)
#9 [internal function]: AuthKeysController->index()
#10 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AuthKeysController), Array)
#11 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthKeysController), Object(CakeRequest))
#13 /data/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}

022-02-22 13:26:55 Error: [UnexpectedValueException] Could not parse JSON: Control character error, possibly incorrectly encoded
Request URL: /auth_keys/delete/55
Stack Trace:
#0 /data/www/MISP/app/Model/AuthKey.php(94): AppModel->jsonDecode('["13.64.0.0\\/16...')
#1 /data/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): AuthKey->afterFind(Array, true)
#2 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3371): CakeEventManager->dispatch(Object(CakeEvent))
#3 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3057): Model->_filterResults(Array)
#4 /data/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#5 /data/www/MISP/app/Controller/Component/CRUDComponent.php(274): Model->find('first', Array)
#6 /data/www/MISP/app/Controller/AuthKeysController.php(65): CRUDComponent->delete(55, Array)
#7 [internal function]: AuthKeysController->delete('55')
#8 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AuthKeysController), Array)
#9 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthKeysController), Object(CakeRequest))
#11 /data/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xThiebaut** [comment]
Closing as stale.
