### ISSUE TITLE
Bug:  install script

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [MISP/MISP#8169]
### Support Questions

AWS Instance Ubuntu 20.04

sudo apt-get update && sudo apt-get dist-upgrade
sudo reboot now
<relogin>
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c

Wasnt prompted for URL, only prompted to create misp User
(happens with -c -M)

### MISP version

2.4.152

### Operating System

Ubuntu Server

### Operating System version

20.04

### PHP version

Not installed

### Relevant log output

```shell
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 147, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)
#########################################################################################  (88%)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pilly170** [comment]
Ive tested on aws instance and virtualbox. Ive also tried redhat.. all give errors during install
Ive also tried using a env variable for url.  (http://localhost or http://127.0.0.1) but then get another error that it cant connect

**Comment by Phil-ThePower-Pearce** [comment]
Now also tried on ubuntu 22.04, same error
have to admit. I think Im going to give up on MISP
