### ISSUE TITLE
Bug: Error in install script

### ISSUE THREAD

**Issue by gallypette** [MISP/MISP#8206]
### Expected behavior

When installing MISP with `bash INSTALL.sh -c -M` installation finishes and the instance is functional (UI and API) but there is the following error just before getting the default credentials:
```
ERROR: apiosintds 1.8.3 has requirement pytz==2019.3, but you'll have pytz 2021.3 which is incompatible.
ERROR: apiosintds 1.8.3 has requirement validators==0.14.0, but you'll have validators 0.18.2 which is incompatible.
Installing collected packages: validators, pymisp
  Attempting uninstall: validators
    Found existing installation: validators 0.14.0
    Uninstalling validators-0.14.0:
      Successfully uninstalled validators-0.14.0
  Attempting uninstall: pymisp
    Found existing installation: pymisp 2.4.155.1
    Uninstalling pymisp-2.4.155.1:
      Successfully uninstalled pymisp-2.4.155.1
  Running setup.py develop for pymisp
Successfully installed pymisp validators-0.18.2
The test files are missing, pulling it.
Cloning into 'tests/viper-test-files'...
remote: Enumerating objects: 110, done.
remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
Receiving objects: 100% (110/110), 15.18 MiB | 12.46 MiB/s, done.
Resolving deltas: 100% (24/24), done.
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 147, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

----------------------------------------------------------------------
Ran 0 tests in 0.003s

FAILED (errors=1)
#########################################################################################  (88%)
```

### Actual behavior

no errors.

### Steps to reproduce

Install in a fresh ubuntu 20.04 with `bash INSTALL.sh -c -M`

### Version

2.5.155

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pilly170** [comment]
I have the same
https://github.com/MISP/MISP/issues/8169

Although it works, the modules section is incomplete/broken

**Comment by utkonos** [comment]
I am encountering the same problems as above. Looking back through the install output there are errors in various locations.


```
Setting "Security.auth_enforced" changed to 0
Setting "Security.log_each_individual_auth_fail" changed to 0
Setting "Security.rest_client_baseurl" changed to ""
Setting "Security.advanced_authkeys" changed to 0
Setting "Security.password_policy_length" changed to "12"
Setting "Security.password_policy_complexity" changed to "/^((?=.*\d)|(?=.*\W+))(?![\n])(?=.*[A-Z])(?=.*[a-z]).*$|.{16,}/"
Error: Method name must be a string
#0 /var/www/MISP/app/Console/Command/AdminShell.php(467): Server->serverSettingsEditValue()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->setSetting()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#5 {main}
Setting "Security.disable_browser_cache" changed to 1
Setting "Security.check_sec_fetch_site_header" changed to 1
Setting "Security.csp_enforce" changed to 1
Setting "Security.advanced_authkeys" changed to 1
Setting "Security.do_not_log_authkeys" changed to 1
Setting "Security.username_in_response_header" changed to 1
```

Python deps errors/warnings:

```
ERROR: dnspython3 1.15.0 has requirement dnspython==1.15.0, but you'll have dnspython 2.2.0 which is incompatible.
ERROR: oletools 0.60 has requirement pyparsing<3,>=2.1.0, but you'll have pyparsing 3.0.7 which is incompatible.
  WARNING: pymisp-2.4.155.1 2.4.155.1 does not provide the extra 'neo'
ERROR: apiosintds 1.8.3 has requirement pytz==2019.3, but you'll have pytz 2021.3 which is incompatible.
ERROR: apiosintds 1.8.3 has requirement validators==0.14.0, but you'll have validators 0.18.2 which is incompatible.
```

Final error:

```
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 147, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
#########################################################################################  (88%)
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

I reported part of the above in 3/2020:
https://github.com/MISP/MISP/issues/5722

**Comment by mrihtar** [comment]
The following error during installation
```
Error: Method name must be a string
#0 /var/www/MISP/app/Console/Command/AdminShell.php(467): Server->serverSettingsEditValue()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->setSetting()
```
could be fixed with the following change to the app/Model/Server.php:
```
--- a/app/Model/Server.php
+++ b/app/Model/Server.php
@@ -2151,8 +2151,10 @@ class Server extends AppModel
             if (isset($setting['test'])) {
                 if ($setting['test'] instanceof Closure) {
                     $testResult = $setting['test']($value);
-                } else {
+                } elseif (is_string($setting['test'])) {
                     $testResult = $this->{$setting['test']}($value);
+                } else {
+                    $testResult = true;  # No test defined for this setting: cannot fail
                 }
             } else {
                 $testResult = true;  # No test defined for this setting: cannot fail
```

**Comment by SteveClement** [comment]
Most of these errors are not relevant to the overall functioning of MISP.

If pyMISP tests fail, that ain`t great, but it also does not really matter for the core.

The cake commands are only tuneables to make a base MISP install more clean. e.g. Writing defaults to avoid having notifications etc. 

Overall, yall` are right, the script would need more sanity checks and should be tested more thoroughly.

**Comment by uhlhosting** [comment]
New fresh deployment:

Got:

```bash
Setting "Security.password_policy_complexity" changed to "/^((?=.*\d)|(?=.*\W+))(?![\n])(?=.*[A-Z])(?=.*[a-z]).*$|.{16,}/"
Error: Method name must be a string
#0 /var/www/MISP/app/Console/Command/AdminShell.php(493): Server->serverSettingsEditValue()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->setSetting()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#5 {main}
Setting "Security.disable_browser_cache" changed to 1
```
and

```bash
ERROR: aiohttp 3.8.3 has requirement charset-normalizer<3.0,>=2.0, but you'll have charset-normalizer 3.1.0 which is incompatible.
```

```bash
Setting "Plugin.Export_pdfexport_enabled" changed to 1
#################################################################################  (80%)
#####################################################################################  (84%)
#######################################################################################  (86%)
url = ""
key = "VZgoW8kFV1n0BNj5z1dXEMKvYsvt1bFNWnlaMo9e"
Entering 'pymisp/data/misp-objects'
From https://github.com/MISP/misp-objects
 * branch            main       -> FETCH_HEAD
Updating 402d7ad..9e4afdf
Fast-forward
 objects/network-socket/definition.json | 10 ++++++++++
 1 file changed, 10 insertions(+)
Entering 'pymisp/tools/pdf_fonts'
fatal: couldn't find remote ref main
fatal: run_command returned non-zero status for pymisp/tools/pdf_fonts
.
Obtaining file:///var/www/MISP/PyMISP
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  WARNING: pymisp-2.4.169.3 2.4.169.3 does not provide the extra 'neo'
Requirement already satisfied: publicsuffixlist<0.10.0,>=0.9.3 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (0.9.3)
Requirement already satisfied: jsonschema<5.0.0,>=4.17.3 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (4.17.3)
Requirement already satisfied: deprecated<2.0.0,>=1.2.13 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (1.2.13)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (2.8.2)
Requirement already satisfied: requests<3.0.0,>=2.28.2 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (2.28.2)
Requirement already satisfied: pydeep2<0.6.0,>=0.5.1; extra == "fileobjects" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (0.5.1)
Requirement already satisfied: python-magic<0.5.0,>=0.4.27; extra == "fileobjects" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (0.4.27)
Requirement already satisfied: lief<0.13.0,>=0.12.3; extra == "fileobjects" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (0.12.3)
Requirement already satisfied: beautifulsoup4==4.11.1; extra == "openioc" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.169.3) (4.11.1)
Collecting reportlab<4.0.0,>=3.6.12; extra == "pdfexport"
  Downloading reportlab-3.6.12-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 14.6 MB/s 
Collecting validators<0.21.0,>=0.20.0; extra == "virustotal"
  Downloading validators-0.20.0.tar.gz (30 kB)
    ERROR: Command errored out with exit status 1:
     command: /var/www/MISP/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-59k_1zzq/validators/setup.py'"'"'; __file__='"'"'/tmp/pip-install-59k_1zzq/validators/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-59k_1zzq/validators/pip-egg-info
         cwd: /tmp/pip-install-59k_1zzq/validators/
    Complete output (21 lines):
    /var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py:264: UserWarning: Unknown distribution option: 'build_requires'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-59k_1zzq/validators/setup.py", line 39, in <module>
        setup(
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
        _Distribution.__init__(
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
        self.finalize_options()
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
        for ep in sorted(loaded, key=by_order):
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 898, in <lambda>
        loaded = map(lambda e: e.load(), filtered)
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
        return functools.reduce(getattr, attrs, module)
    AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The test files are missing, pulling it.
Cloning into 'tests/viper-test-files'...
remote: Enumerating objects: 110, done.
remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
Receiving objects: 100% (110/110), 15.18 MiB | 22.97 MiB/s, done.
Resolving deltas: 100% (24/24), done.
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 65, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pymisp/api.py", line 164, in __init__
    raise NoURL('Please provide the URL of your MISP instance.')
pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
```
