### ISSUE TITLE
Support: Pull Error - Failed downloading the event [HttpSocketJsonException] Could not parse response as JSON

### ISSUE THREAD

**Issue by ahmedxuae91** [MISP/MISP#8209]
### Support Questions

Hi MISP Community and Support Team,

I synced MISP with server 1 and everything is working perfect.

My problem is only with server 2. as i configured it similar to server 1 for pull only and connectivity is working fine.

However, when pulling from server 2 i am getting below error:

`2022-03-15 13:39:01 Error: Failed downloading the event bea00646-9fcf-40c4-8955-ad0f28986db8 from remote server 2
[HttpSocketJsonException] Could not parse response as JSON.`

This is happening for all Events i am pulling.

Full logs:

`2022-03-15 13:39:01 Error: Failed downloading the event bea00646-9fcf-40c4-8955-ad0f28986db8 from remote server 2
[HttpSocketJsonException] Could not parse response as JSON.
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#1 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#2 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#7 {main}[JsonException] Syntax error
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(107): json_decode()
#1 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#2 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
2022-03-15 13:39:02 Error: Failed downloading the event 8cef1068-bc3a-46b2-a6e7-8a6dd17cede0 from remote server 2
[HttpSocketJsonException] Could not parse response as JSON.
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#1 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#2 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#7 {main}[JsonException] Syntax error
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(107): json_decode()
#1 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#2 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}`

Also under Jobs i can see the first pull stuck under 27% and the other failed to pull ( attached with this ticket ).

I tried to get Events JSON output manually using API request and parsed it manually using notepad++ Json parser and it was able to parse with no errors.

This error only when pulling using MISP directly.

Thanks

### MISP version

2.4.153

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
2022-03-15 13:39:01 Error: Failed downloading the event bea00646-9fcf-40c4-8955-ad0f28986db8 from remote server 2
[HttpSocketJsonException] Could not parse response as JSON.
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#1 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#2 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#7 {main}[JsonException] Syntax error
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(107): json_decode()
#1 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#2 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
2022-03-15 13:39:02 Error: Failed downloading the event 8cef1068-bc3a-46b2-a6e7-8a6dd17cede0 from remote server 2
[HttpSocketJsonException] Could not parse response as JSON.
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#1 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#2 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#7 {main}[JsonException] Syntax error
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(107): json_decode()
#1 /var/www/MISP/app/Model/Server.php(471): HttpSocketResponseExtended->json()
#2 /var/www/MISP/app/Model/Server.php(578): Server->__pullEvent()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
```

### Extra attachments

![1](https://user-images.githubusercontent.com/21212837/158360877-4a6db386-53cd-488c-bb21-b480ab94196b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahmedxuae91** [comment]
Update: the problem seems to be from remote server. I just synced it with another server and still facing same issue.
However, still not able to know why it is failing to sync.

**Comment by ahmedxuae91** [comment]
Update: as an alternative solution, i tried to use PyMISP feed generator to extract events and confiugure a feed.
But i am getting this error for all events it is trying to fetch:

to_feed() got an unexpected keyword argument 'with_local_tags' bb08a775-111c-41fa-9c63-04815bc6e9f6

**Comment by ahmedxuae91** [comment]
I was able to pull them as a feed by disabling with_distribution and with_local_tags.

Pulling directly from listed servers didn't work. I assume this is a bug as remote server has many custom distribution lists/sharing groups and local Tags.

**Comment by iglocska** [comment]
Weird, I just tried to fetch that very event and it seems to work fine. 

What would be interesting is contacting the owner of the instance you're pulling from and asking what they're seeing in their logs. The non JSON response means that something has gone awry on their side, they probably have a logged exception from your failed attempt to fetch the data.

**Comment by skchow654** [comment]
even I am facing the same issue
