### ISSUE TITLE
Bug: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous during OidcAuth login

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#8220]
### Expected behavior

Successful login:

```
2022-03-17 14:33:51 Info: OIDC: User `test@admin.test` – Trying login.
2022-03-17 14:33:51 Info: OIDC: User `test@admin.test` – User organisation `REDACTED` created with ID 3.
2022-03-17 14:33:51 Info: OIDC: User `test@admin.test` – Provided roles: misp-user, offline_access, uma_authorization, default-roles-misp
2022-03-17 14:33:51 Info: OIDC: User `test@admin.test` – Not found in database.
2022-03-17 14:33:51 Info: OIDC: User `test@admin.test` – Saved in database with ID 3
2022-03-17 14:33:51 Info: OIDC: User `test@admin.test` – Logged in.
```

### Actual behavior

Plugin produces an error while fetching user data:

```
2022-03-17 14:33:51 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
Request URL: /users/login?state=cICW0N4UNGJGy9Gr0Zlg3g&session_state=eef6ecfb-e38b-44df-8dbe-6d1688836360&code=4ea79d05-d0ab-4d9f-ac4e-d0fd7d020cfe.eef6ecfb-e38b-44df-8dbe-6d1688836360.d5462dd6-b667-4eec-9e8a-329825f56d3d
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php(382): Model->find()
#7 /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php(131): Oidc->_findUser()
#8 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(32): Oidc->authenticate()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#11 /var/www/MISP/app/Controller/UsersController.php(1188): AuthComponent->login()
#12 [internal function]: UsersController->login()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#16 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#17 {main}
```

### Steps to reproduce

Perform a login with a fresh setup MISP (`86832556a408818ebc25cfef3d74664dba08f9a3`) instance.

### Version

86832556a408818ebc25cfef3d74664dba08f9a3

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Thanks for report, this is already fixed in `develop` branch.
