### ISSUE TITLE
Bug: Database diacnostics that appear wrong

### ISSUE THREAD

**Issue by Kagee** [MISP/MISP#8242]
### Expected behavior

Just upgraded to v2.4.157 (f4e390ae27477a87a3de5cc7ab6c47d1360329ff), had no DB schema differences before this.

After update i had some schema differences i fixed, but also these three that seem wrong:

* `cryptographic_keys.key_data` should have the default value `NULL` (the litteral string)
* `cryptographic_keys.fingerprint` should have the default value `''` (the litteral string)
* `events.protected`, a tinyint column, should have the default value `NULL` (the litteral string)

To "fix" `cryptographic_keys.fingerprint` MISP also renders invalid HTML/Javascript code. The `"''"` terminates the `onclick="`
````
onclick="quickFixSchema(
    this, 
    'ALTER TABLE `cryptographic_keys` 
    MODIFY COLUMN `fingerprint` varchar(255) 
    DEFAULT "''" NOT NULL COLLATE utf8_bin ;'
)"
````
The diagnostig json from MISP-report.json is included below

### Actual behavior

Expected no changes required.

### Steps to reproduce

Upgrade to v2.4.157?

### Version

 v2.4.157 (f4e390ae27477a87a3de5cc7ab6c47d1360329ff)

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.4

### Browser

Chrome

### Browser version

99

### Relevant log output

```shell
"diagnostic": {
	"cryptographic_keys": [
		{
			"description": "Column `key_data` is different",
			"column_name": "key_data",
			"error_type": "column_different",
			"actual": {
				"column_name": "key_data",
				"is_nullable": "YES",
				"data_type": "text",
				"character_maximum_length": "65535",
				"numeric_precision": null,
				"collation_name": "utf8mb4_unicode_ci",
				"column_type": "text",
				"column_default": null,
				"extra": ""
			},
			"expected": {
				"column_name": "key_data",
				"is_nullable": "YES",
				"data_type": "text",
				"character_maximum_length": "65535",
				"numeric_precision": null,
				"collation_name": "utf8mb4_unicode_ci",
				"column_type": "text",
				"column_default": "NULL",
				"extra": ""
			},
			"is_critical": true,
			"sql": "ALTER TABLE `cryptographic_keys` MODIFY COLUMN `key_data` text  DEFAULT \"NULL\" NULL COLLATE utf8mb4_unicode_ci ;"
		},
		{
			"description": "Column `fingerprint` is different",
			"column_name": "fingerprint",
			"error_type": "column_different",
			"actual": {
				"column_name": "fingerprint",
				"is_nullable": "NO",
				"data_type": "varchar",
				"character_maximum_length": "255",
				"numeric_precision": null,
				"collation_name": "utf8_bin",
				"column_type": "varchar(255)",
				"column_default": "",
				"extra": ""
			},
			"expected": {
				"column_name": "fingerprint",
				"is_nullable": "NO",
				"data_type": "varchar",
				"character_maximum_length": "255",
				"numeric_precision": null,
				"collation_name": "utf8_bin",
				"column_type": "varchar(255)",
				"column_default": "''",
				"extra": ""
			},
			"is_critical": true,
			"sql": "ALTER TABLE `cryptographic_keys` MODIFY COLUMN `fingerprint` varchar(255)  DEFAULT \"''\" NOT NULL COLLATE utf8_bin ;"
		}
	],
	"events": [
		{
			"description": "Column `protected` is different",
			"column_name": "protected",
			"error_type": "column_different",
			"actual": {
				"column_name": "protected",
				"is_nullable": "YES",
				"data_type": "tinyint",
				"character_maximum_length": null,
				"numeric_precision": "3",
				"collation_name": null,
				"column_type": "tinyint(1)",
				"column_default": null,
				"extra": ""
			},
			"expected": {
				"column_name": "protected",
				"is_nullable": "YES",
				"data_type": "tinyint",
				"character_maximum_length": null,
				"numeric_precision": "3",
				"collation_name": null,
				"column_type": "tinyint(1)",
				"column_default": "NULL",
				"extra": ""
			},
			"is_critical": true,
			"sql": "ALTER TABLE `events` MODIFY COLUMN `protected` tinyint(1)  DEFAULT \"NULL\" NULL  ;"
		}
},        ],
	]
	"cryptographic_keys": [
		{
			"description": "Column `key_data` is different",
			"column_name": "key_data",
			"error_type": "column_different",
			"actual": {
				"column_name": "key_data",
				"is_nullable": "YES",
				"data_type": "text",
				"character_maximum_length": "65535",
				"numeric_precision": null,
				"collation_name": "utf8mb4_unicode_ci",
				"column_type": "text",
				"column_default": null,
				"extra": ""
			},
			"expected": {
				"column_name": "key_data",
				"is_nullable": "YES",
				"data_type": "text",
				"character_maximum_length": "65535",
				"numeric_precision": null,
				"collation_name": "utf8mb4_unicode_ci",
				"column_type": "text",
				"column_default": "NULL",
				"extra": ""
			},
			"is_critical": true,
			"sql": "ALTER TABLE `cryptographic_keys` MODIFY COLUMN `key_data` text  DEFAULT \"NULL\" NULL COLLATE utf8mb4_unicode_ci ;"
		},
		{
			"description": "Column `fingerprint` is different",
			"column_name": "fingerprint",
			"error_type": "column_different",
			"actual": {
				"column_name": "fingerprint",
				"is_nullable": "NO",
				"data_type": "varchar",
				"character_maximum_length": "255",
				"numeric_precision": null,
				"collation_name": "utf8_bin",
				"column_type": "varchar(255)",
				"column_default": "",
				"extra": ""
			},
			"expected": {
				"column_name": "fingerprint",
				"is_nullable": "NO",
				"data_type": "varchar",
				"character_maximum_length": "255",
				"numeric_precision": null,
				"collation_name": "utf8_bin",
				"column_type": "varchar(255)",
				"column_default": "''",
				"extra": ""
			},
			"is_critical": true,
			"sql": "ALTER TABLE `cryptographic_keys` MODIFY COLUMN `fingerprint` varchar(255)  DEFAULT \"''\" NOT NULL COLLATE utf8_bin ;"
		}
	],
	"events": [
		{
			"description": "Column `protected` is different",
			"column_name": "protected",
			"error_type": "column_different",
			"actual": {
				"column_name": "protected",
				"is_nullable": "YES",
				"data_type": "tinyint",
				"character_maximum_length": null,
				"numeric_precision": "3",
				"collation_name": null,
				"column_type": "tinyint(1)",
				"column_default": null,
				"extra": ""
			},
			"expected": {
				"column_name": "protected",
				"is_nullable": "YES",
				"data_type": "tinyint",
				"character_maximum_length": null,
				"numeric_precision": "3",
				"collation_name": null,
				"column_type": "tinyint(1)",
				"column_default": "NULL",
				"extra": ""
			},
			"is_critical": true,
			"sql": "ALTER TABLE `events` MODIFY COLUMN `protected` tinyint(1)  DEFAULT \"NULL\" NULL  ;"
		}
	]
},
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
I have tried setting `key_data` and `protected` to `DEFAULT NULL` (instead of `DEFAULT "NULL"`) but that does not hide the error.

**Comment by Kagee** [comment]
![image](https://user-images.githubusercontent.com/686579/160152842-1ec580bf-d6c0-4e58-a6c7-724acd944f02.png)

**Comment by qbolbk59** [comment]
I have the same issue. Though in the table, the default is set to NULL, but i still see this error in the Diagnostic page.

![image](https://user-images.githubusercontent.com/43533246/160833851-4bea0710-41e4-400c-a0f7-b414686a5f65.png)

**Comment by qbolbk59** [comment]
@Kagee are you able to open the events ? Unfortunately i am not even able to open any events post the upgrade and get error "An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator."

When i check the error logs, i can see error as 
"2022-03-30 14:35:16 Error: [MissingTableException] Table cryptographic_keys for model CryptographicKey was not found in datasource default. Exception Attributes: array ( 'table' => 'cryptographic_keys', 'class' => 'CryptographicKey', 'ds' => 'default', ) Request URL: /events/view/256 Stack Trace: #0 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource() #1 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource() #2 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(2663): Model->schema() #3 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1886): DboSource->fields() #4 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1377): DboSource->generateAssociationQuery() #5 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation() #6 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read() #7 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource() #8 /app/MISP/app/Model/Event.php(2115): Model->find() #9 /app/MISP/app/Controller/EventsController.php(1825): Event->fetchEvent() #10 [internal function]: EventsController->view() #11 /app/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs() #12 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction() #13 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke() #14 /app/MISP/app/webroot/index.php(99): Dispatcher->dispatch() #15 {main}"

**Comment by Kagee** [comment]
@qbolbk59 I do not remember having to fix that table. What version + git hash are you on? Can you screenshot your whole db diagnostic?

**Comment by qbolbk59** [comment]
@Kagee I am at 2.4 version.
I have the same db diagnostic as you have. see below:

![image](https://user-images.githubusercontent.com/43533246/162377846-946ca573-1add-477e-9cb9-906810e60b50.png)

**Comment by qbolbk59** [comment]
I even tried to rebuild this particular table, but still no luck. I can't even see the events anymore. It simply throws the error that I provided previously.

**Comment by marjatech** [comment]
Have the same db diagnostics which cannot be resolved. however it seems to affect somehow Ubuntu 18.04 since my 20.04 instances did not show any db diagnostics after the update.  
MariaDB versions: 10.1.48 vs. 10.3.34
