### ISSUE TITLE
Error when you display your profile

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#836]
Hello all,

An error "Can't use function return value in write context in [/var/www/MISP/app/Controller/UsersController.php, line 604]" occurs when I want to display "My profile" (click "Global Actions" -> "My profile").

The Strack trace is the following:

```
2016-01-10 18:51:10 Error: Fatal Error (64): Can't use function return value in write context in [/var/www/MISP/app/Controller/UsersController.php, line 604]
2016-01-10 18:51:10 Error: [FatalErrorException] Can't use function return value in write context
Request URL: /users/view/me
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Can't use funct...', '/var/www/MISP/a...', 604)
#1 [internal function]: ErrorHandler::handleError(64, 'Can't use funct...', '/var/www/MISP/a...', 604, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 64, 'Can't use funct...', '/var/www/MISP/a...', 604, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

I quickly skirted this issue by modifying the following lines (UsersController.php) : 

```
--- a/app/Controller/UsersController.php
+++ b/app/Controller/UsersController.php
@@ -601,9 +601,16 @@ class UsersController extends AppController {
                        }
                                
                        if ($this->User->Organisation->find('count', array('conditions' => array('Organisation.local' => true))) == 0) {
+                               $misp_org = Configure::read('MISP.org');
                                $org = array('Organisation' => array(
                                                'id' => 1,
-                                               'name' => !empty(Configure::read('MISP.org')) ? Configure::read('MISP.org') : 'ADMIN',
+                                               'name' => !empty($misp_org) ? $misp_org : 'ADMIN',
                                                'description' => 'Automatically generated admin organisation',
                                                'type' => 'ADMIN',
                                                'uuid' => $this->User->Organisation->generateUuid(),
```
 
Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.4 and PHP version : 5.4.44

**Comment by iglocska** [comment]
Hello there, this is caused by empty() only accepting variables prior to PHP 5.5. There are a few things (including this) which break MISP under PHP < 5.5, but considering that 5.4 has reached end of life a back we highly suggest that you upgrade to at least PHP 5.5 instead.
