### ISSUE TITLE
Bug: Race Condition During Event Creation If Server Pull Called Twice

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#8365]
### Expected behavior

MISP should either gracefully refuse to try and sync with the same server in the same direction more than once concurrently, or handle the race condition of multiple sync jobs trying to create the same event.

### Actual behavior

If two overlapping pulls are started for the same server, especially if MISP needs to create a large number of new events, the following error sometimes crashes the sync job.

```
Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '00000000-1111-2222-3333-444444444444' for key 'uuid'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Event.php(3689): Model->save()
#6 /var/www/MISP/app/Model/Server.php(434): Event->_add()
#7 /var/www/MISP/app/Model/Server.php(503): Server->__checkIfPulledEventExistsAndAddOrUpdate()
#8 /var/www/MISP/app/Model/Server.php(591): Server->__pullEvent()
#9 /var/www/MISP/app/Console/Command/ServerShell.php(126): Server->pull()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#13 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#14 {main}
```

## Workaround

I've worked around this by creating a bash script with a mutex that uses `cake`, to sequentially pull each enabled feed, pull from each server, then push to each server; which runs on a cron schedule. 

With the move away from `cake`, I've tried to recreate this with `PyMISP`, but note that `PyMISP.server_pull(Server)` (understandably) triggers the sync and moves on, i.e. doesn't block the thread until the sync is done, so the same race conditon would exists if a sync takes longer than the cron schedule window.

### Steps to reproduce

1. Set up a source server with a high number of sync-able events / attributes.
2. Add the server to a destination server as a pull partnership.
3. Start multiple pulls from the source server, so they overlap.

### Version

2.4.158

### Operating System

CentOS

### Operating System version

7.9.2009

### PHP version

7.4.29

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoePJisc** [comment]
For anyone interested, this is a cut down version of the workaround script I'm currently using:

```bash
#!/bin/bash
#
# Run all current sync partnerships, ensuring only one set of syncs runs at once
# and that all new events are pulled in before any pushing.

# Ensure script is running as Apache user
if [ "$(whoami)" != "apache" ]; then
    echo "Script must be run as user: apache"
    exit 1
fi

# Obtain Execution Lock
exec 9>/tmp/misp-syncing.pid
if ! flock -n 9  ; then
    echo 'another instance is running';
    exit 2
fi

echo "Pulling Feeds"
echo "-CIRCL OSINT Feed"
/var/www/MISP/app/Console/cake Server fetchFeed 1 1 2>/dev/null
echo "-Another Feed"
/var/www/MISP/app/Console/cake Server fetchFeed 1 2 2>/dev/null
# ... repeat as required ...
echo
echo "Pulling from servers"
echo "-A Server"
/var/www/MISP/app/Console/cake server pull 1 1 full 2>/dev/null
echo "-B Server"
/var/www/MISP/app/Console/cake server pull 1 2 full 2>/dev/null
# ... repeat as required ...
echo
echo "Pushing to servers"
echo "-B Server"
/var/www/MISP/app/Console/cake server push 1 2 full 2>/dev/null
echo "-C Server"
/var/www/MISP/app/Console/cake server push 1 3 full 2>/dev/null
# ... repeat as required ...
echo "Done"
```

The downside, if you add a new feed or server and it takes a long time to do the initial pull, nothing else will sync until that finishes.
