### ISSUE TITLE
Workers are not working

### ISSUE THREAD

**Issue by tberky** [MISP/MISP#8383]
### Support Questions

I am unable to start workers... Tried a lot of issues here and was not successful.
![image](https://user-images.githubusercontent.com/69008406/168999328-5c9aa316-b1a9-4227-a111-7f6cc8ef9ca4.png)

### MISP version

2.4.158

### Operating System

Kali

### Operating System version

2022-04-01

### PHP version

8.1.6

### Relevant log output

```shell
sudo -u www-data bash /var/www/MISP/app/Console/worker/stop.sh                                                           1 ⨯
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(103): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(292): Resque_Worker::all()
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(637): CakeResque::getWorkers()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->stop()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}

 sudo -u www-data bash /var/www/MISP/app/Console/worker/start.sh
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(103): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(292): Resque_Worker::all()
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(637): CakeResque::getWorkers()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->stop()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}
Creating workers
Starting worker ... Done
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php(56): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(578): ResqueStatus\ResqueStatus->addWorker()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->start()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
Creating workers
Starting worker ... Done
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php(56): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(578): ResqueStatus\ResqueStatus->addWorker()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->start()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
Creating workers
Starting worker ... Done
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php(56): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(578): ResqueStatus\ResqueStatus->addWorker()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->start()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
Creating workers
Starting worker ... Done
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php(56): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(578): ResqueStatus\ResqueStatus->addWorker()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->start()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
Creating workers
Starting worker ... Done
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php(56): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(578): ResqueStatus\ResqueStatus->addWorker()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->start()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}
Creating the scheduler workers
Error: implode(): Argument #2 ($array) must be of type ?array, string given
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php(73): implode()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call()
#2 /var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php(91): RedisApi->__call()
#3 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(476): ResqueStatus\ResqueStatus->isRunningSchedulerWorker()
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(443): CakeResqueShell->start()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): CakeResqueShell->startScheduler()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @tberky
I see you are using PHP version 8.1.6, MISP currently does not support PHP versions +7.4.

You will have to downgrade to version 7.4 at most.

Hope this helps.
