### ISSUE TITLE
Bug: Kafka not publishing reliably

### ISSUE THREAD

**Issue by UFOSmuggler** [MISP/MISP#8392]
### Expected behavior

When publishing Kafka notifications, the Kafka broker should receive complete topics from the MISP producer always.

### Actual behavior

Kafka topics do not always publish (completely).  When they do, everything is as expected.  

When they do not, the Kafka server network processor debug logs seem to suggest the producer ended the conversation prematurely:

```
[2022-05-19 22:32:48,571] DEBUG Accepted connection from /127.0.0.1:37996 on /127.0.0.1:9092 and assigned it to processor 0, sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400] (kafka.network.Acceptor)
[2022-05-19 22:32:48,571] DEBUG Processor 0 listening to new connection from /127.0.0.1:37996 (kafka.network.Processor)
[2022-05-19 22:32:48,575] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=0] Connection with /127.0.0.1 disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
        at kafka.network.Processor.poll(SocketServer.scala:989)
        at kafka.network.Processor.run(SocketServer.scala:892)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Steps to reproduce

Install as per documentation and configure the rdkafka plugin to talk to a broker, enable event notifications.  Add several events (no need for tags/attributes/publishing, just defaults and event info is fine) and see which were published on the relevant topic.

**System specifics:
Rhel 7.9:**
MISP 2.4.157
librdkafka.x86_64            0.11.5-1.el7          @epel
librdkafka1php.x86_64        1.8.2-1.el7.remi      @remi
php-pecl-rdkafka6.x86_64     6.0.1-1.el7.remi.7.4  @remi-php74
Speaking to AWS MSK cluster w/Apache Kafka 2.6.2
/etc/rdkafka.conf file passed to MISP, configured to deal with self-signed TLS

**Ubuntu 20.04:**
MISP 2.4.157 & 2.4.158
ii  librdkafka++1:amd64                   1.2.1-1ubuntu1                             amd64        library implementing the Apache Kafka protocol (C++ bindings)
ii  librdkafka-dev:amd64                  1.2.1-1ubuntu1                             amd64        library implementing the Apache Kafka protocol (development headers)
ii  librdkafka1:amd64                     1.2.1-1ubuntu1                             amd64        library implementing the Apache Kafka protocol
PECL rdkafka 6.0.1   stable
Speaking to Apache Kafka v3.1.0
no /etc/rdkafka.conf passed to MISP, no TLS etc...

This seems to be caused by https://github.com/MISP/MISP/blob/a3d87b6854f8a9d8bffe7dac3da69afa569ff208/app/Lib/Tools/KafkaPubTool.php#L49 not polling until the kafka producer output queue is empty.  The producer script then ends, closing the connection to the broker, producing the referenced logs.

Changing this to something like:

```
            if (!empty($this->rdkafka)) {
                $topic = $this->rdkafka->newTopic($topicName);
                $topic->produce(RD_KAFKA_PARTITION_UA, 0, $body);
                while ($this->rdkafka->getOutQLen() > 0) {
                    $this->rdkafka->poll(0);
                }
            }
```

seems to fix the issue.  I'm not very good at PHP so I have no idea if this is a reasonable and safe way to resolve this issue.

I won't be surprised if you tell me I'm using the wrong version of the rdkafka libs or something, as I'm pretty surprised to be (I think) the first one to report this.  Apologies in advance if this is the case.

Thanks for your assistance!

### Version

2.4.157-8

### Operating System

Ubuntu 20.04 and RHEL7.9

### Operating System version

Ubuntu 20.04 and RHEL7.9

### PHP version

7.4

### Browser

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36

### Browser version

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36

### Relevant log output

```shell
This is the same as above, just including here for completeness

[2022-05-19 22:32:48,571] DEBUG Accepted connection from /127.0.0.1:37996 on /127.0.0.1:9092 and assigned it to processor 0, sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400] (kafka.network.Acceptor)
[2022-05-19 22:32:48,571] DEBUG Processor 0 listening to new connection from /127.0.0.1:37996 (kafka.network.Processor)
[2022-05-19 22:32:48,575] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=0] Connection with /127.0.0.1 disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
        at kafka.network.Processor.poll(SocketServer.scala:989)
        at kafka.network.Processor.run(SocketServer.scala:892)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dragsu** [comment]
@UFOSmuggler have you had any luck with this? I have enabled `misp_event` topic, and I can see the topic get created in Kafka however when I do event modifications nothing gets written into the `misp_event`  topic.

I did not set `Plugin.Kafka_rdkafka_config` value and Kafka is a very basic setup as explained under `Accessing Apache Kafka with internal and external clients` in [here](https://hub.docker.com/r/bitnami/kafka/) .

**Comment by UFOSmuggler** [comment]
@dragsu g'day mate, one project i'm involved with has been using the changes i suggest above successfully for quite a while now.

see if you get similar kafka logs.

**Comment by dragsu** [comment]
@UFOSmuggler G'day,

I tried that and it worked, thank you. I went and did a bit of googling and found https://idealo.github.io/php-rdkafka-ffi/usage/producer/. It suggests flushing the queue before exiting ( also in official docs in [here](https://github.com/confluentinc/librdkafka/blob/master/INTRODUCTION.md#producer)).

That might be the proper fix.

**Comment by UFOSmuggler** [comment]
@dragsu glad you got it going mate.  would be nice if this got fixed though :D 

i dont currently have an environment with kafka to bugger about in to test, so i cant really easily test the other stuff you found in the docs.
