### ISSUE TITLE
Support: Error when import STIX2 json file

### ISSUE THREAD

**Issue by sholland-bamboohealth** [MISP/MISP#8410]
### Support Questions

This is similar to support request 8404, but everything shows updated. I am trying to upload a stix 2 file via the web interface and I'm getting the same error (see attachment).
![mispversion](https://user-images.githubusercontent.com/93221855/170545735-1560931f-dfb7-4b57-8ff8-c6f34017a8fb.PNG)

![submodulesversion](https://user-images.githubusercontent.com/93221855/170545756-67cb256c-e713-4753-b181-3cb476a5ac6b.PNG)

![misperror](https://user-images.githubusercontent.com/93221855/170546229-028473a8-884d-4d12-9685-cc177103d3d4.PNG)
.

### MISP version

v2.4.158

### Operating System

ubuntu

### Operating System version

20.04.4 LTS

### PHP version

7.4.3 (Up to date)

### Browser

chrome

### Browser version

101

### Relevant log output

```shell
[2022-05-26 13:16:46 1124] Running command /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPcM2bW9 1 event /var/www/MISP/app/files/scripts/tmp/synonymsToTagNames.json
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2083, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2075, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
TypeError: parse() got an unexpected keyword argument 'interoperability'
[2022-05-26 13:16:47 1124] Process finished with return code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ryan-niemes-helix** [comment]
seeing a similar issue with my install. I'm leveragint the cic-misp scripts which allow me to import events from cyware. Using the cli to import events generates this error. Removing the "interoperability=True" seems to fix the issue.

**Comment by BedeschiL** [comment]
I can confirm that editing : app/files/scripts/stix2/stix2misp.py (line 2075) is working for me.
(Docker install) path to the file : your/docker/data/web/app/files/scripts/stix2misp.py

Unfortunately i still got an error with some nameTag.
