### ISSUE TITLE
Support:  OIDC not work

### ISSUE THREAD

**Issue by raihalea** [MISP/MISP#8437]
### Support Questions

We are trying to use OIDC with AWS Cognito and probably already have the necessary information set up for integration.

After the redirect, the login will not complete and you will be redirected to a page.

`$roles` always seems to be null.
I tried the code below and I was able to login successfully.
`./Plugin/OidcAuth/Lib/Oidc.php`
```
        $roleProperty = $this->getConfig('roles_property', 'roles');
        $roles = $claims->{$roleProperty} ? $oidc->requestUserInfo($roleProperty);
        $roles = array( 1 => 'user');    // ADDED THIS LINE
        if ($roles === null) {
            $this->log($user['email'], "Role property `$roleProperty` is missing in claims.");
            return false;
        }
```

Please let me know about the settings to enable OIDC correctly.
Is there something missing in the IdP user information?

The configuration file is as follows.
```
$config = array(
    ...
    'Security' => array(
        'auth' =>
            array (
                0 => 'OidcAuth.Oidc',
        ),
    ),
    ...

    ...
  'OidcAuth' =>
  array (
    'provider_url' => 'https://cognito-idp.ap-northeast-1.amazonaws.com/XXXXXX/.well-known/openid-configuration',
    'client_id' => 'XXXXXXXXX',
    'client_secret' => 'XXXXXXXXXXXXXXXXXXXXXXXX',
    'role_mapper' =>
    array (
      'user' => 3,
      'admin' => 1,
    ),
    'default_org' => 'default',
  ),
```

### MISP version

2.4.159

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Relevant log output

```shell
2022-06-09 16:48:32 Error: [JakubOnderka\ErrorResponse] Error 'invalid_grant' received from IdP
Request URL: /users/login?code=b34e8b26-d629-461c-8ab7-275817d6e546&state=qPwjn1pww7fORK1RCj7_6A
Stack Trace:
#0 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(982): JakubOnderka\OpenIDConnectClient->endpointRequest()
#1 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(460): JakubOnderka\OpenIDConnectClient->requestTokens()
#2 /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php(22): JakubOnderka\OpenIDConnectClient->authenticate()
#3 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(32): Oidc->authenticate()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#6 /var/www/MISP/app/Controller/UsersController.php(1177): AuthComponent->login()
#7 [internal function]: UsersController->login()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#12 {main}
```

### Extra attachments

`debug.log`
`User` in the last line is empty
```
2022-06-09 16:25:13 Info: OIDC: User `MY_MAIL_ADDRESS` – Trying login.
2022-06-09 16:25:13 Info: OIDC: User `MY_MAIL_ADDRESS` – User organisation `default` found with ID 2.
2022-06-09 16:25:14 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php, line 63]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Oidc::authenticate() - APP/Plugin/OidcAuth/Lib/Oidc.php, line 63
OidcAuthenticate::authenticate() - APP/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php, line 32
AuthComponent::identify() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 772
AuthComponent::login() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 612
UsersController::login() - APP/Controller/UsersController.php, line 1177
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-06-09 16:25:14 Info: OIDC: User `` – Role property `roles` is missing in claims.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Benni0** [comment]
Hi @aisoulea 
it seems there is no roles claim in your JWT.
I've also discussed this problem here: https://github.com/NUKIB/misp/issues/20#issuecomment-1029891811
Maybe that will help.
