### ISSUE TITLE
Bug: Some pages in MISP are showing 500 error

### ISSUE THREAD

**Issue by ag-michael** [MISP/MISP#8451]
### Expected behavior

Pages will load as normal

### Actual behavior

`An Internal Error Has Occurred.` is displayed , error log below.

### Steps to reproduce

Try to display scheduled tasks '/tasks'

### Version

2.4.158

### Operating System

Ubuntu

### Operating System version

18

### PHP version

7.2

### Relevant log output

```shell
2022-06-15 17:04:42 Error: [PDOException] SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
Request URL: /tasks
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(503): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(320): DboSource->_execute('SELECT CHARACTE...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(377): Mysql->getCharsetName('utf8_bin')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1397): Mysql->describe(Object(Task))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(2664): Model->schema()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1175): DboSource->fields(Object(Task))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Task), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#8 /var/www/MISP/app/Controller/TasksController.php(42): Model->find('first', Array)
#9 /var/www/MISP/app/Controller/TasksController.php(24): TasksController->__checkTasks()
#10 [internal function]: TasksController->index()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
```
```


### Extra attachments

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ag-michael** [comment]
Anyone looked at this yet?

**Comment by dazed51** [comment]
Hello, 

We are experiencing the same issue with our misp instance after the last release. Upon logging in, users getting the 500 error, but navigating within the rest of the app seems to be fine with errors.

I tried both methods of patching the application that was suggested.

Thanks
