### ISSUE TITLE
Support: Getting error response is not in Jason error 500 , can't connect to MISP

### ISSUE THREAD

**Issue by Prash9682** [MISP/MISP#8455]
### Support Questions

Hi , 
Sentinel Connector is showing connected, but not showing any feeds , 
When I run python3 script.py got following error.
Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.159 - Python 3.8', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': '***************', 'content-type': 'application/json'}
Request body:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 172, in __init__
    response = self.recommended_pymisp_version
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 229, in recommended_pymisp_version
    misp_version = self.misp_instance_version
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 259, in misp_instance_version
    return self._check_json_response(response)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 3497, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 3514, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
Traceback (most recent call last):
  File "script.py", line 100, in <module>
    main()
  File "script.py", line 69, in main
    events = _get_events()
  File "script.py", line 14, in _get_events
    misp = ExpandedPyMISP(config.misp_domain, config.misp_key, config.misp_verifycert)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 193, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP 

### MISP version

2.4.151

### Operating System

Ubantu

### Operating System version

20.04

### PHP version

7.1

### Relevant log output

```shell
Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.159 - Python 3.8', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': '***************', 'content-type': 'application/json'}
Request body:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 172, in __init__
    response = self.recommended_pymisp_version
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 229, in recommended_pymisp_version
    misp_version = self.misp_instance_version
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 259, in misp_instance_version
    return self._check_json_response(response)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 3497, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 3514, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
Traceback (most recent call last):
  File "script.py", line 100, in <module>
    main()
  File "script.py", line 69, in main
    events = _get_events()
  File "script.py", line 14, in _get_events
    misp = ExpandedPyMISP(config.misp_domain, config.misp_key, config.misp_verifycert)
  File "/usr/local/lib/python3.8/dist-packages/pymisp/api.py", line 193, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP
```

### Extra attachments

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
As mentioned in the error log:

- Review the URL used to connect to MISP.  Can you connect via the web interface of MISP?
- Check the error log of your MISP instance as you get back a 500 error message
- Update your MISP to the latest version as you are running old and vulnerable version

**Comment by Prash9682** [comment]
Yes I can connect it via Web interface , now I'm getting only the error when I tried to run python3 script.py it is saying 0 packets send  "An Internal Error Has Occurred.  If the problem persists, please contact administrator". While seeing the events also I'm getting same error

**Comment by Prash9682** [comment]
Can someone please let me know which URL's I need to whitelist on proxy for Sentinel as For scheduling daily run for python script daily internet will be needed. and we want to give internet through proxy by whitelisting Url's MISP URL I have whitelisted similarly for sentinel connection will be there be any URL 

Will be great if get quick response as we are doing this for client
