### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by JakKAaj** [MISP/MISP#8465]
### Support Questions

Hi, 

When installing Install.sh I got an error. Can you help?

### MISP version

2.4

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

PHP 7.4.3

### Relevant log output

```shell
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-x52x7rnd/setup.py", line 32, in <module>
          setup(
        File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 139, in setup
          _setup_distribution = dist = klass(attrs)
        File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 477, in __init__
          _Distribution.__init__(
        File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 275, in __init__
          self.finalize_options()
        File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 900, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 899, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
--------------------------------------
```

### Extra attachments

Collecting git+https://github.com/kbandla/pydeep.git
  Cloning https://github.com/kbandla/pydeep.git to /tmp/pip-req-build-yxqu5ioj
  Resolved https://github.com/kbandla/pydeep.git to commit 010b444245bf66545119ce7dc561ee36a62dd5f5
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakKAaj** [comment]
Again the same issue

Downloading validators-0.19.0.tar.gz (30 kB)
    ERROR: Command errored out with exit status 1:
     command: /var/www/MISP/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nugwdmxx/validators/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nugwdmxx/validators/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-nugwdmxx/validators/pip-egg-info
         cwd: /tmp/pip-install-nugwdmxx/validators/
    Complete output (21 lines):
    /var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'build_requires'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nugwdmxx/validators/setup.py", line 39, in <module>
        setup(
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 462, in __init__
        _Distribution.__init__(
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
        self.finalize_options()
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 885, in finalize_options
        for ep in sorted(loaded, key=by_order):
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 884, in <lambda>
        loaded = map(lambda e: e.load(), filtered)
      File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
        return functools.reduce(getattr, attrs, module)
    AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
