### ISSUE TITLE
Bug: Could not save freetext feed data for feed

### ISSUE THREAD

**Issue by Tyrell20** [MISP/MISP#8466]
### Expected behavior

Feech of all feeds successfully completed.

### Actual behavior

The feetch of some feeds goes in error:
2022-06-30 10:21:16 Error: Could not save freetext feed data for feed 95.

### Steps to reproduce

Manual or automatic execution of fetch all events from a feed.

### Version

2.4.159

### Operating System

Red Hat Enterprise Linux Server

### Operating System version

7.9

### PHP version

7.4

### Relevant log output

```shell
[PDOException] SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(914): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Correlation.php(308): Mysql->insertMulti()
#2 /var/www/MISP/app/Model/Correlation.php(431): Correlation->__saveCorrelations()
#3 /var/www/MISP/app/Model/Attribute.php(443): Correlation->afterSaveCorrelation()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2352): Model->save()
#8 /var/www/MISP/app/Model/Feed.php(1327): Model->saveMany()
#9 /var/www/MISP/app/Model/Feed.php(1189): Feed->saveFreetextFeedData()
#10 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#15 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tyrell20** [comment]
If it helps, we have two issues on DB schema diagnostics: "Column uuid should be unique index, but contains duplicate values" on attributes and objects tables.

But, by clicking on Action (Fix Database Index Schema), we don't have any suggestion to resolve these issues.

![screenshot 376](https://user-images.githubusercontent.com/64137969/177747989-02ac04af-a3bf-462a-9aba-788a34d490d9.jpg)
![screenshot 375](https://user-images.githubusercontent.com/64137969/177748046-5394300b-c08b-4891-8e6e-b3841afcfcd3.jpg)

Attached a couple of screenshots about this.

Thank you

**Comment by iglocska** [comment]
Could you run `select max(id) from correlations;` and paste the results?

**Comment by Tyrell20** [comment]
Hello,

Database changed
MariaDB [misp]> select max(id) from correlations;
+------------+
| max(id)    |
+------------+
| 2147452976 |
+------------+


Thank you
