### ISSUE TITLE
Support: Another 'Internal Error Has Occurred' on the Diagnostics page. 

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#8473]
### Support Questions

I had a git error that I got updating through the gui... 

<pre>
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '95c141f34cbae22ce25648f4cb58027f2ccdf1f9' in submodule path 'app/files/scripts/misp-stix'
</pre>

that I was able to seemingly get through with this on the command line. 

https://github.com/MISP/MISP/issues/6215

<pre>
cd app/files/scripts/misp-stix  
sudo -u www-data -H git reset --hard HEAD 
</pre>

And then I updated through the command line with this - 

<pre>
cd /var/www/MISP 
sudo -u www-data -H git pull origin 2.4  
sudo -u www-data -H git submodule update --init --recursive  
</pre>

and then doublechecking all my permissions.  

<pre>
sudo chown -R www-data:www-data /var/www/MISP 
sudo chmod -R 750 /var/www/MISP  
sudo chmod -R g+ws /var/www/MISP/app/tmp  
sudo chmod -R g+ws /var/www/MISP/app/files  
sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp  
</pre>

... and I didn't get any errors with any of that but now I'm getting the 'Internal Error' on the Diagnostics page.  

 Thank you for any suggestions!!

### MISP version

2.4.2159

### Operating System

Ubuntu 

### Operating System version

20.04 

### PHP version

7.4.3

### Browser

Chrome, Edge 

### Browser version

Edge Ver 102, Chrome Ver 103

### Relevant log output

```shell
root@MISP:/var/www/MISP/app/tmp/logs# tail -f error.log
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/PubSubTool.php(71): ProcessTool::execute()
#1 /var/www/MISP/app/Model/Server.php(3312): PubSubTool->checkIfPythonLibInstalled()
#2 /var/www/MISP/app/Controller/ServersController.php(1138): Server->zmqDiagnostics()
#3 [internal function]: ServersController->serverSettings()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main}


root@MISP:/var/www/MISP/app/tmp/logs# tail -f mispzmq.error.log
    import redis
  File "/var/www/MISP/venv/lib/python3.6/site-packages/redis/__init__.py", line 1, in <module>
    from redis.client import Redis, StrictRedis
  File "/var/www/MISP/venv/lib/python3.6/site-packages/redis/client.py", line 12, in <module>
    from redis.connection import (ConnectionPool, UnixDomainSocketConnection,
  File "/var/www/MISP/venv/lib/python3.6/site-packages/redis/connection.py", line 2, in <module>
    from distutils.version import StrictVersion
  File "/var/www/MISP/venv/lib/python3.6/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
ImportError: cannot import name 'dist'
```

### Extra attachments

![image](https://user-images.githubusercontent.com/5932961/176955081-f2846c60-f02f-4e6a-a6dc-5a07d470bf6c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Hello, can you provide whole `error.log`? The exception message is missing.

**Comment by mathurin68** [comment]
Ah, sorry... yes!  Did I mess up my virtualenv somehow?   

```
2022-06-27 14:23:59 Error: [ProcessException] Command '/var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/mispzmq/mispzmqtest.py' return error code 1.
STDERR: ''
STDOUT: 'Redis library could not be imported.
'
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/PubSubTool.php(71): ProcessTool::execute()
#1 /var/www/MISP/app/Model/Server.php(3312): PubSubTool->checkIfPythonLibInstalled()
#2 /var/www/MISP/app/Controller/ServersController.php(1138): Server->zmqDiagnostics()
#3 [internal function]: ServersController->serverSettings()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main}}
```


```
root@MISP:/var/www/MISP# sudo -H -u www-data /var/www/MISP/venv/bin/python
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/MISP/venv/lib/python3.6/site-packages/redis/__init__.py", line 1, in <module>
    from redis.client import Redis, StrictRedis
  File "/var/www/MISP/venv/lib/python3.6/site-packages/redis/client.py", line 12, in <module>
    from redis.connection import (ConnectionPool, UnixDomainSocketConnection,
  File "/var/www/MISP/venv/lib/python3.6/site-packages/redis/connection.py", line 2, in <module>
    from distutils.version import StrictVersion
  File "/var/www/MISP/venv/lib/python3.6/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
ImportError: cannot import name 'dist'
>>>
```

Can I rebuild my virtualenv by deleting the venv file and then... (my python version on here is 3.8.10)

```
cd /var/www/MISP 
python3 -m venv venv
/var/www/MISP/venv/bin/source activate
sudo -H -u www-data /var/www/MISP/venv/bin/python3 -m pip install /var/www/MISP/requirements.txt
```

the /var/www/MISP/requirements.txt contains - 
pyzmq
coveralls
codecov
stix
pymisp
requests-mock
pip
nose
jsonschema
plyara >= 2.0.2
requirements.txt (END)

Really appreciate the help!

**Comment by mathurin68** [comment]
Keep in mind I have no idea what I'm doing, but for anyone that is facing this same problem, this seems to have fixed it...
I'm on python 3.8.10 

```
sudo -H -u www-data python3 -m venv venv 
sudo -H -u www-data /var/www/MISP/venv/bin/python -m pip install wheel
sudo -H -u www-data /var/www/MISP/venv/bin/python -m pip install -r /var/www/MISP/requirements.txt
sudo -H -u www-data /var/www/MISP/venv/bin/python -m pip install redis
```
