### ISSUE TITLE
Bug: Error when using Install script

### ISSUE THREAD

**Issue by Davdavidid** [MISP/MISP#8485]
### Expected behavior

Installation without Error

### Actual behavior

Near the end of the Installation process i get an Error. MISP seems to be working but i can't get theHive/Cortex to send cases even though they are connected (plugin in MISP is connected and green circles in hive). 
I'm unsure if this is the problem but it would be good to solve it no matter what.

### Steps to reproduce

Tried the installation several times but the error was always the same. Last start i did with:

```
sudo apt-get install openssh-server -y

sudo systemctl enable ssh 
sudo systemctl start ssh

sudo apt install haveged -qy
sudo systemctl start haveged

sudo adduser misp
usermod -a -G sudo misp
usermod -a -G staff misp
usermod -a -G www-data misp
su - misp

sudo wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M

```

### Version

2.4

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Firefox

### Relevant log output

```shell
> Setting "Plugin.Export_pdfexport_enabled" changed to 1
#############################################################  (80%)
######################################################################################  (84%)
> ##########################################################################    (86%)
> url = ""
> key = "1dx9uRr3ffdMrnfHHkcXJtx5P1wQ06KVY16ybnEq"
> Betrete 'pymisp/data/misp-objects'
> Von https://github.com/MISP/misp-objects
>  * branch            main       -> FETCH_HEAD
> Aktualisiere db9d79b..50f61a0
> Fast-forward
>  README.md                                  |  13 +-
>  objects/attack-step/definition.json        |  83 ++++++++
>  objects/domain-ip/definition.json          |   3 +-
>  objects/ftm-Airplane/definition.json       |   4 +-
>  objects/ftm-Assessment/definition.json     |   4 +-
>  objects/ftm-Asset/definition.json          |   4 +-
>  objects/ftm-Audio/definition.json          |   4 +-
>  objects/ftm-BankAccount/definition.json    |   4 +-
>  objects/ftm-Call/definition.json           |   4 +-
>  objects/ftm-CourtCase/definition.json      |   2 +-
>  objects/ftm-CourtCaseParty/definition.json |   2 +-
>  objects/ftm-Directorship/definition.json   |   2 +-
>  objects/ftm-Document/definition.json       |   2 +-
>  objects/ftm-Documentation/definition.json  |   2 +-
>  objects/ftm-Email/definition.json          |   2 +-
>  objects/ftm-Event/definition.json          |   2 +-
>  objects/ftm-Folder/definition.json         |   2 +-
>  objects/ftm-HyperText/definition.json      |   2 +-
>  objects/ftm-Image/definition.json          |   2 +-
>  objects/ftm-Land/definition.json           |   2 +-
>  objects/ftm-Membership/definition.json     |   4 +-
>  objects/ftm-Message/definition.json        |   2 +-
>  objects/ftm-Organization/definition.json   |   2 +-
>  objects/ftm-Ownership/definition.json      |   4 +-
>  objects/ftm-Package/definition.json        |   4 +-
>  objects/ftm-Page/definition.json           |   4 +-
>  objects/ftm-Pages/definition.json          |   4 +-
>  objects/ftm-PlainText/definition.json      |   4 +-
>  objects/ftm-Row/definition.json            |   4 +-
>  objects/ftm-Table/definition.json          |   4 +-
>  objects/ftm-UnknownLink/definition.json    |   4 +-
>  objects/ftm-UserAccount/definition.json    |   4 +-
>  objects/ftm-Vehicle/definition.json        |   4 +-
>  objects/ftm-Video/definition.json          |   4 +-
>  objects/ftm-Workbook/definition.json       |   4 +-
>  objects/network-connection/definition.json |   7 +-
>  objects/query/definition.json              |  53 +++++
>  objects/report/definition.json             |  44 +++-
>  objects/scheduled-task/definition.json     | 112 ++++++++++
>  objects/stock/definition.json              | 325 +++++++++++++++++++++++++++++
>  40 files changed, 681 insertions(+), 61 deletions(-)
>  create mode 100644 objects/attack-step/definition.json
>  create mode 100644 objects/query/definition.json
>  create mode 100644 objects/scheduled-task/definition.json
>  create mode 100644 objects/stock/definition.json
> Betrete 'pymisp/tools/pdf_fonts'
> fatal: Konnte Remote-Referenz main nicht finden.
> fatal: run_command gab nicht-Null Status für 'pymisp/tools/pdf_fonts' zurück.
> .
> Obtaining file:///var/www/MISP/PyMISP
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>     Preparing wheel metadata ... done
>   WARNING: pymisp-2.4.159 2.4.159 does not provide the extra 'neo'
> Requirement already satisfied: jsonschema<5.0.0,>=4.5.1 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (4.6.2)
> Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (2.8.2)
> Requirement already satisfied: requests<3.0.0,>=2.27.1 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (2.28.1)
> Requirement already satisfied: deprecated<2.0.0,>=1.2.13 in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (1.2.13)
> Requirement already satisfied: pydeep2<0.6.0,>=0.5.1; extra == "fileobjects" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (0.5.1)
> Requirement already satisfied: lief<0.13.0,>=0.12.1; extra == "fileobjects" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (0.12.1)
> Requirement already satisfied: python-magic<0.5.0,>=0.4.26; extra == "fileobjects" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (0.4.27)
> Requirement already satisfied: beautifulsoup4<5.0.0,>=4.11.1; extra == "openioc" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (4.11.1)
> Requirement already satisfied: reportlab<4.0.0,>=3.6.9; extra == "pdfexport" in /var/www/MISP/venv/lib/python3.8/site-packages (from pymisp==2.4.159) (3.6.9)
> Collecting validators<0.20.0,>=0.19.0; extra == "virustotal"
>   Downloading validators-0.19.0.tar.gz (30 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /var/www/MISP/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ithupbph/validators/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ithupbph/validators/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ithupbph/validators/pip-egg-info
>          cwd: /tmp/pip-install-ithupbph/validators/
>     Complete output (21 lines):
>     /var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'build_requires'
>       warnings.warn(msg)
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-ithupbph/validators/setup.py", line 39, in <module>
>         setup(
>       File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
>         return distutils.core.setup(**attrs)
>       File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 462, in __init__
>         _Distribution.__init__(
>       File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
>         self.finalize_options()
>       File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 885, in finalize_options
>         for ep in sorted(loaded, key=by_order):
>       File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/dist.py", line 884, in <lambda>
>         loaded = map(lambda e: e.load(), filtered)
>       File "/var/www/MISP/venv/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
>         return functools.reduce(getattr, attrs, module)
>     AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> The test files are missing, pulling it.
> Klone nach 'tests/viper-test-files' …
> remote: Enumerating objects: 110, done.
> remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
> Empfange Objekte: 100% (110/110), 15.18 MiB | 4.16 MiB/s, fertig.
> Löse Unterschiede auf: 100% (24/24), fertig.
> E
> ======================================================================
> ERROR: setUpClass (__main__.TestComprehensive)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "tests/testlive_comprehensive.py", line 65, in setUpClass
>     cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
>   File "/var/www/MISP/venv/lib/python3.8/site-packages/pymisp/api.py", line 147, in __init__
>     raise NoURL('Please provide the URL of your MISP instance.')
> pymisp.exceptions.NoURL: Please provide the URL of your MISP instance.
> 
> ----------------------------------------------------------------------
> Ran 0 tests in 0.002s
> 
> FAILED (errors=1)
>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lexati** [comment]
I have this problem too!

**Comment by righel** [comment]
Could you try running:
`pip install --upgrade pip`

And run the install again?

**Comment by coldflame-js** [comment]
Same here, me2

**Comment by YazidRB** [comment]
same here
