### ISSUE TITLE
Bug: attribute not being created on stix import.

### ISSUE THREAD

**Issue by Rogueit** [MISP/MISP#8522]
### Expected behavior

When importing a stix file and event and coorisponing attributes should be created.

### Actual behavior

The event is being created but the attribute isn't being properly parsed and there is no corresponding value being made from the stix file.

### Steps to reproduce

Run  /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISP2ggVnf

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2146, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2140, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 86, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1254, in parse_event
    getattr(self, self._stix2misp_mapping[object_type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1330, in parse_attack_pattern
    value = reference['external_id'].split('-')[1] if source_name == 'capec' else reference['url']
  File "/var/www/MISP/venv/lib/python3.8/site-packages/stix2/base.py", line 260, in __getitem__
    return self._inner[key]
KeyError: 'url'
[MISP2ggVnf.txt](https://github.com/MISP/MISP/files/9262811/MISP2ggVnf.txt)

### Version

v2.4.159

### Operating System

ubuntu

### Operating System version

20.04.4 LTS

### PHP version

7.4.3 (Up to date)

### Browser

Chrome

### Browser version

104

### Relevant log output

```shell
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2146, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2140, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 86, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1254, in parse_event
    getattr(self, self._stix2misp_mapping[object_type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1330, in parse_attack_pattern
    value = reference['external_id'].split('-')[1] if source_name == 'capec' else reference['url']
  File "/var/www/MISP/venv/lib/python3.8/site-packages/stix2/base.py", line 260, in __getitem__
    return self._inner[key]
KeyError: 'url'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rogueit** [comment]
@chrisr3d Hey man...if you get a moment...you were able to help me out last time, If you get a chance, could you take a look.

**Comment by chrisr3d** [comment]
I fixed in 7da6f26 the `external_references` field parsing for attack pattern objects, which was here the breaking point.
Also there is a lot of duplicates, so this change includes a way to deduplicate the reference values (a simple `set` makes the job here), which was not the case before.

Nonetheless, I did not look at every detail within the STIX content to check everything, cause this is STIX 2.1 but I am always surprised the script does not fail since it is for now supporting STIX 2.0 only (at least officially).
I made sure to include the same changes (https://github.com/MISP/misp-stix/commit/4df8a3b973860c01965f1bf3b53879c06efdba27) on the library that will be used in the future to replace the current scripts and that will support 2.1

Let me know if you face any further issue

**Comment by Rogueit** [comment]
Thanks Chris, I really appreciate your time on this.
