### ISSUE TITLE
Bug: OidcAuth does not use proxy settings

### ISSUE THREAD

**Issue by ftoppi** [MISP/MISP#8535]
### Expected behavior

When opening https://misp/users/login , I expect to be redirected to the IdP for login.

### Actual behavior

When accessing https://misp/users/login, the page never loads and an timeout error appears in the log (see below).

A packet capture shows direct connections from MISP to the OIDC IdP instead of going through the proxy:
![image](https://user-images.githubusercontent.com/4704016/184107924-97ec2d0f-635d-4b9c-a6b9-a17d80b8e911.png)

However, proxy settings are OK according to diagnostics:
![image](https://user-images.githubusercontent.com/4704016/184108058-5614ccf9-b95b-4163-892f-faf5b54af740.png)

We use docker image from https://github.com/MISP/misp-docker .

### Steps to reproduce

1. Configure proxy settings
2. Update MISP.ca_path
3. Install OidcAuth plugin
4. Edit app/Config/config.php
5. Open https://misp/users/login
6. Observe the timeout

### Version

2.4.151

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Firefox, Chrome

### Browser version

Latest

### Relevant log output

```shell
2022-08-11 11:29:18 Error: [JakubOnderka\OpenIDConnectClientException] cURL error #28: Connection timed out after 60000 milliseconds
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(672): JakubOnderka\OpenIDConnectClient->fetchURL()
#1 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(701): JakubOnderka\OpenIDConnectClient->fetchProviderMetadata()
#2 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(625): JakubOnderka\OpenIDConnectClient->getWellKnownConfigValue()
#3 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(862): JakubOnderka\OpenIDConnectClient->getProviderConfigValue()
#4 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(549): JakubOnderka\OpenIDConnectClient->requestAuthorization()
#5 /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php(22): JakubOnderka\OpenIDConnectClient->authenticate()
#6 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(32): Oidc->authenticate()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#9 /var/www/MISP/app/Controller/UsersController.php(1195): AuthComponent->login()
#10 [internal function]: UsersController->login()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#15 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FischerCar** [comment]
observe the same behaviour with 
MISP version 2.4.194
OS: Debian 6.1.94-1
Browser: Edge 127.0.2641.74 and Firefox 128.0.3
PHP version:  7.4.33
