### ISSUE TITLE
Bug: MISP is not working properly after updating to 2.4.160

### ISSUE THREAD

**Issue by sabyasachisamanta** [MISP/MISP#8536]
### Expected behavior

Following are some the functionalities that are not working:
1. Server settings and maintenance
2. Jobs
3. Servers and Feeds sync activities
4. Workflows

### Actual behavior

I am getting an error message while trying to access the above mentioned functionalities: 
**An Internal Error Has Occurred.**
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Steps to reproduce

I tried to update the MISP instance and after successful update I tried to access the Server settings and maintenance. I received an error message. 
![image](https://user-images.githubusercontent.com/46665074/184121613-cb5edd78-9041-4aa1-a68a-1cf2a3a7a278.png)

### Version

2.4.160

### Operating System

Rehat Linux

### Operating System version

8.4

### PHP version

7.4.19

### Browser

Chrome

### Browser version

104.0.5112.81

### Relevant log output

```shell
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:52:05 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/View/Elements/genericElements/IndexTable/index_table.ctp, line 72]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/genericElements/IndexTable/index_table.ctp, line 72
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Correlations/top.ctp, line 61
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:52:07 Error: [TypeError] Redis::setex() expects parameter 2 to be int, null given
Request URL: /correlations/generateTopCorrelations
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(341): Redis->setex()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(170): BackgroundJobsTool->update()
#2 /var/www/MISP/app/Model/Correlation.php(619): BackgroundJobsTool->enqueue()
#3 /var/www/MISP/app/Controller/CorrelationsController.php(63): Correlation->generateTopCorrelationsRouter()
#4 [internal function]: CorrelationsController->generateTopCorrelations()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
2022-08-11 19:57:53 Error: [TypeError] substr() expects parameter 1 to be string, null given
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(633): substr()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(611): BackgroundJobsTool->createSupervisorConnection()
#2 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#3 /var/www/MISP/app/Model/Server.php(7558): BackgroundJobsTool->getWorkers()
#4 /var/www/MISP/app/Model/Server.php(3559): Server->getWorkers()
#5 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
^C
[root@DAQMISP01 ~]# clear
[root@DAQMISP01 ~]# tail -f -n 200 /var/www/MISP/app/tmp/logs/error.log
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
2022-08-11 19:50:48 Error: [TypeError] substr() expects parameter 1 to be string, null given
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(633): substr()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(611): BackgroundJobsTool->createSupervisorConnection()
#2 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#3 /var/www/MISP/app/Model/Server.php(7558): BackgroundJobsTool->getWorkers()
#4 /var/www/MISP/app/Model/Server.php(3559): Server->getWorkers()
#5 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
2022-08-11 19:51:20 Error: [TypeError] substr() expects parameter 1 to be string, null given
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(633): substr()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(611): BackgroundJobsTool->createSupervisorConnection()
#2 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#3 /var/www/MISP/app/Model/Server.php(7558): BackgroundJobsTool->getWorkers()
#4 /var/www/MISP/app/Model/Server.php(3559): Server->getWorkers()
#5 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
2022-08-11 19:51:23 Warning: Warning (2): count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/View/Workflows/error.ctp, line 14]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Workflows/error.ctp, line 14
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
WorkflowsController::beforeFilter() - APP/Controller/WorkflowsController.php, line 23
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:51:23 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/View/Workflows/error.ctp, line 16]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Workflows/error.ctp, line 16
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
WorkflowsController::beforeFilter() - APP/Controller/WorkflowsController.php, line 23
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:51:23 Error: [TypeError] Return value of Workflow::getEnabledModules() must be of the type array, bool returned
Request URL: /workflows/triggers
Stack Trace:
#0 /var/www/MISP/app/Model/Workflow.php(835): Workflow->getEnabledModules()
#1 /var/www/MISP/app/Model/Workflow.php(822): Workflow->__mergeGlobalConfigIntoLoadedModules()
#2 /var/www/MISP/app/Model/Workflow.php(1026): Workflow->loadAllWorkflowModules()
#3 /var/www/MISP/app/Controller/WorkflowsController.php(183): Workflow->getModulesByType()
#4 [internal function]: WorkflowsController->triggers()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
2022-08-11 19:51:26 Error: [TypeError] substr() expects parameter 1 to be string, null given
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(633): substr()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(611): BackgroundJobsTool->createSupervisorConnection()
#2 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#3 /var/www/MISP/app/Model/Server.php(7558): BackgroundJobsTool->getWorkers()
#4 /var/www/MISP/app/Model/Server.php(3559): Server->getWorkers()
#5 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
2022-08-11 19:51:47 Error: [TypeError] substr() expects parameter 1 to be string, null given
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(633): substr()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(611): BackgroundJobsTool->createSupervisorConnection()
#2 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#3 /var/www/MISP/app/Model/Server.php(7558): BackgroundJobsTool->getWorkers()
#4 /var/www/MISP/app/Model/Server.php(3559): Server->getWorkers()
#5 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
2022-08-11 19:51:59 Warning: Warning (2): count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Controller/CorrelationsController.php, line 48]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
CorrelationsController::top() - APP/Controller/CorrelationsController.php, line 48
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:51:59 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/View/Elements/genericElements/IndexTable/index_table.ctp, line 72]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/genericElements/IndexTable/index_table.ctp, line 72
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Correlations/top.ctp, line 61
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:52:02 Error: [TypeError] Redis::setex() expects parameter 2 to be int, null given
Request URL: /correlations/generateTopCorrelations
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(341): Redis->setex()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(170): BackgroundJobsTool->update()
#2 /var/www/MISP/app/Model/Correlation.php(619): BackgroundJobsTool->enqueue()
#3 /var/www/MISP/app/Controller/CorrelationsController.php(63): Correlation->generateTopCorrelationsRouter()
#4 [internal function]: CorrelationsController->generateTopCorrelations()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
2022-08-11 19:52:05 Warning: Warning (2): count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Controller/CorrelationsController.php, line 48]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
CorrelationsController::top() - APP/Controller/CorrelationsController.php, line 48
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:52:05 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/View/Elements/genericElements/IndexTable/index_table.ctp, line 72]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/genericElements/IndexTable/index_table.ctp, line 72
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Correlations/top.ctp, line 61
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-08-11 19:52:07 Error: [TypeError] Redis::setex() expects parameter 2 to be int, null given
Request URL: /correlations/generateTopCorrelations
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(341): Redis->setex()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(170): BackgroundJobsTool->update()
#2 /var/www/MISP/app/Model/Correlation.php(619): BackgroundJobsTool->enqueue()
#3 /var/www/MISP/app/Controller/CorrelationsController.php(63): Correlation->generateTopCorrelationsRouter()
#4 [internal function]: CorrelationsController->generateTopCorrelations()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
2022-08-11 19:57:53 Error: [TypeError] substr() expects parameter 1 to be string, null given
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(633): substr()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(611): BackgroundJobsTool->createSupervisorConnection()
#2 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#3 /var/www/MISP/app/Model/Server.php(7558): BackgroundJobsTool->getWorkers()
#4 /var/www/MISP/app/Model/Server.php(3559): Server->getWorkers()
#5 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
should be fixed by now, update to latest version and leave a comment if you still encounter issues.
