### ISSUE TITLE
Bug: Setting up a new MISP with zero events makes correlations divade by zero and create scary error messages

### ISSUE THREAD

**Issue by Kagee** [MISP/MISP#8562]
### Expected behavior

Setting up a new MISP with no evetns should not create scary error messages in logs.

### Actual behavior

Correlation should fail gracefully if there are zero events.

### Steps to reproduce

When there are zero events ($eventCount = 0), this line vill return in division by zero.
https://github.com/MISP/MISP/blob/2.4/app/Model/Attribute.php#L1579

Then saveprogress will recieve a $progress of "NAN", and try to save that as progress in the DB.

Multiple ugly error messages in the logs.

### Version

2.4.161

### Operating System

NR

### Operating System version

NR

### PHP version

NR

### Browser

NR

### Browser version

NR

### Relevant log output

```shell
Warning Error: Division by zero in [/var/www/MISP/app/Model/Attribute.php, line 1579]

2022-08-30 19:13:13 Warning: Division by zero in [/var/www/MISP/app/Model/Attribute.php, line 1579]
2022-08-30 19:13:14 Notice: Could not save progress for job 4
[PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'NAN' in 'field list'
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave()
#5 /var/www/MISP/app/Model/Job.php(133): Model->save()
#6 /var/www/MISP/app/Model/Attribute.php(1579): Job->saveProgress()
#7 /var/www/MISP/app/Model/Attribute.php(1559): Attribute->__iteratedCorrelation()
#8 /var/www/MISP/app/Console/Command/AdminShell.php(114): Attribute->generateCorrelation()
#9 /var/www/MISP/app/Console/Command/AppShell.php(43): AdminShell->jobGenerateCorrelation()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#15 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ostefano** [comment]
@Kagee  quick fix:
```
diff --git a/app/Model/Attribute.php b/app/Model/Attribute.php
index e4269ce98..aefb76337 100644
--- a/app/Model/Attribute.php
+++ b/app/Model/Attribute.php
@@ -1576,7 +1576,7 @@ class Attribute extends AppModel
     {
         if ($jobId) {
             $message = $attributeId ? __('Correlating Attribute %s', $attributeId) : __('Correlating Event %s (%s MB used)', $eventId, intval(memory_get_usage() / 1024 / 1024));
-            $this->Job->saveProgress($jobId, $message, ($j / $eventCount) * 100);
+            $this->Job->saveProgress($jobId, $message, ($j == 0 or $eventCount == 0) ? 0 : ($j / $eventCount) * 100);
         }
         $attributeConditions = [
             'Attribute.deleted' => 0,
```

**Comment by Kagee** [comment]
Not sure about that, the whole job should be stoped/finished, since there is nothing to correlate.
