### ISSUE TITLE
Bug: Event-Publish workflow errors on version 2.4.162

### ISSUE THREAD

**Issue by Kerbenroast** [MISP/MISP#8585]
### Expected behavior

With the event-publish workflow enabled, when attempting to publish an event the workflow executes and the event is published

### Actual behavior

The workflows throws an error, the event is not published and the actions of the workflow are not executed.

I think I have narrowed down the issue to inside the getUserForWorkflow() in Workflow.php there's no return statement in the if clause for when (!empty($hostOrg))

### Steps to reproduce

Enable the event-publish workflow with a simple workflow. (Mine is just a single Tag Operation) 

Attempt to publish an event. 

This is been tested on two seperate instances with the same results.

Added "return $userForWorkflow" in the if statement in getUserForWorkflow and seemed to have fixed the issue but not familar enough with the codebase to work out if this is the best fix.

### Version

2.4.162

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Relevant log output

```shell
2022-09-14 11:47:05 Error: [JOB ID: 3c96e9fb-b364-4d5f-aff7-4bdef7516f5f] - failed with error code 1. STDERR: Error: Return value of Workflow::getUserForWorkflow() must be of the type array, none returned
#0 /var/www/MISP/app/Model/Workflow.php(555): Workflow->getUserForWorkflow()
#1 /var/www/MISP/app/Model/Workflow.php(514): Workflow->walkGraph()
#2 /var/www/MISP/app/Model/Workflow.php(489): Workflow->__runWorkflow()
#3 /var/www/MISP/app/Model/Workflow.php(456): Workflow->executeWorkflowForTrigger()
#4 /var/www/MISP/app/Model/AppModel.php(3770): Workflow->executeWorkflowForTriggerRouter()
#5 /var/www/MISP/app/Model/Event.php(4461): AppModel->executeTrigger()
#6 /var/www/MISP/app/Console/Command/EventShell.php(420): Event->publish()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): EventShell->publish()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#11 {main}
. STDOUT: .
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Malwar3Ninja** [comment]
+1 Same issue

**Comment by dlewen** [comment]
+1 Same issue, I've solved it locally by moving the return to the end of the getUserForWorkflow function

**Comment by Malwar3Ninja** [comment]
the issue is still there even on latest release

Error: Return value of Workflow::getUserForWorkflow() must be of the type array, none returned
#0 /var/www/MISP/app/Model/Workflow.php(557): Workflow->getUserForWorkflow()
#1 /var/www/MISP/app/Model/Workflow.php(516): Workflow->walkGraph()
#2 /var/www/MISP/app/Model/Workflow.php(489): Workflow->__runWorkflow()
#3 /var/www/MISP/app/Console/Command/WorkflowShell.php(22): Workflow->executeWorkflowForTrigger()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): WorkflowShell->executeWorkflowForTrigger()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}

**Comment by Malwar3Ninja** [comment]
Team any update?
