### ISSUE TITLE
Bug: Redis password reset disables "Server Settings & Maintenance" section

### ISSUE THREAD

**Issue by danieleperera** [MISP/MISP#8586]
## We would like to set Redis password.

The modification was performed on /etc/redis.config
`requirepass PASSWORD_HERE`

Then on MISP servers/serverSettings/MISP, the new password was configured
<html><body>

Critical | MISP.redis_password | ***** | The password on the redis server (if any) to be used for generic MISP tasks.
-- | -- | -- | --

</body>
</html>

Then we restarted redis and httpd service.

### Actual behavior

once the password is set on redis server and configured on MISP redis configuration.
The server fails to load "Server Settings & Maintenance" section.

### Steps to reproduce

Modify redis password
Configure redis password on MISP
Restart redis

### Version

2.4.162

### Operating System

Redhat

### Operating System version

Red Hat Enterprise Linux release 8.5 (Ootpa)

### PHP version

7.4.30

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ryukisec** [comment]
You'll need to set the redis password also in `MISP/app/Plugin/CakeResque/Config/config.php` and/or for the `SimpleBackgroundJobs` [(depending on how you handle background jobs)](https://github.com/MISP/MISP/blob/4cf2156f2fbaafcbc629755d655edc56e81369ec/docs/background-jobs-migration-guide.md).

**Comment by vincenzocaputo** [comment]
> You'll need to set the redis password also in `MISP/app/Plugin/CakeResque/Config/config.php` and/or for the `SimpleBackgroundJobs` [(depending on how you handle background jobs)](https://github.com/MISP/MISP/blob/4cf2156f2fbaafcbc629755d655edc56e81369ec/docs/background-jobs-migration-guide.md).

After setting the redis password, the workers cannot be restarted. Below the logs I see in `resque-worker-error.log`:
```
Error: NOAUTH Authentication required.
#0 /misp/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(108): Redis->select()
#1 /misp/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(668): Resque::redis()
#2 /misp/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(107): Resque_Worker->registerLogger()
#3 /misp/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#4 {main}
```

**Comment by Foxi352** [comment]
@vincenzocaputo 
Clicking on the "Restart dead workers" button on the bottom of the workers page fixed this for me.
I confirm that it is persistent after a reboot.
