### ISSUE TITLE
Support: Millions of 'publishing sightings' jobs after disk shortage

### ISSUE THREAD

**Issue by Shi-Lung** [MISP/MISP#8588]
### Support Questions

Hello,

MISP instance suffered from disk shortage yesterday - A couple of Redis errors poped up in logs, although disk never got fully used. 

Disk was enlarged and Redis alerts went away. However, millions of prio jobs are now accumulating in the jobs queue, and the number keeps growing. Database is extremely busy, it even crashes from time to time and restart automatically.

Is there anything I can do ?

### MISP version

2.4.159

### Operating System

Oracle Linux

### Operating System version

8

### PHP version

7.4

### Browser

Edge

### Relevant log output

```shell
Redis error - before disk enlargement:

[root@server var]# tail -15f /var/www/MISP/app/tmp/logs/error.log
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#6 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#7 {main}
2022-09-19 07:54:45 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
Request URL: /servers/getWorkers
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(657): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(240): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/ServersController.php(41): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ServersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main}


[root@server var]# tail -f /var/log/redis/redis.log
1063:M 19 Sep 2022 07:54:00.847 * 1 changes in 900 seconds. Saving...
1063:M 19 Sep 2022 07:54:00.893 * Background saving started by pid 1990587
1990587:C 19 Sep 2022 07:54:41.300 # Write error saving DB on disk: No space left on device
1063:M 19 Sep 2022 07:54:41.582 # Background saving error
1063:M 19 Sep 2022 07:54:41.682 * 1 changes in 900 seconds. Saving...
1063:M 19 Sep 2022 07:54:41.729 * Background saving started by pid 1990604
1990604:C 19 Sep 2022 07:55:22.157 # Write error saving DB on disk: No space left on device
1063:M 19 Sep 2022 07:55:22.517 # Background saving error
1063:M 19 Sep 2022 07:55:22.617 * 1 changes in 900 seconds. Saving...
1063:M 19 Sep 2022 07:55:22.664 * Background saving started by pid 1990623

recurring messages in /var/www/MISP/app/tmp/logs/resque-2022-09-19.log

[2022-09-19 13:32:04] main.INFO: got {"queue":"prio","id":"26d18af0d9a3b1bccb04f40d23c97d41","class":"EventShell","args":[["publish_sightings","49704",null,1722986,"1"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"prio\",\"id\":\"26d18af0d9a3b1bccb04f40d23c97d41\",\"class\":\"EventShell\",\"args\":[[\"publish_sightings\",\"49704\",null,1722986,\"1\"]]})","worker":"http://server:2071241"} []
[2022-09-19 13:32:04] main.INFO: got {"queue":"prio","id":"513111fa92ad67537d5bc231e25c90c2","class":"EventShell","args":[["publish_sightings","49847",null,1722985,"1"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"prio\",\"id\":\"513111fa92ad67537d5bc231e25c90c2\",\"class\":\"EventShell\",\"args\":[[\"publish_sightings\",\"49847\",null,1722985,\"1\"]]})","worker":"http://server:2071094"} []
[2022-09-19 13:32:04] main.INFO: Processing ID:26d18af0d9a3b1bccb04f40d23c97d41 in prio {"type":"process","worker":"http://server:2071241","job_id":"26d18af0d9a3b1bccb04f40d23c97d41"} []
[2022-09-19 13:32:04] main.INFO: Processing ID:513111fa92ad67537d5bc231e25c90c2 in prio {"type":"process","worker":"http://server:2071094","job_id":"513111fa92ad67537d5bc231e25c90c2"} []
```

### Extra attachments

![image](https://user-images.githubusercontent.com/89835616/191009558-050cca23-582e-4de5-b858-690bfe31291a.png)

![image](https://user-images.githubusercontent.com/89835616/191009673-ce056125-3849-4679-b6fc-81ddca46317f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shi-Lung** [comment]
Someone played with the API without notice and did some mistakes. All look OK now, sorry for the inconvenience.
