### ISSUE TITLE
Support: Intermittent fetchFeed stream_socket_enable_crypto ... ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8604]
### Support Questions

Would appreciate guidance on how to find root cause and fix for fetchFeed failing intermittently on several feeds endpoints with `stream_socket_enable_crypto` ...  `ssl3_get_record:wrong version number`

### MISP version

2.4.162

### Operating System

RH

### Operating System version

8.6

### PHP version

7.4.28

### Browser

N/A

### Relevant log output

```shell
/var/www/MISP/app/Console/cake Server fetchFeed 60 9
Warning Error: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 504]

2022-09-18 08:40:13 Warning: stream_socket_enable_crypto(): SSL operation failed w
ith code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number in [/var/www/MISP
/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 504]
2022-09-18 08:40:13 Error: Could not get freetext feed 9
[Exception] Fetching the 'https://www.dan.me.uk/torlist/?exit' failed with exception: Unable to perform enableCrypto operation on CakeSocket
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(334): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(373): Feed->getFreetextFeedRemote()
#2 /var/www/MISP/app/Model/Feed.php(1175): Feed->getFreetextFeed()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher>dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}[SocketException] Unable to perform enableCrypto operation on CakeSocket
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(261): CakeSocket->enableCrypto()
#1 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(147): CakeSocket->connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): HttpSocketE
xtended->connect()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#4 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(186): HttpSocket->request()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#6 /var/www/MISP/app/Model/Feed.php(2064): HttpSocket->get()
#7 /var/www/MISP/app/Model/Feed.php(2025): Feed->getFollowRedirect()
#8 /var/www/MISP/app/Model/Feed.php(334): Feed->feedGetUriRemote()
#9 /var/www/MISP/app/Model/Feed.php(373): Feed->getFreetextFeedRemote()
#10 /var/www/MISP/app/Model/Feed.php(1175): Feed->getFreetextFeed()
#11 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeed Initiator()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#15 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#16 {main}
Job failed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
ANy help would be appreciated. I see this same SSL issue when trying to connect two MISP instances via server sync. Thanks!

**Comment by manosmustang** [comment]
How this is solved?
