### ISSUE TITLE
Support: Unknown column 'NAN' in 'field list'

### ISSUE THREAD

**Issue by 00gxd14g** [MISP/MISP#8606]
### Support Questions

Although I activate the "feeds", no "job" or event occurs

### MISP version

2.4

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
[PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'NAN' in 'field list'
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave()
#5 /var/www/MISP/app/Model/Job.php(134): Model->save()
#6 /var/www/MISP/app/Model/Attribute.php(1584): Job->saveProgress()
#7 /var/www/MISP/app/Model/Attribute.php(1564): Attribute->__iteratedCorrelation()
#8 /var/www/MISP/app/Console/Command/AdminShell.php(114): Attribute->generateCorrelation()
#9 /var/www/MISP/app/Console/Command/AppShell.php(43): AdminShell->jobGenerateCorrelation()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#15 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
Log message is because of #8562, and not related to described  issue.

**Comment by 00gxd14g** [comment]
Anders Einar (Kagee) @hildenae:matrix.org Thanks, problem solved.
