### ISSUE TITLE
Support: Need Help  GUI - Error: An Internal Error Has Occurred - Novice User

### ISSUE THREAD

**Issue by R1SK72** [MISP/MISP#8635]
### Support Questions

Hi Folks,  i hope you can help.  

At the moment the GUI displays : 
**_An Internal Error Has Occurred.
Error: An Internal Error Has Occurred._**

/var/www/MISP/app/tmp/logs/error.log is attached 

I cant get logged into the system to administer it via the gui .   Sorry for lack of information , please let me know what i can provide to help identify the issue.  
![Pic1](https://user-images.githubusercontent.com/2537153/193671509-18a0bb2d-a389-4e0c-9ae1-2cc2e59ab83d.png)

### MISP version

2.4.151

### Operating System

ubuntu

### Operating System version

18.04

### PHP version

7.4

### Relevant log output

```shell
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2022-10-03 20:09:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(627): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(148): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2022-10-03 20:10:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(627): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(148): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
misp@bc-sin-misp-01:~$ clear
misp@bc-sin-misp-01:~$ tail -n 100 /var/www/MISP/app/tmp/logs/error.log
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2022-10-03 20:08:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(627): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(148): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2022-10-03 20:09:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(627): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(148): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2022-10-03 20:10:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(627): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(148): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2022-10-03 20:11:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(627): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(148): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2022-10-03 20:12:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(627): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(148): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @R1SK72 
Seems your MISP instance cannot connect to your MySQL server:
`SQLSTATE[HY000] [2002] Connection refused`

Check:
1. MySQL is running:
   ```
   sudo service mysql restart
   sudo service mysql status
   ``` 
2. Check your database settings are correct, specially the host and port values in the database config file: `/var/www/MISP/app/Config/database.php`

Hope this helps.
