### ISSUE TITLE
Support: unable to open events post update

### ISSUE THREAD

**Issue by tameknight** [MISP/MISP#8714]
### Support Questions

Post updating to  2.4.164 from 2.4.151, I am unable to open events. Additionally, after looking at the log file I saw a mention of the Correlation Exclusions. When entering the Correlations tab of the Server Settings & Maintenance page I'm greeted with the same error below.

GUI error: `An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.`

### MISP version

2.4.164

### Operating System

Ubuntu

### Operating System version

18.04.6

### PHP version

7.2.24

### Browser

Chrome

### Relevant log output

```shell
2022-10-26 11:34:38 Error: [MissingTableException] Table correlation_exclusions for model CorrelationExclusion was not found in datasource default.
Exception Attributes: array (
  'table' => 'correlation_exclusions',
  'class' => 'CorrelationExclusion',
  'ds' => 'default',
)
Request URL: /servers/serverSettings/correlations
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('correlation_exc...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3177): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3086): Model->_findCount('before', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3020): Model->buildQuery('count', Array)
#4 /var/www/MISP/app/Model/Correlation.php(957): Model->find('count')
#5 /var/www/MISP/app/Controller/ServersController.php(1078): Correlation->collectMetrics()
#6 [internal function]: ServersController->serverSettings('correlations')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2022-10-26 11:38:01 Error: [PDOException] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'misp_test.correlation_exclusions' doesn't exist
Request URL: /events/view/21838
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Correla...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Correla...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Correla...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Correlation), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Behavior/DefaultCorrelationBehavior.php(253): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Behavior/DefaultCorrelationBehavior.php(274): DefaultCorrelationBehavior->__collectCorrelations(Array, '21838', Array, false)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(238): DefaultCorrelationBehavior->runGetAttributesRelatedToEvent(Object(Correlation), Array, '21838', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollection->dispatchMethod(Object(Correlation), Array, Array)
#10 /var/www/MISP/app/Model/Correlation.php(820): Model->__call('runGetAttribute...', Array)
#11 /var/www/MISP/app/Model/Event.php(713): Correlation->getAttributesRelatedToEvent(Array, '21838', Array)
#12 /var/www/MISP/app/Model/Event.php(2029): Event->getRelatedAttributes(Array, '21838')
#13 /var/www/MISP/app/Controller/EventsController.php(1786): Event->fetchEvent(Array, Array)
#14 [internal function]: EventsController->view('21838')
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#18 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#19 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UFOSmuggler** [comment]
might be model cache.

try going into server settings and maintenance, diagnostics, and click clean cache, near the bottom

**Comment by tameknight** [comment]
Cache cleaned, still getting that error.
