### ISSUE TITLE
Issue with mariadb after Ubuntu upgrade

### ISSUE THREAD

**Issue by manosmustang** [MISP/MISP#8758]
Hello,

we have an issue with mariadb  while it starting after an upgrade that performed at Ubuntu (Linux 5.15.0-52-generic).

the error we get is:
```
Nov 15 15:36:47 .local /etc/mysql/debian-start[17194]: Upgrading MySQL tables if necessary.
Nov 15 15:36:47 .local mariadbd[17167]: 2022-11-15 15:36:47 3 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
Nov 15 15:36:47 .local /etc/mysql/debian-start[17197]: Looking for 'mysql' as: /usr/bin/mysql
Nov 15 15:36:47 .local /etc/mysql/debian-start[17197]: Reading datadir from the MariaDB server failed. Got the following error when exec>
Nov 15 15:36:47 .local /etc/mysql/debian-start[17197]: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Nov 15 15:36:47 .local /etc/mysql/debian-start[17197]: FATAL ERROR: Upgrade failed
Nov 15 15:36:47 .local /etc/mysql/debian-start[17203]: Checking for insecure root accounts.
Nov 15 15:36:47 .local mariadbd[17167]: 2022-11-15 15:36:47 4 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
Nov 15 15:36:47 .local debian-start[17206]: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Nov 15 15:36:47 .local mariadbd[17167]: 2022-11-15 15:36:47 0 [Note] InnoDB: Buffer pool(s) load completed at 221115 15:36:47
```

Any help is welcome.

thank you

**Comment by manosmustang** [comment]
I assume that there is an issue with database because we have the below view at GUI

![image](https://user-images.githubusercontent.com/15198539/202197068-c71c4294-ffc6-4457-bfd9-56ab6d6dcc77.png)

**Comment by manosmustang** [comment]
and this is the error message that I get from the error.log

```
2022-11-16 13:52:44 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'Selected driver is not enabled',
  'enabled' => false,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#1 /var/www/MISP/app/Controller/AppController.php(805): ConnectionManager::getDataSource()
#2 /var/www/MISP/app/Controller/AppController.php(143): AppController->_setupDatabaseConnection()
#3 /var/www/MISP/app/Controller/EventsController.php(68): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): EventsController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
```

The database is OK and I can connect successfully to it.

the database.php file looks fine

**Comment by manosmustang** [comment]
Issue solved after installing all the missing php7.4-*   (e.g. php7.4-mysql)   I had to install quite many of them
