### ISSUE TITLE
Unknown column 'EventTag.relationship_type' in 'field list' after upfate from 2.4.159 to 2.4.165

### ISSUE THREAD

**Issue by Barnatu** [MISP/MISP#8771]
After updating MISP from 2.4.159 to 2.4.165, An error is occuring while reaching dashboard, or trying to get events:

Unknown column 'EventTag.relationship_type' in 'field list'
`Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'EventTag.relationship_type' in 'field list'
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
MISP/PyMISP#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
MISP/PyMISP#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
MISP/PyMISP#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll()
MISP/PyMISP#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany()
MISP/PyMISP#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation()
MISP/PyMISP#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
MISP/PyMISP#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
MISP/PyMISP#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): Model->find()
MISP/PyMISP#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate()
MISP/PyMISP#10 /var/www/MISP/app/Controller/EventsController.php(736): Controller->paginate()
MISP/PyMISP#11 [internal function]: EventsController->index()
MISP/PyMISP#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
MISP/PyMISP#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
MISP/PyMISP#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
MISP/PyMISP#15 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
MISP/PyMISP#16 {main}`

The process was done as followed:
sudo -u www-data git reset --hard
sudo -u www-data git pull
sudo -u www-data git submodule update --init --force --recursive

Can you please give me some hints to maybe update my DB to the latest schema where it includes this column ?
I read this so I assume the change was made in 2.4.164: https://www.misp-project.org/2022/10/10/MISP.2.4.164.released.html/

EDIT:
The update worker is healthy.
It seems in diagnostic page under "SQl database status" that DB version is on v95 and is expected to be in v99.
It says under schema status "Notice : An update is currently in progress. " 
When I'm reaching the updateProgress page, it shows :
"Updates are locked due to an ongoing update process. Release the update lock only if you know what you are doing.

Before unlocking, make sure the update worker is healthy
(automatically unlock in Xmin XXsec)
Complete update progression 4 remaining
Database Update progress for update 95
100%
	Update command
	
Update 1 ALTER TABLE `servers` ADD `remove_missing_tags` tinyint(1) N[...] Started @ 2022-11-23 11:32:38 Elapsed Time @ 00:00:02
ALTER TABLE `servers` ADD `remove_missing_tags` tinyint(1) NOT NULL DEFAULT 0 AFTER `skip_proxy`;
Successfully executed the SQL query for 95
"
![updateProgress](https://user-images.githubusercontent.com/116751984/203540184-aa4db2f4-2adf-4dfb-bb22-eeb6362933a5.png)

EDIT2:
Issue seems to be fixed by itself after the update lock got released.
It seems a lot of troubles happened during the migration.
Schema status:
![schema_issues_1](https://user-images.githubusercontent.com/116751984/203566688-9864820a-f457-4a1c-845e-8922c607cc57.png)

In database index:
![schema_issue_2](https://user-images.githubusercontent.com/116751984/203566701-6d075619-138e-4f39-bf0d-66c5b4d063f9.png)
![schema_3](https://user-images.githubusercontent.com/116751984/203566724-96947864-b216-49e7-8e41-f7dab90e0866.png)

Is there a way to make all changes at once instead of fixing each issue one by one by executing each command ?

**Comment by baphael** [comment]
Hello,
exact same situation for me after upgrading from 2.4.152 to 2.4.168. Thanks for the details ! :rocket:
