### ISSUE TITLE
Bug: Bro export broken after upgrade to MISP 2.4.165 / MariaDB 10.4 

### ISSUE THREAD

**Issue by pettai** [MISP/MISP#8803]
### Expected behavior

Bro export via URL https://misp.domain.tld/attributes/bro/download/... has been working fine until latest upgrade to MISP 2.4.165 / MariaDB 10.4

### Actual behavior

https://misp.domain.tld/attributes/bro/download/... generates a error-response:

```
An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

```

### Steps to reproduce

Point your browser/curl towards https://misp.domain.tld/attributes/bro/download/... 

### Version

2.4.165

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.2 (ubuntus standard repo)

### Browser

Firefox / curl

### Browser version

latest stable version

### Relevant log output

```shell
MISP_ROOT/app/tmp/logs/error.log:

2022-12-03 13:59:15 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'bro' at line 1
Request URL: /attributes/bro/download/domain
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('bro', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('bro', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(648): DboSource->fetchAll('bro', Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(834): DboSource->query('bro', Array, Object(Attribute))
#5 /var/www/MISP/app/Controller/AttributesController.php(1906): Model->__call('bro', Array)
#6 [internal function]: AttributesController->bro('download', 'domain')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pettai** [comment]
Database debug log of the query:

```
| 2022-12-12 10:13:48.528643 | [misp] @ localhost []     |    138701 |         1 | Connect      | misp@localhost as anonymous on misp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2022-12-12 10:13:48.528951 | misp[misp] @ localhost [] |    138701 |         1 | Query        | SET NAMES utf8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2022-12-12 10:13:48.532501 | misp[misp] @ localhost [] |    138701 |         1 | Query        | SELECT `User`.`date_modified` FROM `misp`.`users` AS `User`   WHERE `id` = 128    LIMIT 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2022-12-12 10:13:48.536451 | misp[misp] @ localhost [] |    138701 |         1 | Query        | bro                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 2022-12-12 10:13:48.538140 | misp[misp] @ localhost [] |    138701 |         1 | Query        | SELECT `User`.`date_modified` FROM `misp`.`users` AS `User`   WHERE `id` = 128    LIMIT 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 2022-12-12 10:13:48.545918 | misp[misp] @ localhost [] |    138701 |         1 | Quit         |
```

Is `bro` suppose to be an function in the misp db ?

**Comment by mathurin68** [comment]
Is this still an issue?  Other curl commands seem to work fine? 

I'm getting the 'Internal Error' message too... I just upgraded to 2.4.168 a few minutes ago. 

```
curl  -k --header "Authorization: apikey" \
      --header "Accept: application/json" \
      --header "Content-Type: application/json" https://misp.our.net/attributes/bro/download/url
```

**Comment by jloehel** [comment]
How can we help to fix that? I really would like to enable dovehawk again. I am seeing the same error like @pettai. 

MISP Version: 2.4.166
MySQL Version: 8.0.32-0ubuntu0.20.04.2

SQL Log:
```
2023-02-03T07:56:02.257462Z         8 Query     SELECT `User`.`date_modified` FROM `misp`.`users` AS `User`   WHERE `id` = 8    LIMIT 1
2023-02-03T07:56:02.322303Z         8 Query     bro
```

**Comment by amrroq** [comment]
Experiencing this same issue, which is preventing dovehawk from functioning.  Receiving identical log outputs as those previously posted here.

MISP 2.4.167
Ubuntu 20.04
PHP 7.4.3-4ubuntu2.17
MySQL Ver 15.1 Distrib 10.3.37-MariaDB

**Comment by adulau** [comment]
This has been fixed in https://github.com/MISP/MISP/commit/6df6924ca3d361084a44b96f1314523dd39d4d81 you can git pull the latest update from 2.4 branch.

**Comment by KaidoLogi** [comment]
How do you revert to an older version 2.4.167?
