### ISSUE TITLE
Error: An Internal Error Has Occurred when clicked on Server Settings and Maintenance

### ISSUE THREAD

**Issue by ce00267** [MISP/MISP#8809]
### Support Questions

Hi Team,
I am new to MISP.
After the initial installation configuration, everything works fine and I was able to enable default feeds and create and import custom ports.
Now I am experiencing this error: 'An Internal Error Has Occurred' when I click on Administration > Server Settings and maintenance.
I've checked the config.php and config-default.php file and the proxy configurations, and everything seems fine with no issues.
But I  am still seeing the error.
Also feeds imports and feed cache now fail.

Any advice or guidance to get back to a working status will be appreciated.

Kind regards
Chris

### MISP version

2.4.165

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Edge, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mahalepoto** [comment]
I am also facing similar issue. Cant access server setting maintenance/Jobs and Workflow.
My error logs as follow,

```
Error: [TypeError] Return value of Workflow::getEnabledModules() must be of the type array, bool returned
Request URL: /workflows/triggers
Stack Trace:
#0 /var/www/MISP/app/Model/Workflow.php(864): Workflow->getEnabledModules()
#1 /var/www/MISP/app/Model/Workflow.php(851): Workflow->__mergeGlobalConfigIntoLoadedModules()
#2 /var/www/MISP/app/Model/Workflow.php(1055): Workflow->loadAllWorkflowModules()
#3 /var/www/MISP/app/Controller/WorkflowsController.php(187): Workflow->getModulesByType()
#4 [internal function]: WorkflowsController->triggers()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
2023-01-31 16:53:14 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update, scheduler]
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(368): BackgroundJobsTool->validateQueue()
#1 /var/www/MISP/app/Model/Server.php(3699): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Controller/ServersController.php(1200): Server->workerDiagnostics()
#3 [internal function]: ServersController->serverSettings()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main} 
```
OS = Kali 2022.4
Browser = Chrome

**Comment by guzzijones** [comment]
I just encountered this after attempting to upgrade my docker image from v2.4.193 to the latest 2.5 version.  I then downgraded and I now have this problem.

**Comment by guzzijones** [comment]
I ended up having to update the misp-core docker image and the misp-module docker image.  Then I also had to set the redis password to `redispassword`.  We have a custom helm chart that we use.

**Comment by guzzijones** [comment]
The trick was reading the `./app/tmp/logs/errors.log` and seeing that redis was failing
