### ISSUE TITLE
Bug: Missing access_logs in db_schema.json

### ISSUE THREAD

**Issue by skalvaro** [MISP/MISP#8813]
### Expected behavior

Newly implemented access logs work. [https://github.com/MISP/MISP/releases/tag/v2.4.166](url)

### Actual behavior

Errors when trying to view 'Logs > Access Logs'.

### Steps to reproduce

Try to view the access logs 'Logs > Access Logs'.

### Version

2.4.166

### Operating System

RedHat

### Operating System version

7.9

### PHP version

7.4

### Relevant log output

```shell
2022-12-09 13:58:43 Error: [MissingTableException] Table access_logs for model AccessLog was not found in datasource default.
Exception Attributes: array (
  'table' => 'access_logs',
  'class' => 'AccessLog',
  'ds' => 'default',
)
Request URL: /admin/access_logs/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('access_logs')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1490): Model->schema()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(421): Model->hasField('id')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(158): PaginatorComponent->validateSort(Object(AccessLog), Array, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate(Object(AccessLog), Array, Array)
#6 /var/www/MISP/app/Controller/AccessLogsController.php(65): Controller->paginate()
#7 [internal function]: AccessLogsController->admin_index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AccessLogsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AccessLogsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skalvaro** [comment]
Just upgraded to v2.4.167 (https://github.com/MISP/MISP/commit/faa1fc5300fc8e1e6e98c72112801625e583a3fb) and I no longer see the mentioned errors.
