### ISSUE TITLE
Support: New Background Processor Migration Issue

### ISSUE THREAD

**Issue by BurakOzgen** [MISP/MISP#8863]
### Support Questions

Hi,

To migrate to new background processor I have followed the steps in "background-jobs-migration-guide.md" but after enable the background processor Workers screen gave an error "Warning: MISP cannot connect to the Supervisord API, check the following settings are correct: [`supervisor_host`, `supervisor_port`, `supervisor_user`, `supervisor_password`] and restart the service. For details check the MISP error logs." All configurations are correct I checked Redis, related Php config files but I can not figure it out the problem. Also when I click the Start Worker PHP giving me "Error: An error occured when getting the workers statuses via Supervisor API: An HTTP error occurred: Forbidden"

### MISP version

2.4.1

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
2023-01-18 17:21:36 Error: An error occured when getting the workers statuses via Supervisor API: An HTTP error occurred: Forbidden
2023-01-18 17:21:36 Error: Error getting supervisor status.
[fXmlRpc\Exception\HttpException] An HTTP error occurred: Forbidden
Stack Trace:
#0 /var/www/MISP/app/Vendor/lstrojny/fxmlrpc/src/fXmlRpc/Transport/HttpAdapterTransport.php(58): fXmlRpc\Exception\HttpException::httpError()
#1 /var/www/MISP/app/Vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(154): fXmlRpc\Transport\HttpAdapterTransport->send()
#2 /var/www/MISP/app/Vendor/supervisorphp/supervisor/src/Supervisor.php(94): fXmlRpc\Client->call()
#3 /var/www/MISP/app/Vendor/supervisorphp/supervisor/src/Supervisor.php(112): Supervisor\Supervisor->call()
#4 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(512): Supervisor\Supervisor->__call()
#5 /var/www/MISP/app/Model/Server.php(3611): BackgroundJobsTool->getSupervisorStatus()
#6 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#7 [internal function]: ServersController->serverSettings()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#12 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @BurakOzgen 
Try to run this command:
```bash
curl --location 'http://supervisor_host:supervisor_port/RPC2' \
--user supervisor_user:supervisor_password \
--header 'Content-Type: application/xml' \
--data '<?xml version="1.0"?>
<methodCall>
  <methodName>supervisor.getAPIVersion</methodName>
</methodCall>'
```
Replace the settings accordingly before running the command, it should return something like this:

```xml
<?xml version='1.0'?>
<methodResponse>
    <params>
        <param>
            <value>
                <string>3.0</string>
            </value>
        </param>
    </params>
</methodResponse>
```
