### ISSUE TITLE
Support: Fresh install not working

### ISSUE THREAD

**Issue by jtajo2002** [MISP/MISP#8900]
### Support Questions

Hi

I installed a fresh environment and I cannot see the homepage. When browsing http://xx.xx.xx.xx

I run journalctl -f and attaching the logs below

I followed this documentation : -->>https://github.com/amuehlem/MISP-RPM/blob/master/RHEL8.md

![capture3](https://user-images.githubusercontent.com/55409049/216841785-9398d438-2ad1-4816-a19d-f4c0ee59a243.jpg)

### MISP version

misp-2.4.167-1.el8.x86_64

### Operating System

redhat

### Operating System version

8.7

### PHP version

7.4.33

### Browser

firefox

### Browser version

109.0.1 64 bit

### Relevant log output

```shell
Feb 05 22:44:39 misp start.sh[17813]: #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
Feb 05 22:44:39 misp start.sh[17813]: #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('/var/www/MISP/a...')
Feb 05 22:44:39 misp start.sh[17813]: #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
Feb 05 22:44:39 misp start.sh[17813]: #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
Feb 05 22:44:39 misp start.sh[17813]: #7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct()
Feb 05 22:44:39 misp start.sh[17813]: #8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
Feb 05 22:44:39 misp start.sh[17813]: #9 {main}
Feb 05 22:44:39 misp start.sh[17823]: Error: syntax error, unexpected '/'
Feb 05 22:44:39 misp start.sh[17823]: #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read()
Feb 05 22:44:39 misp start.sh[17823]: #1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load()
Feb 05 22:44:39 misp start.sh[17823]: #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
Feb 05 22:44:39 misp start.sh[17823]: #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
Feb 05 22:44:39 misp start.sh[17823]: #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('/var/www/MISP/a...')
Feb 05 22:44:39 misp start.sh[17823]: #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
Feb 05 22:44:39 misp start.sh[17823]: #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
Feb 05 22:44:39 misp start.sh[17823]: #7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct()
Feb 05 22:44:39 misp start.sh[17823]: #8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
Feb 05 22:44:39 misp start.sh[17823]: #9 {main}
Feb 05 22:44:39 misp start.sh[17833]: Error: syntax error, unexpected '/'
Feb 05 22:44:39 misp start.sh[17833]: #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read()
Feb 05 22:44:39 misp start.sh[17833]: #1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load()
Feb 05 22:44:39 misp start.sh[17833]: #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
Feb 05 22:44:39 misp start.sh[17833]: #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
Feb 05 22:44:39 misp start.sh[17833]: #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('/var/www/MISP/a...')
Feb 05 22:44:39 misp start.sh[17833]: #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
Feb 05 22:44:39 misp start.sh[17833]: #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
Feb 05 22:44:39 misp start.sh[17833]: #7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct()
Feb 05 22:44:39 misp start.sh[17833]: #8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
Feb 05 22:44:39 misp start.sh[17833]: #9 {main}
Feb 05 22:44:39 misp systemd[1]: misp-workers.service: Succeeded.
Feb 05 22:44:39 misp systemd[1]: Started MISP workers.
Feb 05 22:44:39 misp audisp-syslog[1128]: node=misp type=SERVICE_START msg=audit(1675626279.715:1169): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=misp-workers comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' UID="root" AUID="unset"
Feb 05 22:44:39 misp audisp-syslog[1128]: node=misp type=SERVICE_STOP msg=audit(1675626279.715:1170): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=misp-workers comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' UID="root" AUID="unset"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dogoniyat** [comment]
I have exactly the same.
running `su - apache /bin/bash --command /var/www/MISP/app/Console/worker/start.sh` gives me the same output, I suspect it's coming from one of the files included, but I can't figure out which one.

I suspect the line `#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')`would give me the culprit, but it found spiritual to truncate the file name...

However, modifying line 327 to add `echo "config=$config, key=$key\n";` I get config=default, key=config, I know the line that breaks the program is `$values = $reader->read($key);` but I don't know what file it's actually reading.
