### ISSUE TITLE
Bug: Permission bug on removing tag from Tag collection

### ISSUE THREAD

**Issue by 01dr1ch** [MISP/MISP#8905]
### Expected behavior

Privileged user (having Tag_editor or admin) navigates to defined Tag collections and by clicking [x] sign removes particular Tag from a Tag collection of choice.

Example:
![image](https://user-images.githubusercontent.com/82970780/217332740-cd58b320-3057-4903-bcd4-580421125758.png)

### Actual behavior

Instead, following is thrown upon clicking the [x] symbol (i.e. the dialog confirmation window "Remove tag" doesn't appear):

user: having "admin" role, i.e. **Site Admin** permission
![image](https://user-images.githubusercontent.com/82970780/217333217-aa174db5-4c23-433a-96ff-61131ba27b38.png)
![image](https://user-images.githubusercontent.com/82970780/217336619-ff7099c5-b271-4ef6-a262-e578a74b7858.png)
![image](https://user-images.githubusercontent.com/82970780/217336464-f74c982a-ff13-4ccd-8998-45f5a89c832b.png)

The attempt is not logged in none of logs, except for:
```
less /var/log/MISP/app/tmp/logs/error.log
```
``` 
2023-02-06 19:01:11 Error: [MethodNotAllowedException] You do not have permission to use this functionality.
Request URL: /galaxies/selectGalaxyNamespace/18/tag_collection/local:0?_=1675706465474
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(349): ACLComponent->checkAccess()
#1 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): AppController->beforeFilter()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#5 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#6 {main}
```

Now, what works is all of following:
- Create tag collection
- Delete tag collection
- Assign tag to Tag collection (both new and existing ones)
- Assign and remove Galaxy cluster Tag

The only option is to remove whole Tag collection. See Extra attachments for extra steps we took in investigation.

Thank you,
Oldrich

### Steps to reproduce

1) Login
2) Create Tag collection or use existing one
3) Assign arbitrary tag - newly created, one from custom taxonomy, any tag acquired from MISP Events from other organizations.
4) Attempt to remove the tag - fails

### Version

2.4.167

### Operating System

RedHat

### Operating System version

7.9 Maipo

### PHP version

7.4.33

### Browser

Chrome, Firefox

### Browser version

newest

### Relevant log output

```shell
2023-02-06 19:01:11 Error: [MethodNotAllowedException] You do not have permission to use this functionality.
Request URL: /galaxies/selectGalaxyNamespace/18/tag_collection/local:0?_=1675706465474
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(349): ACLComponent->checkAccess()
#1 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): AppController->beforeFilter()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#5 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#6 {main}
```

### Extra attachments

Our investigation led us to:
``` ./Controller/Component/ACLComponent.php ```
and following piece of code - definition of ACLs
```
            'tagCollections' => array(
                'add' => array('perm_tag_editor'),
                'addTag' => array('perm_tag_editor'),
                'delete' => array('perm_tag_editor'),
                'edit' => array('perm_tag_editor'),
                'getRow' => array('perm_tag_editor'),
                'import' => array('perm_tag_editor'),
                'index' => array('*'),
                'removeTag' => array('perm_tag_editor'),
                'view' => array('*')
            ),
```

Changing the 'removeTag' to * didn't influence the behavior, we were still not able to remove the tag.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tubetrain** [comment]
Experiencing the same bug on 2.4.168

**Comment by Ninja-ca** [comment]
Hi,

Same bug on 2.4.179 and 2.4.194
