### ISSUE TITLE
Support: You are not on a branch, Update MISP will fail 

### ISSUE THREAD

**Issue by gigagoirle** [MISP/MISP#8911]
### Support Questions

Hi,

We had MISP running on Centos 7 and we migrated the MISP to RHEL8 server. The following steps were done:

1. Install new RHEL8 server
2. Install MISP software by following this guide https://github.com/amuehlem/MISP-RPM/blob/master/RHEL8.md because we had a similar issue as this one https://github.com/MISP/MISP/issues/8669
3. Backup MISP data with the backup/restore script from MISP
4. Restore MISP data on the new installed server with the same script
5. Copied Apache + SSL certs to the new server
6. Configured PHP

MISP is running fine now but we see the alert regarding "You are not on a branch, Update MISP will fail". 

I checked the permissions and I dont see no cause for this problem. In the error log (/var/www/MISP/app/tmp/logs) I see only the following (see Relevant log output section).

I am not sure if these errors has something the do with the "You are not on a branch, Update MISP will fail" message.

Hope someone can help us,
Giga

### MISP version

2.4

### Operating System

RedHat

### Operating System version

8

### PHP version

7.4

### Relevant log output

```shell
Request URL: /server-status?auto=
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#1 {main}
2023-02-10 12:20:00 Error: [MissingControllerException] Controller class Server-statusController could not be found.
Exception Attributes: array (
  'class' => 'Server-statusController',
  'plugin' => NULL,
)
Request URL: /server-status?auto=
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#1 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dogoniyat** [comment]
The root cause is that it is using $PATH_TO_MISP/venv/bin/pip, which is 3.6.8,.. The problem is that poetry>=1.2.0 requires Python 3.7 (as per https://python-poetry.org/docs/), while my RHEL 8.7 and /venv provide 3.6.8, that's the root cause of it.
Now, how can I upgrade the version of Python3 in /venv to use Python 3.7 or 3.8 instead, or force pip to download poetry-1.0.8 and use it instead in misp-stix?
`# /var/www/MISP/venv/bin/pip --version`
`pip 21.3.1 from /var/www/MISP/venv/lib/python3.6/site-packages/pip (python 3.6)`
