### ISSUE TITLE
Bug: Unable to delete Object using OpenAPI. File is missing.

### ISSUE THREAD

**Issue by DimSys** [MISP/MISP#8913]
### Expected behavior

For Object deletion the Documentation says i should use request:
https://misp.local/objects/delete/{objectId}/{hardDelete}

### Actual behavior

In fact we get an error:
`{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/objects\/delete\/130546\/0"}
`
And in error.log:
```
2023-02-13 22:23:48 Error: [MissingViewException] View file "Objects/json/delete.ctp" is missing.
Exception Attributes: array (
  'file' => 'Objects/json/delete.ctp',
)
Request URL: /objects/delete/130546/0
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/JsonView.php(107): View->_getViewFileName()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(968): JsonView->render()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#5 {main}

```

The file "MISP/app/View/Objects/json/delete.ctp" is actually missing. And **in Github repository as well**.

### Steps to reproduce

```
curl  --header "Authorization: MY_AUTH_KEY" \
      --header "Accept: application/json" \
      --header "Content-Type: application/json" -vk https://misp.mydomain/objects/delete/130546/0
```

### Version

2.4.167

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DimSys** [comment]
DELETE Method was missed in request. Sorry.
Closing
