### ISSUE TITLE
Bug: Jobs not completed when scheduled

### ISSUE THREAD

**Issue by valpet93** [MISP/MISP#8920]
### Expected behavior

Once every feed has been fetched, a re-fetch via task-scheduler of the feed in fixed events mode and delta merge mode should work flawlessly, just like when I fetch the feed for the first time.

### Actual behavior

Actually, it doesn't work so. It should not lead to having many pages of uncompleted jobs:
![image](https://user-images.githubusercontent.com/34856348/220323136-4b4a7cfc-ad01-4d35-805f-edd72723997b.png)A

### Steps to reproduce

install misp with modules on fresh ubuntu 20, set feeds 4, 11, 17, 41, 47, 48, 49 and 58 check enabled, caching enabled, lookup visible, autopublish, override IDS Flag and Delta merge.

Then fetch all enabled feeds. Once finished, cache them.
Once finished, set task scheduler to fetch feed every 6 hours. At first start of the task scheduler, the fetch job will stop and the progress bar will never reach 100%.

I've tried to:
- set memory_limit = -1 in any php.ini
- restart all workers
- test the bug with simplebackgroundjob
- test the bug with 5 workers for cache, default and prio

### Version

v2.4.168

### Operating System

ubuntu

### Operating System version

20.04

### PHP version

7.4.3-4ubuntu2.17

### Browser

chrome

### Relevant log output

```shell
here are some errore i get from logs that may be related:

2023-01-30 18:52:42 Warning: Could not add event '5a5df804-acb5-4fd3-8c76-6982e5e1ce75' from feed 66: 1900 2023-01-30 18:52:42 Warning: Could not add event 'ca0e87d9-b850-404d-8b17-e51d2e2b717e' from feed 66: 1901 2023-01-30 18:52:42 Warning: Could not add event '83b4018e-1f45-48c4-908b-2ef8d2e1db0f' from feed 66: 1902 2023-01-30 18:52:42 Warning: Could not add event 'de55cf56-1a4d-4d46-954c-40f0f176d53e' from feed 66: 1903 2023-01-30 18:52:43 Error: Could not add event 'de55cf56-1a4d-4d46-954c-40f0f176d53e' from feed 66. [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Purchase order.exe' for key 'value' Stack Trace: #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute() #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute() #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute() #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create() #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave() #5 /var/www/MISP/app/Model/OverCorrelatingValue.php(50): Model->save() #6 /var/www/MISP/app/Model/Correlation.php(503): OverCorrelatingValue->block() #7 /var/www/MISP/app/Model/Attribute.php(470): Correlation->afterSaveCorrelation() #8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute->afterSave() #9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEventManager->dispatch() #10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave() #11 /var/www/MISP/app/Model/Attribute.php(2518): Model->save() #12 /var/www/MISP/app/Model/MispObject.php(1134): Attribute->captureAttribute() #13 /var/www/MISP/app/Model/Event.php(3776): MispObject->captureObject() #14 /var/www/MISP/app/Model/Feed.php(1098): Event->_add() #15 /var/www/MISP/app/Model/Feed.php(693): Feed->__addEventFromFeed() #16 /var/www/MISP/app/Model/Feed.php(1182): Feed->downloadFromFeed() #17 /var/www/MISP/app/Console/Command/ServerShell.php(404): Feed->downloadFromFeedInitiator() #18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed() #19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand() #20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch() #21 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run() #22 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valpet93** [comment]
using this url https://MISP_HOST/attributes/index/sort:timestamp/direction:desc I can actually see that new attributes are added to fixed events, but I don't know whether they are added by the last fetch or by the scheduled fetch started 1 week ago...

**Comment by Kradma** [comment]
We are having more or less the same problem, there are some feeds that get stuck in that "saving data" state for ever:
![imagen](https://github.com/MISP/MISP/assets/15791908/816fa02a-43b2-40ef-a117-19a45d44d295)

I can open a new Issue just for this case, but it looks the same problem in the 2.4.288
