### ISSUE TITLE
Feature Request: PyMISP add more flexibility to csv_loader

### ISSUE THREAD

**Issue by pelletier6666** [MISP/MISP#8939]
### Is your feature request related to a problem? Please describe.

The feature is related to a lack of flexibility of the `load_csv.py` python script in `/var/www/MISP/PyMISP/examples` (and `PyMISP/pymisp/tools/csvloader.py` which is associated to it). 

**What i've understood from this script**, is that it uses a [MISP object](https://github.com/MISP/misp-objects/) passed in as a parameter to create for each csv row a new instance of it. All the objects will next be combined in one unique event.
The fieldnames of the csv can be override via the `-f` in order to match exactly the name of the field/attributes of the object definition.2 Parsing issues came up:
   
1°) The CSV to parse  can have a very rich header (like [bazaar feed](https://bazaar.abuse.ch/export/csv/recent/)) with many columns, all don't fit specifically in a MISP object. While some other columns fits perfectally together.   
2°) Another CSV can be this time much less rich with few colomn number. However, 1 or 2 columns may be of little importance and does not fit the object definition. 

### Describe the solution you'd like

What i propose is to add more flexibility by allowing to omit some of the CSV headers:

`./load_csv.py -n "obj1" -p "path_to_csv" -f "field1_obj1,,field3_obj,field4_obj,field5_obj,"`
_The idea behind this is to create one object with letting the possibility to omit some columns that couldn't fit with the object definition. We can imagine as well add a tag keyword for fields that does not fit into object definition. Then each time we reach this field a substring search will be made to match an existing tags. 

### Describe alternatives you've considered

The problem with the old proposed solution is that it's a pity to forget some IOCs that could be precious, especially when csv reach a high column number. In that case i've imagine this: 
1°) `./load_csv.py -n "obj1,obj2" -p "path_to_csv" -f "field1_obj1,,,field4_obj1,,,field7_obj"  ",field2_obj2,field3_obj2,,field5_obj2,,"`
_The idea behind this is to create several object with each one referencing each other allowing to consume every  columns of the csv. This allow to fix the problem when too much column can't fit into one object_ 

### Additional context

I've made the first part **Describe the solution you'd like** but PyMISP does not recognize the tool CSVLoader1 that i've made when i run `./load_csv1.py`: 

```
Unable to load pymisp properly: No module named 

'pymisp.tools.csvloader1' 
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/examples/./load_csv1.py", line 7, in <module>
    from pymisp.tools import CSVLoader1
  File "/usr/local/lib/python3.10/dist-packages/pymisp/tools/__init__.py", line 17, in <module>
    from .csvloader1 import CSVLoader1  # noqa
ModuleNotFoundError: No module named 'pymisp.tools.csvloader1'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafiot** [comment]
The solution you propose add *a lot* of complexity and it will keep getting more complicated, rendering the code extremely hard to maintain. I'd strongly recommend to write a dedicated importer for complex CSV files, this way you have full control on each fields and will have a lot easier time maintaining it long term.

Alternatively, if you *really* want to use the csv importer, I'd suggest to pre-process the CSV file, remove the columns you don't want, and then use the CSV importer script.

Regarding the script you wrote, based on the error you're getting, I guess it is not in the right directory. Try copying it to `/usr/local/lib/python3.10/dist-packages/pymisp/tools/`

**Comment by pelletier6666** [comment]
Thank you for your answer, 
I see what you mean, it will add too much complexity 
What do you mean by dedicated imported for complex CSV files ?

**Comment by pelletier6666** [comment]
I've alreadey add this line: 
```
from .csvloader import CSVLoader  # noqa
from .csvloader1 import CSVLoader1  # noqa
```
to the folowing directories: 
```
/var/www/MISP/PyMISP/pymisp/tools/__init__.py
/var/www/MISP/PyMISP/build/lib/pymisp/tools/__init__.py
/var/www/MISP/venv/lib/python3.10/site-packages/pymisp/tools/__init__.py
```
And i restart the misp-module service by typing `sudo systemctl restart misp-modules` (i don't know if it's useful).
![image](https://user-images.githubusercontent.com/51533854/222104841-451ccd1f-7698-4b75-bd66-0a28526a2aaf.png)

**Comment by Rafiot** [comment]
What I mean by dedicated importer script is that you can write a python script that  does the following:

1. Create a MISP event 
2. opens the csv file
3. read it row by row
4. generate a MISP Object for each of them (ignoring the columns you don't want)
5. attach said object to the event
6. submit the event with all the objects to the MISP instance

Regarding the file that cannot be imported, there are a lot of moving parts, from the permissions to figuring out which virtual environment you're using. I won't be able to help you without debugging myself. 
I recommend you to:
1. clone PyMISP
2. add the file in `PyMISP/pymisp/tools/`
3. add `from .csvloader1 import CSVLoader1  # noqa` to `PyMISP/pymisp/tools/__init__.py`
4. run `poetry install`
5. run `poetry shell`
6. run your script

And that should work. 

But again, dedicated script to convert the complex CSV to a MISPEvent is the way to go long term. Using the CSV directly is only an option to consider if you have a simple csv and want to give it a quick try.

**Comment by pelletier6666** [comment]
Thank you so much for these detailed informations, i'm going to try it.
