### ISSUE TITLE
Bug: Reinstalation of MISP - Mysql Connection error - Bad Password

### ISSUE THREAD

**Issue by pelletier6666** [MISP/MISP#8944]
### Expected behavior

""

### Actual behavior

After uninstall MISP by removing `/var/www/MISP` and `/var/www/{.cache,.local}`
I've tried a new installation that failed at this part of the [instalation script](https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sh)
```
coreCAKE () {
  debug "Running core Cake commands to set sane defaults for ${LBLUE}MISP${NC}"

  # IF you have logged in prior to running this, it will fail but the fail is NON-blocking
  ${SUDO_WWW} ${RUN_PHP} -- ${CAKE} userInit -q  <-- here is the error

  # This makes sure all Database upgrades are done, without logging in.
  ${SUDO_WWW} ${RUN_PHP} -- ${CAKE} Admin runUpdates
  ```
  Here is the error that i receive from MISP instalation logs: 
  ```
  Good, /usr/local/src exists and is writeable as misp
#####################################################################  (68%)
#########################################################################  (72%)
ERROR 1045 (28000): Access denied for user 'misp'@'localhost' (using password: YES)
Next step: Updating Galaxies, ObjectTemplates, Warninglists, Noticelists and Templates
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#10 /var/www/MISP/app/Model/AppModel.php(106): Model->__construct()
#11 /var/www/MISP/app/Model/User.php(237): AppModel->__construct()
#12 [internal function]: User->__construct()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#14 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(279): ClassRegistry::init()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#18 /var/www/MISP/app/Model/AppModel.php(106): Model->__construct()
#19 [internal function]: AppModel->__construct()
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#24 /var/www/MISP/app/Console/Command/AppShell.php(42): Shell->initialize()
#25 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize()
#26 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#27 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#28 {main}
```
  When i look at the error at mysql service i see the folowing:
  ```
  journalctl -u mariadb.service | tail -n 1
  mars 02 14:54:14 nicop-IdeaPad-5-Pro-14ARH7 mariadbd[1037]: 2023-03-02 14:54:14 42 [Warning] Access denied for user 'misp'@'localhost' (using password: YES)
  ```
  When i look at the file `/var/www/MISP/app/Config/database.php` i see the following:
  ```
  <?php
  class DATABASE_CONFIG {
          public $default = array(
                  'datasource' => 'Database/Mysql',
                  //'datasource' => 'Database/Postgres',
                  'persistent' => false,
                  'host' => 'localhost',
                  'login' => 'misp',
                  'port' => 3306, // MySQL & MariaDB
                  //'port' => 5432, // PostgreSQL
                  'password' => '239e310bd74cf1d71f9e66cd81211bd6b4d269XXXXX',
                  'database' => 'misp',
                  'prefix' => '',
                  'encoding' => 'utf8',
          );
  }
  ```
  I don't know how to get the password in order to try a `mysql -u misp -h localhost -p` or `mysql -u root -h localhost -p` as mentioned here: https://github.com/MISP/MISP/issues/5737
 
 I know that there is file at `~/mysql.txt` with the password hash that gets generated but i don't know the origin password (without the hash).
 
I've seen [here](https://stackoverflow.com/questions/5654819/how-can-i-decrypt-mysql-passwords) that we can decrypt the hash by doing the invert of this (SHA1(UNHEX(SHA1("password")))   but i don't know how to do it 

### Steps to reproduce

""

### Version

2.4.168

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pelletier6666** [comment]
Following this [tutoriel](https://linuxize.com/post/how-to-reset-a-mysql-root-password/), i have been able to connect to mysql server 
with this command `sudo mysqld_safe --skip-grant-tables &` without any password. 
Then i had access to the hash of the user `misp` and `root` (a part of the hash). I could see that it doesn't match the hash of the password stored in `~/my-sql.txt`. So i think to uninstall misp properly you also have to delete the `misp` and `root` user of the mysql database

**Comment by pelletier6666** [comment]
But unfortunately you can drop account to the database server when used with the option `--skip-grant-tables`
```
MariaDB [(none)]> DROP USER 'misp'@'localhost';
ERROR 1290 (HY000): The MariaDB server is running with the --skip-grant-tables option so it cannot execute this statement
```

**Comment by Nicolas-Pellletier** [comment]
I've got the same error using the same os version.
But for me i've properly succed to install misp core with `bash /tmp/INSTALL.sh -c`. Then the error came when i tried to add the `dashboard` feature doing a new time `bash /tmp/INSTALL.sh -c -D` as i can't do `bash /tmp/INSTALL.sh -D` alone.

I don't know what to do next to make it work again

**Comment by Nicolas-Pellletier** [comment]
I've droped the misp user in mariadb databse then doig installation again but it does not work
