### ISSUE TITLE
Bug: Unable to scroll Audit Logs page

### ISSUE THREAD

**Issue by RyanOchieng** [MISP/MISP#8985]
### Expected behavior

I should be able to view more than one page worth of logs (if present) when using **View Event History** while viewing an **Event**

### Actual behavior

The UI will then show the error 

"An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator." and the log file will show as what's in Relevant log output

when having more than one page available of Audit logs for the event. The page looks as follows, implying there is more than one page of logs available

<img width="320" alt="Screenshot 2023-03-28 at 6 05 32 pm" src="https://user-images.githubusercontent.com/109130639/228155544-02f2cd76-9096-47a9-a874-d8c7c2bcc13b.png">

I have also been able to reproduce the same issue when using MISP from a Docker image that utilises CentOS as the base OS

### Steps to reproduce

Either create a new event and perform any number of actions to have more than one page worth of Audit Logs OR use an existing event that has more than one page worth of Audit Logs.

The UI will then show the error "An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator." and the log file will show as what's in Relevant log output

### Version

2.4.169

### Operating System

Red Hat Enterprise Linux

### Operating System version

7

### PHP version

7.4.33

### Browser

Edge

### Relevant log output

```shell
2023-03-28 07:02:39 Error: [ArgumentCountError] Too few arguments to function AuditLogsController::eventIndex(), 0 passed and at least 1 expected
Request URL: /audit_logs/eventIndex/page:2
Stack Trace:
#0 [internal function]: AuditLogsController->eventIndex()
#1 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#5 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanOchieng** [comment]
Upon further analysis, it would appear that the URL for the 'next' button shown the picture in Actual Behavior is listed as /audit_logs/eventIndex/page:2 where in reality it should be /audit_logs/eventIndex/<event_id>/page:2
