### ISSUE TITLE
Bug:  Allowed memory size of 2097152 bytes exhausted 

### ISSUE THREAD

**Issue by alens** [MISP/MISP#8987]
### Expected behavior

I cant find a solution for my issue with memory_limits on the misp instance.

I added 2048Mb of memory limit in /etc/php/7.4/apache2/php.ini
_memory_limit = 2048M_

restarted apache and try to see diagnostic, where memory_limit regardles my changes does not change and shows (0MB)

max_execution_time (5000 seconds)… OK (recommended: 300 seconds)
**memory_limit (0 MB)**… Low (recommended: 2048 MB)
upload_max_filesize (60 MB)… OK (recommended: 50 MB)
post_max_size (50 MB)… OK (recommended: 50 MB)

Because of this memory limit, the server stops responding and produces the following error:
2023-03-29 14:54:22 Error: Fatal Error (1): Allowed memory size of 2097152 bytes exhausted (tried to allocate 65536 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php, line 547]
2023-03-29 14:54:22 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

### Actual behavior

The amount of memory specified in php.ini should reflect the one reported in the error.log
**2023-03-29 14:54:22 Error: Fatal Error (1): Allowed memory size of **2097152** bytes exhausted (tried to allocate 65536 bytes) **

### Steps to reproduce

.....

### Version

 v2.4.159

### Operating System

ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ansah7** [comment]
@alens Please change the memory limit  in FPM in /etc/php/7.4/fpm/pool.d/www.conf. Uncomment and change the value there. I had a similar issue this resolved it.
php_admin_value[memory_limit] = 3072M
