### ISSUE TITLE
Support: MISP Cant update Feeds openssl error 0A000410

### ISSUE THREAD

**Issue by shadowshift3r** [MISP/MISP#9023]
### Support Questions

In the last two updates MISP hasn't been able to update some feeds and its giving me a SSL error 0A000410 i did some research's before considering posting this , but it haven't found a sound solution for it , and updating my MISP instance hasn't solved the issue. But when i test via the openSSL client it doesn't return any error of any sort.

### MISP version

2.4.170

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox

### Relevant log output

```shell
Application Log from MISP interface:
Could not fetch manifest for feed: Fetching the 'https://www.circl.lu/doc/misp/feed-osint/manifest.json' failed with exception: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:0A000410:SSL routines::sslv3 alert handshake failure stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://www.circl.lu:443 (Unknown error)

/var/www/MISP/app/tmp/logs/error.log

#10 {main}[SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000410:SSL routines::sslv3 alert handshake failure
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://www.openphish.com:443 (Unknown error)
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(146): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): HttpSocketExtended->connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#3 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(185): HttpSocket->request()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#5 /var/www/MISP/app/Model/Feed.php(2076): HttpSocket->get()
#6 /var/www/MISP/app/Model/Feed.php(2037): Feed->getFollowRedirect()
#7 /var/www/MISP/app/Model/Feed.php(343): Feed->feedGetUriRemote()
#8 /var/www/MISP/app/Model/Feed.php(382): Feed->getFreetextFeedRemote()
#9 /var/www/MISP/app/Model/Feed.php(1187): Feed->getFreetextFeed()
#10 /var/www/MISP/app/Console/Command/ServerShell.php(619): Feed->downloadFromFeedInitiator()
#11 /var/www/MISP/app/Console/Command/AppShell.php(48): ServerShell->enqueueFeedFetch()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#15 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#16 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
```

##### Extra attachments
```
Command: openssl -connect openfish.com:443
Output:
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = "DigiCert, Inc.", CN = GeoTrust Global TLS RSA4096 SHA256 2022 CA1
verify return:1
depth=0 CN = www.openphish.com
verify return:1
---
Certificate chain
 0 s:CN = www.openphish.com
   i:C = US, O = "DigiCert, Inc.", CN = GeoTrust Global TLS RSA4096 SHA256 2022 CA1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 18 00:00:00 2023 GMT; NotAfter: Mar 20 23:59:59 2024 GMT
 1 s:C = US, O = "DigiCert, Inc.", CN = GeoTrust Global TLS RSA4096 SHA256 2022 CA1
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: May  4 00:00:00 2022 GMT; NotAfter: Nov  9 23:59:59 2031 GMT
 2 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA1
   v:NotBefore: Nov 10 00:00:00 2006 GMT; NotAfter: Nov 10 00:00:00 2031 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHnDCCBYSgAwIBAgIQCxzHyC14AJD4I9hAXciJbzANBgkqhkiG9w0BAQsFADBc
MQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xNDAyBgNVBAMT
K0dlb1RydXN0IEdsb2JhbCBUTFMgUlNBNDA5NiBTSEEyNTYgMjAyMiBDQTEwHhcN
MjMwMjE4MDAwMDAwWhcNMjQwMzIwMjM1OTU5WjAcMRowGAYDVQQDExF3d3cub3Bl
bnBoaXNoLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANDFi14A
hbhogN6wZ6m8gYUwIUlJ10lOFsO7tAmOLsa+sBjZS99W+/WK9wUocbsAWGfe3mpu
lbk3bPn+zPXhp9FUUvWQzx2wzQEVe5B7Ze8x/mzy4MJvpmOdEsY8qOqiJkikSMGC
MFKZQI3dSfr84YWxFFEERnxEztGFEqG81HowID7Ri4G5lNyEUR1GYlgwd4Zhx+ps
OkCiG4L5f+D3Phq514yUYw0qLZUHfFNDsNIMpnp3nri4abuxn5t5p9g2KBmyEm6v
uZjWq6F+PEfy+fReqVzKUnaLlqg84LtTprHYwu3i99Ker788JjP5nWz0YbfIXjpY
AsXWWdrAlRbkcj0CAwEAAaOCA5gwggOUMB8GA1UdIwQYMBaAFKW01us2xOdrpt/E
ZAsBKiAEuGYjMB0GA1UdDgQWBBTwAItWGngUzXAK34lQexTHsq6MLDArBgNVHREE
JDAighF3d3cub3BlbnBoaXNoLmNvbYINb3BlbnBoaXNoLmNvbTAOBgNVHQ8BAf8E
BAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGfBgNVHR8EgZcw
gZQwSKBGoESGQmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9HZW9UcnVzdEdsb2Jh
bFRMU1JTQTQwOTZTSEEyNTYyMDIyQ0ExLmNybDBIoEagRIZCaHR0cDovL2NybDQu
ZGlnaWNlcnQuY29tL0dlb1RydXN0R2xvYmFsVExTUlNBNDA5NlNIQTI1NjIwMjJD
QTEuY3JsMD4GA1UdIAQ3MDUwMwYGZ4EMAQIBMCkwJwYIKwYBBQUHAgEWG2h0dHA6
Ly93d3cuZGlnaWNlcnQuY29tL0NQUzCBhwYIKwYBBQUHAQEEezB5MCQGCCsGAQUF
BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wUQYIKwYBBQUHMAKGRWh0dHA6
Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9HZW9UcnVzdEdsb2JhbFRMU1JTQTQwOTZT
SEEyNTYyMDIyQ0ExLmNydDAJBgNVHRMEAjAAMIIBfQYKKwYBBAHWeQIEAgSCAW0E
ggFpAWcAdgDuzdBk1dsazsVct520zROiModGfLzs3sNRSFlGcR+1mwAAAYZm3nC2
AAAEAwBHMEUCIDogP6u+/3MwKL0xin03MfnOB9mR46O2tQN86a6cKVP+AiEAyEHp
n2heHPKAa18RZIKoCkk8UEMB/2AZUsSn12A6vboAdQBz2Z6JG0yWeKAgfUed5rLG
HNBRXnEZKoxrgBB6wXdytQAAAYZm3nENAAAEAwBGMEQCIDnAkc1mf+bG+COihenl
1KSfXhWyv4jICL3IUwPOejGMAiBdOvZdP5goSzNtKGbHRpgPY7FDNwWIpS1C4DOY
lsrm9QB2AEiw42vapkc0D+VqAvqdMOscUgHLVt0sgdm7v6s52IRzAAABhmbecNAA
AAQDAEcwRQIhAIHh8JMAjXXfZ1tlz+56iU4FAq0hYB/UEvXwzzcBGJQ9AiAst4Ul
TM76tRzOClrZznGzK5lJ7U2Ta91IBYQxny8ZwTANBgkqhkiG9w0BAQsFAAOCAgEA
hUNLuFyynaSte99VwsiZP/WZgKHUZcbHzyddcW3s+gAcPULfMsa1RLuBU+STQL73
gh8sdxyaBfR1lLyNyBg3V6G364RvmelNSHpsAM6qFxWMRguux1KGEFYvL4QV0hpL
a0ExdKLR9pnMW7U1Hy6IsqMZqHe2YfbpXf8GdFUUCJouCMtmOi5AEQrKqOB1jqCK
z4FYs0tHHg/opL9kRi7PtljaHdS/dNGOuIEOAdressXbJkqeeWsMNNvje4oyIlgT
s4UyykC1aCxBiLAGudDhN92SBaMqOS/2qUHHPJv/5eCcVOCRoTxsPXURggrkwyMs
GPNAh5QGuEn+HSVB7OP7/0f41awOXdnUjTLIR3sbKHj5q/wYFwgOw6YwCxXK0cm3
ujA0tGs4fgDpAJ9OZspv8c7oPWTDHvXmSKaoUJLpBGvma7HL4LZ1iZZclcBMtgkq
M9odB7ZKJuRuMdtZbXRmGF5H4i0540rvE89F9rQusdjlLxmF0ipZAqBb6umLv03b
9KE82B70vC/Jl53wW86i3U4cNBVnjQS1nUZuxzershH6De4jUJuryQ5uh500Tm0T
mzIccbJ86l6j60WtC4oRSeKnTWmJ9o/jIklIQWKlto3csFaLsVsReJ6nusIpc3FA
9XyVUx62+Kbd4ggSvcycrzPdAXKFNbBeBTmpLBxt61Y=
-----END CERTIFICATE-----
subject=CN = www.openphish.com
issuer=C = US, O = "DigiCert, Inc.", CN = GeoTrust Global TLS RSA4096 SHA256 2022 CA1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 5078 bytes and written 441 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 204B7AF365600238FE615A555A762DB47B19C0835BF4D1645B10F37816CF4655
    Session-ID-ctx:
    Master-Key:  blurred
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 97 3c 0b 72 73 f5 75 bd-7d af 46 85 75 2b cd 44   .<.rs.u.}.F.u+.D
    0010 - d4 50 23 00 62 c2 83 dc-b3 b0 be 7c 60 98 39 18   .P#.b......|`.9.
    0020 - 0f a4 d7 9a aa 76 89 5b-9f 83 ee 46 bb 03 c3 86   .....v.[...F....
    0030 - a0 b1 02 d0 f9 13 a4 04-4f d7 5e 59 c5 b8 0d 97   ........O.^Y....
    0040 - 07 94 4a 7d 29 f9 84 dd-4b 74 56 23 4b 5f 3a 64   ..J})...KtV#K_:d
    0050 - 93 a3 6e 0a 8e ac 24 09-d5 6e 26 c2 63 de f1 06   ..n...$..n&.c...
    0060 - 5a e2 72 2a 6b 46 b1 f7-e1 6c d3 4d 9a 89 e1 da   Z.r*kF...l.M....
    0070 - dd 28 32 cb e7 c7 2a b4-b0 a6 12 3b ce 48 3a 25   .(2...*....;.H:%
    0080 - 49 3b 43 d2 33 cc 47 97-e9 ed e3 06 5b 5f 2a cc   I;C.3.G.....[_*.
    0090 - 0c c0 50 04 15 b6 4f 50-f6 4c 31 ed 6f 3d d9 30   ..P...OP.L1.o=.0
    00a0 - 7a 8f 70 ef 9d 29 e0 d8-00 b3 c8 37 cb 08 60 62   z.p..).....7..`b
    00b0 - 1c ad 21 be 91 4d e0 f3-83 1c c9 b7 4d c5 ee b2   ..!..M......M...

    Start Time: 1681628834
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shadowshift3r** [comment]
This issue wasn't resolved.
If this happends to anyone just dump your sql database and make a new misp instance and import the database again.
