### ISSUE TITLE
Support: Error: syntax error, unexpected '/'

### ISSUE THREAD

**Issue by dogoniyat** [MISP/MISP#9048]
### Support Questions

So, I have a very similar problem to many other, but I could not find any clear path to solve it; I modified a couple of files to try to trace the problem, like this:
```
public static function read($var = null) { echo "Configure::read(\"$var\");\n";
                if ($var === null) {
                        return static::$_values;
                } echo "return from config::read()\n";
                return Hash::get(static::$_values, $var);
        }
```

So, I get the following result:
```
[root@misp01 MISP]# php /var/www/MISP/app/webroot/index.php
Before Configure::bootstrap(isset($boot) ? $boot : true);
Configure::read("App");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("Cache.disable");
return from config::read()
Configure::read("debug");
return from config::read()
config=default, key=config
before read("config");
Configure::read("Config.language");
return from config::read()
Configure::read("Config.language");
return from config::read()
Configure::read("Config.language");
return from config::read()
Configure::read("Cache.disable");
return from config::read()
Error: syntax error, unexpected '/'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read()
#1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
#4 /var/www/MISP/app/webroot/index.php(88): include('/var/www/MISP/a...')
#5 {main}
Configure::read("Error.extraFatalErrorMemory");
return from config::read()
```

The password in /var/www/MISP/app/Config/database.php is correct, I can login into MariaDB without issue. Here's my database.php (I'll change the password later, they're not to difficult to generate):
```# cat app/Config/database.php
<?php
/**
 * This is core configuration file.
 *
 * Use it to configure core behaviour of Cake.
 *
 * PHP 5
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       app.Config
 * @since         CakePHP(tm) v 0.2.9
 * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
/**
 * In this file you set up your database connection details.
 *
 * @package       cake.config
 */
/**
 * Database configuration class.
 * You can specify multiple configurations for production, development and testing.
 *
 * datasource => The name of a supported datasource; valid options are as follows:
 *              Database/Mysql          - MySQL 4 & 5,
 *              Database/Sqlite         - SQLite (PHP5 only),
 *              Database/Postgres       - PostgreSQL 7 and higher,
 *              Database/Sqlserver      - Microsoft SQL Server 2005 and higher
 *
 * You can add custom database datasources (or override existing datasources) by adding the
 * appropriate file to app/Model/Datasource/Database.  Datasources should be named 'MyDatasource.php',
 *
 *
 * persistent => true / false
 * Determines whether or not the database should use a persistent connection
 *
 * host =>
 * the host you connect to the database. To add a socket or port number, use 'port' => #
 *
 * prefix =>
 * Uses the given prefix for all the tables in this database.  This setting can be overridden
 * on a per-table basis with the Model::$tablePrefix property.
 *
 * schema =>
 * For Postgres specifies which schema you would like to use the tables in. Postgres defaults to 'public'.
 *
 * encoding =>
 * For MySQL, Postgres specifies the character encoding to use when connecting to the
 * database. Uses database default not specified.
 *
 * unix_socket =>
 * For MySQL to connect via socket specify the `unix_socket` parameter instead of `host` and `port`
 */
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'misp',
                'password' => "7d32f2d530a3f19d145fa20709615d5a251a5ccf245f3fb97244a8c69012b9ae',
                'port' => 3306,
                'database' => 'misp',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}
```

And it definitely works:
```
[root@misp01 MISP]# mysql -u misp --password=7d32f2d530a3f19d145fa20709615d5a251a5ccf245f3fb97244a8c69012b9ae misp
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 9
Server version: 10.3.35-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [misp]>
```

I ran the git pull, git merge, git checkout, they all say the same thing: they're at the right version.

How can I trace what file is crashing to try to fix it?

### MISP version

{"major":2, "minor":4, "hotfix":170}

### Operating System

RedHat 8.7 (updated from 8.3)

### Operating System version

8.7

### PHP version

7.4.33

### Browser

Chrome

### Browser version

112.0.5615.121 (Official Build) (64-bit)

### Relevant log output

```shell
# php /var/www/MISP/app/webroot/index.php
Before Configure::bootstrap(isset($boot) ? $boot : true);
Configure::read("App");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("Cache.disable");
return from config::read()
Configure::read("debug");
return from config::read()
config=default, key=config
before read("config");
Configure::read("Config.language");
return from config::read()
Configure::read("Config.language");
return from config::read()
Configure::read("Config.language");
return from config::read()
Configure::read("Cache.disable");
return from config::read()
Error: syntax error, unexpected '/'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read()
#1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
#4 /var/www/MISP/app/webroot/index.php(88): include('/var/www/MISP/a...')
#5 {main}
Configure::read("Error.extraFatalErrorMemory");
return from config::read()
```

### Extra attachments

```
# cat app/Config/database.php
<?php
/**
 * This is core configuration file.
 *
 * Use it to configure core behaviour of Cake.
 *
 * PHP 5
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       app.Config
 * @since         CakePHP(tm) v 0.2.9
 * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
/**
 * In this file you set up your database connection details.
 *
 * @package       cake.config
 */
/**
 * Database configuration class.
 * You can specify multiple configurations for production, development and testing.
 *
 * datasource => The name of a supported datasource; valid options are as follows:
 *              Database/Mysql          - MySQL 4 & 5,
 *              Database/Sqlite         - SQLite (PHP5 only),
 *              Database/Postgres       - PostgreSQL 7 and higher,
 *              Database/Sqlserver      - Microsoft SQL Server 2005 and higher
 *
 * You can add custom database datasources (or override existing datasources) by adding the
 * appropriate file to app/Model/Datasource/Database.  Datasources should be named 'MyDatasource.php',
 *
 *
 * persistent => true / false
 * Determines whether or not the database should use a persistent connection
 *
 * host =>
 * the host you connect to the database. To add a socket or port number, use 'port' => #
 *
 * prefix =>
 * Uses the given prefix for all the tables in this database.  This setting can be overridden
 * on a per-table basis with the Model::$tablePrefix property.
 *
 * schema =>
 * For Postgres specifies which schema you would like to use the tables in. Postgres defaults to 'public'.
 *
 * encoding =>
 * For MySQL, Postgres specifies the character encoding to use when connecting to the
 * database. Uses database default not specified.
 *
 * unix_socket =>
 * For MySQL to connect via socket specify the `unix_socket` parameter instead of `host` and `port`
 */
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'misp',
                'password' => "7d32f2d530a3f19d145fa20709615d5a251a5ccf245f3fb97244a8c69012b9ae',
                'port' => 3306,
                'database' => 'misp',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dogoniyat** [comment]
found it, it was a missing comma at the end of a line in config.php that provoked the 500 with E_UNEXPECTED TOKEN because of the comment starting at next line.
Reading /var/www/MISP/app/tmp/logs/debug.log showed the actual error and checking thoroughly the modified files pinpointed it.
