### ISSUE TITLE
Support: What causes HTTP 405 ServerSyncTool->fetchSightingsForEvents

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9065]
### Support Questions

We are pulling via MISP Sync fine except at times the log output ends with the following stack trace of an HTTP 405 for `/sightings/restSearch/event`

Any help finding root cause is greatly appreciated.

Happens here in `/var/www/MISP/app/Lib/Tools/ServerSyncTool.php`
```
    /**
     * @param array $eventUuids
     * @return array
     * @throws HttpSocketHttpException
     * @throws HttpSocketJsonException
     * @throws JsonException
     */
    public function fetchSightingsForEvents(array $eventUuids)
    {
        return $this->post('/sightings/restSearch/event', [
            'returnFormat' => 'json',
            'last' => 0, // fetch all
            'includeUuid' => true,
            'uuid' => $eventUuids,
        ])->json()['response'];
    }
```

### MISP version

2.4.170

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.33

### Relevant log output

```shell
2023-03-27 03:00:22 Error: Failed downloading the sightings from REDACTED MISP.
[HttpSocketHttpException] Remote server returns HTTP error code 405 for URL https://misp.redacted/sightings/restSearch/event
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(244): ServerSyncTool->post()
#1 /var/www/MISP/app/Model/Sighting.php(1385): ServerSyncTool->fetchSightingsForEvents()
#2 /var/www/MISP/app/Model/Sighting.php(1363): Sighting->pullSightingNewWay()
#3 /var/www/MISP/app/Model/Server.php(673): Sighting->pullSightings()
#4 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Also, Wondering if that is aborting any remaining pull data from being retrieved as after that stack trace the final log output reporting a summary of pulls is output.

**Comment by teward** [comment]
**Disclaimer: I am affiliated with the partner that runs the MISP instance that @github-germ is connecting to.**

Currently, the Sightings visibility policy is currently configured on this instance to Event Owner Organization only.  None of the events to my knowledge that @github-germ are pulling have them as the owner organization, which explains the 405 error, specifically the HTTP response extracted from the same request via cURL saying: `{"name":"You do not have permission to use this functionality.","message":"You do not have permission to use this functionality.","url":"\/sightings\/restSearch\/event"}`

Additionally, there is no Sightings data in that MISP instance, as it is not implemented or used right now.

Could either of those conditions be why the 405 and error message observed are in fact happening?

(I'm actively building a fresh test instance to attempt to test this type of setup)

**Comment by teward** [comment]
After hours of testing, stabbing a test instance, and fiddling with permissions, I believe this is a **bug** in MISP.

The auth keys being used by @github-germ are Read Only auth keys.  When testing with Read Only auth keys vs. read/write auth keys, this endpoint fails to operate.  It has nothing to do with org user permisisons, etc. but with the auth key checkmark of read vs. read/write.

This sounds very much like a bug so I opened https://github.com/MISP/MISP/issues/9116

**Comment by github-germ** [comment]
@iglocska This is still an issue in 2.4.172. If you need us to provide any additional evidence from our side, please let us know. Thanks!

**Comment by teward** [comment]
I'm gonna suggest that this be closed as we have a fix pushed now via #9116 and the commit that fixed it.

**Comment by github-germ** [comment]
@iglocska #9116 was closed (not sure why). The issue here and there persists in 2.4.183. Do you need us to collect any more info in order to see about fixing this? Thanks...

**Comment by github-germ** [comment]
Issue persists in 2.4.191. Here's the latest stack trace:
```
2024-04-27 10:03:03 Error: Failed to download sightings from remote server *** MISP.
[HttpSocketHttpException] Remote server returns HTTP error code 405 for URL https://misp.ncfta.net/sightings/restSearch/event: {"name":"An ID or UUID must be provided if the context is set.","message":"An ID or UUID must be pro
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(319): ServerSyncTool->post()
#1 /var/www/MISP/app/Model/Sighting.php(1489): ServerSyncTool->fetchSightingsForEvents()
#2 /var/www/MISP/app/Model/Sighting.php(1460): Sighting->pullSightingNewWay()
#3 /var/www/MISP/app/Model/Server.php(700): Sighting->pullSightings()
#4 /var/www/MISP/app/Console/Command/ServerShell.php(152): Server->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}
```
