### ISSUE TITLE
Bug: When using Database for session management uploading files in Objects larger than 45KB will trigger a CSRF

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#9074]
### Expected behavior

The user should be able to upload files in objects with files included larger than 44KB, even when using the Database session without triggering an CSRF, as possible when uploading a file as an individual attribute.

### Actual behavior

When having the Session set to database it will cause a CSRF violation and trigger a MySQL exception

```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'data' at row 1 in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php:502
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Session/DatabaseSession.php(132): Model->save()
#6 [internal function]: DatabaseSession->write()
#7 [internal function]: session_write_close()
#8 {main}
  thrown in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php on line 502" while reading upstream, client: [REDACTED], server: [REDACTED], request: "POST /objects/revise_object/edit/247/421/996 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "[REDACTED]", referrer: "https://[REDACTED]/objects/edit/996"
```

### Steps to reproduce

1. Set "Session.defaults" : Database
2. Create an Object that supports file upload 
3. Upload a file larger than 45KB

This can be due to objects being created with files uses "application/x-www-form-urlencoded" and should potentially use "multipart/form-data" in the same way as when a file attribute is uploaded

### Version

v2.4.170 (4c142e5e70b335c0af7ad07145b88eb14bcfcc4d)

### Operating System

Debian

### Operating System version

9

### PHP version

7.4

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eCrimeLabs** [comment]
A temporary workaround could be - WARNING it is unclear what potential consequences this can have - So the risk is on you :)  
```
ALTER TABLE cake_sessions MODIFY column data LONGTEXT NOT NULL;  
```
