### ISSUE TITLE
Support: Exception: MissingConnectionException MySQL

### ISSUE THREAD

**Issue by 0x90perator** [MISP/MISP#9076]
### Support Questions

New to MISP. My install seems to be working fine, but when I try to publish an event, the job fails and indicates: "Exception: MissingConnectionException
Error: Database connection "Mysql" is missing, or could not be created"

### MISP version

2.4.170

### Operating System

AlmaLinux 

### Operating System version

8.7

### PHP version

7.2.24

### Browser

FireFox

### Relevant log output

```shell
Exception: MissingConnectionException
Error: Database connection "Mysql" is missing, or could not be created.
#0 /srv/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /srv/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /srv/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#3 /srv/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#4 /srv/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#5 /srv/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /srv/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#7 /srv/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#8 /srv/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#9 /srv/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#10 /srv/app/Model/AppModel.php(106): Model->__construct()
#11 /srv/app/Model/User.php(237): AppModel->__construct()
#12 [internal function]: User->__construct()
#13 /srv/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#14 /srv/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(279): ClassRegistry::init()
#15 /srv/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#16 /srv/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#17 /srv/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#18 /srv/app/Model/AppModel.php(106): Model->__construct()
#19 [internal function]: AppModel->__construct()
#20 /srv/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#21 /srv/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#22 /srv/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0x90perator** [comment]
Never mind. The number of allowed connections was exhausted on my DB instance.
