### ISSUE TITLE
Bug: Unable to communicate with another MISP if use client certificates

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#9084]
### Expected behavior

Successful communication with passed client certificate on all communication requests

### Actual behavior

Cause drop connection because client certificate is not passed when making `get` request

### Steps to reproduce

If MISP instance use Client certificates unable to connect from another MISP instace. Problem is causing client certificate not passed when query instance `$this->get('/servers/getVersion')`.
That cause exception and stopping communication. Logical path for finding this bug:

Entry point `https://misp.example/servers/testConnection/1` file `app/Controller/ServersController.php`

```php
    public function testConnection($id = false)
    {
        $server = $this->Server->find('first', ['conditions' => ['Server.id' => $id]]);
        if (!$server) {
            throw new NotFoundException(__('Invalid server'));
        }
        @session_write_close(); // close session to allow concurrent requests
        $result = $this->Server->runConnectionTest($server);
```

Line `$result = $this->Server->runConnectionTest($server);` return exception

Method `runConnectionTest` from file `app/Model/Server.php`

```php
 public function runConnectionTest(array $server, $withPostTest = true)
    {
        App::uses('SyncTool', 'Tools');
        try {
            $clientCertificate = SyncTool::getServerClientCertificateInfo($server);
            if ($clientCertificate) {
                $clientCertificate['valid_from'] = $clientCertificate['valid_from'] ? $clientCertificate['valid_from']->format('c') : __('Not defined');
                $clientCertificate['valid_to'] = $clientCertificate['valid_to'] ? $clientCertificate['valid_to']->format('c') : __('Not defined');
                $clientCertificate['public_key_size'] = $clientCertificate['public_key_size'] ?: __('Unknown');
                $clientCertificate['public_key_type'] = $clientCertificate['public_key_type'] ?: __('Unknown');
            }
        } catch (Exception $e) {
            $clientCertificate = ['error' => $e->getMessage()];
        }

        $serverSync = new ServerSyncTool($server, $this->setupSyncRequest($server));

        try {
            $info = $serverSync->info();
```

Line `$info = $serverSync->info();` returning exception

Method `info` from file `app/Lib/Tools/ServerSyncTool.php`

```php
    /**
     * @return array
     * @throws HttpSocketJsonException
     * @throws HttpSocketHttpException
     * @throws Exception
     */
    public function info()
    {
        if ($this->info) {
            return $this->info;
        }

        $response = $this->get('/servers/getVersion');
        $info = $response->json();
        if (!isset($info['version'])) {
            throw new Exception("Invalid response when fetching server version: `version` field missing.");
        }
        $this->info = $info;
        return $info;
    }
```

Line `$response = $this->get('/servers/getVersion');` returning exception

Method `get` from file `app/Lib/Tools/ServerSyncTool.php`

```php
    /**
     * @params string $url Relative URL
     * @return HttpSocketResponseExtended
     * @throws HttpSocketHttpException
     */
    private function get($url)
    {
        $url = $this->server['Server']['url'] . $url;
        $start = microtime(true);
        $response = $this->socket->get($url, [], $this->request);
        $this->log($start, 'GET', $url, $response);
        if (!$response->isOk()) {
            throw new HttpSocketHttpException($response, $url);
        }
        return $response;
    }
```

### Version

v2.4.171 (f02d52b1ab89fae820695cfe2bce0e615581fca5)

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Browser version

113.0.5672.126

### Relevant log output

```shell
2023-05-31 08:27:09 Error: Could not fetch remote user account.
[SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000086:SSL routines::certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://examplemisp.com:443 (Unknown error)
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(146): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): HttpSocketExtended->connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#3 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(185): HttpSocket->request()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#5 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(434): HttpSocket->get()
#6 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(319): ServerSyncTool->get()
#7 /var/www/MISP/app/Model/Server.php(4753): ServerSyncTool->userInfo()
#8 /var/www/MISP/app/Controller/ServersController.php(1726): Server->getRemoteUser()
#9 [internal function]: ServersController->getRemoteUser()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#14 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @Turecky 
There were some errors in how the certificate files were used if the extension when uploading them was not `pem`.
I pushed a fix to the `develop` branch: f125630c1c2d0f5d11079d3653ab7bb2ab5cd908

Please re-import the certificates and test again with this fix applied or wait it gets merged in the next release.

Hope this helps.

**Comment by Turecky** [comment]
Hello @righel 
Just now check for new updates. Have some issues.
1. If `certs` directory not exist in `/var/www/MISP/app/files/` adding new `.pem` files have no error notification and log files are emty too.
2. After adding directory and try to reupload `.pem` files in web interface have no changes `Server certificate file (*.pem): Not set.` but file is uploades to server. Same for `Client` pem file.

I upload both files but still have error:
```php
2023-08-01 12:57:12 Warning: Warning (2): fread(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A00045C:SSL routines::tlsv13 alert certificate required in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 429]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fread - [internal], line ??
CakeSocket::read() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 429
HttpSocket::request() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 381
HttpSocketExtended::request() - APP/Lib/Tools/HttpSocketExtended.php, line 185
HttpSocket::get() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 464
ServerSyncTool::get() - APP/Lib/Tools/ServerSyncTool.php, line 434
ServerSyncTool::getAvailableSyncFilteringRules() - APP/Lib/Tools/ServerSyncTool.php, line 289
Server::queryAvailableSyncFilteringRules() - APP/Model/Server.php, line 4873
ServersController::queryAvailableSyncFilteringRules() - APP/Controller/ServersController.php, line 2341
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99
```

**Comment by Turecky** [comment]
Addition info.
1. On saving `Server` info for remote server PEM files ar uploaded but not saved info in DB.
2. On server connection test will fail because client certificate is no passed with request.
In file `Lib/Tools/ServerSyncTool.php` function `private function get($url)` use `$this->request` as param and it contains:
```php
array(1) { 
["header"]=> array(4) { 
  ["Authorization"]=> string(40) "..." 
  ["Accept"]=> string(16) "application/json" 
  ["Content-Type"]=> string(16) "application/json" 
  ["User-Agent"]=> string(56) "MISP 2.4.176 - #..." }
}
```
Looks like client certificate data is missing
