### ISSUE TITLE
Bug: Postgresql schema not matching actual MySQL schema

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#9119]
### Expected behavior

Database schema must match 

### Actual behavior

In Postgresql missing tables:
```
access_logs
allowedlist
attachment_scans
audit_logs
auth_keys
cerebrates
correlation_exclusions
correlation_values
cryptographic_keys
dashboards
decaying_model_mappings
decaying_models
default_correlations
event_graph
event_reports
galaxy_cluster_blocklists
galaxy_cluster_relation_tags
galaxy_cluster_relations
inbox
no_acl_correlations
notification_logs
over_correlating_values
rest_client_histories
sharing_group_blueprints
sightingdb_orgs
sightingdbs
system_settings
tag_collection_tags
tag_collections
taxii_servers
user_settings
workflow_blueprints
workflows
```

Tables renamed:
`event_blacklists` -> `event_blocklists`
`org_blacklists` -> `org_blocklists`

Must be removed from Postgresql schema:
```
galaxy_reference
whitelist
```

### Steps to reproduce

Compare MySQL and Postgresql schema. Possible existing table structure not matching actual schema

### Version

v2.4.171 (73fe63bb0edf6879d9e9cd36c279531c7bba1ebf)

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustKiddingCode** [comment]
Could you try with https://github.com/KIT-CERT/MISP, installing the scheme with INSTALL/POSTGRESQL.sql ?

**Comment by Turecky** [comment]
> Could you try with https://github.com/KIT-CERT/MISP, installing the scheme with INSTALL/POSTGRESQL.sql ?

After using new schema looks more promising. Was able to change password but in user profile get error:
```shell
2023-06-02 12:49:00 Error: [PDOException] SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference "date_created" is ambiguous
LINE 1: ...."user_id" = "User"."id")  WHERE 1 = 1   ORDER BY "date_crea...
                                                             ^
Request URL: /users/view/1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/News.php(29): Model->find()
#7 /var/www/MISP/app/Controller/AppController.php(625): News->latestNewsTimestamp()
#8 /var/www/MISP/app/Controller/AppController.php(266): AppController->__verifyUser()
#9 /var/www/MISP/app/Controller/UsersController.php(29): AppController->beforeFilter()
#10 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#15 {main}
```

Other paths have same error.

**Comment by Turecky** [comment]
If change line 29 in `app/Models/News.php`
From: `'order' => 'date_created DESC',`
To: `'order' => 'News.date_created DESC',`

Then on first view have no errors

**Comment by Turecky** [comment]
Galaxies table was empty. Updating `Galaxies` get error:
```shell
2023-06-02 13:02:30 Error: [PDOException] SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 3048 exceeds btree version 4 maximum 2704 for index "idx_16602_value"
DETAIL:  Index row references tuple (783,20) in relation "galaxy_elements".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
Request URL: /galaxies/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(3344): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Galaxy.php(265): DboSource->insertMulti()
#2 /var/www/MISP/app/Controller/GalaxiesController.php(83): Galaxy->update()
#3 [internal function]: GalaxiesController->update()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main}
```

**Comment by JustKiddingCode** [comment]
> If change line 29 in `app/Models/News.php` From: `'order' => 'date_created DESC',` To: `'order' => 'News.date_created DESC',`

That's the reason I included it in my pull request. There are several other issues I handled.

> 
> Then on first view have no errors

Without the changes in AppModel I made, your database schema will remain old (somewhere ~ v60), because the schema updates are done in the AppModel.php.

**Comment by Turecky** [comment]
@JustKiddingCode in your DB schema still missing tables:
```
access_logs
audit_logs
cerebrates
correlation_exclusions
correlation_values
cryptographic_keys
default_correlations
galaxy_cluster_blocklists
galaxy_cluster_relation_tags
galaxy_cluster_relations
no_acl_correlations
over_correlating_values
sharing_group_blueprints
system_settings
taxii_servers
workflow_blueprints
workflows
```

**Comment by JustKiddingCode** [comment]
> @JustKiddingCode in your DB schema still missing tables:
> 
> ```
> access_logs
> audit_logs
> cerebrates
> correlation_exclusions
> correlation_values
> cryptographic_keys
> default_correlations
> galaxy_cluster_blocklists
> galaxy_cluster_relation_tags
> galaxy_cluster_relations
> no_acl_correlations
> over_correlating_values
> sharing_group_blueprints
> system_settings
> taxii_servers
> workflow_blueprints
> workflows
> ```

Please see my previous comment. The database schema is updated in the AppModel.php, e.g., the workflows table is created [here](https://github.com/KIT-CERT/MISP/blob/952b667db15241eb5afb82b24b9ff44de85641f6/app/Model/AppModel.php#LL2143C71-L2143C71)

**Comment by Turecky** [comment]
How to run DB update?
If run `/var/www/MISP/app/Console# ./cake Admin updateDatabase`
Get help display only

**Comment by JustKiddingCode** [comment]
Should be done by your update workers. Go to admin (misp website) section, there is a section for updates.

**Comment by Turecky** [comment]
`servers/updateProgress/` return error:
```shell
2023-06-02 13:35:09 Error: [PDOException] SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "information_schema.processlist" does not exist
LINE 1: SELECT * FROM INFORMATION_SCHEMA.PROCESSLIST;
                      ^
Request URL: /servers/updateProgress/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(641): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3489): DboSource->query()
#5 /var/www/MISP/app/Controller/ServersController.php(1961): Model->query()
#6 [internal function]: ServersController->updateProgress()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
```

**Comment by JustKiddingCode** [comment]
Either you're not using the state from KIT-CERT/MISP or this error message occurred before.
You need to use the version from https://github.com/KIT-CERT/MISP
This error is fixed there.

**Comment by Turecky** [comment]
@JustKiddingCode in your repo in file `/var/www/MISP/app/Model/AppModel.php on line 2368` missing `;` at end of line

**Comment by JustKiddingCode** [comment]
Thanks. Fixed.

**Comment by Turecky** [comment]
@JustKiddingCode  `Jobs` in server section all are `Filed` get errors:
```shell
Failed at: Fri Jun 02 14:21:13 EEST 2023
Exception: MissingConnectionException
Error: Database connection "Postgres" is missing, or could not be created.
(Click to hide stack trace)
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#5 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#9 /var/www/MISP/app/Model/AppModel.php(106): Model->__construct()
#10 /var/www/MISP/app/Model/User.php(237): AppModel->__construct()
#11 [internal function]: User->__construct()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#13 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(279): ClassRegistry::init()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#17 /var/www/MISP/app/Model/AppModel.php(106): Model->__construct()
#18 [internal function]: AppModel->__construct()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#23 /var/www/MISP/app/Console/Command/AppShell.php(42): Shell->initialize()
#24 /var/www/MISP/app/Console/Command/AppShell.php(47): AppShell->initialize()
#25 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#26 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#27 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#28 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#29 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#30 {main}
Close
```

**Comment by JustKiddingCode** [comment]
This looks like the database is missing? What does your `Config/database.php` look like?

**Comment by Turecky** [comment]
If database file was missing web interface was not working but web is working
```php
<?php
  class DATABASE_CONFIG {
          public $default = array(
                  //'datasource' => 'Database/Mysql',
                  'datasource' => 'Database/Postgres',
                  'persistent' => false,
                  'host' => 'localhost',
                  'login' => 'misp',
                  //'port' => 3306, // MySQL & MariaDB
                  'port' => 5432, // PostgreSQL
                  'password' => 'develop',
                  'database' => 'misp',
                  'prefix' => '',
                  'encoding' => 'utf8',
          );
  }
```

**Comment by JustKiddingCode** [comment]
if you make changes to your database configuration be sure to restart php-fpm and your workers

**Comment by Turecky** [comment]
I have not installed php-fpm. After installation get error for service:
```shell
Jun 02 14:44:31 mispint php-fpm7.4[21500]: [02-Jun-2023 14:44:31] NOTICE: PHP message: PHP Warning:  PHP Startup:
Unable to load dynamic library 'pdo_pgsql' (tried: /usr/lib/php/20190902/pdo_pgsql (/usr/lib/php/20190902/pdo_pgsql: cannot open shared object file: 
No such file or directory), /usr/lib/php/20190902/pdo_pgsql.so (/usr/lib/php/20190902/pdo_pgsql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0
```

**Comment by JustKiddingCode** [comment]
If you want to use postgres, you need to install php-pgsql

**Comment by Turecky** [comment]
php-pgsql is installed and enabled in `php.ini`
After `update worker` restart all updates take place. DB version 109

**Comment by Turecky** [comment]
Opening `diagnostics` get error:
```shell
2023-06-02 14:57:02 Notice: Notice (8): Undefined index: columnPerTable in [/var/www/MISP/app/View/Elements/healthElements/diagnostics.ctp, line 319]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/healthElements/diagnostics.ctp, line 319
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Servers/server_settings.ctp, line 11
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99
```

**Comment by Turecky** [comment]
In section `SQL database status` have no data and `Schema status` have red boxes
![Screenshot from 2023-06-02 14-59-43](https://github.com/MISP/MISP/assets/4244630/87f9859c-2902-4e1d-938c-3bfae4a2338b)

**Comment by JustKiddingCode** [comment]
This is done on purpose. DB Diagnostics is only available for MySQL.

**Comment by iglocska** [comment]
Also, psql is not officially supported, so your mileage may vary HEAVILY. I am surprised it works even.
