### ISSUE TITLE
Support: MISP Folder Relocation and Configuration Issue

### ISSUE THREAD

**Issue by Daisy001964** [MISP/MISP#9133]
### Support Questions

Hi, 

Due to certain reasons, I need to move the entire MISP folder from its default path, /var/www/MISP, to /opt/MISP/www/MISP.

Here are the steps I have taken:
1. cp -a /var/www/ /opt/MISP/www/
2. vim /etc/httpd/conf/httpd.conf, change /var/www/MISP to /opt/MISP/www/MISP
3. vim /etc/httpd/conf.d/misp.conf, change /var/www/MISP to /opt/MISP/www/MISP
4. systemctl restart httpd
5. systemctl restart php74-php-fpm.service
6. Rename /var/www/MISP to /var/www/MISP_t and test if everything is working fine.

After completing all the steps above, I was able to successfully operate MISP from the browser. 
However, when I tried to pull events from an external server by executing the following command in the terminal:
`/opt/MISP/www/MISP/app/Console/cake Server Pull 11 3 full`

I encountered the following error messages:
```
PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php): failed to open stream:                                                                                                                         No such file or directory in /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php on line 547
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ConsoleErrorHandler.php' for                                                                                                                         inclusion (include_path='/opt/MISP/www/MISP/app/Vendor/pear/console_commandline:/opt/MISP/www/MISP/app/Vendor/pear/cr                                                                                                                        ypt_gpg:/opt/MISP/www/MISP/app/Vendor/pear/pear_exception:/opt/MISP/www/MISP/app/Lib/cakephp/lib:.:/opt/remi/php74/ro                                                                                                                        ot/usr/share/pear:/opt/remi/php74/root/usr/share/php:/usr/share/pear:/usr/share/php') in /opt/MISP/www/MISP/app/Lib/c                                                                                                                        akephp/lib/Cake/Core/App.php on line 547
PHP Fatal error:  Uncaught Error: Class 'ConsoleErrorHandler' not found in /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cak                                                                                                                        e/Core/Configure.php:92
Stack trace:
#0 /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
#1 /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('/opt/MISP/www/M...')
#2 /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
#3 /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
#4 /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct()
#5 /opt/MISP/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#6 {main}
  thrown in /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php on line 92
PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php): failed to open stream: No such                                                                                                                         file or directory in /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php on line 547
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php' for inclusion                                                                                                                         (include_path='/opt/MISP/www/MISP/app/Vendor/pear/console_commandline:/opt/MISP/www/MISP/app/Vendor/pear/crypt_gpg:/                                                                                                                        opt/MISP/www/MISP/app/Vendor/pear/pear_exception:/opt/MISP/www/MISP/app/Lib/cakephp/lib:.:/opt/remi/php74/root/usr/sh                                                                                                                        are/pear:/opt/remi/php74/root/usr/share/php:/usr/share/pear:/usr/share/php') in /opt/MISP/www/MISP/app/Lib/cakephp/li                                                                                                                        b/Cake/Core/App.php on line 547
PHP Fatal error:  Uncaught Error: Class 'ErrorHandler' not found in /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Core/                                                                                                                        App.php:957
Stack trace:
#0 /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#1 [internal function]: App::shutdown()
#2 {main}
  thrown in /opt/MISP/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php on line 957
```

It appears that some of the code still references the default path /var/www/MISP. I couldn't locate where to make the necessary changes. Please let me know if there are any other configurations I need to edit in order to make it work.

### MISP version

2.4.166

### Operating System

Redhat

### Operating System version

8.6

### PHP version

7.4.33

### Browser

Chrome

### Browser version

114.0.5735.111

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Daisy001964** [comment]
Update my solution here if anyone faces the same situation.

Instead of editing those config files, simply add a soft link to the new path.

1. cp -a /var/www/ /opt/MISP/www/
2. rm -rf /var/www/MISP
3. ln -s /opt/MISP/www/MISP /var/www/MISP
