### ISSUE TITLE
Bug: "cake Admin jobGenerateCorrelation" not providing expected results

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#9206]
### Expected behavior

Run `sudo -H -u www-data /var/www/MISP/app/Console/cake Admin jobGenerateCorrelation 1` to update correlation cache.

### Actual behavior

Manually updating correlation cache (via web UI correlations/generateTopCorrelations) works and creates a job entry in the jobs list.

On one system: `sudo -H -u www-data /var/www/MISP/app/Console/cake Admin jobGenerateCorrelation 1` takes a while to complete, but no job is added to the job list, and the cache age isn't updated
On another system where previously all jobs were purged (via the web UI), the `sudo -H -u www-data /var/www/MISP/app/Console/cake Admin jobGenerateCorrelation 1` now triggers an error:

```
2023-07-24 11:23:06 Notice: Could not save progress for job 1
[PDOException] SQLSTATE[HY000]: General error: 1364 Field 'worker' doesn't have a default value
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave()
#5 /var/www/MISP/app/Model/Job.php(134): Model->save()
#6 /var/www/MISP/app/Model/Correlation.php(186): Job->saveProgress()
#7 /var/www/MISP/app/Model/Correlation.php(150): Correlation->__iteratedCorrelation()
#8 /var/www/MISP/app/Console/Command/AdminShell.php(134): Correlation->generateCorrelation()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->jobGenerateCorrelation()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#12 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#13 {main}
```

### Steps to reproduce

Run `sudo -H -u www-data /var/www/MISP/app/Console/cake Admin jobGenerateCorrelation 1`

### Version

2.4.173

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cudeso** [comment]
+ Default correlation engine is used
