### ISSUE TITLE
Bug: Unpublished Events

### ISSUE THREAD

**Issue by imidoriya** [MISP/MISP#9226]
### Expected behavior

This is paraphrased from a conversation with @iglocska and I on Gitter.  Events are sometimes not being published (simple background jobs) - logs included.

@iglocska ... So basically, The built in workers have a pid assigned by cakeresque
Simple background processing uses Supervisor which won't convey back the pid
Generally not an issue, but the job table, which is purely informational, expects it.
Now most default mariadb installations don't care as they're in a more slack default 
posture.  In your case it's blocking.  It's a bug either way, but ignored for most.
Thanks, should make the fix easy 😎

### Actual behavior

Events are not being published

### Steps to reproduce

Unknown

### Version

2.4.172

### Operating System

Ubuntu

### Operating System version

22.04.2

### PHP version

7.4

### Relevant log output

```shell
/var/www/MISP/app/tmp/logs/misp-workers-errors.log
2023-05-17 13:33:19 Error: [JOB ID: 06aa8dbb-3359-45f1-a8e4-b82140e1835e] - failed with error code 1. STDERR: Error: SQLSTATE[HY000]: General error: 1364 Field 'worker' doesn't have a default value
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Console/Command/EventShell.php(419): Model->save()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): EventShell->publish()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#9 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#10 {main}
. STDOUT: .
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hi @imidoriya 
Can you provide additional context on which action is triggering this error?

**Comment by imidoriya** [comment]
I don't know how to trigger it beyond my normal process of updating events via the api and republishing them.  For some reason, they just get stuck in the queue and don't publish.  @iglocska did some troubleshooting with me on gitter and planned a patch, but I haven't seen any movement on it so figured I'd post the issue here to keep track of it.

**Comment by righel** [comment]
I can see @iglocska did a patch on this issue already, have you tested it ? It was introduced in MISP v2.4.174.

Patch: https://github.com/MISP/MISP/commit/d14728abbb932e3f1ec608612ab1bf77b4053a79

**Comment by Kagee** [comment]
@imidoriya Have you been able to test if 2.4.174 or newer fixes this bug?
