### ISSUE TITLE
Bug: stop logging SendEmailException when MISP.disable_emailing true

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9251]
### Expected behavior

When `MISP.disable_emailing` is `true` nothing should be logged into `error.log`

### Actual behavior

`SendEMail->sendToUser` is logging with:
```

        if (Configure::read('MISP.disable_emailing')) {
            throw new SendEmailException('Emailing is currently disabled on this instance.');
        }
```

### Steps to reproduce

Delete an event attribute in the WebUI.

### Version

2.4.174

### Operating System

RH

### Operating System version

8.8

### PHP version

7.4.33

### Relevant log output

```shell
For one attribute delete click the following is logged multiple times:

==> error.log <==
2023-08-15 13:02:34 Error: Exception during sending e-mail
[SendEmailException] Emailing is currently disabled on this instance.
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(858): SendEmail->sendToUser()
#1 /var/www/MISP/app/Model/ShadowAttribute.php(571): User->sendEmail()
#2 /var/www/MISP/app/Controller/ShadowAttributesController.php(783): ShadowAttribute->sendProposalAlertEmail()
#3 [internal function]: ShadowAttributesController->delete()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
fixed via https://github.com/MISP/MISP/commit/225b74bf9377277433cb3a22580d01db0b449bd4
