### ISSUE TITLE
Support: Unable to login to MISP after upgrade

### ISSUE THREAD

**Issue by fwalbuloushi** [MISP/MISP#9280]
### Support Questions

Dears,

Currently, we are running MISP instance version 2.4.166 without any issues. After trying to upgrade to the latest version (2.4.175), we got the below error when we try to login:

> An Internal Error Has Occurred.
> Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Kindly find the below error logs:
```
2023-09-10 14:33:00 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'AuthKey.unique_ips' in 'field list'
Request URL: /servers/getVersion
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/AuthKey.php(186): Model->find()
#7 /var/www/MISP/app/Controller/AppController.php(1053): AuthKey->getAuthUserByAuthKey()
#8 /var/www/MISP/app/Controller/AppController.php(418): AppController->_checkAuthUser()
#9 /var/www/MISP/app/Controller/AppController.php(235): AppController->__loginByAuthKey()
#10 /var/www/MISP/app/Controller/ServersController.php(41): AppController->beforeFilter()
#11 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ServersController->beforeFilter()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#15 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
```

Your support would be highly appreciated.

### MISP version

2.4.166

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Relevant log output

```shell
2023-09-10 14:33:00 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'AuthKey.unique_ips' in 'field list'
Request URL: /servers/getVersion
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/AuthKey.php(186): Model->find()
#7 /var/www/MISP/app/Controller/AppController.php(1053): AuthKey->getAuthUserByAuthKey()
#8 /var/www/MISP/app/Controller/AppController.php(418): AppController->_checkAuthUser()
#9 /var/www/MISP/app/Controller/AppController.php(235): AppController->__loginByAuthKey()
#10 /var/www/MISP/app/Controller/ServersController.php(41): AppController->beforeFilter()
#11 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ServersController->beforeFilter()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#15 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Run this command:
`sudo -u www-data /var/www/MISP/app/Console/cake Admin runUpdates`

**Comment by fwalbuloushi** [comment]
Dear righel,

It has been solved successfully. Thank you.

Best,

**Comment by socmanager01** [comment]
I had the same issue. After running the provided command, the issue is fixed. Thanks,
