### ISSUE TITLE
Support: Server Settings & Maintenance Page Not Loading & Sudden Redis Failure

### ISSUE THREAD

**Issue by scrennelll** [MISP/MISP#9289]
### Support Questions

A few months ago we upgraded one of our instances from 2.4.161 to 2.4.172 and as it is not fully in use, assumed that as the application was accessible and we could reach the Server Settings & Maintenance page, this was OK. We have since received an email from a partner that states we have not polled their feed since that upgrade.

Checking the logs when after doing a poll via the crontab, this is being caused by redis not being found on the server as you can see from the following log:
2023-09-15 12:00:01 Error: Could not fetch event IDs from server `XXXXX`.
[Exception] Class Redis doesn't exists. Please install redis extension for PHP.
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(857): RedisTool::init()
#1 /var/www/MISP/app/Model/Server.php(964): Server->getEventIndexFromServer()
#2 /var/www/MISP/app/Model/Server.php(279): Server->getEventIdsFromServer()
#3 /var/www/MISP/app/Model/Server.php(630): Server->__getEventIdListBasedOnPullTechnique()
#4 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}

Nothing has changed in terms of installed packages on the server at the time of or since the update. There was a DB sync issue during the update which was fixed with a command on this github issues section. Since this update though, our redis setup, which has worked previously for a number of years, is suddenly not working. The packages installed are redis-server, redis-tools and php-redis, which again have previously been working. Has there been a change in version 2.4.172 that would cause this to stop working? 

Parallel to this, I also have an issue accessing the Server Setting and Maintenance page in order to diagnose any potential issues there. The only action taken since the above was the starting of workers via the script provided in the application release (./app/Console/worker/start.sh). The output to this was fine, with all actions saying done, but since then I have no access to the page. I have tried restarting apache, misp-modules & redis-server to make sure it was none of them causing the issue, all of which were mentioned in support questions here, but none of these have fixed the issue.

Error printed in the log is as follows:
2023-09-15 14:11:27 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update, scheduler]
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(368): BackgroundJobsTool->validateQueue()
#1 /var/www/MISP/app/Model/Server.php(3732): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Controller/ServersController.php(1213): Server->workerDiagnostics()
#3 [internal function]: ServersController->serverSettings()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main}

Any advice on how to fix this so we can check the settings page if we migrate to a different server for this instance or try and update of the application to see if that helps?

### MISP version

2.4.172

### Operating System

Ubuntu

### Operating System version

18.04.6 LTS

### PHP version

7.4.27

### Browser

Edge, Firefox

### Relevant log output

```shell
2023-09-15 12:00:01 Error: Could not fetch event IDs from server `XXXXX`.
[Exception] Class Redis doesn't exists. Please install redis extension for PHP.
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(857): RedisTool::init()
#1 /var/www/MISP/app/Model/Server.php(964): Server->getEventIndexFromServer()
#2 /var/www/MISP/app/Model/Server.php(279): Server->getEventIdsFromServer()
#3 /var/www/MISP/app/Model/Server.php(630): Server->__getEventIdListBasedOnPullTechnique()
#4 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}

2023-09-15 14:11:27 Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update, scheduler]
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(368): BackgroundJobsTool->validateQueue()
#1 /var/www/MISP/app/Model/Server.php(3732): BackgroundJobsTool->getQueueSize()
#2 /var/www/MISP/app/Controller/ServersController.php(1213): Server->workerDiagnostics()
#3 [internal function]: ServersController->serverSettings()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#8 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scrennelll** [comment]
Regarding both issues, this is not "fixed" by rolling back to php7.2, which was replaced over a year ago on our setup.

I tried to search for getting php7.4-redis installed on the server as that was the version of php we were using, but all steps involving the ondrej PPA are now out of date as that version on Ubuntu 18 is EOL. I did find a different third party PPA which is on stackexchange via the following [link](https://stackoverflow.com/questions/76782345/cant-install-php7-4-dev-on-ubuntu-18-04), but installing the redis module on here and a restart of apache2 did not get this working and it was not showing in the loaded php modules.

Rolling back to php7.2, which had the redis module installed, a restart of apache2 and this is now working despite a warning in the Server and Diagnosis. 

I will close this off as it is a PHP redis issue not being present on the server and will aim to  upgrade OS.
