### ISSUE TITLE
Support: STIX 2 import having issues 

### ISSUE THREAD

**Issue by twjsharns** [MISP/MISP#9297]
### Support Questions

Hi MISP Team, 

I encountered an error "An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator." after importing any STIX 2 file. 

Appreciate the help on this.

Thanks

### MISP version

2.4.176

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.4.29

### Browser

Chrome

### Browser version

116.0.5845.188

### Relevant log output

```shell
2023-09-21 13:45:25 Error: [ProcessException] Command 'python3 /var/www/MISP/app/files/scripts/stix2/stix2misp.py -i /var/www/MISP/app/tmp/MISPwNcdp8 --distribution 1 --galaxies_as_tags --debug' finished with error code 1.
STDERR: Logged to tmp/logs/exec-errors.log
STDOUT: ''
Request URL: /events/upload_stix/2
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(5909): ProcessTool::execute()
#1 /var/www/MISP/app/Controller/EventsController.php(2466): Event->upload_stix()
#2 [internal function]: EventsController->upload_stix()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#6 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#7 {main}
```

### Extra attachments

[MAR-10454006.r5.v1.CLEAR_stix2.log](https://github.com/MISP/MISP/files/12685407/MAR-10454006.r5.v1.CLEAR_stix2.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
Hey, I recently pushed a few updates to [misp-stix](https://github.com/misp/misp-stix) which have been tested with different files from CISA, including the one you mention here.
As such, there should not be issues ingesting this content in MISP.

My first guess why you have an issue - even with .176 - is maybe your submodules are not up-to-date
Can you check whether you updated your submodules, and especially the following?
```bash
cd /var/www/MISP

# updating all the submodules
sudo -Hu www-data git submodule update --init

# alternatively focusing on the 2 important ones here
sudo -Hu www-data git submodule update --init PyMISP
sudo -Hu www-data git submodule update --init app/files/scripts/misp-stix
```
If you face any issue to update, let me know

If there is no change, or if you still have issues after making sure everything is up-to-date, it would be easier for me to understand where the issue comes from with more detailed information in the related log file - as mentioned in the log message you pasted: `/var/www/MISP/app/tmp/logs/exec-error.log`

Hope it helps.

**Comment by twjsharns** [comment]
Thank you @chrisr3d. I tried it and the error still persists. After checking, I think this is an update issue as well. When I try python3 it gives me 
```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 31, in <module>
    from misp_stix_converter import (
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/__init__.py", line 5, in <module>
    from .misp2stix import MISPtoSTIX1AttributesParser, MISPtoSTIX1EventsParser # noqa
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/misp2stix/__init__.py", line 3, in <module>
    from .misp_to_stix20 import MISPtoSTIX20Parser # noqa
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/misp2stix/misp_to_stix20.py", line 4, in <module>
    from .misp_to_stix2 import InvalidHashValueError, MISPtoSTIX2Parser
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/misp2stix/misp_to_stix2.py", line 14, in <module>
    from pymisp import MISPAttribute, MISPEvent, MISPGalaxy, MISPGalaxyCluster, MISPObject
ImportError: cannot import name 'MISPGalaxy'
```

After trying with python 3.8 it gives me another error (not the same module) 
```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 31, in <module>
    from misp_stix_converter import (
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/__init__.py", line 5, in <module>
    from .misp2stix import MISPtoSTIX1AttributesParser, MISPtoSTIX1EventsParser # noqa
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/misp2stix/__init__.py", line 1, in <module>
    from .framing import stix1_attributes_framing, stix1_framing, stix20_framing, stix21_framing # noqa
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/misp2stix/framing.py", line 7, in <module>
    from mixbox import idgen
  File "/var/www/MISP/app/files/scripts/mixbox/mixbox/idgen.py", line 9, in <module>
    from .namespaces import Namespace
  File "/var/www/MISP/app/files/scripts/mixbox/mixbox/namespaces.py", line 12, in <module>
    from ordered_set import OrderedSet
ModuleNotFoundError: No module named 'ordered_set' 
```
