### ISSUE TITLE
Support: TOTP Problem

### ISSUE THREAD

**Issue by Mercenarier** [MISP/MISP#9331]
### Support Questions

Hi,
I have a problem with TOTP on MISP. After activation on a user (admin rights), it does not show active TOTP in My Profile and in the user list. Additionally, the "delete TOTP" option is not visible in the user preview. When logging in, a message appears asking you to enter a code.

### MISP version

v2.4.177 (7bd64bc23f5e780709d8a60dd37d2cefb1e7d671)

### Operating System

Ubuntu

### Operating System version

20.04.6 LTS

### PHP version

PHP 7.4.33 (cli) (built: Sep  2 2023 08:03:15) ( NTS)

### Browser

Chrome, Firefox, IE

### Extra attachments

![image](https://github.com/MISP/MISP/assets/147797840/27cf653d-3d25-4ef3-bbf1-eb2538252cc1)
![image](https://github.com/MISP/MISP/assets/147797840/3cf1cf85-8e45-4064-92c0-eae40195176b)
![image](https://github.com/MISP/MISP/assets/147797840/0d28d2a3-4a65-43eb-a297-494f179aba44)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrisChyles** [comment]
Hello, 

we have the same issue, moreover when I try generate again TOTP then process return:
Your account already has a TOTP. Please contact your organisational administrator to change or delete it.

![image](https://github.com/MISP/MISP/assets/147838705/ad52cf09-0fd1-40c2-8aaa-b5143be41223)

**Comment by Wachizungu** [comment]
Hello,

that's really strange.

You can perhaps try to delete totp (if you need to) for the user with the rest client (modifying params as appropriate):
![image](https://github.com/MISP/MISP/assets/9868873/25d03745-a5d9-41dc-a781-c13b812c69d5)

Would be nice to find reproduction scenario though... Could you add a note here if it's consistent behavior / this happens every time for all your users? Does clearing browser cache make any difference?

**Comment by Mercenarier** [comment]
The problem occurs for all users, even newly added ones. It was tested on various browsers, along with cleaning cookies.

**Comment by CrisChyles** [comment]
In debug.log I found some errors, but I compared and the same errors are in MISP instances where TOTP showing statuses fine, please take a look:
2023-10-13 13:08:24 Notice: Notice (8): Undefined index: disabled in [/var/www/MISP/app/Controller/UsersController.php, line 1218]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
UsersController::login() - APP/Controller/UsersController.php, line 1218
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2023-10-13 13:10:14 Notice: Error during GPG signing.
[Crypt_GPG_BadPassphraseException] Cannot sign data. No passphrase provided.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/Engine.php(1741): Crypt_GPG_ProcessHandler->throwException()
#1 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/Engine.php(777): Crypt_GPG_Engine->_closeSubprocess()
#2 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG.php(1663): Crypt_GPG_Engine->run()
#3 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG.php(955): Crypt_GPG->_sign()
#4 /var/www/MISP/app/Model/Server.php(3538): Crypt_GPG->sign()
#5 /var/www/MISP/app/Controller/ServersController.php(1183): Server->gpgDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
2023-10-13 13:12:14 Notice: Notice (8): Undefined index: last_pw_change in [/var/www/MISP/app/View/Users/view.ctp, line 162]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Users/view.ctp, line 162
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
UsersController::admin_view() - APP/Controller/UsersController.php, line 631
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

**Comment by Wachizungu** [comment]
Yeah those logs look unrelated to me.
Could you confirm that you don't have local changes to files / things were updated properly?

cd /var/www/MISP
sudo -u www-data git status

These files are the ones of interest:
/var/www/MISP/app/Controller/UsersController.php
/var/www/MISP/app/View/Users/view.ctp


There is/was a bug with totp delete button not being on 'my profile' page for admins, which will be fixed in the next release.
The issue you both have looks different though. I'm pretty puzzled because on the one hand it looks like you have totp set (that's why you get the "Your account already has totp" message), while on the other hand the view is messed up. They are using pretty much the same check to see whether you have totp set up however, so no idea what is causing this. Unfortunately I can't reproduce it even on the same commit / version.

**Comment by hramosmo** [comment]
Same issue with v2.4.192 just upgraded from v2.4.157 with PHP  7.4.29
