### ISSUE TITLE
Support: Update to the latest version is failing

### ISSUE THREAD

**Issue by siddharthsi** [MISP/MISP#9350]
### Support Questions

While trying to update the MISP to latest version we are getting the following error: 

cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

cd $(git rev-parse --show-toplevel) && git pull origin '2.4' 2>&1

From https://github.com/MISP/MISP
 * branch                2.4        -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	app/files/scripts/stixtest.py
Please commit your changes or stash them before you merge.
Aborting
Updating a61caa3a6..78c1d56eb

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

tried to do  git pull however thats not fixing the issue. 

### MISP version

v2.4.144

### Operating System

Ubuntu 18.04.6 LTS

### Operating System version

18.04.6 LTS

### PHP version

PHP 7.2.24

### Browser

Chrome

### Relevant log output

```shell
cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1



cd $(git rev-parse --show-toplevel) && git pull origin '2.4' 2>&1

From https://github.com/MISP/MISP
 * branch                2.4        -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	app/files/scripts/stixtest.py
Please commit your changes or stash them before you merge.
Aborting
Updating a61caa3a6..78c1d56eb

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FafnerKeyZee** [comment]
Hello,

Looks like you did some modification to : `app/files/scripts/stixtest.py`
In command line, can you do a `git stash` in MISP folder ? (with the correct account , so should be www-data.
Depending how you installed MISP you may do: `sudo -u www-data git stash`

Best regards,

**Comment by siddharthsi** [comment]
@FafnerKeyZee Thank you so much for the update. I have tried that however after the update I ma unable to login to the WebUI 
![image](https://github.com/MISP/MISP/assets/24691088/4760518e-7bbf-4835-b29f-e2069deda7f9)

When I checked the Error logs I see the following 
2023-10-30 11:03:36 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'AuthKey.unique_ips' in 'field list'
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `AuthKey...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `AuthKey...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `AuthKey...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(AuthKey), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/AppModel.php(4008): Model->find('all', Array)
#7 /var/www/MISP/app/Model/AuthKey.php(186): AppModel->find('all', Array)
#8 /var/www/MISP/app/Controller/AppController.php(1073): AuthKey->getAuthUserByAuthKey('hueQkITa1hDHpy7...')
#9 /var/www/MISP/app/Controller/AppController.php(418): AppController->_checkAuthUser('hueQkITa1hDHpy7...')
#10 /var/www/MISP/app/Controller/AppController.php(235): AppController->__loginByAuthKey()
#11 /var/www/MISP/app/Controller/EventsController.php(68): AppController->beforeFilter()
#12 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): EventsController->beforeFilter(Object(CakeEvent))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch(Object(CakeEvent))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
2023-10-30 11:08:01 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.totp' in 'field list'
Request URL: /users/login?_=1698660407030
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(User), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Model/AppModel.php(4008): Model->find('first', Array)
#7 /var/www/MISP/app/Controller/UsersController.php(1204): AppModel->find('first', Array)
#8 [internal function]: UsersController->login()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by FafnerKeyZee** [comment]
Looks like the DB didn't update. What returns the command:
`sudo -u www-data /var/www/MISP/app/Console/cake Admin runUpdates`

**Comment by siddharthsi** [comment]
Once I ran the command I got the following: 
root@misp:/var/www/MISP# sudo -Hu www-data /var/www/MISP/app/Console/cake Admin runUpdates
Executing all updates to bring the database up to date with the current version.
Executing 71..................Done
Executing 72..................Done
Executing 73..................Done
Executing 74..................Done
Executing 75..................Done
Executing 76..................Done
Executing 77..................Done
Executing 78..................Done
Executing 79..................Done
Executing 80..................Done
Executing 81..................Done
Executing 82..................Done
Executing 83..................Done
Executing 84..................Done
Executing 85..................Done
Executing 86..................Done
Executing 87..................Done
Executing 88..................Done
Executing 89..................Done
Executing 90..................Done
Executing 91..................Done
Executing 92..................Done
Executing 93..................Done
Executing 94..................Done
Executing 95..................Done
Executing 96..................Error: Table default_correlations for model Correlation was not found in datasource default.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('default_correla...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2845): Model->getDataSource()
#2 /var/www/MISP/app/Model/Behavior/DefaultCorrelationBehavior.php(182): Model->deleteAll(Array, false)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(238): DefaultCorrelationBehavior->runBeforeSaveCorrelation(Object(Correlation), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollection->dispatchMethod(Object(Correlation), Array, Array)
#5 /var/www/MISP/app/Model/Correlation.php(382): Model->__call('runBeforeSaveCo...', Array)
#6 /var/www/MISP/app/Model/Attribute.php(550): Correlation->beforeSaveCorrelation(Array)
#7 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute->beforeDelete(true)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2694): BetterCakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Model/AppModel.php(2922): Model->delete('1358246')
#10 /var/www/MISP/app/Model/AppModel.php(2846): AppModel->removeDuplicateAttributeUUIDs()
#11 /var/www/MISP/app/Model/AppModel.php(271): AppModel->removeDuplicatedUUIDs()
#12 /var/www/MISP/app/Model/AppModel.php(2538): AppModel->updateMISP(96)
#13 /var/www/MISP/app/Console/Command/AdminShell.php(544): AppModel->runUpdates(true, false, false)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->runUpdates()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('runUpdates', Array)
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#17 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run(Array)
#18 {main}

**Comment by siddharthsi** [comment]
If I re-run it it shows
root@misp:/var/www/MISP# sudo -Hu www-data /var/www/MISP/app/Console/cake Admin runUpdates
Executing all updates to bring the database up to date with the current version.
All updates completed.

**Comment by FafnerKeyZee** [comment]
Can you run:
` sudo -u www-data /var/www/MISP/app/Console/cake Admin cleanCache`
then
` sudo -u www-data /var/www/MISP/app/Console/cake Admin runUpdates`
again and tell if you still can't login ?

**Comment by siddharthsi** [comment]
@FafnerKeyZee Thank you so much, After running the command that you gave, I could login to the Web UI.

**Comment by siddharthsi** [comment]
@FafnerKeyZee We had to restore a snap shot and after snapshot restore we are unable to login in to the MISP. 
We got the same internal error while logging in 
![image](https://github.com/MISP/MISP/assets/24691088/be3f44b4-ccae-4ac7-880e-e8cfef681037)

we see the following error in the error logs : 
2023-11-14 13:02:34 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'AuthKey.unique_ips' in 'field list'
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `AuthKey...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `AuthKey...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `AuthKey...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(AuthKey), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/AppModel.php(4008): Model->find('all', Array)
#7 /var/www/MISP/app/Model/AuthKey.php(186): AppModel->find('all', Array)
#8 /var/www/MISP/app/Controller/AppController.php(1073): AuthKey->getAuthUserByAuthKey('hueQkITa1hDHpy7...')
#9 /var/www/MISP/app/Controller/AppController.php(418): AppController->_checkAuthUser('hueQkITa1hDHpy7...')
#10 /var/www/MISP/app/Controller/AppController.php(235): AppController->__loginByAuthKey()
#11 /var/www/MISP/app/Controller/EventsController.php(68): AppController->beforeFilter()
#12 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): EventsController->beforeFilter(Object(CakeEvent))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch(Object(CakeEvent))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}

Same as before. we tried to run clean caches however still the same result. 
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin cleanCaches
Cleaning caches...
...caches lost in time, like tears in rain.


Please help.

**Comment by siddharthsi** [comment]
We see the following as well: 
sudo -Hu www-data git stash
No local changes to save



sudo -Hu www-data git status
On branch 2.4
Your branch is up to date with 'origin/2.4'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   PyMISP (untracked content)
        modified:   app/files/misp-workflow-blueprints (modified content)
        modified:   app/files/scripts/mixbox (new commits, modified content)
        modified:   app/files/scripts/python-maec (new commits, modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        INSTALL/dependencies/
        Plugin/
        app/Lib/random_compat/
        app/files/scripts/PyMISP/
        cti-python-stix2/
        misp-vagrant/

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by FafnerKeyZee** [comment]
Hey;

Did you try to clean the cache with the command:
`   sudo -u www-data /var/www/MISP/app/Console/cake Admin cleanCache`

**Comment by siddharthsi** [comment]
@FafnerKeyZee Thanks, it worked after running the command multiple time and after a reboot.
