### ISSUE TITLE
Support: Error code 500 in attribute ExpandedPyMisp.search

### ISSUE THREAD

**Issue by parosio** [MISP/MISP#9371]
### Support Questions

Hello, 
I'm receiving the following error using `ExpandedPyMISP` `search` function:

```
2023-11-14 16:13:03,063: INFO: misp2tie: Query params: {"controller": "attributes", "type_attribute": {"OR": ["md5", "sha1", "sha256"]}, "tags": {"NOT": ["misp2tie", "DELETE"]}, "date_from": "2023-11-07", "limit": 5000, "page": null}
2023-11-14 16:13:07,915: CRITICAL: pymisp: Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.126 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '390', 'Authorization': 'xxxxxxxxxxxxxxxxxx', 'content-type': 'application/json'}
Request body:
{"returnFormat": "json", "limit": 5000, "type": {"OR": ["md5", "sha1", "sha256"]}, "tags": {"NOT": ["misp2tie", "DELETE"]}, "from": "2023-11-07", "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/attributes\/restSearch"}
```

In `/var/www/MISP/app/tmp/logs/error.log` I found:

```
2023-11-14 16:13:07 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 285]
2023-11-14 16:13:07 Error: [InternalErrorException] Internal Server Error
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 285)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 285, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

This search has worked withouth problems for months, but recently it fails with the above error. 
The expected result size is in the order of a few thousands attributes, but the search fails also for as few as 1200.

Any suggestion on what can I check/change?

### MISP version

2.4.124

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.2.24

### Browser

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafiot** [comment]
Have you tried to pass `limit = 100` and iterate over the pages in a loop?

**Comment by parosio** [comment]
Hello @Rafiot 
> Have you tried to pass `limit = 100` and iterate over the pages in a loop?

The search was initially not limited, and could return a few thousands attributes without problems. 
After the first errors, I set the limit to 5000. 
I'll try to further reduce the limit and paginate the results.

Thank you for the suggestion

**Comment by parosio** [comment]
Got an error on the second page:

```
2023-11-14 18:11:03,984: INFO: testSearch: Query elements: type {'OR': ['md5', 'sha1', 'sha256']}, tag: {'OR': ['misp2tie']}, from_date: 2023-11-07 00:00:00, limit: 100, pagination: True
2023-11-14 18:11:03,985: INFO: testSearch: Istantiating misp interface
2023-11-14 18:11:04,034: INFO: testSearch: Starting search
2023-11-14 18:11:04,034: INFO: testSearch: paginate search: limit 100, page 1
2023-11-14 18:11:33,371: INFO: testSearch: Search done
2023-11-14 18:11:33,371: INFO: testSearch: Got 100 hashes
2023-11-14 18:11:33,371: INFO: testSearch: Showing first 10 ...
    0: type:    md5, event_id: 62402, value: dc3b2591d62c05c7461fc8f718aa8099
    1: type:   sha1, event_id: 62402, value: 9ac80543f390013dc9d1b346a4bd57a290b88a1b
    2: type: sha256, event_id: 62402, value: ce35af16fd4b4ae4b58aa4dccb1622e1578250c468d9991f0ccbc07811841c63
    3: type:    md5, event_id: 62402, value: b007c104ce07fef732e874fc42498a2b
    4: type:   sha1, event_id: 62402, value: f6149579bdd3dc958b4156448652f53281392819
    5: type: sha256, event_id: 62402, value: 6b00b942bd3d94924e6dd6dc4de310bba12029e96a324e3286cba65aaf5436bf
    6: type:    md5, event_id: 62402, value: db88c5269be03c930e48d5fe8555f8f8
    7: type:   sha1, event_id: 62402, value: 0f9aa78b0674c23a6a7cc00de1a221a3108b33aa
    8: type: sha256, event_id: 62402, value: 5a7fd4f4d561459a609ecda44469d6134c01ed6bbed5f304c217e10b2640ab90
    9: type:    md5, event_id: 62402, value: 0483b51ace0b27c9db9371d184a9efde
2023-11-14 18:11:33,371: INFO: testSearch: paginate search: limit 100, page 2
CRITICAL [api.py:2280 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.126 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '398', 'Authorization': 'xxxxxxxxxx', 'content-type': 'application/json'}
Request body:
{"returnFormat": "json", "page": 2, "limit": 100, "type": {"OR": ["md5", "sha1", "sha256"]}, "tags": {"OR": ["misp2tie"]}, "from": "2023-11-07 00:00:00", "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/attributes\/restSearch"}
2023-11-14 18:11:39,555: CRITICAL: pymisp: Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.126 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '398', 'Authorization': 'xxxxxxxxxx', 'content-type': 'application/json'}
Request body:
{"returnFormat": "json", "page": 2, "limit": 100, "type": {"OR": ["md5", "sha1", "sha256"]}, "tags": {"OR": ["misp2tie"]}, "from": "2023-11-07 00:00:00", "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/attributes\/restSearch"}
```

Server error `/var/www/MISP/app/tmp/logs/error.log`:
```
2023-11-14 18:11:39 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 285]
2023-11-14 18:11:39 Error: [InternalErrorException] Internal Server Error
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 285)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 285, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by Rafiot** [comment]
I see you're using an extremely old version of PyMISP, try to upgrade it. And if you're using a similarly old version of MISP, same, please upgrade.
