### ISSUE TITLE
Bug: MISP v2.4.178 Diagnostics page not loading

### ISSUE THREAD

**Issue by mdhirt** [MISP/MISP#9411]
### Actual behavior

Diagnostics page showing an Internal Server Error

### Expected behavior

Diagnostics page is fully loaded and displayed

### Steps to reproduce

Fresh installation of MISP v2.4.178.
Login and navigate to Administration, Server settings and Maintenance, and attempt to load Diagnostics tab.
The following is displayed
MISP version

Every version of MISP includes a JSON file with the current version.

.....

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Version

2.4.178

### Operating System

RedHat

### Operating System version

9.3

### PHP version

7.4.25

### Browser

Firefox

### Browser version

119.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdhirt** [comment]
The fix is implemented in https://github.com/MISP/MISP/pull/9413

**Comment by wbatista09** [comment]
I'm having the same issue.

Updated to latest version v2.4.181


Log `app/tmp/logs/error.log`:
```
2023-12-08 16:46:47 Error: [TypeError] Return value of Module_assign_country_from_enrichment::_fetchCountryGalaxyClusters() must be of the type array, null returned
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Model/WorkflowModules/action/Module_assign_country_from_enrichment.php(73): Module_assign_country_from_enrichment->_fetchCountryGalaxyClusters()
#1 [internal function]: Module_assign_country_from_enrichment->__construct()
#2 /var/www/MISP/app/Model/Workflow.php(1092): ReflectionClass->newInstance()
#3 /var/www/MISP/app/Model/Workflow.php(1010): Workflow->__getClassFromModuleFile('/var/www/MISP/a...')
#4 /var/www/MISP/app/Model/Workflow.php(872): Workflow->__getClassFromModuleFiles('action', Array, false)
#5 /var/www/MISP/app/Model/Workflow.php(1110): Workflow->loadAllWorkflowModules()
#6 /var/www/MISP/app/Model/Server.php(1474): Workflow->getModulesByType('trigger')
#7 /var/www/MISP/app/Model/Server.php(1423): Server->readModuleSettings(Array, Array)
#8 /var/www/MISP/app/Model/Server.php(1555): Server->getCurrentServerSettings()
#9 /var/www/MISP/app/Controller/ServersController.php(1055): Server->serverSettingsRead()
#10 [internal function]: ServersController->serverSettings('diagnostics')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
```

**Comment by alepadua** [comment]
Hello, I am facing the same issue. 

Version 2.4.183
