### ISSUE TITLE
Bug: CustomAuth breaks login after upgrade to v2.4.180 

### ISSUE THREAD

**Issue by simonbjorzen-ts** [MISP/MISP#9425]
### Actual behavior

Hi, we are using header based CustomAuth for access to MISP, upgrading to v2.4.180 broke MISP entirely.

CustomAuth config:
```
    'CustomAuth_enable' => true,
    'CustomAuth_header' => 'HEADERNAME',
    'CustomAuth_use_header_namespace' => true,
    'CustomAuth_header_namespace' => 'HTTP_',
    'CustomAuth_name' => 'AuthName',
    'CustomAuth_only_allow_source' => 'X.X.X.X',
    'CustomAuth_custom_password_reset' => '',
    'CustomAuth_custom_logout' => '',
    'CustomAuth_required' => false,
```

### Expected behavior

Succesful login, has been working fine before upgrade.

### Steps to reproduce

Sign in using CustomAuth with the provided configuration.

### Version

2.4.180

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

All

### Relevant log output

```shell
Error message in MISP/app/tmp/logs/error.log:
> 2023-11-30 22:06:13 Error: Fatal Error (1): Uncaught Error: Call to a member function _getUserProfile() on null in /var/www/MISP/app/Controller/AppController.php:1152
Stack trace:
#0 /var/www/MISP/app/Controller/AppController.php(206): AppController->__customAuthentication()
#1 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): AppController->beforeFilter()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct()
#6 [internal function]: ErrorHandler::handleException()
#7 {main}
  thrown in [/var/www/MISP/app/Controller/AppController.php, line 1152]
2023-11-30 22:06:13 Error: [InternalErrorException] Internal Server Error
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Could you got pull and try it again? Does it persists?

**Comment by cvandeplas** [comment]
This was indeed a bug, there was a missing `$this->UserLoginProfile = ClassRegistry::init('UserLoginProfile');`.
I have just pushed a fix. 
Can you try again after a pull?

**Comment by simonbjorzen-ts** [comment]
Resolved!
Many thanks for the quick fix :)

**Comment by cvandeplas** [comment]
excellent, thanks for the update!
