### ISSUE TITLE
Bug: ServerSettings page not Loading - Internal Error 

### ISSUE THREAD

**Issue by alepadua** [MISP/MISP#9535]
### Actual behavior

When we try to access the page /server/serverSettings we receive An Internal Error has occurred.

The followin issue is the same as mine. 
https://github.com/MISP/MISP/issues/9411#issuecomment-1847520323

### Expected behavior

Page is loaded normally

### Steps to reproduce

The issue happened when we made the Upgrade from 2.4.166 to 2.4.183

### Version

2.4.183

### Operating System

Redhat 

### Operating System version

8

### PHP version

7.2

### Browser

Edge

### Browser version

121.0.2277.83

### Relevant log output

```shell
**debug.log** 

Request URL: /servers/serverSettings
Stack Trace:
#0 /www/MISP/app/Model/WorkflowModules/action/Module_assign_country_from_enrichment.php(73): Module_assign_country_from_enrichment->_fetchCountryGalaxyClusters()
#1 [internal function]: Module_assign_country_from_enrichment->__construct()
#2 /www/MISP/app/Model/Workflow.php(1092): ReflectionClass->newInstance()
#3 /www/MISP/app/Model/Workflow.php(1010): Workflow->__getClassFromModuleFile('/www/MISP/app/M...')
#4 /www/MISP/app/Model/Workflow.php(872): Workflow->__getClassFromModuleFiles('action', Array, false)
#5 /www/MISP/app/Model/Workflow.php(1110): Workflow->loadAllWorkflowModules()
#6 /www/MISP/app/Model/Server.php(1474): Workflow->getModulesByType('trigger')
#7 /www/MISP/app/Model/Server.php(1423): Server->readModuleSettings(Array, Array)
#8 /www/MISP/app/Model/Server.php(1555): Server->getCurrentServerSettings()
#9 /www/MISP/app/Controller/ServersController.php(1055): Server->serverSettingsRead()
#10 [internal function]: ServersController->serverSettings()
#11 /www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#12 /www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#14 /www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}

**error.log**

024-01-30 14:26:01 Notice: Notice (8): Undefined index: GalaxyCluster in [/www/MISP/app/Model/WorkflowModules/action/Module_assign_country_from_enrichment.php, line 136]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Module_assign_country_from_enrichment::_fetchCountryGalaxyClusters() - APP/Model/WorkflowModules/action/Module_assign_country_from_enrichment.php, line 136
Module_assign_country_from_enrichment::__construct() - APP/Model/WorkflowModules/action/Module_assign_country_from_enrichment.php, line 73
ReflectionClass::newInstance() - [internal], line ??
Workflow::__getClassFromModuleFile() - APP/Model/Workflow.php, line 1092
Workflow::__getClassFromModuleFiles() - APP/Model/Workflow.php, line 1010
Workflow::loadAllWorkflowModules() - APP/Model/Workflow.php, line 872
Workflow::getModulesByType() - APP/Model/Workflow.php, line 1110
Server::readModuleSettings() - APP/Model/Server.php, line 1474
Server::getCurrentServerSettings() - APP/Model/Server.php, line 1423
Server::serverSettingsRead() - APP/Model/Server.php, line 1555
ServersController::serverSettings() - APP/Controller/ServersController.php, line 1055
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101
```

### Extra attachments

![misp_error](https://github.com/MISP/MISP/assets/22760077/e208bdae-605b-425e-ab43-18cf2ad84cf8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alepadua** [comment]
My Galaxies were empty.,.. After I clicked in Update Galaxy as described in this link the issue was solved
https://github.com/MISP/MISP/issues/9415
