### ISSUE TITLE
Bug: Pull job fails becausedata to long for change' column 

### ISSUE THREAD

**Issue by Kagee** [MISP/MISP#9542]
### Actual behavior

when pulling from an extermal server, the pull failes with the error `ERROR: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'change' at row 1` (see below for full stack trace)

### Expected behavior

Pull to succced, data to be saved successfully, truncated or dropped.

### Steps to reproduce

Make å pull that creates a LARGE change field?

### Version

2.4.183-misp-docker

### Operating System

Debian

### Operating System version

12

### PHP version

7.4?

### Relevant log output

```shell
Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'change' at row 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave()
#5 /var/www/MISP/app/Model/AuditLog.php(335): Model->save()
#6 /var/www/MISP/app/Model/Behavior/AuditLogBehavior.php(217): AuditLog->insert()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): AuditLogBehavior->afterSave()
#8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEventManager->dispatch()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#11 /var/www/MISP/app/Model/EventReport.php(552): Model->save()
#12 /var/www/MISP/app/Model/EventReport.php(115): EventReport->saveAndReturnErrors()
#13 /var/www/MISP/app/Model/Event.php(3863): EventReport->captureReport()
#14 /var/www/MISP/app/Model/Server.php(493): Event->_add()
#15 /var/www/MISP/app/Model/Server.php(571): Server->__checkIfPulledEventExistsAndAddOrUpdate()
#16 /var/www/MISP/app/Model/Server.php(654): Server->__pullEvent()
#17 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#21 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#22 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
It looks like this tried to fix it, but somehow it did not work? https://github.com/MISP/MISP/commit/5bed4634164d0e338c51982154962fc3577c0b8a

**Comment by Kagee** [comment]
The previous apparently did not fix it for the auditlog model.

**Comment by JakubOnderka** [comment]
I will fix it.
