### ISSUE TITLE
Bug: Race condition when pulling same event from multiple servers.

### ISSUE THREAD

**Issue by Kagee** [MISP/MISP#9558]
### Actual behavior

In a case where the same event is shared between multiple servers you pull from, 
or you have multiple pulls from the same server,
and you pull from them in parallel, it is possible to trigger a race condition 
and thus a SQL error / Integrity constraint violation.

I believe a similar race condition can trigger a SQL error / Integrity 
constraint violation for tag names - when the same tag name is pulled by
multiple parallel pull jobs.

Possible related issues:
https://github.com/MISP/MISP/issues/8928
https://github.com/MISP/MISP/issues/8920
https://github.com/MISP/MISP/issues/8557 (tags)
https://github.com/MISP/MISP/issues/8365

### Steps to reproduce

Pull the same event (same uuid) from two separate servers.

### Version

2.54.184+90126dc

### Operating System

Debian

### Operating System version

12 (docker)

### PHP version

7.4

### Relevant log output

```shell
Timeline: 
2024-02-09 01:04:49 Event 1f4bc76c-53cc-4840-9b28-5b4a8a4ab844 published on server B
2024-02-09 06:01:58 Event 1f4bc76c-53cc-4840-9b28-5b4a8a4ab844 published on server A
2024-02-09 10:18:35 Job 50b8b5bd-77db-400a-9b5f-d85631417894 created for pull from A  
2024-02-09 10:18:36 Job c30fbede-e397-4a2d-bca9-cba9663bf760 created for pull from B
2024-02-09 10:20:04 GET to server A for event 1f4bc76c-53cc-4840-9b28-5b4a8a4ab844 (log order #1)
2024-02-09 10:20:04 GET to server B for event 1f4bc76c-53cc-4840-9b28-5b4a8a4ab844 (log order #2)
2024-02-09 10:20:05 Event 1f4bc76c-53cc-4840-9b28-5b4a8a4ab844 published on local server (from server A)
2024-02-09 10:20:05 Job for server B: Error: [JOB ID: c30fbede-e397-4a2d-bca9-cba9663bf760] - failed with error code 1 after 88.562 seconds.

Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1f4bc76c-53cc-4840-9b28-5b4a8a4ab844' for key 'uuid'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Event.php(3791): Model->save()
#6 /var/www/MISP/app/Model/Server.php(507): Event->_add()
#7 /var/www/MISP/app/Model/Server.php(583): Server->__checkIfPulledEventExistsAndAddOrUpdate()
#8 /var/www/MISP/app/Model/Server.php(666): Server->__pullEvent()
#9 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#13 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#14 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
A transaction-locked check for event followed by a insert should be able to fix this?

**Comment by iglocska** [comment]
As discussed, we'll modify the behaviour to not barf on duplicates, but to silently drop it.

**Comment by Kagee** [comment]
Can it be applied to both UUIDs and tag names?

**Comment by iglocska** [comment]
Good point! Will keep it in mind.
