### ISSUE TITLE
Bug: SQL error in ssdeep correlation

### ISSUE THREAD

**Issue by Kagee** [MISP/MISP#9569]
### Actual behavior

SQL error when pulling from remote server, apparently during ssdeep correlation

### Expected behavior

No SQL error.

### Steps to reproduce

Best i can do is log output below.

### Version

2.4.184-docker

### Operating System

Debian

### Operating System version

12

### PHP version

7.4

### Relevant log output

```shell
Background Job Error Browser
...
misp.server.hostname[4010]: add -- Attribute from Event #580257: Payload delivery/ssdeep 3:Tsln:ol
Notice Error: Undefined index: in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 901]

Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 901]

2024-02-16 13:15:52 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 901]
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(914): PDOStatement->execute()
#1 /var/www/MISP/app/Model/FuzzyCorrelateSsdeep.php(80): Mysql->insertMulti()
#2 /var/www/MISP/app/Model/Correlation.php(575): FuzzyCorrelateSsdeep->query_ssdeep_chunks()
#3 /var/www/MISP/app/Model/Correlation.php(248): Correlation->ssdeepCorrelation()
#4 /var/www/MISP/app/Model/Correlation.php(429): Correlation->__buildAdvancedCorrelationConditions()
#5 /var/www/MISP/app/Model/Attribute.php(479): Correlation->afterSaveCorrelation()
#6 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute->afterSave()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEventManager->dispatch()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#9 /var/www/MISP/app/Model/Attribute.php(563): Model->save()
#10 /var/www/MISP/app/Model/Attribute.php(2619): Attribute->save()
#11 /var/www/MISP/app/Model/MispObject.php(1131): Attribute->captureAttribute()
#12 /var/www/MISP/app/Model/Event.php(3845): MispObject->captureObject()
#13 /var/www/MISP/app/Model/Server.php(507): Event->_add()
#14 /var/www/MISP/app/Model/Server.php(583): Server->__checkIfPulledEventExistsAndAddOrUpdate()
#15 /var/www/MISP/app/Model/Server.php(666): Server->__pullEvent()
#16 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#20 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#21 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
This *may* be triggered by MISP Event 2c51bc8f-029e-4e02-b31b-5dbdec3930ee
