### ISSUE TITLE
Bug: Failed to pull sightings from the remote server

### ISSUE THREAD

**Issue by slevenbw** [MISP/MISP#9603]
### Actual behavior

While trying to use /var/www/MISP/app/Console/cake Server pull and pullAll (update only) I received the following error:

root@xxxxx:~# /var/www/MISP/app/Console/cake Server pull 2 1 update
2024-03-04 07:32:12 Error: Failed to download sightings from XXXXXXXXXXXXX.
[HttpSocketHttpException] Remote server returns HTTP error code 405 for URL https://xxxxxxxxxxxxx/sightings/restSearch/event: {"name":"An ID or UUID must be provided if the context is set
.","message":"An ID or UUID must be pro
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(310): ServerSyncTool->post()
#1 /var/www/MISP/app/Model/Sighting.php(1416): ServerSyncTool->fetchSightingsForEvents()
#2 /var/www/MISP/app/Model/Sighting.php(1394): Sighting->pullSightingNewWay()
#3 /var/www/MISP/app/Model/Server.php(685): Sighting->pullSightings()
#4 /var/www/MISP/app/Console/Command/ServerShell.php(149): Server->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}
Error: Call to a member function json() on array
#0 /var/www/MISP/app/Model/Server.php(687): AnalystData->pull()
#1 /var/www/MISP/app/Console/Command/ServerShell.php(149): Server->pull()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#5 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#6 {main}

Events were synced without any sightings.

I checked a couple of the previously synced events (Pull All from Sync actions) and found 0 sightings for all of them.

Local version: 2.4.186
Remote version: 2.4.182
User ID and Server ID are correct

### Expected behavior

Sightings should be pulled from the remote server

### Steps to reproduce

In our case:
/var/www/MISP/app/Console/cake Server pull 2 1 update
/var/www/MISP/app/Console/cake Server pullAll 2 update

### Version

2.4.186

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crym** [comment]
Likely related to #9116 and #9065
