### ISSUE TITLE
Bug: Error trying to fetch events from source or feeds GPG couldn't be initialized

### ISSUE THREAD

**Issue by romarito90** [MISP/MISP#9610]
### Actual behavior

the GPG couldn't be initialized and I can't get events from feeds or trying to download events from source 

When I see the error in debug.log this is because the GPG couldn't be initialized, GPG encryption and signing will be not available.

### Expected behavior

1. try to fetch data or download feeds from one source (for example CIRCL)
2. job finish with success getting events from source 

### Steps to reproduce

1. try to fetch data or download feeds from one source (for example CIRCL)
2. see if job failed in trying to downlod events 
3. see the error in debug.log 

### Version

2.4.183

### Operating System

Redhat

### Operating System version

8.6

### PHP version

7.4

### Browser

Firefox

### Relevant log output

```shell
2024-03-05 16:46:16 Notice: GPG couldn't be initialized, GPG encryption and signing will be not available.
[Crypt_GPG_FileException] The 'homedir' "" is not readable or does not exist and cannot be created. This can happen if 'homedir' is not specified in the Crypt_GPG options, Crypt_GPG is run as the web user, and the web user has no home directory.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPGAbstract.php(256): Crypt_GPG_Engine->__construct()
#1 /var/www/MISP/app/Lib/Tools/CryptGpgExtended.php(11): Crypt_GPGAbstract->__construct()
#2 /var/www/MISP/app/Lib/Tools/GpgTool.php(34): CryptGpgExtended->__construct()
#3 /var/www/MISP/app/Model/User.php(1526): GpgTool::initializeGpg()
#4 /var/www/MISP/app/Model/User.php(869): User->initializeGpg()
#5 /var/www/MISP/app/Model/Event.php(3227): User->sendEmail()
#6 /var/www/MISP/app/Console/Command/EventShell.php(289): Event->sendAlertEmail()
#7 /var/www/MISP/app/Console/Command/AppShell.php(48): EventShell->alertemail()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#13 {main}
2024-03-05 16:46:16 Notice: GPG couldn't be initialized, GPG encryption and signing will be not available.
[Crypt_GPG_FileException] The 'homedir' "" is not readable or does not exist and cannot be created. This can happen if 'homedir' is not specified in the Crypt_GPG options, Crypt_GPG is run as the web user, and the web user has no home directory.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPGAbstract.php(256): Crypt_GPG_Engine->__construct()
#1 /var/www/MISP/app/Lib/Tools/CryptGpgExtended.php(11): Crypt_GPGAbstract->__construct()
#2 /var/www/MISP/app/Lib/Tools/GpgTool.php(34): CryptGpgExtended->__construct()
#3 /var/www/MISP/app/Model/User.php(1526): GpgTool::initializeGpg()
#4 /var/www/MISP/app/Model/User.php(869): User->initializeGpg()
#5 /var/www/MISP/app/Model/Event.php(3227): User->sendEmail()
#6 /var/www/MISP/app/Console/Command/EventShell.php(289): Event->sendAlertEmail()
#7 /var/www/MISP/app/Console/Command/AppShell.php(48): EventShell->alertemail()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
```

### Extra attachments

![imagen](https://github.com/MISP/MISP/assets/114606380/c156bd7c-2d1c-42fb-9727-c91b696ea5f7)
![imagen](https://github.com/MISP/MISP/assets/114606380/e5aaeab8-5446-4acc-b5d6-0c2a8a15bfcb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
This faliure and the logs lines does not appear related, the log lines are from >10 minutes before the job started and stopped. Please look in error.log or the log file with the most recent timestamp when this happens.

**Comment by romarito90** [comment]
here is the failed screenshots and logs 

![imagen](https://github.com/MISP/MISP/assets/114606380/29144298-ce21-4ab0-a732-4ee387eace08)

![imagen](https://github.com/MISP/MISP/assets/114606380/a8d56ea3-4f30-4a01-8018-7cd4568982ee)

![imagen](https://github.com/MISP/MISP/assets/114606380/98f47f76-2915-4e2f-ae74-e1a8b964db68)

![imagen](https://github.com/MISP/MISP/assets/114606380/fe92c15a-19f1-46f1-a768-34fe4b14f8f2)

in the error.log 

![imagen](https://github.com/MISP/MISP/assets/114606380/061d7207-188e-4d7b-b139-97344dcdef34)
