### ISSUE TITLE
Support:  Hello dear, I need some help

### ISSUE THREAD

**Issue by Phalvesx** [MISP/MISP#9612]
### Support Questions

After an update, MISP stops working... follow the error log.

### MISP version

2.41

### Operating System

ubuntu

### Operating System version

1804

### PHP version

7.0

### Relevant log output

```shell
2024-03-08 01:09:19 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(16, 'Exception throw...', 'Unknown', 0)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(16, 'Exception throw...', 'Unknown', 0, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2024-03-08 01:09:49 Error: [ParseError] syntax error, unexpected ')'
Request URL: /events/restSearch
Stack Trace:
#0 [internal function]: App::load('AppController')
#1 /var/www/MISP/app/Controller/EventsController.php(9): spl_autoload_call('AppController')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(547): include('/var/www/MISP/a...')
#3 [internal function]: App::load('EventsControlle...')
#4 [internal function]: spl_autoload_call('EventsControlle...')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(266): class_exists('EventsControlle...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(235): Dispatcher->_loadController(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(158): Dispatcher->_getController(Object(CakeRequest), Object(CakeResponse))
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2024-03-08 01:09:49 Error: Fatal Error (16): Exception thrown without a stack frame in [Unknown, line 0]
2024-03-08 01:09:49 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(16, 'Exception throw...', 'Unknown', 0)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(16, 'Exception throw...', 'Unknown', 0, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2024-03-08 01:10:20 Error: [ParseError] syntax error, unexpected ')'
Request URL: /events/restSearch
Stack Trace:
#0 [internal function]: App::load('AppController')
#1 /var/www/MISP/app/Controller/EventsController.php(9): spl_autoload_call('AppController')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(547): include('/var/www/MISP/a...')
#3 [internal function]: App::load('EventsControlle...')
#4 [internal function]: spl_autoload_call('EventsControlle...')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(266): class_exists('EventsControlle...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(235): Dispatcher->_loadController(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(158): Dispatcher->_getController(Object(CakeRequest), Object(CakeResponse))
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2024-03-08 01:10:20 Error: Fatal Error (16): Exception thrown without a stack frame in [Unknown, line 0]
2024-03-08 01:10:20 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(16, 'Exception throw...', 'Unknown', 0)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(16, 'Exception throw...', 'Unknown', 0, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2024-03-08 01:10:37 Error: [MissingControllerException] Controller class ActuatorController could not be found.
Exception Attributes: array (
  'class' => 'ActuatorController',
  'plugin' => NULL,
)
Request URL: /actuator/gateway/routes
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2024-03-08 01:10:37 Error: Fatal Error (16): Exception thrown without a stack frame in [Unknown, line 0]
2024-03-08 01:10:37 Error: [InternalErrorException] Internal Server Error
Request URL: /actuator/gateway/routes
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(16, 'Exception throw...', 'Unknown', 0)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(16, 'Exception throw...', 'Unknown', 0, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
To my knowledge, there is no MISP version 2.41, exactly what version of MISP have you updated to?

MISP does not currently support PHP 7.0, it recommends PHP 7.4 - if you only have 7.0 you need to upgrade your system.
