### ISSUE TITLE
Bug: CIRCL OSINT Feed 'Timeout was reached'

### ISSUE THREAD

**Issue by limbernie** [MISP/MISP#9638]
### Actual behavior

Job failed. See error log for more details.

### Expected behavior

Job done.

### Steps to reproduce

Fetch the feed

### Version

2.4.185

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Firefox

### Browser version

124.0.1

### Relevant log output

```shell
2024-03-24 14:53:09 Error: Could not get new event uuids for feed 1.
[Exception] Fetching the 'https://www.circl.lu/doc/misp/feed-osint/manifest.json' failed with exception: curl error 28 'Timeout was reached': Failed to connect to www.circl.lu port 443 after 15209 ms: Connection timed out
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(276): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(172): Feed->getRemoteManifest()
#2 /var/www/MISP/app/Model/Feed.php(1185): Feed->getNewEventUuids()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(404): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Console/Command/AppShell.php(48): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#10 {main}
[SocketException] curl error 28 'Timeout was reached': Failed to connect to www.circl.lu port 443 after 15209 ms: Connection timed out
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(81): CurlClient->internalRequest()
#1 /var/www/MISP/app/Model/Feed.php(2093): CurlClient->get()
#2 /var/www/MISP/app/Model/Feed.php(2053): Feed->getFollowRedirect()
#3 /var/www/MISP/app/Model/Feed.php(276): Feed->feedGetUriRemote()
#4 /var/www/MISP/app/Model/Feed.php(172): Feed->getRemoteManifest()
#5 /var/www/MISP/app/Model/Feed.php(1185): Feed->getNewEventUuids()
#6 /var/www/MISP/app/Console/Command/ServerShell.php(404): Feed->downloadFromFeedInitiator()
#7 /var/www/MISP/app/Console/Command/AppShell.php(48): ServerShell->fetchFeed()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#13 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
It should be fixed.
