### ISSUE TITLE
Bug: Internal Server Error on Search Attribute Page

### ISSUE THREAD

**Issue by eneamarcantoni99** [MISP/MISP#9655]
### Actual behavior

When I use Attributes Search i get an Internal Server Error.

### Expected behavior

I expect that the search return results.

### Steps to reproduce

Go to https://<misp-host>/attributes/search/results and run a search with "8.8.8.8" in the text box "Containing the following expressions"

### Version

2.4.188

### Operating System

CentOS Stream

### Operating System version

8

### PHP version

7.4.33

### Relevant log output

```shell
2024-04-02 14:10:17 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(value1, value2)) LEFT JOIN `misp`.`events` AS `Event` ON (`Attribute`.`event...' at line 1
Request URL: /attributes/search/results
Stack Trace:
#0 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Datasource/Database/MysqlExtended.php(163): DboSource->_execute()
#2 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): MysqlExtended->execute()
#3 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/AppModel.php(4205): Model->find()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): AppModel->find()
#8 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate()
#9 /var/www/MISP/app/Controller/AttributesController.php(1583): Controller->paginate()
#10 [internal function]: AttributesController->search()
#11 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#15 {main}
```

### Extra attachments

I've attached the screenshot of the Attribute Search Page.
![misp_attribute_search_bug](https://github.com/MISP/MISP/assets/94439174/20104964-0328-4cd3-af4b-1c5813289784)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Hello, this is already fixed in `develop` branch, so next MISP will fix this.
