### ISSUE TITLE
Bug: "Search Attributes" from UI errors out after v2.4.188

### ISSUE THREAD

**Issue by mdavis332** [MISP/MISP#9663]
### Actual behavior

Search errors out when searching for attributes in UI. However, API search continues to work. This is happening across 3 different instances in 3 different environments all on v2.4.188.

### Expected behavior

Search completes successfully.

### Steps to reproduce

1. Go to `/attributes/search` (click on "Search Attributes" in navbar)
2. Put in anything (like google.com or 8.8.8.8) in the "Containing the following expressions field"
3. Click "Search" button
4. `/attributes/search/results` page loads and says **An Internal Error has Occurred.**

### Version

2.4.188

### Operating System

CentOS

### Operating System version

Stream 9

### PHP version

7.4

### Browser

Edge, Chrome, Firefox

### Relevant log output

```shell
mariadb v11.2:

misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(value1, value2)) LEFT JOIN `misp`.`events` AS `Event` ON (`Attribute`.`event...' at line 1
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: Request URL: /attributes/search/results
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: Stack Trace:
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #0 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #1 /var/www/MISP/app/Model/Datasource/Database/MysqlExtended.php(163): DboSource->_execute()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #2 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): MysqlExtended->execute()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #3 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #4 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #5 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #6 /var/www/MISP/app/Model/AppModel.php(4205): Model->find()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): AppModel->find()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #8 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #9 /var/www/MISP/app/Controller/AttributesController.php(1583): Controller->paginate()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #10 [internal function]: AttributesController->search()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #11 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #12 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #13 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #14 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
misp  | Apr  4 15:58:30 b0d0fc03fae8 MISP: error: #15 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
See https://github.com/MISP/MISP/issues/9655

**Comment by mdavis332** [comment]
I see that MISP v2.4.189 was tagged but not seeing an equivalent version tag yet for PyMISP. Will a 2.4.189 pymisp be forthcoming so that PyMISP doesn't complain that MISP doesn't like the PyMISP version talking to it?

**Comment by mdavis332** [comment]
Confirmed after upgrade to v2.4.189 that this was fixed for me.
