### ISSUE TITLE
Bug: Oidc logins not completing in v2.4.189

### ISSUE THREAD

**Issue by mdavis332** [MISP/MISP#9674]
### Actual behavior

Error after redirecting back to MISP upon successful OIDC auth to IdP.

The error is:

```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.
```

Note: in a browser I already had a MISP session in prior to upgrade, I stay logged in. Only when I open an Incognito browser and complete a fresh auth do I get the above error.

### Expected behavior

Oidc auth flow successfully completes like it did prior to v2.4.189.

### Steps to reproduce

1. Configure Oidc auth
2. Attempt to login

### Version

2.4.189

### Operating System

CentOS

### Operating System version

Stream 8

### PHP version

7.4

### Relevant log output

```shell
app/tmp/logs/error.log:
------

2024-04-11 15:14:56 Error: [Exception] OIDC user 00p5nlfax5rLx8OeA2h9 doesn't have email address, that is required by MISP.
Request URL: /users/login?code=<guid>&state=<stateKey>
Stack Trace:
#0 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(34): Oidc->authenticate()
#1 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#2 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#3 /var/www/MISP/app/Controller/UsersController.php(1237): AuthComponent->login()
#4 [internal function]: UsersController->login()
#5 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#9 {main}

/var/log/httpd/error_log (debug logging enabled):
-------
[Thu Apr 11 15:14:56.750176 2024] [auth_openidc:debug] [pid 3264:tid 140037981193984] src/util.c(2259): [client localip:15596] oidc_util_json_merge: result dst={"sub":"00p5nlfax5rLx8OeA2h9","email":"my.email@domain.tld","email_verified":true,"clientId":"00p5nlfax5rLx8OeA2h9","misp_roles":["MISP_Access"],"req_type":"individual","ver":1,"iss":"https://oidcprovider.tld/oauth2/default","aud":"00p5nlfax5rLx8OeA2h9","iat":1712848494,"exp":1712852094,"jti":"ID.mgody8_<guid>","amr":["swk","mfa","pwd"],"idp":"<idp_id>","nonce":"<nonceKey>","auth_time":1712848493,"at_hash":"<hash>"}, referer: https://misp.domain.tld/users/login?code=<guid>&state=<stateKey>
```

### Extra attachments

Only thing changed was upgrade from v2.4.188 to v2.4.189 and this started happening.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdavis332** [comment]
Ugh, figured this out. I have to shim the following extra lines into `/var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php` when I build my MISP container to get Okta (my IdP) to work w/ the OIDC plugin:

```
if ($authenticationMethod !== false && $authenticationMethod !== null) {
      $oidc->setAuthenticationMethod($authenticationMethod);
 ++++ $oidc->addScope('email');
 ++++ $oidc->addScope('misp_roles');
}
```

Looks like there were some recent changes to  `/var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php` so I need to figure out a less brittle way to get my changes in.

**Comment by Kagee** [comment]
The least brittle way would be to get you changes upstreamed via a PR ;)
