### ISSUE TITLE
Bug: Error After Login Post update to 2.4.190

### ISSUE THREAD

**Issue by ahmedxuae91** [MISP/MISP#9692]
### Actual behavior

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Expected behavior

View Events

### Steps to reproduce

N/A

### Version

2.4.190

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
2024-04-19 20:38:21 Error: [InvalidArgumentException] Only SVG and PNG images are supported
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/View/Elements/global_menu.ctp(6): ImageHelper->base64()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(1224): View->_render()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(418): View->_renderElement()
#5 /var/www/MISP/app/View/Layouts/default.ctp(48): View->element()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(546): View->_render()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(481): View->renderLayout()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(968): View->render()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#14 {main}
2024-04-19 20:38:21 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /css/bootstrap-datepicker.css.map
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#1 {main}
2024-04-19 20:38:21 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /css/bootstrap-datepicker.css.map
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#1 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahmedxuae91** [comment]
Issue fixed. One of the files was .PNG and needed to change to .png with lowercase

**Comment by JakubOnderka** [comment]
Thanks for report, fixed in develop branch.
