### ISSUE TITLE
Bug: Cannot access applications via GUI for page 2,3,4 etc due to Column not found: 1054 Unknown column 'Log.page' in 'where clause'

### ISSUE THREAD

**Issue by www-jedi** [MISP/MISP#9705]
### Actual behavior

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Expected behavior

Should expect to view application logs within the GUI. 

### Steps to reproduce

Logs - Applications - Page 2 or Page 3

### Version

2.4.188

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Log.page' in 'where clause'
Request URL: /logs/index/page:2
Stack Trace:
#0 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /datadisk/MISP/var/www/MISP/app/Model/AppModel.php(4205): Model->find()
#7 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): AppModel->find()
#8 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate()
#9 /datadisk/MISP/var/www/MISP/app/Controller/LogsController.php(127): Controller->paginate()
#10 [internal function]: LogsController->index()
#11 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /datadisk/MISP/var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#15 {main}

---------------------------------------------------------------------------------
Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Log.page' in 'where clause'
Request URL: /logs/index/page:3
Stack Trace:
#0 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /datadisk/MISP/var/www/MISP/app/Model/AppModel.php(4205): Model->find()
#7 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): AppModel->find()
#8 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1107): PaginatorComponent->paginate()
#9 /datadisk/MISP/var/www/MISP/app/Controller/LogsController.php(127): Controller->paginate()
#10 [internal function]: LogsController->index()
#11 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /datadisk/MISP/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /datadisk/MISP/var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#15 {main}
------------------------------------------------------------------------------------------
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello, 
This was fixed on the `develop` branch and will be merged in the next release.
ref: https://github.com/MISP/MISP/commit/7416a9dd9716acb57bb48ee28286120b62069115
