### ISSUE TITLE
Bug: List Collections not working

### ISSUE THREAD

**Issue by elvidence** [MISP/MISP#9745]
### Actual behavior

https://misp/collections/index should list collections but instead produce "An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator." 

This behaviour is related to the latest  v2.4.192, older version v2.4.189 worked fine

### Expected behavior

https://misp/collections/index should display collections and elements correctly.

### Steps to reproduce

Installed 2.4.189 - works 
Upgraded to 2.4.192 - error

### Version

2.4.192

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox, Chrome

### Browser version

Latest

### Relevant log output

```shell
Error: [RuntimeException] Invalid controller 'collection' specified.
Request URL: /collections/index
Stack Trace:
#0 /var/www/MISP/app/View/Helper/AclHelper.php(34): ACLComponent->canUserAccess()
#1 /var/www/MISP/app/View/Elements/genericElements/SideMenu/side_menu.ctp(369): AclHelper->canAccess()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(1224): View->_render()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(418): View->_renderElement()
#6 /var/www/MISP/app/View/Elements/genericElements/IndexTable/scaffold.ctp(11): View->element()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(1224): View->_render()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(418): View->_renderElement()
#11 /var/www/MISP/app/View/Collections/index.ctp(89): View->element()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(473): View->_render()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(968): View->render()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#18 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#19 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks, should be fixed!
