### ISSUE TITLE
Error: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

### ISSUE THREAD

**Issue by working-Wolf** [MISP/MISP#9786]
### Support Questions

Hello,

I have a problem with Auth keys and benchmark tab located in my profile. MISP show me this error "Something went wrong - could not fetch content."
When I see the logs in /var/www/MISP/app/tmp/logs/error.log it shows:

For Auth key:
2024-06-18 13:09:19 Error: [RedisException] ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
Request URL: /auth_keys/index/2
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/RedisTool.php(44): Redis->auth()
#1 /var/www/MISP/app/Model/AuthKey.php(359): RedisTool::init()
#2 /var/www/MISP/app/Controller/AuthKeysController.php(39): AuthKey->getLastUsageForKeys()
#3 /var/www/MISP/app/Controller/Component/CRUDComponent.php(59): AuthKeysController->{closure}()
#4 /var/www/MISP/app/Controller/AuthKeysController.php(49): CRUDComponent->index()
#5 [internal function]: AuthKeysController->index()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}

For Benchmark
2024-06-18 13:17:36 Error: [Error] Call to a member function smembers() on bool
Request URL: /benchmarks/index/scope:user/average:1/aggregate:1/key:2
Stack Trace:
#0 /var/www/MISP/app/Controller/BenchmarksController.php(46): BenchmarkTool->getAllTopLists()
#1 [internal function]: BenchmarksController->index()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#5 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#6 {main}

I tried to put password on redis but when I do that I have problem with MISP instance.
Can you direct me how to resolve this issue so that i can see in auth keys tab? 

### MISP version

2.4.193

### Operating System

Ubuntu Server

### Operating System version

22.04.4

### PHP version

 7.4.33

### Extra attachments

![Capture](https://github.com/MISP/MISP/assets/173042967/25cd26f5-1f71-41fd-acaf-0ac9e39b59c9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by working-Wolf** [comment]
I forgot to mention that I installed MISP with bash script. 
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sh
