### ISSUE TITLE
Unexpected Behavior: Certain Feeds Fail to Fetch in MISP Instance

### ISSUE THREAD

**Issue by MrM8BRH** [MISP/MISP#9836]
### Actual behavior

I'm encountering issues with certain feeds that are unable to fetch. This problem is causing disruptions in my workflow, and I need assistance in resolving it. I have tried various methods to troubleshoot, but the issue persists. Could you please provide guidance on how to address this problem effectively? Any help would be greatly appreciated.

### Expected behavior

After installing MISP on Ubuntu 22.04 using the official documentation and the one-command liner, the expectation is that all default feeds should be fetched successfully.

### Steps to reproduce

- Install MISP on Ubuntu 22.04 using the official documentation and the one-command liner provided by the MISP project.
- Access the MISP web interface by opening a web browser and navigating to the server's IP address or domain name.
- Log in to the MISP instance using the credentials created during the installation process.
- Enable the default feeds by navigating to the "Feeds" section in the MISP interface and selecting the desired feeds.
- Attempt to fetch all feeds by clicking the "Fetch all feeds" option or triggering the fetch process manually for individual feeds.
- Observe the behavior of the feeds. The issue occurs when certain feeds fail to fetch, resulting in incomplete or missing data in the MISP instance.

### Version

2.4.194

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Browser

Firefox

### Relevant log output

```shell
root@misp:/var/www/MISP/app/tmp/logs# cat error.log
2024-07-20 09:55:33 Warning: Illegal string offset 'disable_correlation' in [/var/www/MISP/app/Model/Feed.php, line 1352]
2024-07-20 10:02:07 Error: Could not get freetext feed 15
[Exception] Fetching the 'https://osint.bambenekconsulting.com/feeds/c2-ipmasterlist-high.txt' failed with exception: curl error 60 'SSL peer certificate or SSH remote key was not OK': SSL certificate problem: self-signed certificate
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(394): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(433): Feed->getFreetextFeedRemote()
#2 /var/www/MISP/app/Model/Feed.php(1281): Feed->getFreetextFeed()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Console/Command/AppShell.php(60): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#10 {main}
[SocketException] curl error 60 'SSL peer certificate or SSH remote key was not OK': SSL certificate problem: self-signed certificate
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(89): CurlClient->internalRequest()
#1 /var/www/MISP/app/Model/Feed.php(2197): CurlClient->get()
#2 /var/www/MISP/app/Model/Feed.php(2157): Feed->getFollowRedirect()
#3 /var/www/MISP/app/Model/Feed.php(394): Feed->feedGetUriRemote()
#4 /var/www/MISP/app/Model/Feed.php(433): Feed->getFreetextFeedRemote()
#5 /var/www/MISP/app/Model/Feed.php(1281): Feed->getFreetextFeed()
#6 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#7 /var/www/MISP/app/Console/Command/AppShell.php(60): ServerShell->fetchFeed()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#13 {main}
2024-07-20 10:02:07 Error: Could not get freetext feed 16
[Exception] Fetching the 'https://osint.bambenekconsulting.com/feeds/c2-dommasterlist-high.txt' failed with exception: curl error 60 'SSL peer certificate or SSH remote key was not OK': SSL certificate problem: self-signed certificate
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(394): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(433): Feed->getFreetextFeedRemote()
#2 /var/www/MISP/app/Model/Feed.php(1281): Feed->getFreetextFeed()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Console/Command/AppShell.php(60): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#10 {main}
[SocketException] curl error 60 'SSL peer certificate or SSH remote key was not OK': SSL certificate problem: self-signed certificate
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(89): CurlClient->internalRequest()
#1 /var/www/MISP/app/Model/Feed.php(2197): CurlClient->get()
#2 /var/www/MISP/app/Model/Feed.php(2157): Feed->getFollowRedirect()
#3 /var/www/MISP/app/Model/Feed.php(394): Feed->feedGetUriRemote()
#4 /var/www/MISP/app/Model/Feed.php(433): Feed->getFreetextFeedRemote()
#5 /var/www/MISP/app/Model/Feed.php(1281): Feed->getFreetextFeed()
#6 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#7 /var/www/MISP/app/Console/Command/AppShell.php(60): ServerShell->fetchFeed()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#13 {main}
```

### Extra attachments

![2024-07-20_13-02](https://github.com/user-attachments/assets/a35edad6-3b05-489a-bdc3-ae0b0b8e497f)
![2024-07-20_13-04](https://github.com/user-attachments/assets/77401686-afb6-4020-ba7f-3dd62cd8570a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elvidence** [comment]
You are trying to access paid feeds without authentication. Bambenek Consulting feeds are no longer free. Navigate to the URL with your browser and read the notice.

**Comment by MrM8BRH** [comment]
> You are trying to access paid feeds without authentication. Bambenek Consulting feeds are no longer free. Navigate to the URL with your browser and read the notice.

I disabled the Bambenek feeds, but there are another feeds that can't be fetched like:

- CIRCL OSINT Feed: https://www.circl.lu/doc/misp/feed-osint
- Botvrij.eu Data: https://www.botvrij.eu/data/feed-osint
- DigitalSide Threat-Intel OSINT Feed: https://osint.digitalside.it/Threat-Intel/digitalside-misp-feed/

How can I solve this problem?

**Comment by vikaspuri764-commits** [comment]
The same issue i have got trying to solve but not getting solved so could any one help me out of this
