### ISSUE TITLE
Support: Phishtank Feed Issue 

### ISSUE THREAD

**Issue by Moorocks** [MISP/MISP#9855]
### Support Questions

I'm trying to pull feed from phishtank, however i end up getting ssl related error.
I'm trying to bypass the security checks by using -k filter, but still i do end up getting the error.

Command used:
curl -k -X POST --noproxy 10.192.10.10 --header "Authorization: NhhZOdFwMpSNf3yA8iAvNHYT"  --header "User-Agent: MISP 2.4.191" --header "Accept: application/json" --header "Content-Type: application/json" https://10.192.10.10/feeds/fetchFromFeed/89

### MISP version

2.4.191

### Operating System

Red Hat 8.9

### Operating System version

8.9

### PHP version

7.2

### Relevant log output

```shell
2024-08-06 06:55:54 Error: Could not get freetext feed 89 [Exception] Fetching the 'https://data.phishtank.com/data/online-valid.csv' failed with exception: curl error 35 'SSL connect error': OpenSSL SSL_connect: Connection reset by peer in connection to cdn.phishtank.com:443 Stack Trace: #0 /var/www/MISP/app/Model/Feed.php(343): Feed->feedGetUriRemote() #1 /var/www/MISP/app/Model/Feed.php(382): Feed->getFreetextFeedRemote() #2 /var/www/MISP/app/Model/Feed.php(1229): Feed->getFreetextFeed() #3 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator() #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed() #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand() #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch() #7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run() #8 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moorocks** [comment]
I can confirm that I'm using the -k flag to bypass cert error, but I'm still getting an error. Let me know if anything else is required from my end.

**Comment by UFOSmuggler** [comment]
User has discussed this issue in gitter too: https://matrix.to/#/!MduNzlmtqnwdPigyaC:gitter.im/$lAObGWt5VaTy4twUvXeNEYCazUKBecfb4KMDT67ZfZM?via=gitter.im&via=matrix.circl.lu&via=matrix.org

suspect proxying issue or similar.
