### ISSUE TITLE
Bug: Table correlation_rules for model CorrelationRule was not found in datasource default

### ISSUE THREAD

**Issue by vincenzocaputo** [MISP/MISP#9864]
### Actual behavior

When I try to add an attribute to an event, the following error occurs:

```
2024-08-14 12:35:05 Error: [MissingTableException] Table correlation_rules for model CorrelationRule was not found in datasource default.
Exception Attributes: array (
  'table' => 'correlation_rules',
  'class' => 'CorrelationRule',
  'ds' => 'default',
)
Request URL: /attributes/add/122c7ed9-b736-4486-8e93-1213a674da12
Stack Trace:
#0 /misp/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#1 /misp/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): Model->getDataSource()
#2 /misp/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#3 /misp/MISP/app/Model/AppModel.php(4255): Model->find()
#4 /misp/MISP/app/Model/CorrelationRule.php(92): AppModel->find()
#5 /misp/MISP/app/Model/CorrelationRule.php(81): CorrelationRule->__loadRuleCache()
#6 /misp/MISP/app/Model/Correlation.php(487): CorrelationRule->attachCustomCorrelationRules()
#7 /misp/MISP/app/Model/Attribute.php(481): Correlation->afterSaveCorrelation()
#8 /misp/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute->afterSave()
#9 /misp/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEventManager->dispatch()
#10 /misp/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#11 /misp/MISP/app/Model/Attribute.php(565): Model->save()
#12 /misp/MISP/app/Model/Attribute.php(2715): Attribute->save()
#13 /misp/MISP/app/Controller/AttributesController.php(164): Attribute->captureAttribute()
#14 [internal function]: AttributesController->add()
#15 /misp/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#16 /misp/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#17 /misp/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#18 /misp/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#19 {main}
```

The same error arises when I try to visit the "Correlation Rules" page.

### Expected behavior

Add attributes without raising errors

### Steps to reproduce

Create a new Attribute or visit the Correlation Rules page.

### Version

2.4.195

### Operating System

Red Hat

### Operating System version

Red Hat Enterprise Linux release 8.5 (Ootpa)

### PHP version

7.4.30

### Extra attachments

Below are additional details from the "Schema status" in diagnostics

![image](https://github.com/user-attachments/assets/63f41630-30f3-4e3c-a884-2d74e8b862cf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincenzocaputo** [comment]
I've just solved the issue by restarting the workers.
