### ISSUE TITLE
Bug: Crash when running a workflow

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#9872]
### Actual behavior

When I run a workflow , it crash

### Expected behavior

that it's run :)

### Steps to reproduce

create a simple workflow and run it 

### Version

Latest

### Operating System

ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Relevant log output

```shell
2024-08-20 15:26:45 Error: [SocketException] Connection refused
Request URL: /workflows/executeWorkflow/3?_=1724160374333
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request()
#3 /var/www/MISP/app/Model/Workflow.php(1564): HttpSocket->post()
#4 /var/www/MISP/app/Model/Workflow.php(1539): Workflow->sendRequestToDebugEndpoint()
#5 /var/www/MISP/app/Model/Workflow.php(547): Workflow->sendRequestToDebugEndpointIfDebug()
#6 /var/www/MISP/app/Model/Workflow.php(423): Workflow->__runWorkflow()
#7 /var/www/MISP/app/Controller/WorkflowsController.php(182): Workflow->executeWorkflow()
#8 [internal function]: WorkflowsController->executeWorkflow()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#13 {main}
2024-08-20 15:26:45 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException()
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
2024-08-20 15:26:45 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 [internal function]: ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error()
#3 [internal function]: ErrorHandler::handleException()
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2024-08-20 15:26:45 Error: [InternalErrorException] Internal Server Error
Request URL: /workflows/executeWorkflow/3?_=1724160374333
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FafnerKeyZee** [comment]
Ok, looks like I have to run the script: tools/misp-workflow/webhook-listener.py by myself :/
