### ISSUE TITLE
Support: Unable to fetch events from feeds

### ISSUE THREAD

**Issue by BlueValley190** [MISP/MISP#9887]
### Support Questions

Hello,
Thank you in advance for helping a very new user into MISP's world!

I've installed MISP using the procedure given (xsnippet, install.sh, version selection with script, install with the MISP core and modules options (-c -M)) and enabled CIRCL feed.
While attempting to fetch events from it, the job fails and I get the following error (see logs)
The workers are healthy if we believe their diagnostic page ; I've got no errors from them.

Do I need to fix the modules to make it work?

Thanks again!

### MISP version

2.4.196

### Operating System

Ubuntu

### Operating System version

22.04.4

### PHP version

7.4.33

### Browser

Chrome

### Relevant log output

```shell
Error: Argument 2 passed to Feed::checkEventAgainstRules() must be of the type array, null given, called in /var/www/MISP/app/Model/Feed.php on line 221
#0 /var/www/MISP/app/Model/Feed.php(221): Feed->checkEventAgainstRules()
#1 /var/www/MISP/app/Model/Feed.php(1263): Feed->getNewEventUuids()
#2 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#3 /var/www/MISP/app/Console/Command/AppShell.php(60): ServerShell->fetchFeed()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#9 {main}



The whole diagnostic page is green, apart from : 

**ModuleSystem**
This tool tests the various module systems and whether they are reachable based on the module settings.

Enrichment module system…curl error 7 'Couldn't connect to server': **Failed to connect to 127.0.0.1 port 6666 after 0 ms: Connection refused**
Import module system…curl error 7 'Couldn't connect to server': **Failed to connect to 127.0.0.1 port 6666 after 0 ms: Connection refused**
Export module system…curl error 7 'Couldn't connect to server': **Failed to connect to 127.0.0.1 port 6666 after 0 ms: Connection refused**
Cortex module system…**System not enabled**
```
```


### Extra attachments

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elvidence** [comment]
To verify that your MISP instance is correctly fetching feeds, you should first navigate to the appropriate directory and run a specific command:

Navigate to the MISP Application Directory: Open your terminal and execute:
`cd /var/www/MISP/app`
Use the following command to manually fetch a feed:
`sudo -u www-data ./Console/cake Server fetchFeed 2 3`

Here, 2 represents the user ID (which you can find in the User List in the MISP Admin interface), and 3 is the feed ID (the specific feed number you want to test).

After running the command, review the MISP logs to ensure there are no errors and that the feed is fetching correctly.


Regarding the issue with the MISP modules indicated by the curl error:

This error typically suggests a problem with the connectivity or configuration of your MISP modules. It appers to be separate issue to feeds.

To check if the module service is active and listening on the expected port:

Run this command in your terminal:

`ss -tuln | grep 6666`
If the module engine is working, you should see an output indicating that the service is listening, similar to:

`tcp   LISTEN 0      128          127.0.0.1:6666      0.0.0.0:* `      
If there is no such output, it means that no service is currently listening on port 6666, which could be why you are encountering errors. You may need to start the module service or troubleshoot its configuration.

**Comment by BlueValley190** [comment]
Hello, thank you for your time & help!

`sudo -u www-data ./Console/cake Server fetchFeed (user ID) (feed ID)`
gives the following output :
`PHP Warning:  include(Cake/Console/ShellDispatcher.php): failed to open stream:No such file or directory in /home/redacted/MISP/app/Console/cake.php on line 40

PHP Warning:  include(): Failed opening 'Cake/Console/ShellDispatcher.php' for inclusion (include_path='/home/redacted/MISP/app/Lib/cakephp/lib:.:/usr/share/php') in /home/redacted/MISP/app/Console/cake.php on line 40

PHP Fatal error:  Could not locate CakePHP core files. in /home/redacted/MISP/app/Console/cake.php on line 41`

My uneducated guess goes to CakePHP being broken, I will read more about it  (and appreciate any recommandations !)

---
`ss -tuln | grep 6666`
gives no output either, I will work my way around starting the service and come back with further progress, hopefully!

Thanks again!

**Comment by Benni0** [comment]
@BlueValley190
it's a bug in MISP itself, I've created a pull request with a fix for it (#9893).
If you don't want to wait till the pull request got merged and the fix is released, you can add the two lines from the fix to your Feed.php.
