### ISSUE TITLE
Bug: GPG for notifications crashing on homedir option

### ISSUE THREAD

**Issue by KALRONG** [MISP/MISP#9892]
### Actual behavior

While trying to send a notification, new event for example, email is not send with the error GPG couldn't be initializaed.

### Expected behavior

Email notification to be sent.

### Steps to reproduce

Base installation:
1. Configure user to receive notifications.
2. Generate an event and publish it.
3. Check logs to see if email has been sent.

### Version

2.4.196

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
2024-08-30 08:56:37 Notice: GPG couldn't be initialized, GPG encryption and signing will be not available.

[Crypt_GPG_FileException] The 'homedir' "" is not readable or does not exist and cannot be created. This can happen if 'homedir' is not specified in the Crypt_GPG options, Crypt_GPG is run as the web user, and the web user has no home directory.

Stack Trace:

#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPGAbstract.php(256): Crypt_GPG_Engine->__construct()

#1 /var/www/MISP/app/Lib/Tools/CryptGpgExtended.php(11): Crypt_GPGAbstract->__construct()

#2 /var/www/MISP/app/Lib/Tools/GpgTool.php(34): CryptGpgExtended->__construct()

#3 /var/www/MISP/app/Model/User.php(1588): GpgTool::initializeGpg()

#4 /var/www/MISP/app/Model/User.php(884): User->initializeGpg()

#5 /var/www/MISP/app/Model/Event.php(3242): User->sendEmail()

#6 /var/www/MISP/app/Console/Command/EventShell.php(300): Event->sendAlertEmail()

#7 /var/www/MISP/app/Console/Command/AppShell.php(60): EventShell->alertemail()

#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()

#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()

#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()

#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()

#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()

#13 {main}

root@MISP:/var/www/MISP/app# sudo -H -u www-data /var/www/MISP/app/Console/cake Admin getSetting GnuPG.homedir

{

    "level": 0,

    "description": "The location of the GnuPG homedir.",

    "value": "/var/www/MISP/.gnupg",

    "test": "testForEmpty",

    "type": "string",

    "tab": "Encryption",

    "setting": "GnuPG.homedir"

}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
It looks like `GnuPG.homedir` config variable is not set or it is empty.

**Comment by KALRONG** [comment]
> It looks like `GnuPG.homedir` config variable is not set or it is empty.

In the last lines of the logs I attached you can see that the variable is propertly set.
