### ISSUE TITLE
Bug: Can't edit Mapping of DecayingModel to Attribute Types

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#9907]
### Actual behavior

When adding a new Decaying model or editing an existing one in the DecayingModel Tool, it's not possible to add associated attribute types to the model.
After saving changes, the affecting changes do not apply. 

### Expected behavior

Decaying Models should be mappable to type in the DecayingModelTool

### Steps to reproduce

1. Open DecayingModelTool
2. Load one of the existing Models
3. Select some attribute types to map
4. click Edit, (Loading spinner will not stop, even if the message says it saved the model)
5. reload and check the associated types

### Version

2.4.197

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Relevant log output

```shell
2024-09-10 11:06:07 Error: [MissingActionException] Action DecayingModelMappingController::index() could not be found.
Exception Attributes: array (
  'controller' => 'DecayingModelMappingController',
  'action' => 'index',
)
Request URL: /decayingModelMapping/
Stack Trace:
#0 /srv/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#1 /srv/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#2 /srv/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#3 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elvidence** [comment]
Yeah, it is well known issue. 
TypeError: undefined is not an object (evaluating 'data.data.DecayingModel')
undefined is not an object (evaluating 'data.data.DecayingModel') etc.
Been around for a while now. :(

**Comment by marjatech** [comment]
just found my own issue again while i googled how to map attribute_types to decaying-models. 
Is there still some support for this feature? it's practically only usable by editing the database directly now. 
@mokaddem maybe?

**Comment by marjatech** [comment]
the issue arised with the fix for #9769
some types where not fixed there
