### ISSUE TITLE
Bug: An Internal Error Has Occurred when access Diagnostics or Report Download pages inside Administration - Server Settings & Maintenance

### ISSUE THREAD

**Issue by jowilsonfo** [MISP/MISP#9933]
### Actual behavior

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Expected behavior

Display diagnostics page or Download Report page

### Steps to reproduce

Administration - Server Settings & Maintenance - Diagnostics page
Administration - Server Settings & Maintenance - Download Report page

### Version

2.4.198

### Operating System

AlmaLinux

### Operating System version

8.10 (Cerulean Leopard)

### PHP version

PHP 7.4.33 (cli) (built: Oct 31 2022 10:36:05) ( NTS )

### Browser

Chrome and Edge

### Browser version

latest

### Relevant log output

```shell
I've just upgraded a test instance and trying to access the Administration - Server Settings & Maintenance - Diagnostics page trigger this in error.log

2024-09-25 15:43:16 Error: [Exception] It is not possible convert to string encrypted JSON value.
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 [internal function]: EncryptedValue->__toString()
#1 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(419): strlen()
#2 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(196): SecurityAudit->email()
#3 /var/www/MISP/app/Controller/ServersController.php(1218): SecurityAudit->run()
#4 [internal function]: ServersController->serverSettings()
#5 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#9 {main}


If I try to access the Administration - Server Settings & Maintenance - Download Report page trigger this in error.log

2024-09-25 15:44:26 Error: [Exception] It is not possible convert to string encrypted JSON value.
Request URL: /servers/serverSettings/download
Stack Trace:
#0 [internal function]: EncryptedValue->__toString()
#1 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(419): strlen()
#2 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(196): SecurityAudit->email()
#3 /var/www/MISP/app/Controller/ServersController.php(1218): SecurityAudit->run()
#4 [internal function]: ServersController->serverSettings()
#5 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#9 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jowilsonfo** [comment]
I found a workaround, explained below:
1 - I use the option Security.encryption_key to encryption sensitive data in database encrypted
2 - I use GnuPG.password
When i cleared my GnuPG.password the diagnostics and report worked.
Examining the code, i understand that the function that return the GNUPG.password is not decrypting the data that came from the database.

**Comment by jowilsonfo** [comment]
The same thing occurred with the option Proxy.password, if configured, this error occur:
2024-09-27 14:57:06 Error: [Exception] It is not possible convert to string encrypted JSON value.
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(348): EncryptedValue->__toString()
#1 /var/www/MISP/app/Lib/Tools/CurlClient.php(175): CurlClient->generateDefaultOptions()
#2 /var/www/MISP/app/Lib/Tools/SyncTool.php(98): CurlClient->configProxy()
#3 /var/www/MISP/app/Lib/Tools/SyncTool.php(39): SyncTool->createHttpSocket()
#4 /var/www/MISP/app/Model/AppModel.php(3448): SyncTool->setupHttpSocket()
#5 /var/www/MISP/app/Model/Server.php(4276): AppModel->setupHttpSocket()
#6 /var/www/MISP/app/Controller/ServersController.php(1137): Server->getCurrentGitStatus()
#7 [internal function]: ServersController->serverSettings()
#8 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#12 {main}
