### ISSUE TITLE
Bug: Searching for attributes broken in 2.5.0

### ISSUE THREAD

**Issue by simonbjorzen-ts** [MISP/MISP#9964]
### Actual behavior

Search for an attribute using the "Search Attributes" function in the GUI

### Expected behavior

Search results returned

### Steps to reproduce

Internal server error related to an SQL error, see log output

### Version

2.5.0

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

8.3

### Relevant log output

```shell
2024-10-08 14:23:29 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1176 Key 'deleted' doesn't exist in table 'Attribute'
Request URL: /attributes/search/results
Stack Trace:
#0 /var/www/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/misp/app/Model/Datasource/Database/MysqlObserverExtended.php(167): DboSource->_execute()
#2 /var/www/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): MysqlObserverExtended->execute()
#3 /var/www/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/misp/app/Lib/cakephp/lib/Cake/Model/Model.php(3054): DboSource->read()
#5 /var/www/misp/app/Lib/cakephp/lib/Cake/Model/Model.php(3026): Model->_readDataSource()
#6 /var/www/misp/app/Model/AppModel.php(4303): Model->find()
#7 /var/www/misp/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(212): AppModel->find()
#8 /var/www/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1112): PaginatorComponent->paginate()
#9 /var/www/misp/app/Controller/AttributesController.php(1566): Controller->paginate()
#10 [internal function]: AttributesController->search()
#11 /var/www/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#12 /var/www/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/misp/app/webroot/index.php(99): Dispatcher->dispatch()
#15 {main
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cocochepeau** [comment]
I confirm this one.
