### ISSUE TITLE
Bug: v2.5.0 An Internal Error Has Occurred. (trying to open some events)

### ISSUE THREAD

**Issue by sim0nx** [MISP/MISP#9978]
### Actual behavior

After haivng upgraded to v2.5.0, trying to open some events (not all) the following error is displayed:
An Internal Error Has Occurred.

### Expected behavior

Event should be displayed.

### Steps to reproduce

:shrug: I can't really tell what is special about those events that hit the error.

### Version

2.5.0

### Operating System

Debian

### Operating System version

12

### PHP version

8.2

### Browser

Chrome

### Relevant log output

```shell
2024-10-11 14:31:54 Error: [JsonException] The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.
Request URL: /events/view/445530
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/RedisTool.php(168): JsonTool::decode()
#1 /var/www/MISP/app/Model/Warninglist.php(193): RedisTool::deserialize()
#2 /var/www/MISP/app/Model/Event.php(2135): Warninglist->attachWarninglistToAttributes()
#3 /var/www/MISP/app/Controller/EventsController.php(1775): Event->fetchEvent()
#4 [internal function]: EventsController->view()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Try to enable or disable any warninglist. It should delete cache in Redis, that seems broken.

**Comment by sim0nx** [comment]
I did a *FLUSHALL* on redis-cli and that indeed did the trick.
Thanks!

**Comment by sim0nx** [comment]
Reopening as I am still seeing this problem.

Though clearing redis **or** switching a warninglist off/on does help... the problem re-appears shortly after.

FYI I am on 2.5.1 now

**Comment by SAIKATDASGITHUB** [comment]
Hi @sim0nx 

Did you find any solution for this? My MISP is facing the same after upgrading to 2.5.1.

**Comment by iglocska** [comment]
I can't seem to reproduce this, are you using any custom warninglists by chance? Anything you can share to help us?

**Comment by SAIKATDASGITHUB** [comment]
Hi @iglocska,

If the question is for me then I am not using any custom warning list. Infact I just updated to 2.5.1 few hrs ago and noticing few issues as of now.

1. Not able to view any of the events. Tried few of the solutions mentioned in MISP Github but no success as of now. This is the error log for this:

 Error: [ArgumentCountError] array_merge() does not accept unknown named parameters
Request URL: /events/view/1635
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/Folder.php(229): array_merge()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/Folder.php(246): Folder->read()
#2 /var/www/MISP/app/Model/Behavior/EventWarningBehavior.php(32): Folder->find()
#3 /var/www/MISP/app/Model/Behavior/EventWarningBehavior.php(18): EventWarningBehavior->__loadCustomWarningSystems()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(238): EventWarningBehavior->generateWarnings()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollection->dispatchMethod()
#6 /var/www/MISP/app/Controller/EventsController.php(1613): Model->__call()
#7 /var/www/MISP/app/Controller/EventsController.php(1826): EventsController->__viewUI()
#8 [internal function]: EventsController->view()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#13 {main}


2. Also not able to add organisation or not able to add sync server. This is the error log for this:

 Error: Blackhole exception when accessing /servers/add (isRest: 0, action: add, unlockedActions: ["cspReport"]): The request has been bl>
2024-10-29 04:27:08 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#10 {main}



 Error: Blackhole exception when accessing /admin/organisations/add (isRest: 0, action: admin_add, unlockedActions: []): The request has >
2024-10-29 05:34:53 Error: [BadRequestException] The request has been black-holed
Request URL: /admin/organisations/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#10 {main}

**Comment by iglocska** [comment]
I've added a blind mitigation for now, please update and we can hopefully get an idea of what's going on here. The mitigation will let it fail gracefully and stop the event view from barfing, though the warning will still be ignored due to the failure.

However, you should now have some new entries in your error.log indicating which entries couldn't be deserialized, in the following format:

```
2024-10-29 05:34:28 Error: Failed to deserialize warninglist cache: {"95":["foobar.baz","foobar.baz"]}
```

**Comment by iglocska** [comment]
@SAIKATDASGITHUB

This seems to be a completely unrelated issue, whilst the feature that barfs for you also contains the name "warnings" this is a completely distinct subsystem from warninglists. Could you open a separate issue for this?

**Comment by SAIKATDASGITHUB** [comment]
Hi @iglocska ,

Sure I will open an new issue for this.

**Comment by sim0nx** [comment]
@iglocska I am using some standard warninglist, nothing custom. This is my installation that has been running fine for years now... I just upgraded to 2.5.0, 2.5.1 recently.

I should add that this issue not only happens when viewing events but also for creating events, which makes it currently practically impossible to create new events.

I am happy to share whatever helps, not sure what exactly though :see_no_evil: 

Some infos from the diagnostics page:
- Writeable Directories and files: all ok
- PHP Settings: all ok
- PHP Extensions: all ok
- PHP Dependencies: all ok
- Schema status: all ok
- Redis info: all ok
- STIX and Cybox libraries: all ok

I am using the supervisor based workers.

**Comment by mokaddem** [comment]
@sim0nx unfortunately, I could not reproduce this on v2.5.1 (c9fe5692969c08b755d9ee64fa0bdb603703a22d) with PHP 8.3.6.
I tried to following:
- Creating an Event
- Viewing Event that **have** warninglist hits
- Viewing Event that **don't have** warninglist hits

Is there anything else you spot in the logs that could be useful for us to track down the issue?
Does the original log entry still appear even with warninglist disabled?
```text
2024-10-11 14:31:54 Error: [JsonException] The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.
```
Sorry for not being able to help more.

**Comment by sim0nx** [comment]
Thanks

@mokaddem I have so far only switched one random warninglist off/on to make the issue temporarily disappear.

Before trying to disable them all ... would you have a suggestion on how to debug this issue ?
I am not really fluent in php, but maybe there is some way to get to the root of this.

Clearing redis helps ... but something clearly writes "bad" data again into redis; sync issue ? :shrug:

**Comment by iglocska** [comment]
@sim0nx - do you still have the issue with the latest commit?

**Comment by iglocska** [comment]
In particular this commit tried to address it: https://github.com/MISP/MISP/commit/58a34331728d4c0ac1ccf16388dde2eb16111de7

**Comment by sim0nx** [comment]
@iglocska I've just tested that commit (actually 2.5 branch) with a number of "problematic" events.
They now display correctly, which is great :partying_face:  ... and I see the following log being logged now:

```
2024-11-06 16:16:38 Error: Failed to deserialize warninglist cache: s:0:"";
```

Does that help ?

**Comment by sim0nx** [comment]
@iglocska as far as our further tests go, the issue seems to be resolved, besides the error log mentioned above (https://github.com/MISP/MISP/issues/9978#issuecomment-2460216168).

I'll await your feedback on if this is something that needs further looking into or not.

TIA
