### ISSUE TITLE
Bug: Blackhole exception when accessing submitting a screenshot to the email object

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#9982]
### Actual behavior

- Add an attribute to an existing MISP object with the "+" icon
- Add a screenshot
- Error returned in web interface

Response text (web developer pane):
```
You have tripped the cross-site request forgery protection of MISP

CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed. 
```

MISP error log:

```
Blackhole exception when accessing /objects/quickAddAttributeForm/118759 (isRest: 0, action: quickAddAttributeForm, unlockedActions: ["revise_object","get_row"]): The request has been black-holed
2024-10-14 10:18:58 Error: [BadRequestException] The request has been black-holed
Request URL: /objects/quickAddAttributeForm/118759
Stack Trace:
#0 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /data/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /data/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /data/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /data/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): BetterCakeEventManager->dispatch()
#7 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /data/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /data/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
```

Editing the object (objects/edit) and then add the screenshot gives no error.

### Expected behavior

Add the screenshot to the email object

### Steps to reproduce

- Add an attribute to an existing MISP object with the "+" icon
- Add a screenshot

### Version

2.4.198

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SAIKATDASGITHUB** [comment]
Hi,

Anybody found a solution for this?

@iglocska I am also getting the same error - Cross site request forgery protection of MISP

This error I am getting while adding a new organization and also while adding a new sync server.

Version - 2.5.1
PHP - 8.3

Error Log:

2024-10-23 10:26:52 Error: Blackhole exception when accessing /admin/organisations/add (isRest: 0, action: admin_add, unlockedActions: []): The request has >
2024-10-23 10:26:52 Error: [BadRequestException] The request has been black-holed
Request URL: /admin/organisations/add

Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
https://github.com/MISP/MISP/issues/1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
https://github.com/MISP/MISP/issues/2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
https://github.com/MISP/MISP/issues/3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
https://github.com/MISP/MISP/issues/4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
https://github.com/MISP/MISP/issues/5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
https://github.com/MISP/MISP/issues/6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): BetterCakeEventManager->dispatch()
https://github.com/MISP/MISP/issues/7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
https://github.com/MISP/MISP/issues/8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
https://github.com/MISP/MISP/issues/9 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
https://github.com/MISP/MISP/issues/10 {main}
