### ISSUE TITLE
Bug: Elasticsearch ClientBuilder.php not found

### ISSUE THREAD

**Issue by blackrogan** [MISP/MISP#9983]
### Actual behavior

Everytime I try to login and have installed and active plugin Elasticsearch I get this error

2024-10-14 11:07:50 Error: [Error] Class "Elasticsearch\ClientBuilder" not found
Request URL: /users/login?_=1728904065067
Stack Trace:
#0 /var/www/MISP/app/Model/Log.php(1234): ElasticSearchClient->initTool()
#1 /var/www/MISP/app/Model/Log.php(396): Log->getElasticSearchTool()
#2 /var/www/MISP/app/Model/Log.php(166): Log->logData()
#3 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Log->beforeSave()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1874): BetterCakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1761): Model->_doSave()
#6 /var/www/MISP/app/Model/Log.php(269): Model->save()
#7 /var/www/MISP/app/Model/User.php(1340): Log->createLogEntry()
#8 /var/www/MISP/app/Controller/UsersController.php(1281): User->extralog()
#9 /var/www/MISP/app/Controller/UsersController.php(1258): UsersController->_postlogin()
#10 [internal function]: UsersController->login()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#15 {main}

### Expected behavior

That ClientBuilder is found and connector works

### Steps to reproduce

Enable  in Server Settings and Maintenance > Plugin > ElasticSearch > Plugin.ElasticSearch_logging_enable true 

and also install with composer in /var/www/MISP/app sudo -u www-data composer require elasticsearch/elasticsearch

### Version

2.5.0

### Operating System

Ubuntu

### Operating System version

20.04.1

### PHP version

8.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks for the heads-up, expect a fix in 2.5.2

**Comment by blackrogan** [comment]
hello an issue in version 2.5.2 still persist

Class "Elasticsearch\ClientBuilder" not found
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Stack Trace
[APP/Model/Log.php line 1234](https://192.168.175.156/users/logout#) → [ElasticSearchClient->initTool()](https://192.168.175.156/users/logout#)
[APP/Model/Log.php line 396](https://192.168.175.156/users/logout#) → [Log->getElasticSearchTool()](https://192.168.175.156/users/logout#)
[APP/Model/Log.php line 166](https://192.168.175.156/users/logout#) → [Log->logData()](https://192.168.175.156/users/logout#)
[APP/Lib/Tools/BetterCakeEventManager.php line 21](https://192.168.175.156/users/logout#) → [Log->beforeSave()](https://192.168.175.156/users/logout#)
[APP/Lib/cakephp/lib/Cake/Model/Model.php line 1874](https://192.168.175.156/users/logout#) → [BetterCakeEventManager->dispatch()](https://192.168.175.156/users/logout#)
[APP/Lib/cakephp/lib/Cake/Model/Model.php line 1761](https://192.168.175.156/users/logout#) → [Model->_doSave()](https://192.168.175.156/users/logout#)
[APP/Model/Log.php line 269](https://192.168.175.156/users/logout#) → [Model->save()](https://192.168.175.156/users/logout#)
[APP/Model/User.php line 1340](https://192.168.175.156/users/logout#) → [Log->createLogEntry()](https://192.168.175.156/users/logout#)
[APP/Controller/UsersController.php line 1354](https://192.168.175.156/users/logout#) → [User->extralog()](https://192.168.175.156/users/logout#)
[[internal function]](https://192.168.175.156/users/logout#) → [UsersController->logout()](https://192.168.175.156/users/logout#)
[APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 500](https://192.168.175.156/users/logout#) → [ReflectionMethod->invokeArgs()](https://192.168.175.156/users/logout#)
[APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193](https://192.168.175.156/users/logout#) → [Controller->invokeAction()](https://192.168.175.156/users/logout#)
[APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167](https://192.168.175.156/users/logout#) → [Dispatcher->_invoke()](https://192.168.175.156/users/logout#)
[APP/webroot/index.php line 107](https://192.168.175.156/users/logout#) → [Dispatcher->dispatch()](https://192.168.175.156/users/logout#)

**Comment by blackrogan** [comment]
plugin installed with composer was the latest version 8.16.0. Does MISP require some specific version of the plugin to make it work?
