### ISSUE TITLE
Bug: "Plugin DebugKit could not be found"

### ISSUE THREAD

**Issue by xme** [MISP/MISP#9984]
### Actual behavior

I'm migrating my MISP from 2.4 to 2.5. Running the provided upgrade script.

### Expected behavior

Got this error:
```
OK] MISP database.php file rewritten.
[STATUS] Running MISP updates
[ERROR] MISP schema updates failed. Please check /var/log/misp_upgrade.log for more details.
```
From the log:
```
Use the `composer fund` command to find out more!
Error: Plugin DebugKit could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php(167): CakePlugin::load()
#1 /var/www/MISP/app/Config/bootstrap.php(180): CakePlugin::loadAll()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('...')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct()
#8 /var/www/MISP/app/Console/cake.php(43): ShellDispatcher::run()
#9 {main}
```

[Update]
MISP seems to be running fine... Web is up and events are available.

### Steps to reproduce

Just run the upgrade script after a git pull...

### Version

2.4.198

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xme** [comment]
Updated:
It seems I solved the problem with:
`php composer.phar require --dev cakephp/debug_kit`
All components seem to run smoothly!

**Comment by iglocska** [comment]
Phew, thanks for the heads up, will leave this issue open for now in case someone runs into the same problem.

**Comment by marcnil815** [comment]
Same here. Fixed with the below

```
/var/www/MISP/app# sudo -u www-data php composer.phar require --dev cakephp/debug_kit
```

**Comment by asabolansky** [comment]
Same here

**Comment by fukusuket** [comment]
Same here. Fixed with the below
```
/var/www/MISP/app# sudo -u www-data php composer.phar require --dev cakephp/debug_kit
```
In our environment, the following command was also necessary.
```
/var/www/MISP# cp -r ./vendor/cakephp/debug_kit/ ./app/Plugin/
```

**Comment by Schroeffu** [comment]
thx2 @fukusuket for me that was working after the script failed:

`/var/www/MISP/app# sudo -u www-data php composer.phar require --dev cakephp/debug_kit`

but, there are skipped steps in that script. to make it re-run, I commented out line 129-218 and ran it again. Now it completed the last steps.
