### ISSUE TITLE
Bug: Free Text Import issue on MISP 2.5.0 on docker

### ISSUE THREAD

**Issue by theice9c** [MISP/MISP#9996]
### Actual behavior

When you try to insert ioc through the free text import tool you get an error message as follows in the image.

![immagine](https://github.com/user-attachments/assets/20a3b4f2-5abf-4256-bd5b-25eb1618e319)

### Expected behavior

It does not allow you to insert new iocs through the free text import tool

### Steps to reproduce

Create a new event, then add an attribute using the free text import tool button, the error message will appear

### Version

2.5.0

### Operating System

Docker on Ubuntu Server

### Operating System version

22.04.5 LTS

### PHP version

8

### Browser

Chrome

### Relevant log output

```shell
2024-10-17 11:16:57 Error: [TypeError] Attribute::__construct(): Argument #1 ($flags) must be of type int, array given
Request URL: /events/freeTextImport/2?_=1729163804988
Stack Trace:
#0 [internal function]: Attribute->__construct()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(171): ClassRegistry::init()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(204): FormHelper->_getModel()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(354): FormHelper->_introspectModel()
#5 /var/www/MISP/app/View/Events/free_text_import.ctp(2): FormHelper->create()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('...')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(473): View->_render()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(973): View->render()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#13 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theice9c** [comment]
Comparing version 2.4 with version 2.5, the freeTextImport function has a model that has changed. The main difference seems to lie in the use of the model name in the import form. In the new version of MISP 2.5.0, MispAttribute is used instead of Attribute, which could be causing the problem. 

This suggests that the model name has changed from Attribute to MispAttribute in the new version, but the rest of the code still seems to refer to Attribute. This could generate confusion and potentially be the cause of the error. 

Steps to resolve: The model needs to be standardized: Modify the references from Attribute to MispAttribute in the app/Controller/EventsController.php file

Original EventsController.php

```
public function freeTextImport($id, $adhereToWarninglists = false, $returnMetaAttributes = false)
    {
        $this->request->allowMethod(['post', 'get']);

        $event = $this->Event->fetchSimpleEvent($this->Auth->user(), $id);
        if (empty($event)) {
            throw new NotFoundException(__('Invalid event.'));
        }
        $this->set('event_id', $event['Event']['id']);
        if ($this->request->is('get')) {
            $this->layout = false;
            $this->request->data['MispAttribute']['event_id'] = $event['Event']['id'];

        } else if ($this->request->is('post')) {
            App::uses('ComplexTypeTool', 'Tools');
            $complexTypeTool = new ComplexTypeTool();
            $this->loadModel('Warninglist');
            $complexTypeTool->setTLDs($this->Warninglist->fetchTLDLists());
            $complexTypeTool->setSecurityVendorDomains($this->Warninglist->fetchSecurityVendorDomains());
            if (!isset($this->request->data['Attribute'])) {
                $this->request->data = array('Attribute' => $this->request->data);
            }
            if (!isset($this->request->data['Attribute']['value'])) {
                $this->request->data['Attribute'] = array('value' => $this->request->data['Attribute']);
            }
            if (isset($this->request->data['Attribute']['adhereToWarninglists'])) {
                $adhereToWarninglists = $this->request->data['Attribute']['adhereToWarninglists'];
            }
            $resultArray = $complexTypeTool->checkFreeText($this->request->data['Attribute']['value']);
            foreach ($resultArray as &$attribute) {
                $attribute['to_ids'] = $this->Event->Attribute->typeDefinitions[$attribute['default_type']]['to_ids'];
            }
            if ($this->_isRest()) {
                // Keep this 'types' format for rest response, but it is not necessary for UI
                foreach ($resultArray as $key => $r) {
                    $temp = array();
                    foreach ($r['types'] as $type) {
                        $temp[$type] = $type;
                    }
                    $resultArray[$key]['types'] = $temp;
                }
                if ($returnMetaAttributes || !empty($this->request->data['Attribute']['returnMetaAttributes'])) {
                    return $this->RestResponse->viewData($resultArray, $this->response->type());
                } else {
                    return $this->__pushFreetext(
                        $resultArray,
                        $event,
                        isset($this->request->data['Attribute']['distribution']) ? $this->request->data['Attribute']['distribution'] : false,
                        isset($this->request->data['Attribute']['sharing_group_id']) ? $this->request->data['Attribute']['sharing_group_id'] : false,
                        $adhereToWarninglists
                    );
                }
            }
            $this->Event->Attribute->fetchRelated($this->Auth->user(), $resultArray);
            $typeCategoryMapping = [
                'ip-src/ip-dst' => [
                    'Network activity' => 'Network activity',
                    'Payload delivery' => 'Payload delivery',
                    'External analysis' => 'External analysis'
                ],
            ];
            foreach ($this->Event->Attribute->categoryDefinitions as $k => $cat) {
                foreach ($cat['types'] as $type) {
                    $typeCategoryMapping[$type][$k] = $k;
                }
            }
            $distributions = $this->Event->Attribute->distributionLevels;
            $sgs = $this->Event->SharingGroup->fetchAllAuthorised($this->Auth->user(), 'name', 1);
            if (empty($sgs)) {
                unset($distributions[4]);
            }

            $this->set('proposals', !$this->__canModifyEvent($event));
            $this->set('distributions', $distributions);
            $this->set('sgs', $sgs);
            $this->set('event', $event);
            $this->set('mayModify', $this->__canModifyEvent($event));
            $this->set('typeDefinitions', $this->Event->Attribute->typeDefinitions);
            $this->set('typeCategoryMapping', $typeCategoryMapping);
            $this->set('defaultAttributeDistribution', $this->Event->Attribute->defaultDistribution());
            $this->set('resultArray', $resultArray);
            $this->set('importComment', '');
            $this->set('title_for_layout', __('Freetext Import Results'));
            $this->set('title', __('Freetext Import Results'));
            $this->set('missingTldLists', $this->Warninglist->missingTldLists());
            $this->render('resolved_attributes');
        }
    }
```

Fixed EventsController.php

```
public function freeTextImport($id, $adhereToWarninglists = false, $returnMetaAttributes = false)
    {
        $this->request->allowMethod(['post', 'get']);

        $event = $this->Event->fetchSimpleEvent($this->Auth->user(), $id);
        if (empty($event)) {
            throw new NotFoundException(__('Invalid event.'));
        }
        $this->set('event_id', $event['Event']['id']);
        if ($this->request->is('get')) {
            $this->layout = false;
            $this->request->data['MispAttribute']['event_id'] = $event['Event']['id'];

        } else if ($this->request->is('post')) {
            App::uses('ComplexTypeTool', 'Tools');
            $complexTypeTool = new ComplexTypeTool();
            $this->loadModel('Warninglist');
            $complexTypeTool->setTLDs($this->Warninglist->fetchTLDLists());
            $complexTypeTool->setSecurityVendorDomains($this->Warninglist->fetchSecurityVendorDomains());
            if (!isset($this->request->data['MispAttribute'])) {
                $this->request->data = array('MispAttribute' => $this->request->data);
            }
            if (!isset($this->request->data['MispAttribute']['value'])) {
                $this->request->data['MispAttribute'] = array('value' => $this->request->data['MispAttribute']);
            }
            if (isset($this->request->data['MispAttribute']['adhereToWarninglists'])) {
                $adhereToWarninglists = $this->request->data['MispAttribute']['adhereToWarninglists'];
            }
            $resultArray = $complexTypeTool->checkFreeText($this->request->data['MispAttribute']['value']);
            foreach ($resultArray as &$attribute) {
                $attribute['to_ids'] = $this->Event->Attribute->typeDefinitions[$attribute['default_type']]['to_ids'];
            }
            if ($this->_isRest()) {
                // Keep this 'types' format for rest response, but it is not necessary for UI
                foreach ($resultArray as $key => $r) {
                    $temp = array();
                    foreach ($r['types'] as $type) {
                        $temp[$type] = $type;
                    }
                    $resultArray[$key]['types'] = $temp;
                }
                if ($returnMetaAttributes || !empty($this->request->data['MispAttribute']['returnMetaAttributes'])) {
                    return $this->RestResponse->viewData($resultArray, $this->response->type());
                } else {
                    return $this->__pushFreetext(
                        $resultArray,
                        $event,
                        isset($this->request->data['MispAttribute']['distribution']) ? $this->request->data['MispAttribute']['distribution'] : false,
                        isset($this->request->data['MispAttribute']['sharing_group_id']) ? $this->request->data['MispAttribute']['sharing_group_id'] : false,
                        $adhereToWarninglists
                    );
                }
            }
            $this->Event->Attribute->fetchRelated($this->Auth->user(), $resultArray);
            $typeCategoryMapping = [
                'ip-src/ip-dst' => [
                    'Network activity' => 'Network activity',
                    'Payload delivery' => 'Payload delivery',
                    'External analysis' => 'External analysis'
                ],
            ];
            foreach ($this->Event->Attribute->categoryDefinitions as $k => $cat) {
                foreach ($cat['types'] as $type) {
                    $typeCategoryMapping[$type][$k] = $k;
                }
            }
            $distributions = $this->Event->Attribute->distributionLevels;
            $sgs = $this->Event->SharingGroup->fetchAllAuthorised($this->Auth->user(), 'name', 1);
            if (empty($sgs)) {
                unset($distributions[4]);
            }

            $this->set('proposals', !$this->__canModifyEvent($event));
            $this->set('distributions', $distributions);
            $this->set('sgs', $sgs);
            $this->set('event', $event);
            $this->set('mayModify', $this->__canModifyEvent($event));
            $this->set('typeDefinitions', $this->Event->Attribute->typeDefinitions);
            $this->set('typeCategoryMapping', $typeCategoryMapping);
            $this->set('defaultAttributeDistribution', $this->Event->Attribute->defaultDistribution());
            $this->set('resultArray', $resultArray);
            $this->set('importComment', '');
            $this->set('title_for_layout', __('Freetext Import Results'));
            $this->set('title', __('Freetext Import Results'));
            $this->set('missingTldLists', $this->Warninglist->missingTldLists());
            $this->render('resolved_attributes');
        }
    }
```

It is also necessary to update the references in the file app/View/Events/free_text_import.ctp to use MispAttribute instead of Attribute.


Original free_text_import.ctp

`<?= $this->Form->create('Attribute', array('id')); ?>
`
Fixed free_text_import.ctp

`<?= $this->Form->create('MispAttribute', array('id')); ?>`

Run docker compose down and docker compose up -d and verify that the free text import function works correctly.

**Comment by theice9c** [comment]
Fixed with https://github.com/MISP/MISP/issues/9951
