### ISSUE TITLE
Bug: INSTALL on Ubuntu 24.04 fails

### ISSUE THREAD

**Issue by uforia** [MISP/MISP#9999]
### Actual behavior

During the installation on an Ubuntu 24.04.01 LTS system, INSTALLER fails during MISP updates with:

```
[STATUS] Running MISP updates
Error: Database connection "MysqlObserverExtended" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3660): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1163): Model->setDataSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3687): Model->setSource()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1395): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(782): BehaviorCollection->init()
#10 /var/www/MISP/app/Model/AppModel.php(114): Model->__construct()
#11 /var/www/MISP/app/Model/User.php(255): AppModel->__construct()
#12 [internal function]: User->__construct()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(315): ClassRegistry::init()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#17 /var/www/MISP/app/Console/Command/AppShell.php(53): Shell->initialize()
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#20 /var/www/MISP/app/Console/cake.php(47): ShellDispatcher::run()
```

After the background workers setup and the 'settings configured', the installer attempts to ingest JSON structures, and this causes a hard error:

```
[STATUS] Ingesting JSON structures
[ERROR] JSON structures ingestion failed. Please check /var/log/misp_install.log for more details.
```

The install.log at that point is filled with similar errors:

```
Error: Database connection "MysqlObserverExtended" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3660): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1163): Model->setDataSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3687): Model->setSource()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1395): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(782): BehaviorCollection->init()
#10 /var/www/MISP/app/Model/AppModel.php(114): Model->__construct()
#11 /var/www/MISP/app/Model/User.php(255): AppModel->__construct()
#12 [internal function]: User->__construct()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#14 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(279): ClassRegistry::init()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(782): BehaviorCollection->init()
#18 /var/www/MISP/app/Model/AppModel.php(114): Model->__construct()
#19 [internal function]: AppModel->__construct()
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(315): ClassRegistry::init()
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#24 /var/www/MISP/app/Console/Command/AppShell.php(53): Shell->initialize()
#25 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize()
#26 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#27 /var/www/MISP/app/Console/cake.php(47): ShellDispatcher::run()
#28 {main}
```

### Expected behavior

The install should complete normally.

### Steps to reproduce

Start a clean install or restart an errored out existing install:

```
pecl uninstall brotli simdjson zstd
rm -rf /var/www/MISP /var/www/.cache
./INSTALL.ubuntu2404.sh
```

### Version

2.5

### Operating System

Ubuntu

### Operating System version

24.04.01

### PHP version

8.3

### Browser

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ronaldocherokee** [comment]
The same issue

**Comment by iglocska** [comment]
Anything in  `/var/log/misp_install.log`? Sounds like something went wrong with creating the MISP db in the first place or perhaps even the misp DB user in mariadb.

**Comment by iglocska** [comment]
The issue pasted above is already a symptom of the error not the actual error please share the fill misp_install.log file instead.

**Comment by Kelvinloucosta** [comment]
The same issue

**Comment by uforia** [comment]
[misp_install.log](https://github.com/user-attachments/files/17653118/misp_install.log)

Please see the attached misp_install.log file. Is it possible to provide a workaround/fix for this? It's a showstopper currently.

**Comment by uforia** [comment]
I've resolved this by manually completely wiping and doing a clean install of everything. Would it be possible to add a feature to the installer to 'clean up' after a failed install?

**Comment by mbell85** [comment]
> I've resolved this by manually completely wiping and doing a clean install of everything. Would it be possible to add a feature to the installer to 'clean up' after a failed install?

@uforia Would you be able tell me what all you wiped?

**Comment by uforia** [comment]
> > I've resolved this by manually completely wiping and doing a clean install of everything. Would it be possible to add a feature to the installer to 'clean up' after a failed install?
> 
> @uforia Would you be able tell me what all you wiped?

Basically everything that the install script had done up to that point, including (but not limited to):

- pecl packages
- MySQL database and the corresponding user entries in mysql.user, .db, etc.
- directories created (e.g. /var/www/MISP)

The installer does not cleanly handle existing information, from what I can tell.

**Comment by mbell85** [comment]
> > > I've resolved this by manually completely wiping and doing a clean install of everything. Would it be possible to add a feature to the installer to 'clean up' after a failed install?
> > 
> > 
> > @uforia Would you be able tell me what all you wiped?
> 
> Basically everything that the install script had done up to that point, including (but not limited to):
> 
> * pecl packages
> * MySQL database and the corresponding user entries in mysql.user, .db, etc.
> * directories created (e.g. /var/www/MISP)
> 
> The installer does not cleanly handle existing information, from what I can tell.

Thanks!

**Comment by mbell85** [comment]
Tried clearing everything I could find, but still running into trouble during install, same issue as originally reported. I second @uforia's request. :) Appreciate all the hard work and love that goes into this project.

**Comment by mbell85** [comment]
Gave it another shot today and got as far as Ingesting JSON structures, which failed. Link to misp_install.log is below. Any help appreciated: 

[https://1drv.ms/u/s!ArIVUTuSUo0_g4123hpZj6fw2tCzpA?e=VdpdcP](url)

**Comment by uforia** [comment]
> Gave it another shot today and got as far as Ingesting JSON structures, which failed. Link to misp_install.log is below. Any help appreciated:
> 
> [https://1drv.ms/u/s!ArIVUTuSUo0_g4123hpZj6fw2tCzpA?e=VdpdcP](url)

From what I see in the logs, the installer is unable to create a database connection. 

Did you:

- Remove all existing users/dbs/tables/etc. before running the installer, perhaps from a previous install?
- Check if the database server is running?
- Check if the user/pass in the install script are correct?

**Comment by mbell85** [comment]
Hey @uforia! I've purged both mysql and mariadb server and client installs on the machine before restarting the install. After running the installer, I can see mariadb is running and see a Warning: Access denied for `'username'@'localhost' (using password: YES)` The username is an existing user on the machine.

**Comment by uforia** [comment]
> Hey @uforia! I've purged both mysql and mariadb server and client installs on the machine before restarting the install. After running the installer, I can see mariadb is running and see a Warning: Access denied for `'username'@'localhost' (using password: YES)` The username is an existing user on the machine.

That suggests that the specified username/password are incorrrect, or you might not have 'flushed privileges' (`flush_privileges`) before attempting the install. Also, you do not need to purge the server/client installs: instead you need to drop the actual MISP database and mysql user/db table entries from the mysql database to try again. Note: don't 'drop' the mysql database!

**Comment by mbell85** [comment]
Finally got it installed! Thanks much for your help @uforia! For some reason, I needed to have a root passwd set for mysql instead of leaving it blank for it to work correctly.

**Comment by dogoniyat** [comment]
It fails the exact same way on all distributions, all the scripts assume you're starting from a clean slate and you have the random password that was generated at the previous installation. In my case, the previous installation was a failed attempt to install MISP 2.5 on RHEL9.4, MySQL (MariaDB, to be precise) was installed by the MISP installer with random passwords. I was lucky, this VM is used only for MISP so I can "clean the slate" with simply:
```
dnf remove mariadb
rm -rf /etc/my.cnf.d
rm -rf /var/lib/mysql
```
and retry an installation.

However, a "safer" approach in the installation scripts, as a prerequisite is to have privileged access to the system (i.e. being root or listed in the sudoers), would be to connect to the 'mysql' database as root and perform the adequate "delete from" and "drop database" statements before starting trying to create the new database and the misp_admin user. Just a suggestion...

After solving the proxy-related issues (composer-install is not friendly with http proxies), I spent another half day figuring out why the site was reporting an internal error. The logs are not too obvious to find, there (it's in /var/www/MISP/webroot/tmp/logs/), you quickly get a bitter feeling of the entire thing, let me not elaborate on that.
